### ISSUE TITLE
datetime module error in SimpleHoster

### ISSUE THREAD

**Issue by de666** [pyload/pyload#1039]
I receive the following error downloading from Easybytez but I think it is related to some missing import statement in the SimpleHoster plugin

```
pyLoad 0.4.9 Debug Report of EasybytezCom 0.23 

TRACEBACK:
 Traceback (most recent call last):
  File "/opt/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/opt/pyload/module/plugins/Plugin.py", line 237, in preprocessing
    return self.process(self.pyfile)
  File "/var/lib/pyload/userplugins/internal/SimpleHoster.py", line 430, in process
    self.handleFree(pyfile)
  File "/var/lib/pyload/userplugins/internal/XFSHoster.py", line 102, in handleFree
    self.checkErrors()
  File "/var/lib/pyload/userplugins/internal/XFSHoster.py", line 221, in checkErrors
    delay   = secondsToMidnight(gmt=2)
  File "/var/lib/pyload/userplugins/internal/SimpleHoster.py", line 171, in secondsToMidnight
    now = datetime.utcnow() + timedelta(hours=gmt)
NameError: global name 'datetime' is not defined
```

**Comment by vuolter** [comment]
@de666 Thanks for reporting. :)
