### ISSUE TITLE
Problem with Uploadablech  

### ISSUE THREAD

**Issue by Enrico68** [pyload/pyload#1077]
I have a premium account with Uploadablech but whenever I try to download I have the following error 

```
File "/Users/enricopirani/Downloads/pyload/module/network/HTTPRequest.py", line 279, in write 
raise Exception("Loaded Url exceeded limit")
Exception: Loaded Url exceeded limit 25.01.2015 09:21:35 ERROR     pycurl error 23: Failed writing body (0 != 2856)
UnSkipOnFail: Looking for skipped duplicates of: faxkme.rar (pid:12)
25.01.2015 09:21:35 INFO  UnSkipOnFail: No duplicates found 
````

**Comment by vuolter** [comment]
Debug log please or sample url if it's not a premium download.

**Comment by Enrico68** [comment]
```
00:14:56 DEBUG     Run Info Fetching for UploadableCh                                                                   0:11
26.01.2015 00:14:56 INFO      Added package Classic containing 1 links
26.01.2015 00:14:57 INFO      Download starts: http://www.uploadable.ch/file/CgnXD7rsESaP/roaxkem.rar
26.01.2015 00:14:57 DEBUG     UploadableCh: File info (BEFORE): {}
26.01.2015 00:14:57 DEBUG     Finished Info Fetching for UploadableCh
26.01.2015 00:14:58 DEBUG     UploadableCh: File info (AFTER): {'status': 2, 'url': u'http://www.uploadable.ch/file/CgnXD7rsESaP', 'size': 333090652.16, 'name
': u'roaxkem.rar', 'pattern': {'S': u'317.66', 'U': u'MB', 'ID': u'CgnXD7rsESaP', 'N': u'roaxkem.rar'}}
26.01.2015 00:14:58 DEBUG     UploadableCh: File name: roaxkem.rar | File size: 333090652
26.01.2015 00:14:58 DEBUG     UploadableCh: File status: online | File info: {'status': 2, 'url': u'http://www.uploadable.ch/file/CgnXD7rsESaP', 'size': 33309
0652.16, 'name': u'roaxkem.rar', 'pattern': {'S': u'317.66', 'U': u'MB', 'ID': u'CgnXD7rsESaP', 'N': u'roaxkem.rar'}}
26.01.2015 00:14:58 DEBUG     UploadableCh: Looking for direct download link...
26.01.2015 00:14:58 DEBUG     UploadableCh: Redirect #0 to: http://www.uploadable.ch/file/CgnXD7rsESaP
26.01.2015 00:14:59 DEBUG     UploadableCh: Direct download link not found
Traceback (most recent call last):
  File "/Users/enricopirani/Downloads/pyload/module/network/HTTPRequest.py", line 279, in write
    raise Exception("Loaded Url exceeded limit")
Exception: Loaded Url exceeded limit
26.01.2015 00:15:02 DEBUG     pycurl exception 23: Failed writing body (0 != 2856)
26.01.2015 00:15:02 ERROR     pycurl error 23: Failed writing body (0 != 2856)
Traceback (most recent call last):
  File "/Users/enricopirani/Downloads/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/Users/enricopirani/Downloads/pyload/module/plugins/Plugin.py", line 237, in preprocessing
    return self.process(self.pyfile)
  File "/Users/enricopirani/Downloads/pyload/module/plugins/internal/SimpleHoster.py", line 480, in process
    self.preload()
  File "/Users/enricopirani/Downloads/pyload/module/plugins/internal/SimpleHoster.py", line 457, in preload
    self.html = self.load(self.pyfile.url, cookies=bool(self.COOKIES), decode=not self.TEXT_ENCODING)
  File "/Users/enricopirani/Downloads/pyload/module/plugins/Plugin.py", line 415, in load
    res = self.req.load(url, get, post, ref, cookies, just_header, decode=decode)
  File "/Users/enricopirani/Downloads/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/Users/enricopirani/Downloads/pyload/module/network/HTTPRequest.py", line 203, in load
    self.c.perform()
error: (23, 'Failed writing body (0 != 2856)')
26.01.2015 00:15:02 INFO      Debug Report written to debug_UploadableCh_26-01-2015_00-15-02.zip
26.01.2015 00:15:02 INFO      UnSkipOnFail: Looking for skipped duplicates of: roaxkem.rar (pid:1)
26.01.2015 00:15:02 INFO      UnSkipOnFail: No duplicates found
26.01.2015 00:15:02 DEBUG     All downloads processed
~/Downloads/pyload%=>

```

**Comment by vuolter** [comment]
Okay, the download link was not propely recognized. If you could share you account with me, I need to inspect the download request to fix this issue. Thx. (my email is: vuolter@gmail.com)

**Comment by vuolter** [comment]
@Enrico68 Works now?

**Comment by Enrico68** [comment]
Yes now is working.. I don't know why
