### ISSUE TITLE
ClickAndLoad - No Socket is opened

### ISSUE THREAD

**Issue by nomad71** [pyload/pyload#1084]
Hi!
Since my ClickAndLoad.py was updated to 0.30 it stopped working. There had been substantial changes lately. Im now at 0.31, but that didn't help.

There is no log, but pyLoadCore threw the following exception, when another device tried to connect to the port 9666 on the server that is running pyLoad:

```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/home/pi/.pyload/userplugins/hooks/ClickAndLoad.py", line 108, in server
    client_socket = create_connection(("127.0.0.1", webport))
  File "/home/pi/.pyload/userplugins/hooks/ClickAndLoad.py", line 24, in create_connection
    return socket.create_connection(address, timeout, source_address)
  File "/usr/lib/python2.7/socket.py", line 559, in create_connection
    sock.settimeout(timeout)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: a float is required
```

I saw that the changes were made for Python 2.5 - as you can see, im running python 2.7(.3).

Thank you!

**Comment by vuolter** [comment]
Checking...

**Comment by vuolter** [comment]
Please, try replacing manually your userplugins/hooks/ClickAndLoad.py with https://raw.githubusercontent.com/pyload/pyload/49397d8e52e7c68a4ce3c1eb74792e23d79f3ebb/module/plugins/hooks/ClickAndLoad.py, then restart pyLoad.

**Comment by nomad71** [comment]
Awesome! Working fine again!
Thank you for the quick reply!

**Comment by krichter722** [comment]
I experienced the same issue and verified that the fix @vuolter referenced works. You might consider changing `Issue not reproduced` to something like `Fixed`.
