### ISSUE TITLE
ExtractArchive.py 1.20 new problem

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#1120]
when i start pyload...this message appears

31.01.2015 23:29:58 ERROR     Fehler beim importieren von UnRar: invalid syntax (UnRar.py, line 180)
Traceback (most recent call last):
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/root/.pyload/userplugins/internal/UnRar.py", line 180
    files.extend(glob(file))
        ^
SyntaxError: invalid syntax
31.01.2015 23:29:58 WARNING   ExtractArchive: Konnte UnRar nicht aktivieren | 'NoneType' object has no attribute 'UnRar'
Traceback (most recent call last):
  File "/root/.pyload/userplugins/hooks/ExtractArchive.py", line 149, in setup
    klass  = getattr(module, p)
AttributeError: 'NoneType' object has no attribute 'UnRar'
31.01.2015 23:29:58 DEBUG     Redirected import module.plugins.internal.SevenZip -> userplugins.internal.SevenZip
31.01.2015 23:29:58 DEBUG     Redirected import module.plugins.internal.UnRar -> userplugins.internal.UnRar
31.01.2015 23:29:58 ERROR     Fehler beim importieren von SevenZip: invalid syntax (UnRar.py, line 180)
Traceback (most recent call last):
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/root/.pyload/userplugins/internal/SevenZip.py", line 8, in <module>
    from module.plugins.internal.UnRar import ArchiveError, CRCError, PasswordError, UnRar, renice
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/root/.pyload/userplugins/internal/UnRar.py", line 180
    files.extend(glob(file))
        ^
SyntaxError: invalid syntax
31.01.2015 23:29:58 WARNING   ExtractArchive: Konnte SevenZip nicht aktivieren | 'NoneType' object has no attribute 'SevenZip'
Traceback (most recent call last):
  File "/root/.pyload/userplugins/hooks/ExtractArchive.py", line 149, in setup
    klass  = getattr(module, p)
AttributeError: 'NoneType' object has no attribute 'SevenZip'
31.01.2015 23:29:58 DEBUG     Redirected import module.plugins.internal.UnZip -> userplugins.internal.UnZip
31.01.2015 23:29:58 ERROR     Fehler beim importieren von UnZip: invalid syntax (UnZip.py, line 35)
Traceback (most recent call last):
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/root/.pyload/userplugins/internal/UnZip.py", line 35
    badfile = z.testzip():
                         ^
SyntaxError: invalid syntax
31.01.2015 23:29:58 WARNING   ExtractArchive: Konnte UnZip nicht aktivieren | 'NoneType' object has no attribute 'UnZip'
Traceback (most recent call last):
  File "/root/.pyload/userplugins/hooks/ExtractArchive.py", line 149, in setup
    klass  = getattr(module, p)
AttributeError: 'NoneType' object has no attribute 'UnZip'
31.01.2015 23:29:58 INFO      ExtractArchive: Keine Entpackplugins aktiviert

**Comment by Gutz-Pilz** [comment]
ok message in the front is gone. thx!!!

but this happens when i a package should get extracted

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/root/.pyload/userplugins/hooks/ExtractArchive.py", line 256, in extract
    if filter(lambda ext: fname.lower().endswith(ext), extensions)]
UnboundLocalError: local variable 'fid' referenced before assignment

31.01.2015 23:43:06 DEBUG     All downloads processed
31.01.2015 23:43:06 DEBUG     ExtractArchive: Extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
31.01.2015 23:43:06 INFO      ExtractArchive: Check package: 0xd910l0f2xlj7k
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/root/.pyload/userplugins/hooks/ExtractArchive.py", line 194, in allDownloadsProcessed
    if self.extract(self.queue.get()):  #@NOTE: check only if all gone fine, no failed reporting for now
  File "/root/.pyload/userplugins/hooks/ExtractArchive.py", line 256, in extract
    if filter(lambda ext: fname.lower().endswith(ext), extensions)]
UnboundLocalError: local variable 'fid' referenced before assignment

**Comment by Gutz-Pilz** [comment]
new error ;)

ExtractArchive: Extracted files: [u'Downloads/John Wick/John.Wick.German.DL.AC3.Dubbed.720p.BluRay.x264.iNTERNAL-PsO', u'Downloads/John Wick/John.Wick.German.DL.AC3.Dubbed.720p.BluRay.x264.iNTERNAL-PsO/Sample/pso-john.wick_720p-sample.mkv', u'Downloads/John Wick/John.Wick.German.DL.AC3.Dubbed.720p.BluRay.x264.iNTERNAL-PsO/pso-john.wick_720p.mkv', u'Downloads/John Wick/John.Wick.German.DL.AC3.Dubbed.720p.BluRay.x264.iNTERNAL-PsO/Sample']
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/root/.pyload/userplugins/hooks/ExtractArchive.py", line 194, in allDownloadsProcessed
    if self.extract(self.queue.get()):  #@NOTE: check only if all gone fine, no failed reporting for now
  File "/root/.pyload/userplugins/hooks/ExtractArchive.py", line 329, in extract
    self.queue.remove(pid)
  File "/root/.pyload/userplugins/hooks/ExtractArchive.py", line 94, in remove
    queue.pop(item, None)
TypeError: pop() takes at most 1 argument (2 given)

**Comment by vuolter** [comment]
Too later: already fixed here https://github.com/pyload/pyload/commit/8bda0302c7a9452a1828ec9c9e2f60901d25e3c5! :p

**Comment by Gutz-Pilz** [comment]
now works. 
Found another issue
plugins is only deleting one file after successful extraction :)

**Comment by vuolter** [comment]
@Gutz-Pilz Debug log is the way.
