### ISSUE TITLE
Issue with Fshare.vn 

### ISSUE THREAD

**Issue by hunghv1413** [pyload/pyload#1133]
Can't login with Fshare account Premium
Log:
BadHeader: Bad server response: 400 Bad Request
02.02.2015 17:23:39 DEBUG     FshareVn: Scheduled Account refresh for hunghv1413@gmail.com in 0 seconds.
02.02.2015 17:23:39 DEBUG     FshareVn: Get Account Info for hunghv1413@gmail.com
02.02.2015 17:23:40 DEBUG     FshareVn: Account Info: {'premium': False, 'validuntil': None, 'trafficleft': None}
02.02.2015 17:24:46 WARNING   FshareVn: Could not login with account hunghv1413@gmail.com | Bad server response: 400 Bad Request
Traceback (most recent call last):
  File "/root/Downloads/pyload/module/plugins/Account.py", line 82, in _login
    self.login(user, data, req)
  File "/root/.pyload/userplugins/accounts/FshareVn.py", line 55, in login
    referer=True,
  File "/root/Downloads/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/root/Downloads/pyload/module/network/HTTPRequest.py", line 208, in load
    self.code = self.verifyHeader()
  File "/root/Downloads/pyload/module/network/HTTPRequest.py", line 222, in verifyHeader
    raise BadHeader(code, self.getResponse())
BadHeader: Bad server response: 400 Bad Request

**Comment by vuolter** [comment]
Refer to: https://github.com/pyload/pyload/issues/932
