### ISSUE TITLE
FastCGI Error: Exception on start-up

### ISSUE THREAD

**Issue by ItachiSan** [pyload/pyload#1145]
Hello,
as in title, when starting up PyLoad using FastCGI as webinterface, I've the following error code:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/share/pyload/module/web/ServerThread.py", line 69, in run
    self.start_fcgi()
  File "/usr/share/pyload/module/web/ServerThread.py", line 98, in start_fcgi
    webinterface.run_fcgi(host=self.host, port=self.port)
  File "/usr/share/pyload/module/web/webinterface.py", line 153, in run_fcgi
    run(app=web, host=host, port=port, server=FlupFCGIServer, quiet=True)
  File "/usr/share/pyload/module/lib/bottle.py", line 2383, in run
    server.run(app)
  File "/usr/share/pyload/module/lib/bottle.py", line 2070, in run
    flup.server.fcgi.WSGIServer(handler, **self.options).run()
  File "/usr/lib/pymodules/python2.7/flup/server/fcgi.py", line 114, in run
    ret = ThreadedServer.run(self, sock)
  File "/usr/lib/pymodules/python2.7/flup/server/threadedserver.py", line 68, in run
    self._installSignalHandlers()
  File "/usr/lib/pymodules/python2.7/flup/server/threadedserver.py", line 153, in _installSignalHandlers
    signal.signal(sig, self._intHandler)
ValueError: signal only works in main thread
```

Apache2 Error log:

```
[Thu Feb 05 11:55:54 2015] [error] [client 192.168.0.112] (111)Connection refused: FastCGI: failed to connect to server "/var/www/pyload.fcgi": connect() failed
[Thu Feb 05 11:55:54 2015] [error] [client 192.168.0.112] FastCGI: incomplete headers (0 bytes) received from server "/var/www/pyload.fcgi"
```

I've no problem with sharing my Apache/pyLoad configs, also I can test. Waiting for a reply.

**Comment by ItachiSan** [comment]
For the message in the PyLoad log, look at: #1156

**Comment by ItachiSan** [comment]
I've changed [webinterface.py](https://github.com/pyload/pyload/blob/stable/module/web/webinterface.py#L153) removing the *quiet=True* option; now I've this log:
```
...
09.02.2015 14:10:13 INFO      Tempo di download: True
09.02.2015 14:10:13 INFO      Avvio ThriftBackend: 0.0.0.0:7227
09.02.2015 14:10:13 INFO      Free space: 45.00 GiB
09.02.2015 14:10:13 INFO      Activating Accounts...
09.02.2015 14:10:13 INFO      Activating Plugins...
09.02.2015 14:10:13 INFO      Starting fastcgi server: 0.0.0.0:1236
09.02.2015 14:10:13 DEBUG     Redirected import module.plugins.internal.UnRar -> userplugins.internal.UnRar
Bottle server starting up (using FlupFCGIServer())...
Listening on http://0.0.0.0:1236/
Hit Ctrl-C to quit.

Shutdown...
09.02.2015 14:10:14 INFO      ExtractArchive: No UnRar installed
09.02.2015 14:10:14 DEBUG     Redirected import module.plugins.internal.SevenZip -> userplugins.internal.SevenZip
09.02.2015 14:10:14 INFO      ExtractArchive: No SevenZip installed
09.02.2015 14:10:14 DEBUG     Redirected import module.plugins.internal.UnZip -> userplugins.internal.UnZip
...
```

Seems like the FastCGI app is closed before startup.

**Comment by wastez** [comment]
So is fastcgi working with your patch? No or?

**Comment by ItachiSan** [comment]
It works, but generates a FastCGI server that is closed in an istant.

**Comment by wastez** [comment]
What means it works if it is closed instantly?
Fastcgi can´t be used if it is closed.

Are you using fastcgi?

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/pull/1156
