### ISSUE TITLE
CzShare hoster plugin makes Config tab unusable

### ISSUE THREAD

**Issue by majklvi** [pyload/pyload#1147]
When the CzShare plugin is updated, it makes Config tab unusable. I see only the text below instead of working Config tab. When CzShare is deleted from userplugins both hosters and account folder and pyLoad is restarted, everything works correctly, until it's downloaded and loaded again.

An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/i-data/780432d9/admin/zy-pkgs/pyLoad/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/i-data/780432d9/admin/zy-pkgs/pyLoad/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/i-data/780432d9/admin/zy-pkgs/pyLoad/pyload/module/web/utils.py", line 113, in _view
return func(*args, **kwargs)
File "/i-data/780432d9/admin/zy-pkgs/pyLoad/pyload/module/web/pyload_app.py", line 256, in config
accs = PYLOAD.getAccounts(False)
File "/i-data/780432d9/admin/zy-pkgs/pyLoad/pyload/module/Api.py", line 875, in getAccounts
accs = self.core.accountManager.getAccountInfos(False, refresh)
File "/i-data/780432d9/admin/zy-pkgs/pyLoad/pyload/module/utils.py", line 165, in new
return func(*args)
File "/i-data/780432d9/admin/zy-pkgs/pyLoad/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
p = self.getAccountPlugin(p)
File "/i-data/780432d9/admin/zy-pkgs/pyLoad/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

**Comment by majklvi** [comment]
the log says:
05.02.2015 16:31:55	ERROR	Error importing CzshareCom: invalid syntax (CzshareCom.py, line 30)
