### ISSUE TITLE
[uploaded.to] Running into download limit with premium account.

### ISSUE THREAD

**Issue by mbosner** [pyload/pyload#1164]
Tested with 767cf1ccb4420e7cb1805bfe302b8909def79679 plus https://github.com/pyload/pyload/pull/1154

Please merge the pull request if you need a test with a later version. Only a restart of pyload fixes that problem.

debug_Report.txt

```
pyLoad 0.4.9 Debug Report of UploadedTo 0.82 

TRACEBACK:
 Traceback (most recent call last):
  File "/data/media/bin/pyloads/immenz/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/data/media/bin/pyloads/immenz/module/plugins/Plugin.py", line 233, in preprocessing
    self.setup()
  File "/data/media/bin/pyloads/immenz/module/plugins/hoster/UploadedTo.py", line 59, in setup
    self.load("http://uploaded.net/language/en", just_header=True)
  File "/data/media/bin/pyloads/immenz/module/plugins/Plugin.py", line 415, in load
    res = self.req.load(url, get, post, ref, cookies, just_header, decode=decode)
  File "/data/media/bin/pyloads/immenz/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/data/media/bin/pyloads/immenz/module/network/HTTPRequest.py", line 210, in load
    self.addCookies()
  File "/data/media/bin/pyloads/immenz/module/network/HTTPRequest.py", line 133, in addCookies
    if self.cj:
AttributeError: HTTPRequest instance has no attribute 'cj'
 

FRAMESTACK:

Frame preprocessing in /data/media/bin/pyloads/immenz/module/plugins/Plugin.py at line 233
	                self = <module.plugins.hoster.UploadedTo.UploadedTo object at 0x7f74dc4e4050>
	              thread = <DownloadThread(Thread-7, started daemon 140140731156224)>

Frame setup in /data/media/bin/pyloads/immenz/module/plugins/hoster/UploadedTo.py at line 59
	                self = <module.plugins.hoster.UploadedTo.UploadedTo object at 0x7f74dc4e4050>

Frame load in /data/media/bin/pyloads/immenz/module/plugins/Plugin.py at line 415
	             cookies = True
	                 get = {}
	                 url = 'http://uploaded.net/language/en'
	                self = <module.plugins.hoster.UploadedTo.UploadedTo object at 0x7f74dc4e4050>
	              decode = False
	         just_header = True
	                post = {}
	                 ref = True

Frame load in /data/media/bin/pyloads/immenz/module/network/Browser.py at line 97
	                self = <module.network.Browser.Browser object at 0x7f74dc49dd50>
	                args = ('http://uploaded.net/language/en', {}, {}, True, True, True)
	              kwargs = {'decode': False}

Frame load in /data/media/bin/pyloads/immenz/module/network/HTTPRequest.py at line 210
	             cookies = True
	                 get = {}
	                 url = 'http://uploaded.net/language/en'
	                 rep = 'HTTP/1.1 302 Found\r\nServer: nginx\r\nDate: Mon, 09 Feb 2015 18:15:08 GMT\r\nContent-Type: text/html\r\nContent-Length: 20\r\nConnection: keep-alive\r\nExpires: Thu, 19 Nov 1981 08:52:00 GMT\r\nCache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0\r\nPragma: no-cache\r\nLocation: /\r\nVary: Accept-Encoding\r\nContent-Encoding: gzip\r\n\r\n'
	              decode = False
	             referer = True
	           multipart = False
	                post = {}
	                self = <module.network.HTTPRequest.HTTPRequest instance at 0x7f750c065a28>
	         just_header = True

Frame addCookies in /data/media/bin/pyloads/immenz/module/network/HTTPRequest.py at line 133
	                self = <module.network.HTTPRequest.HTTPRequest instance at 0x7f750c065a28>


PLUGIN OBJECT DUMP: 

	             API_KEY = 'lhF2IeeprweDfu9ccWlxXVVypA5nA3EL'
	       CHECK_TRAFFIC = False
	             COOKIES = True
	         DIRECT_LINK = None
	      DL_LIMIT_ERROR = 'You have reached the max. number of possible free downloads for this hour'
	LINK_PREMIUM_PATTERN = '<div class="tfree".*\\s*<form method="post" action="(.+?)"'
	       LOGIN_ACCOUNT = False
	        MULTI_HOSTER = False
	   NAME_REPLACEMENTS = [('&#?\\w+;', <function fixup at 0x7f7523276de8>)]
	   SIZE_REPLACEMENTS = []
	       TEXT_ENCODING = False
	    URL_REPLACEMENTS = [('https?://(?:www\\.)?(uploaded\\.(to|net)|ul\\.to)(/file/|/?\\?id=|.*?&id=|/)(?P<ID>\\w+).*',
  'http://uploaded.net/file/\\g<ID>')]
	        WAIT_PATTERN = 'Current waiting period: <span>(\\d+)'
	             account = <module.plugins.accounts.UploadedTo.UploadedTo object at 0x7f751c08e890>
	               cTask = None
	          chunkLimit = 1
	              config = <module.ConfigParser.ConfigParser instance at 0x7f751e0015f0>
	                core = <__main__.Core object at 0x7f751dff1dd0>
	                html = None
	                  js = <module.common.JsEngine.JsEngine instance at 0x7f751c67d5a8>
	           lastCheck = None
	        lastDownload = ''
	             limitDL = 0
	                 log = <logging.Logger object at 0x7f751e4c7ed0>
	             multiDL = True
	                 ocr = None
	             premium = True
	                 req = <module.network.Browser.Browser object at 0x7f74dc49dd50>
	      resumeDownload = True
	             retries = 0
	              thread = <DownloadThread(Thread-2, stopped daemon 140140981438208)>
	                user = '0000001'
	           waitUntil = 0
	             waiting = False
	       wantReconnect = False

PYFILE OBJECT DUMP: 

	               _size = 0
	               abort = False
	              active = False
	               error = "HTTPRequest instance has no attribute 'cj'"
	                  id = 9495
	                lock = <_RLock owner=None count=0>
	                   m = <module.database.FileDatabase.FileHandler instance at 0x7f751dfd0dd0>
	         maxprogress = 100
	                name = u'http://ul.to/l1zpsa3n'
	               order = 0
	           packageid = 260
	              plugin = <module.plugins.hoster.UploadedTo.UploadedTo object at 0x7f74dc4e4050>
	         pluginclass = <class 'module.plugins.hoster.UploadedTo.UploadedTo'>
	        pluginmodule = <module 'module.plugins.hoster.UploadedTo' from '/data/media/bin/pyloads/immenz/module/plugins/hoster/UploadedTo.pyc'>
	          pluginname = u'UploadedTo'
	            progress = 0
	         reconnected = False
	                size = 0
	              status = 8
	          statusname = None
	                 url = u'http://ul.to/l1zpsa3n'
	           waitUntil = 0
```

fileUrl_line156.dump.html

```
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 09 Feb 2015 18:15:05 GMT
Content-Type: application/x-rar-compressed
Content-Length: 50654868
Last-Modified: Thu, 20 Nov 2014 02:25:26 GMT
Connection: keep-alive
Content-Disposition: attachment; filename="BS.S03E10.German.DD51.DL.1080.p.BD.x.264-TVS.part40.rar"
ETag: "546d5116-304ee94"
Accept-Ranges: bytes
```

setup_line59.dump.html

```
HTTP/1.1 302 Found
Server: nginx
Date: Mon, 09 Feb 2015 18:14:59 GMT
Content-Type: text/html
Content-Length: 20
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Location: /
Vary: Accept-Encoding
Content-Encoding: gzip
```

**Comment by mbosner** [comment]
Seems that this is a uploaded traffic counting problem. Unfixable in pyload.
