### ISSUE TITLE
XMPP disconnects after ~2 hours

### ISSUE THREAD

**Issue by LukasKalbertodt** [pyload/pyload#1165]
The XMPP hook somehow disconnects after approx. 2 hours of working without a problem. There is only one line in the log file:

    ERROR     XMPPInterface: pyLoad XMPP: IO Error: [Errno 32] Broken pipe

After that the XMPPInterface does not recieve or send any messages. But it still tries to do so and prints messages to the log file saying "Send message to [...]" or something... I think this the same bug: http://forum.pyload.org/viewtopic.php?f=12&t=3374
Btw: I am using twattle.net as jabber server.

EDIT: Additional information. Actually the error occured right after it tried to send a message.

    13:46:30 INFO      Download finished:  <filename>
    13:46:30 DEBUG     XMPPInterface: pyLoad XMPP: Send message to <myid>@twattle.net
    13:46:30 ERROR     XMPPInterface: pyLoad XMPP: IO Error: [Errno 32] Broken pipe

**Comment by don-philipe** [comment]
I think the server kills the connection if the client doesnt answer his pings for some time.
According to [this](http://www.softhinker.com/in-the-news/respondtoxmpppingtokeepidleclientalive) blogpost, that behaviour can be avoided with implementing a respond to the pings of the server.

**Comment by GammaC0de** [comment]
@LukasKalbertodt @don-philipe I cannot test it myself so, can you test this version (You will have to edit the plugin config and set the `keepalive interval` to something other then zero) and report back?

```python
# -*- coding: utf-8 -*-

import pyxmpp

from pyxmpp.jabber.client import JabberClient

from module.plugins.hooks.IRC import IRC


class XMPP(IRC, JabberClient):
    __name__    = "XMPP"
    __type__    = "hook"
    __version__ = "0.16"
    __status__  = "testing"

    __config__ = [("activated", "bool", "Activated"                           , False                                    ),
                  ("jid"      , "str" , "Jabber ID"                           , "user@exmaple-jabber-server.org"         ),
                  ("pw"       , "str" , "Password"                            , ""                                       ),
                  ("tls"      , "bool", "Use TLS"                             , False                                    ),
                  ("owners"   , "str" , "List of JIDs accepting commands from", "me@icq-gateway.org;some@msn-gateway.org"),
                  ("keepalive", "int" , "keepalive interval. 0 to disable"    , 0                                        ),
                  ("info_file", "bool", "Inform about every file finished"    , False                                    ),
                  ("info_pack", "bool", "Inform about every package finished" , True                                     ),
                  ("captcha"  , "bool", "Send captcha requests"               , True                                     )]

    __description__ = """Connect to jabber and let owner perform different tasks"""
    __license__     = "GPLv3"
    __authors__     = [("RaNaN", "RaNaN@pyload.org")]


    pyxmpp.interface.implements(IMessageHandlersProvider)


    def __init__(self, *args, **kwargs):
        IRC.__init__(self, *args, **kwargs)

        self.jid = pyxmpp.all.JID(self.config.get('jid'))
        password = self.config.get('pw')

        #: If bare JID is provided add a resource -- it is required
        if not self.jid.resource:
            self.jid = pyxmpp.all.JID(self.jid.node, self.jid.domain, "pyLoad")

        if self.config.get('tls'):
            tls_settings = pyxmpp.streamtls.TLSSettings(require=True, verify_peer=False)
            auth = ("sasl:PLAIN", "sasl:DIGEST-MD5")
        else:
            tls_settings = None
            auth = ("sasl:DIGEST-MD5", "digest")

        #: Setup client with provided connection information
        #: And identity data
        JabberClient.__init__(self, self.jid, password,
                              disco_name="pyLoad XMPP Client", disco_type="bot",
                              tls_settings=tls_settings, auth_methods=auth, keepalive=self.config.get('keepalive'))

        self.interface_providers = [
            VersionHandler(self),
            self,
        ]


    def activate(self):
        self.new_package = {}

        self.start()


    def package_finished(self, pypack):
        try:
            if self.config.get('info_pack'):
                self.announce(_("Package finished: %s") % pypack.name)

        except Exception:
            pass


    def download_finished(self, pyfile):
        try:
            if self.config.get('info_file'):
                self.announce(
                    _("Download finished: %(name)s @ %(plugin)s") % {'name': pyfile.name, 'plugin': pyfile.pluginname})

        except Exception:
            pass


    def run(self):
        #: Connect to IRC etc.
        self.connect()
        try:
            self.loop()

        except Exception, ex:
            self.log_error(ex)


    def stream_state_changed(self, state, arg):
        """
        This one is called when the state of stream connecting the component
        to a server changes. This will usually be used to let the user
        know what is going on.
        """
        self.log_debug("*** State changed: %s %r ***" % (state, arg))


    def disconnected(self):
        self.log_debug("Client was disconnected")


    def stream_closed(self, stream):
        self.log_debug("Stream was closed", stream)


    def stream_error(self, err):
        self.log_debug("Stream Error", err)


    def get_message_handlers(self):
        """
        Return list of (message_type, message_handler) tuples.

        The handlers returned will be called when matching message is received
        in a client session.
        """
        return [("normal", self.message)]


    def message(self, stanza):
        """
        Message handler for the component.
        """
        subject = stanza.get_subject()
        body = stanza.get_body()
        t = stanza.get_type()
        self.log_debug("Message from %s received." % stanza.get_from())
        self.log_debug("Body: %s Subject: %s Type: %s" % (body, subject, t))

        if t == "headline":
            #: 'headline' messages should never be replied to
            return True
        if subject:
            subject = u"Re: " + subject

        to_jid = stanza.get_from()
        from_jid = stanza.get_to()

        # j = pyxmpp.all.JID()
        to_name = to_jid.as_utf8()
        from_name = from_jid.as_utf8()

        names = self.config.get('owners').split(";")

        if to_name in names or to_jid.node + "@" + to_jid.domain in names:
            messages = []

            trigger = "pass"
            args = None

            try:
                temp = body.split()
                trigger = temp[0]
                if len(temp) > 1:
                    args = temp[1:]

            except Exception:
                pass

            handler = getattr(self, "event_%s" % trigger, self.event_pass)
            try:
                res = handler(args)
                for line in res:
                    m = pyxmpp.all.Message(
                        to_jid=to_jid,
                        from_jid=from_jid,
                        stanza_type=stanza.get_type(),
                        subject=subject,
                        body=line)

                    messages.append(m)

            except Exception, e:
                self.log_error(e, trace=True)

            return messages

        else:
            return True


    def response(self, msg, origin=""):
        return self.announce(msg)


    def announce(self, message):
        """
        Send message to all owners
        """
        for user in self.config.get('owners').split(";"):
            self.log_debug("Send message to", user)

            to_jid = pyxmpp.all.JID(user)

            m = pyxmpp.all.Message(from_jid=self.jid,
                                   to_jid=to_jid,
                                   stanza_type="chat",
                                   body=message)

            stream = self.get_stream()
            if not stream:
                self.connect()
                stream = self.get_stream()

            stream.send(m)


    def before_reconnect(self, ip):
        self.disconnect()


    def after_reconnect(self, ip, oldip):
        self.connect()


class VersionHandler(object):
    """
    Provides handler for a version query.

    This class will answer version query and announce 'jabber:iq:version' namespace
    in the client's disco#info results.
    """
    pyxmpp.interface.implements(IIqHandlersProvider, IFeaturesProvider)


    def __init__(self, client):
        """
        Just remember who created this.
        """
        self.client = client


    def get_features(self):
        """
        Return namespace which should the client include in its reply to a
        disco#info query.
        """
        return ["jabber:iq:version"]


    def get_iq_get_handlers(self):
        """
        Return list of tuples (element_name, namespace, handler) describing
        handlers of <iq type='get'/> stanzas
        """
        return [("query", "jabber:iq:version", self.get_version)]


    def get_iq_set_handlers(self):
        """
        Return empty list, as this class provides no <iq type='set'/> stanza handler.
        """
        return []


    def get_version(self, iq):
        """
        Handler for jabber:iq:version queries.

        jabber:iq:version queries are not supported directly by PyXMPP, so the
        XML node is accessed directly through the libxml2 API.  This should be
        used very carefully!
        """
        iq = iq.make_result_response()
        q = iq.new_query("jabber:iq:version")
        q.newTextChild(q.ns(), "name", "Echo component")
        q.newTextChild(q.ns(), "version", "1.0")
        return iq
```

**Comment by don-philipe** [comment]
I'm currently on stable branch.
I had to change https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/IRC.py#L16 to
`from module.plugins.internal.misc import format_size`
to avoid errors.

Sadly I ran into another error in which the XMPP class says:
`name 'IMessageHandlersProvider' is not defined`
My python knowledge isn't good enough to cope with this :( What could be the problem?
pyxmpp version is 1.1.2-4 on Archlinux.

**Comment by GammaC0de** [comment]
@don-philipe `IRC.py` updated with https://github.com/pyload/pyload/commit/9b789aa6c074d492d6291e68a9645294a6a0cf86.
Also, updated `XMPP.py` in my previous post so try it now please

**Comment by don-philipe** [comment]
@GammaC0de what exactly did you change in `XMPP.py` in your previous post?

**Comment by GammaC0de** [comment]
Basically the `pyxmpp.interface.implements` lines and added import.
Just copy-paste it and retry.

**Comment by don-philipe** [comment]
Needed `from module.plugins.internal.Addon import Addon` in `IRC.py` to get line https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/IRC.py#L44 working and `import pyxmpp.all` in `XMPP.py` to get line https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/XMPP.py#L36 working.

Now the plugin connects to the server and I can send commands. Everything works fine :)
In a couple of hours I will report if the keepalive works or not.

**Comment by don-philipe** [comment]
Plugin still running, no disconnect no timeout.
Thank you very much for that fix :)

**Comment by GammaC0de** [comment]
:+1:

**Comment by GammaC0de** [comment]
Why did you used `import pyxmpp.all`?
Isn't 
```
import pyxmpp
import pyxmpp.interfaces
```
sufficient?

**Comment by don-philipe** [comment]
Without this import I get a warning, that XMPP can't be activated and the following traceback (in debug mode):
```
Traceback (most recent call last):
  File "/opt/pyload/module/HookManager.py", line 130, in createIndex
    plugin = pluginClass(self.core, self)
  File "/opt/pyload/module/plugins/hooks/XMPP.py", line 38, in __init__
    self.jid = pyxmpp.all.JID(self.config.get('jid'))
AttributeError: 'module' object has no attribute 'all'
```
