### ISSUE TITLE
pyload only works in Incognito mode

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#1228]
Does anyone know how to fix this ?

```
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 104, in _view
    if s.get("name", None) and s.get("authenticated", False):
  File "/usr/share/pyload/module/lib/beaker/session.py", line 554, in __getattr__
    return getattr(self._session(), attr)
  File "/usr/share/pyload/module/lib/beaker/session.py", line 550, in _session
    **params)
  File "/usr/share/pyload/module/lib/beaker/session.py", line 105, in __init__
    self.cookie = Cookie.SimpleCookie(input=cookieheader)
  File "/usr/lib/python2.7/Cookie.py", line 579, in __init__
    if input: self.load(input)
  File "/usr/lib/python2.7/Cookie.py", line 632, in load
    self.__ParseString(rawdata)
  File "/usr/lib/python2.7/Cookie.py", line 665, in __ParseString
    self.__set(K, rval, cval)
  File "/usr/lib/python2.7/Cookie.py", line 585, in __set
    M.set(key, real_value, coded_value)
CookieError: Illegal key value: ys-api/channel
An error occured while processing the request.
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 104, in _view
    if s.get("name", None) and s.get("authenticated", False):
  File "/usr/share/pyload/module/lib/beaker/session.py", line 554, in __getattr__
    return getattr(self._session(), attr)
  File "/usr/share/pyload/module/lib/beaker/session.py", line 550, in _session
    **params)
  File "/usr/share/pyload/module/lib/beaker/session.py", line 105, in __init__
    self.cookie = Cookie.SimpleCookie(input=cookieheader)
  File "/usr/lib/python2.7/Cookie.py", line 579, in __init__
    if input: self.load(input)
  File "/usr/lib/python2.7/Cookie.py", line 632, in load
    self.__ParseString(rawdata)
  File "/usr/lib/python2.7/Cookie.py", line 665, in __ParseString
    self.__set(K, rval, cval)
  File "/usr/lib/python2.7/Cookie.py", line 585, in __set
    M.set(key, real_value, coded_value)
CookieError: Illegal key value: ys-api/channel

<h1>Critical error while processing request: </h1><h2>Error:</h2>
<pre>CookieError('Illegal key value: ys-api/channel',)</pre>
<h2>Traceback:</h2>
<pre>Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 820, in wsgi
    out = self._cast(self._handle(environ), request, response)
  File "/usr/share/pyload/module/lib/bottle.py", line 773, in _cast
    out = self.error_handler.get(out.status, repr)(out)
  File "/usr/share/pyload/module/web/pyload_app.py", line 83, in error500
    error.traceback.replace("\n", "<br>") if error.traceback else "No Traceback"])
  File "/usr/share/pyload/module/web/pyload_app.py", line 72, in base
    return render_to_response('base.html', {'messages': messages}, [pre_processor])
  File "/usr/share/pyload/module/web/utils.py", line 27, in render_to_response
    args.update(p())
  File "/usr/share/pyload/module/web/pyload_app.py", line 45, in pre_processor
    user = parse_userdata(s)
  File "/usr/share/pyload/module/web/utils.py", line 95, in parse_userdata
    return {"name": session.get("name", "Anonymous"),
  File "/usr/share/pyload/module/lib/beaker/session.py", line 554, in __getattr__
    return getattr(self._session(), attr)
  File "/usr/share/pyload/module/lib/beaker/session.py", line 550, in _session
    **params)
  File "/usr/share/pyload/module/lib/beaker/session.py", line 105, in __init__
    self.cookie = Cookie.SimpleCookie(input=cookieheader)
CookieError: Illegal key value: ys-api/channel
</pre>
```

**Comment by vuolter** [comment]
A YouTube plugin issue?
