### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by simonszu** [pyload/pyload#1245]
Hi,

i want to use pyload in a FreeBSD jail with ZFS. Unfortunately i cannot start it. The error i get when starting pyLoadCore.py with Python 2.7 is:
```
Traceback (most recent call last):
  File "./pyLoadCore.py", line 667, in <module>
    main()
  File "./pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "./pyLoadCore.py", line 412, in start
    self.log.info(_("Free space: %s") % formatSize(spaceLeft))
  File "/usr/local/pyload/module/utils.py", line 95, in formatSize
    return "%.2f %s" % (size, sizes[steps])
IndexError: list index out of range
```

Can you look  at this, please?

**Comment by vuolter** [comment]
Support for drives with TB+ free space was added in 0.4.10.
