### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#1248]
On the newest Updated Plugins i got the following error:
11.03.2015 04:00:41 DEBUG     Content-Disposition: tvs-fortitude-sed-dl-ithd-x264-102.part4.rar
11.03.2015 04:01:47 WARNING   Download failed: tvs-fortitude-sed-dl-ithd-x264-102.part4.rar | 'NoneType' object has no attribute 'strip'
11.03.2015 04:01:47 INFO      Debug Report written to debug_ShareonlineBiz_11-03-2015_04-01-47.zip

Seems to be a mistake in simplehoster:
TRACEBACK:
 Traceback (most recent call last):
  File "/opt/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/opt/pyload/module/plugins/Plugin.py", line 237, in preprocessing
    return self.process(self.pyfile)
  File "/opt/pyload/.pyload/userplugins/internal/SimpleHoster.py", line 487, in process
    self.checkFile()
  File "/opt/pyload/.pyload/userplugins/hoster/ShareonlineBiz.py", line 123, in checkFile
    return super(ShareonlineBiz, self).checkFile()
  File "/opt/pyload/.pyload/userplugins/internal/SimpleHoster.py", line 527, in checkFile
    errmsg = self.checkDownload(rules).strip().capitalize()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by thevortex42** [comment]
I get the same error, though I hvae no idea how to get the traceback, so I cannot say if it is the same source

**Comment by Mister-XY** [comment]
pyLoad 0.4.9 Debug Report of UploadedTo 0.85 

TRACEBACK:
 Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/usr/share/pyload/module/plugins/Plugin.py", line 237, in preprocessing
    return self.process(self.pyfile)
  File "/home/thomas/.pyload/userplugins/internal/SimpleHoster.py", line 487, in process
    self.checkFile()
  File "/home/thomas/.pyload/userplugins/hoster/UploadedTo.py", line 117, in checkFile
    return super(UploadedTo, self).checkFile(rules)
  File "/home/thomas/.pyload/userplugins/internal/SimpleHoster.py", line 527, in checkFile
    errmsg = self.checkDownload(rules).strip().capitalize()
AttributeError: 'NoneType' object has no attribute 'strip'
