### ISSUE TITLE
[SimpleHoster] getConfig() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1263]
Hi,
This exceptions happens with every SimpleHoster based hoster
```
18.03.2015 23:51:21 INFO      Download starts: Dada Life - This Machine Kills Ravers (Deficio Remix).mp3
18.03.2015 23:51:21 WARNING   Download failed: Dada Life - This Machine Kills Ravers (Deficio Remix).mp3 | getConfig() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "/DataVolume/opt/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/DataVolume/opt/share/pyload/module/plugins/Plugin.py", line 237, in preprocessing
    return self.process(self.pyfile)
  File "/DataVolume/opt/etc/pyload/userplugins/internal/SimpleHoster.py", line 462, in process
    self.prepare()
  File "/DataVolume/opt/etc/pyload/userplugins/internal/SimpleHoster.py", line 428, in prepare
    if not self.getConfig('use_premium', True):
TypeError: getConfig() takes exactly 2 arguments (3 given)
18.03.2015 23:51:21 DEBUG     Error creating zip file: 'ascii' codec can't decode byte 0xae in position 11: ordinal not in range(128)
18.03.2015 23:51:21 INFO      Debug Report written to debug_ZippyshareCom_18-03-2015_23-51-21.txt
```

**Comment by vuolter** [comment]
THX.
