### ISSUE TITLE
[ZippyshareCom] somtimes the plugins failes with `failed No JS Engine`

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1264]
Hi,
the same link i was successfully able to download now gives `failed No JS Engine` status
if i try few more times, it is able to download it again.

```
TRACEBACK:
 Traceback (most recent call last):
  File "/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/share/pyload/module/plugins/Plugin.py", line 237, in preprocessing
    return self.process(self.pyfile)
  File "/etc/pyload/userplugins/internal/SimpleHoster.py", line 487, in process
    self.handleFree(pyfile)
  File "/etc/pyload/userplugins/hoster/ZippyshareCom.py", line 52, in handleFree
    self.link = self.get_link()
  File "/etc/pyload/userplugins/hoster/ZippyshareCom.py", line 86, in get_link
    return self.js.eval('\n'.join(scripts))
  File "/share/pyload/module/common/JsEngine.py", line 101, in eval
    raise Exception("No JS Engine")
Exception: No JS Engine
```

**Comment by GammaC0de** [comment]
Ok, 
I was able to pinpoint the problem to the fact that my PATH wasnt pointing to the location of the `js` command so `subprocess`  couldn't find the `js` command.
In the process, I noticed some things about JsEngine.py:
1) It does not use `import subprocess` globally (I can see it  few times in some of the functions)? is there a reason for that?
2) If there is a reason for that, shouldn't you use `import subprocess` on `eval_rhino` and `eval_js` functions also?

**Comment by vuolter** [comment]
JsEngine has been rewritten in 0.4.10 .

**Comment by Velociraptor85** [comment]
@GammaC0de I think this is solved?

**Comment by GammaC0de** [comment]
This issue is unknown to me, probably was solved.
