### ISSUE TITLE
[UserAgentSwitcher] TypeError: invalid arguments to setopt

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1324]
```
TRACEBACK:
 Traceback (most recent call last):
  File "/share/pyload/module/PluginThread.py", line 186, in run
    self.m.core.hookManager.downloadPreparing(pyfile)
  File "/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/share/pyload/module/HookManager.py", line 214, in downloadPreparing
    plugin.downloadPreparing(pyfile)
  File "/etc/pyload/userplugins/hooks/UserAgentSwitcher.py", line 32, in downloadPreparing
    pyfile.plugin.req.http.c.setopt(pycurl.USERAGENT, ua)
TypeError: invalid arguments to setopt
```
Patch:
```patch
--- UserAgentSwitcher.py.bad    2015-04-08 02:33:48.000000000 +0300
+++ UserAgentSwitcher.py        2015-04-08 03:10:16.049485057 +0300
@@ -29,4 +29,4 @@
         ua = self.getConfig('ua')
         if ua:
             self.logDebug("Use custom user-agent string: " + ua)
-            pyfile.plugin.req.http.c.setopt(pycurl.USERAGENT, ua)
+            pyfile.plugin.req.http.c.setopt(pycurl.USERAGENT, ua.encode("utf-8"))

```

**Comment by vuolter** [comment]
Thanks!!!
