### ISSUE TITLE
master: error on adding hoster account

### ISSUE THREAD

**Issue by sebastianhelbig** [pyload/pyload#1410]
```
Traceback (most recent call last):
  File "/opt/pyload/lib/Python/Lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/opt/pyload/lib/Python/Lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/opt/pyload/pyload/webui/app/utils.py", line 105, in _view
    return func(*args, **kwargs)
  File "/opt/pyload/pyload/webui/app/json.py", line 277, in add_account
    PYLOAD.updateAccount(type, login, password)
  File "/opt/pyload/pyload/api/__init__.py", line 914, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "/opt/pyload/pyload/utils/__init__.py", line 214, in new
    return func(*args)
  File "/opt/pyload/pyload/manager/Account.py", line 155, in updateAccount
    updated = p.updateAccounts(user, password, options)
AttributeError: 'NoneType' object has no attribute 'updateAccounts'
```

**Comment by bkchr** [comment]
Pull request #1550 fix this
