### ISSUE TITLE
Pyload did not start

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#1456]
Hello, after the last update, pyload did not start and i get this error

06.06.2015 02:58:45 INFO      starte pyLoad 0.4.9
06.06.2015 02:58:45 INFO      Benutze Home-Verzeichnis: /root/.pyload
Traceback (most recent call last):
  File "/usr/bin/pyLoadCore", line 667, in <module>
    main()
  File "/usr/bin/pyLoadCore", line 658, in main
    pyload_core.start()
  File "/usr/bin/pyLoadCore", line 392, in start
    self.pluginManager = PluginManager(self)
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 50, in __init__
    self.createIndex()
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 73, in createIndex
    self.plugins["hooks"] = self.hookPlugins = self.parse("hooks")
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 196, in parse
    temp = self.parse(folder, pattern, plugins)
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 163, in parse
    config = literal_eval(config[0].strip().replace("\n", "").replace("\r", ""))
  File "/usr/share/pyload/module/lib/SafeEval.py", line 45, in const_eval
    return eval(c, None, _locals)
  File "", line 1, in <module>

TypeError: bad operand type for unary +: 'tuple'

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/b81d202ab0eeb692a85ee4dda946810fb9886f59
