### ISSUE TITLE
pyload not starting after latest updates

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [pyload/pyload#1457]
Hi there,
it seems like tonight's update messed something up. pyload didn't automatically restart and I can't seem to reanimate it manually via ssh (/etc/init.d/pyload restart)

Here's the log of tonight:

```
06.06.2015 02:51:13 INFO      UpdateManager: No new pyLoad version available
06.06.2015 02:51:13 DEBUG     UpdateManager: Requested deletion of plugins: [('accounts', 'BillionuploadsCom'), ('accounts', 'File4safeCom'), ('accounts', 'Keep2shareCc'), ('accounts', 'MegaDebrid'), ('accounts', 'MultiDebridCom'), ('accounts', 'NowVideoAt'), ('accounts', 'Premium4Me'), ('accounts', 'ShareRapidCom'), ('captcha', 'captcha'), ('container', 'DLC_25'), ('container', 'DLC_26'), ('container', 'DLC_27'), ('container', 'LinkList'), ('crypter', 'C1neonCom'), ('crypter', 'DailymotionBatch'), ('crypter', 'DownloadVimeoCom'), ('crypter', 'Go4Up'), ('crypter', 'HotfileFolderCom'), ('crypter', 'Movie2kTo'), ('crypter', 'ShareRapidComFolder'), ('crypter', 'YoutubeBatch'), ('hooks', 'AlldebridCom'), ('hooks', 'Captcha9kw'), ('hooks', 'CaptchaTrader'), ('hooks', 'DebridItaliaCom'), ('hooks', 'EasybytezCom'), ('hooks', 'Ev0InFetcher'), ('hooks', 'FastixRu'), ('hooks', 'FreeWayMe'), ('hooks', 'LinkdecrypterCom'), ('hooks', 'LinksnappyCom'), ('hooks', 'MegaDebrid'), ('hooks', 'MegaDebridEu'), ('hooks', 'MegaRapidoNet'), ('hooks', 'MultiDebridCom'), ('hooks', 'MultihostersCom'), ('hooks', 'MultishareCz'), ('hooks', 'MyfastfileCom'), ('hooks', 'NoPremiumPl'), ('hooks', 'OverLoadMe'), ('hooks', 'Premium4Me'), ('hooks', 'PremiumTo'), ('hooks', 'PremiumizeMe'), ('hooks', 'PutdriveCom'), ('hooks', 'RPNetBiz'), ('hooks', 'RapideoPl'), ('hooks', 'RealdebridCom'), ('hooks', 'RehostTo'), ('hooks', 'ReloadCc'), ('hooks', 'SimplyPremiumCom'), ('hooks', 'SimplydebridCom'), ('hooks', 'SmoozedCom'), ('hooks', 'UnrestrictLi'), ('hooks', 'Vipleech4uCom'), ('hooks', 'WindowsPhoneToastNotify'), ('hooks', 'ZeveraCom'), ('hoster', 'File4safeCom'), ('hoster', 'Keep2shareCC'), ('hoster', 'Keep2shareCc'), ('hoster', 'MegaDebrid'), ('hoster', 'MegaNz'), ('hoster', 'MultiDebridCom'), ('hoster', 'PandaPlaNet'), ('hoster', 'PandaPlanet'), ('hoster', 'Premium4Me'), ('hoster', 'PutlockerCom'), ('hoster', 'ReloadCc'), ('hoster', 'Share4webCom'), ('hoster', 'ShareRapidCom'), ('hoster', 'Solidfiles'), ('hoster', 'Vipleech4uCom'), ('internal', 'AbstractExtractor'), ('internal', 'XFSPAccount'), ('internal', 'XFSPCrypter'), ('internal', 'XFSPHoster')]
06.06.2015 02:51:13 INFO      UpdateManager: New plugin: [account] HighWayMe (v0.01)
06.06.2015 02:51:13 INFO      UpdateManager: New version of plugin: [crypter] BitshareComFolder (v0.03 -> v0.04)
06.06.2015 02:51:14 INFO      UpdateManager: New version of plugin: [crypter] DataHuFolder (v0.06 -> v0.07)
06.06.2015 02:51:14 INFO      UpdateManager: New version of plugin: [crypter] FilestubeCom (v0.05 -> v0.06)
06.06.2015 02:51:15 INFO      UpdateManager: New version of plugin: [crypter] TnyCz (v0.03 -> v0.04)
06.06.2015 02:51:15 INFO      UpdateManager: New plugin: [hook] HighWayMe (v0.01)
06.06.2015 02:51:16 INFO      UpdateManager: New version of plugin: [hoster] FileSharkPl (v0.10 -> v0.11)
06.06.2015 02:51:16 INFO      UpdateManager: New plugin: [hoster] HighWayMe (v0.08)
06.06.2015 02:51:16 INFO      UpdateManager: New version of plugin: [hoster] Keep2ShareCc (v0.22 -> v0.23)
06.06.2015 02:51:17 INFO      UpdateManager: New version of plugin: [hoster] LoadTo (v0.23 -> v0.24)
06.06.2015 02:51:17 INFO      UpdateManager: New version of plugin: [hoster] SizedriveCom (v0.01 -> v0.02)
06.06.2015 02:51:17 INFO      UpdateManager: New version of plugin: [hoster] UploadedTo (v0.91 -> v0.92)
06.06.2015 02:51:18 INFO      UpdateManager: New version of plugin: [hoster] UploadingCom (v0.40 -> v0.41)
06.06.2015 02:51:18 INFO      UpdateManager: New version of plugin: [hoster] VimeoCom (v0.04 -> v0.05)
06.06.2015 02:51:18 INFO      UpdateManager: *** Plugins updated ***
06.06.2015 02:51:18 DEBUG     Request reload of plugins: [('accounts', 'HighWayMe'), ('crypter', 'BitshareComFolder'), ('crypter', 'DataHuFolder'), ('crypter', 'FilestubeCom'), ('crypter', 'TnyCz'), ('hooks', 'HighWayMe'), ('hoster', 'FileSharkPl'), ('hoster', 'HighWayMe'), ('hoster', 'Keep2ShareCc'), ('hoster', 'LoadTo'), ('hoster', 'SizedriveCom'), ('hoster', 'UploadedTo'), ('hoster', 'UploadingCom'), ('hoster', 'VimeoCom')]
06.06.2015 02:51:18 WARNING   UpdateManager: pyLoad restart required to reload the updated plugins
06.06.2015 02:51:19 INFO      restarting pyLoad
06.06.2015 02:51:19 INFO      shutting down...
06.06.2015 02:51:19 DEBUG     Deleting old pidfile /var/run/pyload/pyload.pid
06.06.2015 02:51:19 INFO      Starting pyLoad 0.4.9
06.06.2015 02:51:19 INFO      Using home directory: /home/pyload/.pyload
06.06.2015 02:51:19 DEBUG     Remote activated: True
```
And this is what my wakeup calls via ssh resulted in this morning:
```
06.06.2015 10:43:00 INFO      Starting pyLoad 0.4.9
06.06.2015 10:43:00 INFO      Using home directory: /home/pyload/.pyload
06.06.2015 10:43:00 DEBUG     Remote activated: True
06.06.2015 10:43:17 INFO      Starting pyLoad 0.4.9
06.06.2015 10:43:17 INFO      Using home directory: /home/pyload/.pyload
06.06.2015 10:43:17 DEBUG     Remote activated: True
06.06.2015 10:46:16 INFO      Starting pyLoad 0.4.9
06.06.2015 10:46:16 INFO      Using home directory: /home/pyload/.pyload
06.06.2015 10:46:16 DEBUG     Remote activated: True
```

Any Ideas what that might be? I already looked at this thread (http://forum.pyload.org/viewtopic.php?f=12&t=4196&start=10), but the line in UploadedTo.py mentioned there is not the problem.

**Comment by Web-Eye** [comment]
Same here, I got this by starting pyloadcore manually:

```
06.06.2015 11:29:24 INFO      Starting pyLoad 0.4.9
06.06.2015 11:29:24 INFO      Using home directory: /home/frank/.pyload
Traceback (most recent call last):
  File "/usr/bin/pyLoadCore", line 667, in <module>
    main()
  File "/usr/bin/pyLoadCore", line 658, in main
    pyload_core.start()
  File "/usr/bin/pyLoadCore", line 392, in start
    self.pluginManager = PluginManager(self)
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 50, in __init__
    self.createIndex()
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 73, in createIndex
    self.plugins["hooks"] = self.hookPlugins = self.parse("hooks")
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 196, in parse
    temp = self.parse(folder, pattern, plugins)
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 163, in parse
    config = literal_eval(config[0].strip().replace("\n", "").replace("\r", ""))
  File "/usr/share/pyload/module/lib/SafeEval.py", line 45, in const_eval
    return eval(c, None, _locals)
  File "", line 1, in <module>

TypeError: bad operand type for unary +: 'tuple'
```

**Comment by Guidobelix** [comment]
Thank you, your countermeasure worked for me too :thumbsup:

**Comment by 1337sup3rh4x0r** [comment]
Confirm. This works!
