### ISSUE TITLE
UploadedTo Broken

### ISSUE THREAD

**Issue by I-RiX-I** [pyload/pyload#1464]
Latest update broke uploaded.to

80	08.06.2015 14:23:05	INFO	Download starts: XXX.part02.rar
81	08.06.2015 14:23:07	WARNING	Download failed: XXX.part02.rar | 'str' object is not callable

Account has some hundred gigabytes of traffic left & files are readily available through Chrome.

**Comment by Nippey** [comment]
Hey, same here, I guess it is still related to `SimpleHoster.py`
```
Download failed: CENSORED.rar | 'str' object is not callable
Traceback (most recent call last):
  File "/volume1/@optware/share/pyload-git/module/PluginThread.py", line 187, in run
  File "/volume1/web/pyload-git-stable/module/plugins/internal/Plugin.py", line 237, in preprocessing
    return self.process(self.pyfile)
  File "/volume1/web/pyload-git-stable/module/plugins/internal/SimpleHoster.py", line 512, in process
    self.checkInfo()
  File "/volume1/web/pyload-git-stable/module/plugins/internal/SimpleHoster.py", line 769, in checkInfo
    self.checkNameSize()
  File "/volume1/web/pyload-git-stable/module/plugins/internal/SimpleHoster.py", line 742, in checkNameSize
    self.logDebug("Update file info...")
  File "/volume1/web/pyload-git-stable/module/plugins/internal/SimpleHoster.py", line 438, in logDebug
    return self._log("debug", args)
  File "/volume1/web/pyload-git-stable/module/plugins/internal/SimpleHoster.py", line 428, in _log
    str(a)).strip() for a in args if a)
  File "/volume1/web/pyload-git-stable/module/plugins/internal/SimpleHoster.py", line 428, in <genexpr>
    str(a)).strip() for a in args if a)
TypeError: 'str' object is not callable
08.06.2015 14:21:01 DEBUG     Error creating zip file: 'ascii' codec can't decode byte 0xa0 in position 10: ordinal not in range(128)
08.06.2015 14:21:01 INFO      Debug Report written to debug_ShareonlineBiz_08-06-2015_14-21-01.txt
```

Maybe the internal object `str` is overwritten somewhere?

```
#> find . -iname "*.py"|xargs grep "str "
./module/lib/thrift/protocol/TBinaryProtocol.py:    str = self.trans.readAll(len)
./module/plugins/internal/SimpleHoster.py:                          decode(a) if type(a) is str else
./module/remote/thriftbackend/Protocol.py:            str = str.encode("utf8", "ignore")
./module/remote/thriftbackend/Protocol.py:        str = self.trans.readAll(len)
./module/remote/thriftbackend/Protocol.py:            str = str.decode("utf8", "ignore")
```
Regards
--Nippey

**Comment by Nippey** [comment]
Thxx, all perfect now!

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/a8c8ace5ee4868f58067c8af30ea5702a2434999
