### ISSUE TITLE
Skipping files doesnt work

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#1481]
Skipping files doesnt work
```
10.06.2015 11:28:59 WARNING   Download failed: cmmty.0125.s3s4.l2.hd1-fks.part2.rar | File exists.
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 182, in run
    pyfile.plugin.checkForSameFiles(starting=True)
  File "/root/.pyload/userplugins/internal/Plugin.py", line 598, in checkForSameFiles
    raise SkipDownload("File exists.")
SkipDownload: File exists.
10.06.2015 11:28:59 INFO      Debug Report written to debug_UploadedTo_10-06-2015_11-28-59.zip
10.06.2015 11:28:59 INFO      UnSkipOnFail: Looking for skipped duplicates of: cmmty.0125.s3s4.l2.hd1-fks.part2.rar (pid:10)
10.06.2015 11:28:59 INFO      UnSkipOnFail: No duplicates found
```

**Comment by TodsDeath** [comment]
Have a look at #1473, should be already fixed.

**Comment by Gutz-Pilz** [comment]
sorry for dat
