### ISSUE TITLE
AttributeError: 'ExtractArchive' object has no attribute 'pyfile'

### ISSUE THREAD

**Issue by georg94** [pyload/pyload#1493]
After the new update some Hooks are broken. Here is an example error stack from the log:
```
14.06.2015 18:41:11 ERROR     Error executing hooks: 'ExtractArchive' object has no attribute 'pyfile'
Traceback (most recent call last):
  File "/usr/share/pyload/module/HookManager.py", line 88, in new
    return func(*args)
  File "/usr/share/pyload/module/HookManager.py", line 198, in coreReady
    plugin.coreReady()
  File "/home/pi/.pyload/userplugins/hooks/ExtractArchive.py", line 169, in coreReady
    self.logWarning(_("No %s installed") % p)
  File "/home/pi/.pyload/userplugins/internal/Plugin.py", line 79, in logWarning
    return self._log("warning", args)
  File "/home/pi/.pyload/userplugins/internal/Plugin.py", line 65, in _log
    'id'    : self.pyfile.id,
AttributeError: 'ExtractArchive' object has no attribute 'pyfile'
```

Plugins with the same error are:
 - LinkdecrypterComHook
 - RestartFailed
 - PremiumizeMeHook

**Comment by nordic-style** [comment]
Same here.

**Comment by Mister-XY** [comment]
ERROR	Error executing hooks: 'XFileSharingPro' object has no attribute 'pyfile' 
WARNING	 Konnte ExternalScripts nicht aktivieren

**Comment by vpowler** [comment]
14.06.2015 20:11:28 ERROR     Error executing hooks: 'XFileSharingPro' object has no attribute 'pyfile'
14.06.2015 20:11:28 INFO      pyLoad is up and running
14.06.2015 20:11:30 ERROR     Error executing hooks: 'LinkdecrypterComHook' object has no attribute 'pyfile'

**Comment by GammaC0de** [comment]
```
14.06.2015 23:18:01 ERROR     Error executing hooks: 'XFileSharingPro' object has no attribute 'pyfile'
Traceback (most recent call last):
  File "/usr/share/pyload/module/HookManager.py", line 88, in new
    return func(*args)
  File "/usr/share/pyload/module/HookManager.py", line 198, in coreReady
    plugin.coreReady()
  File "/home/user/.pyload/userplugins/hooks/XFileSharingPro.py", line 57, in coreReady
    self.loadPattern()
  File "/home/user/.pyload/userplugins/hooks/XFileSharingPro.py", line 68, in loadPattern
    self.logInfo(_("Handling any %s I can!") % type)
  File "/home/user/.pyload/userplugins/internal/Plugin.py", line 75, in logInfo
    return self._log("info", args)
  File "/home/user/.pyload/userplugins/internal/Plugin.py", line 65, in _log
    'id'    : self.pyfile.id,
AttributeError: 'XFileSharingPro' object has no attribute 'pyfile'
```
```
14.06.2015 23:18:03 ERROR     Error executing hooks: 'LinkdecrypterComHook' object has no attribute 'pyfile'
Traceback (most recent call last):
  File "/home/user/.pyload/userplugins/internal/MultiHook.py", line 178, in _periodical
    self.periodical()
  File "/home/user/.pyload/userplugins/internal/MultiHook.py", line 198, in periodical
    self.logInfo(_("Reloading supported %s list") % self.plugintype)
  File "/home/user/.pyload/userplugins/internal/Plugin.py", line 75, in logInfo
    return self._log("info", args)
  File "/home/user/.pyload/userplugins/internal/Plugin.py", line 65, in _log
    'id'    : self.pyfile.id,
AttributeError: 'LinkdecrypterComHook' object has no attribute 'pyfile'
```
```
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/home/user/.pyload/userplugins/hooks/ClickAndLoad.py", line 66, in proxy
    self.logInfo(_("Proxy listening on %s:%s") % (ip or "0.0.0.0", cnlport))
  File "/home/user/.pyload/userplugins/internal/Plugin.py", line 75, in logInfo
    return self._log("info", args)
  File "/home/user/.pyload/userplugins/internal/Plugin.py", line 65, in _log
    'id'    : self.pyfile.id,
AttributeError: 'ClickAndLoad' object has no attribute 'pyfile'
```
