### ISSUE TITLE
captchaTask() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by nomad71** [pyload/pyload#1496]
Found this during a (re)Captcha request - repeatet 7 times:
```
Traceback (most recent call last):
  File "/usr/share/pyload/module/CaptchaManager.py", line 69, in handleCaptcha
    plugin.newCaptchaTask(task)
  File "/home/pi/.pyload/userplugins/internal/Hook.py", line 186, in newCaptchaTask
    return self.captchaTask()
TypeError: captchaTask() takes exactly 2 arguments (1 given)
```

**Comment by nomad71** [comment]
Already fixed?! You're an animal XD

**Comment by vuolter** [comment]
:smiley_cat:
