### ISSUE TITLE
global name 'decode' is not defined

### ISSUE THREAD

**Issue by bmalum** [pyload/pyload#1523]
Did not find any open Bug for this, so i opened this one. Using 4.9 in an FreeBSD 10.1 Jail. Since 4 Days after a Restart for Plugin Update Pyload does not download anymore an throws this exception.

```
17.06.2015 22:28:02 INFO      Starting builtin webserver: 0.0.0.0:8000
17.06.2015 22:28:02 DEBUG     Redirected import module.plugins.accounts.UploadedTo -> userplugins.accounts.UploadedTo
17.06.2015 22:28:02 DEBUG     Redirected import module.plugins.internal.Account -> userplugins.internal.Account
Traceback (most recent call last):
  File "pyLoadCore.py", line 667, in <module>
    main()
  File "pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "pyLoadCore.py", line 433, in start
    self.accountManager.getAccountInfos()
  File "/root/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/root/pyload/module/plugins/AccountManager.py", line 176, in getAccountInfos
    data[p.__name__] = p.getAllAccounts(force)
  File "/root/pyload/userplugins/internal/Account.py", line 203, in getAllAccounts
    return [self.getAccountInfo(user, force) for user, data in self.accounts.iteritems()]
  File "/root/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/root/pyload/userplugins/internal/Account.py", line 153, in getAccountInfo
    self.logDebug("Get Account Info for %s" % name)
  File "/root/pyload/userplugins/internal/Plugin.py", line 71, in logDebug
    return self._log("debug", args)
  File "/root/pyload/userplugins/internal/Plugin.py", line 63, in _log
    str(a)).strip() for a in args if a)
  File "/root/pyload/userplugins/internal/Plugin.py", line 63, in <genexpr>
    str(a)).strip() for a in args if a)
NameError: global name 'decode' is not defined
´´´

**Comment by nomad71** [comment]
Seems to be the same as #1492.

Is your Plugin.py up to date? Current version is 0.10 (see [here](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/Plugin.py))

**Comment by bmalum** [comment]
updated manually and is fixed :)
