### ISSUE TITLE
Wrong Codec in Folder/Package Name

### ISSUE THREAD

**Issue by bmalum** [pyload/pyload#1544]
Hey Guys, 

I found another bug which accords to #1110 I think. I found out: If a Folder contains an special character like (äöüß) I get this error in the ui:

```
queued'ascii' codec can't encode character u'\xe4' in position 12: ordinal not in range(128) 112.00 MiBShareonlineBiz  Delete Link  Restart Link
```

It can be done a workaround to change the package name ... hopefully reproducable 😉 thanks and have fun downloading.

**Comment by vuolter** [comment]
Please retry now.
Log wanted.

**Comment by bmalum** [comment]
Hey thanks for the fix - now i have the same problem again that downloads won't start and does not create a Log entry. I have activated logging in Config -> General -> Debugmode True

also cloned the repo in an new jail - in an up2date stable branch ... in 1.0.0 there is downloading working 

```
root@pyload:~/pyload # python pyLoadCore.py
28.07.2015 18:05:14 INFO      Starting pyLoad 0.4.9
28.07.2015 18:05:14 INFO      Using home directory: /root/pyload
28.07.2015 18:05:14 DEBUG     Deleting old pidfile pyload.pid
28.07.2015 18:05:14 DEBUG     Remote activated: True
28.07.2015 18:05:14 DEBUG     created index of plugins
28.07.2015 18:05:15 DEBUG     HOOK ExternalScripts : Deprecated method `event_list`, use `event_map` instead
28.07.2015 18:05:15 INFO      Activated plugins: ExternalScripts, ExtractArchive, LinkdecrypterComHook, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharingPro
28.07.2015 18:05:15 INFO      Deactivate plugins: AlldebridComHook, AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, ClickAndLoad, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMe, HighWayMeHook, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinksnappyComHook, MegaDebridEuHook, MegaRapidoNetHook, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridComHook, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, UnrestrictLiHook, WindowsPhoneNotify, XMPPInterface, ZeveraComHook
28.07.2015 18:05:15 INFO      Downloadtime: True
28.07.2015 18:05:15 INFO      Starting ThriftBackend: 0.0.0.0:7227
Traceback (most recent call last):
28.07.2015 18:05:15 INFO      Starting builtin webserver: 0.0.0.0:8000
  File "pyLoadCore.py", line 667, in <module>
    main()
  File "pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "pyLoadCore.py", line 412, in start
    self.log.info(_("Free space: %s") % formatSize(spaceLeft))
  File "/root/pyload/module/utils.py", line 95, in formatSize
    return "%.2f %s" % (size, sizes[steps])
IndexError: list index out of range
28.07.2015 18:07:18 INFO      Added package Tes containing 1 links
28.07.2015 18:07:18 DEBUG     Run Info Fetching for UploadedTo
28.07.2015 18:07:18 DEBUG     Finished Info Fetching for UploadedTo
```

This was on the command line after starting and adding a download containing a special character, does also not work with any file.

**Comment by vuolter** [comment]
Unfixable in 0.4.9. If your have more than one TB of free space, pyLoad crashes.
