### ISSUE TITLE
Error importing UpdateManager: No module named Hook 

### ISSUE THREAD

**Issue by goldenrider66** [pyload/pyload#1546]
Hello,

I have Problems with pyload on my QNAP NAS. Because I have problems with the UpdateManager, I have updated it to this version:

https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/UpdateManager.py

I found this solution here:

http://forum.pyload.org/viewtopic.php?f=12&t=3807&start=10

After doing so, i get this error:
28.06.2015 19:46:49	ERROR	Fehler beim importieren von UpdateManager: No module named Hook 

Hope somebody could help my to solve it.

Thank you in advance

**Comment by GammaC0de** [comment]
@goldenrider66 please try this http://forum.pyload.org/viewtopic.php?f=10&t=4335

**Comment by goldenrider66** [comment]
@GammaC0de 

I have tried this before posting here for help without any success.

**Comment by GammaC0de** [comment]
Please enable debug mode and post the full log here.

**Comment by ISharkI** [comment]
I got the same error with my Debian machine (Wheezy). Just updated from Git and tried the same about deleting/reinstalling but always the same error.
```
shark:~/pyload$ ./pyLoadCore.py -d
03.07.2015 17:58:52 INFO      Starting pyLoad 0.4.9
03.07.2015 17:58:52 INFO      Using home directory: /home/shark/.pyload
03.07.2015 17:58:52 DEBUG     Remote activated: True
03.07.2015 17:58:53 DEBUG     created index of plugins
03.07.2015 17:58:53 DEBUG     Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
03.07.2015 17:58:53 ERROR     Error importing ExternalScripts: No module named Hook
Traceback (most recent call last):
  File "/home/shark/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
 File "/home/shark/pyload/module/plugins/PluginManager.py", line 317, in load_module                                                         [34/852]
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/shark/.pyload/userplugins/hooks/ExternalScripts.py", line 6, in <module>
    from module.plugins.internal.Hook import Hook
ImportError: No module named Hook
03.07.2015 17:58:53 DEBUG     Redirected import module.plugins.hooks.ClickAndLoad -> userplugins.hooks.ClickAndLoad
03.07.2015 17:58:53 ERROR     Error importing ClickAndLoad: No module named Hook
Traceback (most recent call last):
  File "/home/shark/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/home/shark/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/shark/.pyload/userplugins/hooks/ClickAndLoad.py", line 13, in <module>
    from module.plugins.internal.Hook import Hook, threaded
ImportError: No module named Hook
03.07.2015 17:58:53 DEBUG     Redirected import module.plugins.hooks.XFileSharingPro -> userplugins.hooks.XFileSharingPro
03.07.2015 17:58:53 ERROR     Error importing XFileSharingPro: No module named Hook
Traceback (most recent call last):
  File "/home/shark/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/home/shark/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/shark/.pyload/userplugins/hooks/XFileSharingPro.py", line 5, in <module>
    from module.plugins.internal.Hook import Hook
ImportError: No module named Hook
03.07.2015 17:58:53 DEBUG     Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
03.07.2015 17:58:53 ERROR     Error importing ExtractArchive: No module named Hook
Traceback (most recent call last):
  File "/home/shark/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/home/shark/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/shark/.pyload/userplugins/hooks/ExtractArchive.py", line 56, in <module>
    from module.plugins.internal.Hook import Hook, Expose, threaded
ImportError: No module named Hook
03.07.2015 17:58:53 DEBUG     Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
03.07.2015 17:58:53 ERROR     Error importing UnSkipOnFail: No module named Hook
Traceback (most recent call last):
  File "/home/shark/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/home/shark/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/shark/.pyload/userplugins/hooks/UnSkipOnFail.py", line 4, in <module>
    from module.plugins.internal.Hook import Hook
ImportError: No module named Hook
03.07.2015 17:58:53 DEBUG     Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
03.07.2015 17:58:53 ERROR     Error importing UpdateManager: No module named Hook
Traceback (most recent call last):
  File "/home/shark/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/home/shark/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/shark/.pyload/userplugins/hooks/UpdateManager.py", line 13, in <module>
    from module.plugins.internal.Hook import Expose, Hook, threaded
ImportError: No module named Hook
03.07.2015 17:58:53 INFO      Activated plugins: 
03.07.2015 17:58:53 INFO      Deactivate plugins: BypassCaptcha, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, MergeFiles, MultiHome, RestartFailed, XMPPInterface
03.07.2015 17:58:53 INFO      Downloadtime: True
03.07.2015 17:58:53 INFO      Using SSL ThriftBackend
03.07.2015 17:58:53 INFO      Starting ThriftBackend: 0.0.0.0:7227
03.07.2015 17:58:53 INFO      Starting threaded SSL webserver: 0.0.0.0:8000
03.07.2015 17:58:53 INFO      Free space: 1.00 TiB
03.07.2015 17:58:53 INFO      Activating Accounts...
03.07.2015 17:58:53 INFO      Activating Plugins...
03.07.2015 17:58:53 INFO      pyLoad is up and running
^C03.07.2015 17:59:54 INFO      shutting down...
03.07.2015 17:59:54 DEBUG     Deleting old pidfile pyload.pid
03.07.2015 17:59:54 INFO      killed pyLoad from Terminal
```

**Comment by GammaC0de** [comment]
@ISharkI rename `/home/shark/.pyload/userplugins` to `userplugins.old` then run pyload again

**Comment by ISharkI** [comment]
Now it's just one error still there... but downloading does not work either

```
shark:~/pyload$ ./pyLoadCore.py -d
03.07.2015 18:38:35 INFO      Starting pyLoad 0.4.9
03.07.2015 18:38:35 INFO      Using home directory: /home/shark/.pyload
03.07.2015 18:38:35 DEBUG     Remote activated: True
03.07.2015 18:38:36 DEBUG     created index of plugins
03.07.2015 18:38:36 ERROR     Error importing ExtractArchive: No module named AbstractExtractor
Traceback (most recent call last):
  File "/home/shark/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/home/shark/pyload/module/plugins/hooks/ExtractArchive.py", line 53, in <module>
    from module.plugins.internal.AbstractExtractor import ArchiveError, CRCError, WrongPassword
ImportError: No module named AbstractExtractor
03.07.2015 18:38:36 INFO      Activated plugins: ClickAndLoad, ExternalScripts, UnSkipOnFail, UpdateManager, XFileSharingPro
03.07.2015 18:38:36 INFO      Deactivate plugins: BypassCaptcha, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, MergeFiles, MultiHome, RestartFailed, XMPPInterface
03.07.2015 18:38:36 INFO      Downloadtime: True
03.07.2015 18:38:36 INFO      Using SSL ThriftBackend
03.07.2015 18:38:36 INFO      Starting ThriftBackend: 0.0.0.0:7227
03.07.2015 18:38:36 INFO      Starting threaded SSL webserver: 0.0.0.0:8000
03.07.2015 18:38:36 INFO      Free space: 1.00 TiB
03.07.2015 18:38:36 INFO      Activating Accounts...
03.07.2015 18:38:36 INFO      Activating Plugins...
03.07.2015 18:38:36 DEBUG     XFileSharingPro: Pattern loaded - handling 87 hosters
03.07.2015 18:38:36 INFO      pyLoad is up and running
03.07.2015 18:38:47 INFO      Added package add_file containing 1 links
03.07.2015 18:38:48 INFO      Download starts: /share/incoming/tmp_uploaded_valid.dlc
03.07.2015 18:38:48 WARNING   Download failed: /share/incoming/tmp_uploaded_valid.dlc | No Plugin matched and not a downloadable url.
03.07.2015 18:38:48 INFO      UnSkipOnFail: look for skipped duplicates for tmp_uploaded_valid.dlc (pid:1)...
03.07.2015 18:38:48 DEBUG     All downloads processed
^C03.07.2015 18:39:06 INFO      shutting down...
03.07.2015 18:39:06 DEBUG     Deleting old pidfile pyload.pid
03.07.2015 18:39:06 INFO      killed pyLoad from Terminal
```

**Comment by GammaC0de** [comment]
Uninstall pyload and delete `/home/shark/pyload` and `/home/shark/.pyload` then reinstall pyload from this package http://get.pyload.org/get/ubuntu

**Comment by ISharkI** [comment]
But I assumed the deb is derived from the Git aswell?

**Comment by GammaC0de** [comment]
git is not stable. you start from http://get.pyload.org/get/ubuntu then `UpdateManager` takes care for updating to the latest stable state

**Comment by neon100** [comment]
@GammaC0de i'm not able to download the stable version from your link or the pyload.org page because the link is down.

**Comment by GammaC0de** [comment]
try https://github.com/pyload/pyload/releases

**Comment by stickell** [comment]
You can checkout the `stable` branch of the git repo. You will get 0.4.9 with updated plugins.
