### ISSUE TITLE
Useragent argument error

### ISSUE THREAD

**Issue by sraedler** [pyload/pyload#1581]
The useragent fails if it is activated. There is anything wrong with the arguments.

TRACEBACK:
 Traceback (most recent call last):
  File "/volume1/@appstore/pyload/pyload/module/PluginThread.py", line 186, in run
    self.m.core.hookManager.downloadPreparing(pyfile)
  File "/volume1/@appstore/pyload/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/volume1/@appstore/pyload/pyload/module/HookManager.py", line 214, in downloadPreparing
    plugin.downloadPreparing(pyfile)
  File "/volume1/@appstore/pyload/var/config/userplugins/internal/Addon.py", line 169, in downloadPreparing
    return self.download_preparing(*args, **kwargs)
  File "/volume1/@appstore/pyload/var/config/userplugins/hooks/UserAgentSwitcher.py", line 37, in download_preparing
    pyfile.plugin.req.http.c.setopt(pycurl.USERAGENT, useragent)
TypeError: invalid arguments to setopt

**Comment by vuolter** [comment]
Thanks for reporting!
