### ISSUE TITLE
Premium Accounts can not be added anymore

### ISSUE THREAD

**Issue by boerngen-schmidt** [pyload/pyload#1586]
Hi,

I have the problem, that I can not add any premium accounts anymore since the last(??) update of pyload. I reinstalled pyload with a checkout from GIT and resetted my config folder.

I tried to add the accounts via Webinterface and PyGui, none of them are working. Also there is no debug output concerning the adding of the accounts.

I only get one warning 
```
29.07.2015 00:25:10 WARNING   HOOK ExtractArchive : Could not activate: SevenZip | local variable 'out' referenced before assignment
Traceback (most recent call last):
  File "/home/x/.local/pyload/module/plugins/hooks/ExtractArchive.py", line 165, in activate
    if klass.find():
  File "/home/x/.local/pyload/module/plugins/internal/SevenZip.py", line 56, in find
    m = cls.re_version.search(out)
UnboundLocalError: local variable 'out' referenced before assignment
```

**Comment by boerngen-schmidt** [comment]
Adding the accounts via accounts.conf lets pyload parse and display them, but even though they are premium, the download does not start.

```
29.07.2015 00:36:24 INFO      ACCOUNT UploadedTo : Parsing account info for user `USERID`...
29.07.2015 00:36:24 DEBUG     ACCOUNT UploadedTo : LOAD URL http://uploaded.net/me | cookies=True | get={} | req=None | decode=True | just_header=False | post={} | ref=True
29.07.2015 00:36:25 DEBUG     ACCOUNT UploadedTo : Account info for user `USERID`: {'login': {'timestamp': 1438122865.651502, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1439652985.738831, 'valid': True, 'trafficleft': 547608330240.0, 'timestamp': 1438122984.682779, 'maxtraffic': None, 'premium': True, 'login': 'USERID', 'password': '**********', 'type': 'UploadedTo', 'options': {}}}
29.07.2015 00:36:25 INFO      Download starts: http://uploaded.net/file/xxxxx
29.07.2015 00:36:25 DEBUG     HOOK UserAgentSwitcher : Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
29.07.2015 00:36:25 DEBUG     HOSTER UploadedTo[1] : PROCESS URL http://uploaded.net/file/XXXXXX/FILE
29.07.2015 00:36:25 INFO      HOSTER UploadedTo[1] : Updating file info...
29.07.2015 00:36:25 DEBUG     HOSTER UploadedTo[1] : File info: {'status': 2, 'url': u'http://uploaded.net/file/xxxx', 'size': 1733475116.0, 'name': 'xxxx', 'pattern': {'ID': u'XXXXXX'}}
29.07.2015 00:36:25 DEBUG     HOSTER UploadedTo[1] : Previous file info: {}
29.07.2015 00:36:25 INFO      HOSTER UploadedTo[1] : File name: FILE
29.07.2015 00:36:25 INFO      HOSTER UploadedTo[1] : File size: 1733475116 bytes
29.07.2015 00:36:25 INFO      HOSTER UploadedTo[1] : File status: online
29.07.2015 00:36:25 INFO      HOSTER UploadedTo[1] : Looking for direct download link...
29.07.2015 00:36:25 DEBUG     HOSTER UploadedTo[1] : Redirect #0 to: http://uploaded.net/file/XXXXXX
29.07.2015 00:36:25 DEBUG     HOSTER UploadedTo[1] : LOAD URL http://uploaded.net/file/XXXXXX | cookies=True | get={} | req=None | decode=True | just_header=True | post={} | ref=True
29.07.2015 00:36:25 INFO      HOSTER UploadedTo[1] : Direct download link not found
29.07.2015 00:36:25 DEBUG     HOSTER UploadedTo[1] : LOAD URL http://uploaded.net/file/XXXXXX | cookies=True | get={} | req=None | decode=True | just_header=False | post={} | ref=False
29.07.2015 00:36:26 INFO      HOSTER UploadedTo[1] : Processing as free download...
29.07.2015 00:36:26 DEBUG     HOSTER UploadedTo[1] : LOAD URL http://uploaded.net/language/en | cookies=True | get={} | req=None | decode=True | just_header=True | post={} | ref=True
29.07.2015 00:36:26 DEBUG     HOSTER UploadedTo[1] : LOAD URL http://uploaded.net/js/download.js | cookies=True | get={} | req=None | decode=True | just_header=False | post={} | ref=True
29.07.2015 00:36:26 DEBUG     CAPTCHA ReCaptcha[1] : ReCaptcha | Key: 6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3
29.07.2015 00:36:26 DEBUG     HOSTER UploadedTo[1] : LOAD URL http://www.google.com/recaptcha/api/challenge | cookies=True | get={'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | just_header=False | post={} | ref=True
29.07.2015 00:36:26 DEBUG     CAPTCHA ReCaptcha[1] : ReCaptcha | Challenge: 03AHJ_Vut5ke4ZwTKiaCm2bE4gs3omz_O1ngwL5Kvmn23lP9Si6QL7zo9mdz-SEDa_psQR-3tsVnXakCHsni9lheP0I7RvkQnZVjMLE6tqPJK2FJiy988Aq8qM04iuFdwY_2iNarP0TfLUI2lzvD1YqU4CmIVjd68-uFWoGKuBowxcr7qk6VJRSGzsXj2UCqcOCLrn_sjw0AQGlowgYQ2qRlmuoNwvQCsHBw
29.07.2015 00:36:26 DEBUG     HOSTER UploadedTo[1] : LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | cookies=True | get={} | req=None | decode=True | just_header=False | post={} | ref=True
29.07.2015 00:36:26 DEBUG     HOSTER UploadedTo[1] : LOAD URL http://www.google.com/recaptcha/api/reload | cookies=True | get={'reason': 'i', 'c': u'03AHJ_Vut5ke4ZwTKiaCm2bE4gs3omz_O1ngwL5Kvmn23lP9Si6QL7zo9mdz-SEDa_psQR-3tsVnXakCHsni9lheP0I7RvkQnZVjMLE6tqPJK2FJiy988Aq8qM04iuFdwY_2iNarP0TfLUI2lzvD1YqU4CmIVjd68-uFWoGKuBowxcr7qk6VJRSGzsXj2UCqcOCLrn_sjw0AQGlowgYQ2qRlmuoNwvQCsHBw', 'type': 'image', 'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | just_header=False | post={} | ref=True
29.07.2015 00:36:26 DEBUG     CAPTCHA ReCaptcha[1] : ReCaptcha | Second challenge: 03AHJ_Vusy2pNr0QDXF3mdZFd6285IXUGVaJy5mIHbe6svynOdmhMJkMjq9DcP6IUvM53eY9uHSoBm0lmVxPuEL9siJJ63a1K6ciWyz6apCp0Vlp6-9THVxG0LsY8etWChA3M59jNuAtQSnLRejegoKf8-H7t7C3JrEZ39mk8hmSZZCunKifioRPCL95Zk4qtIsYulgIXKld5hDXvYJYte2srBnBSxtHhDjQ
29.07.2015 00:36:26 DEBUG     CAPTCHA ReCaptcha[1] : ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | cookies=True | get={'c': u'03AHJ_Vusy2pNr0QDXF3mdZFd6285IXUGVaJy5mIHbe6svynOdmhMJkMjq9DcP6IUvM53eY9uHSoBm0lmVxPuEL9siJJ63a1K6ciWyz6apCp0Vlp6-9THVxG0LsY8etWChA3M59jNuAtQSnLRejegoKf8-H7t7C3JrEZ39mk8hmSZZCunKifioRPCL95Zk4qtIsYulgIXKld5hDXvYJYte2srBnBSxtHhDjQ'} | req=None | decode=False | just_header=False | post={} | ref=False
29.07.2015 00:36:27 DEBUG     ACCOUNT UploadedTo : Account info for user `USERID`: {'login': {'timestamp': 1438122865.651502, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1439652985.738831, 'valid': True, 'trafficleft': 547608330240.0, 'timestamp': 1438122984.682779, 'maxtraffic': None, 'premium': True, 'login': 'USERID', 'password': '**********', 'type': 'UploadedTo', 'options': {}}}
29.07.2015 00:36:29 DEBUG     ACCOUNT UploadedTo : Account info for user `USERID`: {'login': {'timestamp': 1438122865.651502, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1439652985.738831, 'valid': True, 'trafficleft': 547608330240.0, 'timestamp': 1438122984.682779, 'maxtraffic': None, 'premium': True, 'login': 'USERID', 'password': '**********', 'type': 'UploadedTo', 'options': {}}}
29.07.2015 00:36:31 DEBUG     ACCOUNT UploadedTo : Account info for user `USERID`: {'login': {'timestamp': 1438122865.651502, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1439652985.738831, 'valid': True, 'trafficleft': 547608330240.0, 'timestamp': 1438122984.682779, 'maxtraffic': None, 'premium': True, 'login': 'USERID', 'password': '**********', 'type': 'UploadedTo', 'options': {}}}
29.07.2015 00:36:33 DEBUG     ACCOUNT UploadedTo : Account info for user `USERID`: {'login': {'timestamp': 1438122865.651502, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1439652985.738831, 'valid': True, 'trafficleft': 547608330240.0, 'timestamp': 1438122984.682779, 'maxtraffic': None, 'premium': True, 'login': 'USERID', 'password': '**********', 'type': 'UploadedTo', 'options': {}}}
29.07.2015 00:36:35 DEBUG     ACCOUNT UploadedTo : Account info for user `USERID`: {'login': {'timestamp': 1438122865.651502, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1439652985.738831, 'valid': True, 'trafficleft': 547608330240.0, 'timestamp': 1438122984.682779, 'maxtraffic': None, 'premium': True, 'login': 'USERID', 'password': '**********', 'type': 'UploadedTo', 'options': {}}}
29.07.2015 00:36:37 DEBUG     ACCOUNT UploadedTo : Account info for user `USERID`: {'login': {'timestamp': 1438122865.651502, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1439652985.738831, 'valid': True, 'trafficleft': 547608330240.0, 'timestamp': 1438122984.682779, 'maxtraffic': None, 'premium': True, 'login': 'USERID', 'password': '**********', 'type': 'UploadedTo', 'options': {}}}
29.07.2015 00:36:39 DEBUG     ACCOUNT UploadedTo : Account info for user `USERID`: {'login': {'timestamp': 1438122865.651502, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1439652985.738831, 'valid': True, 'trafficleft': 547608330240.0, 'timestamp': 1438122984.682779, 'maxtraffic': None, 'premium': True, 'login': 'USERID', 'password': '**********', 'type': 'UploadedTo', 'options': {}}}
29.07.2015 00:36:41 DEBUG     ACCOUNT UploadedTo : Account info for user `USERID`: {'login': {'timestamp': 1438122865.651502, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1439652985.738831, 'valid': True, 'trafficleft': 547608330240.0, 'timestamp': 1438122984.682779, 'maxtraffic': None, 'premium': True, 'login': 'USERID', 'password': '**********', 'type': 'UploadedTo', 'options': {}}}
29.07.2015 00:36:43 DEBUG     ACCOUNT UploadedTo : Account info for user `USERID`: {'login': {'timestamp': 1438122865.651502, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1439652985.738831, 'valid': True, 'trafficleft': 547608330240.0, 'timestamp': 1438122984.682779, 'maxtraffic': None, 'premium': True, 'login': 'USERID', 'password': '**********', 'type': 'UploadedTo', 'options': {}}}
29.07.2015 00:36:45 DEBUG     ACCOUNT UploadedTo : Account info for user `USERID`: {'login': {'timestamp': 1438122865.651502, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1439652985.738831, 'valid': True, 'trafficleft': 547608330240.0, 'timestamp': 1438122984.682779, 'maxtraffic': None, 'premium': True, 'login': 'USERID', 'password': '**********', 'type': 'UploadedTo', 'options': {}}}
29.07.2015 00:36:47 DEBUG     ACCOUNT UploadedTo : Account info for user `USERID`: {'login': {'timestamp': 1438122865.651502, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1439652985.738831, 'valid': True, 'trafficleft': 547608330240.0, 'timestamp': 1438122984.682779, 'maxtraffic': None, 'premium': True, 'login': 'USERID', 'password': '**********', 'type': 'UploadedTo', 'options': {}}}
29.07.2015 00:36:49 DEBUG     ACCOUNT UploadedTo : Account info for user `USERID`: {'login': {'timestamp': 1438122865.651502, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1439652985.738831, 'valid': True, 'trafficleft': 547608330240.0, 'timestamp': 1438122984.682779, 'maxtraffic': None, 'premium': True, 'login': 'USERID', 'password': '**********', 'type': 'UploadedTo', 'options': {}}}
29.07.2015 00:36:51 DEBUG     ACCOUNT UploadedTo : Account info for user `USERID`: {'login': {'timestamp': 1438122865.651502, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1439652985.738831, 'valid': True, 'trafficleft': 547608330240.0, 'timestamp': 1438122984.682779, 'maxtraffic': None, 'premium': True, 'login': 'USERID', 'password': '**********', 'type': 'UploadedTo', 'options': {}}}
29.07.2015 00:36:54 DEBUG     ACCOUNT UploadedTo : Account info for user `USERID`: {'login': {'timestamp': 1438122865.651502, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1439652985.738831, 'valid': True, 'trafficleft': 547608330240.0, 'timestamp': 1438122984.682779, 'maxtraffic': None, 'premium': True, 'login': 'USERID', 'password': '**********', 'type': 'UploadedTo', 'options': {}}}
+++++++++ STOPPED THE DOWNLOADS
29.07.2015 00:38:26 WARNING   Download failed: FILE | 'ReCaptcha' object has no attribute 'captcha'
Traceback (most recent call last):
  File "/home/benjamin/.local/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/benjamin/.local/pyload/module/plugins/internal/Hoster.py", line 183, in preprocessing
    return self.process(self.pyfile)
  File "/home/benjamin/.local/pyload/module/plugins/internal/SimpleHoster.py", line 293, in process
    self.handle_free(pyfile)
  File "/home/benjamin/.local/pyload/module/plugins/hoster/UploadedTo.py", line 75, in handle_free
    response, challenge = recaptcha.challenge()
  File "/home/benjamin/.local/pyload/module/plugins/captcha/ReCaptcha.py", line 51, in challenge
    version=2 if re.search(self.KEY_V2_PATTERN, data or self.retrieve_data()) else 1)
  File "/home/benjamin/.local/pyload/module/plugins/captcha/ReCaptcha.py", line 47, in challenge
    return getattr(self, "_challenge_v%s" % version)(key)
  File "/home/benjamin/.local/pyload/module/plugins/captcha/ReCaptcha.py", line 66, in _challenge_v1
    return self.result(server, challenge, key)
  File "/home/benjamin/.local/pyload/module/plugins/captcha/ReCaptcha.py", line 88, in result
    ocr=False)
  File "/home/benjamin/.local/pyload/module/plugins/internal/Captcha.py", line 53, in decrypt
    return self._decrypt(img, input_type, output_type, ocr, timeout)
  File "/home/benjamin/.local/pyload/module/plugins/internal/Captcha.py", line 110, in _decrypt
    self.captcha.invalid()
AttributeError: 'ReCaptcha' object has no attribute 'captcha'
29.07.2015 00:38:26 INFO      Debug Report written to debug_UploadedTo_29-07-2015_00-38-26.zip
29.07.2015 00:38:26 INFO      HOOK UnSkipOnFail : Looking for skipped duplicates of: FILE (pid:1)
29.07.2015 00:38:26 INFO      HOOK UnSkipOnFail : No duplicates found
29.07.2015 00:38:26 DEBUG     All downloads processed
```
