### ISSUE TITLE
[DLC] cannot add .dlc files:  'list' object has no attribute 'decode'

### ISSUE THREAD

**Issue by nordic-style** [pyload/pyload#1587]
tested with latest stable pyload. Just try to add any dlc file. I tested a lot and all failed.

Debug Log:
```
29.07.2015 00:43:39 INFO      Added package ASDF containing 1 links
29.07.2015 00:43:40 INFO      Decrypting starts: /media/Downloads/tmp_Vikings-S01E01-German-DL-1080p-BD-x-iNTENTiON.dlc
29.07.2015 00:43:40 DEBUG     CONTAINER DLC[6441] : PROCESS URL /media/Downloads/tmp_Vikings-S01E01-German-DL-1080p-BD-x-iNTENTiON.dlc
29.07.2015 00:43:40 DEBUG     CONTAINER DLC[6441] : LOAD URL http://service.jdownloader.org/dlcrypt/service.php?srcType=dlc&destType=pylo&data=TUhVMG1kYlBZZnVid2hwN0xTYnZ0aDcxeEZ4ZWZFZHBPcUZXQnp3RGdmTVh2b3kzZWlsKzRPY21VWUJXVHpJMg== | cookies=True | get={} | req=None | decode=True | just_header=False | post={} | ref=True
29.07.2015 00:43:40 WARNING   CONTAINER DLC[6441] : Config option `use_subfolder` not found, use default `True`
29.07.2015 00:43:40 WARNING   CONTAINER DLC[6441] : Config option `subfolder_per_package` not found, use default `True`
29.07.2015 00:43:40 DEBUG     CONTAINER DLC[6441] : Parsed package: Vikings S01E01 German DL 1080p BD x-iNTENTiON | 9 links | Saved to folder: Vikings S01E01 German DL 1080p BD x-iNTENTiON
29.07.2015 00:43:40 ERROR     Decrypting failed: tmp_Vikings-S01E01-German-DL-1080p-BD-x-iNTENTiON.dlc | 'list' object has no attribute 'decode'
Traceback (most recent call last):
  File "/media/bin/pyload/stable/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/media/bin/pyload/stable/module/plugins/internal/Hoster.py", line 183, in preprocessing
    return self.process(self.pyfile)
  File "/media/bin/pyload/stable/module/plugins/internal/Container.py", line 44, in process
    self._create_packages()
  File "/media/bin/pyload/stable/module/plugins/internal/Crypter.py", line 81, in _create_packages
    pid = self.pyload.api.addPackage(name, self.fixurl(links), package_queue)
  File "/media/bin/pyload/stable/module/plugins/internal/Hoster.py", line 348, in fixurl
    url = _fixurl(url)
  File "/media/bin/pyload/stable/module/plugins/internal/Plugin.py", line 46, in fixurl
    return html_unescape(urllib.unquote(url.decode('unicode-escape'))).strip()
AttributeError: 'list' object has no attribute 'decode'
```

**Comment by koroki** [comment]
Same problem here!

**Comment by snickers2k** [comment]
same here.. not only with DLCs, but with any crypter and any link

**Comment by mkli90** [comment]
dito
