### ISSUE TITLE
Old camel case in module/plugins/internal/Extractor.py

### ISSUE THREAD

**Issue by obli88** [pyload/pyload#1594]
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/home/pi/Programme/pyload/module/PluginThread.py", line 459, in run
    self.f(*self.args, **self.kwargs)
  File "/home/pi/Programme/pyload/module/plugins/hooks/ExtractArchive.py", line 205, in extract_queued
    if self.extract(packages, thread):  #@NOTE: check only if all gone fine, no failed reporting for now
  File "/home/pi/Programme/pyload/module/plugins/hooks/ExtractArchive.py", line 313, in extract
    targets = Extractor.get_targets(files_ids)
  File "/home/pi/Programme/pyload/module/plugins/internal/Extractor.py", line 70, in get_targets
    if cls.isArchive(fname):
AttributeError: type object 'UnRar' has no attribute 'isArchive'

Line 70: if cls.isArchive(fname): -> if cls.is_archive(fname):

**Comment by TodsDeath** [comment]
Next bug :( 
```
HOOK ExtractArchive: *****.rar | Unknown error | 'UnRar' object has no attribute 'getDeleteFiles' 
```

**Comment by vuolter** [comment]
Done.
