### ISSUE TITLE
AttributeError: 'AntiStandby' object has no attribute 'mtime'

### ISSUE THREAD

**Issue by obli88** [pyload/pyload#1595]
29.07.2015 11:03:16 ERROR     HOOK AntiStandby: Error executing addon: 'AntiStandby' object has no attribute 'mtime'
Traceback (most recent call last):
  File "/home/pi/Programme/pyload/module/plugins/internal/Addon.py", line 97, in _periodical
    self.periodical()
  File "/home/pi/Programme/pyload/module/plugins/hooks/AntiStandby.py", line 154, in periodical
    if (self.max_mtime(path) - self.mtime) < self.interval:
AttributeError: 'AntiStandby' object has no attribute 'mtime'
29.07.2015 11:03:42 ERROR     HOOK AntiStandby: Error executing addon: 'AntiStandby' object has no attribute 'mtime'
Traceback (most recent call last):
  File "/home/pi/Programme/pyload/module/plugins/internal/Addon.py", line 97, in _periodical
    self.periodical()
  File "/home/pi/Programme/pyload/module/plugins/hooks/AntiStandby.py", line 154, in periodical
    if (self.max_mtime(path) - self.mtime) < self.interval:
AttributeError: 'AntiStandby' object has no attribute 'mtime'
29.07.2015 11:04:08 ERROR     HOOK AntiStandby: Error executing addon: 'AntiStandby' object has no attribute 'mtime'
Traceback (most recent call last):
  File "/home/pi/Programme/pyload/module/plugins/internal/Addon.py", line 97, in _periodical
    self.periodical()
  File "/home/pi/Programme/pyload/module/plugins/hooks/AntiStandby.py", line 154, in periodical
    if (self.max_mtime(path) - self.mtime) < self.interval:
AttributeError: 'AntiStandby' object has no attribute 'mtime'

**Comment by Gutz-Pilz** [comment]
same issue here
