### ISSUE TITLE
ExternalScript.py invalid syntax

### ISSUE THREAD

**Issue by DKeppi** [pyload/pyload#1597]
ERROR	Fehler beim importieren von ExternalScripts: invalid syntax (ExternalScripts.py, line 79)

**Comment by Stufo76** [comment]
For me too:

ERROR	Errore durante l'importazione ExternalScripts: invalid syntax (ExternalScripts.py, line 79)

**Comment by Gutz-Pilz** [comment]
```
29.07.2015 12:37:08 ERROR     Fehler beim importieren von ExternalScripts: invalid syntax (ExternalScripts.py, line 79)
Traceback (most recent call last):
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/root/.pyload/userplugins/hooks/ExternalScripts.py", line 79
    self.scripts[name].append(file)
       ^
SyntaxError: invalid syntax
```
