### ISSUE TITLE
DatabaseBackend binding error

### ISSUE THREAD

**Issue by boerngen-schmidt** [pyload/pyload#1623]
Hey,

now that pyload seems to start running again I get this error in my logs.
```
Traceback (most recent call last):
  File "/home/xxx/.local/pyload/module/database/DatabaseBackend.py", line 96, in processJob
    self.result = self.f(*self.args, **self.kwargs)
  File "/home/xxx/.local/pyload/module/database/FileDatabase.py", line 767, in updateLink
    self.c.execute('UPDATE links SET url=?,name=?,size=?,status=?,error=?,package=? WHERE id=?', (f.url, f.name, f.size, f.status, f.error, str(f.packageid), str(f.id)))
InterfaceError: Error binding parameter 4 - probably unsupported type.
Database Error @ updateLink (PyFile 452: 9w6zmirb@UploadedTo,) {} Error binding parameter 4 - probably unsupported type.

```

**Comment by vuolter** [comment]
Already fixed in 0.4.10
