### ISSUE TITLE
'NoneType' object has no attribute 'http'  with 1fichier.com

### ISSUE THREAD

**Issue by b0m0x** [pyload/pyload#1634]
Log from 1fichier.com since last plugin update:
```
Download failed: file.rar | 'NoneType' object has no attribute 'http' 
```

**Comment by tatu007** [comment]
Hello, I have the same error

**Comment by mobo95** [comment]
same here on easybytez :)

**Comment by acidburn78** [comment]
same here for shareonline.biz

**Comment by DomiStyle** [comment]
Same for uploaded.net

```
31.07.2015 13:40:00 INFO      Download starts: ae288524-26b5-4436-ba61-d9203645a1ab
31.07.2015 13:40:00 WARNING   Download failed: ae288524-26b5-4436-ba61-d9203645a1ab | 'NoneType' object has no attribute 'http'
Traceback (most recent call last):
  File "/home/domi/pyload/module/PluginThread.py", line 186, in run
    self.m.core.hookManager.downloadPreparing(pyfile)
  File "/home/domi/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/home/domi/pyload/module/HookManager.py", line 214, in downloadPreparing
    plugin.downloadPreparing(pyfile)
  File "/home/domi/pyload/module/plugins/internal/Addon.py", line 170, in downloadPreparing
    return self.download_preparing(*args, **kwargs)
  File "/home/domi/pyload/module/plugins/hooks/UserAgentSwitcher.py", line 31, in download_preparing
    pyfile.plugin.req.http.c.setopt(pycurl.CONNECTTIMEOUT, connecttimeout)
AttributeError: 'NoneType' object has no attribute 'http'
31.07.2015 13:40:00 INFO      Debug Report written to debug_UploadedTo_31-07-2015_13-40-00.zip
31.07.2015 13:40:00 INFO      HOOK UnSkipOnFail: Looking for skipped duplicates of: ae288524-26b5-4436-ba61-d9203645a1ab (pid:85)
31.07.2015 13:40:00 INFO      HOOK UnSkipOnFail: No duplicates found
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/domi/pyload/module/PluginThread.py", line 312, in run
    self.clean(pyfile)
  File "/home/domi/pyload/module/PluginThread.py", line 147, in clean
    pyfile.release()
  File "/home/domi/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/home/domi/pyload/module/PyFile.py", line 146, in release
    self.plugin.clean()
  File "/home/domi/pyload/module/plugins/internal/Hoster.py", line 660, in clean
    self.req.close()
AttributeError: 'NoneType' object has no attribute 'close'
^C31.07.2015 13:40:45 INFO      shutting down...
Traceback (most recent call last):
  File "pyload/pyLoadCore.py", line 590, in shutdown
  File "/home/domi/pyload/module/PyFile.py", line 197, in abortDownload
    self.release()
  File "/home/domi/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/home/domi/pyload/module/PyFile.py", line 146, in release
    self.plugin.clean()
  File "/home/domi/pyload/module/plugins/internal/Hoster.py", line 660, in clean
    self.req.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by obli88** [comment]
I have the same problem with my crypter. Since Crypter inherits from Hoster "preprocessing" and "clean" are called.
  File "/home/pi/Programme/pyload/module/plugins/internal/Hoster.py", line 175, in preprocessing
    self.req.renewHTTPRequest()
AttributeError: 'NoneType' object has no attribute 'renewHTTPRequest'

Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/home/pi/Programme/pyload/module/PluginThread.py", line 407, in run
    self.active.release()
  File "/home/pi/Programme/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/home/pi/Programme/pyload/module/PyFile.py", line 146, in release
    self.plugin.clean()
  File "/home/pi/Programme/pyload/module/plugins/internal/Hoster.py", line 661, in clean
    self.req.close()
AttributeError: 'NoneType' object has no attribute 'close'

**Comment by zephura** [comment]
I provide debug_Report.txt in this post
https://github.com/pyload/pyload/issues/1640#issuecomment-126871526
