### ISSUE TITLE
Exception in thread Thread-2:

### ISSUE THREAD

**Issue by scrimpy** [pyload/pyload#1642]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/share/pyload/module/PluginThread.py", line 312, in run
    self.clean(pyfile)
  File "/usr/share/pyload/module/PluginThread.py", line 147, in clean
    pyfile.release()
  File "/usr/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/usr/share/pyload/module/PyFile.py", line 146, in release
    self.plugin.clean()
  File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 660, in clean
    self.req.close()
AttributeError: 'NoneType' object has no attribute 'close'

**Comment by nordic-style** [comment]
same here.

**Comment by nomad71** [comment]
Dito.

Also I get this and think it may be related:

```
'NoneType' object has no attribute 'http'
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 186, in run
    self.m.core.hookManager.downloadPreparing(pyfile)
  File "/usr/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/usr/share/pyload/module/HookManager.py", line 214, in downloadPreparing
    plugin.downloadPreparing(pyfile)
  File "/home/pi/.pyload/userplugins/internal/Addon.py", line 170, in downloadPreparing
    return self.download_preparing(*args, **kwargs)
  File "/home/pi/.pyload/userplugins/hooks/UserAgentSwitcher.py", line 31, in download_preparing
    pyfile.plugin.req.http.c.setopt(pycurl.CONNECTTIMEOUT, connecttimeout)
AttributeError: 'NoneType' object has no attribute 'http'
```

And this one when trying to restart the failed package.

```
Traceback (most recent call last):
  File "/usr/share/pyload/module/web/api_app.py", line 52, in call_api
    return callApi(func, *args, **kwargs)
  File "/usr/share/pyload/module/web/api_app.py", line 64, in callApi
    **dict([(x, literal_eval(y)) for x, y in kwargs.iteritems()]))
  File "/usr/share/pyload/module/Api.py", line 618, in restartPackage
    self.core.files.restartPackage(int(pid))
  File "/usr/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/usr/share/pyload/module/database/FileDatabase.py", line 68, in new
    return func(*args)
  File "/usr/share/pyload/module/database/FileDatabase.py", line 401, in restartPackage
    self.restartFile(pyfile.id)
  File "/usr/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/usr/share/pyload/module/database/FileDatabase.py", line 68, in new
    return func(*args)
  File "/usr/share/pyload/module/database/FileDatabase.py", line 419, in restartFile
    self.cache[id].abortDownload()
  File "/usr/share/pyload/module/PyFile.py", line 197, in abortDownload
    self.release()
  File "/usr/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/usr/share/pyload/module/PyFile.py", line 146, in release
    self.plugin.clean()
  File "/home/pi/.pyload/userplugins/internal/Hoster.py", line 660, in clean
    self.req.close()
AttributeError: 'NoneType' object has no attribute 'close'
An error occured while processing the request.
```

**Comment by nomad71** [comment]
It's everywhere! ^^

When shutting down:
```
^C01.08.2015 22:24:55 INFO      shutting down...
Traceback (most recent call last):
  File "/usr/bin/pyLoadCore", line 590, in shutdown
    pyfile.abortDownload()
  File "/usr/share/pyload/module/PyFile.py", line 197, in abortDownload
    self.release()
  File "/usr/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/usr/share/pyload/module/PyFile.py", line 146, in release
    self.plugin.clean()
  File "/home/pi/.pyload/userplugins/internal/Hoster.py", line 660, in clean
    self.req.close()
AttributeError: 'NoneType' object has no attribute 'close'
01.08.2015 22:24:55 INFO      error while shutting down

```
