### ISSUE TITLE
[UpdateManager] ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by NETHeader** [pyload/pyload#1645]
Deleted all userplugins ( = <configdir>/userplugins/*.py) to force an update due to the massive problems the last couple of days.
This is the result:

```
01.08.2015 18:43:43 INFO      Starting pyLoad 0.4.9
01.08.2015 18:43:43 INFO      Using home directory: /var/local/pyload
01.08.2015 18:43:43 DEBUG     Remote activated: False
01.08.2015 18:43:46 DEBUG     created index of plugins
01.08.2015 18:43:46 DEBUG     Redirected import module.plugins.hooks.NotifyGNTP -> userplugins.hooks.NotifyGNTP
01.08.2015 18:43:46 INFO      NotifyGNTP: Callback URI is 'http://10.0.1.1:8500'
01.08.2015 18:43:46 INFO      NotifyGNTP: path pluginfile = /var/local/pyload/userplugins/hooks
01.08.2015 18:43:46 INFO      NotifyGNTP: path workingdir = /var/local/pyload
01.08.2015 18:43:46 DEBUG     NotifyGNTP: logo=/usr/share/pyload/icons/logo.png
01.08.2015 18:43:47 INFO      NotifyGNTP: Registered at host '10.0.1.10:23053'
01.08.2015 18:43:47 DEBUG     UpdateManager: Monitoring file changes
01.08.2015 18:43:47 INFO      Activated plugins: ClickAndLoad, ExternalScripts, HotFolder, MergeFiles, NotifyGNTP, UpdateManager
01.08.2015 18:43:47 INFO      Deactivate plugins: ExtractArchive, IRCInterface, MultiHome, XMPPInterface
01.08.2015 18:43:47 INFO      Downloadtime: True
01.08.2015 18:43:47 INFO      Free space: 332.54 GiB
01.08.2015 18:43:47 INFO      Activating Accounts...
01.08.2015 18:43:47 INFO      Activating Plugins...
01.08.2015 18:43:47 INFO      ClickAndLoad: Proxy listening on 0.0.0.0:9666
01.08.2015 18:43:47 INFO      pyLoad is up and running
01.08.2015 18:43:49 INFO      Starting threaded webserver: 0.0.0.0:8500
01.08.2015 18:43:49 ERROR     Error executing hooks: need more than 2 values to unpack
Traceback (most recent call last):
  File "/usr/share/pyload/module/plugins/Hook.py", line 100, in _periodical
    if self.isActivated(): self.periodical()
  File "/usr/share/pyload/module/plugins/hooks/UpdateManager.py", line 181, in checkChanges
    root, type, name = m.__name__.rsplit(".", 2)
ValueError: need more than 2 values to unpack
01.08.2015 18:43:51 WARNING   Not able to connect server for updates
01.08.2015 18:43:51 INFO      No Updates for pyLoad
01.08.2015 18:43:53 ERROR     Error executing hooks: need more than 2 values to unpack
Traceback (most recent call last):
  File "/usr/share/pyload/module/plugins/Hook.py", line 100, in _periodical
    if self.isActivated(): self.periodical()
  File "/usr/share/pyload/module/plugins/hooks/UpdateManager.py", line 181, in checkChanges
    root, type, name = m.__name__.rsplit(".", 2)
ValueError: need more than 2 values to unpack
01.08.2015 18:43:53 WARNING   Not able to connect server for updates
01.08.2015 18:43:53 INFO      No plugin updates available
01.08.2015 18:43:57 ERROR     Error executing hooks: need more than 2 values to unpack
Traceback (most recent call last):
  File "/usr/share/pyload/module/plugins/Hook.py", line 100, in _periodical
    if self.isActivated(): self.periodical()
  File "/usr/share/pyload/module/plugins/hooks/UpdateManager.py", line 181, in checkChanges
    root, type, name = m.__name__.rsplit(".", 2)
ValueError: need more than 2 values to unpack
^C
01.08.2015 18:44:00 INFO      shutting down...
01.08.2015 18:44:00 DEBUG     Deleting old pidfile pyload.pid
01.08.2015 18:44:00 INFO      killed pyLoad from Terminal
```

**Comment by GammaC0de** [comment]
This is because the old `UpdateManager.py` (v0.11) bundled with v0.4.9, checks for updates in `http://get.pyload.org/plugins/check/` which recently have stopped working.
In fact, you cannot download any file presented in http://pyload.org/download.

**Comment by NETHeader** [comment]
I've cloned the current stable tree into my pyload directory. After this manual update pyload is now working again (beside of small issues discussed here anyway).
