### ISSUE TITLE
Remote backend error: (98, 'Address already in use')

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1647]
```
02.08.2015 00:09:20 INFO      Starting pyLoad 0.4.9
02.08.2015 00:09:20 INFO      Using home directory: /etc/pyload
02.08.2015 00:09:20 DEBUG     Remote activated: True
02.08.2015 00:09:29 DEBUG     created index of plugins
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
02.08.2015 00:09:29 DEBUG     HOOK ExternalScripts: Deprecated method `event_list`, use `event_map` instead
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.hooks.Captcha9Kw -> userplugins.hooks.Captcha9Kw
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.internal.Hook -> userplugins.internal.Hook
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.hooks.AntiStandby -> userplugins.hooks.AntiStandby
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.hooks.LinkdecrypterComHook -> userplugins.hooks.LinkdecrypterComHook
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.internal.MultiHook -> userplugins.internal.MultiHook
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.crypter.LinkdecrypterCom -> userplugins.crypter.LinkdecrypterCom
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.internal.MultiCrypter -> userplugins.internal.MultiCrypter
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.internal.SimpleCrypter -> userplugins.internal.SimpleCrypter
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.internal.Crypter -> userplugins.internal.Crypter
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.internal.Hoster -> userplugins.internal.Hoster
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.internal.Captcha -> userplugins.internal.Captcha
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.hooks.ClickAndLoad -> userplugins.hooks.ClickAndLoad
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
02.08.2015 00:09:29 DEBUG     Redirected import module.plugins.hooks.XFileSharingPro -> userplugins.hooks.XFileSharingPro
02.08.2015 00:09:29 INFO      Activated plugins: AntiStandby, Captcha9Kw, ClickAndLoad, ExternalScripts, LinkdecrypterComHook, UnSkipOnFail, UpdateManager, XFileSharingPro
02.08.2015 00:09:29 INFO      Deactivate plugins: AlldebridComHook, AndroidPhoneNotify, AntiVirus, BypassCaptcha, CaptchaBrotherhood, Checksum, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, ExpertDecoders, ExtractArchive, FastixRuHook, FreeWayMeHook, HighWayMe, HighWayMeHook, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinksnappyComHook, MegaDebridEuHook, MegaRapidoNetHook, MergeFiles, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridComHook, RehostToHook, RestartFailed, RestartSlow, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, UnrestrictLiHook, UserAgentSwitcher, WindowsPhoneNotify, XMPPInterface, ZeveraComHook
02.08.2015 00:09:29 INFO      Downloadtime: True
02.08.2015 00:09:30 INFO      Starting ThriftBackend: 0.0.0.0:7227
02.08.2015 00:09:30 INFO      Free space: 0.58 TiB
02.08.2015 00:09:30 INFO      Activating Accounts...
02.08.2015 00:09:30 INFO      Activating Plugins...
02.08.2015 00:09:33 ERROR     Remote backend error: (98, 'Address already in use')
Traceback (most recent call last):
  File "/share/pyload/module/remote/RemoteManager.py", line 33, in run
02.08.2015 00:09:33 INFO      Starting threaded webserver: 0.0.0.0:8000
    self.serve()
  File "/share/pyload/module/remote/ThriftBackend.py", line 56, in serve
    self.server.serve()
  File "/share/pyload/module/lib/thrift/server/TServer.py", line 101, in serve
    self.serverTransport.listen()
  File "/share/pyload/module/remote/thriftbackend/Socket.py", line 122, in listen
    self.handle.bind((self.host, self.port))
  File "<string>", line 1, in bind
error: (98, 'Address already in use')
^C02.08.2015 00:09:44 INFO      shutting down...
02.08.2015 00:09:44 WARNING   HOOK AntiStandby: Unable to change power state | [Errno 2] No such file or directory
02.08.2015 00:09:44 DEBUG     Deleting old pidfile /var/run/pyload.pid
02.08.2015 00:09:44 INFO      killed pyLoad from Terminal
```

**Comment by vuolter** [comment]
?
