### ISSUE TITLE
HTTP Response 500 Web GUI Downloads Page

### ISSUE THREAD

**Issue by Sporrdig** [pyload/pyload#1652]
Web Page Error:

HTTP Response 500

Traceback (most recent call last):
 File "/xxx/pyload/module/lib/bottle.py", line 733, in _handle
 return route.call(*_args)
 File "/xxx/pyload/module/lib/bottle.py", line 1448, in wrapper
 rv = callback(_a, *_ka)
 File "/xxx/pyload/module/web/utils.py", line 113, in _view
 return func(_args, **kwargs)
 File "/xxx/module/web/pyload_app.py", line 209, in downloads
 for file in sorted([fs_decode(x) for x in files]):
UnicodeDecodeError: 'ascii' codec can't decode byte 0x81 in position 40: ordinal not in range(128)

**Comment by foxxx0** [comment]
confirmed, getting the same error using the latest pyload-stable.zip (except mine is choking on a 0x88 byte)
