### ISSUE TITLE
ShareOnline.biz Account only working the first time, after timeout its broken again

### ISSUE THREAD

**Issue by dannoe** [pyload/pyload#1657]
first login is working, after the timeout it will break again

Log: (i only changed my username in "myusername")

16966 02.08.2015 11:19:30 WARNING ACCOUNT ShareonlineBiz: Could not login user myusername | 'password'
16965 02.08.2015 11:19:30 INFO ACCOUNT ShareonlineBiz: Relogin user myusername...
16964 02.08.2015 11:19:30 DEBUG ACCOUNT ShareonlineBiz: Reached login timeout for myusername

**Comment by nordic-style** [comment]
It is the same for uploaded.to
Debug log:
```
02.08.2015 11:27:30 INFO      Download starts: 15S0H06S5F01H56SF10H.part021.rar
02.08.2015 11:27:30 DEBUG     HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
02.08.2015 11:27:30 DEBUG     ACCOUNT UploadedTo: Reached login timeout for 666666
02.08.2015 11:27:30 INFO      ACCOUNT UploadedTo: Relogin user `666666`...
02.08.2015 11:27:30 WARNING   ACCOUNT UploadedTo: Could not login user `666666` | 'password'
Traceback (most recent call last):
  File "/media/bin/pyload/stable/module/plugins/internal/Account.py", line 60, in _login
    self.login(user, info['login']['password'], info['data'], self.req)
KeyError: 'password'
02.08.2015 11:27:30 DEBUG     HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
02.08.2015 11:27:30 DEBUG     HOSTER UploadedTo[100]: PROCESS URL http://uploaded.net/file/n0vgeb08 | PLUGIN VERSION 0.96
02.08.2015 11:27:30 INFO      HOSTER UploadedTo[100]: Updating file info...
02.08.2015 11:27:30 DEBUG     HOSTER UploadedTo[100]: File info: {'status': 2, 'url': u'http://uploaded.net/file/n0vgeb08', 'size': 157286400.0, 'name': '15S0H06S5F01H56SF10H.part021.rar', 'pattern': {'ID': u'n0vgeb08'}}
02.08.2015 11:27:30 DEBUG     HOSTER UploadedTo[100]: Previous file info: {}
02.08.2015 11:27:30 INFO      HOSTER UploadedTo[100]: File name: 15S0H06S5F01H56SF10H.part021.rar
02.08.2015 11:27:30 INFO      HOSTER UploadedTo[100]: File size: 157286400 bytes
02.08.2015 11:27:30 INFO      HOSTER UploadedTo[100]: File status: online
02.08.2015 11:27:30 DEBUG     HOSTER UploadedTo[100]: LOAD URL http://uploaded.net/file/n0vgeb08 | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
02.08.2015 11:27:31 INFO      HOSTER UploadedTo[100]: Processing as free download...
```

**Comment by nordic-style** [comment]
Since uploaded.to falls back to free account i get another strange error after entering the captcha. I don't know if it is directly related. Please take a look at it:

```
02.08.2015 11:33:40 INFO      Download starts: 15S0H06S5F01H56SF10H.part021.rar
02.08.2015 11:33:40 DEBUG     HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
02.08.2015 11:33:40 DEBUG     HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
02.08.2015 11:33:40 DEBUG     HOSTER UploadedTo[100]: PROCESS URL http://uploaded.net/file/n0vgeb08 | PLUGIN VERSION 0.96
02.08.2015 11:33:40 INFO      HOSTER UploadedTo[100]: Updating file info...
02.08.2015 11:33:40 DEBUG     HOSTER UploadedTo[100]: File info: {'status': 2, 'name': '15S0H06S5F01H56SF10H.part021.rar', 'url': u'http://uploaded.net/file/n0vgeb08', 'pattern': {'ID': u'n0vgeb08'}, 'folder': '15S0H06S5F01H56SF10H.part021.rar', 'size': 157286400.0}
02.08.2015 11:33:40 DEBUG     HOSTER UploadedTo[100]: Previous file info: {'status': 2, 'name': '15S0H06S5F01H56SF10H.part021.rar', 'url': u'http://uploaded.net/file/n0vgeb08', 'pattern': {'ID': u'n0vgeb08'}, 'folder': '15S0H06S5F01H56SF10H.part021.rar', 'size': 157286400.0}
02.08.2015 11:33:40 INFO      HOSTER UploadedTo[100]: File name: 15S0H06S5F01H56SF10H.part021.rar
02.08.2015 11:33:40 INFO      HOSTER UploadedTo[100]: File size: 157286400 bytes
02.08.2015 11:33:40 INFO      HOSTER UploadedTo[100]: File status: online
02.08.2015 11:33:40 DEBUG     HOSTER UploadedTo[100]: LOAD URL http://uploaded.net/file/n0vgeb08 | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
02.08.2015 11:33:40 INFO      HOSTER UploadedTo[100]: Processing as free download...
02.08.2015 11:33:40 DEBUG     HOSTER UploadedTo[100]: LOAD URL http://uploaded.net/language/en | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
02.08.2015 11:33:40 DEBUG     HOSTER UploadedTo[100]: LOAD URL http://uploaded.net/js/download.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
02.08.2015 11:33:40 DEBUG     CAPTCHA UploadedTo[100]: ReCaptcha | Key: 6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3
02.08.2015 11:33:40 DEBUG     HOSTER UploadedTo[100]: LOAD URL http://www.google.com/recaptcha/api/challenge | cookies=True | get={'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
02.08.2015 11:33:41 DEBUG     CAPTCHA UploadedTo[100]: ReCaptcha | Challenge: 03AHJ_VuvMnsDsYPBtqo6okaklH4bDCZGPLrcu6MzV4hNqZQPASWw4uuQtWQSz65_MQkqkPuZdux5sLLSJJBuZG6H-e_kW18hclodf2ziqj1V6c35ca0qEpSqusBhm7MJVF_A4RsLxa-VzDURyToT1GJih4eVl1FCWrYNT9k0vvRlkiiNmEMDdjyTOPlz_GVNgaPMW-bPwuM5fYF81ewUu_AS9luv9Fk6e3g
02.08.2015 11:33:41 DEBUG     HOSTER UploadedTo[100]: LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
02.08.2015 11:33:41 DEBUG     HOSTER UploadedTo[100]: LOAD URL http://www.google.com/recaptcha/api/reload | cookies=True | get={'reason': 'i', 'c': u'03AHJ_VuvMnsDsYPBtqo6okaklH4bDCZGPLrcu6MzV4hNqZQPASWw4uuQtWQSz65_MQkqkPuZdux5sLLSJJBuZG6H-e_kW18hclodf2ziqj1V6c35ca0qEpSqusBhm7MJVF_A4RsLxa-VzDURyToT1GJih4eVl1FCWrYNT9k0vvRlkiiNmEMDdjyTOPlz_GVNgaPMW-bPwuM5fYF81ewUu_AS9luv9Fk6e3g', 'type': 'image', 'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
02.08.2015 11:33:41 DEBUG     CAPTCHA UploadedTo[100]: ReCaptcha | Second challenge: 03AHJ_VusgsI3XZ4oxNorbgaexUMH3h-D60b2KlomPABXcGNQF9ELo1HLFLse8tdEij1Uc-PbcOD0trIyp-6MTZflWVJvPIpuqlozYFzmB6UlYKCfc0P1_mVjs8Cnq6KojHlDQdVjPyX0LY3K4q83UvevB_4IUn0UW64tk9KH4lGEHIN9DQJjNlM0SFx95HX0wtXSDkySdmEqU5v7oS3hQlh2bDZxAQgA56w
02.08.2015 11:33:41 DEBUG     CAPTCHA UploadedTo[100]: ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | cookies=True | get={'c': u'03AHJ_VusgsI3XZ4oxNorbgaexUMH3h-D60b2KlomPABXcGNQF9ELo1HLFLse8tdEij1Uc-PbcOD0trIyp-6MTZflWVJvPIpuqlozYFzmB6UlYKCfc0P1_mVjs8Cnq6KojHlDQdVjPyX0LY3K4q83UvevB_4IUn0UW64tk9KH4lGEHIN9DQJjNlM0SFx95HX0wtXSDkySdmEqU5v7oS3hQlh2bDZxAQgA56w'} | req=None | decode=False | multipart=False | post={} | ref=False | just_header=False
02.08.2015 11:34:02 INFO      CAPTCHA UploadedTo[100]: ReCaptcha | Captcha result: aimoney could
02.08.2015 11:34:02 DEBUG     CAPTCHA UploadedTo[100]: ReCaptcha | Result: aimoney could
02.08.2015 11:34:02 DEBUG     HOSTER UploadedTo[100]: LOAD URL http://uploaded.net/io/ticket/captcha/n0vgeb08 | cookies=True | get={} | req=None | decode=True | multipart=False | post={'recaptcha_challenge_field': u'03AHJ_VusgsI3XZ4oxNorbgaexUMH3h-D60b2KlomPABXcGNQF9ELo1HLFLse8tdEij1Uc-PbcOD0trIyp-6MTZflWVJvPIpuqlozYFzmB6UlYKCfc0P1_mVjs8Cnq6KojHlDQdVjPyX0LY3K4q83UvevB_4IUn0UW64tk9KH4lGEHIN9DQJjNlM0SFx95HX0wtXSDkySdmEqU5v7oS3hQlh2bDZxAQgA56w', 'recaptcha_response_field': 'aimoney could'} | ref=True | just_header=False
02.08.2015 11:34:03 DEBUG     HOSTER UploadedTo[100]: Config option `fallback` not found, use default `True`
02.08.2015 11:34:03 WARNING   Download failed: 15S0H06S5F01H56SF10H.part021.rar | Parse error: Free download link not found | Plugin may be out of date
02.08.2015 11:34:03 INFO      HOOK UnSkipOnFail: Looking for skipped duplicates of: 15S0H06S5F01H56SF10H.part021.rar (pid:13)
02.08.2015 11:34:03 INFO      HOOK UnSkipOnFail: No duplicates found
Traceback (most recent call last):
  File "/media/bin/pyload/stable/modulebasebaseBackend.py", line 96, in processJob
    self.result = self.f(*self.args, **self.kwargs)
  File "/media/bin/pyload/stable/modulebase/FileDatabase.py", line 767, in updateLink
    self.c.execute('UPDATE links SET url=?,name=?,size=?,status=?,error=?,package=? WHERE id=?', (f.url, f.name, f.size, f.status, f.error, str(f.packageid), str(f.id)))
InterfaceError: Error binding parameter 4 - probably unsupported type.
Database Error @ updateLink (PyFile 100: 15S0H06S5F01H56SF10H.part021.rar@UploadedTo,) {} Error binding parameter 4 - probably unsupported type.
02.08.2015 11:34:03 DEBUG     All downloads processed
```

**Comment by vuolter** [comment]
Guys, start posting debug_.* files you found under your config dir, otherwise I can not help. u.u

**Comment by hardy123480** [comment]
I have the same problem. After 2 or 3 working downloads it switches to "Status: not valid" but strangely "Premium: yes" in the settings. This is my DEBUG log:

02.08.2015 18:48:49 INFO      HOSTER ShareonlineBiz[8086]: Processing as premium download...
02.08.2015 18:48:49 WARNING   Download failed: xxx.part04.rar | 'password'
Traceback (most recent call last):
  File "/share/HDA_DATA/.qpkg/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/share/HDA_DATA/.qpkg/pyload/data/userplugins/internal/Hoster.py", line 184, in preprocessing
    return self.process(self.pyfile)
  File "/share/HDA_DATA/.qpkg/pyload/data/userplugins/internal/SimpleHoster.py", line 288, in process
    self.handle_premium(pyfile)
  File "/share/HDA_DATA/.qpkg/pyload/data/userplugins/hoster/ShareonlineBiz.py", line 127, in handle_premium
    'password': self.account.get_info(self.user)['login']['password'],
KeyError: 'password'
02.08.2015 18:48:50 DEBUG     Error creating zip file: 'ascii' codec can't decode byte 0x86 in position 11: ordinal not in range(128)
02.08.2015 18:48:50 INFO      Debug Report written to debug_ShareonlineBiz_02-08-2015_18-48-49.txt

**Comment by dannoe** [comment]
https://gist.github.com/dannoe/d961c29e00cc02a137af

**Comment by no-Legend** [comment]
Now the first login is also not possible.

385	03.08.2015 08:04:31	DEBUG	ACCOUNT ShareonlineBiz: Account info for user `XXXXXXXXXXX`: {'login': {'timestamp': 1438581871.152747, 'password': '**********', 'valid': False}, 'data': {'premium': None, 'trafficleft': None, 'options': {}, 'maxtraffic': None, 'validuntil': None, 'login': 'XXXXXXXXXXX', 'password': '**********', 'type': 'ShareonlineBiz', 'valid': False}}
384	03.08.2015 08:04:31	INFO	ACCOUNT ShareonlineBiz: Parsing account info for user `XXXXXXXXXXX`... 
383	03.08.2015 08:04:31	DEBUG	ACCOUNT ShareonlineBiz: Scheduled refresh for user `XXXXXXXXXXX` in 0 seconds
382	03.08.2015 08:04:31	WARNING	ACCOUNT ShareonlineBiz: Could not login user `XXXXXXXXXXX` | 'ShareonlineBiz' object has no attribute 'COOKIES'
381	03.08.2015 08:04:31	DEBUG	ACCOUNT ShareonlineBiz: LOAD URL https://api.share-online.biz/cgi-bin | cookies=True | get={'q': 'userdetails', 'aux': 'traffic', 'username': 'XXXXXXXXXXX', 'password': 'aigvzPD3'} | req=None | decode=False | multipart=False | post={} | ref=True | just_header=False
380	03.08.2015 08:04:31	INFO	ACCOUNT ShareonlineBiz: Login user `XXXXXXXXXXX`...

**Comment by sraedler** [comment]
please close, share-online is working
