### ISSUE TITLE
uploaded_to plugin not working | UnboundLocalError

### ISSUE THREAD

**Issue by bernhard-da** [pyload/pyload#1662]
after a new installation from using pyload-git on a fully up-to-date archlinux.

```
Aug 02 13:47:44 serveroo pyLoadCore[5638]: 02.08.2015 13:47:44 INFO      ACCOUNT UploadedTo: Login user `xxxxxxxx`...
Aug 02 13:47:44 serveroo pyLoadCore[5638]: Traceback (most recent call last):
Aug 02 13:47:44 serveroo pyLoadCore[5638]: File "/usr/bin/pyLoadCore", line 667, in <module>
Aug 02 13:47:44 serveroo pyLoadCore[5638]: main()
Aug 02 13:47:44 serveroo pyLoadCore[5638]: File "/usr/bin/pyLoadCore", line 658, in main
Aug 02 13:47:44 serveroo pyLoadCore[5638]: pyload_core.start()
Aug 02 13:47:44 serveroo pyLoadCore[5638]: File "/usr/bin/pyLoadCore", line 433, in start
Aug 02 13:47:44 serveroo pyLoadCore[5638]: self.accountManager.getAccountInfos()
Aug 02 13:47:44 serveroo pyLoadCore[5638]: File "/opt/pyload/module/utils.py", line 165, in new
Aug 02 13:47:44 serveroo pyLoadCore[5638]: return func(*args)
Aug 02 13:47:44 serveroo pyLoadCore[5638]: File "/opt/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
Aug 02 13:47:44 serveroo pyLoadCore[5638]: p = self.getAccountPlugin(p)
Aug 02 13:47:44 serveroo pyLoadCore[5638]: File "/opt/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
Aug 02 13:47:44 serveroo pyLoadCore[5638]: self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
Aug 02 13:47:44 serveroo pyLoadCore[5638]: File "/opt/pyload/module/plugins/internal/Account.py", line 36, in __init__
Aug 02 13:47:44 serveroo pyLoadCore[5638]: self.init_accounts(accounts)
Aug 02 13:47:44 serveroo pyLoadCore[5638]: File "/opt/pyload/module/plugins/internal/Account.py", line 97, in init_accounts
Aug 02 13:47:44 serveroo pyLoadCore[5638]: self.add(user, data['password'], data['options'])
Aug 02 13:47:44 serveroo pyLoadCore[5638]: File "/opt/pyload/module/utils.py", line 165, in new
Aug 02 13:47:44 serveroo pyLoadCore[5638]: return func(*args)
Aug 02 13:47:44 serveroo pyLoadCore[5638]: File "/opt/pyload/module/plugins/internal/Account.py", line 120, in add
Aug 02 13:47:44 serveroo pyLoadCore[5638]: self._login(user)
Aug 02 13:47:44 serveroo pyLoadCore[5638]: File "/opt/pyload/module/utils.py", line 165, in new
Aug 02 13:47:44 serveroo pyLoadCore[5638]: return func(*args)
Aug 02 13:47:44 serveroo pyLoadCore[5638]: File "/opt/pyload/module/plugins/internal/Account.py", line 77, in _login
Aug 02 13:47:44 serveroo pyLoadCore[5638]: return res
Aug 02 13:47:44 serveroo pyLoadCore[5638]: UnboundLocalError: local variable 'res' referenced before assignment
```

**Comment by vuolter** [comment]
What is the __version__ of your Account.py?

**Comment by SWW13** [comment]
Try to reinstall the pyload-git package (or rebuild it) and then disable updatemanager before you start the pyload service.
Should be somewhere in ```/var/lib/pyload/plugin.conf```.

**Comment by bernhard-da** [comment]
@vuolter in class Account(Plugin), __version__="0.14"

@SWW13 i tried and set bool activated: "Activated" = False but got the same error.

can I provide anything else?

**Comment by vuolter** [comment]
@bernhard-da Its debug_.* file would be much appreciated. You can find it in your pyload config directory.

**Comment by bernhard-da** [comment]
i did a grep in both /opt/pyload and of my personal config (~/.pyload/) looking for files debug_* after setting `bool debug_mode : "Debug Mode" = True` in pyload.conf but i didn't find any debug* files. what is the exact name of the file i should look for?

**Comment by joberreiter** [comment]
> what is the exact name of the file i should look for?

`debug_*.zip`
You could try executing `sudo find / -name "debug_*.zip" 2>/dev/null` to locate them.

I think it is obvious, but nevertheless shall be mentioned: The debug logs are created only after a restart (with debug mode on) and after the error had risen.

**Comment by sraedler** [comment]
please close, it's working
