### ISSUE TITLE
UpdateManager, AniStreamCom plugin runs into TypeError

### ISSUE THREAD

**Issue by redimp** [pyload/pyload#1669]
When starting pyload, its runs into this TypeError Exception every time.

<pre>02.08.2015 21:53:11 INFO      HOOK UpdateManager : New plugin: [account] AniStreamCom (v0.01)
Traceback (most recent call last):
  File "./pyLoadCore.py", line 667, in <module>
    main()
  File "./pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "./pyLoadCore.py", line 469, in start
    self.scheduler.work()
  File "/home/pyload/pyload/module/Scheduler.py", line 85, in work
    j.start()
  File "/home/pyload/pyload/module/Scheduler.py", line 111, in start
    self.run()
  File "/home/pyload/pyload/module/Scheduler.py", line 101, in run
    ret = self.call(*self.args, **self.kwargs)
  File "/home/pyload/.pyload/userplugins/internal/Addon.py", line 100, in _periodical
    self.log_error(_("Error executing addon: %s") % e)
  File "/home/pyload/.pyload/userplugins/internal/Plugin.py", line 191, in log_error
    return self._log("error", self.__type__, self.__name__, args)
  File "/home/pyload/.pyload/userplugins/internal/Hook.py", line 28, in _log
    return super(self.__name__, self)._log(level, plugintype, pluginname.replace("Hook", ""), messages)
TypeError: must be type, not str</pre>

**Comment by Velociraptor85** [comment]
@GammaC0de close?
