### ISSUE TITLE
HTTP Response 500 in Settings Menu

### ISSUE THREAD

**Issue by Sle3perX** [pyload/pyload#1693]
Hi, the next error.
I get this when i try to open the settings tab in pyload under my Synology NAS - 5.2.

An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/opt/pyload/module/web/utils.py", line 113, in _view
return func(*args, **kwargs)
File "/opt/pyload/module/web/pyload_app.py", line 256, in config
accs = PYLOAD.getAccounts(False)
File "/opt/pyload/module/Api.py", line 875, in getAccounts
accs = self.core.accountManager.getAccountInfos(False, refresh)
File "/opt/pyload/module/utils.py", line 165, in new
return func(*args)
File "/opt/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
p = self.getAccountPlugin(p)
File "/opt/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
File "/volume1/Festplatte 1/Sonstiges/pyload/userplugins/internal/Account.py", line 36, in __init__
self.init_accounts(accounts)
File "/volume1/Festplatte 1/Sonstiges/pyload/userplugins/internal/Account.py", line 97, in init_accounts
self.add(user, data['password'], data['options'])
UnboundLocalError: local variable 'res' referenced before assignment

At the moment pyload is not usable for me :(

**Comment by Sle3perX** [comment]
I just got it working again.
Just deleted my Accounts in the "accounts.conf" and now it is working.
