### ISSUE TITLE
uploaded has no attribute "COOKIES"

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#1694]
```
04.08.2015 10:13:06 WARNING   ACCOUNT UploadedTo: Could not login user `13345xxx` | 'UploadedTo' object has no attribute 'COOKIES'
Traceback (most recent call last):
  File "/root/.pyload/userplugins/internal/Account.py", line 59, in _login
    self.login(user, info['login']['password'], info['data'], self.req)
  File "/root/.pyload/userplugins/accounts/UploadedTo.py", line 65, in login
    self.load("http://uploaded.net/language/en")
  File "/root/.pyload/userplugins/internal/Plugin.py", line 337, in load
    if isinstance(self.COOKIES, list):
AttributeError: 'UploadedTo' object has no attribute 'COOKIES'
```

**Comment by mobo95** [comment]
same

**Comment by FRYYYYYY** [comment]
Same for ShareOnline.

**Comment by Gutz-Pilz** [comment]
https://github.com/pyload/pyload/pull/1696/files

^^this will fix it
