### ISSUE TITLE
Account log in not working when running non debug mode

### ISSUE THREAD

**Issue by boerngen-schmidt** [pyload/pyload#1730]
Hey

when I run pyload in debug mode I get the following output
```
06.08.2015 19:13:25 INFO      Activating Accounts...
06.08.2015 19:13:25 INFO      ACCOUNT PremiumizeMe: Login user `xxx`...
06.08.2015 19:13:25 DEBUG     ACCOUNT PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php | cookies=True | get={'params[pass]': 'xxx', 'params[login]': 'xxx', 'method': 'accountstatus'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
06.08.2015 19:13:25 WARNING   ACCOUNT PremiumizeMe: Could not login user `xxx` | Login handshake has failed
Traceback (most recent call last):
  File "/home/benjamin/.local/pyload/module/plugins/internal/Account.py", line 59, in _login
    self.login(user, info['login']['password'], info['data'], self.req)
  File "/home/benjamin/.local/pyload/module/plugins/accounts/PremiumizeMe.py", line 39, in login
    self.login_fail()
  File "/home/benjamin/.local/pyload/module/plugins/internal/Account.py", line 274, in login_fail
    return self.fail(reason)
  File "/home/benjamin/.local/pyload/module/plugins/internal/Plugin.py", line 294, in fail
    raise Fail(encode(reason))  #@TODO: Remove `encode` in 0.4.10
Fail: Login handshake has failed
06.08.2015 19:13:25 INFO      ACCOUNT PremiumizeMe: Parsing account info for user `905214554`...
06.08.2015 19:13:25 DEBUG     ACCOUNT PremiumizeMe: Account info for user `xxx`: {'login': {'timestamp': 1438881205.104186, 'password': '**********', 'valid': False}, 'data': {'premium': None, 'trafficleft': None, 'options': {}, 'maxtraffic': None, 'validuntil': None, 'login': 'xxx', 'password': '**********', 'type': 'PremiumizeMe', 'valid': False}}
06.08.2015 19:13:25 INFO      ACCOUNT UploadedTo: Login user `xxx`...
06.08.2015 19:13:25 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/language/en | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
06.08.2015 19:13:25 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/io/login | cookies=True | get={} | req=None | decode=True | multipart=False | post={'id': 'xxx', 'pw': 'xxx'} | ref=True | just_header=False
06.08.2015 19:13:25 INFO      ACCOUNT UploadedTo: Parsing account info for user `xxx`...
06.08.2015 19:13:25 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
06.08.2015 19:13:25 DEBUG     ACCOUNT UploadedTo: Account info for user `xxx`: {'login': {'timestamp': 1438881205.201856, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'trafficleft': 547608330240.0, 'options': {}, 'maxtraffic': None, 'validuntil': 1439651605.581777, 'login': '13245778', 'password': '**********', 'type': 'UploadedTo', 'valid': True}}
06.08.2015 19:13:25 INFO      Activating Plugins...
```

BUT when I normally run pyload I get this 
```
28	06.08.2015 19:14:52	INFO	Activating Accounts...
29	06.08.2015 19:14:52	INFO	ACCOUNT PremiumizeMe: Login user `905214554`...
30	06.08.2015 19:14:52	WARNING	ACCOUNT PremiumizeMe: Could not login user `905214554` | 'PremiumizeMe' object has no attribute 'COOKIES'
31	06.08.2015 19:14:52	INFO	ACCOUNT PremiumizeMe: Parsing account info for user `905214554`...
32	06.08.2015 19:14:52	INFO	ACCOUNT UploadedTo: Login user `13245778`...
33	06.08.2015 19:14:52	WARNING	ACCOUNT UploadedTo: Could not login user `13245778` | 'UploadedTo' object has no attribute 'COOKIES'
34	06.08.2015 19:14:52	INFO	ACCOUNT UploadedTo: Parsing account info for user `13245778`...
35	06.08.2015 19:14:52	INFO	Activating Plugins... 
```
and the accounts are not logged in.

**Comment by boerngen-schmidt** [comment]
Do not mind the premiumize failure, that was a wrong password

**Comment by GammaC0de** [comment]
@boerngen-schmidt from a look at the logs i can see that your `internal/plugin.py` is not up to date, please manual update from https://github.com/pyload/pyload/raw/stable/module/plugins/internal/Plugin.py then try again.

**Comment by boerngen-schmidt** [comment]
I'm using a clone of the current master and pulled changes yesterday, where it still was not working. I'll try again once I get the chance and will compare the versions of the files

**Comment by GammaC0de** [comment]
you should get the `stable` branch, not `master`.

**Comment by boerngen-schmidt** [comment]
Yeah seems to be working again after I switched between branches master and back to stable (which I was on!)

Anyhow I close this bug for now.

**Comment by boerngen-schmidt** [comment]
Von meinem iPhone gesendet
