### ISSUE TITLE
Premiumize Account not working

### ISSUE THREAD

**Issue by georg94** [pyload/pyload#1740]
When I try to add a new Premiumize Account I get this error:
```
10.08.2015 23:36:12 DEBUG     Redirected import module.plugins.accounts.PremiumizeMe -> userplugins.accounts.PremiumizeMe
10.08.2015 23:36:12 DEBUG     Redirected import module.plugins.internal.Account -> userplugins.internal.Account
10.08.2015 23:36:12 INFO      ACCOUNT PremiumizeMe: Login user `0123456789`...
10.08.2015 23:36:12 DEBUG     ACCOUNT PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php | cookies=True | get={'params[pass]': 'censored', 'params[login]': '0123456789', 'method': 'accountstatus'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
10.08.2015 23:36:12 WARNING   ACCOUNT PremiumizeMe: Could not login user `0123456789` | 'PremiumizeMe' object has no attribute 'COOKIES'
Traceback (most recent call last):
  File "/home/pi/.pyload/userplugins/internal/Account.py", line 59, in _login
    self.login(user, info['login']['password'], info['data'], self.req)
  File "/home/pi/.pyload/userplugins/accounts/PremiumizeMe.py", line 35, in login
    status = self.get_account_status(user, password, req)
  File "/home/pi/.pyload/userplugins/accounts/PremiumizeMe.py", line 48, in get_account_status
    'params[pass]' : password})
  File "/home/pi/.pyload/userplugins/internal/Plugin.py", line 337, in load
    if isinstance(self.COOKIES, list):
AttributeError: 'PremiumizeMe' object has no attribute 'COOKIES'
10.08.2015 23:36:12 DEBUG     ACCOUNT PremiumizeMe: Scheduled refresh for user `0123456789` in 0 seconds
10.08.2015 23:36:25 INFO      ACCOUNT PremiumizeMe: Relogin user `0123456789`...
10.08.2015 23:36:25 WARNING   ACCOUNT PremiumizeMe: Could not login user `0123456789` | 'password'
Traceback (most recent call last):
  File "/home/pi/.pyload/userplugins/internal/Account.py", line 59, in _login
    self.login(user, info['login']['password'], info['data'], self.req)
KeyError: 'password'
```
(Of course I replaced my username and password)

**Comment by boerngen-schmidt** [comment]
Hey

I added the accounts via the config accounts.conf and it is working. I do not know about the webinterface, but a few weeks back this was not working.
