### ISSUE TITLE
Failed downloads stuck on Home page

### ISSUE THREAD

**Issue by chaosmaker** [pyload/pyload#1803]
So apart from the many other bugs that have been recently found or rather put back in this one is one of the most annoying. I can deal with changing filenames (although I'd rather not) but at least I can make sure that whatever was downloaded has been downloaded.

Now this one, when the file gets downloaded, at least on my system, the file is present, in some cases pyload reports the file as failed. Now that would be fine, if that was only the case in the queue. But the failed file is stuck on the home page - you cannot abort it and when you delete the package (as the file did download) then you need to restart pyload from command line, as now pyload keeps asking for your username and password and won't let you see anything.

**Comment by joberreiter** [comment]
Debug log please.

**Comment by chaosmaker** [comment]
That is going to be fun to reproduce, I'll try :)

**Comment by chaosmaker** [comment]
```
03.09.2015 08:25:20 INFO      Download starts: 2ug582gy
03.09.2015 08:25:20 DEBUG     HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
03.09.2015 08:25:20 DEBUG     HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
03.09.2015 08:25:20 DEBUG     HOSTER RealdebridCom[4]: RealdebridCom | PROCESS URL http://uploaded.net/file/2ug582gy | PLUGIN VERSION 0.69
03.09.2015 08:25:20 INFO      HOSTER RealdebridCom[4]: RealdebridCom | Updating file info...
03.09.2015 08:25:21 DEBUG     HOSTER RealdebridCom[4]: RealdebridCom | File info: {'status': 3, 'name': u'2ug582gy', 'url': u'http://uploaded.net/file/2ug582gy', 'f$
03.09.2015 08:25:21 DEBUG     HOSTER RealdebridCom[4]: RealdebridCom | Previous file info: {'status': 3, 'url': u'http://uploaded.net/file/2ug582gy', 'folder': u'2u$
03.09.2015 08:25:21 INFO      HOSTER RealdebridCom[4]: RealdebridCom | File name: 2ug582gy
03.09.2015 08:25:21 INFO      HOSTER RealdebridCom[4]: RealdebridCom | File size: 1024322437 bytes
03.09.2015 08:25:21 INFO      HOSTER RealdebridCom[4]: RealdebridCom | File status: queued
03.09.2015 08:25:21 DEBUG     HOSTER RealdebridCom[4]: RealdebridCom | LOAD URL http://uploaded.net/file/2ug582gy | decode=True | cookies=True | get={} | req=None |$
03.09.2015 08:25:21 INFO      HOSTER RealdebridCom[4]: RealdebridCom | File status: queued
03.09.2015 08:25:21 INFO      HOSTER RealdebridCom[4]: RealdebridCom | Processing as premium download...
03.09.2015 08:25:21 DEBUG     HOSTER RealdebridCom[4]: RealdebridCom | LOAD URL https://real-debrid.com/ajax/unrestrict.php | decode=True | cookies=True | get={'lan$
03.09.2015 08:25:21 DEBUG     HOSTER RealdebridCom[4]: RealdebridCom | Returned Data: {u'main_link': u'https://da.rdeb.io/d/FIGC7BWSVZJOO/Extant.S02E11.720p.HDTV.X2$
03.09.2015 08:25:21 INFO      HOSTER RealdebridCom[4]: RealdebridCom | Downloading file...
03.09.2015 08:25:21 DEBUG     HOSTER RealdebridCom[4]: RealdebridCom | DOWNLOAD URL https://da.rdeb.io/d/FIGC7BWSVZJOO/Extant.S02E11.720p.HDTV.X264-DIMENSION.mkv | $
03.09.2015 08:25:21 DEBUG     Resume File from 21250048
03.09.2015 08:25:21 DEBUG     Chunked resume with range 362509150-682878652
03.09.2015 08:25:22 DEBUG     Chunked resume with range 703927996-
03.09.2015 08:40:40 WARNING   Download failed: 2ug582gy | [Errno 2] No such file or directory: u'/volume1/pyload/downloads/NewSer/2ug582gy.chunk1'
03.09.2015 08:40:41 DEBUG     Error creating zip file: 'ascii' codec can't decode byte 0x91 in position 18: ordinal not in range(128)
03.09.2015 08:40:41 INFO      Debug Report written to debug_UploadedTo_03-09-2015_08-40-40.txt
03.09.2015 08:40:42 INFO      HOOK UnSkipOnFail: Looking for skipped duplicates of: 2ug582gy (pid:1)
03.09.2015 08:40:42 INFO      HOOK UnSkipOnFail: No duplicates found
03.09.2015 08:40:43 DEBUG     All downloads processed
03.09.2015 08:40:53 WARNING   Download failed: 2ug582gy | 'NoneType' object has no attribute 'size'
```

**Comment by chaosmaker** [comment]
this is what I got last time

**Comment by joberreiter** [comment]
Please attach or post "debug_UploadedTo_03-09-2015_08-40-40.txt"

**Comment by chaosmaker** [comment]
```
pyLoad 0.4.9 Debug Report of UploadedTo 0.69 

TRACEBACK:
 Traceback (most recent call last):
  File "/volume1/public/pyload/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/opt/share/pyload_config/userplugins/internal/Hoster.py", line 185, in preprocessing
    return self.process(self.pyfile)
  File "/volume1/public/pyload/pyload/module/plugins/internal/MultiHoster.py", line 96, in process
    self.download(self.link, disposition=self.DISPOSITION)
  File "/opt/share/pyload_config/userplugins/internal/Hoster.py", line 407, in download
    progressNotify=self.pyfile.setProgress, disposition=disposition)
  File "/volume1/public/pyload/pyload/module/network/Browser.py", line 88, in httpDownload
    name = self.dl.download(chunks, resume)
  File "/volume1/public/pyload/pyload/module/network/HTTPDownload.py", line 129, in download
    self._download(chunks, resume)
  File "/volume1/public/pyload/pyload/module/network/HTTPDownload.py", line 295, in _download
    self._copyChunks()
  File "/volume1/public/pyload/pyload/module/network/HTTPDownload.py", line 100, in _copyChunks
    fi = open(fname, "rb")
IOError: [Errno 2] No such file or directory: u'/volume1/pyload/downloads/NewSer/2ug582gy.chunk1'
 

FRAMESTACK:

Frame preprocessing in /opt/share/pyload_config/userplugins/internal/Hoster.py at line 185
	                self = <module.plugins.hoster.RealdebridCom.RealdebridCom object at 0x7a22d0>
	              thread = <DownloadThread(Thread-3, started daemon)>

Frame process in /volume1/public/pyload/pyload/module/plugins/internal/MultiHoster.py at line 122
	              pyfile = PyFile 4: 2ug582gy@UploadedTo
	                self = <module.plugins.hoster.RealdebridCom.RealdebridCom object at 0x7a22d0>

Frame download in /opt/share/pyload_config/userplugins/internal/Hoster.py at line 409
	                 key = 'ref'
	             cookies = True
	                name = u'2ug582gy'
	                 val = True
	                 get = {}
	                 url = u'https://da.rdeb.io/d/P5WODLXP23IQ4/Extant.S02E11.720p.HDTV.X264-DIMENSION.mkv'
	                self = <module.plugins.hoster.RealdebridCom.RealdebridCom object at 0x7a22d0>
	   download_location = u'/volume1/pyload/downloads/NewSer'
	            filename = u'/volume1/pyload/downloads/NewSer/2ug582gy'
	     download_folder = u'/volume1/pyload/downloads'
	            location = u'/volume1/pyload/downloads/NewSer'
	         disposition = True
	                post = {}
	                 ref = True

Frame httpDownload in /volume1/public/pyload/pyload/module/network/Browser.py at line 88
	             cookies = True
	      progressNotify = <bound method PyFile.setProgress of PyFile 4: 2ug582gy@UploadedTo>
	              resume = True
	                 url = u'https://da.rdeb.io/d/P5WODLXP23IQ4/Extant.S02E11.720p.HDTV.X264-DIMENSION.mkv'
	                self = <module.network.Browser.Browser object at 0x8276f8>
	                 get = {}
	            filename = u'/volume1/pyload/downloads/NewSer/2ug582gy'
	         disposition = True
	              chunks = 3
	                post = {}
	                 ref = True

Frame download in /volume1/public/pyload/pyload/module/network/HTTPDownload.py at line 145
	              chunks = 3
	                self = <module.network.HTTPDownload.HTTPDownload instance at 0x7c9df0>
	              resume = False

Frame _download in /volume1/public/pyload/pyload/module/network/HTTPDownload.py at line 295
	               chunk = <HTTPChunk id=2, size=341439323, arrived=341439324>
	                done = True
	                  ex = None
	                diff = [221184, 221184, 221184]
	              chunks = 3
	     lastFinishCheck = 1441266036.6245451
	                curl = <pycurl.Curl object at 0x8d1b98>
	       chunksCreated = True
	               errno = 23
	                self = <module.network.HTTPDownload.HTTPDownload instance at 0x7c9df0>
	                 ret = 0
	              failed = []
	                init = <HTTPChunk id=0, size=341439325, arrived=341442784>
	         num_handles = 0
	                 msg = 'Failed writing body (0 != 7976)'
	          chunksDone = set([<pycurl.Curl object at 0x7da3a0>, <pycurl.Curl object at 0x8d0d08>, <pycurl.Curl object at 0x8d1b98>])
	              handle = <pycurl.Curl object at 0x8d1b98>
	              resume = False
	            err_list = [(<pycurl.Curl object at 0x8d0d08>, 23, 'Failed writing body (0 != 1165)'),
 (<pycurl.Curl object at 0x8d1b98>, 23, 'Failed writing body (0 != 7976)')]
	             ok_list = []
	               num_q = 0
	                   a = 221184
	                   c = (<pycurl.Curl object at 0x8d1b98>, 23, 'Failed writing body (0 != 7976)')
	                   i = 2
	                   t = 1441266036.6245451
	       lastTimeCheck = 1441266035.475733

Frame _copyChunks in /volume1/public/pyload/pyload/module/network/HTTPDownload.py at line 100
	                   i = 1
	                init = u'/volume1/pyload/downloads/NewSer/2ug582gy.chunk0'
	                self = <module.network.HTTPDownload.HTTPDownload instance at 0x7c9df0>
	               fname = u'/volume1/pyload/downloads/NewSer/2ug582gy.chunk1'
	                  fo = <open file u'/volume1/pyload/downloads/NewSer/2ug582gy.chunk0', mode 'rb+' at 0x7cb968>


PLUGIN OBJECT DUMP: 

	          CHECK_FILE = True
	       CHECK_TRAFFIC = False
	             COOKIES = True
	         DIRECT_LINK = None
	         DISPOSITION = True
	         FILE_ERRORS = [('Html error',
  '\\A(?:\\s*<.+>)?((?:[\\w\\s]*(?:[Ee]rror|ERROR)\\s*\\:?)?\\s*\\d{3})(?:\\Z|\\s+)'),
 ('Request error', '([Aa]n error occured while processing your request)'),
 ('Html file', '\\A\\s*<!DOCTYPE html')]
	         HOSTER_NAME = 'RealdebridCom'
	        LEECH_HOSTER = False
	        LINK_PATTERN = None
	       LOGIN_ACCOUNT = True
	       LOGIN_PREMIUM = False
	   NAME_REPLACEMENTS = [('&#?\\w+;', <function fixup at 0xe5af0>)]
	   SIZE_REPLACEMENTS = []
	       TEXT_ENCODING = True
	    URL_REPLACEMENTS = []
	             account = <module.plugins.accounts.RealdebridCom.RealdebridCom object at 0x471830>
	             captcha = <module.plugins.internal.Captcha.Captcha object at 0x7a2c70>
	         chunk_limit = 3
	           direct_dl = None
	                html = u'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"\n    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="de">\n\n<head>\n\t<title>Extant.S02E11.720p.HDTV.X26\u2026mkv (976,87 MB) - uploaded.net</title>\n    <base href="http://uploaded.net/" />\n\t<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />\n\t<meta name="revisit-after" content="1 days" />\n\t<meta name="description" content="the easiest way to backup and share your files with everyone." />\n\t<meta name="keywords" content="uploaded, ul, uploaded.to, ul.to, upload, download, free, premium, one click hoster, och, sharehoster" />\n\t<meta name="author" content="uploaded.net" />\n\t<meta name="owner" content="uploaded.net" />\n\t<meta name="RATING" content="General">\n\t<meta name="language" http-equiv="content-language" content="de" />\n\t<!--<meta property="fb:page_id" content="217881528283333" />-->\n\t\t<link rel="stylesheet" href="/img/layout.css?xcache=3229" />\n\t<!--[if !IE]><!--><link rel="stylesheet" href="/img/noIE.css" /><!--<![endif]-->\t<link rel="icon" href="/favicon.ico" type="image/x-icon" />\n\t<meta http-equiv="Content-Script-Type" content="text/javascript" />\n\t<script type="text/javascript" src="/js2/protoculous.js?v=1"></script>\n\t<script type="text/javascript" src="/js2/yahoo-dom-event.js"></script>\n\t<script type="text/javascript" src="/js2/element-min.js"></script>\n\t<script type="text/javascript" src="/js2/uploader-min.js"></script>\n\t<script type="text/javascript" src="/js2/md5.js"></script>\n\t<script type="text/javascript" src="/js/script.js"></script>\n\t<script type="text/javascript" src="/js/guest.js"></script>\t\t</head>\n\n<body>\n\n<script type="text/javascript">\n\tif(parent.frames.length > 0)\n\t\ttop.location.href = self.location;\n</script>\n\n<div id="head">\n\t<div class="center">\n\n        \t\t<a href="" id="logo"><img src="/img/uploaded.png" /></a>\n        \n\t\t<div class="navi">\n\t\t\t\t\t\t<ul class="user">\n\t\t\t\t<li><span id="nlogin" class="link">Login</span></li> \xb7\n\t\t\t\t<li><a href="register" id="nregister">Registrieren</a></li>\n\t\t\t</ul>\n\t\t\t<ul>\n\t\t\t\t<li><a href="affiliate">Partnerprogramm</a></li> \xb7\n\t\t\t\t<li><a href="/udrive">uDrive</a></li> \xb7\n\t\t\t\t<li><a href="help">Support</a></li> \xb7\n\t\t\t</ul>\n\t\t\t\t\t\t<form action="//uploaded.net" style="display:none;" id="guestvars">\n\t\t\t\t<input type="text"\t\tname="id" id="guestid" style="display:none;" value="" />\n\t\t\t\t<input type="password"\tname="pw" id="guestpw" style="display:none;" value="" />\n\t\t\t</form>\n\t\t\t\t\t\t\t\t\t\t\t\t<div id="nupload"></div>\n\t\t\t\t\t</div>\n\t</div>\n\t\n\t<noscript style="position:absolute;top:80px;width:100%;font-weight:bold;" class="cR aC">\n\t\t<span style="margin-left:150px;">Um unseren Dienst nutzen zu k\ufffdn m\ufffdSie JavaScript aktivieren.</span>\n\t</noscript>\n</div>\n<div class="hshadow"></div>\n\n<div class="bga">\n\t<div id="content">\n\n\n<div id="download" class="center">\n\n\t<ul id="headmenu">\n\t\t\t\t\t\t\t</ul><br />\n\n    \n        <div class="center" style="text-align:center; margin-top: 0px; margin-bottom: 20px;margin-left:40px;">\n\t\t<script type=\'text/javascript\' src=\'http://delivery.uauniverse.com/www/delivery/spcjs.php?id=1\'></script><script type=\'text/javascript\'><!--// <![CDATA[\n                /* [id26] uploaded.net - DL Leaderboard ODS - OTHER */\n                OA_show(26);\n                // ]]> -->\n            </script>\n            <noscript><a target=\'_blank\' href=\'http://delivery.uauniverse.com/www/delivery/ck.php?n=1ff50e1\'><img border=\'0\' alt=\'\' src=\'http://delivery.uauniverse.com/www/delivery/avw.php?zoneid=26&n=1ff50e1\' /></a></noscript>    </div>\n    \n\t\t<div id="fblike" style="float:left;margin:2px 25px 0 25px;width:70px;height:110px">\n\t\t<iframe src="http://uploaded.net/img/fb.html" style="width:100%;height:100%;border:0px" scrolling="no" frameborder="0"></iframe>\n\t</div>\n\t\n\t<div class="title" style="float:left;width:78%">\n\t\t<small class="date" style="text-transform:uppercase">Datei herunterladen:</small>\n\n\t\t<h1 style="font-size:38px;line-height:40px;text-shadow:0 -1px 1px #BBC8D9, 0 1px 1px #fff"><a href="file/2ug582gy" id="filename">Extant.S02E11.720p.HDTV.X26\u2026mkv</a> \xa0\n\t\t\t<small style="border-radius:5px;padding:0 3px;text-shadow:none;background:#ebebeb;color:#bbbbbb;font-size:11px;">976,87 MB</small>\n\t\t</h1>\n\t\t\t</div>\n    <div style="clear: both;"></div>\n\n<script type="text/javascript">\n\tvar tracking_method = \'presale\';\n</script>\n<div style="clear:both;" ></div>\n\n\t<div class="box">\n\t\t<table style="width:914px" class="tfree">\n\t\t\t<tr class="aT">\n\t\t\t\t<td class="aT" style="width:295px"><h2 style="margin:3px 0 5px 0">W\ufffden Sie Ihre Downloadart.</h2>\n\t\t\t\t\t<small>Premium Benutzer genie\ufffdn zahlreiche Vorteile; Beispielsweise startet der Download <b>sofort</b> und mit <b>voller Geschwindigkeit</b>!</small></td>\n\t\t\t\t<td rowspan="13" style="width:50px"></td>\n\t\t\t\t<td id="captcha" style="width:320px" colspan="2">\n\t\t\t\t\t<button class="free" style="margin-right:0px">\n\t\t\t\t\t\t<h1>Free Download</h1>\n\t\t\t\t\t\t<span>Aktuelle Wartezeit: <span>30</span> Sekunden</span>\n\t\t\t\t\t</button>\n\t\t\t\t</td>\n\t\t\t\t<td style="width:1px"></td>\n\t\t\t\t<td style="width:294px">\n\t\t\t\t\t<form method="get" action="register">\n\t\t\t\t\t\t<button type="submit" class="prem" onmousedown="try { _gaq.push([\'_trackEvent\', \'premium\', tracking_method ,]); }catch(e) {}" onmouseover="Download._blink=false" onmouseout="Download._blink=true;">\n\t\t\t\t\t\t\t<h1>Premium Download!</h1>Fullspeed & Parallele Downloads\t\t\t\t\t\t</button>\n\t\t\t\t\t</form>\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t<tr style="height:20px">\n\t\t\t\t<th colspan="6"></th>\n\t\t\t</tr>\n\t\t\t<tr class="feature aB">\n\t\t\t\t<td style="padding-bottom:4px"><b>Downloadgeschwindigkeit:</b></td>\n\t\t\t\t\t\t\t\t<th style="padding-left:40px" class="aB">50 KB/s<br /><small class="cL">G\ufffde</small></th>\n\t\t\t\t<th style="padding-right:23px" class="aB">70 KB/s<br /><small class="cL">Free \xbb <a href="registerfree">Registrieren</a></small></th>\n\t\t\t\t<th></th>\n\t\t\t\t<th class="cL aB"><em style="color:#6DA31D">unlimitiert</em><br /><small>Premium \u2713 <a href="register">ab 14c/Tag</a></small></th>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th colspan="6" style="padding-top:6px"><div class="border"></div></th>\n\t\t\t</tr>\n\t\t\t\t\t\t<tr class="feature">\n\t\t\t\t<td><b>Downloadzeit:</b></td>\n\t\t\t\t<th colspan="2">~ 5 Stunden 33 Minuten und 27 Sekunden</th>\n\t\t\t\t<th></th>\n\t\t\t\t<th><em>~ 2 Minuten und 47 Sekunden</em></th>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th colspan="6"><div class="border"></div></th>\n\t\t\t</tr>\n\t\t\t\t\t\t<tr class="feature">\n\t\t\t\t<td><b>Parallele Downloads:</b></td>\n\t\t\t\t<th colspan="2"><div class="check no"></div></th>\n\t\t\t\t<th></th>\n\t\t\t\t<th><em>unlimitiert</em></th>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th colspan="6"><div class="border"></div></th>\n\t\t\t</tr>\n\t\t\t<tr class="feature">\n\t\t\t\t<td><b>Downloadbeschr\ufffdung:</b></td>\n\t\t\t\t<th colspan="2">eine Datei alle 180 Minuten</th>\n\t\t\t\t<th></th>\n\t\t\t\t<th><em>keine</em></th>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th colspan="6"><div class="border"></div></th>\n\t\t\t</tr>\n\t\t\t<tr class="feature">\n\t\t\t\t<td><b>Direkt-/Hot Linking:</b></td>\n\t\t\t\t<th colspan="2"><div class="check no"></div></th>\n\t\t\t\t<th></th>\n\t\t\t\t<th><div class="check"></div></th>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th colspan="6"><div class="border"></div></th>\n\t\t\t</tr>\n\t\t\t<tr class="feature">\n\t\t\t\t<td><b>Downloads starten sofort:</b></td>\n\t\t\t\t<th colspan="2"><div class="check no"></div></th>\n\t\t\t\t<th></th>\n\t\t\t\t<th><div class="check"></div></th>\n\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t<tr id="ad-group-download-bottom">\n\t\t\t\t<td colspan="6">\n\t\t\t\t\t<script type=\'text/javascript\'><!--// <![CDATA[\n                /* [id91] uploaded.net - DL Bottom 800x400 - OTHER */\n                OA_show(91);\n                // ]]> -->\n            </script>\n            <noscript><a target=\'_blank\' href=\'http://delivery.uauniverse.com/www/delivery/ck.php?n=8b34d8e\'><img border=\'0\' alt=\'\' src=\'http://delivery.uauniverse.com/www/delivery/avw.php?zoneid=91&n=8b34d8e\' /></a></noscript>\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t\t\t</table>\n\t\t<img src="img/e/shadow.png" class="shadow" alt="" />\n\t</div>\n\n    \n</div>\n<script type="text/javascript">\n\tvar free_enabled = true;\n    var filename = \'Extant.S02E11.720p.HDTV.X26%26hellip%3Bmkv\';\n</script>\n\n<script type="text/javascript" src="js/download.js"></script>\n<script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>\n\t<br style="clear:both" />\n<script type="text/javascript">\nfunction importFile(auth){\n\tvar isUser = false;\n\tvar c = $(\'import\');\n\n\tif(isUser){\n\t\tc.update(\'Lade\');\n\t\tnew Ajax.Request(\'io/import\', {onComplete:function(t){\n\t\t\tt = t.responseText.substr(0, t.responseText.length-1).evalJSON();\n\n\t\t\tif(t.err)\n\t\t\t\t return c.update(\'<b class="cR">Fehler:</b> \'+t.err);\n\n\t\t\tc.update(\'<b class="cG">OK</b>\');\n\n\t\t\tif(confirm("Die Datei wurde in Ihren Account kopiert.\\nM\ufffden Sie nun zu Ihren Dateien & Ordnern wechseln?"))\n\t\t\t\ttop.location.href = \'/manage\';\n\n\t\t}.bind(this),parameters:\'urls=http://ul.to/2ug582gy\'});\n\t}\n\telse\n\t\treturn top.location.href = \'/register\';\n}\n\nfunction like(auth)\n{\n\tvar c = $(\'ilike\');\n\n\tnew Ajax.Request(\'io/fav/add/\'+auth, {parameters:\'type=file\',onComplete:function(t){\n\t\tc.replace(\'<span id="likestatus" class="cG" style="padding-left:3px">\'+t.responseText.gsub(\' \', \'\xa0\')+\'</span>\');\n\t\t$(\'likestatus\').highlight({endcolor:\'#f8f8f8\'});\n\t}});\n}\n\t\t\tdocument.cookie = \'ref=\'+(\'ref_user=3133407&date=1441265121\')+\'; expires=0;path=/;\';\n\t\n\t\tvar oDLad = {"active":1,"active404":0,"typ":2,"url":"http://uploaded.net/register","cookietime":1,"attr":"width=1024,height=600,scrollbars=yes"};\n\tvar country = \'en-us\';\n\tif(oDLad.active && oDLad.url) {\n\t\tif(!document.cookie.include(\'ulDlAd1\')) {\n\t\t\tswitch(oDLad.typ){\n\t\t\t\tcase 1:\n\t\t\t\tcase 2:\n\t\t\t\t\tcreatePop(oDLad);\n\t\t\t\tbreak;\n\t\t\t\tcase 3:\n\t\t\t\t\tif(country == \'de-de\' || country == \'de\'){\n\t\t\t\t\t\tvar _abdDetectedFnc = function(){ };\n\t\t\t\t\t\tvar _abdNotDetectedFnc = \'uLayer\';\n\t\t\t\t\t\tvar _abdParam = oDLad;\n\n\t\t\t\t\t\tfunction uLayer(){\n\t\t\t\t\t\t\tnew Ajax.Request(\'js/ulayer.js\');\n\t\t\t\t\t\t}\n\n\t\t\t\t\t\tnew Ajax.Request(\'js2/adblock_detector.js\');\n\t\t\t\t\t}\n\t\t\t\tbreak;\n\t\t\t\tdefault:\n\t\t\t\t\talert(oDLad);\n\t\t\t\tbreak;\n\t\t\t}\n\t\t\tdocument.cookie = \'ulDlAd1=seen; expires=\'+new Date(new Date().getTime() + (oDLad.cookietime*60*60*1000)).toGMTString()+\';path=/;\';\n\t\t}\n\t}\n\n\tfunction createPop(obj) {\n\t\tdocument.getElementsByTagName(\'html\')[0].onclick = function(){\n\t\t\tdocument.getElementsByTagName(\'html\')[0].onclick=function(){};\n\t\t\t//if(\'de\' != \'de\') return;\n\n\t\t\treturn;\n\t\t\tvar win = window.open(obj.url, \'PopUp\', obj.attr);\n\t\t\tif(obj.typ==2) {\n\t\t\t\twin.blur();\n\t\t\t\twindow.setTimeout(function(){window.self.focus();}, 100);\n\t\t\t}\n\t\t\t//window.onclick = function(){};\n\t\t\treturn true;\n\t\t}\n\t}\n\nvar externalAdLoaded = false;\nfunction initExternalAd() {\n    if(externalAdLoaded) {return false;}\n    var s = document.getElementsByTagName(\'script\')[0]; \n    ele = document.createElement(\'script\');\n    ele.type="text/javascript";\n\n                                s.parentNode.insertBefore(ele, s);\n    externalAdLoaded = true;\n\tnew Ajax.Request("/io/ticket/mp/2ug582gy");\n}\n// $$(\'.free\')[0].observe("mousedown", initExternalAd);\n</script>\n<script type=\'text/javascript\'><!--// <![CDATA[\n                /* [id27] uploaded.net - DL Popunder - OTHER */\n                OA_show(27);\n                // ]]> -->\n            </script>\n            <noscript><a target=\'_blank\' href=\'http://delivery.uauniverse.com/www/delivery/ck.php?n=efb71a4\'><img border=\'0\' alt=\'\' src=\'http://delivery.uauniverse.com/www/delivery/avw.php?zoneid=27&n=efb71a4\' /></a></noscript>\n\n\n    \n\t</div>\n\n\t<div id="foot"><div>\n\t\t<div class="center">\n\t\t\t\t\t<a href="register">Registrieren</a>\xb7\n\t\t\t\t\t<a href="affiliate">Partnerprogramm</a>\xb7\n\t\t\t\t\t\t<a href="legal">AGB &  Richtlinien</a>\xb7\n\t\t\t<!--<a href="job">Jobs</a> \xb7-->\n\t\t\t<!--<a href="policy">Child Pornography Policy</a> \xb7-->\n\t\t\t<a href="help">Support</a> \xb7\n\t\t\t<a href="/products">Produkte</a> \xb7\n            <a href="corporate">Corporate products</a> <br/>\n\n            <a href="/takedown/notice">Takedown</a>\xb7\n            <a href="about">Werbeanfragen</a> \xb7\n\t\t\t<a href="about">Impressum</a>\n\n\t\t\t<div style="width: 155px;" class="right aR">\n\t\t\t\t<b>Sprache:</b> \n                <span class="a" id="language">Deutsch</span>\n                <a title="Twitter @ul_to" href="http://twitter.com/ul_to" target="_blank" class="twitter-icon"></a>\n\t\t\t\t\t\t\t</div>\n\t\t\t<div class="footlogo"></div>\n\t\t</div>\n\t</div></div>\n</div>\n<script type="text/javascript"> \n\n  var _gaq = _gaq || []; \n  _gaq.push([\'_setAccount\', \'UA-34088231-1\']); \n  _gaq.push([\'_trackPageview\']); \n\n  (function() { \n    var ga = document.createElement(\'script\'); ga.type = \'text/javascript\'; ga.async = true; \n    ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\' : \'http://www\') + \'.google-analytics.com/ga.js\'; \n    var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(ga, s); \n  })(); \n\n</script><!-- 2015-09-03 09:25:21 / 0.024600028991699 --> \n\n</body></html>\n'
	                info = {'folder': u'2ug582gy',
 'name': u'2ug582gy',
 'size': 0,
 'status': 3,
 'url': u'http://uploaded.net/file/2ug582gy'}
	                  js = <module.common.JsEngine.JsEngine instance at 0x45f238>
	          last_check = None
	       last_download = ''
	            leech_dl = False
	             limitDL = 0
	                link = u'https://da.rdeb.io/d/FIGC7BWSVZJOO/Extant.S02E11.720p.HDTV.X264-DIMENSION.mkv'
	             multiDL = True
	             premium = True
	              pyfile = PyFile 4: 2ug582gy@UploadedTo
	              pyload = <__main__.Core object at 0x1ae2d0>
	                 req = <module.network.Browser.Browser object at 0x7eb688>
	     resume_download = True
	             retries = {}
	          retry_free = False
	              thread = <DownloadThread(Thread-2, started daemon)>
	                user = 'chaosmaker'
	          wait_until = 0
	             waiting = False
	       wantReconnect = False

PYFILE OBJECT DUMP: 

	               _size = 1024317976
	               abort = False
	              active = False
	               error = "[Errno 2] No such file or directory: u'/volume1/pyload/downloads/NewSer/2ug582gy.chunk1'"
	                  id = 4
	                lock = <_RLock(None, 0)>
	                   m = <module.database.FileDatabase.FileHandler instance at 0x1ff558>
	         maxprogress = 100
	                name = u'2ug582gy'
	               order = 3
	           packageid = 1
	              plugin = <module.plugins.hoster.RealdebridCom.RealdebridCom object at 0x7a22d0>
	         pluginclass = <class 'module.plugins.hoster.RealdebridCom.RealdebridCom'>
	        pluginmodule = <module 'module.plugins.hoster.RealdebridCom' from '/volume1/public/pyload/pyload/module/plugins/hoster/RealdebridCom.pyc'>
	          pluginname = u'UploadedTo'
	            progress = 99L
	         reconnected = False
	                size = 1024317976
	              status = 8
	          statusname = None
	                 url = u'http://uploaded.net/file/2ug582gy'
	           waitUntil = 0


CONFIG: 

{'desc': 'UploadedTo',
 'outline': 'Uploaded.net hoster plugin',
 'use_premium': {'desc': 'Use premium account if available',
                 'type': 'bool',
                 'value': True}}
```

**Comment by joberreiter** [comment]
Seems to be a problem of curl writing the chunk to disk -- is this reproduceable?
You can eliminate a simple issue like running out of disk space?

**Comment by chaosmaker** [comment]
It happens quite often... mainly when I have 3 or more files in the same package that are actually the same thing. There is always 1 that has an .html extension, 1 that has a correct extension .mkv and 2 which are just hashes - like this one. Usually the last hash fails, the file is there, like all of it is there, no missing chunks or anything. Yet pyload reports it as failed.
