### ISSUE TITLE
Database Error @ updateLink (Error binding parameter 4 - probably unsupported type)

### ISSUE THREAD

**Issue by joberreiter** [pyload/pyload#1804]
Pyload still throws an error at executing updateLink(), due to a wrong type.
Could it be a wrong/incomplete implementation of  `module.plugins.Plugin.Fail`, since `type(f.error) ==  <class 'module.plugins.Plugin.Fail'>`.
Should'nt it be `<str>` or `<unicode>`?

Note: The `DEBUG     DBG` lines are added by myself in FileDatabase.py to clarify the error.
```
03.09.2015 16:40:10 INFO      Download starts: Jonathan_Wylie.rar
03.09.2015 16:40:10 DEBUG     HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 10.0; rv:40.0) Gecko/20100101 Firefox/40.0
03.09.2015 16:40:10 DEBUG     HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 10.0; rv:40.0) Gecko/20100101 Firefox/40.0
03.09.2015 16:40:10 DEBUG     DBG f.url = http://uploaded.net/file/pmkpadnj (<type 'unicode'>)
03.09.2015 16:40:10 DEBUG     DBG f.name = Jonathan_Wylie.rar (<type 'unicode'>)
03.09.2015 16:40:10 DEBUG     HOSTER UploadedTo[12804]: PROCESS URL http://uploaded.net/file/pmkpadnj | PLUGIN VERSION 0.97
03.09.2015 16:40:10 DEBUG     DBG f.size = 912369 (<type 'int'>)
03.09.2015 16:40:10 INFO      HOSTER UploadedTo[12804]: Updating file info...
03.09.2015 16:40:10 DEBUG     DBG f.status = 7 (<type 'int'>)
03.09.2015 16:40:10 DEBUG     DBG f.error =  (<type 'str'>)
03.09.2015 16:40:10 DEBUG     DBG f.packageid = 4207 (<type 'int'>)
03.09.2015 16:40:10 DEBUG     DBG f.id = 12804 (<type 'int'>)
03.09.2015 16:40:10 DEBUG     HOSTER UploadedTo[12804]: File info: {'status': 2, 'url': u'http://uploaded.net/file/pmkpadnj', 'size': 912369.0, 'name': 'Jonathan_Wylie.rar', 'pattern': {'ID': u'pmkpadnj'}}
03.09.2015 16:40:10 DEBUG     HOSTER UploadedTo[12804]: Previous file info: {}
03.09.2015 16:40:10 INFO      HOSTER UploadedTo[12804]: File name: Jonathan_Wylie.rar
03.09.2015 16:40:10 INFO      HOSTER UploadedTo[12804]: File size: 912369 bytes
03.09.2015 16:40:10 INFO      HOSTER UploadedTo[12804]: File status: online
03.09.2015 16:40:10 DEBUG     HOSTER UploadedTo[12804]: LOAD URL http://uploaded.net/file/pmkpadnj | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
03.09.2015 16:40:10 INFO      HOSTER UploadedTo[12804]: Processing as free download...
03.09.2015 16:40:10 DEBUG     HOSTER UploadedTo[12804]: LOAD URL http://uploaded.net/language/en | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
03.09.2015 16:40:10 DEBUG     HOSTER UploadedTo[12804]: LOAD URL http://uploaded.net/js/download.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
03.09.2015 16:40:10 DEBUG     CAPTCHA UploadedTo[12804]: ReCaptcha | Key: 6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3
03.09.2015 16:40:11 DEBUG     HOSTER UploadedTo[12804]: LOAD URL http://www.google.com/recaptcha/api/challenge | cookies=True | get={'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
03.09.2015 16:40:11 DEBUG     CAPTCHA UploadedTo[12804]: ReCaptcha | Challenge: 03AHJ_Vuunuq4QiKcdK6m0dwyfA2O9n4C_Q6ouFLysCW2z_i7Xi4CPdZNu2As72REKc6xCf71hE18Jjj1FufFw3dvr7LmoUhU_8-U65DLkPf59N5XtdacHZSX59eg0yTzHfPrUSo5qmW7qu2AaIOgNQ4RY0J0Q4Vse7HZm2O1uroP8H9r7j-3SWINvSezILnDKhc01LwkVnlWq
03.09.2015 16:40:11 DEBUG     HOSTER UploadedTo[12804]: LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
03.09.2015 16:40:11 DEBUG     HOSTER UploadedTo[12804]: LOAD URL http://www.google.com/recaptcha/api/reload | cookies=True | get={'reason': 'i', 'c': u'03AHJ_Vuunuq4QiKcdK6m0dwyfA2O9n4C_Q6ouFLysCW2z_i7Xi4CPdZNu2As72REKc6xCf71hE18Jjj1FufFw3dvr7LmoUhU_8-U65DLkPf59N5XtdacHZSX59eg0yTzHfPrUSo5qmW7qu2AaIOgNQ4RY0J0Q4Vse7HZm2O1uroP8H9r7j-3SWINvSezILnDKhc01LwkVnlWq', 'type': 'image', 'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
03.09.2015 16:40:11 DEBUG     CAPTCHA UploadedTo[12804]: ReCaptcha | Second challenge: 03AHJ_VuteE2zjfq2tC8ohrI0XLQN9V2eStjmczgcDPZPUNSk1zQdhRzgX9BjXGBcJdlaMj0S1BQoyNunSYkGAVFp5c_kNae8yS3I4U5_n4Fcu8UWG52W6JGwOJoZ3PVDa6PyS0VvU7wLi3SmcpRW272_vBZyZggAR4NO3GhGnF5ePREUa9qF2J59wIw4Hr38ybpn2RnyRRMVM
03.09.2015 16:40:11 DEBUG     CAPTCHA UploadedTo[12804]: ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | cookies=True | get={'c': u'03AHJ_VuteE2zjfq2tC8ohrI0XLQN9V2eStjmczgcDPZPUNSk1zQdhRzgX9BjXGBcJdlaMj0S1BQoyNunSYkGAVFp5c_kNae8yS3I4U5_n4Fcu8UWG52W6JGwOJoZ3PVDa6PyS0VvU7wLi3SmcpRW272_vBZyZggAR4NO3GhGnF5ePREUa9qF2J59wIw4Hr38ybpn2RnyRRMVM'} | req=None | decode=False | multipart=False | post={} | ref=False | just_header=False
03.09.2015 16:40:22 DEBUG     CAPTCHA UploadedTo[12804]: ReCaptcha | Result: ddrutpu and
03.09.2015 16:40:22 DEBUG     HOSTER UploadedTo[12804]: LOAD URL http://uploaded.net/io/ticket/captcha/pmkpadnj | cookies=True | get={} | req=None | decode=True | multipart=False | post={'recaptcha_challenge_field': u'03AHJ_VuteE2zjfq2tC8ohrI0XLQN9V2eStjmczgcDPZPUNSk1zQdhRzgX9BjXGBcJdlaMj0S1BQoyNunSYkGAVFp5c_kNae8yS3I4U5_n4Fcu8UWG52W6JGwOJoZ3PVDa6PyS0VvU7wLi3SmcpRW272_vBZyZggAR4NO3GhGnF5ePREUa9qF2J59wIw4Hr38ybpn2RnyRRMVM', 'recaptcha_response_field': 'ddrutpu and'} | ref=True | just_header=False
03.09.2015 16:40:23 DEBUG     HOSTER UploadedTo[12804]: Config option `fallback` not found, use default `True`
03.09.2015 16:40:23 DEBUG     DBG f.url = http://uploaded.net/file/pmkpadnj (<type 'unicode'>)
03.09.2015 16:40:23 DEBUG     DBG f.name = Jonathan_Wylie.rar (<type 'str'>)
03.09.2015 16:40:23 WARNING   Download failed: Jonathan_Wylie.rar | Parse error: Free download link not found | Plugin may be out of date
03.09.2015 16:40:23 DEBUG     DBG f.size = 912369 (<type 'int'>)
03.09.2015 16:40:23 DEBUG     DBG f.status = 8 (<type 'int'>)
03.09.2015 16:40:23 INFO      HOOK UnSkipOnFail: Looking for skipped duplicates of: Jonathan_Wylie.rar (pid:4207)
03.09.2015 16:40:23 DEBUG     DBG f.error = Parse error: Free download link not found | Plugin may be out of date (<class 'module.plugins.Plugin.Fail'>)
03.09.2015 16:40:23 DEBUG     DBG f.packageid = 4207 (<type 'int'>)
03.09.2015 16:40:23 DEBUG     DBG f.id = 12804 (<type 'int'>)
Traceback (most recent call last):
  File "/usr/share/pyload/module/database/DatabaseBackend.py", line 96, in processJob
    self.result = self.f(*self.args, **self.kwargs)
  File "/usr/share/pyload/module/database/FileDatabase.py", line 774, in updateLink
    self.c.execute('UPDATE links SET url=?,name=?,size=?,status=?,error=?,package=? WHERE id=?', (f.url, f.name, f.size, f.status, f.error, str(f.packageid), str(f.id)))
InterfaceError: Error binding parameter 4 - probably unsupported type.
Database Error @ updateLink (PyFile 12804: Jonathan_Wylie.rar@UploadedTo,) {} Error binding parameter 4 - probably unsupported type.
03.09.2015 16:40:26 INFO      HOOK UnSkipOnFail: No duplicates found
03.09.2015 16:40:26 DEBUG     DBG f.url = http://uploaded.net/file/pmkpadnj (<type 'unicode'>)
03.09.2015 16:40:26 DEBUG     DBG f.name = Jonathan_Wylie.rar (<type 'str'>)
03.09.2015 16:40:26 DEBUG     DBG f.size = 912369 (<type 'int'>)
03.09.2015 16:40:26 DEBUG     DBG f.status = 8 (<type 'int'>)
03.09.2015 16:40:26 DEBUG     DBG f.error = Parse error: Free download link not found | Plugin may be out of date (<class 'module.plugins.Plugin.Fail'>)
03.09.2015 16:40:26 DEBUG     DBG f.packageid = 4207 (<type 'int'>)
03.09.2015 16:40:26 DEBUG     DBG f.id = 12804 (<type 'int'>)
Traceback (most recent call last):
  File "/usr/share/pyload/module/database/DatabaseBackend.py", line 96, in processJob
    self.result = self.f(*self.args, **self.kwargs)
  File "/usr/share/pyload/module/database/FileDatabase.py", line 774, in updateLink
    self.c.execute('UPDATE links SET url=?,name=?,size=?,status=?,error=?,package=? WHERE id=?', (f.url, f.name, f.size, f.status, f.error, str(f.packageid), str(f.id)))
InterfaceError: Error binding parameter 4 - probably unsupported type.
Database Error @ updateLink (PyFile 12804: Jonathan_Wylie.rar@UploadedTo,) {} Error binding parameter 4 - probably unsupported type.
```

**Comment by joberreiter** [comment]
I've made a workaround by adding two lines to the function `updateLink` in `/usr/share/pyload/module/database/FileDatabase.py`:
```python
    if not isinstance(f.error, (unicode, basestring)):
        f.error = f.error.args[0]
```
directly before the SQL command execution, which works, but isn't the pythonic way of solving it. 

Anyway, if the problem affects only v0.4.9 and is solved in v0.4.10, then there is no need for the workaround -- but until v0.4.10 is released, it may be of help for someone.
