### ISSUE TITLE
filecrypt.cc error

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#1805]
```
03.09.2015 20:46:38	INFO	HOOK HDAreaOrg: COLLECTOR: Ein verruecktes Paar (1993) IMDb: 6.9
364	03.09.2015 20:46:38	INFO	Added package Ein verruecktes Paar (1993) IMDb: 6.9 containing 1 links
365	03.09.2015 20:46:56	INFO	Decrypting starts: https://www.filecrypt.cc/Container/82052D6BD5.html
366	03.09.2015 20:46:58	ERROR	Decrypting failed: https://www.filecrypt.cc/Container/82052D6BD5.html | Bad server response: 400 Bad Request
```

**Comment by Leonderi** [comment]
was already mentioned in https://github.com/pyload/pyload/issues/1781

**Comment by Gutz-Pilz** [comment]
```

11.09.2015 18:51:20 DEBUG     Redirected import module.plugins.crypter.FilecryptCc -> userplugins.crypter.FilecryptCc
11.09.2015 18:51:20 DEBUG     Redirected import module.plugins.internal.Crypter -> userplugins.internal.Crypter
11.09.2015 18:51:20 INFO      Decrypting starts: https://www.filecrypt.cc/Container/9C2AC73E4F.html
11.09.2015 18:51:20 DEBUG     CRYPTER FilecryptCc[1661]: PROCESS URL https://www.filecrypt.cc/Container/9C2AC73E4F.html | PLUGIN VERSION 0.19
11.09.2015 18:51:20 DEBUG     CRYPTER FilecryptCc[1661]: LOAD URL https://www.filecrypt.cc/Container/9C2AC73E4F.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
11.09.2015 18:51:22 DEBUG     CRYPTER FilecryptCc[1661]: Captcha-URL: ../captcha/captcha.php?namespace=container
11.09.2015 18:51:22 DEBUG     CAPTCHA FilecryptCc[1661]: Captcha | LOAD URL https://www.filecrypt.cc/../captcha/captcha.php?namespace=container | cookies=False | get={} | req=None | decode=False | multipart=False | post={} | ref=False | just_header=False
11.09.2015 18:51:23 ERROR     Decrypting failed: https://www.filecrypt.cc/Container/9C2AC73E4F.html | Bad server response: 400 Bad Request
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/root/.pyload/userplugins/internal/Hoster.py", line 185, in preprocessing
    return self.process(self.pyfile)
  File "/root/.pyload/userplugins/internal/Crypter.py", line 41, in process
    self.decrypt(pyfile)
  File "/root/.pyload/userplugins/crypter/FilecryptCc.py", line 52, in decrypt
    self.handle_captcha()
  File "/root/.pyload/userplugins/crypter/FilecryptCc.py", line 96, in handle_captcha
    input_type="gif")
  File "/root/.pyload/userplugins/internal/Captcha.py", line 55, in decrypt
    img = self.load(url, get=get, post=post, ref=ref, cookies=cookies, decode=decode)
  File "/root/.pyload/userplugins/internal/Plugin.py", line 341, in load
    res = req.load(url, get, post, ref, bool(cookies), just_header, multipart, decode is True)  #@TODO: Fix network multipart in 0.4.10
  File "/usr/share/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 207, in load
    self.code = self.verifyHeader()
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 221, in verifyHeader
    raise BadHeader(code, self.getResponse())
BadHeader: Bad server response: 400 Bad Request
11.09.2015 18:51:23 INFO      Debug Report written to debug_FilecryptCc_11-09-2015_18-51-23.zip

```

**Comment by j4m** [comment]
thats right. If you change the Captcha Pattern to '<img id="nc" src="../(.+?)"' you'll get the captchas but thats not the main problem. The main problem is the fucked up cookie handling as mentioned in #1756...
The committed captcha won't work.

**Comment by Gutz-Pilz** [comment]
this really sucks
@vuolter can u please take a look at this ?
also. my hooks and externalscripts hook doesnt work. they are not being executed.

**Comment by Gutz-Pilz** [comment]
@GammaC0de 
you know something about crypter?
i tried my best to fix filecrypt.cc
but totally dont understand the code there.

2 links and 2 different errors

```
25.09.2015 16:15:52 INFO      Decrypting starts: http://filecrypt.cc/Container/3193DFCBF5.html
25.09.2015 16:15:52 DEBUG     CRYPTER FilecryptCc[1794]: PROCESS URL http://filecrypt.cc/Container/3193DFCBF5.html | PLUGIN VERSION 0.19
25.09.2015 16:15:52 DEBUG     CRYPTER FilecryptCc[1794]: LOAD URL http://filecrypt.cc/Container/3193DFCBF5.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 16:15:52 DEBUG     CRYPTER FilecryptCc[1794]: Captcha-URL: ../captcha/captcha.php?namespace=container
25.09.2015 16:15:52 ERROR     Decrypting failed: http://filecrypt.cc/Container/3193DFCBF5.html | global name 'captcha_url' is not defined
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/root/.pyload/userplugins/internal/Hoster.py", line 184, in preprocessing
    return self._process(*args, **kwargs)
  File "/root/.pyload/userplugins/internal/Hoster.py", line 179, in _process
    return self.process(self.pyfile)
  File "/root/.pyload/userplugins/internal/Crypter.py", line 39, in process
    self.decrypt(pyfile)
  File "/root/.pyload/userplugins/crypter/FilecryptCc.py", line 52, in decrypt
    self.handle_captcha()
  File "/root/.pyload/userplugins/crypter/FilecryptCc.py", line 95, in handle_captcha
    captcha = self.load(captcha_url, decode=False)
NameError: global name 'captcha_url' is not defined
```

```
25.09.2015 16:24:20 INFO      Added package A World Beyond (2015) containing 1 links
25.09.2015 16:24:21 INFO      Decrypting starts: http://filecrypt.cc/Container/5C4F06651C.html
25.09.2015 16:24:21 DEBUG     CRYPTER FilecryptCc[1803]: PROCESS URL http://filecrypt.cc/Container/5C4F06651C.html | PLUGIN VERSION 0.19
25.09.2015 16:24:21 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc/Container/5C4F06651C.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 16:24:21 WARNING   CAPTCHA FilecryptCc[1803]: ReCaptcha | Key pattern not found
None
25.09.2015 16:24:21 INFO      CRYPTER FilecryptCc[1803]: No captcha found
25.09.2015 16:24:21 INFO      CRYPTER FilecryptCc[1803]: Found 2 mirrors
25.09.2015 16:24:21 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc/Container/5C4F06651C.html?mirror=1 | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 16:24:21 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc//Link/eoGaN7oli3yrBXRFmvjP-oRXpH3naqe9BJFrLFAM2OgD0gNL4edN9YshUYWH2L_xFkvHU2EWtcQN6b_5hp4g_DpwQ3w4AzAh8AatA6-mRGbckDyQd_CgV4gzKT57O0T4.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 16:24:21 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc//Link/9FWfYe89WJV994NdaK7ClSPA6OZyF_SNyHjXdQM_XmTlXIPjoUhESbTu_ewOhBqTFNrbG9WQBNxFaBc5zX3ypQ.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 16:24:21 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc//Link/6JMeqSqoLIxmQyZq7zj7m7lliqaqqEvHP7xc8_yub-wPQrkapvgCe3FjrFTh_cZTu0oIQhKu9-1hZ5DR9Do0r8OeIK_siXFgYTvnuFHyA6vVineP5IYPui4gOAPhUdBJ.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 16:24:21 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc//Link/5TZWahj0alL9Bil6GQjbMlwZLhAZNZ62e0wBlDj5snR3GqxCkk3Vs0yWDDBvOrozXHGj2-aDeSvYqh3Mujp59A.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 16:24:21 ERROR     Decrypting failed: http://filecrypt.cc/Container/5C4F06651C.html | Decrypt error: No link grabbed | Plugin may be out of date
```

**Comment by GammaC0de** [comment]
`FilecryptCc` uses about 5 different captcha providers randomly, so I guess you're hitting different bugs every time because of that.
Anyway I'll take a look.

**Comment by GammaC0de** [comment]
@Gutz-Pilz How can you download this file?
![untitled](https://cloud.githubusercontent.com/assets/11036551/10108533/2cb5b774-63ca-11e5-9d76-29af054487c2.png)

**Comment by Gutz-Pilz** [comment]
i cant. 
it says.

```
25.09.2015 16:24:20 INFO      Added package A World Beyond (2015) containing 1 links
25.09.2015 16:24:21 INFO      Decrypting starts: http://filecrypt.cc/Container/5C4F06651C.html
25.09.2015 16:24:21 DEBUG     CRYPTER FilecryptCc[1803]: PROCESS URL http://filecrypt.cc/Container/5C4F06651C.html | PLUGIN VERSION 0.19
25.09.2015 16:24:21 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc/Container/5C4F06651C.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 16:24:21 WARNING   CAPTCHA FilecryptCc[1803]: ReCaptcha | Key pattern not found
None
25.09.2015 16:24:21 INFO      CRYPTER FilecryptCc[1803]: No captcha found
25.09.2015 16:24:21 INFO      CRYPTER FilecryptCc[1803]: Found 2 mirrors
25.09.2015 16:24:21 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc/Container/5C4F06651C.html?mirror=1 | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 16:24:21 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc//Link/eoGaN7oli3yrBXRFmvjP-oRXpH3naqe9BJFrLFAM2OgD0gNL4edN9YshUYWH2L_xFkvHU2EWtcQN6b_5hp4g_DpwQ3w4AzAh8AatA6-mRGbckDyQd_CgV4gzKT57O0T4.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 16:24:21 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc//Link/9FWfYe89WJV994NdaK7ClSPA6OZyF_SNyHjXdQM_XmTlXIPjoUhESbTu_ewOhBqTFNrbG9WQBNxFaBc5zX3ypQ.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 16:24:21 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc//Link/6JMeqSqoLIxmQyZq7zj7m7lliqaqqEvHP7xc8_yub-wPQrkapvgCe3FjrFTh_cZTu0oIQhKu9-1hZ5DR9Do0r8OeIK_siXFgYTvnuFHyA6vVineP5IYPui4gOAPhUdBJ.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 16:24:21 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc//Link/5TZWahj0alL9Bil6GQjbMlwZLhAZNZ62e0wBlDj5snR3GqxCkk3Vs0yWDDBvOrozXHGj2-aDeSvYqh3Mujp59A.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 16:24:21 ERROR     Decrypting failed: http://filecrypt.cc/Container/5C4F06651C.html | Decrypt error: No link grabbed | Plugin may be out of date
```

**Comment by GammaC0de** [comment]
No, I mean with a web browser..

**Comment by Gutz-Pilz** [comment]
i just can download the dlc file

**Comment by Gutz-Pilz** [comment]
sorry i made a mistake. iwas changing back to FilecryptCc.py version 0.18
now i got 0.19 and still not working.

```
25.09.2015 20:32:22 INFO      Decrypting starts: http://filecrypt.cc/Container/5C4F06651C.html
25.09.2015 20:32:22 DEBUG     CRYPTER FilecryptCc[1803]: PROCESS URL http://filecrypt.cc/Container/5C4F06651C.html | PLUGIN VERSION 0.19
25.09.2015 20:32:22 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc/Container/5C4F06651C.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 20:32:22 WARNING   CAPTCHA FilecryptCc[1803]: ReCaptcha | Key pattern not found
None
25.09.2015 20:32:22 INFO      CRYPTER FilecryptCc[1803]: No captcha found
25.09.2015 20:32:22 INFO      CRYPTER FilecryptCc[1803]: Found 2 mirrors
25.09.2015 20:32:22 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc/Container/5C4F06651C.html?mirror=1 | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 20:32:22 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc//Link/fycSvftZvysYCNsdHdEXwaY2OgNoAMv2n4jr1sx0U3RF1ZvliMDMHHm6-rB0GI_2ei86A6DE2bNwh7ayfenxTHGhOWQI81z-t9nuUIqp5x4zlnISKV5Gnxvgi6jMlQ2N.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 20:32:22 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc//Link/ts7gQh1NAXbs0w4ZlnQ_zBQ0QySNEYE9P8iSXAzAQMAGC5x4LyKaCOmGacOMytfJADfTpGSWBOGLhV-qsCR6Ew.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 20:32:22 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc//Link/qikER-FUqr7I3FQs1R9tnFh2bzvt7Q_BcfxJDlxwURZrwDi-DGur7XY65L2gVmk1YbdeKDi2pSOt88f0myfS-PKzlKT4bgOEdHwBfLAaXO1-N_aZ4xTEYRKXgHuiBqU1.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 20:32:22 DEBUG     CRYPTER FilecryptCc[1803]: LOAD URL http://filecrypt.cc//Link/G7I96X_JU7KXt3927GzUexgPc5sFm4Y6_dpbJYlKfbsNHOTAMa3QgnzWhVya4pDBx5Zh4PcErfQoNl6fApwQeA.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 20:32:22 ERROR     Decrypting failed: http://filecrypt.cc/Container/5C4F06651C.html | Decrypt error: No link grabbed | Plugin may be out of date
```

**Comment by Gutz-Pilz** [comment]
and on another link:

```
25.09.2015 20:34:20 INFO      Decrypting starts: http://filecrypt.cc/Container/3193DFCBF5.html
25.09.2015 20:34:20 DEBUG     CRYPTER FilecryptCc[1794]: PROCESS URL http://filecrypt.cc/Container/3193DFCBF5.html | PLUGIN VERSION 0.19
25.09.2015 20:34:20 DEBUG     CRYPTER FilecryptCc[1794]: LOAD URL http://filecrypt.cc/Container/3193DFCBF5.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25.09.2015 20:34:20 DEBUG     CRYPTER FilecryptCc[1794]: Captcha-URL: ../captcha/captcha.php?namespace=container
25.09.2015 20:34:20 DEBUG     CAPTCHA FilecryptCc[1794]: Captcha | LOAD URL http://filecrypt.cc/../captcha/captcha.php?namespace=container | cookies=True | get={} | req=None | decode=False | multipart=False | post={} | ref=False | just_header=False
25.09.2015 20:34:20 ERROR     Decrypting failed: http://filecrypt.cc/Container/3193DFCBF5.html | Bad server response: 400 Bad Request
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/root/.pyload/userplugins/internal/Hoster.py", line 184, in preprocessing
    return self._process(*args, **kwargs)
  File "/root/.pyload/userplugins/internal/Hoster.py", line 179, in _process
    return self.process(self.pyfile)
  File "/root/.pyload/userplugins/internal/Crypter.py", line 39, in process
    self.decrypt(pyfile)
  File "/root/.pyload/userplugins/crypter/FilecryptCc.py", line 52, in decrypt
    self.handle_captcha()
  File "/root/.pyload/userplugins/crypter/FilecryptCc.py", line 96, in handle_captcha
    input_type="gif")
  File "/root/.pyload/userplugins/internal/Captcha.py", line 55, in decrypt
    img = self.load(url, get=get, post=post, ref=ref, cookies=cookies, decode=decode)
  File "/root/.pyload/userplugins/internal/Plugin.py", line 359, in load
    res = req.load(url, get, post, ref, bool(cookies), just_header, multipart, decode is True)  #@TODO: Fix network multipart in 0.4.10
  File "/usr/share/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 207, in load
    self.code = self.verifyHeader()
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 221, in verifyHeader
    raise BadHeader(code, self.getResponse())
BadHeader: Bad server response: 400 Bad Request
25.09.2015 20:34:20 INFO      Debug Report written to debug_FilecryptCc_25-09-2015_20-34-20.zip
```

**Comment by GammaC0de** [comment]
@Gutz-Pilz please check #1885 
Let me know if CircleCaptcha works, thx

**Comment by Gutz-Pilz** [comment]
gr8. ill check tonight and let u know!

**Comment by GammaC0de** [comment]
don't forget https://github.com/pyload/pyload/pull/1882 or else it won't work

**Comment by Gutz-Pilz** [comment]
thanks. but i have read that already. i will do that :)
thanks in advance. i am looking forward
:+1:

**Comment by Gutz-Pilz** [comment]
okay. 
changed files to your commits. 
tested on 2 links. both working!!!
but both wasnt circle. still searching for circle.

I let u know when i get circle captcha !

**Comment by GammaC0de** [comment]
good news :+1:

**Comment by Gutz-Pilz** [comment]
Thanks a lot - you're the man !
now i keep my updatmanager turned off for a while :)
:+1: :+1:

**Comment by Leonderi** [comment]
Looks really good.

Thank you!!!

**Comment by Leonderi** [comment]
And by the way, also the Circle Capchas looks like they work.

**Comment by GammaC0de** [comment]
:+1:  trying to get `CircleCaptcha` OCR to work
