### ISSUE TITLE
UploadedTo "no such group" error

### ISSUE THREAD

**Issue by Frozen-byte** [pyload/pyload#1854]
first Problem is: I have entered a valid premium Account but Uploaded still asks for Captcha.
When I solve it - this happens:
```
pyLoad 0.4.9 Debug Report of UploadedTo 0.97 

TRACEBACK:
 Traceback (most recent call last):
  File "/root/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/root/pyload/module/plugins/internal/Hoster.py", line 184, in preprocessing
    return self._process(*args, **kwargs)
  File "/root/pyload/module/plugins/internal/Hoster.py", line 179, in _process
    return self.process(self.pyfile)
  File "/root/pyload/module/plugins/internal/SimpleHoster.py", line 284, in process
    self.handle_free(pyfile)
  File "/root/pyload/module/plugins/hoster/UploadedTo.py", line 80, in handle_free
    self.check_errors()
  File "/root/pyload/module/plugins/internal/SimpleHoster.py", line 362, in check_errors
    errmsg = m.group(1).strip()
IndexError: no such group
 

FRAMESTACK:

Frame preprocessing in /root/pyload/module/plugins/internal/Hoster.py at line 184
                        self = <Hoster UploadedTo>
                        args = (<DownloadThread(Thread-2, started daemon 140231843899136)>,)
                      kwargs = {}

Frame _process in /root/pyload/module/plugins/internal/Hoster.py at line 179
                        self = <Hoster UploadedTo>
                      thread = <DownloadThread(Thread-2, started daemon 140231843899136)>

Frame process in /root/pyload/module/plugins/internal/SimpleHoster.py at line 298
                      pyfile = PyFile 915: 01ruul.part1.rar@UploadedTo
                        self = <Hoster UploadedTo>

Frame handle_free in /root/pyload/module/plugins/hoster/UploadedTo.py at line 80
                      pyfile = PyFile 915: 01ruul.part1.rar@UploadedTo
                   challenge = u'03AHJ_Vuv20YFI-4ZjeBc1dhKidI1P_PKtN4MnSzA0nyGFcNmTt1tj7A088nZBOeQKU8_1Loh9F-POobLkQWDHVOOTzC_pubOBEM3n2fGUSV5S47vgQD7AFHXdViEeM4uUJWHPJXwHTbbbhVbE-EkkcD7zhrEUs5My1WZUUb2ZjdRYbW_SSkQ6VgiuxIodsqpH34wAPlwJxql3'
                   recaptcha = <Captcha ReCaptcha>
                    response = 'from Altrui'
                        self = <Hoster UploadedTo>

Frame check_errors in /root/pyload/module/plugins/internal/SimpleHoster.py at line 365
                        self = <Hoster UploadedTo>
                           m = <_sre.SRE_Match object at 0x2b59ac0>
```

**Comment by Gutz-Pilz** [comment]
same here

**Comment by Frozen-byte** [comment]
After deleting the *.pyc and pulling the newest commit it is working again.
Still not able to login as a premium user - will open another Issue for this:  #1866
