### ISSUE TITLE
UpleaCom : unsupported operand type(s) for -: 'unicode' and 'float'

### ISSUE THREAD

**Issue by f6fvy** [pyload/pyload#1891]
INFO	Download starts: http://uplea.com/dl/xxxxx
INFO	HOSTER UpleaCom[192]: Updating file info...
INFO	HOSTER UpleaCom[192]: File name: xxx.avi
INFO	HOSTER UpleaCom[192]: File size: 1460288880 bytes
INFO	HOSTER UpleaCom[192]: File status: starting
INFO	HOSTER UpleaCom[192]: Processing as free download...
WARNING	Download failed: xxx.avi | unsupported operand type(s) for -: 'unicode' and 'float'

pyload v0.49
UpleaCom v0.13

**Comment by vuolter** [comment]
Debug log please.

**Comment by f6fvy** [comment]
I'm not sure of what you need. I hope this will help :

TRACEBACK:
 Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/pi/.pyload/userplugins/internal/Hoster.py", line 196, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/pi/.pyload/userplugins/internal/Hoster.py", line 191, in _process
    return self.process(self.pyfile)
  File "/home/pi/.pyload/userplugins/internal/SimpleHoster.py", line 279, in process
    self.handle_free(pyfile)
  File "/home/pi/.pyload/userplugins/hoster/UpleaCom.py", line 62, in handle_free
    self.wait(15)
  File "/home/pi/.pyload/userplugins/internal/Hoster.py", line 263, in wait
    self.log_info(_("Waiting %d seconds...") % pyfile.waitUntil - time.time())
TypeError: unsupported operand type(s) for -: 'unicode' and 'float'

**Comment by vuolter** [comment]
:+1:

**Comment by Vince-IN** [comment]
Same with ShareOnline
