### ISSUE TITLE
LinkCryptWs Error in PluginManager

### ISSUE THREAD

**Issue by Bambie42** [pyload/pyload#1896]
testlink: http://linkcrypt.ws/dir/v46j4zoeh2wu6s2

This happens after adding the correct Captcha
```
pyLoad 0.4.9 Debug Report of LinkCryptWs 0.12

TRACEBACK:
 Traceback (most recent call last):
  File "/home/download/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/home/download/pyload/module/plugins/internal/Hoster.py", line 196, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/download/pyload/module/plugins/internal/Hoster.py", line 191, in _process
    return self.process(self.pyfile)
  File "/home/download/pyload/module/plugins/internal/Crypter.py", line 47, in process
    self._create_packages()
  File "/home/download/pyload/module/plugins/internal/Crypter.py", line 80, in _create_packages
    pid = self.pyload.api.addPackage(name, links, package_queue)
  File "/home/download/pyload/module/Api.py", line 328, in addPackage
    self.core.files.addLinks(links, pid)
  File "/home/download/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/home/download/pyload/module/database/FileDatabase.py", line 68, in new
    return func(*args)
  File "/home/download/pyload/module/database/FileDatabase.py", line 126, in addLinks
    data = self.core.pluginManager.parseUrls(urls)
  File "/home/download/pyload/module/plugins/PluginManager.py", line 218, in parseUrls
    if value["re"].match(url):
KeyError: 're'
```

**Comment by Frozen-byte** [comment]
Same Error pops up for filecrypt.cc Module.

**Comment by sraedler** [comment]
It's working

close...
