### ISSUE TITLE
Not able to download - Unexpected keyword argument

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#1899]
30.09.2015 18:45:00	WARNING	Download failed: tvs-reign-ded-dl-ithd-x264-207.part2.rar | get_data() got an unexpected keyword argument 'refresh'

**Comment by maelue** [comment]
Similar to #1898 #1888

**Comment by jackdierippe** [comment]
Same error here with share-online.

**Comment by J-8** [comment]
When using --debug:
```
 get_data() got an unexpected keyword argument 'refresh'
Traceback (most recent call last):
  File "/home/pyload/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/pyload/pyload/module/plugins/internal/Hoster.py", line 196, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/pyload/pyload/module/plugins/internal/Hoster.py", line 191, in _process
    return self.process(self.pyfile)
  File "/home/pyload/pyload/module/plugins/internal/SimpleHoster.py", line 273, in process
    if self.premium and (not self.CHECK_TRAFFIC or self.check_traffic()):
  File "/home/pyload/pyload/module/plugins/internal/Hoster.py", line 582, in check_traffic
    traffic = self.account.get_data(refresh=True)['trafficleft']
TypeError: get_data() got an unexpected keyword argument 'refresh'
```

Any more info we can provide on that?
