### ISSUE TITLE
OSError(2, 'No such file or directory')

### ISSUE THREAD

**Issue by snickers2k** [pyload/pyload#1912]
Don't know really what happened.. Just getting this error, when opening the webinterface, using the latest git version:

Critical error while processing request:

Error:

OSError(2, 'No such file or directory')
Traceback:

Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 820, in wsgi
    out = self._cast(self._handle(environ), request, response)
  File "/usr/share/pyload/module/lib/bottle.py", line 773, in _cast
    out = self.error_handler.get(out.status, repr)(out)
  File "/usr/share/pyload/module/web/pyload_app.py", line 83, in error500
    error.traceback.replace("\n", "
") if error.traceback else "No Traceback"])
  File "/usr/share/pyload/module/web/pyload_app.py", line 72, in base
    return render_to_response('base.html', {'messages': messages}, [pre_processor])
  File "/usr/share/pyload/module/web/utils.py", line 27, in render_to_response
    args.update(p())
  File "/usr/share/pyload/module/web/pyload_app.py", line 45, in pre_processor
    user = parse_userdata(s)
  File "/usr/share/pyload/module/web/utils.py", line 95, in parse_userdata
    return {"name": session.get("name", "Anonymous"),
  File "/usr/share/pyload/module/lib/beaker/session.py", line 554, in __getattr__
    return getattr(self._session(), attr)
  File "/usr/share/pyload/module/lib/beaker/session.py", line 550, in _session
    **params)
  File "/usr/share/pyload/module/lib/beaker/session.py", line 119, in __init__
    self.invalidate()
OSError: [Errno 2] No such file or directory: './tmp'

Is there something wrong on my OS ? Already reinstalled pyload, without success...

**Comment by mattionline** [comment]
An error occured while processing the request.
Traceback (most recent call last):
  File "/home/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/home/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/home/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/home/pyload/module/web/json_app.py", line 182, in add_package
    pack = PYLOAD.addPackage(name, links, queue)
  File "/home/pyload/module/Api.py", line 328, in addPackage
    self.core.files.addLinks(links, pid)
  File "/home/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/home/pyload/module/database/FileDatabase.py", line 68, in new
    return func(*args)
  File "/home/pyload/module/database/FileDatabase.py", line 126, in addLinks
    data = self.core.pluginManager.parseUrls(urls)
  File "/home/pyload/module/plugins/PluginManager.py", line 218, in parseUrls
    if value["re"].match(url):
KeyError: 're'

same here. i cloned pyload before 20 minutes so its the newest version.
This happens when i add a container

**Comment by vuolter** [comment]
As usual try: http://forum.pyload.org/viewtopic.php?f=7&t=4335

**Comment by syss** [comment]
also does the user under which pyload is running has the rights to create files on the filesystem?

You have ./tmp as directory (with leading dot). I don't know if this is what you entered or from pyload.
maybe try a more recent version, a lot of errors have been fixed

**Comment by Velociraptor85** [comment]
@snickers2k closing issue since its old and I guess its solved since there where some ideas regarding the Filesystem and Permission ... can reopen if needed
