### ISSUE TITLE
Share-Online.biz premium not working. 'super' object ha no attribute '_setup' in Hoster.py

### ISSUE THREAD

**Issue by BAERnado** [pyload/pyload#1914]
Using Share-Online premium is not working due to a bug in Hoster.py.
If further information (debugLogs-Files) are needed, please tell me.
Debug output on CLI shows:

01.10.2015 14:57:38 CRITICAL  'super' object has no attribute '_setup'
Traceback (most recent call last):
  File "/home/pyload/pyload/module/ThreadManager.py", line 276, in assignJob
    job.initPlugin()
  File "/home/pyload/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/home/pyload/pyload/module/PyFile.py", line 103, in initPlugin
    self.plugin = self.pluginclass(self)
  File "/home/pyload/.pyload/userplugins/internal/Hoster.py", line 50, in __init__
    self._setup()
  File "/home/pyload/.pyload/userplugins/internal/Hoster.py", line 55, in _setup
    super(Base, self)._setup()
AttributeError: 'super' object has no attribute '_setup'

**Comment by godfuture** [comment]
Guess I was faster ;-)
https://github.com/pyload/pyload/issues/1913
