### ISSUE TITLE
HotFolder: Error executing periodical task: 're'

### ISSUE THREAD

**Issue by manacker** [pyload/pyload#1915]
When trying to add a dlc container via HotFolder the following error occurs:

619	01.10.2015 21:37:25	INFO	ADDON HotFolder: Added 889c794abbe108611a9b113643727dc5f2cd33ab.dlc from HotFolder
620	01.10.2015 21:37:25	ERROR	ADDON HotFolder: Error executing periodical task: 're'

**Comment by vuolter** [comment]
Debug log please.

**Comment by manacker** [comment]
The two lines above is all I get, even with debug mode on. If there is some way to get a stack trace, let me know. I'm running pyload on a Synology NAS.

**Comment by manacker** [comment]
While trying to download something I got a similar error, which might be related. I got this from the debug report:

```
pyLoad 0.4.9 Debug Report of UploadedTo 0.97 

TRACEBACK:
 Traceback (most recent call last):
  File "/volume1/@appstore/pyload/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/volume1/@appstore/pyload/var/config/userplugins/internal/Base.py", line 201, in preprocessing
    return self._process(*args, **kwargs)
  File "/volume1/@appstore/pyload/var/config/userplugins/internal/Hoster.py", line 84, in _process
    self._check_download()
  File "/volume1/@appstore/pyload/var/config/userplugins/internal/Hoster.py", line 270, in _check_download
    elif self.check_file({'Empty file': re.compile(r'\A((.|)(\2|\s)*)\Z')},
NameError: global name 're' is not defined
```

**Comment by vuolter** [comment]
:+1:

**Comment by manacker** [comment]
It is now working again.
