### ISSUE TITLE
Share online - Need more then 1 value to unpack 

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#1920]
02.10.2015 05:07:07 WARNING   Download failed: tvs-rush-au-dl-hdtv-x264-101.part5.rar | need more than 1 value to unpack

Again one issue more.

**Comment by vuolter** [comment]
Debug log please.

**Comment by CodeUnit** [comment]
Same here.

02.10.2015 08:52:58 WARNING   Download failed: xXxXxXxXxXxXxXxXxXxXx.part1.rar | need more than 1 value to unpack
Traceback (most recent call last):
  File "/home/USER/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/USER/.pyload/userplugins/internal/Base.py", line 201, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/USER/.pyload/userplugins/internal/Hoster.py", line 80, in _process
    self.process(self.pyfile)
  File "/home/USER/.pyload/userplugins/internal/SimpleHoster.py", line 289, in process
    self.handle_premium(pyfile)
  File "/home/USER/.pyload/userplugins/hoster/ShareonlineBiz.py", line 126, in handle_premium
    key, value = line.split(": ")
ValueError: need more than 1 value to unpack
02.10.2015 08:52:58 INFO      Debug Report written to debug_ShareonlineBiz_02-10-2015_08-52-58.zip
02.10.2015 08:52:58 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: xXxXxXxXxXxXxXxXxXxXx.part1.rar (pid:27)
02.10.2015 08:52:58 INFO      ADDON UnSkipOnFail: No duplicates found
02.10.2015 08:52:58 DEBUG     All downloads processed
