### ISSUE TITLE
 Error importing LinkdecrypterComHook: No module named MultiHook

### ISSUE THREAD

**Issue by DomiakaSnakez** [pyload/pyload#1921]
I'm not able to add container files. Get these error:
>Error importing LinkdecrypterComHook: No module named MultiHook

Debug Log after starting pyload:

>02.10.2015 07:51:38 ERROR     OpenloadIo has a invalid pattern.
02.10.2015 07:51:39 DEBUG     created index of plugins
02.10.2015 07:51:39 DEBUG     Redirected import module.plugins.hooks.LinkdecrypterComHook -> userplugins.hooks.LinkdecrypterComHook
02.10.2015 07:51:39 ERROR     Error importing LinkdecrypterComHook: No module named MultiHook
Traceback (most recent call last):
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/osmc/.pyload/userplugins/hooks/LinkdecrypterComHook.py", line 5, in <module>
    from module.plugins.internal.MultiHook import MultiHook
ImportError: No module named MultiHook

Debug Log after try to add a DLC (container) file:

>Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/module/web/json_app.py", line 182, in add_package
    pack = PYLOAD.addPackage(name, links, queue)
  File "/usr/share/pyload/module/Api.py", line 328, in addPackage
    self.core.files.addLinks(links, pid)
  File "/usr/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/usr/share/pyload/module/database/FileDatabase.py", line 68, in new
    return func(*args)
  File "/usr/share/pyload/module/database/FileDatabase.py", line 126, in addLinks
    data = self.core.pluginManager.parseUrls(urls)
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 218, in parseUrls
    if value["re"].match(url):
KeyError: 're'
An error occured while processing the request.
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/module/web/json_app.py", line 182, in add_package
    pack = PYLOAD.addPackage(name, links, queue)
  File "/usr/share/pyload/module/Api.py", line 328, in addPackage
    self.core.files.addLinks(links, pid)
  File "/usr/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/usr/share/pyload/module/database/FileDatabase.py", line 68, in new
    return func(*args)
  File "/usr/share/pyload/module/database/FileDatabase.py", line 126, in addLinks
    data = self.core.pluginManager.parseUrls(urls)
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 218, in parseUrls
    if value["re"].match(url):
KeyError: 're'

**Comment by jansohn** [comment]
The pull request I added fixed it for me!

**Comment by vuolter** [comment]
Checking...
