### ISSUE TITLE
Share-Online fails as premium (ShareonlineBiz.py), function handle_premium

### ISSUE THREAD

**Issue by BAERnado** [pyload/pyload#1930]
Downloading from share-online as premium fails (free user works fine).

Traceback (most recent call last):
  File "/home/pyload/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/pyload/.pyload/userplugins/internal/Base.py", line 201, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/pyload/.pyload/userplugins/internal/Hoster.py", line 80, in _process
    self.process(self.pyfile)
  File "/home/pyload/.pyload/userplugins/internal/SimpleHoster.py", line 289, in process
    self.handle_premium(pyfile)
  File "/home/pyload/.pyload/userplugins/hoster/ShareonlineBiz.py", line 126, in handle_premium
    key, value = line.split(": ")

**Comment by vuolter** [comment]
Just fixed the error, not about the plugin at all.
