### ISSUE TITLE
[DLC] Cannot add files: KeyError: 're'

### ISSUE THREAD

**Issue by nordic-style** [pyload/pyload#1952]
Tested with latest commit as i write.
As soon as i add a DLC to pyload i get this error:

```
An error occured while processing the request.
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/user/.local/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/data/media/bin/pyload/stable/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/data/media/bin/pyload/stable/module/web/json_app.py", line 182, in add_package
    pack = PYLOAD.addPackage(name, links, queue)
  File "/data/media/bin/pyload/stable/module/Api.py", line 328, in addPackage
    self.core.files.addLinks(links, pid)
  File "/data/media/bin/pyload/stable/module/utils.py", line 165, in new
    return func(*args)
  File "/data/media/bin/pyload/stable/module/database/FileDatabase.py", line 68, in new
    return func(*args)
  File "/data/media/bin/pyload/stable/module/database/FileDatabase.py", line 126, in addLinks
    data = self.core.pluginManager.parseUrls(urls)
  File "/data/media/bin/pyload/stable/module/plugins/PluginManager.py", line 218, in parseUrls
    if value["re"].match(url):
KeyError: 're'
```

**Comment by Gronkdalonka** [comment]
+1

**Comment by nordic-style** [comment]
With the latest commits the download is added but does not work:
```
05.10.2015 02:21:21 INFO      ADDON UpdateManager: No plugin updates available
05.10.2015 02:21:22 DEBUG     HOSTER BasePlugin[10995]: Config option `use_premium` not found, use default `True`
05.10.2015 02:21:22 INFO      Download starts: rh9wy5km
05.10.2015 02:21:22 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
05.10.2015 02:21:22 DEBUG     HOSTER BasePlugin[10995]: Config option `use_premium` not found, use default `True`
05.10.2015 02:21:22 DEBUG     HOSTER BasePlugin[10995]: PROCESS URL ://http://ul.to/rh9wy5km | PLUGIN VERSION 0.46
05.10.2015 02:21:22 DEBUG     HOSTER BasePlugin[10995]: Config option `fallback_premium` not found, use default `True`
05.10.2015 02:21:22 WARNING   Download failed: rh9wy5km | No plugin matched
05.10.2015 02:21:22 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: rh9wy5km (pid:335)
05.10.2015 02:21:22 INFO      ADDON UnSkipOnFail: No duplicates found
Traceback (most recent call last):
  File "/data/media/bin/pyload/stable/module/database/DatabaseBackend.py", line 96, in processJob
    self.result = self.f(*self.args, **self.kwargs)
  File "/data/media/bin/pyload/stable/module/database/FileDatabase.py", line 767, in updateLink
    self.c.execute('UPDATE links SET url=?,name=?,size=?,status=?,error=?,package=? WHERE id=?', (f.url, f.name, f.size, f.status, f.error, str(f.packageid), str(f.id)))
InterfaceError: Error binding parameter 4 - probably unsupported type.
Database Error @ updateLink (PyFile 10995: rh9wy5km@BasePlugin,) {} Error binding parameter 4 - probably unsupported type.
05.10.2015 02:21:24 DEBUG     HOSTER BasePlugin[10996]: Config option `use_premium` not found, use default `True`
05.10.2015 02:21:24 INFO      Download starts: sxqi1b2h
05.10.2015 02:21:24 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
05.10.2015 02:21:24 DEBUG     HOSTER BasePlugin[10996]: Config option `use_premium` not found, use default `True`
05.10.2015 02:21:24 DEBUG     HOSTER BasePlugin[10996]: PROCESS URL ://http://ul.to/sxqi1b2h | PLUGIN VERSION 0.46
05.10.2015 02:21:24 DEBUG     HOSTER BasePlugin[10996]: Config option `fallback_premium` not found, use default `True`
05.10.2015 02:21:24 WARNING   Download failed: sxqi1b2h | No plugin matched
05.10.2015 02:21:24 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: sxqi1b2h (pid:335)
05.10.2015 02:21:24 INFO      ADDON UnSkipOnFail: No duplicates found
Traceback (most recent call last):
  File "/data/media/bin/pyload/stable/module/database/DatabaseBackend.py", line 96, in processJob
    self.result = self.f(*self.args, **self.kwargs)
  File "/data/media/bin/pyload/stable/module/database/FileDatabase.py", line 767, in updateLink
    self.c.execute('UPDATE links SET url=?,name=?,size=?,status=?,error=?,package=? WHERE id=?', (f.url, f.name, f.size, f.status, f.error, str(f.packageid), str(f.id)))
InterfaceError: Error binding parameter 4 - probably unsupported type.
Database Error @ updateLink (PyFile 10996: sxqi1b2h@BasePlugin,) {} Error binding parameter 4 - probably unsupported type.
05.10.2015 02:21:26 DEBUG     HOSTER BasePlugin[10997]: Config option `use_premium` not found, use default `True`
05.10.2015 02:21:26 INFO      Download starts: 8axiprl9
05.10.2015 02:21:26 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
05.10.2015 02:21:26 DEBUG     HOSTER BasePlugin[10997]: Config option `use_premium` not found, use default `True`
05.10.2015 02:21:26 DEBUG     HOSTER BasePlugin[10997]: PROCESS URL ://http://ul.to/8axiprl9 | PLUGIN VERSION 0.46
05.10.2015 02:21:26 DEBUG     HOSTER BasePlugin[10997]: Config option `fallback_premium` not found, use default `True`
05.10.2015 02:21:26 WARNING   Download failed: 8axiprl9 | No plugin matched
05.10.2015 02:21:26 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: 8axiprl9 (pid:335)
05.10.2015 02:21:26 INFO      ADDON UnSkipOnFail: No duplicates found
```

**Comment by qu1xxderboy** [comment]
same problem here

**Comment by nordic-style** [comment]
Fixed recently.
