### ISSUE TITLE
XFileSharingPro crash

### ISSUE THREAD

**Issue by djgreg13** [pyload/pyload#1954]
```
04.10.2015 22:18:02 INFO      HOOK XFileSharingPro: Handling any hoster I can!
04.10.2015 22:18:02 ERROR     Error executing hooks: bad character range
Traceback (most recent call last):
  File "/usr/share/pyload/module/HookManager.py", line 88, in new
    return func(*args)
  File "/usr/share/pyload/module/HookManager.py", line 198, in coreReady
    plugin.coreReady()
  File "/usr/share/pyload/module/plugins/internal/Addon.py", line 147, in coreReady
    return self.activate(*args, **kwargs)
  File "/usr/share/pyload/module/plugins/hooks/XFileSharingPro.py", line 50, in activate
    self.load_pattern()
  File "/usr/share/pyload/module/plugins/hooks/XFileSharingPro.py", line 89, in load_pattern
    dict['re'] = re.compile(pattern)
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
error: bad character range
```

**Comment by drt1** [comment]
same here...

**Comment by SniffingMyBoxers** [comment]
same..

**Comment by joberreiter** [comment]
@djgreg13 
Please close the issue if the problem is gone, thank you.

**Comment by djgreg13** [comment]
Ok fixed
