### ISSUE TITLE
only can access with ingoknito/private mode in browser

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#1963]
Hi there,

when i am trying to access the webgui i get this

```
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/wsgiserver/__init__.py", line 1174, in communicate
    req.respond()
  File "/usr/share/pyload/module/lib/wsgiserver/__init__.py", line 544, in respond
    self._respond()
  File "/usr/share/pyload/module/lib/wsgiserver/__init__.py", line 556, in _respond
    response = self.wsgi_app(self.environ, self.start_response)
  File "/usr/share/pyload/module/web/middlewares.py", line 53, in __call__
    response.gzip_start_response)
  File "/usr/share/pyload/module/web/middlewares.py", line 17, in __call__
    return self.app(e, h)
  File "/usr/share/pyload/module/lib/beaker/middleware.py", line 152, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/share/pyload/module/lib/bottle.py", line 843, in __call__
    return self.wsgi(environ, start_response)
  File "/usr/share/pyload/module/lib/bottle.py", line 837, in wsgi
    environ['wsgi.errors'].write(err) #TODO: wsgi.error should not get html
IOError: [Errno 5] Input/output error

```

i can bypass that with using the browser ins private/inkognito mode
so i guess it is a cookie issue?

BTW. i have that for month now

**Comment by joberreiter** [comment]
Which server (builtin, threaded, etc.) do you have configured?
Does it reappear if another one is used?

**Comment by Gutz-Pilz** [comment]
```
Critical error while processing request:
Error:

CookieError('Illegal key value: X-OPENMEDIAVAULT-WEBGUI-$1$fnwDJqGy$r5HmQ/FktC3I9qYs.WV8x/',)

Traceback:

Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 820, in wsgi
    out = self._cast(self._handle(environ), request, response)
  File "/usr/share/pyload/module/lib/bottle.py", line 773, in _cast
    out = self.error_handler.get(out.status, repr)(out)
  File "/usr/share/pyload/module/web/pyload_app.py", line 83, in error500
    error.traceback.replace("\n", "
") if error.traceback else "No Traceback"])
  File "/usr/share/pyload/module/web/pyload_app.py", line 72, in base
    return render_to_response('base.html', {'messages': messages}, [pre_processor])
  File "/usr/share/pyload/module/web/utils.py", line 27, in render_to_response
    args.update(p())
  File "/usr/share/pyload/module/web/pyload_app.py", line 45, in pre_processor
    user = parse_userdata(s)
  File "/usr/share/pyload/module/web/utils.py", line 95, in parse_userdata
    return {"name": session.get("name", "Anonymous"),
  File "/usr/share/pyload/module/lib/beaker/session.py", line 554, in __getattr__
    return getattr(self._session(), attr)
  File "/usr/share/pyload/module/lib/beaker/session.py", line 550, in _session
    **params)
  File "/usr/share/pyload/module/lib/beaker/session.py", line 105, in __init__
    self.cookie = Cookie.SimpleCookie(input=cookieheader)
CookieError: Illegal key value: X-OPENMEDIAVAULT-WEBGUI-$1$fnwDJqGy$r5HmQ/FktC3I9qYs.WV8x/

```

Thats what fastcgi gives me

**Comment by Gutz-Pilz** [comment]
https://github.com/pyload/pyload/issues/1228

**Comment by joberreiter** [comment]
Something must be special at your installation.

Searching the web for 'Illegal key value' shows that this primary might be a bug in the Python Cookie Module itself [[1]][]. The key value `OPENMEDIAVAULT-WEBGUI` points to [[2]][], which seems to be a) running on your machine and b) is obviously the origin of this illegal cookie key.

Workarounds:
- step up to a more recent version of python (as the error may be fixed in the cookie module)
- clear the (cookie) cache both in your browser an in your config folder of pyLoad (as maybe the cookie is gone with that)
- 'avoid' OpenMediaVault (I can't be more specific, as I don't know it).

As far as I think, this is _NOT_ a pyLoad related problem.

[1]: https://groups.google.com/forum/#!topic/django-users/0nRCNXl1w6w
[2]: http://www.openmediavault.org/

**Comment by joberreiter** [comment]
It seems that this issue is still open at the [beaker issue list](https://github.com/bbangert/beaker/issues/24https://github.com/bbangert/beaker/issues/24).

Do you access the pyLoad web user interface over OpenMediaVault?

**Comment by Gutz-Pilz** [comment]
OMV is installed on my PI2
OMV is based on Debian Wheezy.
pyload is manually installed.

I access it over global internet sometimes

**Comment by joberreiter** [comment]
I would file a bug report to [OpenMediaVault](http://sourceforge.net/projects/openmediavault/), as [RFC6265](http://tools.ietf.org/html/rfc6265#section-4.1.1) and [RFC2616](http://tools.ietf.org/html/rfc2616#section-3.3.1) states that an "/" in the cookie name should not be used, as far as i interpret the RFC correctly.
And I would copy the issue at [beaker](https://github.com/bbangert/beaker/issues/24), maybe beaker can handle or bypass this error.

**Comment by joberreiter** [comment]
Please close #1228 and #1963.

**Comment by driet** [comment]
Had a similar problem a while ago, got a broken webgui, but only on windows systems; linux and tablet worked fine. Did a pyload backup, then reinstall and finally copied an actual copy of the repository from github over the installation (backup dismissed then ;). But I don't know what finally fixed it.

**Comment by joberreiter** [comment]
@driet 
Do you also use OpenMediaVault?

**Comment by driet** [comment]
Didn't run a debug, so can't tell. And it's running fine on all systems, now. No OMV, it ran on an proprietary NAS-OS.
