### ISSUE TITLE
[SimpleHoster] Key Error: 'pattern'

### ISSUE THREAD

**Issue by joberreiter** [pyload/pyload#1974]
```
08.10.2015 08:27:15 DEBUG     HOSTER UploadedTo[13364]: PROCESS URL http://uploaded.net/file/xxxxxxxx | PLUGIN VERSION 0.97
08.10.2015 08:27:15 INFO      HOSTER UploadedTo[13364]: Updating file info...
08.10.2015 08:27:15 WARNING   Download failed: xxxxxxxx.iso | 'pattern'
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/usr/share/pyload/module/plugins/internal/Base.py", line 201, in preprocessing
    return self._process(*args, **kwargs)
  File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 80, in _process
    self.process(self.pyfile)
  File "/usr/share/pyload/module/plugins/internal/SimpleHoster.py", line 264, in process
    self.check_info()  #@TODO: Remove in 0.4.10
  File "/usr/share/pyload/module/plugins/internal/SimpleHoster.py", line 483, in check_info
    self.check_name_size()
  File "/usr/share/pyload/module/plugins/internal/SimpleHoster.py", line 452, in check_name_size
    self.info.update(self.get_info(self.pyfile.url, self.html))
  File "/usr/share/pyload/module/plugins/internal/SimpleHoster.py", line 191, in get_info
    if 'N' in info['pattern']:
KeyError: 'pattern'
```

**Comment by vuolter** [comment]
Detected!

**Comment by vuolter** [comment]
Fixed.
