### ISSUE TITLE
[SimpleHoster|UploadedTo] KeyError: 'ID'

### ISSUE THREAD

**Issue by joberreiter** [pyload/pyload#1979]
Seems to be a successor to #1974.

```
08.10.2015 13:42:51 DEBUG     HOSTER UploadedTo[9883]: PROCESS URL http://uploaded.net/file/xxxxxxxx | PLUGIN VERSION 0.97
08.10.2015 13:42:51 INFO      HOSTER UploadedTo[9883]: Updating file info...
08.10.2015 13:42:52 DEBUG     HOSTER UploadedTo[9883]: File info: {'status': 2, 'name': 'KDZEREv.part2.rar', 'url': u'http://uploaded.net/file/xxxxxxxx', 'pattern': {}, 'folder': 'KDZEREv.part2.rar', 'size': 25436706.0}
08.10.2015 13:42:52 DEBUG     HOSTER UploadedTo[9883]: Previous file info: {'status': 2, 'name': 'KDZEREv.part2.rar', 'url': u'http://uploaded.net/file/xxxxxxxx', 'pattern': {}, 'folder': 'KDZEREv.part2.rar', 'size': 25436706.0}
08.10.2015 13:42:52 INFO      HOSTER UploadedTo[9883]: File name: KDZEREv.part2.rar
08.10.2015 13:42:52 INFO      HOSTER UploadedTo[9883]: File size: 25436706 bytes
08.10.2015 13:42:52 INFO      HOSTER UploadedTo[9883]: File status: starting
08.10.2015 13:42:52 DEBUG     HOSTER UploadedTo[9883]: LOAD URL http://uploaded.net/file/xxxxxxxx | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
08.10.2015 13:42:52 INFO      HOSTER UploadedTo[9883]: Processing as free download...
08.10.2015 13:42:52 DEBUG     HOSTER UploadedTo[9883]: LOAD URL http://uploaded.net/language/en | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
08.10.2015 13:42:52 DEBUG     HOSTER UploadedTo[9883]: LOAD URL http://uploaded.net/js/download.js | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
08.10.2015 13:42:52 DEBUG     CAPTCHA UploadedTo[9883]: ReCaptcha | Key: 6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3
08.10.2015 13:42:52 DEBUG     HOSTER UploadedTo[9883]: LOAD URL http://www.google.com/recaptcha/api/challenge | redirect=True | cookies=True | get={'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
08.10.2015 13:42:52 DEBUG     CAPTCHA UploadedTo[9883]: ReCaptcha | Challenge: 03AHJ_VuuxyYEd47BM5tMqDKy3D8xV7TrwZboVu9RyqEwLLV5FR2AIwQgPOclp5Xs3RtsFIBPuHSOwn6cUhleeojvn5vPhZHvQWTlApWo0BzQveD-qsv7rrI4AiNQiuA5vl_bIAiDFz4pgnv_xMovKel7adNtC4MXdE5L9yBI1PZWwB-m2LnENuzXU1BCnsoizfNgrHk-tkbKb
08.10.2015 13:42:52 DEBUG     HOSTER UploadedTo[9883]: LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
08.10.2015 13:42:52 DEBUG     HOSTER UploadedTo[9883]: LOAD URL http://www.google.com/recaptcha/api/reload | redirect=True | cookies=True | get={'reason': 'i', 'c': u'03AHJ_VuuxyYEd47BM5tMqDKy3D8xV7TrwZboVu9RyqEwLLV5FR2AIwQgPOclp5Xs3RtsFIBPuHSOwn6cUhleeojvn5vPhZHvQWTlApWo0BzQveD-qsv7rrI4AiNQiuA5vl_bIAiDFz4pgnv_xMovKel7adNtC4MXdE5L9yBI1PZWwB-m2LnENuzXU1BCnsoizfNgrHk-tkbKb', 'type': 'image', 'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
08.10.2015 13:42:53 DEBUG     CAPTCHA UploadedTo[9883]: ReCaptcha | Second challenge: 03AHJ_VutPbbJ3NEfuUJLreQu3HT6hFUSBpqvmcRQ-1qpzdzCs83OLUW2G-a-XPXWmQ82kf8ozfC9WG7FklHghQu10V7lHOTUqQgkBEWUyjZ5BtT-9muRuGvdUYB_1haMt2CNlTHgNqdOD2VE_a7M_a6j_LfAgNQph-qbL5MXKIQEg7RReO-MejfSkcfjq5lbp5gbX7a6_VWxg
08.10.2015 13:42:53 DEBUG     CAPTCHA UploadedTo[9883]: ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | redirect=True | cookies=True | get={'c': u'03AHJ_VutPbbJ3NEfuUJLreQu3HT6hFUSBpqvmcRQ-1qpzdzCs83OLUW2G-a-XPXWmQ82kf8ozfC9WG7FklHghQu10V7lHOTUqQgkBEWUyjZ5BtT-9muRuGvdUYB_1haMt2CNlTHgNqdOD2VE_a7M_a6j_LfAgNQph-qbL5MXKIQEg7RReO-MejfSkcfjq5lbp5gbX7a6_VWxg'} | req=<module.network.Browser.Browser object at 0x27343b0> | decode=False | multipart=False | post={} | ref=False | just_header=False
08.10.2015 13:43:12 DEBUG     CAPTCHA UploadedTo[9883]: ReCaptcha | Result: sons Monditcu
08.10.2015 13:43:12 WARNING   Download failed: KDZEREv.part2.rar | 'ID'
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/var/local/pyload/userplugins/internal/Base.py", line 205, in preprocessing
    return self._process(*args, **kwargs)
  File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 80, in _process
    self.process(self.pyfile)
  File "/var/local/pyload/userplugins/internal/SimpleHoster.py", line 282, in process
    self.handle_free(pyfile)
  File "/usr/share/pyload/module/plugins/hoster/UploadedTo.py", line 77, in handle_free
    self.html = self.load("http://uploaded.net/io/ticket/captcha/%s" % self.info['pattern']['ID'],
KeyError: 'ID'
```

**Comment by pixou80** [comment]
for me it's | 'ID1' for 1fichier.com

**Comment by thadrien** [comment]
Corrected for OneFichierCom. See https://github.com/pyload/pyload/pull/1989.
For UploadedTo, it doesn't work for me even in normal browser...

**Comment by GammaC0de** [comment]
@joberreiter try #1997 and post the result please
