### ISSUE TITLE
RealDebrid not working

### ISSUE THREAD

**Issue by thstorm** [pyload/pyload#1990]
Realdebrid is not working on my pyload-installation. (Fresh checkout from github)

-Realdebrid Account is working and is added to pyload
-pyload does not use RealDebrid for downloading for example uploaded.to links.
-No settings are changed in RealDebridCom plugin.

I also reported this in the forum to get help:
http://forum.pyload.org/viewtopic.php?f=12&t=4610

**Comment by chaosmaker** [comment]
Same here. Mine actually crashes with the following error messages which seem to affect Hook.py and the relevant plugins:
'''
DataStation> python pyLoadCore.py -d
11.10.2015 08:31:53 INFO      Starting pyLoad 0.4.9
11.10.2015 08:31:53 INFO      Using home directory: /opt/share/pyload_config
11.10.2015 08:31:53 DEBUG     Deleting old pidfile pyload.pid
11.10.2015 08:31:53 DEBUG     Remote activated: True
11.10.2015 08:31:58 DEBUG     created index of plugins
11.10.2015 08:31:58 DEBUG     Redirected import module.plugins.hooks.LinkdecrypterComHook -> userplugins.hooks.LinkdecrypterComHook
11.10.2015 08:31:58 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
11.10.2015 08:31:58 DEBUG     Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
11.10.2015 08:31:59 DEBUG     Redirected import module.plugins.hooks.ClickNLoad -> userplugins.hooks.ClickNLoad
11.10.2015 08:31:59 DEBUG     Redirected import module.plugins.hooks.MergeFiles -> userplugins.hooks.MergeFiles
11.10.2015 08:31:59 DEBUG     Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
11.10.2015 08:31:59 WARNING   Failed activating ExternalScripts
Traceback (most recent call last):
  File "/volume1/public/pyload/pyload/module/HookManager.py", line 130, in createIndex
    plugin = pluginClass(self.core, self)
  File "/opt/share/pyload_config/userplugins/internal/Addon.py", line 60, in __init__
    self.init_events()
  File "/opt/share/pyload_config/userplugins/internal/Addon.py", line 76, in init_events    self.log_debug("Deprecated method `event_list`, use `event_map` instead")
  File "/opt/share/pyload_config/userplugins/internal/Plugin.py", line 318, in log_debug    self._log("debug", self.__type, self.__name, args)
AttributeError: 'ExternalScripts' object has no attribute '_Plugin__type'
11.10.2015 08:31:59 DEBUG     Redirected import module.plugins.hooks.XFileSharingPro -> userplugins.hooks.XFileSharingPro
11.10.2015 08:31:59 WARNING   Failed activating XFileSharingPro
Traceback (most recent call last):
  File "/volume1/public/pyload/pyload/module/HookManager.py", line 130, in createIndex
    plugin = pluginClass(self.core, self)
  File "/volume1/public/pyload/pyload/module/plugins/internal/Hook.py", line 23, in __init__
    self.init_periodical(10)
AttributeError: 'XFileSharingPro' object has no attribute 'init_periodical'
11.10.2015 08:31:59 DEBUG     Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
11.10.2015 08:31:59 DEBUG     Redirected import module.plugins.internal.Extractor -> userplugins.internal.Extractor
11.10.2015 08:31:59 DEBUG     Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
11.10.2015 08:31:59 DEBUG     Redirected import module.plugins.internal.MultiHoster -> userplugins.internal.MultiHoster
11.10.2015 08:31:59 DEBUG     Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
11.10.2015 08:31:59 DEBUG     Redirected import module.plugins.internal.Hoster -> userplugins.internal.Hoster
11.10.2015 08:31:59 DEBUG     Redirected import module.plugins.internal.Base -> userplugins.internal.Base
11.10.2015 08:31:59 DEBUG     Redirected import module.plugins.internal.Captcha -> userplugins.internal.Captcha
11.10.2015 08:31:59 WARNING   Failed activating RealdebridComHook
Traceback (most recent call last):
  File "/volume1/public/pyload/pyload/module/HookManager.py", line 130, in createIndex
    plugin = pluginClass(self.core, self)
  File "/volume1/public/pyload/pyload/module/plugins/internal/Hook.py", line 23, in __init__
    self.init_periodical(10)
AttributeError: 'RealdebridComHook' object has no attribute 'init_periodical'
11.10.2015 08:31:59 INFO      Activated plugins: ClickAndLoad, ClickNLoad, ExtractArchive, LinkdecrypterComHook, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher
11.10.2015 08:31:59 INFO      Deactivate plugins: AlldebridComHook, AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMeHook, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinksnappyComHook, LogMarker, MegaDebridEuHook, MegaRapidoNetHook, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, TransmissionRPC, WindowsPhoneNotify, XMPPInterface, ZeveraComHook
11.10.2015 08:31:59 INFO      Downloadtime: True
11.10.2015 08:31:59 INFO      Starting ThriftBackend: 0.0.0.0:7227
11.10.2015 08:32:01 INFO      Free space: 70.21 GiB
11.10.2015 08:32:01 INFO      Starting builtin webserver: 0.0.0.0:8000
11.10.2015 08:32:01 INFO      Activating Accounts...
11.10.2015 08:32:01 DEBUG     Redirected import module.plugins.accounts.RealdebridCom -> userplugins.accounts.RealdebridCom
11.10.2015 08:32:01 DEBUG     Redirected import module.plugins.internal.Account -> userplugins.internal.Account
Traceback (most recent call last):
  File "/volume1/public/pyload/pyload/pyLoadCore.py", line 667, in <module>
    main()
  File "/volume1/public/pyload/pyload/pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "/volume1/public/pyload/pyload/pyLoadCore.py", line 433, in start
    self.accountManager.getAccountInfos()
  File "/volume1/public/pyload/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/volume1/public/pyload/pyload/module/plugins/AccountManager.py", line 176, in getAccountInfos
    data[p.__name__] = p.getAllAccounts(force)
  File "/volume1/public/pyload/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/share/pyload_config/userplugins/internal/Account.py", line 311, in getAllAccounts
    self.init_accounts()  #@TODO: Recheck in 0.4.10
  File "/volume1/public/pyload/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/share/pyload_config/userplugins/internal/Account.py", line 297, in init_accounts
    self.add(user, info['password'], info['options'])
  File "/volume1/public/pyload/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/share/pyload_config/userplugins/internal/Account.py", line 324, in add
    self.log_info(_("Adding user `%s`...") % user)
  File "/opt/share/pyload_config/userplugins/internal/Plugin.py", line 325, in log_info
    self._log("info", self.__type, self.__name, args)
AttributeError: 'RealdebridCom' object has no attribute '_Plugin__type'
'''

**Comment by vuolter** [comment]
@thstorm MultiAccount plugin is broken, so any multi-hoster will not work.
@chaosmaker Fixed yesterday.
