### ISSUE TITLE
__type__ or __type?

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1998]
after the recent changes these errors appeared:
```
Traceback (most recent call last):
  File "/usr/share/pyload/module/HookManager.py", line 88, in new
    return func(*args)
  File "/usr/share/pyload/module/HookManager.py", line 197, in coreReady
    if plugin.isActivated():
  File "/home/user/.pyload-0.4.9/userplugins/internal/Addon.py", line 148, in isActivated
    return self.activated
  File "/home/user/.pyload-0.4.9/userplugins/internal/Addon.py", line 143, in activated
    return self.get_config("activated")
  File "/home/user/.pyload-0.4.9/userplugins/internal/Plugin.py", line 399, in get_config
    self.log_debug("Config option `%s` not found, use default `%s`" % (option, default or None))  #@TODO: Restore to `log_warning` in 0.4.10
  File "/home/user/.pyload-0.4.9/userplugins/internal/Plugin.py", line 318, in log_debug
    self._log("debug", self.__type, self.__name, args)
AttributeError: 'AntiStandby' object has no attribute '_Plugin__type'
```

I noticed that, in the log_xxx() functions, `__type__` was changed to `__type` but was not changed on the other files (plugins)

So, which is correct? `__type__`  or `__type`?

also in [Addon.py](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/Addon.py#L25), there are both `__type__`  and `__type`..

**Comment by nordic-style** [comment]
Could you please change the topic to match your problem?

This happens all over the place:

'''
10.10.2015 20:49:29 INFO      Activating Accounts...
Traceback (most recent call last):
  File "/data/media/bin/pyload/stable/pyLoadCore.py", line 667, in <module>
    main()
  File "/data/media/bin/pyload/stable/pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "/data/media/bin/pyload/stable/pyLoadCore.py", line 433, in start
    self.accountManager.getAccountInfos()
  File "/data/media/bin/pyload/stable/module/utils.py", line 165, in new
    return func(*args)
  File "/data/media/bin/pyload/stable/module/plugins/AccountManager.py", line 175, in getAccountInfos
    p = self.getAccountPlugin(p)
  File "/data/media/bin/pyload/stable/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
  File "/data/media/bin/pyload/stable/module/plugins/internal/Account.py", line 31, in __init__
    self._init(manager.core)
  File "/data/media/bin/pyload/stable/module/plugins/internal/Plugin.py", line 297, in _init
    value = getattr(self, "__%s__" % attr)
AttributeError: 'UploadedTo' object has no attribute '__name__'
'''
and

'''
10.10.2015 20:49:29 WARNING   Failed activating ClickNLoad
Traceback (most recent call last):
  File "/data/media/bin/pyload/stable/module/HookManager.py", line 130, in createIndex
    plugin = pluginClass(self.core, self)
  File "/data/media/bin/pyload/stable/module/plugins/internal/Addon.py", line 41, in __init__
    self._init(core)
  File "/data/media/bin/pyload/stable/module/plugins/internal/Plugin.py", line 297, in _init
    value = getattr(self, "__%s__" % attr)
AttributeError: 'ClickNLoad' object has no attribute '__name__'
'''

or

'''
10.10.2015 20:49:29 WARNING   Failed activating ExtractArchive
Traceback (most recent call last):
  File "/data/media/bin/pyload/stable/module/HookManager.py", line 130, in createIndex
    plugin = pluginClass(self.core, self)
  File "/data/media/bin/pyload/stable/module/plugins/internal/Addon.py", line 41, in __init__
    self._init(core)
  File "/data/media/bin/pyload/stable/module/plugins/internal/Plugin.py", line 297, in _init
    value = getattr(self, "__%s__" % attr)
AttributeError: 'ExtractArchive' object has no attribute '__name__'
'''

or

'''
10.10.2015 20:49:29 WARNING   Failed activating XFileSharingPro
Traceback (most recent call last):
  File "/data/media/bin/pyload/stable/module/HookManager.py", line 130, in createIndex
    plugin = pluginClass(self.core, self)
  File "/data/media/bin/pyload/stable/module/plugins/internal/Addon.py", line 41, in __init__
    self._init(core)
  File "/data/media/bin/pyload/stable/module/plugins/internal/Plugin.py", line 297, in _init
    value = getattr(self, "__%s__" % attr)
AttributeError: 'XFileSharingPro' object has no attribute '__name__'
'''

**Comment by GammaC0de** [comment]
so what topic do you suggest?

also from your log i can see that you have problem with `__name__` not definded, not `__type__`
this can be solved by refreshing your userplugins

**Comment by nordic-style** [comment]
What do you mean by "refreshing your userplugins" ? I just deleted all userplugins and pulled the latest code - or are you talking about fixing it myself?

Maybe your topic name is fine ;)

**Comment by GammaC0de** [comment]
looking further in the recent changes, on some files `__name` / `__type` is used and on other files `__name__` / `__type__`  is used
so I would wait for @vuolter for a fix.
