### ISSUE TITLE
LinkCryptWs/ Captcha Unicode Error

### ISSUE THREAD

**Issue by Bambie42** [pyload/pyload#2003]
Maybe  other plugins are affected, too?

```
TRACEBACK:
 Traceback (most recent call last):
  File "/home/download/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/home/download/pyload/module/plugins/internal/Base.py", line 218, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/download/pyload/module/plugins/internal/Base.py", line 213, in _process
    self.process(self.pyfile)
  File "/home/download/pyload/module/plugins/internal/Crypter.py", line 39, in process
    self.decrypt(pyfile)
  File "/home/download/pyload/module/plugins/crypter/LinkCryptWs.py", line 64, in decrypt
    self.unlock_captcha_protection()
  File "/home/download/pyload/module/plugins/crypter/LinkCryptWs.py", line 136, in unlock_captcha_pro
    captcha_code = self.captcha.decrypt(captcha_url, input_type="gif", output_type='positional')
  File "/home/download/pyload/module/plugins/internal/Captcha.py", line 54, in decrypt
    img = self.load(url, get=get, post=post, ref=ref, cookies=cookies, decode=decode, req=req or self
  File "/home/download/pyload/module/plugins/internal/Plugin.py", line 517, in load
    f.write(encode(html))
  File "/home/download/pyload/module/plugins/internal/Plugin.py", line 67, in encode
    res = encode(decode(string, decoding), encoding)
  File "/home/download/pyload/module/plugins/internal/Plugin.py", line 44, in decode
    res = unicode(string, encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd6 in position 6: invalid continuation byte
```

**Comment by sraedler** [comment]
I guess this is also done...
