### ISSUE TITLE
Plugin Unicode Error

### ISSUE THREAD

**Issue by izderadicka** [pyload/pyload#2010]
```
 'ascii' codec can't encode character u'\xe9' in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/ivan/tmp/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/ivan/.pyload/userplugins/internal/Base.py", line 217, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/ivan/.pyload/userplugins/internal/Hoster.py", line 87, in _process
    self.process(self.pyfile)
  File "/home/ivan/.pyload/userplugins/internal/SimpleHoster.py", line 252, in process
    self.check_info()  #@TODO: Remove in 0.4.10
  File "/home/ivan/.pyload/userplugins/internal/SimpleHoster.py", line 475, in check_info
    self.check_name_size()
  File "/home/ivan/.pyload/userplugins/internal/SimpleHoster.py", line 446, in check_name_size
    self.info.update(self.get_info(self.pyfile.url, self.html))
  File "/home/ivan/.pyload/userplugins/internal/SimpleHoster.py", line 184, in get_info
    info['name'] = parse_name(name)
  File "/home/ivan/.pyload/userplugins/internal/Plugin.py", line 103, in parse_name
    path  = fixurl(decode(string), unquote=False)
  File "/home/ivan/.pyload/userplugins/internal/Plugin.py", line 93, in fixurl
    newurl = html_unescape(decode(newurl).decode('unicode-escape'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 6: ordinal not in range(128)
```

Problem here is with using decode on unicode object -   decode is ment  to be used on bytes - so unicode is first converted to bytes using default encoding, which is ascii in python 2. I tried to fix it, however then there is problem with urlib,quote, which does not seem to know how to handle unicode.

This was working :

``` python
   newurl = html_unescape(decode(newurl).encode('utf8').decode('unicode-escape'))
    newurl = re.sub(r'(?<!:)/{2,}', '/', newurl).strip().lstrip('.')

    if not unquote:
        newurl = unicode(urllib.quote(newurl.encode('utf8')), 'utf8')
```

However then name was corrupted. 

Generally I think there are two many encoding/decoding, quoting/unquoting back and forth.  Solution that finally worked for me was to change parse_name like this:

``` python
def parse_name(string):
    path  = decode(string)
    url_p = urlparse.urlparse(path.rstrip('/'))
    name  = (url_p.path.split('/')[-1] or
             url_p.query.split('=', 1)[::-1][0].split('&', 1)[0] or
             url_p.netloc.split('.', 1)[0])

    return name
```

**Comment by sschwart** [comment]
There is a solution in post #2286 ;)
It works great for me :)

**Comment by Velociraptor85** [comment]
@vuolter @GammaC0de pls close is duplicate and already in "main" issue thread linked #2286
