### ISSUE TITLE
Debug problem when using OCR decoding plugin

### ISSUE THREAD

**Issue by izderadicka** [pyload/pyload#2011]
```
Traceback (most recent call last):
  File "/home/ivan/tmp/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/ivan/.pyload/userplugins/internal/Base.py", line 217, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/ivan/.pyload/userplugins/internal/Hoster.py", line 87, in _process
    self.process(self.pyfile)
  File "/home/ivan/.pyload/userplugins/internal/SimpleHoster.py", line 283, in process
    self.handle_free(pyfile)
  File "/home/ivan/.pyload/userplugins/hoster/UlozTo.py", line 76, in handle_free
    captcha_value = self.captcha.decrypt(str(data['sound']), input_type='wav', ocr="UlozTo")
  File "/home/ivan/.pyload/userplugins/internal/Captcha.py", line 54, in decrypt
    img = self.load(url, get=get, post=post, ref=ref, cookies=cookies, decode=decode, req=req or self.plugin.req)
  File "/home/ivan/.pyload/userplugins/internal/Plugin.py", line 518, in load
    f.write(encode(html))
  File "/home/ivan/.pyload/userplugins/internal/Plugin.py", line 67, in encode
    res = encode(decode(string, decoding), encoding)
  File "/home/ivan/.pyload/userplugins/internal/Plugin.py", line 44, in decode
    res = unicode(string, encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 4: invalid continuation byte
```

Problem is caused by decoding response body as  text in debug mode (I guess for printing - ine 518, in load f.write(encode(html))) in load method -  however load is also used to get catcha file, which is binary.

**Comment by GammaC0de** [comment]
same as #2003
