### ISSUE TITLE
Scheduler Incorrect padding

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#2016]
```
root@pi-server:~# 12.10.2015 21:21:11 ERROR     HOOK HDAreaOrg: Error executing periodical task: Incorrect padding
Traceback (most recent call last):
  File "/usr/bin/pyLoadCore", line 667, in <module>
    main()
  File "/usr/bin/pyLoadCore", line 658, in main
    pyload_core.start()
  File "/usr/bin/pyLoadCore", line 469, in start
    self.scheduler.work()
  File "/usr/share/pyload/module/Scheduler.py", line 85, in work
    j.start()
  File "/usr/share/pyload/module/Scheduler.py", line 111, in start
    self.run()
  File "/usr/share/pyload/module/Scheduler.py", line 101, in run
    ret = self.call(*self.args, **self.kwargs)
  File "/root/.pyload/userplugins/internal/Addon.py", line 121, in _periodical
    self.log_error(_("Error executing periodical task: %s") % e, trace=True)
```

i get this, since the new update
can u explain how to rewrite my hooks to be addons and let them be executed on start and repeat periodically.
They worked before the last update...

**Comment by GammaC0de** [comment]
@Gutz-Pilz replace `Plugin.py` (backup the old one) with the one in #2019 then repost the Traceback

**Comment by Gutz-Pilz** [comment]
```
13.10.2015 09:07:52 WARNING   Konnte HDAreaOrg nicht aktivieren
Traceback (most recent call last):
  File "/usr/share/pyload/module/HookManager.py", line 130, in createIndex
    plugin = pluginClass(self.core, self)
  File "/root/.pyload/userplugins/internal/Hook.py", line 23, in __init__
    self.init_periodical(10)
AttributeError: 'HDAreaOrg' object has no attribute 'init_periodical'
```

**Comment by GammaC0de** [comment]
@Gutz-Pilz your `Hook.py` is not up to date..

**Comment by Gutz-Pilz** [comment]
where is Hook.py ?
https://github.com/pyload/pyload/tree/stable/module/plugins/internal

**Comment by GammaC0de** [comment]
oh, I see it was deleted,
you should now derive your class from `Addon`

**Comment by Gutz-Pilz** [comment]
Did 
now i get this 
```
13.10.2015 11:12:05 INFO      HOOK SJ: NEW EPISODE: The.Big.Bang.Theory.S09E04.720p.HDTV.X264-DIMENSION
13.10.2015 11:12:05 DEBUG     Redirected import module.plugins.crypter.SerienjunkiesOrg -> userplugins.crypter.SerienjunkiesOrg
13.10.2015 11:12:05 INFO      Added package The.Big.Bang.Theory.S09E04.720p.HDTV.X264-DIMENSION containing 1 links
13.10.2015 11:12:06 ERROR     HOOK SJ: Error executing periodical task: Incorrect padding
13.10.2015 11:12:06 ERROR     Traceback (most recent call last):
  File "/usr/share/pyload/module/Scheduler.py", line 101, in run
    ret = self.call(*self.args, **self.kwargs)
  File "/root/.pyload/userplugins/internal/Addon.py", line 118, in _periodical
    self.periodical()
  File "/root/.pyload/userplugins/hooks/SJ.py", line 144, in periodical
    self.range_checkr(link,title)
  File "/root/.pyload/userplugins/hooks/SJ.py", line 195, in range_checkr
    self.parse_download(link, title)
  File "/root/.pyload/userplugins/hooks/SJ.py", line 221, in parse_download
    self.send_package(title,items) if len(items) > 0 else True
  File "/root/.pyload/userplugins/hooks/SJ.py", line 224, in send_package
    storage = self.retrieve(title)
  File "/root/.pyload/userplugins/internal/Plugin.py", line 443, in retrieve
    value = json_loads(entry.decode('base64'))
  File "/usr/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/usr/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
```

**Comment by Gutz-Pilz** [comment]
it seems to be executed a little bit. but than it errors

**Comment by GammaC0de** [comment]
problem resides in `Plugin.py`'s [`retrieve`](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/Plugin.py#L433) function that is called by [SJ.py#L225](https://github.com/Gutz-Pilz/pyLoad-stuff/blob/master/SJ.py#L225)

**Comment by GammaC0de** [comment]
also, try changing the code as below and post the result:
```python
    def send_package(self, title, link):
        try:
            storage = self.retrieve(title)
        except Exception:
            self.log_debug("retrieve got exception, title: %s" % title)
```

**Comment by Gutz-Pilz** [comment]
```
13.10.2015 22:58:36 DEBUG     HOOK SJ: retrieve got exception, title: The.Big.Bang.Theory.S09E04.720p.HDTV.X264-DIMENSION
13.10.2015 22:58:36 ERROR     HOOK SJ: Error executing periodical task: local variable 'storage' referenced before assignment
13.10.2015 22:58:36 ERROR     Traceback (most recent call last):
  File "/usr/bin/pyLoadCore", line 667, in <module>
    main()
  File "/usr/bin/pyLoadCore", line 658, in main
    pyload_core.start()
  File "/usr/bin/pyLoadCore", line 469, in start
    self.scheduler.work()
  File "/usr/share/pyload/module/Scheduler.py", line 85, in work
    j.start()
  File "/usr/share/pyload/module/Scheduler.py", line 111, in start
    self.run()
  File "/usr/share/pyload/module/Scheduler.py", line 101, in run
    ret = self.call(*self.args, **self.kwargs)
  File "/root/.pyload/userplugins/internal/Addon.py", line 118, in _periodical
    self.periodical()
  File "/root/.pyload/userplugins/hooks/SJ.py", line 144, in periodical
    self.range_checkr(link,title)
  File "/root/.pyload/userplugins/hooks/SJ.py", line 195, in range_checkr
    self.parse_download(link, title)
  File "/root/.pyload/userplugins/hooks/SJ.py", line 221, in parse_download
    self.send_package(title,items) if len(items) > 0 else True
  File "/root/.pyload/userplugins/hooks/SJ.py", line 228, in send_package
    if storage == 'downloaded':
UnboundLocalError: local variable 'storage' referenced before assignment
```

**Comment by GammaC0de** [comment]
Works fine for me, try refeshing [`Plugin.py`](https://github.com/pyload/pyload/raw/stable/module/plugins/internal/Plugin.py).

**Comment by GammaC0de** [comment]
Also, try deleting `files.db` (backup first!)

**Comment by Gutz-Pilz** [comment]
Gr8. that fixed it.
But i guess captch9kw and xfs need tweaking
```
13.10.2015 23:39:08 WARNING   Konnte Captcha9Kw nicht aktivieren
Traceback (most recent call last):
  File "/usr/share/pyload/module/HookManager.py", line 130, in createIndex
    plugin = pluginClass(self.core, self)
  File "/root/.pyload/userplugins/internal/Hook.py", line 23, in __init__
    self.init_periodical(10)
AttributeError: 'Captcha9Kw' object has no attribute 'init_periodical'
13.10.2015 23:39:08 DEBUG     Redirected import module.plugins.hooks.ClickNLoad -> userplugins.hooks.ClickNLoad
13.10.2015 23:39:08 DEBUG     Redirected import module.plugins.hooks.TraktFetcher -> userplugins.hooks.TraktFetcher
13.10.2015 23:39:09 DEBUG     Redirected import module.plugins.hooks.XFileSharingPro -> userplugins.hooks.XFileSharingPro
13.10.2015 23:39:09 WARNING   Konnte XFileSharingPro nicht aktivieren
Traceback (most recent call last):
  File "/usr/share/pyload/module/HookManager.py", line 130, in createIndex
    plugin = pluginClass(self.core, self)
  File "/root/.pyload/userplugins/internal/Hook.py", line 23, in __init__
    self.init_periodical(10)

```

**Comment by vuolter** [comment]
New version coming...

**Comment by GammaC0de** [comment]
they are no up to date also, many plugins have not increased their version number so `UpdateManager` didn`t update them.
refresh your userplugins from https://github.com/pyload/pyload/archive/stable.zip (all the subdirectories in \pyload-stable\module\plugins\ in the zip file)

**Comment by vuolter** [comment]
Mmmnnn... :S

**Comment by Gutz-Pilz** [comment]
can now be closed

**Comment by GammaC0de** [comment]
@Gutz-Pilz you can close your own issues..
