### ISSUE TITLE
AttributeError: '*****' object has no attribute 'rst_free'

### ISSUE THREAD

**Issue by joberreiter** [pyload/pyload#2034]
```
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/usr/share/pyload/module/plugins/internal/Base.py", line 218, in preprocessing
    return self._process(*args, **kwargs)
  File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 78, in _process
    self._setup()
  File "/usr/share/pyload/module/plugins/internal/SimpleCrypter.py", line 86, in _setup
    super(SimpleCrypter, self)._setup()
  File "/usr/share/pyload/module/plugins/internal/Base.py", line 162, in _setup
    self.load_account()  #@TODO: Move to PluginThread in 0.4.10
  File "/usr/share/pyload/module/plugins/internal/SimpleCrypter.py", line 94, in load_account
    super(SimpleCrypter, self).load_account()
  File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 64, in load_account
    if self.rst_free:
AttributeError: 'UploadedToFolder' object has no attribute 'rst_free'
```

Seems due to the fact, that in `internal/Base.py`, a call to `load_account()` is executed before `init_base()` or `setup_base()`, in where the variable `rst_free` is being defined.

And what drives one to name a variable `rst_free` when it could also be named `restart_free`, which would make the code be better readable ...?

**Comment by vuolter** [comment]
Nothing should be executed before `__init__` (and its `init_base`). Checking...

**Comment by joberreiter** [comment]
You are right, this seems not the reason for the error message. Hm.

**Comment by vuolter** [comment]
@joberreiter News?

**Comment by joberreiter** [comment]
Yes, same download link, new error
```
23.10.2015 17:38:03 INFO      Added package Stray Cats containing 1 links
23.10.2015 17:38:03 DEBUG     Run Info Fetching for XFileSharingFolder
23.10.2015 17:38:03 DEBUG     Finished Info Fetching for XFileSharingFolder
23.10.2015 17:38:05 INFO      Decrypting starts: http://uploaded.net/folder/kidxbr
23.10.2015 17:38:05 DEBUG     CRYPTER XFileSharingFolder[13712]: UploadedNet | Plugin version: 0.20
23.10.2015 17:38:05 DEBUG     CRYPTER XFileSharingFolder[13712]: UploadedNet | Plugin status: testing
23.10.2015 17:38:05 WARNING   CRYPTER XFileSharingFolder[13712]: UploadedNet | Plugin may be unstable
23.10.2015 17:38:05 DEBUG     CRYPTER XFileSharingFolder[13712]: UploadedNet | Config option `use_premium` not found, use default `True`
23.10.2015 17:38:05 ERROR     Decrypting failed: http://uploaded.net/folder/kidxbr | can only assign string to XFileSharingFolder.__name__, not 'unicode'
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/var/local/pyload/userplugins/internal/Base.py", line 281, in preprocessing
    return self._process(*args, **kwargs)
  File "/var/local/pyload/userplugins/internal/Base.py", line 267, in _process
    self._setup()
  File "/var/local/pyload/userplugins/internal/Base.py", line 145, in _setup
    self.load_account()  #@TODO: Move to PluginThread in 0.4.10
  File "/var/local/pyload/userplugins/crypter/XFileSharingFolder.py", line 51, in load_account
    self.__class__.__name__ = self.PLUGIN_NAME
TypeError: can only assign string to XFileSharingFolder.__name__, not 'unicode'
```
