### ISSUE TITLE
uploaded.to 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#2056]
```
19.10.2015 08:41:05 INFO      Download starts: http://uploaded.net/file/6zgpeaoc
19.10.2015 08:41:05 DEBUG     HOSTER UploadedTo[363]: Plugin version: 0.98
19.10.2015 08:41:05 DEBUG     HOSTER UploadedTo[363]: Plugin status: testing
19.10.2015 08:41:05 WARNING   HOSTER UploadedTo[363]: Plugin may be unstable
19.10.2015 08:41:05 INFO      ACCOUNT UploadedTo: Grabbing account info for user `13345744`...
19.10.2015 08:41:05 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
19.10.2015 08:41:05 DEBUG     ACCOUNT UploadedTo: Size: 505,00 | Unit: gb
19.10.2015 08:41:05 DEBUG     ACCOUNT UploadedTo: Account info for user `13345744`: {'login': {'timestamp': 1445236574.981243, 'password': 'pe78v82x', 'valid': True}, 'data': {'premium': True, 'plugin': <Account UploadedTo>, 'trafficleft': 529530880L, 'maxtraffic': None, 'validuntil': 1457167265.656952, 'login': '13345744', 'type': 'UploadedTo', 'options': {'limitdl': ['0']}}}
19.10.2015 08:41:05 INFO      HOSTER UploadedTo[363]: Grabbing link info...
19.10.2015 08:41:06 WARNING   Download failed: http://uploaded.net/file/6zgpeaoc | 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/root/.pyload/userplugins/internal/Base.py", line 288, in preprocessing
    return self._process(*args, **kwargs)
  File "/root/.pyload/userplugins/internal/Hoster.py", line 83, in _process
    self._setup()
  File "/root/.pyload/userplugins/internal/Base.py", line 169, in _setup
    self.grab_info()
  File "/root/.pyload/userplugins/internal/Base.py", line 231, in grab_info
    new_info = self.get_info(self.pyfile.url, self.html)
  File "/root/.pyload/userplugins/internal/SimpleHoster.py", line 194, in get_info
    info['size'] = parse_size(info['size'], unit)
  File "/root/.pyload/userplugins/internal/utils.py", line 87, in parse_size
    unit    = (unit.strip().lower() or m.group(2) or "byte")[0]
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by Gutz-Pilz** [comment]
Dat removinc lower and strip fixed it for me

**Comment by bollstedt** [comment]
so how exactly can I fix it?

**Comment by Leonderi** [comment]
i think you have to change this:

https://github.com/Gutz-Pilz/pyload/commit/964ee6242492b712d32b231bf25a38883009e04a


I have the same Problem with ShareOnline and it looks like, that this didn't work for me.

**Comment by Gutz-Pilz** [comment]
Did u make the changes and restarted pyload?

**Comment by Leonderi** [comment]
now it works. maybe i had some outdated files..

thanks for your help.
