### ISSUE TITLE
ExtractArchive not working 

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#2081]
I get this error and extractarchive is not working at all. 
<pre><code>
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/opt/pyload/module/PluginThread.py", line 459, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/pyload/.pyload/userplugins/hooks/ExtractArchive.py", line 185, in extract_queued
    if self.extract(packages, thread):  #@NOTE: check only if all gone fine, no failed reporting for now
  File "/opt/pyload/.pyload/userplugins/hooks/ExtractArchive.py", line 292, in extract
    targets = Extractor.get_targets(files_ids)
  File "/opt/pyload/.pyload/userplugins/internal/Extractor.py", line 79, in get_targets
    pname = re.sub(cls.re_multipart, "", fname) if cls.ismultipart(fname) else os.path.splitext(fname)[0]
AttributeError: type object 'UnRar' has no attribute 'ismultipart'
</Code></pre>

**Comment by GammaC0de** [comment]
Probably result of #2079.
Manual update your `UnRar.py` or even better, refresh all your `userplugins`

**Comment by vuolter** [comment]
Fixed.
