### ISSUE TITLE
Dereferer can't set attribute 

### ISSUE THREAD

**Issue by Bambie42** [pyload/pyload#2094]
This happens for example with all https://www.smoozed.rocks/redirect/?link=http://ul.to/somefileid links 

```
pyLoad 0.4.9 Debug Report of Dereferer 0.20

TRACEBACK:
 Traceback (most recent call last):
  File "/home/download/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/home/download/pyload/module/plugins/internal/Base.py", line 280, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/download/pyload/module/plugins/internal/Base.py", line 266, in _process
    self._setup()
  File "/home/download/pyload/module/plugins/internal/SimpleCrypter.py", line 134, in _setup
    self.classname = orig_name.rstrip("Folder")
AttributeError: can't set attribute
```

**Comment by GammaC0de** [comment]
fix would require adding a method to `Plugin.py` but I don't know if @vuolter desires that.
```python
    @classname.setter
    def classname(self, value):
        self.__class__.__name__ = value

```
