### ISSUE TITLE
SmoozedRocks | 'Dereferer' object has no attribute 'links'

### ISSUE THREAD

**Issue by Arno-Nymous** [pyload/pyload#2151]
Something seems still to go wrong with the dereferrer plugin as it cannot find the links attribute.
In my case this happens with links from share-links.biz.

DEBUG LOG (Most recent last)
```
04.11.2015 02:43:15 INFO    Decrypting starts: https://www.smoozed.rocks/redirect/?link=http://www.share-online.biz/dl/xxxxxxxxxxx
04.11.2015 02:43:15 DEBUG   CRYPTER Dereferer[337]: SmoozedRocks | Plugin version: 0.24
04.11.2015 02:43:15 DEBUG   CRYPTER Dereferer[337]: SmoozedRocks | Plugin status: testing
04.11.2015 02:43:15 WARNING CRYPTER Dereferer[337]: SmoozedRocks | Plugin may be unstable
04.11.2015 02:43:15 DEBUG   CRYPTER Dereferer[337]: SmoozedRocks | Config option `use_premium` not found, use default `True`
04.11.2015 02:43:15 INFO    CRYPTER Dereferer[337]: SmoozedRocks | Grabbing link info...
04.11.2015 02:43:15 DEBUG   CRYPTER Dereferer[337]: SmoozedRocks | Link info: {'status': 3, 'pattern': {'DOMAIN': u'smoozed.rocks', 'LINK': u'http://www.share-online.biz/dl/xxxxxxxxxxx'}, 'size': 0, 'url': u'https://www.smoozed.rocks/redirect/?link=http://www.share-online.biz/dl/xxxxxxxxxxx', 'name': 'xxxxxxxxxxx'}
04.11.2015 02:43:15 DEBUG   CRYPTER Dereferer[337]: SmoozedRocks | Previous link info: {}
04.11.2015 02:43:15 INFO    CRYPTER Dereferer[337]: SmoozedRocks | Link name: xxxxxxxxxxx
04.11.2015 02:43:15 INFO    CRYPTER Dereferer[337]: SmoozedRocks | Link size: N/D
04.11.2015 02:43:15 INFO    CRYPTER Dereferer[337]: SmoozedRocks | Link status: eingereiht
04.11.2015 02:43:15 INFO    CRYPTER Dereferer[337]: SmoozedRocks | Processing url: https://www.smoozed.rocks/redirect/?link=http://www.share-online.biz/dl/xxxxxxxxxxx
04.11.2015 02:43:15 ERROR   Decrypting failed: xxxxxxxxxxx | 'Dereferer' object has no attribute 'links'
04.11.2015 02:43:15 INFO    Debug Report written to debug_Dereferer_04-11-2015_02-43-15.zip
```

pyLoad 0.4.9 Debug Report of Dereferer 0.24 

TRACEBACK:
```
 Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 367, in run
    self.active.plugin.preprocessing(self)
  File "/home/shared/.pyload/userplugins/internal/Base.py", line 280, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/shared/.pyload/userplugins/internal/Base.py", line 274, in _process
    self.process(self.pyfile)
  File "/home/shared/.pyload/userplugins/internal/Crypter.py", line 38, in process
    self.decrypt(pyfile)
  File "/home/shared/.pyload/userplugins/internal/SimpleCrypter.py", line 219, in decrypt
    if not self.links and not self.packages:
AttributeError: 'Dereferer' object has no attribute 'links'
```

FRAMESTACK:
```
Frame preprocessing in /home/shared/.pyload/userplugins/internal/Base.py at line 280
	                self = <Crypter Dereferer>
	                args = (<DecrypterThread(Thread-25, started daemon -1383074704)>,)
	              kwargs = {}

Frame _process in /home/shared/.pyload/userplugins/internal/Base.py at line 274
	                self = <Crypter Dereferer>
	              thread = <DecrypterThread(Thread-25, started daemon -1383074704)>

Frame process in /home/shared/.pyload/userplugins/internal/Crypter.py at line 38
	              pyfile = PyFile 337: XXXXXXXXXX@Dereferer
	                self = <Crypter Dereferer>

Frame decrypt in /home/shared/.pyload/userplugins/internal/SimpleCrypter.py at line 219
	              pyfile = PyFile 337: XXXXXXXXXX@Dereferer
	                self = <Crypter Dereferer>
```

PLUGIN OBJECT DUMP: 
```
	             COOKIES = True
	         DIRECT_LINK = False
	       ERROR_PATTERN = None
	  IP_BLOCKED_PATTERN = None
	   LINK_FREE_PATTERN = None
	        LINK_PATTERN = None
	LINK_PREMIUM_PATTERN = None
	       LOGIN_ACCOUNT = False
	       LOGIN_PREMIUM = False
	        NAME_PATTERN = None
	   NAME_REPLACEMENTS = []
	     OFFLINE_PATTERN = None
	       PAGES_PATTERN = None
	       PLUGIN_DOMAIN = u'smoozed.rocks'
	         PLUGIN_NAME = u'SmoozedRocks'
	PREMIUM_ONLY_PATTERN = None
	  SIZE_LIMIT_PATTERN = None
	TEMP_OFFLINE_PATTERN = None
	       TEXT_ENCODING = True
	    URL_REPLACEMENTS = []
	        WAIT_PATTERN = None
	             account = False
	             captcha = <Captcha Captcha>
	           classname = 'Dereferer'
	                data = ''
	           direct_dl = False
	                info = {'name': 'XXXXXXXXXX',
 'pattern': {'DOMAIN': u'smoozed.rocks',
             'LINK': u'http://www.share-online.biz/dl/XXXXXXXXXX'},
 'size': 0,
 'status': 3,
 'url': u'https://www.smoozed.rocks/redirect/?link=http://www.share-online.biz/dl/XXXXXXXXXX'}
	                  js = <module.common.JsEngine.JsEngine instance at 0xe47ee0>
	           last_html = None
	             multiDL = True
	            packages = []
	             premium = False
	              pyfile = PyFile 337: XXXXXXXXXX@Dereferer
	              pyload = <__main__.Core object at 0xb6341850>
	                 req = <module.network.Browser.Browser object at 0xad9ae340>
	             retries = {}
	              thread = <DecrypterThread(Thread-25, started daemon -1383074704)>
	                urls = []
	                user = None
	             waiting = False
	       wantReconnect = False
```

PYFILE OBJECT DUMP: 
```
	               _size = 0
	               abort = False
	              active = False
	               error = "'Dereferer' object has no attribute 'links'"
	                  id = 337
	                lock = <_RLock owner=None count=0>
	                   m = <module.database.FileDatabase.FileHandler instance at 0xb6351ee0>
	         maxprogress = 100
	                name = 'XXXXXXXXXX'
	               order = 4
	           packageid = 54
	              plugin = <Crypter Dereferer>
	         pluginclass = <class 'userplugins.crypter.Dereferer.Dereferer'>
	        pluginmodule = <module 'userplugins.crypter.Dereferer' from '/home/shared/.pyload/userplugins/crypter/Dereferer.pyc'>
	          pluginname = u'Dereferer'
	            progress = 0
	         reconnected = False
	                size = 0
	              status = 8
	          statusname = None
	                 url = u'https://www.smoozed.rocks/redirect/?link=http://www.share-online.biz/dl/XXXXXXXXXX'
	           waitUntil = 0
```

CONFIG: 
```
{'activated': {'desc': 'Activated', 'type': 'bool', 'value': True},
 'desc': 'Dereferer',
 'outline': 'Universal link dereferer',
 'subfolder_per_pack': {'desc': 'Create a subfolder for each package',
                        'type': 'bool',
                        'value': True},
 'use_subfolder': {'desc': 'Save package to subfolder',
                   'type': 'bool',
                   'value': True}}
```

**Comment by Arno-Nymous** [comment]
Again, another versioning issue -_-
Obviously recently in some files code was changed from `self.links` to `self.urls`. Unfortunatelly the version of [Crypter.py](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/Crypter.py) was not incremented to 0.15, so I (and assumingly lots of others too) did not get the update. So, if anyone but me  has this problem, just copy the latest version of [Crypter.py](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/Crypter.py) to your PyLoad installation and you should be fine.
