### ISSUE TITLE
Download failed | too many values to unpack

### ISSUE THREAD

**Issue by Arno-Nymous** [pyload/pyload#2161]
Recently I get this ugly error here with the following log output...
Unfortunatelly, PyLoad denotes it only as a warning whereas it actually should be an error since the message `Too many values to unpack` is a generic python error message and throws an exception.

What bugs me furthermore is this annoying `No info available` associated with my Share-online.biz account. It seems that something goes wrong in the signin process of the ShareonlineBiz plugin.
Maybe someone can tell me, what the `api['a']` stands for or contains in the api_response here https://github.com/pyload/pyload/blob/stable/module/plugins/accounts/ShareonlineBiz.py#L35

I could not find any applicable information on the Share-online API regarding this parameter.

DEBUG LOG:
```
11.11.2015 19:41:04 INFO      Download starts: PE20G70Bx6iTRA.part14.rar
11.11.2015 19:41:04 DEBUG     HOSTER ShareonlineBiz[345]: Plugin version: 0.63
11.11.2015 19:41:04 DEBUG     HOSTER ShareonlineBiz[345]: Plugin status: testing
11.11.2015 19:41:04 WARNING   HOSTER ShareonlineBiz[345]: Plugin may be unstable
11.11.2015 19:41:04 DEBUG     ACCOUNT ShareonlineBiz: Reached login timeout for user `***********`
11.11.2015 19:41:04 INFO      ACCOUNT ShareonlineBiz: Relogin user `***********`...
11.11.2015 19:41:04 DEBUG     ACCOUNT ShareonlineBiz: LOAD URL https://api.share-online.biz/cgi-bin | redirect=True | cookies=True | get={'q': 'userdetails', 'aux': 'traffic', 'username': '************', 'password': '**********'} | req=None | decode=False | multipart=False | post={} | ref=True | just_header=False
11.11.2015 19:41:05 DEBUG     ACCOUNT ShareonlineBiz:
                                  user=***********
                                  email=***********
                                  group=Sammler
                                  register_date=1418174056
                                  expire_date=-1
                                  points=11000
                                  money=11.00
                                  a=not_available
                                  traffic_1d=0;0.000
                                  traffic_7d=0;0.000
11.11.2015 19:41:05 ERROR     ACCOUNT ShareonlineBiz: Could not login user `***********` | No info available
11.11.2015 19:41:05 WARNING   Download failed: PE20G70Bx6iTRA.part14.rar | too many values to unpack
11.11.2015 19:41:05 INFO      Debug Report written to debug_ShareonlineBiz_11-11-2015_19-41-05.zip
11.11.2015 19:41:05 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: PE20G70Bx6iTRA.part14.rar (pid:53)
11.11.2015 19:41:05 INFO      ADDON UnSkipOnFail: No duplicates found
```

pyLoad 0.4.9 Debug Report of ShareonlineBiz 0.63 

TRACEBACK:
```
 Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/shared/.pyload/userplugins/internal/Base.py", line 280, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/shared/.pyload/userplugins/internal/Hoster.py", line 85, in _process
    self._setup()
  File "/home/shared/.pyload/userplugins/internal/Base.py", line 144, in _setup
    self.load_account()  #@TODO: Move to PluginThread in 0.4.10
  File "/home/shared/.pyload/userplugins/internal/Hoster.py", line 70, in load_account
    super(Hoster, self).load_account()
  File "/home/shared/.pyload/userplugins/internal/Base.py", line 175, in load_account
    self.account.choose()
  File "/home/shared/.pyload/userplugins/internal/utils.py", line 49, in new
    return fn(*args)
  File "/home/shared/.pyload/userplugins/internal/Account.py", line 435, in choose
    user = self.select()[0]
  File "/home/shared/.pyload/userplugins/internal/utils.py", line 49, in new
    return fn(*args)
  File "/home/shared/.pyload/userplugins/internal/Account.py", line 382, in select
    info = self.accounts[user]['plugin'].get_info()
  File "/home/shared/.pyload/userplugins/internal/Account.py", line 239, in get_info
    self.reset()
  File "/home/shared/.pyload/userplugins/internal/Account.py", line 219, in reset
    self.info['data'] = dict((k, clear(v)) for k, v in self.info['data'])
  File "/home/shared/.pyload/userplugins/internal/Account.py", line 219, in <genexpr>
    self.info['data'] = dict((k, clear(v)) for k, v in self.info['data'])
ValueError: too many values to unpack
```
 
FRAMESTACK:
```
Frame preprocessing in /home/shared/.pyload/userplugins/internal/Base.py at line 280
                  self = <Hoster ShareonlineBiz>
                  args = (<DownloadThread(Thread-2, started daemon -1251486608)>,)
                kwargs = {}

Frame _process in /home/shared/.pyload/userplugins/internal/Hoster.py at line 85
                  self = <Hoster ShareonlineBiz>
                thread = <DownloadThread(Thread-2, started daemon -1251486608)>

Frame _setup in /home/shared/.pyload/userplugins/internal/Base.py at line 144
                  self = <Hoster ShareonlineBiz>

Frame load_account in /home/shared/.pyload/userplugins/internal/Hoster.py at line 70
                  self = <Hoster ShareonlineBiz>

Frame load_account in /home/shared/.pyload/userplugins/internal/Base.py at line 175
                  self = <Hoster ShareonlineBiz>

Frame new in /home/shared/.pyload/userplugins/internal/utils.py at line 52
                  args = (<Account ShareonlineBiz>,)
                    fn = <function choose at 0x1acabb0>

Frame choose in /home/shared/.pyload/userplugins/internal/Account.py at line 435
                  self = <Account ShareonlineBiz>
                  user = None

Frame new in /home/shared/.pyload/userplugins/internal/utils.py at line 52
                  args = (<Account ShareonlineBiz>,)
                    fn = <function select at 0x1acaa30>

Frame select in /home/shared/.pyload/userplugins/internal/Account.py at line 382
         free_accounts = {}
                  self = <Account ShareonlineBiz>
                  user = '***********'
      premium_accounts = {}

Frame get_info in /home/shared/.pyload/userplugins/internal/Account.py at line 239
                  self = <Account ShareonlineBiz>
               refresh = False

Frame reset in /home/shared/.pyload/userplugins/internal/Account.py at line 219
                 clear = <function <lambda> at 0xa88b9db0>
                    pp = <pprint.PrettyPrinter instance at 0x2287af8>
                  self = <Account ShareonlineBiz>

Frame <genexpr> in /home/shared/.pyload/userplugins/internal/Account.py at line 219
                    .0 = <dictionary-keyiterator object at 0x24d98d0>
                 clear = <function <lambda> at 0xa88b9db0>
```

PLUGIN OBJECT DUMP: 
```
            CHECK_FILE = True
         CHECK_TRAFFIC = True
               COOKIES = True
           DIRECT_LINK = True
           DISPOSITION = True
      DL_LIMIT_PATTERN = None
         ERROR_PATTERN = '<p class="b">Information:</p>\\s*<div>\\s*<strong>(.*?)</strong>'
           FILE_ERRORS = [('Html error',
  '\\A(?:\\s*<.+>)?((?:[\\w\\s]*(?:[Ee]rror|ERROR)\\s*\\:?)?\\s*\\d{3})(?:\\Z|\\s+)'),
 ('Request error', '([Aa]n error occured while processing your request)'),
 ('Html file', '\\A\\s*<!DOCTYPE html')]
    HAPPY_HOUR_PATTERN = None
       HASHSUM_PATTERN = None
          INFO_PATTERN = None
    IP_BLOCKED_PATTERN = None
          LEECH_HOSTER = False
     LINK_FREE_PATTERN = None
          LINK_PATTERN = None
  LINK_PREMIUM_PATTERN = None
         LOGIN_ACCOUNT = False
         LOGIN_PREMIUM = False
          NAME_PATTERN = None
     NAME_REPLACEMENTS = []
       OFFLINE_PATTERN = None
  PREMIUM_ONLY_PATTERN = None
         RECAPTCHA_KEY = '6LdatrsSAAAAAHZrB70txiV5p-8Iv8BtVxlTtjKX'
    SIZE_LIMIT_PATTERN = None
          SIZE_PATTERN = None
     SIZE_REPLACEMENTS = []
  TEMP_OFFLINE_PATTERN = None
         TEXT_ENCODING = True
      URL_REPLACEMENTS = [('https?://(?:www\\.)?(share-online\\.biz|egoshare\\.com)/(download\\.php\\?id=|dl/)(?P<ID>\\w+).*',
  'http://www.share-online.biz/dl/\\g<ID>')]
          WAIT_PATTERN = None
               account = <Account ShareonlineBiz>
               captcha = <Captcha Captcha>
           chunk_limit = None
             classname = 'ShareonlineBiz'
                  data = ''
                  info = {}
                    js = <module.common.JsEngine.JsEngine instance at 0x182cf08>
            last_check = None
         last_download = None
             last_html = None
               limitDL = 0
               multiDL = True
               premium = None
                pyfile = PyFile 345: PE20G70Bx6iTRA.part14.rar@ShareonlineBiz
                pyload = <__main__.Core object at 0xb6254830>
                   req = None
          restart_free = False
       resume_download = False
               retries = {}
                thread = <DownloadThread(Thread-2, started daemon -1251486608)>
                  user = None
               waiting = False
         wantReconnect = False
```
PYFILE OBJECT DUMP: 
```
                 _size = 0
                 abort = False
                active = False
                 error = 'too many values to unpack'
                    id = 345
                  lock = <_RLock owner=None count=0>
                     m = <module.database.FileDatabase.FileHandler instance at 0xb6264ee0>
           maxprogress = 100
                  name = u'PE20G70Bx6iTRA.part14.rar'
                 order = 13
             packageid = 53
                plugin = <Hoster ShareonlineBiz>
           pluginclass = <class 'userplugins.hoster.ShareonlineBiz.ShareonlineBiz'>
          pluginmodule = <module 'userplugins.hoster.ShareonlineBiz' from '/home/shared/.pyload/userplugins/hoster/ShareonlineBiz.pyc'>
            pluginname = u'ShareonlineBiz'
              progress = 0
           reconnected = False
                  size = 0
                status = 8
            statusname = None
                   url = u'http://www.share-online.biz/dl/D377TKXNMDQ'
             waitUntil = 0
```

CONFIG: 
```
{'activated': {'desc': 'Activated', 'type': 'bool', 'value': True},
 'desc': 'ShareonlineBiz',
 'outline': 'Shareonline.biz hoster plugin',
 'use_premium': {'desc': 'Use premium account if available',
                 'type': 'bool',
                 'value': True}}
```

**Comment by Arno-Nymous** [comment]
Think I found some quick fix for this issue. Since [this is the problematic code line](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/Account.py#L212) I applied a recommendation from stackoverflow which worked for me so far.
I changed the line from ```self.info['data'] = dict((k, clear(v)) for k, v in self.info['data'])``` to ```self.info['data'] = dict((k, clear(v)) for k, v in self.info['data'].iteritems())```. I hope this change solves the problem in general.
Try it and report back if it worked for you too.

Here's the answer from stackoverflow for the archives :)

You are looping over a dictionary:
```
for key, role in relatives:
```
but that only yields *keys*, so one single object at a time. If you want to loop over keys and values, use the `dict.items()` method:
```
for key, role in relatives.items():
```
On Python 2, use the dict.iteritems() method for efficiency:
```
for key, role in relatives.iteritems():
```

**Comment by Arno-Nymous** [comment]
Sorry, clicked the wrong button...

**Comment by ace02000** [comment]
same error :/

**Comment by GammaC0de** [comment]
Closing.
