### ISSUE TITLE
C'n'L Connection refused

### ISSUE THREAD

**Issue by gr0ebi** [pyload/pyload#2198]
I'm using pyload 0.4.9, threaded webserver and disabled HTTPS on Debian 7, Kernel 3.2.0 and Python 2.7.3.
My ClickNLoad is configured as followed:
Add packages to: Collector
Activated:	yes
Listen for external connections: yes
Port:	9667

Every time I try to C'n'L I get the same Error:
```python
18.12.2015 15:54:15 INFO      ADDON UpdateManager: All plugins are up to date!
18.12.2015 15:54:19 INFO      ADDON RestartFailed: Restarting all failed downloads...
18.12.2015 15:54:19 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9667
18.12.2015 15:54:34 DEBUG     ADDON ClickNLoad: Connection from 10.0.0.107:48349
18.12.2015 15:54:34 ERROR     ADDON ClickNLoad: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 525, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/opt/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/pyload/module/plugins/hooks/ClickNLoad.py", line 106, in _server
    server_socket.connect(("127.0.0.1", webport))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
```

I tried to open it locally (I started remotely from Windows 7 with port redirection) on the server but I get the same error. 
Here is my netstat:

```bash
root@xyz:~# netstat -tulpn | grep python
tcp        0      0 0.0.0.0:9667            0.0.0.0:*               LISTEN      6932/python
tcp        0      0 10.0.0.252:8901         0.0.0.0:*               LISTEN      6932/python
root@xyz:~# netstat -tulpn | grep 8901
tcp        0      0 10.0.0.252:8901         0.0.0.0:*               LISTEN      6932/python
root@xyz:~# netstat -tulpn | grep 9667
tcp        0      0 0.0.0.0:9667            0.0.0.0:*               LISTEN      6932/python
```
Maybe someone can help me, thanks in advance

**Comment by GammaC0de** [comment]
I don't see port 8000 (webport) on the list...

**Comment by gr0ebi** [comment]
> I don't see port 8000 (webport) on the list...

Are you asking for the port of the webinterface? its changed to 8901 - if not, where can I set the webport?

**Comment by GammaC0de** [comment]
>Are you asking for the port of the webinterface? its changed to 8901 - if not, where can I set the webport?

Yes, the port of the webinterface.

Can you tell me what you have configured in:
1) "Donwload" - `Download interface to bind (ip or Name)`
2) "Webinterface" - `IP`

**Comment by gr0ebi** [comment]
thx for your quick reply


> 1) "Donwload" - Download interface to bind (ip or Name)

"None" - that might be the problem


> 2) "Webinterface" - IP

10.0.0.252

**Comment by GammaC0de** [comment]
Try this patch, see it it helps:
```patch
--- module/plugins/hooks/ClickNLoad.py	(date 1449411681000)
+++ module/plugins/hooks/ClickNLoad.py	(revision )
@@ -45,11 +45,12 @@
         if not self.pyload.config.get("webinterface", "activated"):
             return
 
-        ip      = "" if self.get_config('extern') else "127.0.0.1"
-        webport = self.pyload.config.get("webinterface", "port")
+        cnlip   = "" if self.get_config('extern') else "127.0.0.1"
         cnlport = self.get_config('port')
+        webip   = self.pyload.config.get("webinterface", "host") or "127.0.0.1"
+        webport = self.pyload.config.get("webinterface", "port")
 
-        self.pyload.scheduler.addJob(5, self.proxy, [ip, webport, cnlport], threaded=False)
+        self.pyload.scheduler.addJob(5, self.proxy, [cnlip, cnlport, webip, webport], threaded=False)
 
 
     @threaded
@@ -66,10 +67,10 @@
 
 
     @threaded
-    def proxy(self, ip, webport, cnlport):
-        self.log_info(_("Proxy listening on %s:%s") % (ip or "0.0.0.0", cnlport))
+    def proxy(self, cnlip, cnlport, webip, webport):
+        self.log_info(_("Proxy listening on %s:%s") % (cnlip or "0.0.0.0", cnlport))
 
-        self._server(ip, webport, cnlport)
+        self._server(cnlip, cnlport, webip, webport)
 
         lock = threading.Lock()
         lock.acquire()
@@ -77,10 +78,10 @@
 
 
     @threaded
-    def _server(self, ip, webport, cnlport):
+    def _server(self, cnlip, cnlport, webip, webport):
         try:
             dock_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
-            dock_socket.bind((ip, cnlport))
+            dock_socket.bind((cnlip, cnlport))
             dock_socket.listen(5)
 
             while True:
@@ -103,16 +104,16 @@
                         client_socket.close()
                         continue
 
-                server_socket.connect(("127.0.0.1", webport))
+                server_socket.connect((webip, webport))
 
                 self.forward(client_socket, server_socket, self.get_config('dest') is "queue")
                 self.forward(server_socket, client_socket)
 
         except socket.timeout:
             self.log_debug("Connection timed out, retrying...")
-            return self._server(ip, webport, cnlport)
+            return self._server(cnlip, cnlport, webip, webport)
 
         except socket.error, e:
             self.log_error(e)
             time.sleep(240)
-            return self._server(ip, webport, cnlport)
+            return self._server(cnlip, cnlport, webip, webport)
```

**Comment by gr0ebi** [comment]
Works like a charm! Can't believe it was fixed in 9 hours, thanks a lot!

**Comment by GammaC0de** [comment]
:+1:
