### ISSUE TITLE
Shareonline.biz and Uploaded  Tracebacks

### ISSUE THREAD

**Issue by Gronkdalonka** [pyload/pyload#2238]
After updating i always get following traceback trying to download files with Shareonline

TRACEBACK:
 Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/usr/share/pyload/module/plugins/internal/Base.py", line 286, in preprocessing
    return self._process(*args, **kwargs)
  File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 100, in _process
    self.process(self.pyfile)
  File "/usr/share/pyload/module/plugins/internal/SimpleHoster.py", line 284, in process
    self.download(self.link, disposition=self.DISPOSITION)
  File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 224, in download
    self.captcha.correct()
TypeError: correct() takes at least 2 arguments (1 given)

i commented out said line for a test, and afterwards i get following traceback:

(This is also the traceback i get when trying to download from uploaded.to)

TRACEBACK:
 Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/usr/share/pyload/module/plugins/internal/Base.py", line 286, in preprocessing
    return self._process(*args, **kwargs)
  File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 100, in _process
    self.process(self.pyfile)
  File "/usr/share/pyload/module/plugins/internal/SimpleHoster.py", line 284, in process
    self.download(self.link, disposition=self.DISPOSITION)
  File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 262, in download
    disposition=disposition)
  File "/usr/share/pyload/module/network/Browser.py", line 88, in httpDownload
    name = self.dl.download(chunks, resume)
  File "/usr/share/pyload/module/network/HTTPDownload.py", line 129, in download
    self._download(chunks, resume)
  File "/usr/share/pyload/module/network/HTTPDownload.py", line 160, in _download
    self.m.add_handle(init.getHandle())
  File "/usr/share/pyload/module/network/HTTPChunk.py", line 201, in getHandle
    self.fp = open(fs_name, "wb")
IOError: [Errno 2] No such file or directory: '/usr/share/.pyload/usr/share/.pyload/mnt/Daten/Download/<Folder>/<Filename>'
(i replaced folder and filename)

"/mnt/Daten/Download" is the folder i specified as download folder, and "/usr/share/.pyload" is my config dir

After creating subfolders and symlinking to the "original" folder downloads work fine

**Comment by vuolter** [comment]
Checking...

**Comment by Gronkdalonka** [comment]
#2239 and second issue seem to be the same
