### ISSUE TITLE
uploaded.to wont work

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#2256]
```
02.01.2016 16:47:36 INFO      ACCOUNT UploadedTo: Grabbing account info for user `13345xx4`...
02.01.2016 16:47:36 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
02.01.2016 16:47:36 DEBUG     ACCOUNT UploadedTo: Size: 495,87 | Unit: gb
02.01.2016 16:47:36 DEBUG     ACCOUNT UploadedTo: Account info for user `13345xx4`: {'login': {'timestamp': 1451749559.97731, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account UploadedTo>, 'trafficleft': 519957381L, 'maxtraffic': None, 'validuntil': 1457164056.662723, 'login': '13345744', 'type': 'UploadedTo', 'options': {'limitdl': ['0']}}}
02.01.2016 16:47:36 INFO      HOSTER UploadedTo[54]: Filesize: 76317 KiB | Traffic left for user `13345744`: 519957381 KiB
02.01.2016 16:47:36 INFO      HOSTER UploadedTo[54]: Processing as premium download...
02.01.2016 16:47:36 INFO      HOSTER UploadedTo[54]: Downloading file...
02.01.2016 16:47:36 DEBUG     HOSTER UploadedTo[54]: DOWNLOAD URL http://am4-r1f2-stor09.uploaded.net/dl/08954925-cee6-4858-91c7-2cc51a86995f | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
02.01.2016 16:47:36 DEBUG     Error removing chunk: curl object not on this multi-stack
02.01.2016 16:47:36 WARNING   Download failed: zzgtv-the.following-ded-7p-bd-x264-306.part10.rar | 2
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/root/.pyload/userplugins/internal/Base.py", line 286, in preprocessing
    return self._process(*args, **kwargs)
  File "/root/.pyload/userplugins/internal/Hoster.py", line 118, in _process
    self.process(self.pyfile)
  File "/root/.pyload/userplugins/internal/SimpleHoster.py", line 284, in process
    self.download(self.link, disposition=self.DISPOSITION)
  File "/root/.pyload/userplugins/internal/Hoster.py", line 280, in download
    disposition=disposition)
  File "/usr/share/pyload/module/network/Browser.py", line 88, in httpDownload
    name = self.dl.download(chunks, resume)
  File "/usr/share/pyload/module/network/HTTPDownload.py", line 129, in download
    self._download(chunks, resume)
  File "/usr/share/pyload/module/network/HTTPDownload.py", line 160, in _download
    self.m.add_handle(init.getHandle())
  File "/usr/share/pyload/module/network/HTTPChunk.py", line 201, in getHandle
    self.fp = open(fs_name, "wb")
IOError: [Errno 2] No such file or directory: '/root/.pyload/root/.pyload/Downloads/zzgtv-the.following-ded-7p-bd-x264-306/zzgtv-the.following-ded-7p-bd-x264-306.part10.rar.chunk0'
02.01.2016 16:47:36 INFO      Debug Report written to debug_UploadedTo_02-01-2016_16-47-36.zip
02.01.2016 16:47:36 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: zzgtv-the.following-ded-7p-bd-x264-306.part10.rar (pid:27)
02.01.2016 16:47:36 INFO      ADDON UnSkipOnFail: No duplicates found
02.01.2016 16:47:36 DEBUG     All downloads processed
```

**Comment by akquise** [comment]
See #2239.
