### ISSUE TITLE
[Plugin] exception when using captcha in debug mode

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#2260]
This happens because a bug in `Plugin.py` in function `dump_html` which is run only in debug mode:
`captcha` uses this line to load the image into memory:
```python
img = self.load(url, get=get, post=post, ref=ref, cookies=cookies, decode=decode, req=req or self.pyfile.plugin.req)
```

`self.load` calls `dump_html` when debug mode is active but now `last_html` variable is actually a binary image so `encode(self.last_html) ` generates the below exception.
That's why I made https://github.com/pyload/pyload/commit/718ff08e1b8fe0b2ccd5681a621d19ea2a979547
```
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 192, in run
    pyfile.plugin.preprocessing(self)
  File "/home/user/.pyload/userplugins/internal/Base.py", line 288, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/user/.pyload/userplugins/internal/Hoster.py", line 118, in _process
    self.process(self.pyfile)
  File "/home/user/.pyload/userplugins/internal/SimpleHoster.py", line 283, in process
    self.handle_free(pyfile)
  File "/home/user/.pyload/userplugins/hoster/NitroflareCom.py", line 61, in handle_free
    response, challenge = self.captcha.challenge(self.RECAPTCHA_KEY)
  File "/home/user/.pyload/userplugins/captcha/ReCaptcha.py", line 50, in challenge
    version=2 if re.search(self.KEY_V2_PATTERN, data or self.retrieve_data()) else 1)
  File "/home/user/.pyload/userplugins/captcha/ReCaptcha.py", line 46, in challenge
    return getattr(self, "_challenge_v%s" % version)(key)
  File "/home/user/.pyload/userplugins/captcha/ReCaptcha.py", line 65, in _challenge_v1
    return self.result(server, challenge, key)
  File "/home/user/.pyload/userplugins/captcha/ReCaptcha.py", line 86, in result
    input_type="jpg")
  File "/home/user/.pyload/userplugins/internal/Captcha.py", line 46, in decrypt
    img = self.load(url, get=get, post=post, ref=ref, cookies=cookies, decode=decode, req=req or self.pyfile.plugin.req)
  File "/home/user/.pyload/userplugins/internal/Plugin.py", line 225, in load
    self.dump_html()
  File "/home/user/.pyload/userplugins/internal/Plugin.py", line 250, in dump_html
    f.write(encode(self.last_html))
  File "/home/user/.pyload/userplugins/internal/misc.py", line 383, in encode
    res = transcode(value, decoding, encoding)
  File "/home/user/.pyload/userplugins/internal/misc.py", line 368, in transcode
    return value.decode(decoding).encode(encoding)
  File "/opt/lib/python2.5/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: unexpected code byte
```

**Comment by GammaC0de** [comment]
@vuolter Can you address this please?

**Comment by nordic-style** [comment]
Just tested the latest version.

Instead (yes it replaces the utf8 error) the utf8 error i now get these:

failed[Errno 2] No such file or directory: u'/data/media/Downloads/AshbyLame/ash.part005.rar.chunk0' 150.00 MiBUploadedTo

The error comes with a captcha request always.

Debug log

```
10.01.2016 19:43:02 WARNING   Download failed: lame-ash-rmx.part005.rar | [Errno 2] No such file or directory: u'/data/media/Downloads/AshbyLame/ash.part005.rar.chunk0'
Traceback (most recent call last):
  File "/data/media/bin/pyload/stable/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/data/media/bin/pyload/stable/module/plugins/internal/Base.py", line 290, in preprocessing
    return self._process(*args, **kwargs)
  File "/data/media/bin/pyload/stable/module/plugins/internal/Hoster.py", line 118, in _process
    self.process(self.pyfile)
  File "/data/media/bin/pyload/stable/module/plugins/internal/SimpleHoster.py", line 287, in process
    self.download(self.link, disposition=self.DISPOSITION)
  File "/data/media/bin/pyload/stable/module/plugins/internal/Hoster.py", line 302, in download
    disposition, resume, chunks)
  File "/data/media/bin/pyload/stable/module/plugins/internal/Hoster.py", line 233, in _download
    self.pyfile.setProgress, disposition)
  File "/data/media/bin/pyload/stable/module/network/Browser.py", line 88, in httpDownload
    name = self.dl.download(chunks, resume)
  File "/data/media/bin/pyload/stable/module/network/HTTPDownload.py", line 129, in download
    self._download(chunks, resume)
  File "/data/media/bin/pyload/stable/module/network/HTTPDownload.py", line 295, in _download
    self._copyChunks()
  File "/data/media/bin/pyload/stable/module/network/HTTPDownload.py", line 119, in _copyChunks
    move(init, fs_encode(self.filename))
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/data/media/Downloads/AshbyLame/ash.part005.rar.chunk0'
```

**Comment by GammaC0de** [comment]
Try the (partial) solution in https://github.com/pyload/pyload/issues/2265 an report again
