### ISSUE TITLE
Summarize utf8 error

### ISSUE THREAD

**Issue by nordic-style** [pyload/pyload#2281]
Since this is a relative new error and it would be great if this is fixed i will write a more detailed error description with some naive assumptions.

For me this only happens with links to uploaded.to. Shareonline.biz is fine and i don't see any errors of this kind with shareonline. I am using premium accounts with both of them.

What does happen:
I add a dlc to pyload and pyload starts downloading files. After some time i get the error:

failed'utf8' codec can't decode byte 0xff in position 0: invalid start byte 150.00 MiBUploadedTo

This only happens for some downloads and it actually does not download anything. In the case of this error i press the "restart link" button and i get this state:

queued'utf8' codec can't decode byte 0xff in position 0: invalid start byte 150.00 MiBUploadedTo

Within some secondons pyload starts downloading the file. The next state is: 

finished 150.00 MiBUploadedTo

And everything is fine.

This brings me to two options:
A) pyload has some kind of race condition that randomly creates this error

B) uploaded.to answers are broken and pyload cannot handle these answers.

In both cases a workaround would be possible: If this happens the first time for this link just restart the link. For the first option this would be a bad workaround - for the second option this would be a valid patch until uploaded fixes their software.

Debug log:

```
10.01.2016 17:26:32 WARNING   Download failed: Ob20GeDTDL10BlAVRePa37152.part138.rar | 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "/data/media/bin/pyload/stable/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/data/media/bin/pyload/stable/module/plugins/internal/Base.py", line 290, in preprocessing
    return self._process(*args, **kwargs)
  File "/data/media/bin/pyload/stable/module/plugins/internal/Hoster.py", line 118, in _process
    self.process(self.pyfile)
  File "/data/media/bin/pyload/stable/module/plugins/internal/SimpleHoster.py", line 283, in process
    self.handle_free(pyfile)
  File "/data/media/bin/pyload/stable/module/plugins/hoster/UploadedTo.py", line 79, in handle_free
    response, challenge = self.captcha.challenge()
  File "/data/media/bin/pyload/stable/module/plugins/captcha/ReCaptcha.py", line 50, in challenge
    version=2 if re.search(self.KEY_V2_PATTERN, data or self.retrieve_data()) else 1)
  File "/data/media/bin/pyload/stable/module/plugins/captcha/ReCaptcha.py", line 46, in challenge
    return getattr(self, "_challenge_v%s" % version)(key)
  File "/data/media/bin/pyload/stable/module/plugins/captcha/ReCaptcha.py", line 65, in _challenge_v1
    return self.result(server, challenge, key)
  File "/data/media/bin/pyload/stable/module/plugins/captcha/ReCaptcha.py", line 86, in result
    input_type="jpg")
  File "/data/media/bin/pyload/stable/module/plugins/internal/Captcha.py", line 46, in decrypt
    img = self.load(url, get=get, post=post, ref=ref, cookies=cookies, decode=False, req=req or self.pyfile.plugin.req)
  File "/data/media/bin/pyload/stable/module/plugins/internal/Plugin.py", line 221, in load
    self.dump_html()
  File "/data/media/bin/pyload/stable/module/plugins/internal/Plugin.py", line 246, in dump_html
    f.write(encode(self.last_html))
  File "/data/media/bin/pyload/stable/module/plugins/internal/misc.py", line 388, in encode
    res = transcode(value, decoding, encoding)
  File "/data/media/bin/pyload/stable/module/plugins/internal/misc.py", line 373, in transcode
    return value.decode(decoding).encode(encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by GammaC0de** [comment]
@nordic-style retry now
Your log describes the issue in #2260

**Comment by nordic-style** [comment]
Thank you. I will follow the discussion in #2260

**Comment by GammaC0de** [comment]
Try the (partial) solution in https://github.com/pyload/pyload/issues/2265 an report again

**Comment by nordic-style** [comment]
I will do that. Just as a side note: i do not use captchas in pyload. They should not appear since i use premium accounts with enough traffic.

**Comment by GammaC0de** [comment]
Fine, #2265 is not related to captchas

**Comment by nordic-style** [comment]
The error is gone but now i get this for some downloads:

```
10.01.2016 20:12:57 INFO      HOSTER UploadedTo[1879]: Filesize: 153600 KiB | Traffic left for user `xxxxxxx`: 360290713 KiB
10.01.2016 20:12:57 INFO      HOSTER UploadedTo[1879]: Processing as premium download...
10.01.2016 20:12:57 WARNING   HOSTER UploadedTo[1879]: Premium download failed | Parse error: Premium download link not found | Plugin may be out of date
10.01.2016 20:12:57 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
10.01.2016 20:12:57 INFO      Download restarted: lhd-rai2_uc-rmx.part009.rar | Fallback to free processing
10.01.2016 20:12:57 INFO      Download starts: lhd-rai2_uc-rmx.part009.rar
10.01.2016 20:12:57 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
```

**Comment by nordic-style** [comment]
It seems that after the captcha timeout pyload starts downloading the file, nevertheless. It just takes a lot more time.

**Comment by GammaC0de** [comment]
Had you activated direct download in your account?

**Comment by nordic-style** [comment]
No. That is a problem for "some" files? I am talking about 1 of 10. Just activated it and i am testing.

**Comment by GammaC0de** [comment]
It is much better and simpler to use premium direct download

**Comment by nordic-style** [comment]
Just activated it and even restarted pyload but it did not help. Still getting captchas (which i ignore).

**Comment by GammaC0de** [comment]
Debug log please

**Comment by nordic-style** [comment]
Ok - i hope everything is included:

```
10.01.2016 21:04:00 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
10.01.2016 21:04:00 INFO      Download finished: DeChStdeHe20GeDTDL10BlAVReBl46327.part025.rar
10.01.2016 21:04:00 DEBUG     ADDON ExternalScripts: No script found under folder `download_finished`
10.01.2016 21:04:02 INFO      Download starts: http://uploaded.net/file/z18qf9uk/DeChStdeHe20GeDTDL10BlAVReBl46327.part026.rar
10.01.2016 21:04:02 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
10.01.2016 21:04:02 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
10.01.2016 21:04:03 DEBUG     HOSTER UploadedTo[2130]: Plugin version: 1.01
10.01.2016 21:04:03 DEBUG     HOSTER UploadedTo[2130]: Plugin status: testing
10.01.2016 21:04:03 WARNING   HOSTER UploadedTo[2130]: Plugin may be unstable
10.01.2016 21:04:03 INFO      ACCOUNT UploadedTo: Grabbing account info for user `xxxxxxxx`...
10.01.2016 21:04:03 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
10.01.2016 21:04:03 DEBUG     ACCOUNT UploadedTo: Size: 306,84 | Unit: gb
10.01.2016 21:04:03 DEBUG     ACCOUNT UploadedTo: Account info for user `xxxxxxxx`: {'login': {'timestamp': 1452456000.83116, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account UploadedTo>, 'trafficleft': 321745059, 'maxtraffic': None, 'validuntil': 1513080243.736073, 'login': 'xxxxxxxx', 'type': 'UploadedTo', 'options': {'limitdl': ['0']}}}
10.01.2016 21:04:03 INFO      HOSTER UploadedTo[2130]: Grabbing link info...
10.01.2016 21:04:03 DEBUG     HOSTER UploadedTo[2130]: Link info: {'status': 2, 'hash': {}, 'name': 'DeChStdeHe20GeDTDL10BlAVReBl46327.part026.rar', 'url': u'http://uploaded.net/file/z18qf9uk', 'pattern': {'ID': u'z18qf9uk'}, 'size': 157286404}
10.01.2016 21:04:03 DEBUG     HOSTER UploadedTo[2130]: Previous link info: {}
10.01.2016 21:04:03 INFO      HOSTER UploadedTo[2130]: Link name: DeChStdeHe20GeDTDL10BlAVReBl46327.part026.rar
10.01.2016 21:04:03 INFO      HOSTER UploadedTo[2130]: Link size: 150.00 MiB (157286404 bytes)
10.01.2016 21:04:03 INFO      HOSTER UploadedTo[2130]: Link status: online
10.01.2016 21:04:03 INFO      HOSTER UploadedTo[2130]: Processing url: http://uploaded.net/file/z18qf9uk/DeChStdeHe20GeDTDL10BlAVReBl46327.part026.rar
10.01.2016 21:04:03 INFO      HOSTER UploadedTo[2130]: Looking for direct download link...
10.01.2016 21:04:03 DEBUG     HOSTER UploadedTo[2130]: LOAD URL http://uploaded.net/file/z18qf9uk | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
10.01.2016 21:04:03 WARNING   CAPTCHA UploadedTo[2114]: ReCaptcha | Invalid captcha
10.01.2016 21:04:03 DEBUG     HOSTER UploadedTo[2114]: WAIT set to timestamp 1452456245.914353 | Previous waitUntil: 0.000000
10.01.2016 21:04:03 DEBUG     HOSTER UploadedTo[2114]: RECONNECT not required | Previous wantReconnect: False
10.01.2016 21:04:03 INFO      HOSTER UploadedTo[2114]: Waiting 1 seconds...
10.01.2016 21:04:04 INFO      HOSTER UploadedTo[2130]: Direct download link detected
10.01.2016 21:04:04 INFO      HOSTER UploadedTo[2130]: Downloading file...
10.01.2016 21:04:04 DEBUG     HOSTER UploadedTo[2130]: DOWNLOAD URL http://fra-7m20-stor06.uploaded.net/dl/138e3049-7832-4d18-adcb-b189d680d381 | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
10.01.2016 21:04:04 DEBUG     Content-Disposition: DeChStdeHe20GeDTDL10BlAVReBl46327.part026.rar
10.01.2016 21:04:05 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
10.01.2016 21:04:05 INFO      Download restarted: DeChStdeHe20GeDTDL10BlAVReBl46327.part010.rar | No captcha result obtained in appropriate timing
10.01.2016 21:04:06 INFO      Download starts: DeChStdeHe20GeDTDL10BlAVReBl46327.part010.rar
10.01.2016 21:04:06 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
10.01.2016 21:04:06 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
10.01.2016 21:04:07 DEBUG     HOSTER UploadedTo[2114]: Plugin version: 1.01
10.01.2016 21:04:07 DEBUG     HOSTER UploadedTo[2114]: Plugin status: testing
10.01.2016 21:04:07 WARNING   HOSTER UploadedTo[2114]: Plugin may be unstable
10.01.2016 21:04:07 INFO      ACCOUNT UploadedTo: Grabbing account info for user `xxxxxxxx`...
10.01.2016 21:04:07 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
10.01.2016 21:04:07 DEBUG     ACCOUNT UploadedTo: Size: 306,84 | Unit: gb
10.01.2016 21:04:07 DEBUG     ACCOUNT UploadedTo: Account info for user `xxxxxxxx`: {'login': {'timestamp': 1452456000.83116, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account UploadedTo>, 'trafficleft': 321745059, 'maxtraffic': None, 'validuntil': 1513080247.124077, 'login': 'xxxxxxxx', 'type': 'UploadedTo', 'options': {'limitdl': ['0']}}}
10.01.2016 21:04:07 INFO      HOSTER UploadedTo[2114]: Grabbing link info...
10.01.2016 21:04:07 DEBUG     HOSTER UploadedTo[2114]: Link info: {'status': 2, 'hash': {}, 'name': 'DeChStdeHe20GeDTDL10BlAVReBl46327.part010.rar', 'url': u'http://uploaded.net/file/b0rpqpel', 'pattern': {'ID': u'b0rpqpel'}, 'size': 157286404}
10.01.2016 21:04:07 DEBUG     HOSTER UploadedTo[2114]: Previous link info: {'status': 2, 'hash': {}, 'name': 'DeChStdeHe20GeDTDL10BlAVReBl46327.part010.rar', 'url': u'http://uploaded.net/file/b0rpqpel', 'pattern': {'ID': u'b0rpqpel'}, 'size': 157286404}
10.01.2016 21:04:07 INFO      HOSTER UploadedTo[2114]: Link name: DeChStdeHe20GeDTDL10BlAVReBl46327.part010.rar
10.01.2016 21:04:07 INFO      HOSTER UploadedTo[2114]: Link size: 150.00 MiB (157286404 bytes)
10.01.2016 21:04:07 INFO      HOSTER UploadedTo[2114]: Link status: online
10.01.2016 21:04:07 INFO      HOSTER UploadedTo[2114]: Processing url: http://uploaded.net/file/b0rpqpel
10.01.2016 21:04:07 INFO      HOSTER UploadedTo[2114]: Looking for direct download link...
10.01.2016 21:04:07 DEBUG     HOSTER UploadedTo[2114]: LOAD URL http://uploaded.net/file/b0rpqpel | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
10.01.2016 21:04:07 INFO      HOSTER UploadedTo[2114]: Direct download link detected
10.01.2016 21:04:07 INFO      HOSTER UploadedTo[2114]: Downloading file...
10.01.2016 21:04:07 DEBUG     HOSTER UploadedTo[2114]: DOWNLOAD URL http://fra-7m17-stor05.uploaded.net/dl/ab617ad6-bc6e-4403-a7ae-b67ac15e20d5 | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
10.01.2016 21:04:07 DEBUG     Content-Disposition: DeChStdeHe20GeDTDL10BlAVReBl46327.part010.rar
10.01.2016 21:04:08 INFO      HOSTER UploadedTo[2130]: File saved
10.01.2016 21:04:08 INFO      HOSTER UploadedTo[2130]: Checking download...
10.01.2016 21:04:08 INFO      HOSTER UploadedTo[2130]: File is OK
10.01.2016 21:04:08 INFO      HOSTER UploadedTo[2130]: Checking file (with built-in rules)...
```

**Comment by GammaC0de** [comment]
@nordic-style I will need an account to check that..

**Comment by nordic-style** [comment]
ok - how can i send it to you?

**Comment by nordic-style** [comment]
@GammaC0de how can i send you the ul account details?

**Comment by GammaC0de** [comment]
Send it to nitzo2001 {AT} yahoo {dot} com

**Comment by GammaC0de** [comment]
@nordic-style Please send me sample links

**Comment by nordic-style** [comment]
@GammaC0de may i send them via e-mail? I would prefer to send you a link to random stuff (maybe something you normaly would not download) instead of my private videos. Is that fine with you?

**Comment by GammaC0de** [comment]
:+1:

**Comment by nordic-style** [comment]
Done

**Comment by GammaC0de** [comment]
Until now, 24 files successfully downloads with not even single captcha wait..
try downloading the latest stable from git...

**Comment by GammaC0de** [comment]
Ok, so it did try once to download as free download.
Try maybe decreasing LOGIN_TIMEOUT of `accounts/UploadedTo.py`, see if that helps.
```patch
--- UploadedTo.py.old   2016-01-05 01:00:13.000000000 +0200
+++ UploadedTo.py       2016-01-14 00:58:44.694857958 +0200
@@ -17,6 +17,8 @@
     __authors__     = [("Walter Purcaro", "vuolter@gmail.com")]


+    LOGIN_TIMEOUT = 15 * 60
+
     COOKIES = False

     PREMIUM_PATTERN      = r'<em>Premium</em>'

```

**Comment by nordic-style** [comment]
![broken](https://cloud.githubusercontent.com/assets/11313330/12321556/f38388e6-baae-11e5-98c7-f9b556398141.png)
![normal](https://cloud.githubusercontent.com/assets/11313330/12321565/f83b599a-baae-11e5-964f-81cd8873a624.png)

**Comment by GammaC0de** [comment]
What are you showing here?

**Comment by nordic-style** [comment]
Didn't mean to send it yet.

**Comment by GammaC0de** [comment]
Same as #2260
