### ISSUE TITLE
OneFichierCom Error 

### ISSUE THREAD

**Issue by thegounet** [pyload/pyload#2288]
```
13.01.2016 00:40:53 INFO      Added package film containing 1 links
13.01.2016 00:40:54 INFO      Download starts: https://1fichier.com/?AAAA
13.01.2016 00:40:55 WARNING   HOSTER OneFichierCom[186]: Plugin may be unstable
13.01.2016 00:40:55 INFO      HOSTER OneFichierCom[186]: Grabbing link info...
13.01.2016 00:40:56 INFO      Download starts: https://1fichier.com/?oAAA
13.01.2016 00:40:56 INFO      HOSTER OneFichierCom[186]: Link name: ?oAAAA
13.01.2016 00:40:56 INFO      HOSTER OneFichierCom[186]: Link size: N/D
13.01.2016 00:40:56 INFO      HOSTER OneFichierCom[186]: Link status: en file d'attente
13.01.2016 00:40:56 INFO      HOSTER OneFichierCom[186]: Processing url: https://1fichier.com/?oAAAA
13.01.2016 00:40:56 INFO      HOSTER OneFichierCom[186]: Looking for direct download link...
13.01.2016 00:40:57 INFO      HOSTER OneFichierCom[186]: Direct download link not found
13.01.2016 00:40:57 INFO      HOSTER OneFichierCom[186]: Checking for link errors...
13.01.2016 00:40:57 INFO      HOSTER OneFichierCom[186]: No errors found
13.01.2016 00:40:57 INFO      HOSTER OneFichierCom[186]: Grabbing link info...
13.01.2016 00:40:57 WARNING   HOSTER OneFichierCom[186]: Plugin may be unstable
13.01.2016 00:40:57 INFO      HOSTER OneFichierCom[186]: Grabbing link info...
13.01.2016 00:40:58 INFO      HOSTER OneFichierCom[186]: Link name:  AAA.avi
13.01.2016 00:40:58 INFO      HOSTER OneFichierCom[186]: Link size: 1.38 GiB (1481763717 bytes)
13.01.2016 00:40:58 INFO      HOSTER OneFichierCom[186]: Link status: en ligne
13.01.2016 00:40:58 INFO      HOSTER OneFichierCom[186]: Processing as free download...
13.01.2016 00:40:58 INFO      HOSTER OneFichierCom[186]: Checking download...
13.01.2016 00:40:58 WARNING   Download failed: AAA.avi | Parse error: No file downloaded | Plugin may be out of date
13.01.2016 00:40:58 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: AAA.avi (pid:102)
13.01.2016 00:40:58 INFO      ADDON UnSkipOnFail: No duplicates found
13.01.2016 00:40:58 WARNING   Download failed:  AAA.avi | 'NoneType' object has no attribute 'id'
13.01.2016 00:40:58 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: AAA.avi (pid:102)
13.01.2016 00:40:59 INFO      ADDON UnSkipOnFail: No duplicates found
13.01.2016 00:40:59 ERROR     Error executing hooks: plugin
````

from fresh git fetch

**Comment by GammaC0de** [comment]
@thegounet Check partial fix is #2265 and rebort back

**Comment by thegounet** [comment]
thank you i'll try the fix

**Comment by GammaC0de** [comment]
Debug log please

**Comment by thegounet** [comment]
```
13.01.2016 21:44:40 INFO      Added package film containing 1 links
13.01.2016 21:44:40 INFO      Download starts: https://1fichier.com/?56du7k6jgy
13.01.2016 21:44:41 WARNING   HOSTER OneFichierCom[187]: Plugin may be unstable
13.01.2016 21:44:41 INFO      HOSTER OneFichierCom[187]: Grabbing link info...
13.01.2016 21:44:42 INFO      Download starts: https://1fichier.com/?56du7k6jgy
13.01.2016 21:44:42 INFO      Download finished: https://1fichier.com/?56du7k6jgy
13.01.2016 21:44:42 WARNING   Download failed: https://1fichier.com/?56du7k6jgy | No file downloaded
13.01.2016 21:44:42 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: https://1fichier.com/?56du7k6jgy (pid:103)
13.01.2016 21:44:42 INFO      ADDON UnSkipOnFail: No duplicates found
13.01.2016 21:44:43 WARNING   Download failed: https://1fichier.com/?56du7k6jgy | 'NoneType' object has no attribute 'id'
13.01.2016 21:44:43 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: https://1fichier.com/?56du7k6jgy (pid:103)
13.01.2016 21:44:43 INFO      ADDON UnSkipOnFail: No duplicates found
13.01.2016 21:44:43 ERROR     Error executing hooks: plugin
```

**Comment by GammaC0de** [comment]
@thegounet Please turn on DEBUG mode then resend a log

**Comment by thegounet** [comment]
with debug mode  : 

```13.01.2016 21:48:25 INFO      Download starts: https://1fichier.com/?56du7k6jgy
13.01.2016 21:48:25 DEBUG     ADDON ExternalScripts: No script found under folde                r `download_preparing`
13.01.2016 21:48:25 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent str                ing `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
13.01.2016 21:48:26 DEBUG     HOSTER OneFichierCom[187]: Plugin version: 0.98
13.01.2016 21:48:26 DEBUG     HOSTER OneFichierCom[187]: Plugin status: testing
13.01.2016 21:48:26 WARNING   HOSTER OneFichierCom[187]: Plugin may be unstable
13.01.2016 21:48:26 INFO      HOSTER OneFichierCom[187]: Grabbing link info...
13.01.2016 21:48:27 INFO      Download starts: https://1fichier.com/?56du7k6jgy
13.01.2016 21:48:27 DEBUG     ADDON ExternalScripts: No script found under folde                r `download_preparing`
13.01.2016 21:48:27 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent str                ing `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
13.01.2016 21:48:27 INFO      Download finished: https://1fichier.com/?56du7k6jg                y
13.01.2016 21:48:27 DEBUG     ADDON ExternalScripts: No script found under folde                r `download_finished`
13.01.2016 21:48:27 DEBUG     ADDON Checksum:
13.01.2016 21:48:27 WARNING   Download failed: https://1fichier.com/?56du7k6jgy                 | No file downloaded
13.01.2016 21:48:27 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates                 of: https://1fichier.com/?56du7k6jgy (pid:103)
13.01.2016 21:48:28 INFO      ADDON UnSkipOnFail: No duplicates found
13.01.2016 21:48:28 DEBUG     ADDON ExternalScripts: No script found under folde                r `download_failed`
13.01.2016 21:48:28 WARNING   Download failed: https://1fichier.com/?56du7k6jgy                 | 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/var/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/var/pyload/module/plugins/internal/Base.py", line 292, in preprocessing
    return self._process(*args, **kwargs)
  File "/var/pyload/module/plugins/internal/Hoster.py", line 107, in _process
    self._setup()
  File "/var/pyload/module/plugins/internal/Base.py", line 166, in _setup
    self.grab_info()
  File "/var/pyload/module/plugins/internal/Base.py", line 231, in grab_info
    self.log_debug("Link info: %s" % self.info)
  File "/var/pyload/module/plugins/internal/Plugin.py", line 84, in log_debug
    self._log("debug", self.__type__, self.__name__, args)
  File "/var/pyload/module/plugins/internal/Base.py", line 119, in _log
    'id'        : self.pyfile.id,
AttributeError: 'NoneType' object has no attribute 'id'
13.01.2016 21:48:28 DEBUG     ADDON ExternalScripts: No script found under folde                r `all_downloads_processed`
13.01.2016 21:48:28 DEBUG     All downloads processed
13.01.2016 21:48:28 DEBUG     ADDON ExternalScripts: No script found under folde                r `all_downloads_processed`
13.01.2016 21:48:28 DEBUG     All downloads processed
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/var/pyload/module/PluginThread.py", line 309, in run
    self.writeDebugReport(pyfile)
  File "/var/pyload/module/PluginThread.py", line 57, in writeDebugReport
    dump = self.getDebugDump(pyfile)
  File "/var/pyload/module/PluginThread.py", line 92, in getDebugDump
    self.m.core.api.getServerVersion(), pyfile.pluginname, pyfile.plugin.__versi                on__, format_exc())
AttributeError: plugin
```

**Comment by GammaC0de** [comment]
This worked for me flawlessly, are you sure you're using the latest stable (https://github.com/pyload/pyload/archive/stable.zip) branch?

**Comment by thegounet** [comment]
the lasted git revision, i'll try with this link

**Comment by davidmarli** [comment]
Same issue here...

**Comment by thegounet** [comment]
still failling for me

**Comment by GammaC0de** [comment]
Which OS are you running pyLoad?

**Comment by thegounet** [comment]
debian jessy

**Comment by davidmarli** [comment]
Still failing too. I'm running pyload on synology. All is up to date.

**Comment by AblionGE** [comment]
Hi! Same issue for me on Debian Wheezy.

**Comment by lemicp** [comment]
Same here on syno

**Comment by vuolter** [comment]
Checking...

**Comment by GammaC0de** [comment]
Can you confirm if https://github.com/pyload/pyload/commit/cad33cec0ca6d19c66beaef2746f30630ff98102 resolves this issue?

**Comment by thegounet** [comment]
Work for me ! thank you !

**Comment by GammaC0de** [comment]
OneFichierCom works, closing.
