### ISSUE TITLE
BasePlugin' object has no attribute 'isdownload'

### ISSUE THREAD

**Issue by Piero87** [pyload/pyload#2302]
I'm trying to download a file with the BasePlugin and give me error:

    BasePlugin' object has no attribute 'is download'

```
19.01.2016 15:09:35 INFO      ADDON UpdateManager: All plugins are up to date!
19.01.2016 15:09:40 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
19.01.2016 15:09:56 INFO      Download starts: WaP.part1.rar
19.01.2016 15:09:56 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
19.01.2016 15:09:56 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
19.01.2016 15:09:57 DEBUG     HOSTER BasePlugin[1]: Plugin version: 0.51
19.01.2016 15:09:57 DEBUG     HOSTER BasePlugin[1]: Plugin status: testing
19.01.2016 15:09:57 WARNING   HOSTER BasePlugin[1]: Plugin may be unstable
19.01.2016 15:09:57 DEBUG     HOSTER BasePlugin[1]: Config option `use_premium` not found, use default `True`
19.01.2016 15:09:57 INFO      HOSTER BasePlugin[1]: Grabbing link info...
19.01.2016 15:09:57 DEBUG     HOSTER BasePlugin[1]: Link info: {'status': 3, 'hash': {}, 'name': 'WaP.part1.', 'url': u'http://url.WaP.part1.rar', 'pattern': {}, 'size': 0}
19.01.2016 15:09:57 DEBUG     HOSTER BasePlugin[1]: Previous link info: {}
19.01.2016 15:09:57 INFO      HOSTER BasePlugin[1]: Link name: WaP.part1.rar
19.01.2016 15:09:57 INFO      HOSTER BasePlugin[1]: Link size: N/D
19.01.2016 15:09:57 INFO      HOSTER BasePlugin[1]: Link status: in coda
19.01.2016 15:09:57 INFO      HOSTER BasePlugin[1]: Processing url: http://url.WaP.part1.rar
19.01.2016 15:09:57 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
19.01.2016 15:09:57 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
19.01.2016 15:09:57 WARNING   Download failed: WaP.part1.rar | 'BasePlugin' object has no attribute 'isdownload'
Traceback (most recent call last):
  File "/volume1/@appstore/pyload/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/volume1/@appstore/pyload/var/config/userplugins/internal/Base.py", line 290, in preprocessing
    return self._process(*args, **kwargs)
  File "/volume1/@appstore/pyload/var/config/userplugins/internal/Hoster.py", line 118, in _process
    self.process(self.pyfile)
  File "/volume1/@appstore/pyload/var/config/userplugins/hoster/Http.py", line 32, in process
    link = self.isdownload(url)
AttributeError: 'BasePlugin' object has no attribute 'isdownload'
19.01.2016 15:09:57 DEBUG     Error creating zip file: [Errno 2] No such file or directory: 'tmp/BasePlugin'
19.01.2016 15:09:57 INFO      Debug Report written to debug_BasePlugin_19-01-2016_15-09-57.txt
19.01.2016 15:09:57 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: WaP.part1.rar (pid:1)
19.01.2016 15:09:57 INFO      ADDON UnSkipOnFail: No duplicates found
19.01.2016 15:09:57 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
19.01.2016 15:09:57 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
19.01.2016 15:09:57 DEBUG     All downloads processed
```

**Comment by Piero87** [comment]
thanks! it works!

**Comment by GammaC0de** [comment]
:+1:
