### ISSUE TITLE
Filecrypt not working

### ISSUE THREAD

**Issue by sraedler** [pyload/pyload#2311]
Filecrypt is not working, see debug log.

```
21.01.2016 15:11:51 INFO      Added package Brand containing 1 links
21.01.2016 15:11:51 INFO      Decrypting starts: http://filecrypt.cc/Container/F0554EE980.html
21.01.2016 15:11:52 DEBUG     CRYPTER FilecryptCc[325]: Plugin version: 0.23
21.01.2016 15:11:52 DEBUG     CRYPTER FilecryptCc[325]: Plugin status: testing
21.01.2016 15:11:52 WARNING   CRYPTER FilecryptCc[325]: Plugin may be unstable
21.01.2016 15:11:52 DEBUG     CRYPTER FilecryptCc[325]: Config option `use_premium` not found, use default `True`
21.01.2016 15:11:52 INFO      CRYPTER FilecryptCc[325]: Grabbing link info...
21.01.2016 15:11:52 DEBUG     CRYPTER FilecryptCc[325]: Link info: {'status': 3, 'hash': {}, 'name': 'F0554EE980.html', 'url': u'http://filecrypt.cc/Container/F0554EE980.html', 'pattern': {}, 'size': 0}
21.01.2016 15:11:52 DEBUG     CRYPTER FilecryptCc[325]: Previous link info: {}
21.01.2016 15:11:52 INFO      CRYPTER FilecryptCc[325]: Link name: F0554EE980.html
21.01.2016 15:11:52 INFO      CRYPTER FilecryptCc[325]: Link size: N/D
21.01.2016 15:11:52 INFO      CRYPTER FilecryptCc[325]: Link status: eingereiht
21.01.2016 15:11:52 INFO      CRYPTER FilecryptCc[325]: Processing url: http://filecrypt.cc/Container/F0554EE980.html
21.01.2016 15:11:52 DEBUG     CRYPTER FilecryptCc[325]: LOAD URL http://filecrypt.cc/Container/F0554EE980.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
21.01.2016 15:11:52 INFO      CRYPTER FilecryptCc[325]: No captcha found
21.01.2016 15:11:52 ERROR     Decrypting failed: F0554EE980.html | Decrypt error: No link grabbed | Plugin may be out of date
```

**Comment by sraedler** [comment]
bot Wirkung with The new Captcha.py

```TypeError: not all arguments converted during string formatting```

**Comment by GammaC0de** [comment]
DEBUG log please

**Comment by sraedler** [comment]
Do you need more log or is this enough?


```pyLoad 0.4.9 Debug Report of FilecryptCc 0.24 

TRACEBACK:
 Traceback (most recent call last):
  File "/volume1/@appstore/pyload/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/volume1/@appstore/pyload/pyload/module/plugins/internal/Base.py", line 290, in preprocessing
    return self._process(*args, **kwargs)
  File "/volume1/@appstore/pyload/pyload/module/plugins/internal/Base.py", line 283, in _process
    self.process(self.pyfile)
  File "/volume1/@appstore/pyload/pyload/module/plugins/internal/Crypter.py", line 34, in process
    self.decrypt(pyfile)
  File "/volume1/@appstore/pyload/pyload/module/plugins/crypter/FilecryptCc.py", line 59, in decrypt
    self.handle_captcha()
  File "/volume1/@appstore/pyload/pyload/module/plugins/crypter/FilecryptCc.py", line 115, in handle_captcha
    input_type="png", output_type='positional')
  File "/volume1/@appstore/pyload/pyload/module/plugins/internal/Captcha.py", line 47, in decrypt
    return self.decrypt_image(img, input_type, output_type, ocr, timeout)
  File "/volume1/@appstore/pyload/pyload/module/plugins/internal/Captcha.py", line 106, in decrypt_image
    self.log_info(_("Captcha result: `%s`") % result)
TypeError: not all arguments converted during string formatting
```
