### ISSUE TITLE
Error performing periodical task | local variable 'storage' 

### ISSUE THREAD

**Issue by sveni-lee** [pyload/pyload#2332]
`06.02.2016 14:37:20 ERROR     ADDON SJ: Error performing periodical task | local variable 'storage' referenced before assignment
Traceback (most recent call last):
  File "/usr/bin/pyLoadCore", line 667, in <module>
    main()
  File "/usr/bin/pyLoadCore", line 658, in main
    pyload_core.start()
  File "/usr/bin/pyLoadCore", line 469, in start
    self.scheduler.work()
  File "/usr/share/pyload/module/Scheduler.py", line 85, in work
    j.start()
  File "/usr/share/pyload/module/Scheduler.py", line 111, in start
    self.run()
  File "/usr/share/pyload/module/Scheduler.py", line 101, in run
    ret = self.call(*self.args, **self.kwargs)
  File "/home/svenilee/.pyload/userplugins/internal/misc.py", line 182, in _task
    self.task()
  File "/home/svenilee/.pyload/userplugins/hooks/SJ.py", line 162, in periodical_task
    self.range_checkr(link,title)
  File "/home/svenilee/.pyload/userplugins/hooks/SJ.py", line 199, in range_checkr
    self.parse_download(link, title)
  File "/home/svenilee/.pyload/userplugins/hooks/SJ.py", line 225, in parse_download
    self.send_package(title,items) if len(items) > 0 else True
  File "/home/svenilee/.pyload/userplugins/hooks/SJ.py", line 232, in send_package
    if storage == 'downloaded':`

I've updated all Plugins abut everytime I get the same error...
I have delete the files.db several time but allways get the same error...

**Comment by vuolter** [comment]
SJ is not an official plugin, anyhow the Plugin's DB class will get an hotfix soon, perhaps could also solve this issue.
