### ISSUE TITLE
PyCharm Debugging

### ISSUE THREAD

**Issue by sraedler** [pyload/pyload#2341]
Does anyone know, why I get this error when starting debugmode in Pycharm?

> AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.4\helpers\pydev\pydevd_frame.py", line 424, in trace_dispatch
    self.doWaitSuspend(thread, frame, event, arg)
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.4\helpers\pydev\pydevd_frame.py", line 56, in doWaitSuspend
    self._args[0].doWaitSuspend(*args, **kwargs)
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.4\helpers\pydev\pydevd.py", line 1417, in doWaitSuspend
    self.processInternalCommands()
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.4\helpers\pydev\pydevd.py", line 585, in processInternalCommands
    queue = self.getInternalQueue(thread_id)
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.4\helpers\pydev\pydevd.py", line 465, in getInternalQueue
    if thread_id.startswith('__frame__'):

**Comment by vuolter** [comment]
I really think that's not related directly to pyLoad. XD
