### ISSUE TITLE
Error opening Settings after enabling debug mode

### ISSUE THREAD

**Issue by chodid** [pyload/pyload#2344]
Hey everybody,

I just tried to delete an uploaded.net account, which always left me with an error message - being unable to delete it. After enabling debug mode in order to ask for help on github - pyload settings stopped working.
The message I get when opening the settings page is as follows:

> 
> An Error occured, please enable debug mode to get more details.
> 
> HTTP Response 500
> 
> Traceback (most recent call last):
> File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
> return route.call(**args)
> File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
> rv = callback(*a, **ka)
> File "/usr/share/pyload/module/web/utils.py", line 113, in _view
> return func(*args, **kwargs)
> File "/usr/share/pyload/module/web/pyload_app.py", line 256, in config
> accs = PYLOAD.getAccounts(False)
> File "/usr/share/pyload/module/Api.py", line 875, in getAccounts
> accs = self.core.accountManager.getAccountInfos(False, refresh)
> File "/usr/share/pyload/module/utils.py", line 165, in new
> return func(*args)
> File "/usr/share/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
> p = self.getAccountPlugin(p)
> File "/usr/share/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
> self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
> File "/home/pyload/config/userplugins/internal/Account.py", line 60, in __init__
> self.setAccounts(accounts)
> File "/home/pyload/config/userplugins/internal/Account.py", line 112, in setAccounts
> self._login(user, data)
> AttributeError: 'UploadedTo' object has no attribute 'pyfile'

Log File:
```
116	17.02.2016 16:24:13	INFO	starte pyLoad 0.4.9
117	17.02.2016 16:24:13	INFO	Benutze Home-Verzeichnis: /home/pyload/config
118	17.02.2016 16:24:13	DEBUG	Deleting old pidfile /home/pyload/.pyload/pyload.pid
119	17.02.2016 16:24:13	DEBUG	Remote activated: True
120	17.02.2016 16:24:15	DEBUG	created index of plugins
121	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.hooks.LinkdecrypterComHook -> userplugins.hooks.LinkdecrypterComHook
122	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.internal.MultiHook -> userplugins.internal.MultiHook
123	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.internal.Hook -> userplugins.internal.Hook
124	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.crypter.LinkdecrypterCom -> userplugins.crypter.LinkdecrypterCom
125	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.internal.Crypter -> userplugins.internal.Crypter
126	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
127	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
128	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
129	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.internal.Extractor -> userplugins.internal.Extractor
130	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
131	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.internal.Hoster -> userplugins.internal.Hoster
132	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
133	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.hooks.ClickAndLoad -> userplugins.hooks.ClickAndLoad
134	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
135	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.hooks.XFileSharingPro -> userplugins.hooks.XFileSharingPro
136	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.hooks.FileBot -> userplugins.hooks.FileBot
137	17.02.2016 16:24:15	DEBUG	Redirected import module.plugins.hooks.UserAgentSwitcher -> userplugins.hooks.UserAgentSwitcher
138	17.02.2016 16:24:15	INFO	Aktivierte Plugins: ClickAndLoad, ExternalScripts, ExtractArchive, FileBot, LinkdecrypterComHook, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharingPro
139	17.02.2016 16:24:15	INFO	Deaktivierte Plugins: AlldebridComHook, AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMe, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinksnappyComHook, MegaDebridEuHook, MegaRapidoNetHook, MergeFiles, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridComHook, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, UnrestrictLiHook, WindowsPhoneNotify, XMPPInterface, ZeveraComHook
140	17.02.2016 16:24:15	INFO	Downloadzeit: True
141	17.02.2016 16:24:15	INFO	Nutze SSL Thrift Backend
142	17.02.2016 16:24:15	INFO	Starte ThriftBackend: 0.0.0.0:6090
143	17.02.2016 16:24:16	INFO	Free space: 222.22 GiB
144	17.02.2016 16:24:16	INFO	Starting threaded SSL webserver: 0.0.0.0:6080
145	17.02.2016 16:24:16	INFO	Activating Accounts...
146	17.02.2016 16:24:16	DEBUG	Redirected import module.plugins.accounts.UploadedTo -> userplugins.accounts.UploadedTo
147	17.02.2016 16:24:16	DEBUG	Redirected import module.plugins.internal.Account -> userplugins.internal.Account
148	17.02.2016 16:28:52	INFO	Added package a containing 1 links
149	17.02.2016 16:28:52	DEBUG	Redirected import module.plugins.hoster.UploadedTo -> userplugins.hoster.UploadedTo
150	17.02.2016 16:28:52	DEBUG	Redirected import module.plugins.internal.ReCaptcha -> userplugins.internal.ReCaptcha
151	17.02.2016 16:28:52	DEBUG	Redirected import module.plugins.internal.Captcha -> userplugins.internal.Captcha
152	17.02.2016 16:28:52	DEBUG	Run Info Fetching for UploadedTo
153	17.02.2016 16:28:52	DEBUG	Finished Info Fetching for UploadedTo 
```

Thanks in advance for any help!

**Comment by chodid** [comment]
Any ideas? Otherwise I'd try reinstalling pyload. Is there a guide for removal somewhere?

**Comment by vuolter** [comment]
In your config directory, rename or delete the account.conf file and delete the userplugins folder, the start pyLoad and wait the updatemager ends to update all your plugins.

**Comment by chodid** [comment]
Perfect! Resolved the issue and enabled me to start over regarding accounts.
Thanks hell of a lot!
