### ISSUE TITLE
Rapidu.net HTTP Response 500

### ISSUE THREAD

**Issue by ladigb** [pyload/pyload#2372]
Hi
some problem when add premium rapidu account

An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/web/utils.py", line 113, in _view
return func(*args, **kwargs)
File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/web/pyload_app.py", line 256, in config
accs = PYLOAD.getAccounts(False)
File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/Api.py", line 875, in getAccounts
accs = self.core.accountManager.getAccountInfos(False, refresh)
File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/utils.py", line 165, in new
return func(*args)
File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
p = self.getAccountPlugin(p)
File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

**Comment by GammaC0de** [comment]
@ladigb I will need an account for testing.
Please send account information to nitzo2001 \<AT\> yahoo \<DOT\> com

**Comment by ladigb** [comment]
just sent

**Comment by GammaC0de** [comment]
@ladigb Have you installed `pyLoad` just recently?
Also send sample URL

**Comment by ladigb** [comment]
no, instaled it 1 year ago
https://rapidu.net/7813599612/Train.Simulator.2016.2015.v53.6c.Steam.Edition.P2P.part1.rar

**Comment by GammaC0de** [comment]
Work fine for me, try refreshing your `userplugins` :
* Get the stable package from https://github.com/pyload/pyload/archive/stable.zip
* Extract all the **subfolders** in `<stable.zip>/module/plugins` to your `userplugins` directory.

**Comment by ladigb** [comment]
perfect start working
thank you for help

**Comment by GammaC0de** [comment]
:+1:
