### ISSUE TITLE
Fresh install Update failed.

### ISSUE THREAD

**Issue by Agomy** [pyload/pyload#2382]
Hello,

I have made a fresh install of pyLoad on a Debian system and followed the instructions made in #2000 to change the updater file.
However during the update it fails with the following error: 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/usr/share/pyload/module/plugins/hooks/UpdateManager.py", line 52, in periodical
    self.checkPlugins(updates)
  File "/usr/share/pyload/module/plugins/hooks/UpdateManager.py", line 136, in checkPlugins
    "version": float(version)
ValueError: could not convert string to float:
```

any suggestions what could be the reason and how to fix it?

**Comment by lordfiSh** [comment]
wget https://github.com/pyload/pyload/archive/stable.zip && unzip stable.zip
cp -R pyload-stable/module/plugins/* ~/.pyload/userplugins/
rm unzip stable.zip

**Comment by GammaC0de** [comment]
@lordfiSh #2000
