### ISSUE TITLE
Unable to logon to webinterface in chrome

### ISSUE THREAD

**Issue by vrapp** [pyload/pyload#2401]
Trying to logon from Chrome  49.0.2623.87 m - it fails with the error message below.

Doing it from "incognito" window - it works.
# error message:

Critical error while processing request:

Error:

CookieError('Illegal key value: wireless_list_D8:50:E6:45:7E:B0_temp',)
Traceback:

Traceback (most recent call last):
  File "/tmp/mnt/sda1/entware/share/pyload/module/lib/bottle.py", line 820, in wsgi
    out = self._cast(self._handle(environ), request, response)
  File "/tmp/mnt/sda1/entware/share/pyload/module/lib/bottle.py", line 773, in _cast
    out = self.error_handler.get(out.status, repr)(out)
  File "/tmp/mnt/sda1/entware/share/pyload/module/web/pyload_app.py", line 83, in error500
    error.traceback.replace("\n", "
") if error.traceback else "No Traceback"])
  File "/tmp/mnt/sda1/entware/share/pyload/module/web/pyload_app.py", line 72, in base
    return render_to_response('base.html', {'messages': messages}, [pre_processor])
  File "/tmp/mnt/sda1/entware/share/pyload/module/web/utils.py", line 27, in render_to_response
    args.update(p())
  File "/tmp/mnt/sda1/entware/share/pyload/module/web/pyload_app.py", line 45, in pre_processor
    user = parse_userdata(s)
  File "/tmp/mnt/sda1/entware/share/pyload/module/web/utils.py", line 95, in parse_userdata
    return {"name": session.get("name", "Anonymous"),
  File "/tmp/mnt/sda1/entware/share/pyload/module/lib/beaker/session.py", line 554, in __getattr__
    return getattr(self._session(), attr)
  File "/tmp/mnt/sda1/entware/share/pyload/module/lib/beaker/session.py", line 550, in _session
    **params)
  File "/tmp/mnt/sda1/entware/share/pyload/module/lib/beaker/session.py", line 105, in __init__
    self.cookie = Cookie.SimpleCookie(input=cookieheader)
CookieError: Illegal key value: wireless_list_D8:50:E6:45:7E:B0_temp

**Comment by vrapp** [comment]
Same in Chrome Version 49.0.2623.110 m (64-bit)

**Comment by ladigb** [comment]
clear your cookie, should help or use incognito mode.

**Comment by QMaxy** [comment]
Same error here in FF with pyLoad 0.4.9 installed on an Asus RT Router with Merlin firmware/entware-ng.
Incognito mode works fine, cache clean need to be done everytime, and I've found that the problem doesn't appear if I use my router name instead of IP address (i.e. https://myasus:8011) or accessing using No-Ip registered hostname (https://myasus.no-ip.com:8011).

**Comment by BKPepe** [comment]
I installed latest version from git.
Here is my issue.
Chrome 56.0.2924.87 said only: Critical error while processing request: 
but on Firefox version: 51.0.1 it works w/o any problem.
What should I provide you to get it fixed?

**Comment by micwoj92** [comment]
I can login fine, I'm using latest version from pypi and chrome Version 96.0.4664.110 (Official Build) (64-bit)

**Comment by GammaC0de** [comment]
closing.
