### ISSUE TITLE
OverflowError: math range error

### ISSUE THREAD

**Issue by sti0** [pyload/pyload#2426]
Hello,
I reinstalled pyload (cause of pycrypto wasn't recognized ) and now i get this error when I try to setup pyload ( python pyLoadCore.py -s )
```
Traceback (most recent call last):
  File "/usr/local/pyload/pyLoadCore.py", line 48, in <module>
    from module.network.RequestFactory import RequestFactory
  File "/usr/local/pyload/module/network/RequestFactory.py", line 22, in <module>
    from Browser import Browser
  File "/usr/local/pyload/module/network/Browser.py", line 6, in <module>
    from HTTPRequest import HTTPRequest
  File "/usr/local/pyload/module/network/HTTPRequest.py", line 24, in <module>
    from httplib import responses
  File "/opt/lib/python2.5/httplib.py", line 70, in <module>
    import mimetools
  File "/opt/lib/python2.5/mimetools.py", line 6, in <module>
    import tempfile
  File "/opt/lib/python2.5/tempfile.py", line 33, in <module>
    from random import Random as _Random
  File "/opt/lib/python2.5/random.py", line 58, in <module>
    SG_MAGICCONST = 1.0 + _log(4.5)
OverflowError: math range error
```
I've tryed to reinstall the entire ipkg and python framework and downloaded the pyload stable version serveral times but every time I get the error above...

Do you have any idea?

Thanks!

**Comment by GammaC0de** [comment]
This problem is not related to pyload:
if you open python and issue:
`from random import Random as _Random`
you will get the same error, so your python installation is broken
