### ISSUE TITLE
UpdateManager.py error at startup (in console)

### ISSUE THREAD

**Issue by eerozeteen** [pyload/pyload#2497]
I have that error in console when i startup pyload:

07.06.2016 21:50:16 DEBUG     ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (.........) , (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
07.06.2016 21:50:16 ERROR     ADDON UpdateManager: Error updating plugin: CAPTCHA UlozTo | Bad version number on the server
**Traceback (most recent call last):
  File "/ffp/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/ffp/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/i-data/0a3e5834/ffp@apps/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/i-data/0a3e5834/ffp@apps/pyload/module/plugins/hooks/UpdateManager.py", line 150, in update
    if self._update() != 2 or not self.config.get('autorestart'):
  File "/i-data/0a3e5834/ffp@apps/pyload/module/plugins/hooks/UpdateManager.py", line 172, in _update
    exitcode = self.update_plugins()
  File "/i-data/0a3e5834/ffp@apps/pyload/module/plugins/hooks/UpdateManager.py", line 198, in update_plugins
    updated = self._update_plugins(server_data)
  File "/i-data/0a3e5834/ffp@apps/pyload/module/plugins/hooks/UpdateManager.py", line 291, in _update_plugins
    newver = float(plugin_version)
ValueError: could not convert string to float:** 

07.06.2016 21:50:16 INFO      ADDON UpdateManager: All plugins are up to date!

**Comment by GammaC0de** [comment]
This is a known issue since three month (pyload/updatemanager#39), you can ignore it since it regards `UlozTo` capptcha plugin only.
