### ISSUE TITLE
Nitroflare redirects

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#2585]
hi,
to test a bit with the Nitroflare plugin, I'm using this sample URL I found googling: ```http://nitroflare.com/view/4EE928DBC53566F/Bed_set_01.rar```, which gives:
```
04.09.2016 14:10:29 DEBUG     HOSTER NitroflareCom[28149]: Plugin version: 0.22
04.09.2016 14:10:29 DEBUG     HOSTER NitroflareCom[28149]: Plugin status: testing
04.09.2016 14:10:29 WARNING   HOSTER NitroflareCom[28149]: Plugin may be unstable
04.09.2016 14:10:29 INFO      HOSTER NitroflareCom[28149]: Grabbing link info...
04.09.2016 14:10:30 DEBUG     HOSTER NitroflareCom[28149]: Link info: {'status': 2, 'hash': {}, 'name': u'Bed_set_01.rar', 'url': u'http://nitroflare.com/view/4EE928DBC53566F/Bed_set_01.rar', 'pattern': {'ID': u'4EE928DBC53566F'}, 'size': 372383107}
04.09.2016 14:10:30 DEBUG     HOSTER NitroflareCom[28149]: Previous link info: {}
04.09.2016 14:10:30 INFO      HOSTER NitroflareCom[28149]: Link name: Bed_set_01.rar
04.09.2016 14:10:30 INFO      HOSTER NitroflareCom[28149]: Link size: 355.13 MiB (372383107 bytes)
04.09.2016 14:10:30 INFO      HOSTER NitroflareCom[28149]: Link status: online
04.09.2016 14:10:30 INFO      HOSTER NitroflareCom[28149]: Processing url: http://nitroflare.com/view/4EE928DBC53566F/Bed_set_01.rar
04.09.2016 14:10:30 DEBUG     HOSTER NitroflareCom[28149]: starting process...
04.09.2016 14:10:30 DEBUG     HOSTER NitroflareCom[28149]: LOAD URL http://nitroflare.com/view/4EE928DBC53566F/Bed_set_01.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
04.09.2016 14:10:30 INFO      HOSTER NitroflareCom[28149]: Grabbing link info...
04.09.2016 14:10:31 DEBUG     HOSTER NitroflareCom[28149]: Link info: {'status': 2, 'hash': {}, 'name': u'Bed_set_01.rar', 'url': u'http://nitroflare.com/view/4EE928DBC53566F/Bed_set_01.rar', 'pattern': {'S': u'355.13', 'U': u'MB', 'ID': u'4EE928DBC53566F', 'N': u'Bed_set_01.rar'}, 'size': 372380794}
04.09.2016 14:10:31 DEBUG     HOSTER NitroflareCom[28149]: Previous link info: {'status': 2, 'hash': {}, 'name': u'Bed_set_01.rar', 'url': u'http://nitroflare.com/view/4EE928DBC53566F/Bed_set_01.rar', 'pattern': {'ID': u'4EE928DBC53566F'}, 'size': 372383107}
04.09.2016 14:10:31 INFO      HOSTER NitroflareCom[28149]: Link name: Bed_set_01.rar
04.09.2016 14:10:31 INFO      HOSTER NitroflareCom[28149]: Link size: 355.13 MiB (372380794 bytes)
04.09.2016 14:10:31 INFO      HOSTER NitroflareCom[28149]: Link status: online
04.09.2016 14:10:31 INFO      HOSTER NitroflareCom[28149]: Processing as free download...
04.09.2016 14:10:31 DEBUG     HOSTER NitroflareCom[28149]: LOAD URL http://nitroflare.com/ajax/setCookie.php | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'fileId': u'4EE928DBC53566F'} | ref=True | just_header=False
04.09.2016 14:10:31 DEBUG     HOSTER NitroflareCom[28149]: LOAD URL http://nitroflare.com/view/4EE928DBC53566F/Bed_set_01.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'goToFreePage': ''} | ref=True | just_header=False
04.09.2016 14:10:32 DEBUG     pycurl exception 47: Maximum (10) redirects followed
04.09.2016 14:10:32 ERROR     pycurl error 47: Maximum (10) redirects followed
Traceback (most recent call last):
  File "/home/cache/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/cache/pyload/module/plugins/internal/Base.py", line 294, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/cache/pyload/module/plugins/internal/Hoster.py", line 118, in _process
    self.process(self.pyfile)
  File "/home/cache/pyload/module/plugins/internal/SimpleHoster.py", line 290, in process
    self.handle_free(pyfile)
  File "/home/cache/pyload/module/plugins/hoster/NitroflareCom.py", line 67, in handle_free
    self.load(pyfile.url, post={'goToFreePage': ""})
  File "/home/cache/pyload/module/plugins/internal/Base.py", line 497, in load
    return super(Base, self).load(*args, **kwargs)
  File "/home/cache/pyload/module/plugins/internal/Plugin.py", line 217, in load
    html = req.load(url, get, post, bool(ref), bool(cookies), just_header, multipart, decode is True)  #@TODO: Fix network multipart in 0.4.10
  File "/home/cache/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/home/cache/pyload/module/network/HTTPRequest.py", line 197, in load
    self.c.perform()
error: (47, 'Maximum (10) redirects followed')
```
However, command-line curl gets it just fine:
```
% curl -D head "http://nitroflare.com/ajax/setCookie.php" --data "fileId=4EE928DBC53566F" --cookie-jar /tmp/nitrojar.txt; cat head
HTTP/1.1 200 OK
Date: Sun, 04 Sep 2016 12:59:50 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=dbbefea73dce918500d67b273cdfb661c1472993990; expires=Mon, 04-Sep-17 12:59:50 GMT; path=/; domain=.nitroflare.com; HttpOnly
Vary: Accept-Encoding
X-Powered-By: PHP/5.6.17
Set-Cookie: lastFile=4EE928DBC53566F; expires=Sun, 04-Sep-2016 16:05:51 GMT; Max-Age=7200; path=/
X-Content-Type-Options: nosniff
Server: cloudflare-nginx
CF-RAY: 2dd19ef8224c3bed-CDG

% curl -D head "http://nitroflare.com/view/4EE928DBC53566F/Bed_set_01.rar" --data "goToFreePage" --cookie /tmp/nitrojar.txt -L > out.html; cat head                                                                                                                                
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15    0     3  100    12     16     66 --:--:-- --:--:-- --:--:--    66
100 17828    0 17828    0     0  56305      0 --:--:-- --:--:-- --:--:-- 56305
HTTP/1.1 302 Moved Temporarily
Date: Sun, 04 Sep 2016 12:59:59 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.6.17
Set-Cookie: PHPSESSID=3d76s6dlspjhi1m0ar2rcpj9b6; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
location: /view/4EE928DBC53566F/Bed_set_01.rar/free
X-Content-Type-Options: nosniff
Server: cloudflare-nginx
CF-RAY: 2dd19f31ff2c090e-CDG

HTTP/1.1 200 OK
Date: Sun, 04 Sep 2016 12:59:59 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
X-Powered-By: PHP/5.6.17
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: lastFile=4EE928DBC53566F; expires=Sun, 04-Sep-2016 16:06:00 GMT; Max-Age=7200; path=/
X-Frame-Options: sameorigin
X-Content-Type-Options: nosniff
Server: cloudflare-nginx
CF-RAY: 2dd19f327f39090e-CDG

```

Any idea what might be pycurl's problem here? Can I make pycurl be more verbose maybe?

**Comment by GammaC0de** [comment]
Works fine for me..

As for verbose pycurl, uncoment https://github.com/pyload/pyload/blob/stable/module/network/HTTPRequest.py#L85

**Comment by GammaC0de** [comment]
Closing because of no response
