### ISSUE TITLE
0.49 Home and Config options unvisible

### ISSUE THREAD

**Issue by helmchenlord** [pyload/pyload#2590]
When pressing the Home button in web interface I can't see the downloads.
Nothing is display under Status/Name/Information/Size/Progress.
in console the following is displayed when pressing "Home-Button"

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib64/python2.7/site-packages/bottle.py", line 1735, in wrapper
    json_response = dumps(rv)
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 380, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 275, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 357, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 252, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: MiB(1000.0) is not JSON serializable
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib64/python2.7/site-packages/bottle.py", line 1735, in wrapper
    json_response = dumps(rv)
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 380, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 275, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 357, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 252, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: MiB(1000.0) is not JSON serializable

Choosing Config in Web interface nothing is displayed for the options like Download etc.
The only thing I can see is the "Submit" Button.

Adding an account neither works and results in:

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib64/python2.7/site-packages/bottle.py", line 1729, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/pyload/webui/App/utils.py", line 102, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/pyload/webui/App/json.py", line 276, in add_account
    PYLOAD.updateAccount(type, login, password)
  File "/usr/share/pyload/pyload/Api/__init__.py", line 913, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "/usr/share/pyload/pyload/utils/__init__.py", line 204, in new
    return func(*args)
  File "/usr/share/pyload/pyload/manager/Account.py", line 157, in updateAccount
    updated = p.updateAccounts(user, password, options)
AttributeError: 'NoneType' object has no attribute 'updateAccounts'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib64/python2.7/site-packages/bottle.py", line 1729, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/pyload/webui/App/utils.py", line 102, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/pyload/webui/App/json.py", line 276, in add_account
    PYLOAD.updateAccount(type, login, password)
  File "/usr/share/pyload/pyload/Api/__init__.py", line 913, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "/usr/share/pyload/pyload/utils/__init__.py", line 204, in new
    return func(*args)
  File "/usr/share/pyload/pyload/manager/Account.py", line 157, in updateAccount
    updated = p.updateAccounts(user, password, options)
AttributeError: 'NoneType' object has no attribute 'updateAccounts'

**Comment by GammaC0de** [comment]
@helmchenlord `master` branch is not stable, please read #2000 for installation instructions

**Comment by GammaC0de** [comment]
Closing because of no response
