### ISSUE TITLE
PackageData' object has no attribute 'id

### ISSUE THREAD

**Issue by DocMAX** [pyload/pyload#2628]
this comes if i change clicknload to "add packages to: queue"

```
Okt 20 01:27:57 server pyLoadCore[16811]: 20.10.2016 01:27:57 INFO      Added package http://jdownloader.org/spielwiese containing 1 links
Okt 20 01:27:57 server pyLoadCore[16811]: Exception in thread Thread-13:
Okt 20 01:27:57 server pyLoadCore[16811]: Traceback (most recent call last):
Okt 20 01:27:57 server pyLoadCore[16811]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Okt 20 01:27:57 server pyLoadCore[16811]:     self.run()
Okt 20 01:27:57 server pyLoadCore[16811]:   File "/opt/pyload/module/PluginThread.py", line 466, in run
Okt 20 01:27:57 server pyLoadCore[16811]:     self.f(*self.args, **self.kwargs)
Okt 20 01:27:57 server pyLoadCore[16811]:   File "/opt/pyload/module/plugins/hooks/ClickNLoad.py", line 84, in forward
Okt 20 01:27:57 server pyLoadCore[16811]:     new_ids = set(pack.id for pack in self.pyload.api.getCollector())
Okt 20 01:27:57 server pyLoadCore[16811]:   File "/opt/pyload/module/plugins/hooks/ClickNLoad.py", line 84, in <genexpr>
Okt 20 01:27:57 server pyLoadCore[16811]:     new_ids = set(pack.id for pack in self.pyload.api.getCollector())
Okt 20 01:27:57 server pyLoadCore[16811]: AttributeError: 'PackageData' object has no attribute 'id'

```

**Comment by GammaC0de** [comment]
How did you installed pyLoad? please read #2000

**Comment by DocMAX** [comment]
pacaur -S pyload-git

**Comment by DocMAX** [comment]
Similar to https://github.com/pyload/pyload/issues/2516

**Comment by DocMAX** [comment]
OK that workaround from #2516 "fixed" this. But you need to take care of this.
