### ISSUE TITLE
ulozto hoster - recaptcha

### ISSUE THREAD

**Issue by izderadicka** [pyload/pyload#2633]
From what I have seen, when number of requests to ulozto from  public IP ulozto will start to request reCAPTCHA  (google)   verification. 
Redirection to https://ulozto.cz/limit-exceeded and m this message:
"Byl překročen maximální limit požadavků. Pro pokračování nám potvrď, že nejsi robot."

This is applied to search result and individual files pages.

After verifying recaptcha I'm fine to as long as ulozto session is valid. With new ulozto  session again recpatcha verification is needed. 

This will indeed interfere with pyload plugin, which cannot work then.

Changing IP (different internet connection) will remove recaptcha - so this confirms my assumption that limits are related to public IP.

Does anybody have similar experiences?
Any information how and when recaptcha is actually used in ulozto - what is limit, when it's reset etc.?

**Comment by GammaC0de** [comment]
If you have problems with this plugin, please provide DEBUG log and sample URL.

**Comment by izderadicka** [comment]
Got stuck with char encoding, it's not exactly related but cannot get any ulozto link work due to:
```
28.10.2016 19:15:38 INFO      Download starts: https://ulozto.cz/!2yicpLZr9/perinbaba-pres-multiload-cz-mkv
28.10.2016 19:15:38 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
28.10.2016 19:15:38 DEBUG     HOSTER UlozTo[1]: Plugin version: 1.38
28.10.2016 19:15:38 DEBUG     HOSTER UlozTo[1]: Plugin status: testing
28.10.2016 19:15:38 WARNING   HOSTER UlozTo[1]: Plugin may be unstable
28.10.2016 19:15:38 INFO      HOSTER UlozTo[1]: Grabbing link info...
28.10.2016 19:15:39 WARNING   Download failed: https://ulozto.cz/!2yicpLZr9/perinbaba-pres-multiload-cz-mkv | 'ascii' codec can't encode character u'\u017e' in position 3: ordinal not in range(128)
Traceback (most recent call last):
  File "/data/local/pyload/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/data/local/pyload/pyload/module/plugins/internal/Base.py", line 294, in preprocessing
    return self._process(*args, **kwargs)
  File "/data/local/pyload/pyload/module/plugins/internal/Hoster.py", line 106, in _process
    self._setup()
  File "/data/local/pyload/pyload/module/plugins/internal/Base.py", line 166, in _setup
    self.grab_info()
  File "/data/local/pyload/pyload/module/plugins/internal/Base.py", line 227, in grab_info
    new_info = self.get_info(self.pyfile.url, self.data)
  File "/data/local/pyload/pyload/module/plugins/internal/SimpleHoster.py", line 179, in get_info
    info['name'] = parse_name(name)
  File "/data/local/pyload/pyload/module/plugins/internal/misc.py", line 534, in parse_name
    path  = fixurl(decode(value), unquote=False)
  File "/data/local/pyload/pyload/module/plugins/internal/misc.py", line 471, in fixurl
    url = html_unescape(decode(url).decode('unicode-escape'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u017e' in position 3: ordinal not in range(128)
28.10.2016 19:15:39 DEBUG     Error creating zip file: [Errno 2] No such file or directory: 'tmp/UlozTo'
28.10.2016 19:15:39 INFO      Debug Report written to debug_UlozTo_28-10-2016_19-15-39.txt
28.10.2016 19:15:39 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
28.10.2016 19:15:39 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: https://ulozto.cz/!2yicpLZr9/perinbaba-pres-multiload-cz-mkv (pid:1)
28.10.2016 19:15:39 INFO      ADDON UnSkipOnFail: No duplicates found
28.10.2016 19:15:39 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
28.10.2016 19:15:39 DEBUG     All downloads processed
```

I did have same issues in past, looks like they are not resolved.  
I've tried to completely reinstall from latest git clone, but this issues persists, so cannot really test recaptcha now.

**Comment by GammaC0de** [comment]
@izderadicka There is a known issue with filenames that contains amulets, no sufficent solution yet, hopefully will be fixed in the next major version.

As for the original issue (ulozto hoster - recaptcha), is this issue still exists?
If so, please provide DEBUG log and sample URL.

**Comment by izderadicka** [comment]
I'd like to but cannot get over this issue - I've tried different URLs,  
some with just ascii characters, however problem remains - strange is 
that it always reports same position and characters - are old downloads 
somewhere stored - I've tried to look around but cannot find - deleted 
all config dir, but still same issue.

**Comment by GammaC0de** [comment]
@izderadicka See #2106

**Comment by izderadicka** [comment]
Ulozto hoster seems to be now defunct for all links -   issues is that NAME_PATTERN now always matches to 
```python
{'N': u'Ulo\u017e.to'}  
```
which contains non-ascii character.

Later you do this in parse_name
```python
 path  = fixurl(decode(value), unquote=False)
```

which leads to this 
```python
url = html_unescape(decode(url).decode('unicode-escape'))
```

as url is already unicode decode('unicode-escape') will first try to encode into default encoding ( which is ascii for python 2) and leads to UnicodeEncodingError posted above.

The proposed fix above might work,   but I think it creates even bigger mess in way how unicode in handled there.  Why not just leave unicode as it is for this case - e.g. change parse_name not to use fix_url?

**Comment by izderadicka** [comment]
Now this is the debug:
```
29.10.2016 10:01:51 DEBUG     ADDON ExternalScripts: No script found under folder `package_deleted`
29.10.2016 10:04:51 INFO      Added package deadpoll containing 1 links
29.10.2016 10:04:52 INFO      Download starts: https://ulozto.cz/!5VAhZMb1eIG9/deadpool-cz-dabing-2016-txr-avi
29.10.2016 10:04:52 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
29.10.2016 10:04:52 DEBUG     HOSTER UlozTo[3]: Plugin version: 1.38
29.10.2016 10:04:52 DEBUG     HOSTER UlozTo[3]: Plugin status: testing
29.10.2016 10:04:52 WARNING   HOSTER UlozTo[3]: Plugin may be unstable
29.10.2016 10:04:52 INFO      HOSTER UlozTo[3]: Grabbing link info...
29.10.2016 10:04:53 DEBUG     HOSTER UlozTo[3]: Link info: {'status': 2, 'hash': {}, 'name': 'Ulo?.to', 'url': u'https://ulozto.net/!5VAhZMb1eIG9/deadpool-cz-dabing-2016-txr-avi', 'pattern': {'ID': u'!5VAhZMb1eIG9/deadpool-cz-dabing-2016-txr-avi', 'N': u'Ulo\u017e.to'}, 'size': 0}
29.10.2016 10:04:53 DEBUG     HOSTER UlozTo[3]: Previous link info: {}
29.10.2016 10:04:53 INFO      HOSTER UlozTo[3]: Link name: Ulo?.to
29.10.2016 10:04:53 INFO      HOSTER UlozTo[3]: Link size: N/D
29.10.2016 10:04:53 INFO      HOSTER UlozTo[3]: Link status: online
29.10.2016 10:04:53 INFO      HOSTER UlozTo[3]: Processing url: https://ulozto.cz/!5VAhZMb1eIG9/deadpool-cz-dabing-2016-txr-avi
29.10.2016 10:04:53 INFO      HOSTER UlozTo[3]: Looking for direct download link...
29.10.2016 10:04:53 DEBUG     HOSTER UlozTo[3]: LOAD URL https://ulozto.net/!5VAhZMb1eIG9/deadpool-cz-dabing-2016-txr-avi | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
29.10.2016 10:04:53 INFO      HOSTER UlozTo[3]: Direct download link detected
29.10.2016 10:04:53 INFO      HOSTER UlozTo[3]: Downloading file...
29.10.2016 10:04:53 DEBUG     HOSTER UlozTo[3]: DOWNLOAD URL https://ulozto.net/!5VAhZMb1eIG9/deadpool-cz-dabing-2016-txr-avi | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
29.10.2016 10:04:54 INFO      HOSTER UlozTo[3]: File saved
29.10.2016 10:04:54 INFO      HOSTER UlozTo[3]: Checking download...
29.10.2016 10:04:54 INFO      HOSTER UlozTo[3]: File is OK
29.10.2016 10:04:54 INFO      HOSTER UlozTo[3]: Checking file (with built-in rules)...
29.10.2016 10:04:54 INFO      HOSTER UlozTo[3]: Checking file (with custom rules)...
29.10.2016 10:04:54 INFO      HOSTER UlozTo[3]: Checking for link errors...
29.10.2016 10:04:54 INFO      HOSTER UlozTo[3]: No errors found
29.10.2016 10:04:54 INFO      HOSTER UlozTo[3]: No errors found
29.10.2016 10:04:54 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
29.10.2016 10:04:54 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
29.10.2016 10:04:54 INFO      Download finished: Ulo?.to
29.10.2016 10:04:54 DEBUG     ADDON ExternalScripts: No script found under folder `download_finished`
29.10.2016 10:04:54 INFO      Package finished: deadpoll
29.10.2016 10:04:54 DEBUG     ADDON ExternalScripts: No script found under folder `package_finished`
29.10.2016 10:04:54 DEBUG     ADDON ExtractArchive: Use for extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
29.10.2016 10:04:54 ERROR     ADDON ExtractArchive: [Errno 2] No such file or directory: 'passwords.txt'
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/ivan/tmp/pyload/pyload/module/PluginThread.py", line 459, in run
    self.f(*self.args, **self.kwargs)
  File "/home/ivan/tmp/pyload/pyload/module/plugins/hooks/ExtractArchive.py", line 181, in extract_queued
    if self.extract(packages, thread):  #@NOTE: check only if all gone fine, no failed reporting for now
  File "/home/ivan/tmp/pyload/pyload/module/plugins/hooks/ExtractArchive.py", line 255, in extract
    self.reload_passwords()
  File "/home/ivan/tmp/pyload/pyload/module/plugins/hooks/ExtractArchive.py", line 526, in reload_passwords
    with open(file) as f:
IOError: [Errno 2] No such file or directory: 'passwords.txt'

29.10.2016 10:04:54 INFO      ADDON ExtractArchive: Check package: deadpoll
29.10.2016 10:04:54 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
29.10.2016 10:04:54 INFO      ADDON ExtractArchive: No files found to extract
29.10.2016 10:04:54 DEBUG     All downloads processed
29.10.2016 10:04:54 DEBUG     ADDON ExternalScripts: No script found under folder `all_archives_extracted`
29.10.2016 10:04:54 DEBUG     ADDON ExternalScripts: No script found under folder `all_archives_processed`
29.10.2016 10:04:54 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_finished`
29.10.2016 10:04:54 DEBUG     All downloads finished
```

Download looks like finished, but actually only HTML page containing recapcha is saved instead of the file - see attached zipped
[Ulo?.to.zip](https://github.com/pyload/pyload/files/559829/Ulo.to.zip)


To sum up - my problems now are combination of 3 issues:
1) ulozto hoster is not grabbing correct file name, but always Ulož.to
2) pyload cannot work with non ascii file names
3) ulozto hoster is not hadling properly situation when site requires recaptcha verification  - loading rather html page instead of the file

**Comment by OndrejIT** [comment]
I have same problem...
![re captcha](https://ctrlv.cz/shots/2016/10/29/dqjh.png)

I'm trying to fix...

**Comment by OndrejIT** [comment]
hmm recaptcha plugin not working for me :( ...

**Comment by GammaC0de** [comment]
Why not!?

**Comment by OndrejIT** [comment]
I don't know...
"BadHeader: Bad server response: 400 Bad Request"

**Comment by GammaC0de** [comment]
Is this issue still exist?

**Comment by izderadicka** [comment]
Yes,
I thing ulozto limits are reset monthly,  so right now I do not have 
problems with recaptcha,
however it may appear again if usage is high.
At least some detection of recaptcha and appropriate error message would 
be nice.

I.

**Comment by GammaC0de** [comment]
OK I am closing this then.
If the problem returns, we can reopen this.
