### ISSUE TITLE
Deathbycaptcha broken

### ISSUE THREAD

**Issue by Burnout5151** [pyload/pyload#2746]
As detailed in #2741, Deathbycaptcha stopped working:

```
Traceback (most recent call last):
  File "/home/XXX/pyload/module/CaptchaManager.py", line 69, in handleCaptcha
    plugin.newCaptchaTask(task)

  File "/home/XXX/pyload/module/plugins/internal/Addon.py", line 200, in newCaptchaTask
    return self.captcha_task(task)

  File "/home/XXX/pyload/module/plugins/hooks/DeathByCaptcha.py", line 172, in captcha_task
    self.get_status()

  File "/home/XXX/pyload/module/plugins/hooks/DeathByCaptcha.py", line 123, in get_status
    res = self.api_response("status", False)

  File "/home/XXX/pyload/module/plugins/hooks/DeathByCaptcha.py", line 81, in api_response
    req=req)

  File "/home/XXX/pyload/module/plugins/internal/Plugin.py", line 200, in load
    req.http.c.setopt(pycurl.MAXREDIRS, redirect)

AttributeError: HTTPRequest instance has no attribute 'http'
```

Happens with every download, e.g.
http://www.datafile.com/d/TWpVek16RXpOREUF9/test1.txt

**Comment by Burnout5151** [comment]
That was quick! :+1:
