### ISSUE TITLE
Downloads not working after update

### ISSUE THREAD

**Issue by pfloosy** [pyload/pyload#2759]
Hi,

pyload was working like a charm till yesterday. Suddenly it stops working. I have tried to get the newest version from github, but it shows the same error: pycurl error 23: Failed writing body (0 != 1440)
Can some please help me out?

Thanks!

 
`02.03.2017 08:38:50 INFO      HOSTER UploadedTo[6]: Processing url: http://ul.to/pacc5fi5
02.03.2017 08:38:50 INFO      HOSTER UploadedTo[6]: Looking for direct download link...
02.03.2017 08:38:50 DEBUG     HOSTER UploadedTo[6]: LOAD URL http://uploaded.net/file/pacc5fi5 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
02.03.2017 08:38:50 INFO      HOSTER UploadedTo[6]: Direct download link not found
02.03.2017 08:38:50 DEBUG     HOSTER UploadedTo[6]: LOAD URL http://uploaded.net/file/pacc5fi5 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
Traceback (most recent call last):
  File "/opt/pyload_new/pyload/module/network/HTTPRequest.py", line 279, in write
    raise Exception("Loaded Url exceeded limit")
Exception: Loaded Url exceeded limit
02.03.2017 08:38:51 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
02.03.2017 08:38:51 DEBUG     pycurl exception 23: Failed writing body (0 != 1440)
02.03.2017 08:38:51 ERROR     pycurl error 23: Failed writing body (0 != 1440)
Traceback (most recent call last):
  File "/opt/pyload_new/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/opt/pyload_new/pyload/module/plugins/internal/Base.py", line 289, in preprocessing
    return self._process(*args, **kwargs)
  File "/opt/pyload_new/pyload/module/plugins/internal/Hoster.py", line 112, in _process
    self.process(self.pyfile)
  File "/opt/pyload_new/pyload/module/plugins/internal/SimpleHoster.py", line 277, in process
    self._preload()
  File "/opt/pyload_new/pyload/module/plugins/internal/SimpleHoster.py", line 256, in _preload
    decode=self.TEXT_ENCODING)
  File "/opt/pyload_new/pyload/module/plugins/internal/Base.py", line 488, in load
    return Plugin.load(self, *args, **kwargs)
  File "/opt/pyload_new/pyload/module/plugins/internal/Plugin.py", line 215, in load
    decode is True)  # @TODO: Fix network multipart in 0.4.10
  File "/opt/pyload_new/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/opt/pyload_new/pyload/module/network/HTTPRequest.py", line 203, in load
    self.c.perform()
error: (23, 'Failed writing body (0 != 1440)')
02.03.2017 08:38:51 INFO      Debug Report written to debug_UploadedTo_02-03-2017_08-38-51.zip
02.03.2017 08:38:51 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: eELLCeaZoAj2gFrbfRM1JvRvQ.part06.rar (pid:1)
02.03.2017 08:38:51 INFO      ADDON UnSkipOnFail: No duplicates found
02.03.2017 08:38:51 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
`

**Comment by geronimoronin** [comment]
look here #2756
