### ISSUE TITLE
UploadedTo Download not working "KeyError: 'ID'"

### ISSUE THREAD

**Issue by Lalarian** [pyload/pyload#2763]
Hello! Since the recent update I had this bug:
https://github.com/pyload/pyload/issues/2756

I manually applied the patch from there, and the module related bug vanished, but I still can't download from UploadedTo since:

TRACEBACK:
 Traceback (most recent call last):
  File "/opt/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/opt/var/pyload/userplugins/internal/Base.py", line 289, in preprocessing
    return self._process(*args, **kwargs)
  File "/opt/var/pyload/userplugins/internal/Hoster.py", line 112, in _process
    self.process(self.pyfile)
  File "/opt/var/pyload/userplugins/internal/SimpleHoster.py", line 292, in process
    self.handle_free(pyfile)
  File "/opt/var/pyload/userplugins/hoster/UploadedTo.py", line 86, in handle_free
    self.data = self.load("http://uploaded.net/io/ticket/captcha/%s" % self.info['pattern']['ID'],
KeyError: 'ID'

So instead of an error it only says "ID".

I have also tried deleting pyload folder and redownloading from git, but it wouldn't change.

I have the whole debug zip file here, please tell me if you need something from inside this.

**Comment by Lalarian** [comment]
I have seen the issues regarding Python 2.5 problems. But I got Python 2.7.13 and this also is, what pyload is reporting.

**Comment by Lalarian** [comment]
I have seen the issues regarding Python 2.5 problems. But I got Python 2.7.13 and this also is, what pyload is reporting.

**Comment by Lalarian** [comment]
Working fine again.
Thank you very much for your work on pyload, GammaC0de!
