### ISSUE TITLE
various problems after autoupdate

### ISSUE THREAD

**Issue by Schlunze** [pyload/pyload#2765]
Hello,

after autoupdate various problems occured. Here some further information. Thanks in advance.

Traceback (most recent call last):
File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/opt/pyload/module/web/utils.py", line 113, in _view
return func(*args, **kwargs)
File "/opt/pyload/module/web/pyload_app.py", line 256, in config
accs = PYLOAD.getAccounts(False)
File "/opt/pyload/module/Api.py", line 875, in getAccounts
accs = self.core.accountManager.getAccountInfos(False, refresh)
File "/opt/pyload/module/utils.py", line 165, in new
return func(*args)
File "/opt/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
p = self.getAccountPlugin(p)
File "/opt/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

Debug output:
02.03.2017 14:58:02 INFO      starte pyLoad 0.4.9
02.03.2017 14:58:02 INFO      Benutze Home-Verzeichnis: /home/oliver/.pyload
02.03.2017 14:58:02 DEBUG     Deleting old pidfile pyload.pid
02.03.2017 14:58:02 DEBUG     Remote activated: True
02.03.2017 14:58:02 DEBUG     created index of plugins
02.03.2017 14:58:02 DEBUG     Redirected import module.plugins.hooks.MergeFiles -> userplugins.hooks.MergeFiles
02.03.2017 14:58:03 ERROR     Fehler beim importieren von MergeFiles: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/PluginManager.py", line 320, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/oliver/.pyload/userplugins/hooks/MergeFiles.py", line 8, in <module>
    from ..internal.Addon import Addon
  File "/home/oliver/.pyload/userplugins/internal/Addon.py", line 6, in <module>
    from .Plugin import Plugin
  File "/home/oliver/.pyload/userplugins/internal/Plugin.py", line 11, in <module>
    from ..Plugin import SkipDownload as Skip
ImportError: No module named Plugin
02.03.2017 14:58:03 DEBUG     Redirected import module.plugins.hooks.EventMapper -> userplugins.hooks.EventMapper
02.03.2017 14:58:03 ERROR     Fehler beim importieren von EventMapper: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/PluginManager.py", line 320, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/oliver/.pyload/userplugins/hooks/EventMapper.py", line 3, in <module>
    from ..internal.Addon import Addon
  File "/home/oliver/.pyload/userplugins/internal/Addon.py", line 6, in <module>
    from .Plugin import Plugin
  File "/home/oliver/.pyload/userplugins/internal/Plugin.py", line 11, in <module>
    from ..Plugin import SkipDownload as Skip
ImportError: No module named Plugin
02.03.2017 14:58:03 DEBUG     Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
02.03.2017 14:58:03 ERROR     Fehler beim importieren von ExternalScripts: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/PluginManager.py", line 320, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/oliver/.pyload/userplugins/hooks/ExternalScripts.py", line 6, in <module>
    from ..internal.Addon import Addon
  File "/home/oliver/.pyload/userplugins/internal/Addon.py", line 6, in <module>
    from .Plugin import Plugin
  File "/home/oliver/.pyload/userplugins/internal/Plugin.py", line 11, in <module>
    from ..Plugin import SkipDownload as Skip
ImportError: No module named Plugin
02.03.2017 14:58:03 DEBUG     Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
02.03.2017 14:58:03 ERROR     Fehler beim importieren von UnSkipOnFail: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/PluginManager.py", line 320, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/oliver/.pyload/userplugins/hooks/UnSkipOnFail.py", line 5, in <module>
    from ..internal.Addon import Addon
  File "/home/oliver/.pyload/userplugins/internal/Addon.py", line 6, in <module>
    from .Plugin import Plugin
  File "/home/oliver/.pyload/userplugins/internal/Plugin.py", line 11, in <module>
    from ..Plugin import SkipDownload as Skip
ImportError: No module named Plugin
02.03.2017 14:58:03 DEBUG     Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
02.03.2017 14:58:03 ERROR     Fehler beim importieren von ExtractArchive: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/PluginManager.py", line 320, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/oliver/.pyload/userplugins/hooks/ExtractArchive.py", line 8, in <module>
    from ..internal.Addon import Addon
  File "/home/oliver/.pyload/userplugins/internal/Addon.py", line 6, in <module>
    from .Plugin import Plugin
  File "/home/oliver/.pyload/userplugins/internal/Plugin.py", line 11, in <module>
    from ..Plugin import SkipDownload as Skip
ImportError: No module named Plugin
02.03.2017 14:58:03 DEBUG     Redirected import module.plugins.hooks.XFileSharing -> userplugins.hooks.XFileSharing
02.03.2017 14:58:03 ERROR     Fehler beim importieren von XFileSharing: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/PluginManager.py", line 320, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/oliver/.pyload/userplugins/hooks/XFileSharing.py", line 6, in <module>
    from ..internal.Addon import Addon
  File "/home/oliver/.pyload/userplugins/internal/Addon.py", line 6, in <module>
    from .Plugin import Plugin
  File "/home/oliver/.pyload/userplugins/internal/Plugin.py", line 11, in <module>
    from ..Plugin import SkipDownload as Skip
ImportError: No module named Plugin
02.03.2017 14:58:03 DEBUG     Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
02.03.2017 14:58:03 ERROR     Fehler beim importieren von UpdateManager: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/PluginManager.py", line 320, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/oliver/.pyload/userplugins/hooks/UpdateManager.py", line 11, in <module>
    from ..internal.Addon import Addon
  File "/home/oliver/.pyload/userplugins/internal/Addon.py", line 6, in <module>
    from .Plugin import Plugin
  File "/home/oliver/.pyload/userplugins/internal/Plugin.py", line 11, in <module>
    from ..Plugin import SkipDownload as Skip
ImportError: No module named Plugin
02.03.2017 14:58:03 DEBUG     Redirected import module.plugins.hooks.ClickNLoad -> userplugins.hooks.ClickNLoad
02.03.2017 14:58:03 ERROR     Fehler beim importieren von ClickNLoad: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/PluginManager.py", line 320, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/oliver/.pyload/userplugins/hooks/ClickNLoad.py", line 7, in <module>
    from ..internal.Addon import Addon
  File "/home/oliver/.pyload/userplugins/internal/Addon.py", line 6, in <module>
    from .Plugin import Plugin
  File "/home/oliver/.pyload/userplugins/internal/Plugin.py", line 11, in <module>
    from ..Plugin import SkipDownload as Skip
ImportError: No module named Plugin
02.03.2017 14:58:03 DEBUG     Redirected import module.plugins.hooks.UserAgentSwitcher -> userplugins.hooks.UserAgentSwitcher
02.03.2017 14:58:03 ERROR     Fehler beim importieren von UserAgentSwitcher: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/PluginManager.py", line 320, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/oliver/.pyload/userplugins/hooks/UserAgentSwitcher.py", line 6, in <module>
    from ..internal.Addon import Addon
  File "/home/oliver/.pyload/userplugins/internal/Addon.py", line 6, in <module>
    from .Plugin import Plugin
  File "/home/oliver/.pyload/userplugins/internal/Plugin.py", line 11, in <module>
    from ..Plugin import SkipDownload as Skip
ImportError: No module named Plugin
02.03.2017 14:58:03 INFO      Aktivierte Plugins: 
02.03.2017 14:58:03 INFO      Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
02.03.2017 14:58:03 INFO      Downloadzeit: True
02.03.2017 14:58:03 INFO      Starte ThriftBackend: 0.0.0.0:7227
02.03.2017 14:58:03 INFO      Starting builtin webserver: 127.0.0.1:8000
02.03.2017 14:58:03 INFO      Free space: 64.26 GiB
02.03.2017 14:58:03 INFO      Activating Accounts...
02.03.2017 14:58:03 DEBUG     Redirected import module.plugins.accounts.ShareonlineBiz -> userplugins.accounts.ShareonlineBiz
02.03.2017 14:58:03 ERROR     Error importing ShareonlineBiz: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/PluginManager.py", line 320, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/oliver/.pyload/userplugins/accounts/ShareonlineBiz.py", line 4, in <module>
    from ..internal.Account import Account
  File "/home/oliver/.pyload/userplugins/internal/Account.py", line 9, in <module>
    from .Plugin import Plugin, Skip
  File "/home/oliver/.pyload/userplugins/internal/Plugin.py", line 11, in <module>
    from ..Plugin import SkipDownload as Skip
ImportError: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/pyLoadCore.py", line 667, in <module>
    main()
  File "/opt/pyload/pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "/opt/pyload/pyLoadCore.py", line 433, in start
    self.accountManager.getAccountInfos()
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
    p = self.getAccountPlugin(p)
  File "/opt/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable
02.03.2017 14:58:05 DEBUG     Redirected import module.plugins.accounts.ShareonlineBiz -> userplugins.accounts.ShareonlineBiz
02.03.2017 14:58:05 ERROR     Error importing ShareonlineBiz: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/PluginManager.py", line 320, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/oliver/.pyload/userplugins/accounts/ShareonlineBiz.py", line 4, in <module>
    from ..internal.Account import Account
  File "/home/oliver/.pyload/userplugins/internal/Account.py", line 9, in <module>
    from .Plugin import Plugin, Skip
  File "/home/oliver/.pyload/userplugins/internal/Plugin.py", line 11, in <module>
    from ..Plugin import SkipDownload as Skip
ImportError: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/opt/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/opt/pyload/module/web/pyload_app.py", line 256, in config
    accs = PYLOAD.getAccounts(False)
  File "/opt/pyload/module/Api.py", line 875, in getAccounts
    accs = self.core.accountManager.getAccountInfos(False, refresh)
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
    p = self.getAccountPlugin(p)
  File "/opt/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable
An error occured while processing the request.
Traceback (most recent call last):
  File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/opt/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/opt/pyload/module/web/pyload_app.py", line 256, in config
    accs = PYLOAD.getAccounts(False)
  File "/opt/pyload/module/Api.py", line 875, in getAccounts
    accs = self.core.accountManager.getAccountInfos(False, refresh)
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
    p = self.getAccountPlugin(p)
  File "/opt/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

02.03.2017 15:01:34 DEBUG     Redirected import module.plugins.accounts.ShareonlineBiz -> userplugins.accounts.ShareonlineBiz
02.03.2017 15:01:34 ERROR     Error importing ShareonlineBiz: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/PluginManager.py", line 320, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/oliver/.pyload/userplugins/accounts/ShareonlineBiz.py", line 4, in <module>
    from ..internal.Account import Account
  File "/home/oliver/.pyload/userplugins/internal/Account.py", line 9, in <module>
    from .Plugin import Plugin, Skip
  File "/home/oliver/.pyload/userplugins/internal/Plugin.py", line 11, in <module>
    from ..Plugin import SkipDownload as Skip
ImportError: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/opt/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/opt/pyload/module/web/pyload_app.py", line 256, in config
    accs = PYLOAD.getAccounts(False)
  File "/opt/pyload/module/Api.py", line 875, in getAccounts
    accs = self.core.accountManager.getAccountInfos(False, refresh)
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
    p = self.getAccountPlugin(p)
  File "/opt/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable
An error occured while processing the request.
Traceback (most recent call last):
  File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/opt/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/opt/pyload/module/web/pyload_app.py", line 256, in config
    accs = PYLOAD.getAccounts(False)
  File "/opt/pyload/module/Api.py", line 875, in getAccounts
    accs = self.core.accountManager.getAccountInfos(False, refresh)
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
    p = self.getAccountPlugin(p)
  File "/opt/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

**Comment by geronimoronin** [comment]
Sieh #2758

**Comment by Velociraptor85** [comment]
@Schlunze yap like @geronimoronin said try reinstalling the pyload ^^ and please report back if it worked and close the issue 👍

**Comment by Schlunze** [comment]
tx @ geronimoronin.
