### ISSUE TITLE
fail to manual install

### ISSUE THREAD

**Issue by audren49** [pyload/pyload#2790]
I am trying to install ppyload manually from current master branch. I'm on Raspberry jessie

I get this error when running "`sudo python setup.py`" :

Traceback (most recent call last):
  File "setup.py", line 216, in <module>
    setup(**SETUP_MAP)
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 262, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 287, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 603, in resolve
    requirements = list(requirements)[::-1]
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2697, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ("Expected ',' or end-of-list in", 'sphinx<=1.4;python_version=="2.6" or python_version=="3.3"', 'at', ';python_version=="2.6" or python_version=="3.3"')

Any ideas please?

**Comment by GammaC0de** [comment]
@audren49 "master" branch is beta and "stable" branch is the production.

Read https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(RaspberryPi) for installation instruction for Raspberry Pi.

**Comment by audren49** [comment]
I know that but stable branch has not been updated since ages... If I am not mistaken. 
Stable branch does not support some updated plugins & accounts management that I need. 

So, does your answer means current master branch is broken? It worked well when pyloadCore file was still here. 

Thank you

**Comment by audren49** [comment]
Got my answer elsewhere. No worries, thank you

**Comment by sclausen** [comment]
@audren49 could you please share the answer you found?

**Comment by GammaC0de** [comment]
@audren49 Please open a new issue explaining your problem.
