### ISSUE TITLE
The manual installation is completely broken

### ISSUE THREAD

**Issue by majuss** [pyload/pyload#2808]
In the file: setup.py
join takes only 1 argument 2 where given:
`LONG_DESC='\n\n'.join(io.open("README.md").read(), io.open("HISTORY.md").read())
`
And then if you try `sudo python setup.py install`the requirements for the html5 libs are broken (.eggs/bleach-2.0.0-py2.7.egg/EGG-INFO/requires.txt): should be `html5lib>=0.999` not with million 9's more. 

After that the install runs through but then it throws this error if I try to use it:

`pyload
Traceback (most recent call last):
  File "/usr/local/bin/pyload", line 6, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 3019, in <module>
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 3003, in _call_aside
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 655, in _build_master
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 963, in require
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 849, in resolve
pkg_resources.DistributionNotFound: The 'pyload.utils' distribution was not found and is required by pyload.core`

Under latest raspbian all dependencies are in place.

**Comment by GammaC0de** [comment]
Please read #2000 for installation instructions.
