### ISSUE TITLE
Mega.co.nz impossibe to add a premium account

### ISSUE THREAD

**Issue by ingjcgonzalez** [pyload/pyload#2825]
I recently buy a premium account on Mega, so, I try to add to pyLoad. But the Log show me this error:
```
ERROR	ACCOUNT MegaCoNz: Could not login user `ing*******` | must be long, not int
INFO	ACCOUNT MegaCoNz: Login user `ing*******`...
INFO	ACCOUNT MegaCoNz: Adding user `ing*******`...
INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
INFO	ADDON UpdateManager: All plugins are up to date!
INFO	ADDON UpdateManager: pyLoad is up to date!
INFO	pyLoad is up and running
```
I tried to find on the files the way to fix it, but I can't. What should I do to fix it?

**Comment by GammaC0de** [comment]
@ingjcgonzalez
1. Stop pyload
2. Login to the console (putty?)
3. Start pyload with `python pyLoadCore.py -d`
4. Go to pyLoad's WebUI adn add the account
5. Copy all the log from the console and paste here (don't forget to surround it with triple quotes \`\`\`)

**Comment by ingjcgonzalez** [comment]
I Just did it, this is what the debug show me:

```19.04.2017 10:17:44 DEBUG     ADDON ExtractArchive: Found UnRar 5.00 | Found SevenZip 16.02 | Found UnZip 2.7.5 | Found UnTar 2.7.5
19.04.2017 10:17:44 INFO      ADDON XFileSharing: Auto-discover new hosters
19.04.2017 10:17:44 DEBUG     ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com|cramit\.in|easybytez\.com|exashare\.com|filejoker\.net|fileom\.com|filerio\.com|hugefiles\.net|junocloud\.me|movreel\.com|nosupload\.com|novafile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|streamcloud\.eu|tusfiles\.net|uploadrocket\.net|uptobox\.com|vidplay\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
19.04.2017 10:17:44 INFO      ADDON XFileSharing: Auto-discover new crypters
19.04.2017 10:17:44 DEBUG     ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
19.04.2017 10:17:44 INFO      pyLoad is up and running
19.04.2017 10:17:44 INFO      ADDON UpdateManager: pyLoad is up to date!
19.04.2017 10:17:44 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
19.04.2017 10:17:44 DEBUG     ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
19.04.2017 10:17:44 INFO      ADDON UpdateManager: All plugins are up to date!
19.04.2017 10:17:50 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
19.04.2017 10:18:19 INFO      ACCOUNT MegaCoNz: Adding user `ing*******`...
19.04.2017 10:18:19 DEBUG     ACCOUNT MegaCoNz: Reached login timeout for user `ing*******`
19.04.2017 10:18:19 INFO      ACCOUNT MegaCoNz: Login user `ing*******`...
19.04.2017 10:18:21 DEBUG     ACCOUNT MegaCoNz: LOAD URL https://eu.api.mega.co.nz/cs | redirect=True | cookies=True | get={'id': 3476715567} | req=None | decode=True | multipart=False | post=[{"a": "us", "user": "ing*******", "uh": "gpTq66wi-oE="}] | ref=True | just_header=False
19.04.2017 10:18:22 DEBUG     ACCOUNT MegaCoNz: Api Response: [{"csid":"CAAxEcd88MtX8Ihic3o7Gb0Td_8iLdmuCb9g5-8P_YsH6-UA-wcpbvR6SMohT7xtbnkns4mHzjI6x9Hkfdbs4znkEFQFZwiTaXqWTPhIhvkG2Xmc9yV4anJ8ppgLwU-Mh4cG1f9gx-9GNvJ6JWL_xuAlpKRnVsMSS9rmRkhlI4G6I7P8leu-KDjz5AbRxMlvcUYZi1BQAbjvMlBy4uD2C5I4G2mAH37WFDGo8fmb9NpffIvkZjF6mWpxOBNCw1qRsvDkLCLfAfEN50klEYjJP022D2WHmwXrzKxO4-5_Bki5E0SeyVLBobMV4n0yOlnfmcFSQHu9RJzYGAr_adA4L_fa","privk":"s9jH-sGptn9K5fnr8B7ndqXYFnBdmz-qMuO1nf7H1LMCdVMscytBnh0xwPu-E8GXofrrlK7ZWBvMRf8UWVhS43rIZNTpIqqxOESIoLLUxtfNOO98yiM_ETdOuvIsj46N4zJc-ZTJ5LkYpG9d5qijQpJKzLkp3T6tnhmOA0ZkGh6NEpoJxl2nJzyfRLmc-LQFhnzu9Ip5pcVAU9E3twE6rABM1n12PPpPj-HqnfZtuSYJHbSxaS7i_mE0VIhmzHWjvBoL8OVEaTjWuSHj0QG-1-3Tzqn5o-Smukh4nJ5bARhMfixodIGSkdhqk_VpPC61gQ40VLVkK7whM2PNScyAC7vBNf7XbLJJrtjWzLrtckWy1JVid-jt8G0zpi4EkBserKOVlSnTRRu_jFn6y2QVXOTT2n8MjCigTgVQ_RJdvgA7m1WZNjh78G89AX-011KRW7au5OTrS918VUSbwfzm_z1HGNf7elayIJl4_JnYUYmrl6FvLJW0vQHv52CgYsEwVz8PXfcDwNSCVFkFBZ-JDkOpp4qlGMhngwsUfdBz_eL7t6TetrrWD2Zb7kek5hLK4dz3EfnjN4Zo1OqGY4R_dzSD1a3xFVIvDTgoC5b9vRgBnZ-38sKPPI3LdTyuCzue4slii4tKqV_gsEil5T9NoS4hhofTR_dMr0WZ84iBlXI2tu_LBgpY1_tJolJw6E0D1F-mSMnKiFQ5q46qM61HbG2vrGwhA3WM4RVeFBiCv6WZVCrCtCxQqFms9AR0YWov4VUIqiu_hlL3vh79dT0jXJKv7EU6quSZd_nXHPqp6-uKpqtw8ALL03WWmCHjs4fVxFH13k63Yc7LgWE-3VSKuRhPIELdgqR1l1KJc45tc_w","k":"uSnHGnm8pOuBM779OrfhBg","u":"CaAXxZ5MqQs"}]
19.04.2017 10:18:22 ERROR     ACCOUNT MegaCoNz: Could not login user `ing*******` | must be long, not int```

Plus, I read another issue #1592 on beatgen comment, to try to fix it adding manually the account. Now I add the premium accout and show me this on the webGUI
![mega](https://cloud.githubusercontent.com/assets/13559202/25188420/98605356-24eb-11e7-80c2-143eb57a4c4c.jpg)

**Comment by GammaC0de** [comment]
Sorry for late response but your log is not enough,
You need to stop pyload and start is from the console with the command `python pyLoadCore.py -d` then re-add the accound and post the log from the console, not the WebUI.
And please don't forget to surround it with triple quotes (\`\`\`)

**Comment by ingjcgonzalez** [comment]
I understand. That's what the console show me up. But I'll do it again right now.

And thanx for ur support

**Comment by GammaC0de** [comment]
The most important thing is the exception information (which is not saved to the log file but is displayed to the console).

**Comment by ingjcgonzalez** [comment]
This is the log from debug mode:
```

**Comment by GammaC0de** [comment]
Can you edit [<userplugins_folder>/module/plugins/accounts/MegaCoNz.py line 75](https://github.com/pyload/pyload/blob/stable/module/plugins/accounts/MegaCoNz.py#L75) and change it from `rsa_private_key = [0, 0, 0, 0]` to `rsa_private_key = [long(0), long(0), long(0), long(0)]`?

Then retry the same steps as before and post the log again?

**Comment by ingjcgonzalez** [comment]
Ok, right the way! I let you know

**Comment by ingjcgonzalez** [comment]
Nothing yet
```
22.04.2017 18:17:17 INFO      Comenzando pyLoad 0.4.9
22.04.2017 18:17:17 INFO      Usando directorio de inicio: /etc/pyload/.pyload
22.04.2017 18:17:17 DEBUG     Remote activated: True
22.04.2017 18:17:18 DEBUG     created index of plugins
22.04.2017 18:17:19 INFO      Plugins activos: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
22.04.2017 18:17:19 INFO      Plugins desactivados: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
22.04.2017 18:17:19 INFO      Tiempo de descarga: True
22.04.2017 18:17:19 INFO      Iniciando ThriftBackend: 0.0.0.0:7227
22.04.2017 18:17:21 INFO      Starting builtin webserver: 192.168.1.1:8001
22.04.2017 18:17:21 INFO      Free space: 908.69 GiB
22.04.2017 18:17:21 INFO      Activating Accounts...
22.04.2017 18:17:21 INFO      Activating Plugins...
22.04.2017 18:17:21 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
22.04.2017 18:17:21 DEBUG     ADDON ExternalScripts: No script found under folder `pyload_start`
22.04.2017 18:17:22 DEBUG     ADDON ExtractArchive: Found UnRar 5.00 | Found SevenZip 16.02 | Found UnZip 2.7.5 | Found UnTar 2.7.5
22.04.2017 18:17:22 INFO      ADDON XFileSharing: Auto-discover new hosters
22.04.2017 18:17:22 DEBUG     ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com|cramit\.in|easybytez\.com|exashare\.com|filejoker\.net|fileom\.com|filerio\.com|hugefiles\.net|junocloud\.me|movreel\.com|nosupload\.com|novafile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|streamcloud\.eu|tusfiles\.net|uploadrocket\.net|uptobox\.com|vidplay\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
22.04.2017 18:17:23 INFO      ADDON UpdateManager: pyLoad is up to date!
22.04.2017 18:17:23 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
22.04.2017 18:17:23 INFO      ADDON XFileSharing: Auto-discover new crypters
22.04.2017 18:17:23 DEBUG     ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
22.04.2017 18:17:23 INFO      pyLoad is up and running
22.04.2017 18:17:23 DEBUG     ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
22.04.2017 18:17:23 INFO      ADDON UpdateManager: New version of plugin: HOSTER RealdebridCom (v0.75 -> v0.76)
22.04.2017 18:17:23 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/pyload/cb4a916/module/plugins/hoster/RealdebridCom.py | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x2f09258> | decode=False | multipart=False | post={} | ref=True | just_header=False
22.04.2017 18:17:24 INFO      ADDON UpdateManager: *** Plugins updated ***
22.04.2017 18:17:24 DEBUG     Request reload of plugins: [(u'hoster', u'RealdebridCom')]
22.04.2017 18:17:24 DEBUG     Reloading RealdebridCom
22.04.2017 18:17:29 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
22.04.2017 18:18:09 INFO      ACCOUNT MegaCoNz: Adding user `ing*******`...
22.04.2017 18:18:09 DEBUG     ACCOUNT MegaCoNz: Reached login timeout for user `ing*******`
22.04.2017 18:18:09 INFO      ACCOUNT MegaCoNz: Login user `ing*******`...
22.04.2017 18:18:11 DEBUG     ACCOUNT MegaCoNz: LOAD URL https://eu.api.mega.co.nz/cs | redirect=True | cookies=True | get={'id': 2147989281} | req=None | decode=True | multipart=False | post=[{"a": "us", "user": "ing*******", "uh": "gpTq66wi-oE="}] | ref=True | just_header=False
22.04.2017 18:18:14 DEBUG     ACCOUNT MegaCoNz: Api Response: [{"csid":"CAAoR84oscLIFcarhi9ADjZdQ8LkIhCpGMgmU_shpjqLCwYi7Ku_eDgNQWN4coa2fZuZzJUfacmOCut3EKBtyqeNiKSL3vNS56Fd5nDTU72t8rlCLouO0S2KpPLqsUDOo-0S_NE-zowr-ZR2JW11-XaM6GzXqVnn7ifevTZnywMg8e42tQpEic8ZzKv5q6vdFmHtno43Y6gzHmLBqNSJnFZRRYk-mhnn9tYPY_h58kvkQvvZehMkHHpZOGUqnnGl30ccT8zoPPmjW9xqTOsoH-RVLsyAge_RmhyPIzoFlZ3P5lnSHaV2oJrpDvgelCrsRaeKQm-DmoMyA8l4ekx9EbBq","privk":"s9jH-sGptn9K5fnr8B7ndqXYFnBdmz-qMuO1nf7H1LMCdVMscytBnh0xwPu-E8GXofrrlK7ZWBvMRf8UWVhS43rIZNTpIqqxOESIoLLUxtfNOO98yiM_ETdOuvIsj46N4zJc-ZTJ5LkYpG9d5qijQpJKzLkp3T6tnhmOA0ZkGh6NEpoJxl2nJzyfRLmc-LQFhnzu9Ip5pcVAU9E3twE6rABM1n12PPpPj-HqnfZtuSYJHbSxaS7i_mE0VIhmzHWjvBoL8OVEaTjWuSHj0QG-1-3Tzqn5o-Smukh4nJ5bARhMfixodIGSkdhqk_VpPC61gQ40VLVkK7whM2PNScyAC7vBNf7XbLJJrtjWzLrtckWy1JVid-jt8G0zpi4EkBserKOVlSnTRRu_jFn6y2QVXOTT2n8MjCigTgVQ_RJdvgA7m1WZNjh78G89AX-011KRW7au5OTrS918VUSbwfzm_z1HGNf7elayIJl4_JnYUYmrl6FvLJW0vQHv52CgYsEwVz8PXfcDwNSCVFkFBZ-JDkOpp4qlGMhngwsUfdBz_eL7t6TetrrWD2Zb7kek5hLK4dz3EfnjN4Zo1OqGY4R_dzSD1a3xFVIvDTgoC5b9vRgBnZ-38sKPPI3LdTyuCzue4slii4tKqV_gsEil5T9NoS4hhofTR_dMr0WZ84iBlXI2tu_LBgpY1_tJolJw6E0D1F-mSMnKiFQ5q46qM61HbG2vrGwhA3WM4RVeFBiCv6WZVCrCtCxQqFms9AR0YWov4VUIqiu_hlL3vh79dT0jXJKv7EU6quSZd_nXHPqp6-uKpqtw8ALL03WWmCHjs4fVxFH13k63Yc7LgWE-3VSKuRhPIELdgqR1l1KJc45tc_w","k":"uSnHGnm8pOuBM779OrfhBg","u":"CaAXxZ5MqQs"}]
22.04.2017 18:18:14 ERROR     ACCOUNT MegaCoNz: Could not login user `ing*******` | must be long, not int
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 784, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/etc/pyload/module/web/ServerThread.py", line 75, in run
    self.start_builtin()
  File "/etc/pyload/module/web/ServerThread.py", line 83, in start_builtin
    webinterface.run_simple(host=self.host, port=self.port)
  File "/etc/pyload/module/web/webinterface.py", line 129, in run_simple
    run(app=web, host=host, port=port, quiet=True)
  File "/etc/pyload/module/lib/bottle.py", line 2383, in run
    server.run(app)
  File "/etc/pyload/module/lib/bottle.py", line 2081, in run
    srv.serve_forever()
  File "/usr/lib64/python2.7/SocketServer.py", line 238, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib64/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib64/python2.7/wsgiref/simple_server.py", line 124, in handle
    handler.run(self.server.get_app())
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/etc/pyload/module/web/middlewares.py", line 53, in __call__
    response.gzip_start_response)
  File "/etc/pyload/module/web/middlewares.py", line 17, in __call__
    return self.app(e, h)
  File "/usr/lib/python2.7/site-packages/beaker/middleware.py", line 152, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/etc/pyload/module/lib/bottle.py", line 843, in __call__
    return self.wsgi(environ, start_response)
  File "/etc/pyload/module/lib/bottle.py", line 820, in wsgi
    out = self._cast(self._handle(environ), request, response)
  File "/etc/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/etc/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/etc/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/etc/pyload/module/web/json_app.py", line 276, in add_account
    PYLOAD.updateAccount(type, login, password)
  File "/etc/pyload/module/Api.py", line 894, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "/etc/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/etc/pyload/module/plugins/AccountManager.py", line 149, in updateAccount
    updated = p.updateAccounts(user, password, options)
  File "/etc/pyload/module/plugins/internal/misc.py", line 228, in new
    return fn(*args, **kwargs)
  File "/etc/pyload/module/plugins/internal/Account.py", line 334, in updateAccounts
    self.add(user, password, options)
  File "/etc/pyload/module/plugins/internal/misc.py", line 228, in new
    return fn(*args, **kwargs)
  File "/etc/pyload/module/plugins/internal/Account.py", line 311, in add
    result = u['plugin'].choose(user)
  File "/etc/pyload/module/plugins/internal/misc.py", line 228, in new
    return fn(*args, **kwargs)
  File "/etc/pyload/module/plugins/internal/Account.py", line 428, in choose
    self.relogin()
  File "/etc/pyload/module/plugins/internal/Account.py", line 175, in relogin
    return self.login()
  File "/etc/pyload/module/plugins/internal/Account.py", line 116, in login
    self.info['data'])
  File "/etc/pyload/module/plugins/accounts/MegaCoNz.py", line 90, in signin
    rsa_private_key[1]))
  File "/usr/lib64/python2.7/site-packages/Crypto/PublicKey/RSA.py", line 539, in construct
    key = self._math.rsa_construct(*tup)
TypeError: must be long, not int
```
What should I do with the changes I did #1582? Should I let it or undo the changes?

**Comment by GammaC0de** [comment]
Is it possible that you will change your password to a temporary password and send the user and password to nitzo2001 at yahoo dot com?
Otherwise it would take longer if you make changes and post the log and then I would answer...

I don't think that #1582 has nothing to do with this issue.

**Comment by ingjcgonzalez** [comment]
I already send it, please confirm if  you get it.

**Comment by GammaC0de** [comment]
👍 Got it.

**Comment by GammaC0de** [comment]
Something wrong with the login info, I have sent you an email..

**Comment by ingjcgonzalez** [comment]
Done, I wrote you back

**Comment by GammaC0de** [comment]
Account plugin updated and downloads are working (tested with 10GB link).
