### ISSUE TITLE
Direct Download error on many Hosts

### ISSUE THREAD

**Issue by klode82** [pyload/pyload#2839]
I have pyload 0.4.9 installed on my Pine64 (ARM PC Board with Ubuntu Xenial 16.04). It works fine, but after some days, I got error on Direct Download not found:. Here the log in debug mode:

```06.05.2017 06:41:43 INFO      HOSTER BigfileTo[274]: Grabbing link info...
06.05.2017 06:41:44 DEBUG     HOSTER BigfileTo[274]: Link info: {'status': 2, 'hash': {}, 'name': u'SWTCW_2_03.part05.rev', 'url': u'https://www.bigfile.to/file/PTapybCHujCm', 'pattern': {'S': u'502.00', 'U': u'MB', 'ID': u'PTapybCHujCm', 'N': u'xxxxxxxx.part05.rev'}, 'size': 526385152}
06.05.2017 06:41:44 DEBUG     HOSTER BigfileTo[274]: Previous link info: {}
06.05.2017 06:41:44 INFO      HOSTER BigfileTo[274]: Link name: xxxxxxxx.part05.rev
06.05.2017 06:41:44 INFO      HOSTER BigfileTo[274]: Link size: 502.00 MiB (526385152 bytes)
06.05.2017 06:41:44 INFO      HOSTER BigfileTo[274]: Link status: online
06.05.2017 06:41:44 INFO      HOSTER BigfileTo[274]: Processing url: https://www.bigfile.to/file/PTapybCHujCm
06.05.2017 06:41:44 INFO      HOSTER BigfileTo[274]: Looking for direct download link...
06.05.2017 06:41:44 DEBUG     HOSTER BigfileTo[274]: LOAD URL https://www.bigfile.to/file/PTapybCHujCm | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
06.05.2017 06:41:45 INFO      HOSTER BigfileTo[274]: Direct download link not found
06.05.2017 06:41:45 DEBUG     HOSTER BigfileTo[274]: LOAD URL https://www.bigfile.to/file/PTapybCHujCm | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
06.05.2017 06:42:16 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
06.05.2017 06:42:16 DEBUG     pycurl exception 28: Operation too slow. Less than 5 bytes/sec transferred the last 30 seconds
06.05.2017 06:42:16 WARNING   Couldn't connect to host or connection reset, waiting 1 minute and retry.
06.05.2017 06:43:16 INFO      Download starts: xxxxxxxx.part05.rev
06.05.2017 06:43:16 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
06.05.2017 06:43:16 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
06.05.2017 06:43:16 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
06.05.2017 06:43:16 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
06.05.2017 06:43:16 DEBUG     HOSTER BigfileTo[274]: Plugin version: 0.19
06.05.2017 06:43:16 DEBUG     HOSTER BigfileTo[274]: Plugin status: testing
06.05.2017 06:43:16 WARNING   HOSTER BigfileTo[274]: Plugin may be unstable
06.05.2017 06:43:16 INFO      ACCOUNT BigfileTo: Grabbing account info for user `aaa*******`...
06.05.2017 06:43:16 DEBUG     ACCOUNT BigfileTo: LOAD URL https://www.bigfile.to/login.php | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
06.05.2017 06:43:18 DEBUG     ACCOUNT BigfileTo: Account info for user `aaa*******`: {'login': {'timestamp': 1494052761.343195, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account BigfileTo>, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': None, 'login': 'aaa*******', 'type': 'BigfileTo', 'options': {'limitdl': '0'}}}
06.05.2017 06:43:18 INFO      HOSTER BigfileTo[274]: Grabbing link info...
06.05.2017 06:43:22 DEBUG     HOSTER BigfileTo[274]: Link info: {'status': 2, 'hash': {}, 'name': u'SWTCW_2_03.part05.rev', 'url': u'https://www.bigfile.to/file/PTapybCHujCm', 'pattern': {'S': u'502.00', 'U': u'MB', 'ID': u'PTapybCHujCm', 'N': u'xxxxxxx.part05.rev'}, 'size': 526385152}
06.05.2017 06:43:22 DEBUG     HOSTER BigfileTo[274]: Previous link info: {'status': 2, 'hash': {}, 'name': u'SWTCW_2_03.part05.rev', 'url': u'https://www.bigfile.to/file/PTapybCHujCm', 'pattern': {'S': u'502.00', 'U': u'MB', 'ID': u'PTapybCHujCm', 'N': u'SWTCW_2_03.part05.rev'}, 'size': 526385152}
06.05.2017 06:43:22 INFO      HOSTER BigfileTo[274]: Link name: xxxxxxxxx.part05.rev
06.05.2017 06:43:22 INFO      HOSTER BigfileTo[274]: Link size: 502.00 MiB (526385152 bytes)
06.05.2017 06:43:22 INFO      HOSTER BigfileTo[274]: Link status: online
06.05.2017 06:43:22 INFO      HOSTER BigfileTo[274]: Processing url: https://www.bigfile.to/file/PTapybCHujCm
06.05.2017 06:43:22 INFO      HOSTER BigfileTo[274]: Looking for direct download link...
06.05.2017 06:43:22 DEBUG     HOSTER BigfileTo[274]: LOAD URL https://www.bigfile.to/file/PTapybCHujCm | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
06.05.2017 06:43:23 INFO      HOSTER BigfileTo[274]: Direct download link not found
06.05.2017 06:43:23 DEBUG     HOSTER BigfileTo[274]: LOAD URL https://www.bigfile.to/file/PTapybCHujCm | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
Traceback (most recent call last):
  File "/home/leocric/src/pyload/module/network/HTTPRequest.py", line 279, in write
    raise Exception("Loaded Url exceeded limit")
Exception: Loaded Url exceeded limit
06.05.2017 06:43:27 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
06.05.2017 06:43:27 DEBUG     pycurl exception 23: Failed writing body (0 != 8640)
06.05.2017 06:43:27 ERROR     pycurl error 23: Failed writing body (0 != 8640)
Traceback (most recent call last):
  File "/home/leocric/src/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/leocric/src/pyload/module/plugins/internal/Base.py", line 294, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/leocric/src/pyload/module/plugins/internal/Hoster.py", line 113, in _process
    self.process(self.pyfile)
  File "/home/leocric/src/pyload/module/plugins/internal/SimpleHoster.py", line 277, in process
    self._preload()
  File "/home/leocric/src/pyload/module/plugins/internal/SimpleHoster.py", line 256, in _preload
    decode=self.TEXT_ENCODING)
  File "/home/leocric/src/pyload/module/plugins/internal/Base.py", line 493, in load
    return Plugin.load(self, *args, **kwargs)
  File "/home/leocric/src/pyload/module/plugins/internal/Plugin.py", line 213, in load
    decode is True)  # @TODO: Fix network multipart in 0.4.10
  File "/home/leocric/src/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/home/leocric/src/pyload/module/network/HTTPRequest.py", line 203, in load
    self.c.perform()
error: (23, 'Failed writing body (0 != 8640)')
06.05.2017 06:43:27 INFO      Debug Report written to debug_BigfileTo_06-05-2017_06-43-27.zip
06.05.2017 06:43:27 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
06.05.2017 06:43:27 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: SWTCW_2_03.part05.rev (pid:4)
06.05.2017 06:43:27 INFO      ADDON UnSkipOnFail: No duplicates found
06.05.2017 06:43:28 INFO      Download starts: https://www.bigfile.to/file/DFS3bBXBW5tM
06.05.2017 06:43:28 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
06.05.2017 06:43:28 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
06.05.2017 06:43:28 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
06.05.2017 06:43:28 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
06.05.2017 06:43:28 DEBUG     HOSTER BigfileTo[275]: Plugin version: 0.19
06.05.2017 06:43:28 DEBUG     HOSTER BigfileTo[275]: Plugin status: testing
06.05.2017 06:43:28 WARNING   HOSTER BigfileTo[275]: Plugin may be unstable
06.05.2017 06:43:28 INFO      ACCOUNT BigfileTo: Grabbing account info for user `aaa*******`...
06.05.2017 06:43:28 DEBUG     ACCOUNT BigfileTo: LOAD URL https://www.bigfile.to/login.php | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
06.05.2017 06:43:28 DEBUG     ACCOUNT BigfileTo: Account info for user `aaa*******`: {'login': {'timestamp': 1494052761.343195, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account BigfileTo>, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': None, 'login': 'aaa*******', 'type': 'BigfileTo', 'options': {'limitdl': '0'}}}
06.05.2017 06:43:28 INFO      HOSTER BigfileTo[275]: Grabbing link info...
06.05.2017 06:43:30 DEBUG     HOSTER BigfileTo[275]: Link info: {'status': 2, 'hash': {}, 'name': u'xxxxxxxxx.part06.rar', 'url': u'https://www.bigfile.to/file/DFS3bBXBW5tM', 'pattern': {'S': u'502.00', 'U': u'MB', 'ID': u'DFS3bBXBW5tM', 'N': u'SWTCW_2_03.part06.rar'}, 'size': 526385152}
06.05.2017 06:43:30 DEBUG     HOSTER BigfileTo[275]: Previous link info: {}
06.05.2017 06:43:30 INFO      HOSTER BigfileTo[275]: Link name: xxxxxxxx.part06.rar
06.05.2017 06:43:30 INFO      HOSTER BigfileTo[275]: Link size: 502.00 MiB (526385152 bytes)
06.05.2017 06:43:30 INFO      HOSTER BigfileTo[275]: Link status: online
06.05.2017 06:43:30 INFO      HOSTER BigfileTo[275]: Processing url: https://www.bigfile.to/file/DFS3bBXBW5tM
06.05.2017 06:43:30 INFO      HOSTER BigfileTo[275]: Looking for direct download link...
06.05.2017 06:43:30 DEBUG     HOSTER BigfileTo[275]: LOAD URL https://www.bigfile.to/file/DFS3bBXBW5tM | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
06.05.2017 06:43:31 INFO      HOSTER BigfileTo[275]: Direct download link not found
06.05.2017 06:43:31 DEBUG     HOSTER BigfileTo[275]: LOAD URL https://www.bigfile.to/file/DFS3bBXBW5tM | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
Traceback (most recent call last):
  File "/home/leocric/src/pyload/module/network/HTTPRequest.py", line 279, in write
    raise Exception("Loaded Url exceeded limit")
Exception: Loaded Url exceeded limit
06.05.2017 06:43:34 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
06.05.2017 06:43:34 DEBUG     pycurl exception 23: Failed writing body (0 != 1440)
06.05.2017 06:43:34 ERROR     pycurl error 23: Failed writing body (0 != 1440)
Traceback (most recent call last):
  File "/home/leocric/src/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/leocric/src/pyload/module/plugins/internal/Base.py", line 294, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/leocric/src/pyload/module/plugins/internal/Hoster.py", line 113, in _process
    self.process(self.pyfile)
  File "/home/leocric/src/pyload/module/plugins/internal/SimpleHoster.py", line 277, in process
    self._preload()
  File "/home/leocric/src/pyload/module/plugins/internal/SimpleHoster.py", line 256, in _preload
    decode=self.TEXT_ENCODING)
  File "/home/leocric/src/pyload/module/plugins/internal/Base.py", line 493, in load
    return Plugin.load(self, *args, **kwargs)
  File "/home/leocric/src/pyload/module/plugins/internal/Plugin.py", line 213, in load
    decode is True)  # @TODO: Fix network multipart in 0.4.10
  File "/home/leocric/src/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/home/leocric/src/pyload/module/network/HTTPRequest.py", line 203, in load
    self.c.perform()
error: (23, 'Failed writing body (0 != 1440)')
06.05.2017 06:43:34 INFO      Debug Report written to debug_BigfileTo_06-05-2017_06-43-34.zip
06.05.2017 06:43:34 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
06.05.2017 06:43:34 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: SWTCW_2_03.part06.rar (pid:4)
06.05.2017 06:43:34 INFO      ADDON UnSkipOnFail: No duplicates found
06.05.2017 06:43:36 INFO      Download starts: https://www.bigfile.to/file/Z29NDxskqT4A
06.05.2017 06:43:36 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
06.05.2017 06:43:36 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
06.05.2017 06:43:36 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
06.05.2017 06:43:36 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
06.05.2017 06:43:36 DEBUG     HOSTER BigfileTo[276]: Plugin version: 0.19
06.05.2017 06:43:36 DEBUG     HOSTER BigfileTo[276]: Plugin status: testing
06.05.2017 06:43:36 WARNING   HOSTER BigfileTo[276]: Plugin may be unstable
06.05.2017 06:43:36 INFO      ACCOUNT BigfileTo: Grabbing account info for user `aaa*******`...
06.05.2017 06:43:36 DEBUG     ACCOUNT BigfileTo: LOAD URL https://www.bigfile.to/login.php | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
06.05.2017 06:43:36 DEBUG     ACCOUNT BigfileTo: Account info for user `aaa*******`: {'login': {'timestamp': 1494052761.343195, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account BigfileTo>, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': None, 'login': 'aaa*******', 'type': 'BigfileTo', 'options': {'limitdl': '0'}}}
06.05.2017 06:43:36 INFO      HOSTER BigfileTo[276]: Grabbing link info...
06.05.2017 06:43:38 DEBUG     HOSTER BigfileTo[276]: Link info: {'status': 2, 'hash': {}, 'name': u'xxxxxxxx.part07.rar', 'url': u'https://www.bigfile.to/file/Z29NDxskqT4A', 'pattern': {'S': u'502.00', 'U': u'MB', 'ID': u'Z29NDxskqT4A', 'N': u'xxxxxxxx.part07.rar'}, 'size': 526385152}
06.05.2017 06:43:38 DEBUG     HOSTER BigfileTo[276]: Previous link info: {}
06.05.2017 06:43:38 INFO      HOSTER BigfileTo[276]: Link name: xxxxxxxx.part07.rar
06.05.2017 06:43:38 INFO      HOSTER BigfileTo[276]: Link size: 502.00 MiB (526385152 bytes)
06.05.2017 06:43:38 INFO      HOSTER BigfileTo[276]: Link status: online
06.05.2017 06:43:38 INFO      HOSTER BigfileTo[276]: Processing url: https://www.bigfile.to/file/Z29NDxskqT4A
06.05.2017 06:43:38 INFO      HOSTER BigfileTo[276]: Looking for direct download link...
06.05.2017 06:43:38 DEBUG     HOSTER BigfileTo[276]: LOAD URL https://www.bigfile.to/file/Z29NDxskqT4A | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
06.05.2017 06:43:39 INFO      HOSTER BigfileTo[276]: Direct download link not found
06.05.2017 06:43:39 DEBUG     HOSTER BigfileTo[276]: LOAD URL https://www.bigfile.to/file/Z29NDxskqT4A | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
Traceback (most recent call last):
  File "/home/leocric/src/pyload/module/network/HTTPRequest.py", line 279, in write
    raise Exception("Loaded Url exceeded limit")
Exception: Loaded Url exceeded limit
06.05.2017 06:43:42 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
06.05.2017 06:43:42 DEBUG     pycurl exception 23: Failed writing body (0 != 1440)
06.05.2017 06:43:42 ERROR     pycurl error 23: Failed writing body (0 != 1440)
Traceback (most recent call last):
  File "/home/leocric/src/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/leocric/src/pyload/module/plugins/internal/Base.py", line 294, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/leocric/src/pyload/module/plugins/internal/Hoster.py", line 113, in _process
    self.process(self.pyfile)
  File "/home/leocric/src/pyload/module/plugins/internal/SimpleHoster.py", line 277, in process
    self._preload()
  File "/home/leocric/src/pyload/module/plugins/internal/SimpleHoster.py", line 256, in _preload
    decode=self.TEXT_ENCODING)
  File "/home/leocric/src/pyload/module/plugins/internal/Base.py", line 493, in load
    return Plugin.load(self, *args, **kwargs)
  File "/home/leocric/src/pyload/module/plugins/internal/Plugin.py", line 213, in load
    decode is True)  # @TODO: Fix network multipart in 0.4.10
  File "/home/leocric/src/pyload/module/network/Browser.py", line 97, in load return self.http.load(*args, **kwargs)
  File "/home/leocric/src/pyload/module/network/HTTPRequest.py", line 203, in load self.c.perform()
error: (23, 'Failed writing body (0 != 1440)')
06.05.2017 06:43:42 INFO      Debug Report written to debug_BigfileTo_06-05-2017_06-43-42.zip
06.05.2017 06:43:42 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
06.05.2017 06:43:42 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: SWTCW_2_03.part07.rar (pid:4)
06.05.2017 06:43:42 INFO      ADDON UnSkipOnFail: No duplicates found
```

A similar situation is for Easybytez.com. Maybe I have some trouble with pyLoad... or whatelse?

**Comment by GammaC0de** [comment]
This works fine here, how exactly have you installed pyLoad?

**Comment by klode82** [comment]
Maybe this can be useful for other people who had my same problem.
During installation, it notifies me the JS engine is not found.
So, on my Pine64 I've installed Rhino, then I've cleaned anything about pyload (configuration, release, etc.) and now it works fine for me.

One thing, during the first setup, I think is useful add some notes for each prerequisites about their features.

**Comment by GammaC0de** [comment]
JS engine is not mandatory: it is used for ClickNLoad and some plugins.
Your problem resided somewhere else and since you have managed to solve this, I am closing this issue.
👍
