### ISSUE TITLE
setup.py broken: conversion of README for python 3

### ISSUE THREAD

**Issue by sebix** [pyload/pyload#2855]
The next bug in the setup.py's of pyload, config, requests and utils:

```python
> pip install ../Downloads/pyload-0.6.2.tar.gz 
Processing ../Downloads/pyload-0.6.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-vgrflfhc-build/setup.py", line 85, in _get_long_description
        return _read_text('README.rst')
      File "/tmp/pip-vgrflfhc-build/setup.py", line 36, in _read_text
        with io.open(file, mode='rb') as fp:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-vgrflfhc-build/setup.py", line 258, in <module>
        LONG_DESC = _get_long_description()
      File "/tmp/pip-vgrflfhc-build/setup.py", line 87, in _get_long_description
        return _gen_long_description()
      File "/tmp/pip-vgrflfhc-build/setup.py", line 77, in _gen_long_description
        readme = _purge_text(_read_text('README.md').split(delimeter, 1)[0])
    TypeError: a bytes-like object is required, not 'str'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-vgrflfhc-build/
```

Either simply change the file mode to text mode in `_read_text`, or encode and decode a bunch of strings afterwards (I had to fix it 3 times until I stopped working on it...)

**Comment by sebix** [comment]
And the next bugs:
```python
> pip install ../Downloads/pyload-0.6.2/
Processing /home/ele/Downloads/pyload-0.6.2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, map
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3037, in <module>
        @_call_aside
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3021, in _call_aside
        f(*args, **kwargs)
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3065, in _initialize_master_working_set
        for dist in working_set
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3065, in <genexpr>
        for dist in working_set
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2595, in activate
        declare_namespace(pkg)
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2163, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2098, in _handle_ns
        loader.load_module(packageName)
      File "./pyload.py", line 16, in <module>
        from pyload.core.cli import main
    ModuleNotFoundError: No module named 'pyload.core'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-_v_cyqxp-build/
```
Switching the sys-path change and the import does give other errors and doesn't fix it, but simply using `from src.pyload.core.cli import main` fixes it.

Then the next bug:
```python
> pip install ../Downloads/pyload-0.6.2/
Processing /home/ele/Downloads/pyload-0.6.2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, map
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3037, in <module>
        @_call_aside
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3021, in _call_aside
        f(*args, **kwargs)
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3065, in _initialize_master_working_set
        for dist in working_set
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3065, in <genexpr>
        for dist in working_set
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2595, in activate
        declare_namespace(pkg)
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2163, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2098, in _handle_ns
        loader.load_module(packageName)
      File "./pyload.py", line 16, in <module>
        from src.pyload.core.cli import main
      File "/tmp/pip-cqa6fpuy-build/src/pyload/core/__init__.py", line 39, in <module>
        from . import api, config, database, datatype, manager, network, plugin, thread
      File "/tmp/pip-cqa6fpuy-build/src/pyload/core/api/__init__.py", line 4, in <module>
        from .init import Api, requireperm, statestring
      File "/tmp/pip-cqa6fpuy-build/src/pyload/core/api/init.py", line 11, in <module>
        from ..datatype.init import DownloadState, DownloadStatus, Permission
      File "/tmp/pip-cqa6fpuy-build/src/pyload/core/datatype/__init__.py", line 6, in <module>
        from .file import File, FileDoesNotExist, FileInfo, FileStatus
      File "/tmp/pip-cqa6fpuy-build/src/pyload/core/datatype/file.py", line 14, in <module>
        from pyload.utils.struct.lock import RWLock, lock
      File "/home/ele/bin/pyloadenv/lib/python3.6/site-packages/pyload/utils/struct/lock.py", line 11, in <module>
        from ..layer.safethreading import Condition, Lock, RLock, currentThread
    ImportError: cannot import name 'currentThread'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-cqa6fpuy-build/
```
But that's now in utils - but it happens when *installing* pyload.

**Comment by Slevin7** [comment]
From the readme
Notice: Master Branch is under heavy development, very unstable, often broken.
Notice: Stable Branch is production ready.

you have to use the stable because 0.6 is not ready yet

**Comment by sebix** [comment]
@Slevin7 I used the latest tag/release 0.6.2

**Comment by Slevin7** [comment]
I but that is the master branche and that doesnt work.
you should use 0.4.9
i mean this branch https://github.com/pyload/pyload/tree/stable

**Comment by BKPepe** [comment]
According to gitter and respond from @vuolter
Release 0.6.2 isn't still ready. :(

**Comment by vuolter** [comment]
I have not written it anywhere, my fault, but ideally I switch to semantic versioning so until **v1.0.0** there not will be a stable release for the audience. Of course I hope to made a working testing release a bunch of versions earlier, like 0.8.0 or 0.7.0. For now there are three essential modules (packages), in addition to this, I working on: `pyload.utils`, `pyload.config`, `pyload.webui`.
`pyload.utils` is complete, just `setup.py` is not working and maybe some bad logic we'll spot in the upcoming testing phase, maybe not. ;)
`pyload.config` was just fully rewritten by me, it's complete. Need testing as well.
`pyload.webui` is not complete. That module was written by @RaNaN, so I don't know it very well.
Finally this, `pyload.core`m it's in a "pain the neck" state (for me at least). Indeed, took me a long time to refact the old python2 code to python3 (and pypy) and in all honesty was a crazy huge job! There're still several missing routines, others need a rewrite, others need to be linked to the new modules and so on. In short, I think I'm approximately at the half of the work. That's not good, I know.

**Comment by sebix** [comment]
Well, the stable branch is not quite usable too. I try to give early feedback on the new versions based on master - I hope @vuolter can make something out of it :).
