### ISSUE TITLE
'error' in __slots__ conflicts with class variable

### ISSUE THREAD

**Issue by sebix** [pyload/pyload#2856]
```python
> pip install ../Downloads/pyload-0.6.2/
Processing ../Downloads/pyload-0.6.2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/user/bin/pyloadenv/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, map
      File "/home/user/bin/pyloadenv/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/home/user/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3037, in <module>
        @_call_aside
      File "/home/user/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3021, in _call_aside
        f(*args, **kwargs)
      File "/home/user/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3065, in _initialize_master_working_set
        for dist in working_set
      File "/home/user/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3065, in <genexpr>
        for dist in working_set
      File "/home/user/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2595, in activate
        declare_namespace(pkg)
      File "/home/user/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2163, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/user/bin/pyloadenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2098, in _handle_ns
        loader.load_module(packageName)
      File "./pyload.py", line 16, in <module>
        from src.pyload.core.cli import main
      File "/tmp/pip-aq8vdjca-build/src/pyload/core/__init__.py", line 39, in <module>
        from . import api, config, database, datatype, manager, network, plugin, thread
      File "/tmp/pip-aq8vdjca-build/src/pyload/core/api/__init__.py", line 4, in <module>
        from .init import Api, requireperm, statestring
      File "/tmp/pip-aq8vdjca-build/src/pyload/core/api/init.py", line 11, in <module>
        from ..datatype.init import DownloadState, DownloadStatus, Permission
      File "/tmp/pip-aq8vdjca-build/src/pyload/core/datatype/__init__.py", line 9, in <module>
        from .task import Interaction, InteractionTask
      File "/tmp/pip-aq8vdjca-build/src/pyload/core/datatype/task.py", line 29, in <module>
        class InteractionTask(BaseObject):
    ValueError: 'error' in __slots__ conflicts with class variable
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-aq8vdjca-build/
```
Same for `handler`, `locked`, `owner`, `result`, `seen`, `shared`, `storage`, `wait_until`

**Comment by Slevin7** [comment]
From the readme
Notice: Master Branch is under heavy development, very unstable, often broken.
Notice: Stable Branch is production ready.

you have to use the stable because 0.6 is not ready yet

**Comment by vuolter** [comment]
Fixing...
