### ISSUE TITLE
AttributeError: Job instance has no attribute 'threaded'

### ISSUE THREAD

**Issue by BKPepe** [pyload/pyload#2857]
I was downloading few files and suddenly web ui wasn't responding and I tried refresh, but it didn't work. I though it's downloading files, but it wasn't.

Honestly I can't say much about it. This is log from /var/log/daemon.log
Hopefully it will help you to fix it.

```
Jun  3 23:41:09 Debian-NAS pyLoadCore.py[3224]: Traceback (most recent call last):
Jun  3 23:41:09 Debian-NAS pyLoadCore.py[3224]: File "/home/pepe/pyload/pyLoadCore.py", line 667, in <module>
Jun  3 23:41:09 Debian-NAS pyLoadCore.py[3224]: main()
Jun  3 23:41:09 Debian-NAS pyLoadCore.py[3224]: File "/home/pepe/pyload/pyLoadCore.py", line 658, in main
Jun  3 23:41:09 Debian-NAS pyLoadCore.py[3224]: pyload_core.start()
Jun  3 23:41:09 Debian-NAS pyLoadCore.py[3224]: File "/home/pepe/pyload/pyLoadCore.py", line 469, in start
Jun  3 23:41:09 Debian-NAS pyLoadCore.py[3224]: self.scheduler.work()
Jun  3 23:41:09 Debian-NAS pyLoadCore.py[3224]: File "/home/pepe/pyload/module/Scheduler.py", line 85, in work
Jun  3 23:41:09 Debian-NAS pyLoadCore.py[3224]: j.start()
Jun  3 23:41:09 Debian-NAS pyLoadCore.py[3224]: File "/home/pepe/pyload/module/Scheduler.py", line 108, in start
Jun  3 23:41:09 Debian-NAS pyLoadCore.py[3224]: if self.threaded:
Jun  3 23:41:09 Debian-NAS pyLoadCore.py[3224]: AttributeError: Job instance has no attribute 'threaded'
```

and before it I have this:
```
Jun  3 23:40:19 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:19 INFO      HOSTER WebshareCz[78]: Checking for link errors...
Jun  3 23:40:19 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:19 INFO      HOSTER WebshareCz[78]: No errors found
Jun  3 23:40:19 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:19 INFO      HOSTER WebshareCz[78]: Processing as premium download...
Jun  3 23:40:19 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:19 INFO      ACCOUNT WebshareCz: Grabbing account info for user `Pep*******`...
Jun  3 23:40:22 Debian-NAS smartd[3237]: Device: /dev/disk/by-id/ata-ST8000AS0002-1NA17Z_Z840P3EZ [SAT], SMART Usage Attribute: 190 Airflow_Temperature_Cel changed from 67 to 68
Jun  3 23:40:24 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:24 INFO      HOSTER WebshareCz[79]: Link name: trstm10.part6.rar
Jun  3 23:40:24 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:24 INFO      HOSTER WebshareCz[79]: Link size: 1.85 GiB (1982559144 bytes)
Jun  3 23:40:24 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:24 INFO      HOSTER WebshareCz[79]: Link status: online
Jun  3 23:40:24 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:24 INFO      HOSTER WebshareCz[79]: Processing url: https://webshare.cz/#/file/38g6a1j22f/trstm10-part6-rar
Jun  3 23:40:24 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:24 INFO      HOSTER WebshareCz[79]: Looking for direct download link...
Jun  3 23:40:25 Debian-NAS smartd[3237]: Device: /dev/disk/by-id/ata-ST2000DX001-1NS164_Z4Z6D98E [SAT], SMART Prefailure Attribute: 1 Raw_Read_Error_Rate changed from 117 to 118
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:28 ERROR     ACCOUNT UptoboxCom: Could not login user `bkp*******` | (6, 'Could not resolve host: login.uptobox.com')
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: Traceback (most recent call last):
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: if self.shouldRollover(record):
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: msg = "%s\n" % self.format(record)
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: return fmt.format(record)
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: record.message = record.getMessage()
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: msg = msg % self.args
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: TypeError: not all arguments converted during string formatting
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: Logged from file ThreadManager.py, line 146
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: Traceback (most recent call last):
Jun  3 23:40:28 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
Jun  3 23:40:29 Debian-NAS pyLoadCore.py[3224]: msg = self.format(record)
Jun  3 23:40:29 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
Jun  3 23:40:29 Debian-NAS pyLoadCore.py[3224]: return fmt.format(record)
Jun  3 23:40:29 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
Jun  3 23:40:29 Debian-NAS pyLoadCore.py[3224]: record.message = record.getMessage()
Jun  3 23:40:29 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
Jun  3 23:40:29 Debian-NAS pyLoadCore.py[3224]: msg = msg % self.args
Jun  3 23:40:29 Debian-NAS pyLoadCore.py[3224]: TypeError: not all arguments converted during string formatting
Jun  3 23:40:29 Debian-NAS pyLoadCore.py[3224]: Logged from file ThreadManager.py, line 146
Jun  3 23:40:29 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:28 INFO      HOSTER UptoboxCom[80]: Grabbing link info...
Jun  3 23:40:34 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:34 INFO      HOSTER WebshareCz[79]: Direct download link not found
Jun  3 23:40:36 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:36 INFO      HOSTER WebshareCz[79]: Checking for link errors...
Jun  3 23:40:36 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:36 INFO      HOSTER WebshareCz[79]: No errors found
Jun  3 23:40:36 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:36 INFO      HOSTER WebshareCz[79]: Processing as premium download...
Jun  3 23:40:36 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:36 INFO      ACCOUNT WebshareCz: Grabbing account info for user `Pep*******`...
Jun  3 23:40:38 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:38 INFO      HOSTER WebshareCz[78]: Downloading file...
Jun  3 23:40:38 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:38 INFO      HOSTER UptoboxCom[80]: Link name: spltq16.part1.rar
Jun  3 23:40:38 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:38 INFO      HOSTER UptoboxCom[80]: Link size: 1.80 GiB (1932735283 bytes)
Jun  3 23:40:38 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:38 INFO      HOSTER UptoboxCom[80]: Link status: online
Jun  3 23:40:38 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:38 INFO      HOSTER UptoboxCom[80]: Processing url: http://uptobox.com/bxd9sctglsmx
Jun  3 23:40:46 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:46 INFO      HOSTER UptoboxCom[80]: Checking for link errors...
Jun  3 23:40:46 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:46 WARNING   HOSTER UptoboxCom[80]: 1 hour, 9 minutes, 34 seconds
Jun  3 23:40:46 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:46 INFO      HOSTER UptoboxCom[80]: Waiting 1 hours, 9 minutes, 34 seconds...
Jun  3 23:40:50 Debian-NAS pyLoadCore.py[3224]: 03.06.2017 23:40:50 INFO      HOSTER WebshareCz[79]: Downloading file...
```

I also noticed this  traceback (but it didnt crash payload, but it was working)
Don't know if I should create another issue, bcs I don't know if it is related.
```
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: Traceback (most recent call last):
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: self.finish_response()
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: self.write(data)
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: self.send_headers()
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/wsgiref/handlers.py", line 271, in send_headers
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: self._write(str(self.headers))
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/socket.py", line 324, in write
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: self.flush()
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/socket.py", line 303, in flush
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: error: [Errno 32] Broken pipe
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: Traceback (most recent call last):
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: self.process_request(request, client_address)
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: self.finish_request(request, client_address)
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: self.RequestHandlerClass(request, client_address, self)
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: self.finish()
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: self.wfile.close()
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/socket.py", line 279, in close
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: self.flush()
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: File "/usr/lib/python2.7/socket.py", line 303, in flush
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Jun  3 22:31:27 Debian-NAS pyLoadCore.py[3224]: error: [Errno 32] Broken pipe
```

**Comment by GammaC0de** [comment]
Have you tried to restart pyload?

**Comment by BKPepe** [comment]
When I want to continue with downloading I was forced to do restart, but that's not solution. ;-)
Everytime to check what was bad. This should be fixed. I enabled debug and hopefully it will tell you more to get it fixed.

**Comment by GammaC0de** [comment]
This could be a one time fault such as out of memory, etc..

**Comment by GammaC0de** [comment]
Continue in #2859
