### ISSUE TITLE
Nitroflare Premium Account

### ISSUE THREAD

**Issue by somerandom48** [pyload/pyload#2915]
I am unable to add a Nitroflare Premium Account when I put my details in status is not valid. I am running it on Ubuntu server but I also tried a clean install on my windows machine and run into the same error. It does however seems to be working when added the account via jDownloader so I don't think there is a problem with the account. I ran the pyloadcore in debug mode this is the output.
~~~28.07.2017 10:30:53 INFO      Starting pyLoad 0.4.9
28.07.2017 10:30:53 INFO      Using home directory: /opt/pyload
28.07.2017 10:30:53 DEBUG     Remote activated: True
28.07.2017 10:30:54 DEBUG     created index of plugins
28.07.2017 10:30:54 DEBUG     Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
28.07.2017 10:30:54 DEBUG     Redirected import module.plugins.hooks.EventMapper -> userplugins.hooks.EventMapper
28.07.2017 10:30:54 DEBUG     Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
28.07.2017 10:30:54 DEBUG     Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
28.07.2017 10:30:54 DEBUG     Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
28.07.2017 10:30:54 DEBUG     Redirected import module.plugins.hooks.ClickNLoad -> userplugins.hooks.ClickNLoad
28.07.2017 10:30:54 DEBUG     Redirected import module.plugins.hooks.UserAgentSwitcher -> userplugins.hooks.UserAgentSwitcher
28.07.2017 10:30:54 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, UnSkipOnFail, UpdateManager, UserAgentSwitcher
28.07.2017 10:30:54 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, Hot
Folder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XFileSharing, XMPP
28.07.2017 10:30:54 INFO      Downloadtime: True
28.07.2017 10:30:54 INFO      Starting ThriftBackend: 0.0.0.0:7227
28.07.2017 10:30:56 INFO      Starting builtin webserver: 0.0.0.0:8002
28.07.2017 10:30:56 INFO      Free space: 917.92 GiB
28.07.2017 10:30:56 INFO      Activating Accounts...
28.07.2017 10:30:56 DEBUG     Redirected import module.plugins.accounts.UploadedTo -> userplugins.accounts.UploadedTo
28.07.2017 10:30:56 INFO      ACCOUNT UploadedTo: Adding user `som*******`...
28.07.2017 10:30:56 DEBUG     ACCOUNT UploadedTo: Reached login timeout for user `som*******`
28.07.2017 10:30:56 INFO      ACCOUNT UploadedTo: Login user `som*******`...
28.07.2017 10:30:56 DEBUG     ACCOUNT UploadedTo: Reached login timeout for user `som*******`                                                                                                                                        [64/762]
28.07.2017 10:30:56 INFO      ACCOUNT UploadedTo: Login user `som*******`...
28.07.2017 10:30:56 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.07.2017 10:30:56 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/io/login | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'id': 'som*******', 'pw': '**********'} | ref=True | just_
header=False
28.07.2017 10:30:56 INFO      ACCOUNT UploadedTo: Grabbing account info for user `som*******`...
28.07.2017 10:30:56 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.07.2017 10:30:57 DEBUG     ACCOUNT UploadedTo: Size: 472,68 | Unit: gb
28.07.2017 10:30:57 DEBUG     ACCOUNT UploadedTo: Account info for user `som*******`: {'login': {'timestamp': 1501201856.121882, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account UploadedTo>, 'traffic
left': 495640903, 'maxtraffic': None, 'validuntil': 1506475857.069739, 'login': 'som*******', 'type': 'UploadedTo', 'options': {'limitdl': ['0']}}}
28.07.2017 10:30:57 DEBUG     Redirected import module.plugins.accounts.NitroflareCom -> userplugins.accounts.NitroflareCom
28.07.2017 10:30:57 INFO      ACCOUNT NitroflareCom: Adding user `som*******`...
28.07.2017 10:30:57 DEBUG     ACCOUNT NitroflareCom: Reached login timeout for user `som*******`
28.07.2017 10:30:57 INFO      ACCOUNT NitroflareCom: Login user `som*******`...
28.07.2017 10:30:57 DEBUG     ACCOUNT NitroflareCom: LOAD URL https://nitroflare.com/api/v2/getKeyInfo | redirect=True | cookies=True | get={'premiumKey': '**********', 'user': 'som*******'} | req=None | decode=True | multipart=False | p
ost={} | ref=True | just_header=False
28.07.2017 10:30:58 ERROR     ACCOUNT NitroflareCom: Could not login user `som*******` | 'status'
Traceback (most recent call last):
  File "/opt/pyload/pyload-0.4.9/pyLoadCore.py", line 666, in <module>
    main()
  File "/opt/pyload/pyload-0.4.9/pyLoadCore.py", line 657, in main
    pyload_core.start()
  File "/opt/pyload/pyload-0.4.9/pyLoadCore.py", line 432, in start
    self.accountManager.getAccountInfos()
  File "/opt/pyload/pyload-0.4.9/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/pyload-0.4.9/module/plugins/AccountManager.py", line 176, in getAccountInfos
    data[p.__name__] = p.getAllAccounts(force)
  File "/opt/pyload/userplugins/internal/misc.py", line 228, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/userplugins/internal/Account.py", line 279, in getAllAccounts
    self.init_accounts()  # @TODO: Recheck in 0.4.10
  File "/opt/pyload/userplugins/internal/misc.py", line 228, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/userplugins/internal/Account.py", line 267, in init_accounts
    self.add(user, info['password'], info['options'])
  File "/opt/pyload/userplugins/internal/misc.py", line 228, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/userplugins/internal/Account.py", line 313, in add
    result = u['plugin'].choose(user)
  File "/opt/pyload/userplugins/internal/misc.py", line 228, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/userplugins/internal/Account.py", line 430, in choose
    self.relogin()
  File "/opt/pyload/userplugins/internal/Account.py", line 177, in relogin
    return self.login()
  File "/opt/pyload/userplugins/internal/Account.py", line 118, in login
    self.info['data'])
  File "/opt/pyload/userplugins/accounts/NitroflareCom.py", line 49, in signin
    if data['type'] != 'success' or data['result']['status'] == "banned":
KeyError: 'status'

28.07.2017 10:30:58 DEBUG     Redirected import module.plugins.accounts.RapidgatorNet -> userplugins.accounts.RapidgatorNet
28.07.2017 10:30:58 INFO      ACCOUNT RapidgatorNet: Adding user `tru*******`...
28.07.2017 10:30:58 DEBUG     ACCOUNT RapidgatorNet: Reached login timeout for user `tru*******`
28.07.2017 10:30:58 INFO      ACCOUNT RapidgatorNet: Login user `tru*******`...
28.07.2017 10:30:58 DEBUG     ACCOUNT RapidgatorNet: LOAD URL http://rapidgator.net/api/user/login | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'username': 'tru*******', 'password': '********
**'} | ref=True | just_header=False
28.07.2017 10:31:00 DEBUG     ACCOUNT RapidgatorNet: API:LOGIN | {"response":{"session_id":"fesusrc6rmnj1pnpu64rbgbbc7","expire_date":1501216709,"traffic_left":"1091808810002"},"response_status":200,"response_details":null}
28.07.2017 10:31:00 INFO      ACCOUNT RapidgatorNet: Grabbing account info for user `tru*******`...
28.07.2017 10:31:00 DEBUG     ACCOUNT RapidgatorNet: LOAD URL http://rapidgator.net/api/user/info | redirect=True | cookies=True | get={'sid': 'fesusrc6rmnj1pnpu64rbgbbc7'} | req=None | decode=True | multipart=False | post={} | ref=True
| just_header=False
28.07.2017 10:31:00 DEBUG     ACCOUNT RapidgatorNet: API:USERINFO | {"response":{"expire_date":1501216709,"traffic_left":"1091808810002"},"response_status":200,"response_details":null}
28.07.2017 10:31:00 DEBUG     ACCOUNT RapidgatorNet: Account info for user `tru*******`: {'login': {'timestamp': 1501201858.201088, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account RapidgatorNet>, 't
rafficleft': 1066219541.0175781, 'maxtraffic': None, 'sid': 'fesusrc6rmnj1pnpu64rbgbbc7', 'validuntil': 1501216709, 'login': 'tru*******', 'type': 'RapidgatorNet', 'options': {'limitdl': ['0']}}}
28.07.2017 10:31:00 DEBUG     Redirected import module.plugins.accounts.UptoboxCom -> userplugins.accounts.UptoboxCom
rafficleft': 1066219541.0175781, 'maxtraffic': None, 'sid': 'fesusrc6rmnj1pnpu64rbgbbc7', 'validuntil': 1501216709, 'login': 'tru*******', 'type': 'RapidgatorNet', 'options': {'limitdl': ['0']}}}                                   [0/762]
28.07.2017 10:31:00 DEBUG     Redirected import module.plugins.accounts.UptoboxCom -> userplugins.accounts.UptoboxCom
28.07.2017 10:31:00 INFO      ACCOUNT UptoboxCom: Adding user `som*******`...
28.07.2017 10:31:00 DEBUG     ACCOUNT UptoboxCom: Reached login timeout for user `som*******`
28.07.2017 10:31:00 INFO      ACCOUNT UptoboxCom: Login user `som*******`...
28.07.2017 10:31:00 DEBUG     ACCOUNT UptoboxCom: LOAD URL https://login.uptobox.com/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.07.2017 10:31:00 DEBUG     ACCOUNT UptoboxCom: LOAD URL https://login.uptobox.com/logarithme | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'redirect': 'http://uptobox.com/', 'login': 'som**
*****', 'password': '**********', 'op': 'login'} | ref=True | just_header=False
28.07.2017 10:31:01 INFO      ACCOUNT UptoboxCom: Grabbing account info for user `som*******`...
28.07.2017 10:31:01 DEBUG     ACCOUNT UptoboxCom: LOAD URL http://uptobox.com/ | redirect=True | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.07.2017 10:31:01 DEBUG     ACCOUNT UptoboxCom: Expire date: 25 July 2018
28.07.2017 10:31:01 DEBUG     ACCOUNT UptoboxCom: Valid until: 1532440800.0
28.07.2017 10:31:01 DEBUG     ACCOUNT UptoboxCom: TRAFFIC LEFT PATTERN not found
28.07.2017 10:31:01 DEBUG     ACCOUNT UptoboxCom: LEECH TRAFFIC PATTERN not found
28.07.2017 10:31:01 DEBUG     ACCOUNT UptoboxCom: Account info for user `som*******`: {'login': {'timestamp': 1501201860.376512, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account UptoboxCom>, 'leechtr
affic': None, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1532440800.0, 'login': 'som*******', 'type': 'UptoboxCom', 'options': {'limitdl': ['0']}}}
28.07.2017 10:31:01 DEBUG     Redirected import module.plugins.accounts.OpenloadCo -> userplugins.accounts.OpenloadCo
28.07.2017 10:31:01 INFO      ACCOUNT OpenloadCo: Adding user `som*******`...
28.07.2017 10:31:01 DEBUG     ACCOUNT OpenloadCo: Reached login timeout for user `som*******`
28.07.2017 10:31:01 INFO      ACCOUNT OpenloadCo: Login user `som*******`...
28.07.2017 10:31:01 DEBUG     ACCOUNT OpenloadCo: LOAD URL http://www.openload.co/login.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.07.2017 10:31:02 DEBUG     ACCOUNT OpenloadCo: LOAD URL http://www.openload.co/login.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'redirect': 'http://www.openload.co/', 'login': 'som*
******', 'password': '**********', 'op': 'login'} | ref=True | just_header=False
28.07.2017 10:31:02 INFO      ACCOUNT OpenloadCo: Checking for link errors...
28.07.2017 10:31:02 INFO      ACCOUNT OpenloadCo: No errors found
28.07.2017 10:31:02 INFO      ACCOUNT OpenloadCo: Grabbing account info for user `som*******`...
28.07.2017 10:31:02 DEBUG     ACCOUNT OpenloadCo: LOAD URL http://www.openload.co/ | redirect=True | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.07.2017 10:31:02 DEBUG     ACCOUNT OpenloadCo: VALID UNTIL PATTERN not found
28.07.2017 10:31:02 DEBUG     ACCOUNT OpenloadCo: TRAFFIC LEFT PATTERN not found
28.07.2017 10:31:02 DEBUG     ACCOUNT OpenloadCo: LEECH TRAFFIC PATTERN not found
28.07.2017 10:31:02 DEBUG     ACCOUNT OpenloadCo: Account info for user `som*******`: {'login': {'timestamp': 1501201861.471007, 'password': '**********', 'valid': True}, 'data': {'premium': False, 'plugin': <Account OpenloadCo>, 'leecht
raffic': None, 'trafficleft': None, 'maxtraffic': None, 'validuntil': None, 'login': 'som*******', 'type': 'OpenloadCo', 'options': {'limitdl': ['0']}}}
28.07.2017 10:31:02 INFO      Activating Plugins...
28.07.2017 10:31:02 DEBUG     ADDON ExternalScripts: No script found under folder `pyload_start`
28.07.2017 10:31:02 DEBUG     Redirected import module.plugins.internal.UnRar -> userplugins.internal.UnRar
28.07.2017 10:31:03 DEBUG     Redirected import module.plugins.internal.SevenZip -> userplugins.internal.SevenZip
28.07.2017 10:31:03 DEBUG     Redirected import module.plugins.internal.UnZip -> userplugins.internal.UnZip
28.07.2017 10:31:03 DEBUG     Redirected import module.plugins.internal.UnTar -> userplugins.internal.UnTar
28.07.2017 10:31:03 DEBUG     ADDON ExtractArchive: Found UnRar 5.30 | Found UnZip 2.7.12 | Found UnTar 2.7.12
28.07.2017 10:31:03 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.07.2017 10:31:03 INFO      pyLoad is up and running
28.07.2017 10:31:03 INFO      ADDON UpdateManager: pyLoad is up to date!
28.07.2017 10:31:03 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.07.2017 10:31:03 DEBUG     ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'Ddlsto
rageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'
accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadC
c'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts
', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom
'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'cryp
ter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u
'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezC
om'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'
hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNe
t'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hook
s', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks'
, u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'R
ealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks',
 u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToas
tNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Kee
p2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4M
e'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh
'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCa
ptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
28.07.2017 10:31:03 INFO      ADDON UpdateManager: All plugins are up to date!
28.07.2017 10:31:09 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
~~~

Thanks

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by somerandom48** [comment]
I have sent them through.

Thanks

**Comment by GammaC0de** [comment]
Plugin updated, please test.

**Comment by somerandom48** [comment]
Yes it is working now

Thanks heaps!
