### ISSUE TITLE
ACCOUNT RealdebridCom: Could not login user  | Login handshake has failed

### ISSUE THREAD

**Issue by ozooha** [pyload/pyload#2936]
Get the following error for:
`19.08.2017 11:21:52 INFO      ACCOUNT RealdebridCom: Adding user `ozo*******`...
19.08.2017 11:21:52 DEBUG     ACCOUNT RealdebridCom: Reached login timeout for user `ozo*******`
19.08.2017 11:21:52 INFO      ACCOUNT RealdebridCom: Login user `ozo*******`...
19.08.2017 11:21:52 DEBUG     ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/rest/1.0/user | redirect=True | cookies=True | get={'auth_token': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
19.08.2017 11:21:53 ERROR     ACCOUNT RealdebridCom: Could not login user `ozo*******` | Login handshake has failed
Traceback (most recent call last):
  File "/opt/pyload/pyLoadCore.py", line 667, in <module>
    main()
  File "/opt/pyload/pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "/opt/pyload/pyLoadCore.py", line 433, in start
    self.accountManager.getAccountInfos()
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/plugins/AccountManager.py", line 176, in getAccountInfos
    data[p.__name__] = p.getAllAccounts(force)
  File "/opt/pyload/module/plugins/internal/misc.py", line 230, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 279, in getAllAccounts
    self.init_accounts()  # @TODO: Recheck in 0.4.10
  File "/opt/pyload/module/plugins/internal/misc.py", line 230, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 267, in init_accounts
    self.add(user, info['password'], info['options'])
  File "/opt/pyload/module/plugins/internal/misc.py", line 230, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 313, in add
    result = u['plugin'].choose(user)
  File "/opt/pyload/module/plugins/internal/misc.py", line 230, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 430, in choose
    self.relogin()
  File "/opt/pyload/module/plugins/internal/Account.py", line 177, in relogin
    return self.login()
  File "/opt/pyload/module/plugins/internal/Account.py", line 118, in login
    self.info['data'])
  File "/opt/pyload/module/plugins/accounts/RealdebridCom.py", line 56, in signin
    self.fail_login()
  File "/opt/pyload/module/plugins/internal/Account.py", line 446, in fail_login
    return self.fail(msg)
  File "/opt/pyload/module/plugins/internal/Plugin.py", line 158, in fail
    raise Fail(encode(msg))  # @TODO: Remove `encode` in 0.4.10
Fail: Login handshake has failed
`

**Comment by GammaC0de** [comment]
@ozooha Password for RealdebridCom should be  the API token (get is from http://real-debrid.com/apitoken)

**Comment by ozooha** [comment]
It gives me the same error inspite of replacing the password with the apitoken you mentioned above. Do I have clean restart something to take effect?

**Comment by GammaC0de** [comment]
I don't think so but it doesn't hurt..
Also, please post the log.

**Comment by ozooha** [comment]
Here you that is the log for the run after replacing the password with the apitoken as suggested by you.


19.08.2017 22:22:55 INFO      ACCOUNT RealdebridCom: Adding user `ozo*******`...
19.08.2017 22:22:55 DEBUG     ACCOUNT RealdebridCom: Reached login timeout for user `ozo*******`
19.08.2017 22:22:55 INFO      ACCOUNT RealdebridCom: Login user `ozo*******`...
19.08.2017 22:22:55 DEBUG     ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/rest/1.0/user | redirect=True | cookies=True | get={'auth_token': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
19.08.2017 22:22:56 ERROR     ACCOUNT RealdebridCom: Could not login user `ozo*******` | Login handshake has failed
Traceback (most recent call last):
  File "/opt/pyload/pyLoadCore.py", line 667, in <module>
    main()
  File "/opt/pyload/pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "/opt/pyload/pyLoadCore.py", line 433, in start
    self.accountManager.getAccountInfos()
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/plugins/AccountManager.py", line 176, in getAccountInfos
    data[p.__name__] = p.getAllAccounts(force)
  File "/opt/pyload/module/plugins/internal/misc.py", line 230, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 279, in getAllAccounts
    self.init_accounts()  # @TODO: Recheck in 0.4.10
  File "/opt/pyload/module/plugins/internal/misc.py", line 230, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 267, in init_accounts
    self.add(user, info['password'], info['options'])
  File "/opt/pyload/module/plugins/internal/misc.py", line 230, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 313, in add
    result = u['plugin'].choose(user)
  File "/opt/pyload/module/plugins/internal/misc.py", line 230, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 430, in choose
    self.relogin()
  File "/opt/pyload/module/plugins/internal/Account.py", line 177, in relogin
    return self.login()
  File "/opt/pyload/module/plugins/internal/Account.py", line 118, in login
    self.info['data'])
  File "/opt/pyload/module/plugins/accounts/RealdebridCom.py", line 63, in signin
    self.fail_login()
  File "/opt/pyload/module/plugins/internal/Account.py", line 446, in fail_login
    return self.fail(msg)
  File "/opt/pyload/module/plugins/internal/Plugin.py", line 158, in fail
    raise Fail(encode(msg))  # @TODO: Remove `encode` in 0.4.10
Fail: Login handshake has failed

**Comment by ozooha** [comment]
Nevermind it got solved. I had put in the wrong userid.

**Comment by GammaC0de** [comment]
👍
