### ISSUE TITLE
NitroFlare - Fail: Account Login Requires Recaptcha

### ISSUE THREAD

**Issue by ozooha** [pyload/pyload#2937]
Below is the log for the issue with **Nitroflare**:

20.08.2017 10:00:19 INFO      ACCOUNT NitroflareCom: Adding user `102*******`...
20.08.2017 10:00:19 DEBUG     ACCOUNT NitroflareCom: Reached login timeout for user `102*******`
20.08.2017 10:00:19 INFO      ACCOUNT NitroflareCom: Login user `102*******`...
20.08.2017 10:00:19 DEBUG     ACCOUNT NitroflareCom: LOAD URL https://nitroflare.com/api/v2/getKeyInfo | redirect=True | cookies=True | get={'premiumKey': '**********', 'user': '102*******'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
20.08.2017 10:00:19 ERROR     ACCOUNT NitroflareCom: Could not login user `102*******` | Account Login Requires Recaptcha
Traceback (most recent call last):
  File "/opt/pyload/pyLoadCore.py", line 667, in <module>
    main()
  File "/opt/pyload/pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "/opt/pyload/pyLoadCore.py", line 433, in start
    self.accountManager.getAccountInfos()
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/plugins/AccountManager.py", line 176, in getAccountInfos
    data[p.__name__] = p.getAllAccounts(force)
  File "/opt/pyload/module/plugins/internal/misc.py", line 230, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 279, in getAllAccounts
    self.init_accounts()  # @TODO: Recheck in 0.4.10
  File "/opt/pyload/module/plugins/internal/misc.py", line 230, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 267, in init_accounts
    self.add(user, info['password'], info['options'])
  File "/opt/pyload/module/plugins/internal/misc.py", line 230, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 313, in add
    result = u['plugin'].choose(user)
  File "/opt/pyload/module/plugins/internal/misc.py", line 230, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 430, in choose
    self.relogin()
  File "/opt/pyload/module/plugins/internal/Account.py", line 177, in relogin
    return self.login()
  File "/opt/pyload/module/plugins/internal/Account.py", line 118, in login
    self.info['data'])
  File "/opt/pyload/module/plugins/accounts/NitroflareCom.py", line 56, in signin
    self.fail_login(_("Account Login Requires Recaptcha"))
  File "/opt/pyload/module/plugins/internal/Account.py", line 446, in fail_login
    return self.fail(msg)
  File "/opt/pyload/module/plugins/internal/Plugin.py", line 158, in fail
    raise Fail(encode(msg))  # @TODO: Remove `encode` in 0.4.10
Fail: Account Login Requires Recaptcha

**Comment by GammaC0de** [comment]
Unfortunately, there is nothing that can be done (pyload does not support logging-in with captcha).

Just wait some time and then retry, hopefully this will not happen again.
