### ISSUE TITLE
LinkSnappy Plugin on QPyload (QNAP)

### ISSUE THREAD

**Issue by taK1993** [pyload/pyload#2938]
Hello,

I'm just installed this version: qoolbox.fr/QPyload_170116_x86_64.zip for QNAP QTS 4.3.x

I add a premium account for LinkSnappy, but it shows me "valid" but not as "premium".

Maybe someone can help me to solve the problem.

Thank you very much.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
Please send the PIN code from your email.

**Comment by taK1993** [comment]
Hello,
PIN Code:
1CAK8

**Comment by taK1993** [comment]
I changed my password.

When i use "!" in my password pyload crash with error 500.

I've delete the account via ssh on path:
/share/CACHEDEV1_DATA/.qpkg/QPyload/CONFIG/accounts.conf

**Comment by GammaC0de** [comment]
Plugin updated, please test.

**Comment by taK1993** [comment]
Thanks, but after the fix:

HTTP Response 500

Traceback (most recent call last):
File "/share/CACHEDEV1_DATA/.qpkg/QPyload/pyload-stable/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/share/CACHEDEV1_DATA/.qpkg/QPyload/pyload-stable/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/share/CACHEDEV1_DATA/.qpkg/QPyload/pyload-stable/module/web/utils.py", line 113, in _view
return func(*args, **kwargs)
File "/share/CACHEDEV1_DATA/.qpkg/QPyload/pyload-stable/module/web/pyload_app.py", line 256, in config
accs = PYLOAD.getAccounts(False)
File "/share/CACHEDEV1_DATA/.qpkg/QPyload/pyload-stable/module/Api.py", line 880, in getAccounts
for acc in group])
KeyError: 'validuntil'

**Comment by taK1993** [comment]
@GammaC0de 
Now it works.

Thank you very much !!

**Comment by GammaC0de** [comment]
👍
