### ISSUE TITLE
ShareOnlineBiz doesn't login

### ISSUE THREAD

**Issue by mationic** [pyload/pyload#3042]
Fresh install from stable branch.
Added share-online.biz account doesn't work:

```
05.12.2017 18:14:03 INFO      ACCOUNT ShareonlineBiz: Adding user `074*******`...
05.12.2017 18:14:03 DEBUG     ACCOUNT ShareonlineBiz: Reached login timeout for user `074*******`
05.12.2017 18:14:03 INFO      ACCOUNT ShareonlineBiz: Login user `074*******`...
05.12.2017 18:14:03 DEBUG     ACCOUNT ShareonlineBiz: LOAD URL https://api.share-online.biz/cgi-bin | redirect=True | cookies=True | get={'q': 'userdetails', 'aux': 'traffic', 'username': '074*******', 'password': '**********'} | req=None | decode=False | multipart=False | post={} | ref=True | just_header=False
05.12.2017 18:14:03 ERROR     ACCOUNT ShareonlineBiz: Could not login user `074*******` | Bad server response: 403 Forbidden
Traceback (most recent call last):
  File "./pyLoadCore.py", line 685, in <module>
    main()
  File "./pyLoadCore.py", line 676, in main
    pyload_core.start()
  File "./pyLoadCore.py", line 445, in start
    self.accountManager.getAccountInfos()
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/plugins/AccountManager.py", line 176, in getAccountInfos
    data[p.__name__] = p.getAllAccounts(force)
  File "/opt/pyload/module/plugins/internal/misc.py", line 231, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 279, in getAllAccounts
    self.init_accounts()  # @TODO: Recheck in 0.4.10
  File "/opt/pyload/module/plugins/internal/misc.py", line 231, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 267, in init_accounts
    self.add(user, info['password'], info['options'])
  File "/opt/pyload/module/plugins/internal/misc.py", line 231, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 313, in add
    result = u['plugin'].choose(user)
  File "/opt/pyload/module/plugins/internal/misc.py", line 231, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 430, in choose
    self.relogin()
  File "/opt/pyload/module/plugins/internal/Account.py", line 177, in relogin
    return self.login()
  File "/opt/pyload/module/plugins/internal/Account.py", line 118, in login
    self.info['data'])
  File "/opt/pyload/module/plugins/accounts/ShareonlineBiz.py", line 64, in signin
    api_info = self.api_response(user, password)
  File "/opt/pyload/module/plugins/accounts/ShareonlineBiz.py", line 24, in api_response
    decode=False)
  File "/opt/pyload/module/plugins/internal/Plugin.py", line 213, in load
    decode is True)  # @TODO: Fix network multipart in 0.4.10
  File "/opt/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/opt/pyload/module/network/HTTPRequest.py", line 232, in load
    self.code = self.verifyHeader()
  File "/opt/pyload/module/network/HTTPRequest.py", line 248, in verifyHeader
    raise BadHeader(code, self.header, self.getResponse())
BadHeader: Bad server response: 403 Forbidden
```

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by mationic** [comment]
Just deleted & readded the account (again). Login works fine now. Will reopen if error reoccurs.
