### ISSUE TITLE
WebUI not loading

### ISSUE THREAD

**Issue by UDZGuru** [pyload/pyload#3043]
Hi all. Since the latest git-pull about 10 hours ago my WebUI fails to load with the following error message (I enabled debug mode to get this): 

```
Critical error while processing request:

Error:

TemplateNotFound()
Traceback:

Traceback (most recent call last):
  File "/opt/pyload/module/lib/bottle.py", line 820, in wsgi
    out = self._cast(self._handle(environ), request, response)
  File "/opt/pyload/module/lib/bottle.py", line 773, in _cast
    out = self.error_handler.get(out.status, repr)(out)
  File "/opt/pyload/module/web/pyload_app.py", line 83, in error500
    error.traceback.replace("\n", "
") if error.traceback else "No Traceback"])
  File "/opt/pyload/module/web/pyload_app.py", line 72, in base
    return render_to_response('base.html', {'messages': messages}, [pre_processor])
  File "/opt/pyload/module/web/utils.py", line 29, in render_to_response
    t = env.get_template(TEMPLATE + "/" + name)
  File "/opt/pyload/module/lib/jinja2/environment.py", line 716, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/pyload/module/lib/jinja2/environment.py", line 690, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/pyload/module/lib/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/pyload/module/lib/jinja2/loaders.py", line 339, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: default/base.html
```

I tried googling and found that there were issues with jinja2 some years ago. But according to https://github.com/pyload/pyload/issues/2362 jinja2 is not used anymore. I am confused. Can anyone help?

**Comment by GammaC0de** [comment]
The "default" web theme was renamed to "classic"

What you have to do is stop pyload and edit pyload.conf
change "default" webinterface to "classic"

Thats it.

**Comment by UDZGuru** [comment]
Thanks! That solved the issue. 

BTW: Are there other themes in the stable branch?

**Comment by GammaC0de** [comment]
There are https://github.com/xunil75/PyPlex and https://github.com/OzzieIsaacs/pyload-NextTheme.

**Comment by regpa** [comment]
I have the following log when I request the ```:8000``` port
this is a fresh install of the stable branch on a RPI with raspbian stretch.
I don't find any ```pyload.conf``` file under the pyload base directory, so I cannot apply the fix proposed by @GammaC0de, could you tell me what put me away of the track ?
 
```
An error occured while processing the request.
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/module/web/pyload_app.py", line 169, in home
    return render_to_response("home.html", {"res": res}, [pre_processor])
  File "/usr/share/pyload/module/web/utils.py", line 29, in render_to_response
    t = env.get_template(TEMPLATE + "/" + name)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 360, in load
    loader, local_name = self.get_loader(name)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 346, in get_loader
    raise TemplateNotFound(template)
TemplateNotFound: default/home.html'
<h1>Critical error while processing request: </h1>
30.12.2017 01:45:11 INFO      ADDON UpdateManager: pyLoad is up to date!

```

**Comment by GammaC0de** [comment]
@regpa Use `find / -name "pyload.conf"` to find the location of pyload.conf.

**Comment by regpa** [comment]
as a matter of fact, all the config files were under /home/pi instead of /home/pyload, after having moved then all it worked as a charm
thanks @GammaC0de for your help, you put me on the right track
