### ISSUE TITLE
Critical error while processing request: /login

### ISSUE THREAD

**Issue by R3alflash** [pyload/pyload#3052]
Hey,

i have the same issue since my last reboot of my Asustor NAS.

i have tryed this: https://github.com/pyload/pyload/issues/3045

but nothing happens

```
Critical error while processing request: /login
Error:

TemplateNotFound()

Traceback:

Traceback (most recent call last):
  File "/volume1/.@plugins/AppCentral/pyload/pyload/module/lib/bottle.py", line 820, in wsgi
    out = self._cast(self._handle(environ), request, response)
  File "/volume1/.@plugins/AppCentral/pyload/pyload/module/lib/bottle.py", line 773, in _cast
    out = self.error_handler.get(out.status, repr)(out)
  File "/volume1/.@plugins/AppCentral/pyload/pyload/module/web/pyload_app.py", line 83, in error500
    error.traceback.replace("\n", "
") if error.traceback else "No Traceback"])
  File "/volume1/.@plugins/AppCentral/pyload/pyload/module/web/pyload_app.py", line 72, in base
    return render_to_response('base.html', {'messages': messages}, [pre_processor])
  File "/volume1/.@plugins/AppCentral/pyload/pyload/module/web/utils.py", line 29, in render_to_response
    t = env.get_template(TEMPLATE + "/" + name)
  File "/volume1/.@plugins/AppCentral/pyload/pyload/module/lib/jinja2/environment.py", line 716, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/volume1/.@plugins/AppCentral/pyload/pyload/module/lib/jinja2/environment.py", line 690, in _load_template
    template = self.loader.load(self, name, globals)
  File "/volume1/.@plugins/AppCentral/pyload/pyload/module/lib/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/volume1/.@plugins/AppCentral/pyload/pyload/module/lib/jinja2/loaders.py", line 339, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: default/base.html
```

The Output of
 `PKG_DIR="/usr/local/AppCentral/pyload"
ARCH=$(/bin/uname -m)
if [ "$ARCH" = "x86_64" ]; then
REPOS_DIR="$PKG_DIR/repository"
else
REPOS_DIR="$PKG_DIR/repository-32"
fi
export PYTHONPATH=$REPOS_DIR/lib/python
export LD_LIBRARY_PATH=$REPOS_DIR/usr/lib
cd $PKG_DIR/pyload/
/usr/local/bin/python2.7 ./pyLoadCore.py --configdir=$PKG_DIR/config -d`

is

````

> 21.12.2017 16:38:52 INFO      Starting pyLoad 0.4.9
> 21.12.2017 16:38:52 INFO      Using home directory: /volume1/.@plugins/AppCentral/pyload/config
> 21.12.2017 16:38:52 DEBUG     Remote activated: True
> 21.12.2017 16:38:53 DEBUG     created index of plugins
> 21.12.2017 16:38:53 INFO      Activated plugins: AntiStandby, ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, LinkdecrypterComHook, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
> 21.12.2017 16:38:53 INFO      Deactivate plugins: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
> 21.12.2017 16:38:53 INFO      Downloadtime: True
> 21.12.2017 16:38:53 INFO      Starting ThriftBackend: 0.0.0.0:7227
> 21.12.2017 16:38:53 ERROR     Remote backend error: [Errno 98] Address already in use
> Traceback (most recent call last):
>   File "/volume1/.@plugins/AppCentral/pyload/pyload/module/remote/RemoteManager.py", line 33, in run
>     self.serve()
>   File "/volume1/.@plugins/AppCentral/pyload/pyload/module/remote/ThriftBackend.py", line 56, in serve
>     self.server.serve()
>   File "/usr/local/AppCentral/python/lib/python2.7/site-packages/thrift/server/TServer.py", line 102, in serve
>     self.serverTransport.listen()
>   File "/volume1/.@plugins/AppCentral/pyload/pyload/module/remote/thriftbackend/Socket.py", line 122, in listen
>     self.handle.bind((self.host, self.port))
>   File "/usr/local/AppCentral/python/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> error: [Errno 98] Address already in use
> 21.12.2017 16:38:53 INFO      Free space: 1.14 TiB
> 21.12.2017 16:38:53 INFO      Activating Accounts...
> 21.12.2017 16:38:53 INFO      Activating Plugins...
> 21.12.2017 16:38:53 INFO      Starting threaded webserver: 0.0.0.0:9050
> 21.12.2017 16:38:53 DEBUG     ADDON ExternalScripts: No script found under folder `pyload_start`
> Exception in thread Thread-6:
> Traceback (most recent call last):
>   File "/usr/local/AppCentral/python/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/volume1/.@plugins/AppCentral/pyload/pyload/module/web/ServerThread.py", line 71, in run
>     self.start_threaded()
>   File "/volume1/.@plugins/AppCentral/pyload/pyload/module/web/ServerThread.py", line 93, in start_threaded
>     webinterface.run_threaded(host=self.host, port=self.port, cert=self.cert, key=self.key)
>   File "/volume1/.@plugins/AppCentral/pyload/pyload/module/web/webinterface.py", line 153, in run_threaded
>     run(app=web, host=host, port=port, server=CherryPyWSGI, quiet=True)
>   File "/volume1/.@plugins/AppCentral/pyload/pyload/module/lib/bottle.py", line 2383, in run
>     server.run(app)
>   File "/volume1/.@plugins/AppCentral/pyload/pyload/module/web/utils.py", line 137, in run
>     server.start()
>   File "/volume1/.@plugins/AppCentral/pyload/pyload/module/lib/wsgiserver/__init__.py", line 1596, in start
>     raise socket.error, msg
> error: [Errno 98] Address already in use
> 
> 21.12.2017 16:38:53 WARNING   ADDON AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
> 21.12.2017 16:38:53 WARNING   ADDON AntiStandby: Unable to change display power state | [Errno 2] No such file or directory
> 21.12.2017 16:38:53 DEBUG     ADDON ExtractArchive: Found SevenZip 9.20 | Found UnZip 2.7.10 | Found UnTar 2.7.10
> 21.12.2017 16:38:53 ERROR     Error importing TurbobitNet: /usr/local/AppCentral/pyload/repository/lib/python/Crypto/Cipher/_ARC4.so: undefined symbol: PyUnicodeUCS4_FromString
> Traceback (most recent call last):
>   File "/volume1/.@plugins/AppCentral/pyload/pyload/module/plugins/PluginManager.py", line 301, in loadModule
>     plugins[name]["name"])
>   File "/volume1/.@plugins/AppCentral/pyload/pyload/module/plugins/hoster/TurbobitNet.py", line 9, in <module>
>     import Crypto.Cipher.ARC4
>   File "/usr/local/AppCentral/pyload/repository/lib/python/Crypto/Cipher/ARC4.py", line 66, in <module>
>     from Crypto.Cipher import _ARC4
> ImportError: /usr/local/AppCentral/pyload/repository/lib/python/Crypto/Cipher/_ARC4.so: undefined symbol: PyUnicodeUCS4_FromString
> 21.12.2017 16:38:53 INFO      ADDON XFileSharing: Auto-discover new hosters
> 21.12.2017 16:38:53 DEBUG     ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com|clicknupload\.org|cramit\.in|easybytez\.com|exashare\.com|filejoker\.net|fileom\.com|filerio\.com|fistfast\.net|hugefiles\.net|junocloud\.me|movreel\.com|nosupload\.com|novafile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|streamcloud\.eu|tusfiles\.net|uploadrocket\.net|uptobox\.com|vidplay\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
> 21.12.2017 16:38:53 INFO      ADDON XFileSharing: Auto-discover new crypters
> 21.12.2017 16:38:53 DEBUG     ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
> 21.12.2017 16:38:53 DEBUG     ADDON UpdateManager: LOAD URL https://github.com/pyload/updates/raw/master/plugins.txt | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
> 21.12.2017 16:38:53 INFO      pyLoad is up and running
> 21.12.2017 16:38:54 INFO      ADDON UpdateManager: pyLoad is up to date!
> 21.12.2017 16:38:54 DEBUG     ADDON UpdateManager: LOAD URL https://github.com/pyload/updates/raw/master/plugins.txt | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
> 21.12.2017 16:38:55 DEBUG     ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'FreeWayMe'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
> 21.12.2017 16:38:55 INFO      ADDON UpdateManager: All plugins are up to date!
> 21.12.2017 16:38:59 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
> 21.12.2017 16:38:59 ERROR     ADDON ClickNLoad: [Errno 98] Address already in use
> Traceback (most recent call last):
>   File "/usr/local/AppCentral/python/lib/python2.7/threading.py", line 783, in __bootstrap
>     self.__bootstrap_inner()
>   File "/usr/local/AppCentral/python/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/volume1/.@plugins/AppCentral/pyload/pyload/module/PluginThread.py", line 466, in run
>     self.f(*self.args, **self.kwargs)
>   File "/volume1/.@plugins/AppCentral/pyload/pyload/module/plugins/hooks/ClickNLoad.py", line 107, in _server
>     dock_socket.bind((self.cnl_ip, self.cnl_port))
>   File "/usr/local/AppCentral/python/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> error: [Errno 98] Address already in use


Can u help me?

**Comment by GammaC0de** [comment]
See https://github.com/pyload/pyload/issues/3043#issuecomment-349409012

**Comment by R3alflash** [comment]
yeah, ty :D

/closed

**Comment by GammaC0de** [comment]
👍
