### ISSUE TITLE
Cannot install through build

### ISSUE THREAD

**Issue by Festum** [pyload/pyload#3081]
```
python setup.py build
/home/festum/.local/lib/python2.7/site-packages/setuptools/dist.py:355: UserWarning: Normalizing '1.0.0-alpha' to '1.0.0a0'
  normalized_version,
running build
running build_py
running build_locale
Traceback (most recent call last):
  File "setup.py", line 172, in <module>
    zip_safe=True)
  File "/home/festum/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 111, in run
    self.run_command('build_locale')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 970, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 846, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "/home/festum/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 147, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib/python2.7/distutils/cmd.py", line 64, in __init__
    self.initialize_options()
  File "/usr/lib/python2.7/distutils/cmd.py", line 136, in initialize_options
    "abstract method -- subclass %s must override" % self.__class__
RuntimeError: abstract method -- subclass __main__.BuildLocale must override
```

**Comment by GammaC0de** [comment]
See https://github.com/pyload/pyload/issues/2000

**Comment by Zapeth** [comment]
Reverting the changes from https://github.com/pyload/pyload/commit/cee1f162f6d8ef4b7c9d16954dd00237e257cfc9 fixed the errors for me.

**Comment by GammaC0de** [comment]
OK, so closing. 👍

**Comment by pyblub** [comment]
Isn't this a change in master and not in stable? You should install stable.

**Comment by Zapeth** [comment]
Well it looks like it doesn't work at all in stable due to a changed location of setup.py (probably the reason for this question https://github.com/pyload/pyload/issues/3048 ), though I can't say whether this is intentional or not since I'm not really familiar with the (development of the) project.
