### ISSUE TITLE
[Errno 107] Transport endpoint is not connected

### ISSUE THREAD

**Issue by alesnav** [pyload/pyload#3090]
Hello there!

I'm trying to use Pyload in a fresh install (using stable release), but it shows an error each 2 seconds in the log.:
```
Exception in thread Thread-115:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/thrift/server/TServer.py", line 118, in handle
    itrans = self.inputTransportFactory.getTransport(client)
  File "/opt/pyload/module/remote/thriftbackend/Transport.py", line 24, in getTransport
    buffered = Transport(trans)
  File "/opt/pyload/module/remote/thriftbackend/Transport.py", line 12, in __init__
    self.remoteaddr = trans.handle.getpeername()
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected

Exception in thread Thread-116:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/thrift/server/TServer.py", line 119, in handle
    otrans = self.outputTransportFactory.getTransport(client)
  File "/opt/pyload/module/remote/thriftbackend/Transport.py", line 24, in getTransport
    buffered = Transport(trans)
  File "/opt/pyload/module/remote/thriftbackend/Transport.py", line 12, in __init__
    self.remoteaddr = trans.handle.getpeername()
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected
```

When I execute pyload, it shows a single message after "`04.02.2018 18:15:28 INFO      ADDON UpdateManager: pyLoad is up to date!`" that maybe is related to the `Errno 107`:
```
No handlers could be found for logger "thrift.server.TServer"
```

Thanks,  
Best regards

**Comment by GammaC0de** [comment]
I think you should remove thrift because pyLoad has an older version included on your version is probably incompatible..

**Comment by GammaC0de** [comment]
Did you m anaged to solve this?

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by alesnav** [comment]
Hello again,

Sorry for the delay... I wasn't able to fix this problem.

I have tried to get it installed using the [docker image](https://hub.docker.com/r/writl/pyload/) with the same result:

```
error: [Errno 107] Transport endpoint is not connected
```

Any idea? :/

Thanks!

**Comment by GammaC0de** [comment]
Diy you do `sudo pip uninstall thrift`?

**Comment by alesnav** [comment]
Yes, I did it.

And finally, I tried to do it with a docker container to avoid any problem related to my server. But I get the same result and I don't know how to continue with the troubleshooting :(

Thanks

**Comment by GammaC0de** [comment]
Post the log again please

**Comment by alesnav** [comment]
Yep. It shows many 107 errors and some 104, too.

```
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/thrift/server/TServer.py", line 115, in handle
    itrans = self.inputTransportFactory.getTransport(client)
  File "/opt/pyload/module/remote/thriftbackend/Transport.py", line 24, in getTransport
    buffered = Transport(trans)
  File "/opt/pyload/module/remote/thriftbackend/Transport.py", line 12, in __init__
    self.remoteaddr = trans.handle.getpeername()
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/thrift/server/TServer.py", line 115, in handle
    itrans = self.inputTransportFactory.getTransport(client)
  File "/opt/pyload/module/remote/thriftbackend/Transport.py", line 24, in getTransport
    buffered = Transport(trans)
  File "/opt/pyload/module/remote/thriftbackend/Transport.py", line 12, in __init__
    self.remoteaddr = trans.handle.getpeername()
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected
ERROR:root:[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/thrift/server/TServer.py", line 121, in handle
    self.processor.process(iprot, oprot)
  File "/opt/pyload/module/remote/thriftbackend/Processor.py", line 23, in process
    (name, type, seqid) = iprot.readMessageBegin()
  File "/usr/lib/python2.7/dist-packages/thrift/protocol/TBinaryProtocol.py", line 126, in readMessageBegin
    sz = self.readI32()
  File "/usr/lib/python2.7/dist-packages/thrift/protocol/TBinaryProtocol.py", line 206, in readI32
    buff = self.trans.readAll(4)
  File "/usr/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 58, in readAll
    chunk = self.read(sz - have)
  File "/usr/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 159, in read
    self.__rbuf = StringIO(self.__trans.read(max(sz, self.__rbuf_size)))
  File "/opt/pyload/module/remote/thriftbackend/Socket.py", line 67, in read
    buff = self.handle.recv(sz)
error: [Errno 104] Connection reset by peer
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/thrift/server/TServer.py", line 115, in handle
    itrans = self.inputTransportFactory.getTransport(client)
  File "/opt/pyload/module/remote/thriftbackend/Transport.py", line 24, in getTransport
    buffered = Transport(trans)
  File "/opt/pyload/module/remote/thriftbackend/Transport.py", line 12, in __init__
    self.remoteaddr = trans.handle.getpeername()
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected
```

**Comment by GammaC0de** [comment]
I am sorry but `thrift` is still installed:
`File "/usr/lib/python2.7/dist-packages/thrift/server/TServer.py", line 115, in handle`

Maybe you should run `sudo python2.7 -m pip uninstall thrift`
