### ISSUE TITLE
Alldebrid does not work

### ISSUE THREAD

**Issue by t3uch1** [pyload/pyload#3116]
Hello

I just installed Pyload on Kodi18 LEIA via libreelec, everything works except that you can not download premium via Alldebrid, when I activate the plugin, it turns off, and the link goes through Uptobox or other but not Alldebrid here the log

```
LibreELEC:~ # killall python
LibreELEC:~ # ADDON_DIR="$HOME/.kodi/addons/service.downloadmanager.pyload"
LibreELEC:~ # ADDON_HOME="$HOME/.kodi/userdata/addon_data/service.downloadmanager.pyload"
LibreELEC:~ # export PYTHONPATH="$PYTHONPATH:$ADDON_DIR/pylib" 
LibreELEC:~ # python $ADDON_DIR/pyload/pyLoadCore.py -d --configdir=$ADDON_HOME
26.02.2018 23:20:18 INFO      Démarrage pyLoad 0.4.9
26.02.2018 23:20:18 INFO      Utilisation du dossier principal : /storage/.kodi/userdata/addon_data/service.downloadmanager.pyload
26.02.2018 23:20:18 DEBUG     Deleting old pidfile pyload.pid
26.02.2018 23:20:18 DEBUG     Remote activated: True
26.02.2018 23:20:19 DEBUG     created index of plugins
26.02.2018 23:20:19 INFO      Plugins activés: CaptchaTrader, ClickAndLoad, ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, LinkdecrypterCom, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing, XFileSharingPro
26.02.2018 23:20:19 INFO      Plugins désactivés: AlldebridCom, AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, HotFolder, IRC, IRCInterface, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, MultishareCz, Premium4Me, PremiumizeMe, PushBullet, PushOver, RealdebridCom, RehostTo, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP, XMPPInterface, ZeveraCom
26.02.2018 23:20:19 INFO      Temps de téléchargement : True
26.02.2018 23:20:19 INFO      Démarre ThriftBackend: 0.0.0.0:7227
26.02.2018 23:20:20 INFO      Starting threaded webserver: 0.0.0.0:8000
26.02.2018 23:20:20 INFO      Free space: 129.45 GiB
26.02.2018 23:20:20 INFO      Activating Accounts...
26.02.2018 23:20:20 INFO      ACCOUNT AlldebridCom: Adding user `t3uch1`...
26.02.2018 23:20:20 DEBUG     ACCOUNT AlldebridCom: Reached login timeout for user `t3uch1`
26.02.2018 23:20:20 INFO      ACCOUNT AlldebridCom: Login user `t3uch1`...
26.02.2018 23:20:20 DEBUG     ACCOUNT AlldebridCom: LOAD URL https://www.alldebrid.com/register/ | redirect=True | cookies=True | get={'action': 'login', 'login_login': 't3uch1', 'login_password': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
26.02.2018 23:20:21 INFO      ACCOUNT AlldebridCom: Grabbing account info for user `t3uch1`...
26.02.2018 23:20:21 DEBUG     ACCOUNT AlldebridCom: LOAD URL http://www.alldebrid.com/account/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
26.02.2018 23:20:21 DEBUG     ACCOUNT AlldebridCom: Account expires in:  164 days 14 hours and 7 minutes
26.02.2018 23:20:21 DEBUG     ACCOUNT AlldebridCom: Account info for user `t3uch1`: {'login': {'timestamp': 1519687220.5622611, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account AlldebridCom>, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1533907581.445482, 'login': 't3uch1', 'type': 'AlldebridCom', 'options': {'limitdl': ['0']}}}
26.02.2018 23:20:21 INFO      ACCOUNT AlldebridCom: Grabbing account info for user `t3uch1`...
26.02.2018 23:20:21 DEBUG     ACCOUNT AlldebridCom: LOAD URL http://www.alldebrid.com/account/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
26.02.2018 23:20:21 DEBUG     ACCOUNT AlldebridCom: Account expires in:  164 days 14 hours and 7 minutes
26.02.2018 23:20:21 DEBUG     ACCOUNT AlldebridCom: Account info for user `t3uch1`: {'login': {'timestamp': 1519687220.5622611, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account AlldebridCom>, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1533907581.8291171, 'login': 't3uch1', 'type': 'AlldebridCom', 'options': {'limitdl': ['0']}}}
26.02.2018 23:20:21 INFO      Activating Plugins...
26.02.2018 23:20:22 ERROR     Error executing hooks: (6, 'Could not resolve host: linkdecrypter.com')
Traceback (most recent call last):
  File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/HookManager.py", line 88, in new
    return func(*args)
  File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/HookManager.py", line 198, in coreReady
    plugin.coreReady()
  File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/plugins/hooks/LinkdecrypterCom.py", line 33, in coreReady
    page = getURL("http://linkdecrypter.com/")
  File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/network/RequestFactory.py", line 122, in getURL
    return pyreq.getURL(*args, **kwargs)
  File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/network/RequestFactory.py", line 67, in getURL
    rep = h.load(*args, **kwargs)
  File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/network/HTTPRequest.py", line 203, in load
    self.c.perform()
error: (6, 'Could not resolve host: linkdecrypter.com')
26.02.2018 23:20:22 INFO      pyLoad is up and running
```

I tried the last Pyload Stable by replacing the files as recommended, but obviously it does not work on this distribution because Pyload does not start after copying the files and tell me this error

```
LibreELEC:~ # python $ADDON_DIR/pyload/pyLoadCore.py -d --configdir=$ADDON_HOME

26.02.2018 22:56:20 INFO      Démarrage pyLoad 0.4.9

26.02.2018 22:56:20 INFO      Utilisation du dossier principal : /storage/.kodi/userdata/addon_data/service.downloadmanager.pyload

26.02.2018 22:56:20 DEBUG     Deleting old pidfile pyload.pid

26.02.2018 22:56:20 DEBUG     Remote activated: True

26.02.2018 22:56:22 ERROR     <<< UNCAUGHT EXCEPTION >>>

Traceback (most recent call last):

  File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/pyLoadCore.py", line 685, in <module>

    main()

  File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/pyLoadCore.py", line 676, in main

    pyload_core.start()

  File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/pyLoadCore.py", line 404, in start

    self.pluginManager = PluginManager(self)

  File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/plugins/PluginManager.py", line 50, in __init__

    self.createIndex()

  File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/plugins/PluginManager.py", line 91, in createIndex

    self.hookPlugins, config = self.parse("hooks")

  File "/storage/.kodi/addons/service.downloadmanager.pyload/pyload/module/plugins/PluginManager.py", line 222, in parse

    config['activated'] = ["bool", "Activated", False]

TypeError: list indices must be integers, not str
```

At the very least, I'd like to run the old version with the functional Alldebrid plugin

Thanks

**Comment by t3uch1** [comment]
26.02.2018 23:28:53 INFO      Démarrage pyLoad 0.4.9
26.02.2018 23:28:53 INFO      Utilisation du dossier principal : /storage/.kodi/userdata/addon_data/service.downloadmanager.pyload
26.02.2018 23:28:53 DEBUG     Remote activated: True
26.02.2018 23:28:55 DEBUG     created index of plugins
26.02.2018 23:28:55 INFO      Plugins activés: CaptchaTrader, ClickAndLoad, ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, LinkdecrypterCom, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing, XFileSharingPro
26.02.2018 23:28:55 INFO      Plugins désactivés: AlldebridCom, AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, HotFolder, IRC, IRCInterface, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, MultishareCz, Premium4Me, PremiumizeMe, PushBullet, PushOver, RealdebridCom, RehostTo, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP, XMPPInterface, ZeveraCom

**Comment by GammaC0de** [comment]
How exactly did you installed service.downloadmanager.pyload? 
It seems like an old version..

**Comment by t3uch1** [comment]
problem solved by an installation of the latest console version
Thanks

**Comment by felixmosh** [comment]
@t3uch1 can you share how to install pyload on kodi?
