### ISSUE TITLE
Error when starting pyload: invalid syntax

### ISSUE THREAD

**Issue by zoomyboy** [pyload/pyload#3119]
When starting pyload, I get the following syntax error:

```
28.02.2018 23:08:22 INFO      Starting pyLoad 0.4.9
28.02.2018 23:08:22 INFO      Using home directory: /etc/pyload
28.02.2018 23:08:24 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
28.02.2018 23:08:24 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
28.02.2018 23:08:24 INFO      Downloadtime: True
28.02.2018 23:08:24 INFO      Free space: 860.94 GiB
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/pyload/module/web/ServerThread.py", line 30, in run
    import webinterface
  File "/opt/pyload/module/web/webinterface.py", line 40, in <module>
    from jinja2 import Environment, FileSystemLoader, PrefixLoader, FileSystemBytecodeCache
  File "/usr/lib/python2.7/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 486
    def _tokenize(self, source, name, filename=None,�state=None)
                                                    ^
SyntaxError: invalid syntax

28.02.2018 23:08:24 INFO      Activating Accounts...
28.02.2018 23:08:24 INFO      Activating Plugins...
28.02.2018 23:08:25 INFO      ADDON XFileSharing: Auto-discover new hosters
28.02.2018 23:08:25 INFO      ADDON XFileSharing: Auto-discover new crypters
28.02.2018 23:08:25 INFO      pyLoad is up and running
28.02.2018 23:08:27 INFO      ADDON UpdateManager: pyLoad is up to date!
28.02.2018 23:08:27 INFO      ADDON UpdateManager: All plugins are up to date!
28.02.2018 23:08:29 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
```

I cannot reach the webinterface though. What's going on here?

**Comment by zoomyboy** [comment]
Fixed. Just reinstalled Jinja2 via APT.
