### ISSUE TITLE
Settings no longer available

### ISSUE THREAD

**Issue by Bava1980** [pyload/pyload#3133]
Hi there,
I am facing a very strange error and while I was not finding some similar report I want to report it. 

After three month I just wanted to download something and got an error. By checking the logs I got this information:

> 
> 180 | 16.03.2018 08:03:38 | INFO | Activating Accounts...
> -- | -- | -- | --
> 179 | 16.03.2018 08:03:38 | INFO | Starting threaded webserver: 0.0.0.0:7272
> 178 | 16.03.2018 08:03:38 | INFO | Free space: 895.37 GiB
> 177 | 16.03.2018 08:03:36 | INFO | Starte ThriftBackend: 0.0.0.0:7227
> 176 | 16.03.2018 08:03:36 | INFO | Downloadzeit: True
> 175 | 16.03.2018 08:03:36 | INFO | Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus,  BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos,  DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler,  ExpertDecoders, ExternalScripts, HotFolder, IRC, ImageTyperz,  JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome,  PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC,  WindowsPhoneNotify, XMPP
> 174 | 16.03.2018 08:03:36 | INFO | Aktivierte Plugins:
> 173 | 16.03.2018 08:03:36 | ERROR | Fehler beim importieren von UserAgentSwitcher: No module named json
> 172 | 16.03.2018 08:03:36 | ERROR | Fehler beim importieren von XFileSharing: No module named json
> 171 | 16.03.2018 08:03:36 | ERROR | Fehler beim importieren von ExtractArchive: No module named json
> 170 | 16.03.2018 08:03:36 | ERROR | Fehler beim importieren von ClickNLoad: No module named json
> 169 | 16.03.2018 08:03:36 | ERROR | Fehler beim importieren von EventMapper: No module named json
> 168 | 16.03.2018 08:03:36 | ERROR | Fehler beim importieren von UnSkipOnFail: No module named json
> 167 | 16.03.2018 08:03:36 | ERROR | Fehler beim importieren von MergeFiles: No module named json
> 166 | 16.03.2018 08:03:36 | ERROR | Fehler beim importieren von UpdateManager: No module named json
> 165 | 16.03.2018 08:03:29 | INFO | Benutze Home-Verzeichnis: /i-data/fa351e36/admin/zy-pkgs/pyLoad/etc/pyload
> 164 | 16.03.2018 08:03:29 | INFO | starte pyLoad 0.4.9

I thought maybe there is another change in the UpdateManger-File and just downloaded the latest version (what is the same one I already have). 

I stopped Pyload, changed the file and started Pyload again. Still the same error message in the logs. 
Now I thought there is maybe a change in the options and went to the settings. Well, I am not able to access the settings. Every time i try to access I get this message: 

> An Error occured, please enable debug mode to get more details.
>
> HTTP Response 500
> 
> Traceback (most recent call last):
> File "/i-data/fa351e36/admin/zy-pkgs/pyLoad/pyload/module/lib/bottle.py", line 733, in _handle
> return route.call(**args)
> File "/i-data/fa351e36/admin/zy-pkgs/pyLoad/pyload/module/lib/bottle.py", line 1448, in wrapper
> rv = callback(*a, **ka)
> File "/i-data/fa351e36/admin/zy-pkgs/pyLoad/pyload/module/web/utils.py", line 113, in _view
> return func(*args, **kwargs)
> File "/i-data/fa351e36/admin/zy-pkgs/pyLoad/pyload/module/web/pyload_app.py", line 256, in config
> accs = PYLOAD.getAccounts(False)
> File "/i-data/fa351e36/admin/zy-pkgs/pyLoad/pyload/module/Api.py", line 875, in getAccounts
> accs = self.core.accountManager.getAccountInfos(False, refresh)
> File "/i-data/fa351e36/admin/zy-pkgs/pyLoad/pyload/module/utils.py", line 165, in new
> return func(*args)
> File "/i-data/fa351e36/admin/zy-pkgs/pyLoad/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
> p = self.getAccountPlugin(p)
> File "/i-data/fa351e36/admin/zy-pkgs/pyLoad/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
> self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
> TypeError: 'NoneType' object is not callable

After trying to access the settings I also get this information in the logs:

> 184 | 16.03.2018 08:18:27 | ERROR | Error importing ShareonlineBiz: No module named json
> -- | -- | -- | --
> 183 | 16.03.2018 08:05:41 | ERROR | Error importing ShareonlineBiz: No module named json
> 182 | 16.03.2018 08:03:57 | ERROR | Error importing ShareonlineBiz: No module named json
> 181 | 16.03.2018 08:03:38 | ERROR | Error importing ShareonlineBiz: No module named json

I thought maybe I just have to replace the bottle.py but can't find a new one. Even in the Pyload-Master file I downloaded. What can I do?
I must admit I got no knowledge about using the console. I am using the web interface.
Pyload is running on a Zyxel Nas

> Python: | 2.6.2 (r262:71600, Nov 24 2014, 22:01:21)  [GCC 4.3.2]
> -- | --
> Betriebssystem: | posix linux2 Linux MileniumFalcon 2.6.31.8 #2 Wed Jun 21 16:44:13 CST 2017 armv5tel
> pyLoad Version: | 0.4.9
> Installationsordner: | /i-data/fa351e36/admin/zy-pkgs/pyLoad/pyload
> Konfigurationsordner: | /i-data/fa351e36/admin/zy-pkgs/pyLoad/etc/pyload
> Downloadordner: | /i-data/md1/admin/pyload-download
> Freier Speicherplatz: | 895.37 GiB
> Sprache: | de
> Webinterface Port: | 7272
> Remote Interface Port: | 7227

Any ideas? 

Thank you.
Bava

**Comment by Bava1980** [comment]
Ok.. i think i found a solution. 

I just changed the name from userplugins folder in \pyLoad\etc\pyload to userpluginsBAK. After a restart a new folder was created and now I am able to access the settings again.
