### ISSUE TITLE
latest pyload stable dose not work on debian

### ISSUE THREAD

**Issue by MrIcedTea** [pyload/pyload#3143]
hi,

i can actually confirm the issue #2361 of @cavebeat cause ive got the same problem here. My approach as an believing debian user wasnt to go up to testing but to go down to stable. Maybe you could install such a debian system to and check that out. I am not a python person so i dont know what this utils are referring to... As you can see pyload v0.4.4 is (after shortly switching up and down) the latest version ive got to run (dont tryed testing):

```
wrz@debiantestingamd64box:~/bin/pyload$ git tag
v0.1
v0.1.1
v0.2
v0.2.1
v0.2.2
v0.3
v0.3.1
v0.3.2
v0.4
v0.4.1
v0.4.2
v0.4.3
v0.4.4
v0.4.5
v0.4.6
v0.4.7
v0.4.8
v0.4.9
wrz@ttpdeb03:~/bin/pyload$ git checkout v0.4.9
Note: checking out 'v0.4.9'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 903127a5d pyLoad 0.4.9
wrz@ttpdeb03:~/bin/pyload$ ls
docs   LICENSE  module       pyLoadCli.py   pyLoadGui.py  scripts    systemCheck.py  tests
icons  locale   pavement.py  pyLoadCore.py  README        setup.cfg  testlinks.txt
wrz@ttpdeb03:~/bin/pyload$ ./pyLoadCore.py 
Traceback (most recent call last):
  File "./pyLoadCore.py", line 43, in <module>
    from module.plugins.AccountManager import AccountManager
  File "/home/wrz/bin/pyload/module/plugins/AccountManager.py", line 25, in <module>
    from module.PullEvents import AccountUpdateEvent
  File "/home/wrz/bin/pyload/module/PullEvents.py", line 21, in <module>
    from module.utils import uniqify
ImportError: No module named utils
wrz@ttpdeb03:~/bin/pyload$ ./pyLoadCli.py 
Traceback (most recent call last):
  File "./pyLoadCli.py", line 45, in <module>
    from module.cli.printer import *
  File "/home/wrz/bin/pyload/module/cli/__init__.py", line 2, in <module>
    from ManageFiles import ManageFiles
  File "/home/wrz/bin/pyload/module/cli/ManageFiles.py", line 27, in <module>
    from module.Api import Destination, PackageData
  File "/home/wrz/bin/pyload/module/Api.py", line 25, in <module>
    from PyFile import PyFile
  File "/home/wrz/bin/pyload/module/PyFile.py", line 20, in <module>
    from module.PullEvents import UpdateEvent
  File "/home/wrz/bin/pyload/module/PullEvents.py", line 21, in <module>
    from module.utils import uniqify
ImportError: No module named utils
wrz@ttpdeb03:~/bin/pyload$ git checkout v0.4.7
Previous HEAD position was 903127a5d pyLoad 0.4.9
HEAD is now at a716a1e74 pyLoad 0.4.7
wrz@ttpdeb03:~/bin/pyload$ ./pyLoadCli.py 
Traceback (most recent call last):
  File "./pyLoadCli.py", line 49, in <module>
    from module.cli.printer import *
  File "/home/wrz/bin/pyload/module/cli/__init__.py", line 2, in <module>
    from ManageFiles import ManageFiles
  File "/home/wrz/bin/pyload/module/cli/ManageFiles.py", line 27, in <module>
    from module.Api import Destination, PackageData
  File "/home/wrz/bin/pyload/module/Api.py", line 27, in <module>
    from PyFile import PyFile
  File "/home/wrz/bin/pyload/module/PyFile.py", line 20, in <module>
    from module.PullEvents import UpdateEvent
  File "/home/wrz/bin/pyload/module/PullEvents.py", line 21, in <module>
    from module.utils import uniqify
ImportError: No module named utils
wrz@ttpdeb03:~/bin/pyload$ git checkout v0.3.2
Previous HEAD position was a716a1e74 pyLoad 0.4.7
HEAD is now at 3d934b204 gui version fix
wrz@ttpdeb03:~/bin/pyload$ ./pyLoadCli.py 
Benutzername: 
Adresse: 
SSL? ([y]/n): 
Port: 
Passwort: 
https://:@:/
pyLoadCore läuft nicht!
wrz@ttpdeb03:~/bin/pyload$ ./pyLoadCli.py --help
Traceback (most recent call last):
  File "./pyLoadCli.py", line 446, in <module>
    opts, extraparams = __import__("getopt").getopt(sys.argv[1:], shortOptions, longOptions)
  File "/usr/lib/python2.7/getopt.py", line 88, in getopt
    opts, args = do_longs(opts, args[0][2:], longopts, args[1:])
  File "/usr/lib/python2.7/getopt.py", line 152, in do_longs
    has_arg, opt = long_has_args(opt, longopts)
  File "/usr/lib/python2.7/getopt.py", line 169, in long_has_args
    raise GetoptError('option --%s not recognized' % opt, opt)
getopt.GetoptError: option --help not recognized
wrz@ttpdeb03:~/bin/pyload$ git checkout v0.4.2
Previous HEAD position was 3d934b204 gui version fix
HEAD is now at 9d8074cce new version strings
wrz@ttpdeb03:~/bin/pyload$ ./pyLoadCli.py 
Username: ^CTraceback (most recent call last):
  File "./pyLoadCli.py", line 533, in <module>
    if not username: username = raw_input(_("Username: "))
KeyboardInterrupt
wrz@ttpdeb03:~/bin/pyload$ git checkout v0.4.5
Previous HEAD position was 9d8074cce new version strings
HEAD is now at a74c7923c pyLoad 0.4.5
wrz@ttpdeb03:~/bin/pyload$ ./pyLoadCli.py
Traceback (most recent call last):
  File "./pyLoadCli.py", line 38, in <module>
    from module.utils import formatSize
ImportError: No module named utils
wrz@ttpdeb03:~/bin/pyload$ git checkout v0.4.4
Previous HEAD position was a74c7923c pyLoad 0.4.5
HEAD is now at 7df36031d pyLoad 0.4.4
wrz@ttpdeb03:~/bin/pyload$ ./pyLoadCli.py
Username: ^CTraceback (most recent call last):
  File "./pyLoadCli.py", line 563, in <module>
    if not username: username = raw_input(_("Username: "))
KeyboardInterrupt
wrz@ttpdeb03:~/bin/pyload$ cat .git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/pyload/pyload.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
wrz@ttpdeb03:~/bin/pyload$ lsb_release 
No LSB modules are available.
wrz@ttpdeb03:~/bin/pyload$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.11 (wheezy)
Release:	7.11
Codename:	wheezy
wrz@ttpdeb03:~/bin/pyload$ python --version
Python 2.7.14+

```

**Comment by GammaC0de** [comment]
Have you read the solution for #2361? 
https://github.com/pyload/pyload/issues/2361#issuecomment-188944549

**Comment by GammaC0de** [comment]
No response, closing.
