### ISSUE TITLE
Template not found error

### ISSUE THREAD

**Issue by syss** [pyload/pyload#3168]
I am having a problem while starting pyload.
Pyload seems to be uptodate
```
root@rpi2:/opt/pyload# git status
On branch stable
Your branch is up-to-date with 'origin/stable'.
```

The startup itself seems to be fine, however it can't seem to find the default/home.html template:

```
pyload@rpi2:~$ /opt/pyload/pyLoadCore.py  -p /var/run/pyload/pyload.pid
07.05.2018 13:41:26 INFO      Starting pyLoad 0.4.9
07.05.2018 13:41:26 INFO      Using home directory: /mnt/fts300gb/var/pyload
07.05.2018 13:41:28 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, LinkdecrypterComHook, MergeFiles, RestartFailed, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
07.05.2018 13:41:28 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LogMarker, MultiHome, PushBullet, PushOver, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
07.05.2018 13:41:28 INFO      Downloadtime: True
07.05.2018 13:41:29 INFO      Free space: 89.67 GiB
07.05.2018 13:41:29 INFO      Starting builtin webserver: 0.0.0.0:8000
07.05.2018 13:41:29 INFO      Activating Accounts...
07.05.2018 13:41:29 INFO      ACCOUNT UploadedTo: Adding user `340*******`...
07.05.2018 13:41:29 INFO      ACCOUNT UploadedTo: Login user `340*******`...
07.05.2018 13:41:29 INFO      ACCOUNT UploadedTo: Grabbing account info for user `340*******`...
07.05.2018 13:41:29 INFO      ACCOUNT ShareonlineBiz: Adding user `561*******`...
07.05.2018 13:41:29 INFO      ACCOUNT ShareonlineBiz: Login user `561*******`...
07.05.2018 13:41:29 INFO      ACCOUNT ShareonlineBiz: Grabbing account info for user `561*******`...
07.05.2018 13:41:29 INFO      Activating Plugins...
07.05.2018 13:41:30 ERROR     Error importing Xdcc: No module named Xdcc
07.05.2018 13:41:30 INFO      ADDON XFileSharing: Auto-discover new hosters
07.05.2018 13:41:30 INFO      ADDON XFileSharing: Auto-discover new crypters
07.05.2018 13:41:30 INFO      pyLoad is up and running
07.05.2018 13:41:31 INFO      ADDON UpdateManager: pyLoad is up to date!
07.05.2018 13:41:31 INFO      ADDON UpdateManager: All plugins are up to date!
07.05.2018 13:41:32 INFO      ADDON RestartFailed: Restarting all failed downloads...
07.05.2018 13:41:36 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
Traceback (most recent call last):
  File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/opt/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/opt/pyload/module/web/pyload_app.py", line 254, in home
    return render_to_response("home.html", {"res": res}, [pre_processor])
  File "/opt/pyload/module/web/utils.py", line 29, in render_to_response
    t = env.get_template(TEMPLATE + "/" + name)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python2.7/dist-packages/jinja2/loaders.py", line 350, in load
    loader, local_name = self.get_loader(name)
  File "/usr/lib/python2.7/dist-packages/jinja2/loaders.py", line 336, in get_loader
    raise TemplateNotFound(template)
TemplateNotFound: default/home.html
An error occured while processing the request.
Traceback (most recent call last):
  File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/opt/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/opt/pyload/module/web/pyload_app.py", line 254, in home
    return render_to_response("home.html", {"res": res}, [pre_processor])
  File "/opt/pyload/module/web/utils.py", line 29, in render_to_response
    t = env.get_template(TEMPLATE + "/" + name)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python2.7/dist-packages/jinja2/loaders.py", line 350, in load
    loader, local_name = self.get_loader(name)
  File "/usr/lib/python2.7/dist-packages/jinja2/loaders.py", line 336, in get_loader
    raise TemplateNotFound(template)
TemplateNotFound: default/home.html

<h1>Critical error while processing request: </h1>
```

Maybe I just need to add the J2 template to some place?

**Comment by syss** [comment]
Hi,
this solved my problem.
pyload also stated, that my Jinja2 was too old (v 2.10)
I am on Raspbian 8, Jessie

Maybe my `pip` provided too old Jinja2 templates, where pyload had problems with.
And for that reason it was not able to create the HTML.

But that's only a guess :)

**Comment by lukastribus** [comment]
For the record, choosing the classic template is also fine. The issue is that the old template was renamed from default to classic, which is why configs referring to the default template fail.

Reconfiguring either classic or pyplex as a template fixes the issue.
