### ISSUE TITLE
(QNAP/QPYLOAD) Downloads are in the wrong Download Folder

### ISSUE THREAD

**Issue by taK1993** [pyload/pyload#3177]
Hello,
i have updated my Pyload on my QNAP NAS. (QPYLOAD old version to newest)

But if i download something the location of the files is:
/share/CACHEDEV1_DATA/.qpkg/QPyload/CONFIG/Downloads/C or /D

But the right location should be this (Standard Path from QNAP)
/share/CACHEDEV1_DATA/Download

Can anyone help me?
Thanks

**Comment by GammaC0de** [comment]
Go to pyload's config page->general->general and change `Download Folder` to whatever you like.

**Comment by GammaC0de** [comment]
Sorry, I could not understand what you are trying to say..

Try typing the correct path instead of browsing for it.

**Comment by taK1993** [comment]
Thanks. I'll try this.

**Comment by GammaC0de** [comment]
Any update?

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by totofroto** [comment]
i have the same issue
i have reinstalled Pyload again without sucsess.
i got the following error:
pyLoad - Webinterface

An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/share/HDA_DATA/.qpkg/Entware-ng/share/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/share/HDA_DATA/.qpkg/Entware-ng/share/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/share/HDA_DATA/.qpkg/Entware-ng/share/pyload/module/web/pyload_app.py", line 528, in info
"freespace": formatSize(PYLOAD.freeSpace()),
File "/share/HDA_DATA/.qpkg/Entware-ng/share/pyload/module/Api.py", line 238, in freeSpace
return freeSpace(self.core.config["general"]["download_folder"])
File "/share/HDA_DATA/.qpkg/Entware-ng/share/pyload/module/utils.py", line 112, in freeSpace
s = statvfs(folder)
OSError: [Errno 2] No such file or directory: 'mnt'
