### ISSUE TITLE
Click'N'Load not working

### ISSUE THREAD

**Issue by hoch1009** [pyload/pyload#3216]
I forward the port of the server to my MacBook and try to add a container via Click'N'Load. The server produces the following TraceBack:

```
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/cnl_app.py", line 22, in _view
    return function(*args, **kwargs)
TypeError: add() takes exactly 1 argument (0 given)
An error occured while processing the request.
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/cnl_app.py", line 22, in _view
    return function(*args, **kwargs)
TypeError: add() takes exactly 1 argument (0 given)
```

**Comment by Velociraptor85** [comment]
So I just tested it with my installation and it works for me.
So please give us more information so we could reproduce the problem:
* a Testlink for example
* How did you setup your pyload server?
* did it work before you did something?

maybe we can help you than ;)

**Comment by GammaC0de** [comment]
Already been fixed (https://github.com/pyload/pyload/pull/2662), 

Please upgrade to the latest `stable` branch.

**Comment by hoch1009** [comment]
@Velociraptor85:

Link: https://bit.ly/2B1Uvg7 (click on Share-Online, Overlay pops up where i click on "Download via Click'n'Load'", a pop up comes up and then the error occurs (TraceBack above))

ClickNLoad config:
- activated: on
- listen for external connections: on
- port: 9666

Forward via ssh: ssh -L 127.0.0.1:9666:192.168.1.1:9666 192.168.1.1

CNL works except for the site mentioned above.

**Comment by GammaC0de** [comment]
@hoch1009 See https://github.com/pyload/pyload/issues/3216#issuecomment-412264557

**Comment by hoch1009** [comment]
@GammaC0de ok. pyLoadCore tells me everything is up to date. How should I perform the advised update?

**Comment by hoch1009** [comment]
Updated the UpdateManager.py and removed the userplugins folder

**Comment by hoch1009** [comment]
Sorry. After all plugins have been updated I tried to use CNL on the above mentioned site.
It produced this error:

```
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/cnl_app.py", line 22, in _view
    return function(*args, **kwargs)
TypeError: add() takes exactly 1 argument (0 given)
An error occured while processing the request.
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/cnl_app.py", line 22, in _view
    return function(*args, **kwargs)
TypeError: add() takes exactly 1 argument (0 given)

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/home/chr/.pyload/userplugins/hooks/ClickNLoad.py", line 85, in forward
    forward(source, destination)
  File "/home/chr/.pyload/userplugins/internal/misc.py", line 869, in forward
    destination.shutdown(socket.SHUT_WR)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected
```

**Comment by Velociraptor85** [comment]
@hoch1009 so I just tested it with your link and it works for me ... 

so maybe you could try to fix the change like described here https://github.com/pyload/pyload/pull/2662/files

* stop pyload
* find the file module/web/cnl_app.py
* change the line #38
* delete the corresponding cnl_app.pyc file 
* start pyload

**Comment by hoch1009** [comment]
Everything works now. Thank you @Velociraptor85 & @GammaC0de

**Comment by GammaC0de** [comment]
Great 👍 
Now I recommend you to switch to the pyplex webinterface.
