### ISSUE TITLE
Cannot manually add a link

### ISSUE THREAD

**Issue by hoch1009** [pyload/pyload#3218]
When trying to add a [link](https://bit.ly/2P6GAs1) the following errors occurs:

```
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/module/web/json_app.py", line 158, in add_package
    queue = int(request.forms['add_dest'])
  File "/usr/share/pyload/module/lib/bottle.py", line 1574, in __getitem__
    def __getitem__(self, key): return self.dict[key][-1]
KeyError: 'add_dest'
An error occured while processing the request.
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/module/web/json_app.py", line 158, in add_package
    queue = int(request.forms['add_dest'])
  File "/usr/share/pyload/module/lib/bottle.py", line 1574, in __getitem__
    def __getitem__(self, key): return self.dict[key][-1]
KeyError: 'add_dest'
```

**Comment by GammaC0de** [comment]
Does this happen for every link or just this specific one?

**Comment by Velociraptor85** [comment]
Would you please tell us how you added the link so one could try to reproduce the error? For me adding via the web-interface on queue page worked for that link

**Comment by hoch1009** [comment]
- I am at the web interface @ http://192.168.1.1:8000/queue/
- I click on "Add Package"
- I add the link from the clipboard and name the package Test
- I click on "Add Package" - the overlay goes away (nothing happens at the server)
- I click on "Queue" to check if the package is added - the following error occurs:

```
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/module/web/json_app.py", line 158, in add_package
    queue = int(request.forms['add_dest'])
  File "/usr/share/pyload/module/lib/bottle.py", line 1574, in __getitem__
    def __getitem__(self, key): return self.dict[key][-1]
KeyError: 'add_dest'
An error occured while processing the request.
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/module/web/json_app.py", line 158, in add_package
    queue = int(request.forms['add_dest'])
  File "/usr/share/pyload/module/lib/bottle.py", line 1574, in __getitem__
    def __getitem__(self, key): return self.dict[key][-1]
KeyError: 'add_dest'
```

- I try it again ... (see above) but now the following Traceback occurs:

```
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/module/web/json_app.py", line 158, in add_package
    queue = int(request.forms['add_dest'])
  File "/usr/share/pyload/module/lib/bottle.py", line 1574, in __getitem__
    def __getitem__(self, key): return self.dict[key][-1]
KeyError: 'add_dest'
An error occured while processing the request.
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/module/web/json_app.py", line 158, in add_package
    queue = int(request.forms['add_dest'])
  File "/usr/share/pyload/module/lib/bottle.py", line 1574, in __getitem__
    def __getitem__(self, key): return self.dict[key][-1]
KeyError: 'add_dest'

Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Exception happened during processing of request from ('192.168.1.110', 52058)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------

```


I am using the pyplex theme - if that matters.
Used another link: https://bit.ly/2w4N7uE

**Comment by GammaC0de** [comment]
Please post a screenshot of the "Add Package" dialog

**Comment by hoch1009** [comment]
![bildschirmfoto 2018-08-15 um 20 58 53](https://user-images.githubusercontent.com/20758077/44167308-1ae93b80-a0ce-11e8-940a-9746773d5f5d.png)

**Comment by GammaC0de** [comment]
Open your browser's developer tools - network tab.
add a link ans search for the POST method.
What arguments are sent?

**Comment by hoch1009** [comment]
I am struggling to find the POST method but I can say that an answer from "add_package" is pending (little spinning wheel). This waiting process is aborted as soon as I click somewhere in the web interface.

![bildschirmfoto 2018-08-16 um 18 16 32](https://user-images.githubusercontent.com/20758077/44221036-90addf80-a180-11e8-9f79-956ccd3513e3.png)

**Comment by GammaC0de** [comment]
Maybe you have some kind of firewall that is blocking?

**Comment by hoch1009** [comment]
Not really. Unfortunately I did not note where I saw it but I saw a 403 while i was looking for the POST method. What permissions are required with regard to manually adding links? Because CNL works so it’s maybe related to the path where the manual added links are saved (even temporarily).

**Comment by Velociraptor85** [comment]
@hoch1009 would you try running that in a private mode of the browser so your plugins/addons dont interfere ?

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by hoch1009** [comment]
@Velociraptor85 started Safari in private mode and added a link. Looks like this:

![bildschirmfoto 2018-08-23 um 16 39 35](https://user-images.githubusercontent.com/20758077/44532429-65347300-a6f3-11e8-9410-bdd0289f215d.png)

When clicking on "Queue" to check if it has been added the following Traceback occurs:

```
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/module/web/json_app.py", line 158, in add_package
    queue = int(request.forms['add_dest'])
  File "/usr/share/pyload/module/lib/bottle.py", line 1574, in __getitem__
    def __getitem__(self, key): return self.dict[key][-1]
KeyError: 'add_dest'
An error occured while processing the request.
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/module/web/json_app.py", line 158, in add_package
    queue = int(request.forms['add_dest'])
  File "/usr/share/pyload/module/lib/bottle.py", line 1574, in __getitem__
    def __getitem__(self, key): return self.dict[key][-1]
KeyError: 'add_dest'

Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Exception happened during processing of request from ('192.168.1.110', 56584)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 197, in send_preamble
    self._write('Server: %s\r\n' % self.server_software)
  File "/usr/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Exception happened during processing of request from ('192.168.1.110', 56586)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Exception happened during processing of request from ('192.168.1.110', 56589)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 271, in send_headers
    self._write(str(self.headers))
  File "/usr/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Exception happened during processing of request from ('192.168.1.110', 56592)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by GammaC0de** [comment]
Can you put a break-point on `/usr/share/pyload/module/web/json_app.py` line 158
and see what is the content of `request.forms.items()` ?

**Comment by GammaC0de** [comment]
Well?

**Comment by GammaC0de** [comment]
?

**Comment by GammaC0de** [comment]
No response, closing.
