### ISSUE TITLE
9Kw plugin thread crashes

### ISSUE THREAD

**Issue by MPW1412** [pyload/pyload#3335]
Hello,

I'm trying to make Shareonline work with the 9Kw Captcha Plugin. I've already read a lot of issues and their fixes here, but I can't locale the problem in the code.

 - I'm using latest stable from git
 - Shareonline works with RecaptchaV2 from the pyload webui (with tampermonkey). So I think the hoster plugin is working
 - I have two Captcha 9kw plugins, one with a uppercase K and one with a lowercase k. I can't find the latter in the repo. Where is it comming from?
 - The hook with uppercase K is version 0.39
 - I deleted the userplugins folder. 
 - I have more than 400 credits on 9kw.eu
 - According to my 9kw history, pyload doesn't try to send a captcha there

Debug output says Secure Pattern Not Found:

```
09.03.2019 08:48:57 DEBUG     HOSTER ShareonlineBiz[30]: Plugin version: 0.70
09.03.2019 08:48:57 DEBUG     HOSTER ShareonlineBiz[30]: Plugin status: testing
09.03.2019 08:48:57 WARNING   HOSTER ShareonlineBiz[30]: Plugin may be unstable
09.03.2019 08:48:57 INFO      HOSTER ShareonlineBiz[30]: Grabbing link info...
09.03.2019 08:48:57 DEBUG     HOSTER ShareonlineBiz[30]: Link info: {'status': 2, 'hash': {}, 'name': '[removed].rar', 'url': u'htt
p://www.share-online.biz/dl/[removed]', 'pattern': {'ID': u'[removed]'}, 'size': 106857601, 'md5': '[removed]', '
fileid': '[removed]'}
09.03.2019 08:48:57 DEBUG     HOSTER ShareonlineBiz[30]: Previous link info: {'status': 2, 'hash': {}, 'name': '[removed].rar', 'ur
l': u'http://www.share-online.biz/dl/[removed]', 'pattern': {'ID': u'[removed]'}, 'fileid': '[removed]', 'md5': '[removed]', 'size': 106857601}
09.03.2019 08:48:57 INFO      HOSTER ShareonlineBiz[30]: Link name: [removed].rar
09.03.2019 08:48:57 INFO      HOSTER ShareonlineBiz[30]: Link size: 101.91 MiB (106857601 bytes)
09.03.2019 08:48:57 INFO      HOSTER ShareonlineBiz[30]: Link status: online
09.03.2019 08:48:57 INFO      HOSTER ShareonlineBiz[30]: Processing url: http://www.share-online.biz/dl/[removed]
09.03.2019 08:48:57 INFO      HOSTER ShareonlineBiz[30]: Looking for direct download link...
09.03.2019 08:48:57 DEBUG     HOSTER ShareonlineBiz[30]: LOAD URL http://www.share-online.biz/dl/[removed] | redirect=True | cookies=True 
| get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
09.03.2019 08:48:57 INFO      HOSTER ShareonlineBiz[30]: Direct download link not found
09.03.2019 08:48:57 DEBUG     HOSTER ShareonlineBiz[30]: LOAD URL http://www.share-online.biz/dl/[removed] | redirect=True | cookies=True 
| get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
09.03.2019 08:48:57 INFO      HOSTER ShareonlineBiz[30]: Processing as free download...
09.03.2019 08:48:57 DEBUG     HOSTER ShareonlineBiz[30]: WAIT set to timestamp 1552117741.575209 | Previous waitUntil: 1552117737.010473
09.03.2019 08:48:57 INFO      HOSTER ShareonlineBiz[30]: Waiting 3 seconds...
09.03.2019 08:49:01 DEBUG     HOSTER ShareonlineBiz[30]: LOAD URL http://www.share-online.biz/dl/[removed]/free/ | redirect=True | cookies
=True | get={} | req=None | decode=True | multipart=False | post={'dl_free': '1', 'choice': 'free'} | ref=True | just_header=False
09.03.2019 08:49:01 DEBUG     CAPTCHA ShareonlineBiz[30]: ReCaptcha | Key: 6LdnPkIUAAAAABqC_ITR9-LTJKSdyR_Etj1Sf-Xi
09.03.2019 08:49:01 DEBUG     CAPTCHA ShareonlineBiz[30]: ReCaptcha | Detected reCAPTCHA v2
09.03.2019 08:49:01 WARNING   CAPTCHA ShareonlineBiz[30]: ReCaptcha | Secure Token pattern not found
09.03.2019 08:49:01 DEBUG     HOSTER ShareonlineBiz[30]: LOAD URL http://www.google.com/recaptcha/api/fallback?k=6LdnPkIUAAAAABqC_ITR9-LTJKS
dyR_Etj1Sf-Xi | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=http://www.share-online.biz
/dl/HQ6YY01PFK3 | just_header=False
09.03.2019 08:49:01 WARNING   CAPTCHA ShareonlineBiz[30]: ReCaptcha | reCAPTCHA noscript is blocked, trying reCAPTCHA interactive
09.03.2019 08:49:01 DEBUG     CAPTCHA ShareonlineBiz[30]: ReCaptcha | Challenge reCAPTCHA v2 interactive
09.03.2019 08:49:01 DEBUG     ADDON Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | redirect=True | cookies=True | get={'action': 'userc
aptchaguthaben', 'source': 'pyload', 'apikey': u'[removed]', 'pyload': '1'} | req=None | decode=True | multipart=False | post={}
 | ref=True | just_header=False
09.03.2019 08:49:02 INFO      ADDON Captcha9Kw: 674 credits left
09.03.2019 08:49:02 DEBUG     ADDON Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt | redirect=True | cookies=True | get={} | 
req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
```

Any ideas where to start looking?

Best,
Matthias

**Comment by GammaC0de** [comment]
> I'm using latest stable from git
> I have two Captcha 9kw plugins

So how come that you have two plugins?
pyload has only one plugin (Captcha9Kw.py v0.39) https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/Captcha9Kw.py

**Comment by MPW1412** [comment]
It seems there have been some leftover in the config file. I removed the pyload and the pyload-config folder. Now the second Captcha9kw plugin is gone.

I get a little further now. The plugin thread crashes:

```
09.03.2019 20:40:46 WARNING   CAPTCHA ShareonlineBiz[38]: ReCaptcha | Secure Token pattern not found
09.03.2019 20:40:46 WARNING   CAPTCHA ShareonlineBiz[38]: ReCaptcha | reCAPTCHA noscript is blocked, trying reCAPTCHA interactive
09.03.2019 20:40:47 INFO      ADDON Captcha9Kw: 1621 credits left
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/mpw/gits/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/home/mpw/gits/pyload/module/plugins/hooks/Captcha9Kw.py", line 161, in _process_captcha
    'action': "usercaptchacorrectdata"})
  File "/home/mpw/gits/pyload/module/plugins/internal/Plugin.py", line 215, in load
    decode is True)  # @TODO: Fix network multipart in 0.4.10
  File "/home/mpw/gits/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/home/mpw/gits/pyload/module/network/HTTPRequest.py", line 207, in load
    self.setRequestContext(url, get, post, referer, cookies, multipart)
  File "/home/mpw/gits/pyload/module/network/HTTPRequest.py", line 175, in setRequestContext
    self.c.setopt(pycurl.URL, url)
error: cannot invoke setopt() - perform() is currently running

Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/mpw/gits/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/home/mpw/gits/pyload/module/plugins/hooks/Captcha9Kw.py", line 161, in _process_captcha
    'action': "usercaptchacorrectdata"})
  File "/home/mpw/gits/pyload/module/plugins/internal/Plugin.py", line 215, in load
    decode is True)  # @TODO: Fix network multipart in 0.4.10
  File "/home/mpw/gits/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/home/mpw/gits/pyload/module/network/HTTPRequest.py", line 207, in load
    self.setRequestContext(url, get, post, referer, cookies, multipart)
  File "/home/mpw/gits/pyload/module/network/HTTPRequest.py", line 175, in setRequestContext
    self.c.setopt(pycurl.URL, url)
error: cannot invoke setopt() - perform() is currently running
```

**Comment by MPW1412** [comment]
It doesn't work now though, I just noticed. Maybe we should still catch that error somehow?

**Comment by GammaC0de** [comment]
please delete `/home/mpw/gits/pyload` and the `userplugins` directory and then reinstall

**Comment by MPW1412** [comment]
I did that. I made a mistake in the last post. I wanted to write “it does work now though“ instead of “it doesn't work“. So everything is fine.

The question is just, if we would want to fix the crash there?

**Comment by GammaC0de** [comment]
> The question is just, if we would want to fix the crash there?

It works fine for me, no errors...

**Comment by GammaC0de** [comment]
No response, closing.
