### ISSUE TITLE
Invalid RSA public exponent when trying to add a Mega Account

### ISSUE THREAD

**Issue by euneiro** [pyload/pyload#3342]
I've just installed this for the first time and I'm trying to add a Mega.nz account and every time I try I get this error. I'm pretty new to this stuff so I'm not sure where to start really. 

 ```
| Invalid RSA public exponent
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/mnt/mpathag/euneiro/pyload/module/web/ServerThread.py", line 75, in run
    self.start_builtin()
  File "/mnt/mpathag/euneiro/pyload/module/web/ServerThread.py", line 83, in start_builtin
    webinterface.run_simple(host=self.host, port=self.port)
  File "/mnt/mpathag/euneiro/pyload/module/web/webinterface.py", line 138, in run_simple
    run(app=web, host=host, port=port, quiet=True)
  File "/mnt/mpathag/euneiro/pyload/module/lib/bottle.py", line 2383, in run
    server.run(app)
  File "/mnt/mpathag/euneiro/pyload/module/lib/bottle.py", line 2081, in run
    srv.serve_forever()
  File "/usr/lib64/python2.7/SocketServer.py", line 233, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib64/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib64/python2.7/wsgiref/simple_server.py", line 131, in handle
    handler.run(self.server.get_app())
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/mnt/mpathag/euneiro/pyload/module/web/middlewares.py", line 53, in __call__
    response.gzip_start_response)
  File "/mnt/mpathag/euneiro/pyload/module/web/middlewares.py", line 17, in __call__
    return self.app(e, h)
  File "/mnt/mpathag/euneiro/pyload/module/lib/beaker/middleware.py", line 152, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/mnt/mpathag/euneiro/pyload/module/lib/bottle.py", line 843, in __call__
    return self.wsgi(environ, start_response)
  File "/mnt/mpathag/euneiro/pyload/module/lib/bottle.py", line 820, in wsgi
    out = self._cast(self._handle(environ), request, response)
  File "/mnt/mpathag/euneiro/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/mnt/mpathag/euneiro/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/mnt/mpathag/euneiro/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/mnt/mpathag/euneiro/pyload/module/web/json_app.py", line 277, in add_account
    PYLOAD.updateAccount(type, login, password)
  File "/mnt/mpathag/euneiro/pyload/module/Api.py", line 894, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "/mnt/mpathag/euneiro/pyload/module/utils.py", line 169, in new
    return func(*args)
  File "/mnt/mpathag/euneiro/pyload/module/plugins/AccountManager.py", line 149, in updateAccount
    updated = p.updateAccounts(user, password, options)
  File "/mnt/mpathag/euneiro/pyload/module/plugins/internal/misc.py", line 232, in new
    return fn(*args, **kwargs)
  File "/mnt/mpathag/euneiro/pyload/module/plugins/internal/Account.py", line 336, in updateAccounts
    self.add(user, password, options)
  File "/mnt/mpathag/euneiro/pyload/module/plugins/internal/misc.py", line 232, in new
    return fn(*args, **kwargs)
  File "/mnt/mpathag/euneiro/pyload/module/plugins/internal/Account.py", line 313, in add
    result = u['plugin'].choose(user)
  File "/mnt/mpathag/euneiro/pyload/module/plugins/internal/misc.py", line 232, in new
    return fn(*args, **kwargs)
  File "/mnt/mpathag/euneiro/pyload/module/plugins/internal/Account.py", line 430, in choose
    self.relogin()
  File "/mnt/mpathag/euneiro/pyload/module/plugins/internal/Account.py", line 177, in relogin
    return self.login()
  File "/mnt/mpathag/euneiro/pyload/module/plugins/internal/Account.py", line 118, in login
    self.info['data'])
  File "/mnt/mpathag/euneiro/pyload/module/plugins/accounts/MegaCoNz.py", line 94, in signin
    rsa_private_key[1]))
  File "/usr/lib/python2.7/site-packages/Crypto/PublicKey/RSA.py", line 578, in construct
    raise ValueError("Invalid RSA public exponent")
ValueError: Invalid RSA public exponent
```

When I did a system check beforehand I got this:

```
When you are ready for system check, hit enter.

## System Check ##
Python Version: OK
pycurl: OK
sqlite3: OK

pycrypto: OK
py-OpenSSL: OK

py-imaging: OK
tesseract: missing

PyQt4: missing

jinja2: OK
beaker: OK
JS engine: OK

System check finished, hit enter to see your status report.

## Status ##

Features available: container decrypting, ssl connection, Webinterface, extended Click'N'Load

Featues missing: 

** no Captcha OCR Recognition available **
Only needed for some hosters and as freeuser.

** Gui not available **
The Graphical User Interface.
```

**Comment by GammaC0de** [comment]
Hello,
This works fine for me.

How exactly have you installed pyload?

**Comment by GammaC0de** [comment]
No response, closing.
