### ISSUE TITLE
Unable to add mega.nz account

### ISSUE THREAD

**Issue by scamperer** [pyload/pyload#3362]
I've just installed pyLoad. I tried to add a mega.nz premium account. 

On the account tab it says status "not valid" premium "no"

The log is below
```Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/media/5cd8/pilch/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/media/5cd8/pilch/share/pyload/module/plugins/hooks/ClickNLoad.py", line 107, in _server
    dock_socket.bind((self.cnl_ip, self.cnl_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

13.04.2019 14:52:35 INFO      ACCOUNT MegaCoNz: Adding user `xym*******`...
13.04.2019 14:52:35 DEBUG     ACCOUNT MegaCoNz: Reached login timeout for user `xym*******`
13.04.2019 14:52:35 INFO      ACCOUNT MegaCoNz: Login user `xym*******`...
13.04.2019 14:52:37 DEBUG     ACCOUNT MegaCoNz: LOAD URL https://eu.api.mega.co.nz/cs | redirect=True | cookies=True | get={'id': 4946370400} | req=None | decode=True | multipart=False | post=[{"a": "us", "user": "xym*******", "uh": "22JteviSmg0="}] | ref=True | just_header=False
13.04.2019 14:52:37 DEBUG     ACCOUNT MegaCoNz: Api Response: [-9]
13.04.2019 14:52:37 ERROR     ACCOUNT MegaCoNz: Could not login user `xym*******` | Login handshake has failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/media/5cd8/pilch/share/pyload/module/web/ServerThread.py", line 75, in run
    self.start_builtin()
  File "/media/5cd8/pilch/share/pyload/module/web/ServerThread.py", line 83, in start_builtin
    webinterface.run_simple(host=self.host, port=self.port)
  File "/media/5cd8/pilch/share/pyload/module/web/webinterface.py", line 138, in run_simple
    run(app=web, host=host, port=port, quiet=True)
  File "/media/5cd8/pilch/share/pyload/module/lib/bottle.py", line 2383, in run
    server.run(app)
  File "/media/5cd8/pilch/share/pyload/module/lib/bottle.py", line 2081, in run
    srv.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 233, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 131, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/media/5cd8/pilch/share/pyload/module/web/middlewares.py", line 53, in __call__
    response.gzip_start_response)
  File "/media/5cd8/pilch/share/pyload/module/web/middlewares.py", line 17, in __call__
    return self.app(e, h)
  File "/media/5cd8/pilch/share/pyload/module/lib/beaker/middleware.py", line 152, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/media/5cd8/pilch/share/pyload/module/lib/bottle.py", line 843, in __call__
    return self.wsgi(environ, start_response)
  File "/media/5cd8/pilch/share/pyload/module/lib/bottle.py", line 820, in wsgi
    out = self._cast(self._handle(environ), request, response)
  File "/media/5cd8/pilch/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/media/5cd8/pilch/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/media/5cd8/pilch/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/media/5cd8/pilch/share/pyload/module/web/json_app.py", line 277, in add_account
    PYLOAD.updateAccount(type, login, password)
  File "/media/5cd8/pilch/share/pyload/module/Api.py", line 894, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "/media/5cd8/pilch/share/pyload/module/utils.py", line 169, in new
    return func(*args)
  File "/media/5cd8/pilch/share/pyload/module/plugins/AccountManager.py", line 149, in updateAccount
    updated = p.updateAccounts(user, password, options)
  File "/media/5cd8/pilch/share/pyload/module/plugins/internal/misc.py", line 232, in new
    return fn(*args, **kwargs)
  File "/media/5cd8/pilch/share/pyload/module/plugins/internal/Account.py", line 336, in updateAccounts
    self.add(user, password, options)
  File "/media/5cd8/pilch/share/pyload/module/plugins/internal/misc.py", line 232, in new
    return fn(*args, **kwargs)
  File "/media/5cd8/pilch/share/pyload/module/plugins/internal/Account.py", line 313, in add
    result = u['plugin'].choose(user)
  File "/media/5cd8/pilch/share/pyload/module/plugins/internal/misc.py", line 232, in new
    return fn(*args, **kwargs)
  File "/media/5cd8/pilch/share/pyload/module/plugins/internal/Account.py", line 430, in choose
    self.relogin()
  File "/media/5cd8/pilch/share/pyload/module/plugins/internal/Account.py", line 177, in relogin
    return self.login()
  File "/media/5cd8/pilch/share/pyload/module/plugins/internal/Account.py", line 118, in login
    self.info['data'])
  File "/media/5cd8/pilch/share/pyload/module/plugins/accounts/MegaCoNz.py", line 63, in signin
    self.fail_login()
  File "/media/5cd8/pilch/share/pyload/module/plugins/internal/Account.py", line 446, in fail_login
    return self.fail(msg)
  File "/media/5cd8/pilch/share/pyload/module/plugins/internal/Plugin.py", line 158, in fail
    raise Fail(encode(msg))  # @TODO: Remove `encode` in 0.4.10
Fail: Login handshake has failed'''

**Comment by scamperer** [comment]
I tried a reinstall using a slightly different method but got the same result
I used 1 - https://www.feralhosting.com/wiki/software/pyload
2 - https://whatbox.ca/wiki/pyLoad (didnt use the virtual environment but followed the other steps)

I tried my browser in safe mode in case it was an addin. I tried a different browser. I tried a second Mega account (free one). All had the same result

**Comment by GammaC0de** [comment]
@scamperer 
Install python 2.7 and then use pip to install pycurl.
After that download and unpack the latest stable branch from https://github.com/pyload/pyload/archive/stable.zip
and run pyLoadCore.py

**Comment by scamperer** [comment]
I deleted the old install and started again.
I install Python 2.7 via https://whatbox.ca/wiki/virtualenv

I used pip install pycurl

I downloaded pyload via  wget -O pyload.zip https://github.com/pyload/pyload/archive/stable.zip
unzip pyload.zip; mv pyload-stable/ pyload/

I then ran pyLoadCore.py

Unfortunately I still get the same error

**Comment by GammaC0de** [comment]
There may be an issue with the plugin because MegaCoNz have made changes on their side recently.

When have you registered the account?

**Comment by scamperer** [comment]
I registered the account the same day as the first installation, so 3/4 days ago

**Comment by GammaC0de** [comment]
>I registered the account the same day as the first installation, so 3/4 days ago

This makes sense,
There are two types of accounts Mega uses: v1 (older ones) that pyload can use and v2 (newer accounts that uses a different encryption, pyload cannt handle these yet)

**Comment by scamperer** [comment]
Ah, thanks very much for the explanation GammaC0de. Hopefully the plugin will be able to work with the newer versions but I understand that make take some time. Appreciate your help

**Comment by GammaC0de** [comment]
@scamperer Please test.

**Comment by themago** [comment]
I have the same problem
