### ISSUE TITLE
ImportError: cannot import name CherryPyWSGIServer

### ISSUE THREAD

**Issue by axzxc1236** [pyload/pyload#3371]
I'm setting up a pyload web server that is exposed to public with SSL enabled, setup goes well, but it throw errors when I run "python pyLoadCore.py".

```
26.04.2019 04:58:07 INFO      Starting threaded SSL webserver: 0.0.0.0:8000
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/runpyload/pyload/module/web/ServerThread.py", line 71, in run
    self.start_threaded()
  File "/home/runpyload/pyload/module/web/ServerThread.py", line 93, in start_threaded
    webinterface.run_threaded(host=self.host, port=self.port, cert=self.cert, key=self.key)
  File "/home/runpyload/pyload/module/web/webinterface.py", line 146, in run_threaded
    from wsgiserver import CherryPyWSGIServer
ImportError: cannot import name CherryPyWSGIServer
```

I already installed wsgiserver using "pip install wsgiserver", can't see anything wrong except jinja2 in system check (uninstalled it after the check).

> ## System Check ##
> Python Version: OK
> pycurl: OK
> sqlite3: OK
> 
> pycrypto: OK
> py-OpenSSL: OK
> 
> py-imaging: OK
> tesseract: OK
> 
> PyQt4: OK
> 
> Your installed jinja2 version 2.10.1 seems too old.
> You can safely continue but if the webinterface is not working,
> please upgrade or deinstall it, pyLoad includes a sufficient jinja2 libary.
> 
> jinja2: missing
> beaker: OK
> JS engine: OK

It's the latest version from stable branch, git pull confirms that.

**Comment by axzxc1236** [comment]
Looks like I didn't need to install wsgiserver, removed it and pyload is now working.
