### ISSUE TITLE
Graceful handling of 403 for FileJoker (and probably others using CloudFlare)

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#3385]
### Type of ticket:

- [ ] Plugin request
- [x] Feature request
- [x] Bug report
- [ ] Question
- [ ] Other

### Summary:

Filejoker (and probably others using cloudflare) just returns a 403 error for requests from certain proxies it seems. Currently, at least the Filejoker plugin crashes:
```
Traceback (most recent call last):
  File "/home/cache/pyload_newfork/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/cache/pyload_newfork/module/plugins/internal/Base.py", line 294, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/cache/pyload_newfork/module/plugins/internal/Hoster.py", line 116, in _process
    self.process(self.pyfile)
  File "/home/cache/pyload_newfork/module/plugins/internal/SimpleHoster.py", line 268, in process
    self._preload()
  File "/home/cache/pyload_newfork/module/plugins/internal/SimpleHoster.py", line 247, in _preload
    decode=self.TEXT_ENCODING)
  File "/home/cache/pyload_newfork/module/plugins/internal/Base.py", line 494, in load
    return Plugin.load(self, *args, **kwargs)
  File "/home/cache/pyload_newfork/module/plugins/internal/Plugin.py", line 225, in load
    decode is True)  # @TODO: Fix network multipart in 0.4.10
  File "/home/cache/pyload_newfork/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/home/cache/pyload_newfork/module/network/HTTPRequest.py", line 247, in load
    self.code = self.verifyHeader()
  File "/home/cache/pyload_newfork/module/network/HTTPRequest.py", line 263, in verifyHeader
    raise BadHeader(code, self.header, self.getResponse())
BadHeader: Bad server response: 403 Forbidden
```
but maybe this could be handled more gracefully, causing a `TEMP_OFFLINE` maybe?

### How to reproduce

```
% curl -L -D header --proxy "http://SOME_PROXY" https://filejoker.net/FILE_ID
Forbidden. Contact support@filejoker.net% 
% cat header 
HTTP/1.1 200 Connection established

HTTP/1.1 403 Forbidden
[...]
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
[...]

% curl -L -D header https://filejoker.net/FILE_ID
[...]
% cat header 
HTTP/1.1 200 OK
[...]
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
[...]
```

**Comment by GammaC0de** [comment]
Currently 403  produces a failed status, am I right?

So I don't see any benefit of marking it as TEMP_OFFLINE.
Also I can you tell if it is offline permanently or temporary?

**Comment by igel-kun** [comment]
> Currently 403 produces a failed status, am I right?

Yes, the plugin-crash results in a failed status on the file.


> So I don't see any benefit of marking it as TEMP_OFFLINE.
> Also I can you tell if it is offline permanently or temporary?

Well, if it was permanently offline, then it would return a normal html response matching the `OFFLINE_PATTERN`. I guess, thinking about it a little, this should probably be handled by the FileJoker plugin itself, catching a 403 and maybe `self.fail()`ing with a more meaningful error message like "Forbidden Page. Maybe your proxy is blocked." or something...
