### ISSUE TITLE
Pyload does not start. 'is_subclass' is not defined

### ISSUE THREAD

**Issue by maxanier** [pyload/pyload#3418]
### Describe the problem

I just installed pyload using
`sudo pip3 install pyload-ng`
but if I try to start it with
`pyload`
it immediately crashes with:
```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyload/__init__.py", line 49, in excepthook
    if is_subclass(exc_type, KeyboardInterrupt):
NameError: name 'is_subclass' is not defined

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/pyload", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pyload/script.py", line 124, in main
    run(core_args, args.daemon)
  File "/usr/local/lib/python3.6/dist-packages/pyload/script.py", line 108, in run
    pyload_core = Core(*core_args)
  File "/usr/local/lib/python3.6/dist-packages/pyload/core/__init__.py", line 91, in __init__
    self._init_config(userdir, cachedir, storagedir, debug)
  File "/usr/local/lib/python3.6/dist-packages/pyload/core/__init__.py", line 107, in _init_config
    from .config.parser import ConfigParser
ModuleNotFoundError: No module named 'pyload.core.config'
```
pyLoad Version is 0.5.0 (PyPi says 0.5.0a5.dev537 )

I am running Ubuntu 18.04 with Python3.6. 
I also tried installing pyload-ng[all] but it did not help.
(Also I  had to manually install `python-magic` because 
```
File "/usr/local/lib/python3.6/dist-packages/pyload/core/utils/fs.py", line 18, in <module>
    import magic
ModuleNotFoundError: No module named 'magic'
```

**Comment by maxanier** [comment]
The respective code has been changed here https://github.com/pyload/pyload/commit/28ac88a2b2dcb82158074868bee684bfcc38c2de#diff-0a73b3ad8b9fe95846c66c25aa69e1a5
Not sure, maybe there is a new dependency I need to install

**Comment by GammaC0de** [comment]
pyload-ng is in alpha stage and still not ready yet for end user use.

So do you really want to test pyload-ng or just use the stable pyload?

**Comment by maxanier** [comment]
I already have pyload stable up and running, but I wanted to see how good pyload-ng is running by now.
The "alpha" pyload-ng has been around for quite some time now and the README suggest that ng is the preferred version. But if you say ng is still alpha by its original meaning, I will happily continue using pyload stable :)

**Comment by GammaC0de** [comment]
> But if you say ng is still alpha by its original meaning

Correct, closing.
