### ISSUE TITLE
ADDON ExternalScripts [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by r9isgod8** [pyload/pyload#3430]
### Describe the problem

I am trying to run a script that would display Download Finished to the console once a package is finished downloading. The script resides in /root/.pyload/scripts/package_finished folder but everytime it get runs it displays 
ADDON ExternalScripts: Runtime error: scripts/package_finished/test.sh | [Errno 2] No such file or directory

Here are the content of the scripts - 
`#!/bin/sh
echo "Download Finished"`

### Debug log

```
18.08.2019 06:59:02 INFO      Starting pyLoad 0.4.9
18.08.2019 06:59:02 INFO      Using home directory: /root/.pyload
18.08.2019 06:59:02 DEBUG     Deleting old pidfile pyload.pid
18.08.2019 06:59:02 DEBUG     Remote activated: True
18.08.2019 06:59:03 DEBUG     created index of plugins
18.08.2019 06:59:03 INFO      ADDON ExternalScripts: Activated scripts in folder `package_finished`: test.sh
18.08.2019 06:59:03 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
18.08.2019 06:59:03 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
18.08.2019 06:59:03 INFO      Downloadtime: True
18.08.2019 06:59:03 INFO      Starting ThriftBackend: 0.0.0.0:7227
18.08.2019 06:59:03 INFO      Starting builtin webserver: 0.0.0.0:8000
18.08.2019 06:59:03 INFO      Free space: 310.18 GiB
18.08.2019 06:59:03 INFO      Activating Accounts...
18.08.2019 06:59:03 INFO      ACCOUNT MegaCoNz: Adding user `joe*******`...
18.08.2019 06:59:03 DEBUG     ACCOUNT MegaCoNz: Reached login timeout for user `joe*******`
18.08.2019 06:59:03 INFO      ACCOUNT MegaCoNz: Login user `joe*******`...
18.08.2019 06:59:03 DEBUG     ACCOUNT MegaCoNz: LOAD URL https://eu.api.mega.co.nz/cs | redirect=True | cookies=True | get={'id': 4131126746, 'sid': u'gOKpFCxO6cXRWAV3g7Uf3m1ITFNTMXNUbHV3BIy9tVv5lIV0V-93mK7L7Q'} | req=None | decode=True | multipart=False | post=[{"a": "ug", "pro": 1, "xfer": 1}] | ref=True | just_header=False
18.08.2019 06:59:04 DEBUG     ACCOUNT MegaCoNz: Api Response: [{"u":"mHLSS1sTluw","s":0,"since":1385659367,"email":"joe*******","emails":["joe*******"],"pemails":[],"name":"Joel Murphy","k":"NxPuyM9hml9BfB_-kPFPiQ","c":1,"pubk":"B_91i_EAvv3d5KLoYc0IOiFKsG7YFhurBly-mCglWbOFtZY11cBULjByEREmWvtdvF_xAKMTlvyTFZ_K9TgLP8c9BTyqkp02BnTrvheIHXHd0d2Y-pmzPBDo5WDK2oujJRdcvvlj71Tb7dnl1OYowjBd5wfPLeJVULHDJBnvOpbbrH9GlVAznTpsWD-o2OBJdyk3d8wB36-Xbj54zRRFc9P9IT4O6jCkIzx38rS4HNNIrII8lMoPzs02eqbR8e3V5oCxS5vpnrBus_XnljD3Nx27SU2chhgdeMTNZAbh81u67jyvEfZPsx79J_5zffaQKWl4-qJTOCN60gRYpRAJWqaVAAUR","privk":"usniUi31XeyowbzXriJ7hBdR2mqUwNi5X2t_FCr_W8HMylvDMiaH5drp9e57y6E7iPXZFvn_LylpIdSqc143DjhOJ-qobv61oNOy6VLRinmWnULrUGj9vsJwyXP1niRWigoE7w4TR4X227WGSpXgm8QZMzcDt0Td4pGKZz1t56IAKnM-9y1Swgj4sufrV8XUTwbIgU_yUNpm_W7w7o_TIHGwePN47RlZU75p2zqYo0o853m6PxNfngvb_OwacyeYlHOKfb_psX51hT0ee4vcQpZOF2igINyQa-ot0qH-v-XMtUiSZdWwoIFTwbosY8xLR6CYlHF881uYo88VmdUMj3-N5V0fRWiLLidej4NroWRQqwfUhO44WN8BKyT1LsnoEg7M_wDv_2dv-6GbPlG6KP6CufbxT91HBHjOorc7Ak-gNy29YUL3xDp1ovb2S3W7HgcT1_DJoXDow1gEtj4e_z-Y2Z3Km5jgYQ3aXj7TBAxRorppSv3ef3r4g2uDng9QtqCeg0SV53KRnaSEeObmN2G3vaQ9-FR7BCwvqOZSIq2ixNR1Qe0g5byu9b-hAO4ivEtzRFW-VV5Ft56_ejjK44QY_poQqzhJ37J_spF4jEgfWbicoA0oAe4mfuy9dyLD-5Bf6iOrVQ6eMzIxVRTGvM7FbePzNeF2EuYwJdRCAcnX3ntK6M66BvXrkDoJ_Jx_rriHxP7pOMAyCwTNHFe0GmdjY5ZfNMxRWS9SeLDEuY0nxFbH0w1myWxsOAdxCTU2QECZDerKDOv0Vss6y5IfVy6r3w09x2TX0Wwa6EDUnCJFdC17jRVJwgqPEDU5MPRMuTyn17W2tWTanXRKgEq7v6H7v51qSFjyRHwL-vuHVjs","*!cf":"ELvr8CrMJBUth6nCikO0aXdpznEal-6Io-TXT-EeNdh1e_6nLtwj","^!lang":"ZW4","^!lastPsa":"NA","^!onboarding":"AAEBAQEAAQEB","^!prd":"MDoxNTY0NTE5OTIyOjE6MDoxNTY1NzkwNDA5","^!usl":"MA","firstname":"Sm9lbA","lasn":"d1VxSlJVYkxza0E","lastname":"TXVycGh5","name2":"objectObjectMurphw","terms":"Mg","ts":"Od89dmToWecRSDBDK1FaxrBn2WFi8DO7F0XJadX4OFs","^clv":"MQ","p":4,"flags":{"ach":0,"mcs":1,"mfae":1,"nsre":1,"smsve":1,"ssrs":1},"aav":1,"ipcc":"US","ut":"ii03-vSC6oA"}]
18.08.2019 06:59:04 WARNING   ACCOUNT MegaCoNz: Skipped login user `joe*******` | Already signed in
18.08.2019 06:59:04 INFO      ACCOUNT MegaCoNz: Grabbing account info for user `joe*******`...
18.08.2019 06:59:04 DEBUG     ACCOUNT MegaCoNz: LOAD URL https://eu.api.mega.co.nz/cs | redirect=True | cookies=True | get={'id': 3118360207, 'sid': u'gOKpFCxO6cXRWAV3g7Uf3m1ITFNTMXNUbHV3BIy9tVv5lIV0V-93mK7L7Q'} | req=None | decode=True | multipart=False | post=[{"a": "uq", "pro": 1, "xfer": 1}] | ref=True | just_header=False
18.08.2019 06:59:04 DEBUG     ACCOUNT MegaCoNz: Api Response: [{"mxfer":13194139533312,"pxfer":13194139533312,"caxfer":503361950600,"csxfer":0,"srvratio":0,"balance":[],"stype":"S","scycle":"1 Y","srenew":[0],"sgw":["iTunes"],"sgwids":[2],"utype":4,"smixed":0,"suntil":1588194518,"bt":65535,"tah":[0,0,0,0,0,0],"tar":0,"tuo":0,"tua":0,"ruo":0,"rua":1359543376,"rtt":1}]
18.08.2019 06:59:04 DEBUG     ACCOUNT MegaCoNz: Account info for user `joe*******`: {'login': {'timestamp': 1566111543.588048, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account MegaCoNz>, 'trafficleft': 12393337483, 'mega_session_id': u'gOKpFCxO6cXRWAV3g7Uf3m1ITFNTMXNUbHV3BIy9tVv5lIV0V-93mK7L7Q', 'maxtraffic': None, 'validuntil': 1588194518, 'login': 'joe*******', 'type': 'MegaCoNz', 'options': {'limitDL': ['0']}}}
18.08.2019 06:59:04 INFO      Activating Plugins...
18.08.2019 06:59:04 DEBUG     ADDON ExternalScripts: No script found under folder `pyload_start`
18.08.2019 06:59:04 INFO      ADDON XFileSharing: Auto-discover new hosters
18.08.2019 06:59:04 DEBUG     ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com|clicknupload\.org|cramit\.in|easybytez\.com|exashare\.com|filejoker\.net|fileom\.com|filerio\.com|fistfast\.net|hugefiles\.net|junocloud\.me|katfile\.com|movreel\.com|nosupload\.com|novafile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|streamcloud\.eu|suprafiles\.me|tusfiles\.net|uploadrocket\.net|vidplay\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
18.08.2019 06:59:04 INFO      ADDON XFileSharing: Auto-discover new crypters
18.08.2019 06:59:04 DEBUG     ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
18.08.2019 06:59:04 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/updates/master/plugins.txt | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
18.08.2019 06:59:04 INFO      pyLoad is up and running
18.08.2019 06:59:05 INFO      ADDON UpdateManager: pyLoad is up to date!
18.08.2019 06:59:05 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/updates/master/plugins.txt | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
18.08.2019 06:59:05 DEBUG     ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'FreeWayMe'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaBrotherhood'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'Libgen'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'RealdebridComTorrent'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
18.08.2019 06:59:05 INFO      ADDON UpdateManager: All plugins are up to date!
18.08.2019 06:59:06 INFO      Download starts: https://mega.nz/#!HslBUKIT!7bWqnvon2E3GXwaXBoAWM9TY0m2aaXJqv3pRVqfre_0
18.08.2019 06:59:06 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
18.08.2019 06:59:06 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
18.08.2019 06:59:06 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
18.08.2019 06:59:06 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
18.08.2019 06:59:06 DEBUG     HOSTER MegaCoNz[1]: Plugin version: 0.53
18.08.2019 06:59:06 DEBUG     HOSTER MegaCoNz[1]: Plugin status: testing
18.08.2019 06:59:06 WARNING   HOSTER MegaCoNz[1]: Plugin may be unstable
18.08.2019 06:59:06 DEBUG     HOSTER MegaCoNz[1]: Config option `use_premium` not found, use default `True`
18.08.2019 06:59:06 INFO      ACCOUNT MegaCoNz: Grabbing account info for user `joe*******`...
18.08.2019 06:59:06 DEBUG     ACCOUNT MegaCoNz: LOAD URL https://eu.api.mega.co.nz/cs | redirect=True | cookies=True | get={'id': 9649801839, 'sid': u'gOKpFCxO6cXRWAV3g7Uf3m1ITFNTMXNUbHV3BIy9tVv5lIV0V-93mK7L7Q'} | req=None | decode=True | multipart=False | post=[{"a": "uq", "pro": 1, "xfer": 1}] | ref=True | just_header=False
18.08.2019 06:59:07 DEBUG     ACCOUNT MegaCoNz: Api Response: [{"mxfer":13194139533312,"pxfer":13194139533312,"caxfer":503361950600,"csxfer":0,"srvratio":0,"balance":[],"stype":"S","scycle":"1 Y","srenew":[0],"sgw":["iTunes"],"sgwids":[2],"utype":4,"smixed":0,"suntil":1588194518,"bt":65535,"tah":[0,0,0,0,0,0],"tar":0,"tuo":0,"tua":0,"ruo":0,"rua":1359543376,"rtt":1}]
18.08.2019 06:59:07 DEBUG     ACCOUNT MegaCoNz: Account info for user `joe*******`: {'login': {'timestamp': 1566111543.588048, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account MegaCoNz>, 'trafficleft': 12393337483, 'mega_session_id': u'gOKpFCxO6cXRWAV3g7Uf3m1ITFNTMXNUbHV3BIy9tVv5lIV0V-93mK7L7Q', 'maxtraffic': None, 'validuntil': 1588194518, 'login': 'joe*******', 'type': 'MegaCoNz', 'options': {'limitDL': ['0']}}}
18.08.2019 06:59:07 INFO      HOSTER MegaCoNz[1]: Grabbing link info...
18.08.2019 06:59:07 DEBUG     HOSTER MegaCoNz[1]: Link info: {'status': 7, 'hash': {}, 'name': '#!HslBUKIT!7bWqnvon2E3GXwaXBoAWM9TY0m2aaXJqv3pRVqfre_0', 'url': u'https://mega.nz/#!HslBUKIT!7bWqnvon2E3GXwaXBoAWM9TY0m2aaXJqv3pRVqfre_0', 'pattern': {'OWNER': None, 'TYPE': u'', 'ID': u'HslBUKIT', 'KEY': u'7bWqnvon2E3GXwaXBoAWM9TY0m2aaXJqv3pRVqfre_0'}, 'size': 0}
18.08.2019 06:59:07 DEBUG     HOSTER MegaCoNz[1]: Previous link info: {}
18.08.2019 06:59:07 INFO      HOSTER MegaCoNz[1]: Link name: #!HslBUKIT!7bWqnvon2E3GXwaXBoAWM9TY0m2aaXJqv3pRVqfre_0
18.08.2019 06:59:07 INFO      HOSTER MegaCoNz[1]: Link size: N/D
18.08.2019 06:59:07 INFO      HOSTER MegaCoNz[1]: Link status: starting
18.08.2019 06:59:07 INFO      HOSTER MegaCoNz[1]: Processing url: https://mega.nz/#!HslBUKIT!7bWqnvon2E3GXwaXBoAWM9TY0m2aaXJqv3pRVqfre_0
18.08.2019 06:59:07 DEBUG     HOSTER MegaCoNz[1]: ID: HslBUKIT | Key: 7bWqnvon2E3GXwaXBoAWM9TY0m2aaXJqv3pRVqfre_0 | Type: public | Owner: None
18.08.2019 06:59:07 DEBUG     HOSTER MegaCoNz[1]: LOAD URL https://eu.api.mega.co.nz/cs | redirect=True | cookies=True | get={'sid': u'gOKpFCxO6cXRWAV3g7Uf3m1ITFNTMXNUbHV3BIy9tVv5lIV0V-93mK7L7Q', 'id': 455127163, 'n': u'HslBUKIT'} | req=None | decode=True | multipart=False | post=[{"a": "g", "p": "HslBUKIT", "g": 1, "ssl": 1}] | ref=True | just_header=False
18.08.2019 06:59:07 DEBUG     HOSTER MegaCoNz[1]: Api Response: [{"s":1063471,"at":"KLuXHPdr8l5QQ03xs1uXwvWkb-W02RBYkydNPNChqzLe7NgyFTtCxZVq5YzPV1jjsQ1wLsCK1lTJG466_krtXZB-wsuZnOa50N9QMW6Pr7Y","msd":1,"g":"https://gfs270n109.userstorage.mega.co.nz/dl/XFBHgqiJZlcW2wL5Mc47J7Gt9yPGKc4W9s4Q3kkS4YhOnT9ILmClnmWE-ghsXkMPG1KPFEEspimE-3MNvvYPl2_zdGP_qZQovd1TMjqxpkC0yiQpmOC4MUJHdVmoWg"}]
18.08.2019 06:59:07 DEBUG     HOSTER MegaCoNz[1]: Decrypted Attr: {u'c': u'EpQJ9nX6bsfW4BP7GV2a8gQ5SEVd', u'n': u'convertpro-addon-1.2.3.rar'}
18.08.2019 06:59:07 DEBUG     HOSTER MegaCoNz[1]: DOWNLOAD URL https://gfs270n109.userstorage.mega.co.nz/dl/XFBHgqiJZlcW2wL5Mc47J7Gt9yPGKc4W9s4Q3kkS4YhOnT9ILmClnmWE-ghsXkMPG1KPFEEspimE-3MNvvYPl2_zdGP_qZQovd1TMjqxpkC0yiQpmOC4MUJHdVmoWg | fixurl=True | resume=None | get={} | cookies=True | disposition=True | chunks=None | post={} | ref=True
18.08.2019 06:59:10 INFO      HOSTER MegaCoNz[1]: File saved
18.08.2019 06:59:10 INFO      HOSTER MegaCoNz[1]: File decrypted
18.08.2019 06:59:10 INFO      HOSTER MegaCoNz[1]: Checking download...
18.08.2019 06:59:10 INFO      HOSTER MegaCoNz[1]: File is OK
18.08.2019 06:59:10 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
18.08.2019 06:59:10 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
18.08.2019 06:59:10 INFO      Download finished: convertpro-addon-1.2.3.rar
18.08.2019 06:59:10 DEBUG     ADDON ExternalScripts: No script found under folder `download_finished`
18.08.2019 06:59:10 INFO      Package finished: test
18.08.2019 06:59:10 INFO      ADDON ExternalScripts: Executing scripts in folder `package_finished`...
18.08.2019 06:59:10 DEBUG     ADDON ExternalScripts: EXECUTE scripts/package_finished/test.sh 1 test Downloads/test
18.08.2019 06:59:10 ERROR     ADDON ExternalScripts: Runtime error: scripts/package_finished/test.sh | [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/content/pyload-stable/module/PluginThread.py", line 191, in run
    self.m.core.files.checkPackageFinished(pyfile)
  File "/content/pyload-stable/module/database/FileDatabase.py", line 532, in checkPackageFinished
    self.core.hookManager.packageFinished(pyfile.package())
  File "/content/pyload-stable/module/utils.py", line 169, in new
    return func(*args)
  File "/content/pyload-stable/module/HookManager.py", line 248, in packageFinished
    plugin.packageFinished(package)
  File "/content/pyload-stable/module/plugins/internal/Addon.py", line 175, in packageFinished
    return self.package_finished(pypack)
  File "/content/pyload-stable/module/plugins/hooks/ExternalScripts.py", line 210, in package_finished
    self.call_script("package_finished", *args)
  File "/content/pyload-stable/module/plugins/hooks/ExternalScripts.py", line 138, in call_script
    p = self.call_cmd(file, *args)
  File "/content/pyload-stable/module/plugins/hooks/ExternalScripts.py", line 118, in call_cmd
    p = subprocess.Popen(call, bufsize=-1)  # @NOTE: output goes to pyload
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by GammaC0de** [comment]
Have you made the script executable?
`chmod +x /root/.pyload/scripts/package_finished/test.sh`

**Comment by r9isgod8** [comment]
> Have you made the script executable?
> `chmod +x /root/.pyload/scripts/package_finished/test.sh`

I did make it executable.

**Comment by GammaC0de** [comment]
What user are you running pyload with?

What happens wen you run test.sh with the pyload user, e.g:
```
su pyloaduser
/root/.pyload/scripts/package_finished/test.sh
````

**Comment by r9isgod8** [comment]
> What user are you running pyload with?
> 
> What happens wen you run test.sh with the pyload user, e.g:
> 
> ```
> su pyloaduser
> /root/.pyload/scripts/package_finished/test.sh
> ```

I am running pyload on google colab which is running ubuntu 18.04.2. Pyload runs with root and running the command gives me "no password entry for the user" error.

**Comment by GammaC0de** [comment]
`#!/bin/sh echo "Download Finished"`

Is there a new line between the sh and echo?

**Comment by r9isgod8** [comment]
> `#!/bin/sh echo "Download Finished"`
> 
> Is there a new line between the sh and echo?

No there isn't.

**Comment by GammaC0de** [comment]
>No there isn't.

There should be a  new line there..

**Comment by r9isgod8** [comment]
> > No there isn't.
> 
> There should be a new line there..

I modified the command and added a new line but still the same error.

**Comment by GammaC0de** [comment]
Try adding a `shell=True` parameter to [ExternalScripts.py#L118](https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/ExternalScripts.py#L118).

**Comment by r9isgod8** [comment]
> Try adding a `shell=True` parameter to [/content/pyload-stable/module/plugins/hooks/ExternalScripts.py#L118](https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/ExternalScripts.py#L118).

I did as you told me. The previous error is gone but now it seems like my test.sh script can't be found.
04.09.2019 08:00:41 INFO      ADDON ExternalScripts: Executing scripts in folder `package_finished`...
04.09.2019 08:00:41 DEBUG     ADDON ExternalScripts: EXECUTE scripts/package_finished/test.sh 1 test Downloads/test
1: 1: 1: scripts/package_finished/test.sh: not found

**Comment by GammaC0de** [comment]
What OS are you using?

**Comment by r9isgod8** [comment]
> What OS are you using?

I am using Ubuntu 18.04.3
