### ISSUE TITLE
Pyload crash on getAccountData after ShareonlineBiz login fails

### ISSUE THREAD

**Issue by Uphane** [pyload/pyload#3440]
### Describe the problem

If a user login fails (example on network error), Pyload crashed someone. If I start Pyload in debug mode, than I can't yet reproduce the crash. The account is valid an work on restart.

### Debug log

```
05.09.2019 06:42:52 WARNING   HOSTER ShareonlineBiz[7853]: Plugin may be unstable
05.09.2019 06:42:52 INFO      ACCOUNT ShareonlineBiz: Relogin user `723*******`...
05.09.2019 06:43:08 ERROR     ACCOUNT ShareonlineBiz: Could not login user `723*******` | (52, 'Empty reply from server')
05.09.2019 06:43:09 INFO      HOSTER ShareonlineBiz[7853]: Grabbing link info...
05.09.2019 06:43:10 INFO      HOSTER ShareonlineBiz[7853]: Link name: *****.part2.rar
05.09.2019 06:43:10 INFO      HOSTER ShareonlineBiz[7853]: Link size: 751.75 MiB (788263570 bytes)
05.09.2019 06:43:10 INFO      HOSTER ShareonlineBiz[7853]: Link status: online
05.09.2019 06:43:10 INFO      HOSTER ShareonlineBiz[7853]: Processing url: http://www.share-online.biz/dl/*****
05.09.2019 06:43:10 INFO      HOSTER ShareonlineBiz[7853]: Looking for direct download link...
05.09.2019 06:43:10 INFO      HOSTER ShareonlineBiz[7853]: Direct download link not found
05.09.2019 06:43:11 INFO      HOSTER ShareonlineBiz[7853]: Processing as free download...
05.09.2019 06:43:11 INFO      HOSTER ShareonlineBiz[7853]: Waiting 3 seconds...
05.09.2019 06:43:16 WARNING   CAPTCHA ShareonlineBiz[7853]: ReCaptcha | Secure Token pattern not found
05.09.2019 06:43:16 WARNING   CAPTCHA ShareonlineBiz[7853]: ReCaptcha | Secure Token pattern not found
05.09.2019 06:43:16 WARNING   CAPTCHA ShareonlineBiz[7853]: ReCaptcha | reCAPTCHA noscript is blocked, trying reCAPTCHA interactive
05.09.2019 06:53:17 WARNING   CAPTCHA ShareonlineBiz[7853]: ReCaptcha | Invalid captcha | No captcha result obtained in appropriate timing (300s)
05.09.2019 06:53:17 INFO      HOSTER ShareonlineBiz[7853]: Waiting 1 seconds...
05.09.2019 06:53:19 INFO      Download restarted: *****.part2.rar | Retry Captcha
05.09.2019 06:53:19 INFO      Download starts: *****.part2.rar
05.09.2019 06:53:19 WARNING   HOSTER ShareonlineBiz[7853]: Plugin may be unstable
05.09.2019 06:53:19 WARNING   Download failed: *****.part2.rar | 'NoneType' object has no attribute 'get_info'
05.09.2019 06:53:19 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: *****.part2.rar (pid:330)
05.09.2019 06:53:20 INFO      ADDON UnSkipOnFail: No duplicates found
05.09.2019 06:53:20 ERROR     <<< UNCAUGHT EXCEPTION >>>
Traceback (most recent call last):
  File "./pyload/pyLoadCore.py", line 685, in <module>
  File "./pyload/pyLoadCore.py", line 672, in main
  File "./pyload/pyLoadCore.py", line 664, in deamon
  File "./pyload/pyLoadCore.py", line 486, in start
  File "/home/user/pyload/module/ThreadManager.py", line 151, in work
    self.assignJob()
  File "/home/user/pyload/module/ThreadManager.py", line 265, in assignJob
    inuse = set([(x.active.pluginname,self.getLimit(x)) for x in self.threads if x.active and x.active.hasPlugin() and x.active.plugin.account])
  File "/home/user/pyload/module/ThreadManager.py", line 313, in getLimit
    limit = thread.active.plugin.account.getAccountData(thread.active.plugin.user)["options"].get("limitDL",["0"])[0]
  File "/home/user/pyload/module/plugins/internal/misc.py", line 227, in new
    return fn(*args, **kwargs)
  File "/home/user/pyload/module/plugins/internal/Account.py", line 274, in getAccountData
    return self.accounts[user]
KeyError: None
```

**Comment by GammaC0de** [comment]
Is this a new installation?

**Comment by Uphane** [comment]
No, there is not a new installation. This installation based on the stable branch and I update it continual.

**Comment by Uphane** [comment]
First time pyload crashed in debug mode. The last log lines are: 
```
07.09.2019 06:01:32 DEBUG     HOSTER ShareonlineBiz[8449]: Plugin version: 0.72
07.09.2019 06:01:32 DEBUG     HOSTER ShareonlineBiz[8449]: Plugin status: testing
07.09.2019 06:01:33 WARNING   HOSTER ShareonlineBiz[8449]: Plugin may be unstable
07.09.2019 06:01:33 DEBUG     ACCOUNT ShareonlineBiz: Reached login timeout for user `723*******`
07.09.2019 06:01:33 INFO      ACCOUNT ShareonlineBiz: Relogin user `723*******`...
07.09.2019 06:01:35 DEBUG     ACCOUNT ShareonlineBiz: LOAD URL https://api.share-online.biz/cgi-bin | redirect=True | cookies=True | get={'q': 'userdetails', 'aux': 'traffic', 'username': '723*******', 'password': '**********'} | req=None | decode=False | multipart=False | post={} | ref=True | just_header=False
07.09.2019 06:02:15 ERROR     ACCOUNT ShareonlineBiz: Could not login user `723*******` | (28, 'SSL connection timeout')
07.09.2019 06:02:16 INFO      HOSTER ShareonlineBiz[8449]: Grabbing link info...
07.09.2019 06:02:17 DEBUG     HOSTER ShareonlineBiz[8449]: Link info: {'status': 2, 'hash': {}, 'name': '*****.rar', 'url': u'http://www.share-online.biz/dl/*****', 'pattern': {'ID': u'*****'}, 'size': 157286400, 'md5': 'ce21a5dcb544b40de63b00ddffb194e7'}
07.09.2019 06:02:17 DEBUG     HOSTER ShareonlineBiz[8449]: Previous link info: {}
07.09.2019 06:02:18 INFO      HOSTER ShareonlineBiz[8449]: Link name: *****.rar
07.09.2019 06:02:19 INFO      HOSTER ShareonlineBiz[8449]: Link size: 150.00 MiB (157286400 bytes)
07.09.2019 06:02:21 INFO      HOSTER ShareonlineBiz[8449]: Link status: online
07.09.2019 06:02:22 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
07.09.2019 06:02:25 INFO      Download skipped: *****.rar due to File exists
07.09.2019 06:02:27 INFO      Download starts: *****.rar
07.09.2019 06:02:27 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
07.09.2019 06:02:28 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
07.09.2019 06:02:28 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
07.09.2019 06:02:28 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
07.09.2019 06:02:28 DEBUG     HOSTER ShareonlineBiz[8449]: Plugin version: 0.72
07.09.2019 06:02:29 DEBUG     HOSTER ShareonlineBiz[8449]: Plugin status: testing
07.09.2019 06:02:29 WARNING   HOSTER ShareonlineBiz[8449]: Plugin may be unstable
07.09.2019 06:02:29 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
07.09.2019 06:02:31 WARNING   Download failed: *****.rar | 'NoneType' object has no attribute 'get_info'
07.09.2019 06:02:32 ERROR     <<< UNCAUGHT EXCEPTION >>>
Traceback (most recent call last):
  File "pyload/pyLoadCore.py", line 685, in <module>
  File "pyload/pyLoadCore.py", line 672, in main
  File "pyload/pyLoadCore.py", line 664, in deamon
  File "pyload/pyLoadCore.py", line 486, in start
  File "/home/user/pyload/module/ThreadManager.py", line 151, in work
    self.assignJob()
  File "/home/user/pyload/module/ThreadManager.py", line 265, in assignJob
    inuse = set([(x.active.pluginname,self.getLimit(x)) for x in self.threads if x.active and x.active.hasPlugin() and x.active.plugin.account])
  File "/home/user/pyload/module/ThreadManager.py", line 313, in getLimit
    limit = thread.active.plugin.account.getAccountData(thread.active.plugin.user)["options"].get("limitDL",["0"])[0]
  File "/home/user/pyload/module/plugins/internal/misc.py", line 227, in new
    return fn(*args, **kwargs)
  File "/home/user/pyload/module/plugins/internal/Account.py", line 274, in getAccountData
    return self.accounts[user]
KeyError: None
```

**Comment by GammaC0de** [comment]
R.I.P ShareonlineBiz.
https://torrentfreak.com/police-raids-shut-down-share-online-biz-germanys-largest-file-hoster-191017/
