### ISSUE TITLE
Failed to start pyLoad 0.5.0

### ISSUE THREAD

**Issue by oltodosel** [pyload/pyload#3442]
```
[2019-09-09 12:09:36]  CRITICAL            pyload  unsupported operand type(s) for >>=: 'float' and 'int'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pyload/core/utils/format.py", line 49, in size
    return bitmath.Byte(value).best_prefix()
AttributeError: 'NoneType' object has no attribute 'Byte'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pyload/core/__init__.py", line 319, in start
    avail_space = format.size(fs.free_space(storage_folder))
  File "/usr/lib/python3.7/site-packages/pyload/core/utils/format.py", line 55, in size
    value >>= 10
TypeError: unsupported operand type(s) for >>=: 'float' and 'int'
[2019-09-09 12:09:36]  DEBUG               pyload  Stopping core...
[2019-09-09 12:09:36]  INFO                pyload  Exiting core...

```

**Comment by maxammann** [comment]
Having the same problem. Is there already a fix?

**Comment by oltodosel** [comment]
`pip install bitmath`
Then I got a multitude of new errors. I decided to go back to v0.49 for the now.
