### ISSUE TITLE
[Pyload] Exception when starting webinterface 

### ISSUE THREAD

**Issue by HooK81** [pyload/pyload#3465]
Hello all,
I have a very weird issue since my server suffer a power cut.

Now, the web interface is not running and I got a weird exception 

`julien@legolas:/usr/share/pyload` $ sudo /usr/bin/pyLoadCore

04.11.2019 15:07:53 INFO      Starting pyLoad 0.4.9
04.11.2019 15:07:53 INFO      Using home directory: /etc/pyload
04.11.2019 15:07:57 INFO      Activated plugins: EventMapper, ExternalScripts, UnSkipOnFail, UpdateManager, UserAgentSwitcher
04.11.2019 15:07:57 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, Checksum, ClickNLoad, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XFileSharing, XMPP
04.11.2019 15:07:57 INFO      Downloadtime: True
04.11.2019 15:07:57 INFO      Starting ThriftBackend: 0.0.0.0:7227
04.11.2019 15:07:57 INFO      Free space: 647.25 GiB
04.11.2019 15:07:57 INFO      Activating Accounts...
04.11.2019 15:07:57 INFO      Activating Plugins...
04.11.2019 15:07:57 INFO      pyLoad is up and running
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/pyload/module/web/ServerThread.py", line 30, in run
    import webinterface
  File "/usr/share/pyload/module/web/webinterface.py", line 117, in <module>
    from beaker.middleware import SessionMiddleware
  File "/usr/share/pyload/module/lib/beaker/middleware.py", line 12, in <module>
    from beaker.session import Session, SessionObject
  File "/usr/share/pyload/module/lib/beaker/session.py", line 7, in <module>
    from beaker.crypto import hmac as HMAC, hmac_sha1 as SHA1, md5
  File "/usr/share/pyload/module/lib/beaker/crypto/__init__.py", line 3, in <module>
    from beaker.crypto.pbkdf2 import PBKDF2, strxor
  File "/usr/share/pyload/module/lib/beaker/crypto/pbkdf2.py", line 75, in <module>
    from beaker.crypto.util import hmac as HMAC, hmac_sha1 as SHA1
  File "/usr/share/pyload/module/lib/beaker/crypto/util.py", line 7, in <module>
    from Crypto.Hash import HMAC as hmac, SHA as hmac_sha1
EOFError: EOF read where object expected

04.11.2019 15:07:57 INFO      ADDON UpdateManager: pyLoad is up to date!
04.11.2019 15:07:57 INFO      ADDON UpdateManager: All plugins are up to date!`

I tried to remove all pyc file and running again pyLoad but I got same error :(

Do you have any idea ?

**Comment by HooK81** [comment]
Fixed by reinstalling package python-crypto
`
sudo apt install --reinstall python-crypto
`
