### ISSUE TITLE
Rapidgator Plugin Issue

### ISSUE THREAD

**Issue by nxtwannabee** [pyload/pyload#3474]
### Describe the problem

Hello Guys
I can´t download anything using my rapidgator premium account. I´m running pyload in centos 7 and i tried to reinstall pyload but that doesn´t help..
Other filehosters are working really good.. but just the rapidgator plugin wont work correctly. 

### Debug log

```
login as: root
Keyboard-interactive authentication prompts from server:
| Password:
End of keyboard-interactive prompts from server
Last failed login: Mon Nov 11 11:17:05 UTC 2019 from 248.ip-145-239-196.eu on ss                                                                                                                                                             h:notty
There were 2259 failed login attempts since the last successful login.
Last login: Sun Nov 10 23:56:03 2019 from i6dfa86b9.versanet.de
[root@localhost ~]# sudo /root/pyload/pyload-stable/pyLoadCore.py -q
waiting for pyLoad to quit
pyLoad successfully stopped
[root@localhost ~]# sudo /root/pyload/pyload-stable/pyLoadCore.py -d
11.11.2019 11:17:28 INFO      starte pyLoad 0.4.9
11.11.2019 11:17:28 INFO      Benutze Home-Verzeichnis: /root/.pyload
11.11.2019 11:17:28 DEBUG     Remote activated: True
11.11.2019 11:17:29 DEBUG     created index of plugins
11.11.2019 11:17:29 INFO      Aktivierte Plugins: EventMapper, ExternalScripts,                                                                                                                                                              UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
11.11.2019 11:17:29 INFO      Deaktivierte Plugins: AndroidPhoneNotify, AntiStan                                                                                                                                                             dby, AntiVirus, BypassCaptcha, Captcha9Kw, Checksum, ClickNLoad, CloudFlareDdos,                                                                                                                                                              DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecod                                                                                                                                                             ers, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, Linkd                                                                                                                                                             ecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, Restart                                                                                                                                                             Failed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
11.11.2019 11:17:29 INFO      Downloadzeit: True
11.11.2019 11:17:29 INFO      Starte ThriftBackend: 0.0.0.0:7227
11.11.2019 11:17:29 INFO      Starting threaded webserver: 0.0.0.0:8888
11.11.2019 11:17:29 INFO      Free space: 1.00 PiB
11.11.2019 11:17:29 INFO      Activating Accounts...
11.11.2019 11:17:29 INFO      ACCOUNT RapidgatorNet: Adding user `exl*******`...
11.11.2019 11:17:29 DEBUG     ACCOUNT RapidgatorNet: Reached login timeout for u                                                                                                                                                             ser `exl*******`
11.11.2019 11:17:29 INFO      ACCOUNT RapidgatorNet: Login user `exl*******`...
11.11.2019 11:17:29 DEBUG     ACCOUNT RapidgatorNet: LOAD URL https://rapidgator                                                                                                                                                             .net/api/user/login | redirect=True | cookies=True | get={'username': 'exl******                                                                                                                                                             *', 'password': '**********'} | req=None | decode=True | multipart=False | post=                                                                                                                                                             {} | ref=True | just_header=False
11.11.2019 11:17:30 INFO      ACCOUNT RapidgatorNet: Grabbing account info for u                                                                                                                                                             ser `exl*******`...
11.11.2019 11:17:30 DEBUG     ACCOUNT RapidgatorNet: LOAD URL https://rapidgator                                                                                                                                                             .net/api/user/info | redirect=True | cookies=True | get={'sid': 'faf86db9c58c2cc                                                                                                                                                             d73e6ea28735d3def'} | req=None | decode=True | multipart=False | post={} | ref=T                                                                                                                                                             rue | just_header=False
11.11.2019 11:17:30 DEBUG     ACCOUNT RapidgatorNet: Account info for user `exl*                                                                                                                                                             ******`: {'login': {'timestamp': 1573471049.760562, 'password': '**********', 'v                                                                                                                                                             alid': True}, 'data': {'premium': True, 'plugin': <Account RapidgatorNet>, 'traf                                                                                                                                                             ficleft': 9304727246.78125, 'maxtraffic': None, 'sid': 'faf86db9c58c2ccd73e6ea28                                                                                                                                                             735d3def', 'validuntil': 1579692435, 'login': 'exl*******', 'type': 'RapidgatorN                                                                                                                                                             et', 'options': {'limitDL': ['0']}}}
11.11.2019 11:17:30 INFO      Activating Plugins...
11.11.2019 11:17:30 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubus                                                                                                                                                             ercontent.com/pyload/updates/master/plugins.txt | redirect=True | cookies=True |                                                                                                                                                              get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=T                                                                                                                                                             rue | just_header=False
11.11.2019 11:17:30 DEBUG     ADDON ExternalScripts: No script found under folde                                                                                                                                                             r `pyload_start`
11.11.2019 11:17:30 DEBUG     Redirected import module.plugins.internal.XFSHoste                                                                                                                                                             r -> userplugins.internal.XFSHoster
11.11.2019 11:17:30 DEBUG     Redirected import userplugins.captcha.ReCaptcha ->                                                                                                                                                              module.plugins.captcha.ReCaptcha
11.11.2019 11:17:30 DEBUG     Redirected import userplugins.captcha.SolveMedia -                                                                                                                                                             > module.plugins.captcha.SolveMedia
11.11.2019 11:17:30 DEBUG     Redirected import userplugins.internal.misc -> mod                                                                                                                                                             ule.plugins.internal.misc
11.11.2019 11:17:30 DEBUG     Redirected import userplugins.internal.SimpleHoste                                                                                                                                                             r -> module.plugins.internal.SimpleHoster
11.11.2019 11:17:30 DEBUG     Redirected import module.plugins.hoster.TurbobitNe                                                                                                                                                             t -> userplugins.hoster.TurbobitNet
11.11.2019 11:17:30 DEBUG     Redirected import module.plugins.hoster.RapiduNet                                                                                                                                                              -> userplugins.hoster.RapiduNet
11.11.2019 11:17:30 DEBUG     Redirected import module.plugins.hoster.Letsupload                                                                                                                                                             Co -> userplugins.hoster.LetsuploadCo
11.11.2019 11:17:30 INFO      ADDON XFileSharing: Auto-discover new hosters
11.11.2019 11:17:30 DEBUG     ADDON XFileSharing: Pattern for hosters: (?:https?                                                                                                                                                             ://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com|clicknupload\.org|cramit\.in|ddl\.t                                                                                                                                                             o|easybytez\.com|exashare\.com|filejoker\.net|fileom\.com|filerio\.com|fistfast\                                                                                                                                                             .net|hugefiles\.net|junocloud\.me|katfile\.com|movreel\.com|nosupload\.com|novaf                                                                                                                                                             ile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|stre                                                                                                                                                             amcloud\.eu|suprafiles\.me|tusfiles\.net|uploadrocket\.net|vidplay\.net))(?P<DOM                                                                                                                                                             AIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:                                                                                                                                                             \W|$)
11.11.2019 11:17:30 INFO      ADDON XFileSharing: Auto-discover new crypters
11.11.2019 11:17:30 DEBUG     ADDON XFileSharing: Pattern for crypters: (?:https                                                                                                                                                             ?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P<DOMAIN>(?:[\d.]                                                                                                                                                             +|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
11.11.2019 11:17:30 INFO      ADDON UpdateManager: pyLoad is up to date!
11.11.2019 11:17:30 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubus                                                                                                                                                             ercontent.com/pyload/updates/master/plugins.txt | redirect=True | cookies=True |                                                                                                                                                              get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=T                                                                                                                                                             rue | just_header=False
11.11.2019 11:17:30 INFO      pyLoad is up and running
11.11.2019 11:17:30 DEBUG     ADDON UpdateManager: Requested deletion of plugins                                                                                                                                                             : [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accoun                                                                                                                                                             ts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'Ddlstorag                                                                                                                                                             eCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accoun                                                                                                                                                             ts', u'FileParadoxIn'), (u'accounts', u'FreeWayMe'), (u'accounts', u'HotfileCom'                                                                                                                                                             ), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts',                                                                                                                                                              u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'),                                                                                                                                                              (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'                                                                                                                                                             NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'                                                                                                                                                             accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRap                                                                                                                                                             idCom'), (u'accounts', u'ShareonlineBiz'), (u'accounts', u'StahnuTo'), (u'accoun                                                                                                                                                             ts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'Uploading                                                                                                                                                             Com'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accoun                                                                                                                                                             ts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'ShareonlineBiz'),                                                                                                                                                              (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'),                                                                                                                                                              (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCo                                                                                                                                                             m'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter'                                                                                                                                                             , u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'                                                                                                                                                             ), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypte                                                                                                                                                             r', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFol                                                                                                                                                             der'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder')                                                                                                                                                             , (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hook                                                                                                                                                             s', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw')                                                                                                                                                             , (u'hooks', u'CaptchaBrotherhood'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'                                                                                                                                                             ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook                                                                                                                                                             '), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'E                                                                                                                                                             v0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks',                                                                                                                                                              u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks'                                                                                                                                                             , u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'                                                                                                                                                             ), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'                                                                                                                                                             MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'h                                                                                                                                                             ooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDe                                                                                                                                                             bridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (                                                                                                                                                             u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'Myfast                                                                                                                                                             fileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hook                                                                                                                                                             s', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'                                                                                                                                                             ), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHo                                                                                                                                                             ok'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u                                                                                                                                                             'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hook                                                                                                                                                             s', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u                                                                                                                                                             'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'Rehos                                                                                                                                                             tTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'Restar                                                                                                                                                             tSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (                                                                                                                                                             u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'                                                                                                                                                             SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hoo                                                                                                                                                             ks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPho                                                                                                                                                             neToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (                                                                                                                                                             u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCo                                                                                                                                                             m'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'                                                                                                                                                             Keep2shareCc'), (u'hoster', u'Libgen'), (u'hoster', u'MegaDebrid'), (u'hoster',                                                                                                                                                              u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'ho                                                                                                                                                             ster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'),                                                                                                                                                              (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'Rapidsh                                                                                                                                                             areCom'), (u'hoster', u'RealdebridComTorrent'), (u'hoster', u'ReloadCc'), (u'hos                                                                                                                                                             ter', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCo                                                                                                                                                             m'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh'), (u'hoster', u'Vip                                                                                                                                                             leech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor                                                                                                                                                             '), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'H                                                                                                                                                             ook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u                                                                                                                                                             'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'),                                                                                                                                                              (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'ut                                                                                                                                                             ils')]
11.11.2019 11:17:30 INFO      ADDON UpdateManager: All plugins are up to date!
11.11.2019 11:17:52 INFO      Download starts: pyload-stable.zip
11.11.2019 11:17:52 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
11.11.2019 11:17:52 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
11.11.2019 11:17:52 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
11.11.2019 11:17:52 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW                                                                                                                        64; rv:38.0) Gecko/20100101 Firefox/38.0`
11.11.2019 11:17:52 DEBUG     HOSTER RapidgatorNet[23]: Plugin version: 0.54
11.11.2019 11:17:52 DEBUG     HOSTER RapidgatorNet[23]: Plugin status: testing
11.11.2019 11:17:52 WARNING   HOSTER RapidgatorNet[23]: Plugin may be unstable
11.11.2019 11:17:52 INFO      ACCOUNT RapidgatorNet: Grabbing account info for user `exl*******`...
11.11.2019 11:17:52 DEBUG     ACCOUNT RapidgatorNet: LOAD URL https://rapidgator.net/api/user/info | redirect=True |                                                                                                                         cookies=True | get={'sid': 'faf86db9c58c2ccd73e6ea28735d3def'} | req=None | decode=True | multipart=False | post={} |                                                                                                                         ref=True | just_header=False
11.11.2019 11:17:52 DEBUG     ACCOUNT RapidgatorNet: Account info for user `exl*******`: {'login': {'timestamp': 1573                                                                                                                        471049.760562, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account RapidgatorNet>,                                                                                                                         'trafficleft': 9304727246.78125, 'maxtraffic': None, 'sid': 'faf86db9c58c2ccd73e6ea28735d3def', 'validuntil': 157969                                                                                                                        2435, 'login': 'exl*******', 'type': 'RapidgatorNet', 'options': {'limitDL': ['0']}}}
11.11.2019 11:17:52 INFO      HOSTER RapidgatorNet[23]: Grabbing link info...
11.11.2019 11:17:52 DEBUG     HOSTER RapidgatorNet[23]: Link info: {'status': 2, 'hash': {u'MD5': u'b87b8d8786e023663                                                                                                                        53e27d9d2856dd0'}, 'name': u'pyload-stable.zip', 'url': u'https://rapidgator.net/file/a61203dcf2be2c3e82d7dfb52ebfe09                                                                                                                        5', 'pattern': {'H': u'MD5', 'S': u'2.23', 'U': u'MB', 'D': u'b87b8d8786e02366353e27d9d2856dd0', 'N': u'pyload-stable                                                                                                                        .zip'}, 'size': 2338324}
11.11.2019 11:17:52 DEBUG     HOSTER RapidgatorNet[23]: Previous link info: {}
11.11.2019 11:17:52 INFO      HOSTER RapidgatorNet[23]: Link name: pyload-stable.zip
11.11.2019 11:17:52 INFO      HOSTER RapidgatorNet[23]: Link size: 2.23 MiB (2338324 bytes)
11.11.2019 11:17:52 INFO      HOSTER RapidgatorNet[23]: Link status: online
11.11.2019 11:17:53 INFO      HOSTER RapidgatorNet[23]: Processing url: https://rapidgator.net/file/a61203dcf2be2c3e8                                                                                                                        2d7dfb52ebfe095
11.11.2019 11:17:53 INFO      HOSTER RapidgatorNet[23]: Looking for direct download link...
11.11.2019 11:17:53 DEBUG     HOSTER RapidgatorNet[23]: LOAD URL https://rapidgator.net/file/a61203dcf2be2c3e82d7dfb5                                                                                                                        2ebfe095 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | ju                                                                                                                        st_header=True
11.11.2019 11:17:53 DEBUG     HOSTER RapidgatorNet[23]: Redirect #1 to: http://pr20.rapidgator.net//?r=download/index                                                                                                                        &session_id=eEglq0rEqxWd2IgNsnXFQ017my8n7sxo
11.11.2019 11:17:53 DEBUG     HOSTER RapidgatorNet[23]: LOAD URL http://pr20.rapidgator.net//?r=download/index&sessio                                                                                                                        n_id=eEglq0rEqxWd2IgNsnXFQ017my8n7sxo | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=Fa                                                                                                                        lse | post={} | ref=True | just_header=True
11.11.2019 11:17:53 INFO      HOSTER RapidgatorNet[23]: Direct download link detected
11.11.2019 11:17:53 INFO      HOSTER RapidgatorNet[23]: Downloading file...
11.11.2019 11:17:53 DEBUG     HOSTER RapidgatorNet[23]: DOWNLOAD URL https://rapidgator.net/file/a61203dcf2be2c3e82d7                                                                                                                        dfb52ebfe095 | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
11.11.2019 11:17:54 DEBUG     Error removing chunk: curl object not on this multi-stack
11.11.2019 11:17:54 ERROR     HOSTER RapidgatorNet[23]:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 785, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/root/pyload/pyload-stable/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/root/pyload/pyload-stable/module/plugins/internal/Base.py", line 294, in preprocessing
    return self._process(*args, **kwargs)
  File "/root/pyload/pyload-stable/module/plugins/internal/Hoster.py", line 116, in _process
    self.process(self.pyfile)
  File "/root/pyload/pyload-stable/module/plugins/internal/SimpleHoster.py", line 286, in process
    self.download(self.link, disposition=self.DISPOSITION)
  File "/root/pyload/pyload-stable/module/plugins/internal/Hoster.py", line 309, in download
    disposition, resume, chunks)
  File "/root/pyload/pyload-stable/module/plugins/internal/Hoster.py", line 231, in _download
    progressNotify=self.pyfile.setProgress, disposition=disposition)
  File "/root/pyload/pyload-stable/module/network/Browser.py", line 88, in httpDownload
    name = self.dl.download(chunks, resume)
  File "/root/pyload/pyload-stable/module/network/HTTPDownload.py", line 145, in download
    self.close()
  File "/root/pyload/pyload-stable/module/network/HTTPDownload.py", line 317, in close
    self.closeChunk(chunk)
  File "/root/pyload/pyload-stable/module/network/HTTPDownload.py", line 312, in closeChunk
    chunk.close()
  File "/root/pyload/pyload-stable/module/network/HTTPChunk.py", line 291, in close
    if self.fp: self.fp.close()
IOError: [Errno 1] Operation not permitted

11.11.2019 11:17:54 WARNING   HOSTER RapidgatorNet[23]: Premium download failed | IOError 1
11.11.2019 11:17:54 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
11.11.2019 11:17:54 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
11.11.2019 11:17:54 INFO      Download restarted: pyload-stable.zip | Fallback to free processing
11.11.2019 11:17:54 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
11.11.2019 11:17:54 DEBUG     All downloads processed
11.11.2019 11:17:54 INFO      Download starts: pyload-stable.zip
11.11.2019 11:17:54 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
11.11.2019 11:17:54 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
11.11.2019 11:17:54 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
11.11.2019 11:17:54 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW                                                                                                                        64; rv:38.0) Gecko/20100101 Firefox/38.0`
11.11.2019 11:17:54 DEBUG     HOSTER RapidgatorNet[23]: Plugin version: 0.54
11.11.2019 11:17:54 DEBUG     HOSTER RapidgatorNet[23]: Plugin status: testing
11.11.2019 11:17:54 WARNING   HOSTER RapidgatorNet[23]: Plugin may be unstable
11.11.2019 11:17:54 INFO      HOSTER RapidgatorNet[23]: Grabbing link info...
11.11.2019 11:17:54 DEBUG     HOSTER RapidgatorNet[23]: Link info: {'status': 2, 'hash': {u'MD5': u'b87b8d8786e023663                                                                                                                        53e27d9d2856dd0'}, 'name': u'pyload-stable.zip', 'url': u'https://rapidgator.net/file/a61203dcf2be2c3e82d7dfb52ebfe09                                                                                                                        5', 'pattern': {'H': u'MD5', 'S': u'2.23', 'U': u'MB', 'D': u'b87b8d8786e02366353e27d9d2856dd0', 'N': u'pyload-stable                                                                                                                        .zip'}, 'size': 2338324}
11.11.2019 11:17:54 DEBUG     HOSTER RapidgatorNet[23]: Previous link info: {'status': 2, 'hash': {u'MD5': u'b87b8d87                                                                                                                        86e02366353e27d9d2856dd0'}, 'name': u'pyload-stable.zip', 'url': u'https://rapidgator.net/file/a61203dcf2be2c3e82d7df                                                                                                                        b52ebfe095', 'pattern': {'H': u'MD5', 'S': u'2.23', 'U': u'MB', 'D': u'b87b8d8786e02366353e27d9d2856dd0', 'N': u'pylo                                                                                                                        ad-stable.zip'}, 'size': 2338324}
11.11.2019 11:17:54 INFO      HOSTER RapidgatorNet[23]: Link name: pyload-stable.zip
11.11.2019 11:17:54 INFO      HOSTER RapidgatorNet[23]: Link size: 2.23 MiB (2338324 bytes)
11.11.2019 11:17:54 INFO      HOSTER RapidgatorNet[23]: Link status: online
11.11.2019 11:17:54 INFO      HOSTER RapidgatorNet[23]: Processing url: https://rapidgator.net/file/a61203dcf2be2c3e8                                                                                                                        2d7dfb52ebfe095
11.11.2019 11:17:54 INFO      HOSTER RapidgatorNet[23]: Looking for direct download link...
11.11.2019 11:17:54 DEBUG     HOSTER RapidgatorNet[23]: LOAD URL https://rapidgator.net/file/a61203dcf2be2c3e82d7dfb5                                                                                                                        2ebfe095 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | ju                                                                                                                        st_header=True
11.11.2019 11:17:54 INFO      HOSTER RapidgatorNet[23]: Direct download link not found
11.11.2019 11:17:54 DEBUG     HOSTER RapidgatorNet[23]: LOAD URL https://rapidgator.net/file/a61203dcf2be2c3e82d7dfb5                                                                                                                        2ebfe095 | redirect=True | cookies=[('rapidgator.net', 'lang', 'en')] | get={} | req=None | decode=True | multipart=F                                                                                                                        alse | post={} | ref=False | just_header=False
11.11.2019 11:17:54 INFO      HOSTER RapidgatorNet[23]: Checking for link errors...
11.11.2019 11:17:54 WARNING   HOSTER RapidgatorNet[23]: Free download failed | File can be downloaded by premium user                                                                                                                        s only
11.11.2019 11:17:54 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
11.11.2019 11:17:54 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
11.11.2019 11:17:54 WARNING   Download failed: pyload-stable.zip | File can be downloaded by premium users only
11.11.2019 11:17:54 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
11.11.2019 11:17:54 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: pyload-stable.zip (pid:7)
11.11.2019 11:17:54 INFO      ADDON UnSkipOnFail: No duplicates found
11.11.2019 11:17:54 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
11.11.2019 11:17:54 DEBUG     All downloads processed

```

### Additional references

..hope anyone can help me..
regards :)

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by nxtwannabee** [comment]
now i can download the files correctly. I think the issue was caused to my download destination. It was a mounted gogole drive folder (rclone). Now i´ve changed it and it seems to word for now :)
..is it possible to download the files directly to the google drive mounted by rclone? Because pyload ist running on a small vps server with just a 15 gb ssd..
regards :)

**Comment by GammaC0de** [comment]
Are you running pyload as root?

**Comment by nxtwannabee** [comment]
no, as another user. But i have mounted the gogole drive folder with the user who is running pyload.
It´s possible to extract the downloaded files to the google drive mount using ExtractArchive. So the permissions should be okey.

**Comment by GammaC0de** [comment]
Using cloud filesystem can be slow and it I would not recommend to use it as a download folder.

**Comment by nxtwannabee** [comment]
okey, thank you :) Then i have the download limit from the ssd... 
Is it possible to pause the downloads while pyload is extracting a file? Or pause the downloads if the download folder is full and start them when there is memory availible again? So i could use it with the delete after extraction option ?

**Comment by nxtwannabee** [comment]
solved the problem for me. 
Simply added --vfs-cache-mode writes --vfs-cache-max-age 0h0m0s to the rclone mount. Then i can download directly to the cloud storage 👍

**Comment by GammaC0de** [comment]
:+1:
