### ISSUE TITLE
No module named 'filetype'/'magic' during pyload run.

### ISSUE THREAD

**Issue by ErnestoD** [pyload/pyload#3475]
When running pyload from PowerShell I get "No module named 'filetype'/'magic'.

### Debug log
ModuleNotFoundError: No module named 'filetype'
Traceback (most recent call last):
  File "c:\users\*\appdata\local\programs\python\python38-32\lib\site-packages\pyload\core\utils\fs.py", line 18, in <module>
    import magic
ModuleNotFoundError: No module named 'magic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\*\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\*\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38-32\Scripts\pyload.exe\__main__.py", line 4, in <module>
    from pyload.script import main
  File "c:\users\*\appdata\local\programs\python\python38-32\lib\site-packages\pyload\script.py", line 9, in <module>
    from .core import Core
  File "c:\users\*\appdata\local\programs\python\python38-32\lib\site-packages\pyload\core\__init__.py", line 22, in <module>
    from .utils import format, fs
  File "c:\users\*\appdata\local\programs\python\python38-32\lib\site-packages\pyload\core\utils\format.py", line 9, in <module>
    from .fs import fullpath
  File "c:\users\*\appdata\local\programs\python\python38-32\lib\site-packages\pyload\core\utils\fs.py", line 21, in <module>
    from filetype import guess_mime
ModuleNotFoundError: No module named 'filetype'

```

```

**Comment by GammaC0de** [comment]
You have installed the alpha version of pyload which is not ready yet.

You should install python 2.7 and then the stable version of pyload.

**Comment by ErnestoD** [comment]
Ah ok. I have Python 2.7 installed along with Python 3. I am a studied programmer looking to find projects to contribute to and found this one. Although I am all pretty new to this.

**Comment by Goblin80** [comment]
`pip install python-magic`
