### ISSUE TITLE
ClickNLoad SSL

### ISSUE THREAD

**Issue by UserX404** [pyload/pyload#3517]
### Describe the problem

After a QNAP update (4.4.1.1216) i got problems with ClickNload.
Maybe someone is able to guide me to bring functionality back again.

### Debug log

```
1887 | 18.02.2020 17:57:17 | DEBUG | ADDON ClickNLoad: Connection from 192.168.1.2:57480
-- | -- | -- | --
1888 | 18.02.2020 17:57:17 | ERROR | ADDON ClickNLoad: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:727)

```

**Comment by UserX404** [comment]
in addition I also run into problems with the ssl webserver

`Exception in thread Thread-12:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/share/CACHEDEV1_DATA/.qpkg/Entware/share/pyload/module/web/ServerThread.py", line 71, in run
    self.start_threaded()
  File "/share/CACHEDEV1_DATA/.qpkg/Entware/share/pyload/module/web/ServerThread.py", line 93, in start_threaded
    webinterface.run_threaded(host=self.host, port=self.port, cert=self.cert, key=self.key)
  File "/share/CACHEDEV1_DATA/.qpkg/Entware/share/pyload/module/web/webinterface.py", line 156, in run_threaded
    run(app=web, host=host, port=port, server=CherryPyWSGI, quiet=True)
  File "/share/CACHEDEV1_DATA/.qpkg/Entware/share/pyload/module/lib/bottle.py", line 2383, in run
    server.run(app)
  File "/share/CACHEDEV1_DATA/.qpkg/Entware/share/pyload/module/web/utils.py", line 137, in run
    server.start()
  File "/share/CACHEDEV1_DATA/.qpkg/Entware/share/pyload/module/lib/wsgiserver/__init__.py", line 1607, in start
    self.tick()
  File "/share/CACHEDEV1_DATA/.qpkg/Entware/share/pyload/module/lib/wsgiserver/__init__.py", line 1678, in tick
    conn = self.ConnectionClass(s, self.wsgi_app, environ)
  File "/share/CACHEDEV1_DATA/.qpkg/Entware/share/pyload/module/lib/wsgiserver/__init__.py", line 1142, in __init__
    if SSL and isinstance(sock, SSL.ConnectionType):
AttributeError: 'module' object has no attribute 'ConnectionType'
`

**Comment by UserX404** [comment]
#3488
leads me to the solution
