### ISSUE TITLE
Raspberry pi 4 - not compatible

### ISSUE THREAD

**Issue by 71m383nd3r** [pyload/pyload#3560]
I tired everything but simply it's not working, the instruction manual on wiki it's a old version for RPI3 still the pyload instruction is old and rusty.
What can we do about it?

**Comment by GammaC0de** [comment]
You probably should install the deb file: https://github.com/pyload/pyload/releases/download/0.4.20/pyload-cli_0.4.20_all.deb

**Comment by 71m383nd3r** [comment]
simply it's not compatible with python 3...
my RPI has the latest Python 3.7.3 + pyLoad

pi@raspberrypi:~ $ python3 --version
Python 3.7.3
pi@raspberrypi:~ $ pyload
ModuleNotFoundError: No module named 'filetype'
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pyload/core/utils/fs.py", line 18, in <module>
    import magic
ModuleNotFoundError: No module named 'magic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/bin/pyload", line 6, in <module>
    from pyload.script import main
  File "/home/pi/.local/lib/python3.7/site-packages/pyload/script.py", line 9, in <module>
    from .core import Core
  File "/home/pi/.local/lib/python3.7/site-packages/pyload/core/__init__.py", line 22, in <module>
    from .utils import format, fs
  File "/home/pi/.local/lib/python3.7/site-packages/pyload/core/utils/format.py", line 9, in <module>
    from .fs import fullpath
  File "/home/pi/.local/lib/python3.7/site-packages/pyload/core/utils/fs.py", line 21, in <module>
    from filetype import guess_mime
ModuleNotFoundError: No module named 'filetype'
pi@raspberrypi:~ $

**Comment by GammaC0de** [comment]
Sadly pyLoad does not support python 3, only python 2.7.

**Comment by 71m383nd3r** [comment]
still when remove python3 and install python2.7 still I get the same error. What to do now about it?

**Comment by GammaC0de** [comment]
Log please.

**Comment by JimScope** [comment]
Install the python-magic package
