### ISSUE TITLE
error: [Errno 32] Broken pipe and error: [Errno 131] Connection reset by peer

### ISSUE THREAD

**Issue by juankaxxi** [pyload/pyload#3585]
Hello!!, in the last days I have this error and in a certain time pyload closes, but I cannot find information why it may be.

pyload is installed on a xioami 3g router with openwrt version 19.07.2

Thank you

16.04.2020 08:10:10 INFO      Starting pyLoad 0.4.20
16.04.2020 08:10:10 INFO      Using home directory: /mnt/software/pyload/.pyload
16.04.2020 08:10:19 INFO      Activated plugins: Captcha9Kw, ClickNLoad, EventMa                                                                                                                                                             pper, ExternalScripts, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileShar                                                                                                                                                             ing
16.04.2020 08:10:19 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandb                                                                                                                                                             y, AntiVirus, AppriseNotify, BypassCaptcha, Checksum, CloudFlareDdos, DeathByCap                                                                                                                                                             tcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, Extrac                                                                                                                                                             tArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterCom                                                                                                                                                             Hook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, Ski                                                                                                                                                             pRev, TransmissionRPC, WindowsPhoneNotify, XMPP
16.04.2020 08:10:19 INFO      Downloadtime: True
16.04.2020 08:10:20 INFO      Starting ThriftBackend: 0.0.0.0:7227
16.04.2020 08:10:24 INFO      Starting builtin webserver: 0.0.0.0:8000
16.04.2020 08:10:24 INFO      Free space: 209.44 GiB
16.04.2020 08:10:24 INFO      Activating Accounts...
16.04.2020 08:10:24 INFO      Activating Plugins...
16.04.2020 08:10:29 INFO      ADDON XFileSharing: Auto-discover new hosters
16.04.2020 08:10:30 INFO      ADDON XFileSharing: Auto-discover new crypters
16.04.2020 08:10:30 INFO      pyLoad is up and running
16.04.2020 08:10:30 INFO      ADDON UpdateManager: pyLoad is up to date!
16.04.2020 08:10:31 INFO      ADDON UpdateManager: All plugins are up to date!
16.04.2020 08:10:32 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
  File "/usr/lib/python2.7/socket.py", line 328, in write
  File "/usr/lib/python2.7/socket.py", line 307, in flush
error: [Errno 131] Connection reset by peer
----------------------------------------
Exception happened during processing of request from ('192.168.1.135', 53739)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 293, in _handle_request_nobloc                                                                                                                                                             k
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
  File "/usr/lib/python2.7/socket.py", line 283, in close
  File "/usr/lib/python2.7/socket.py", line 307, in flush
error: [Errno 32] Broken pipe
----------------------------------------

**Comment by juankaxxi** [comment]
Error on openwrt 19.02, on 19.01 works
