### ISSUE TITLE
pyload dont start

### ISSUE THREAD

**Issue by ikhaltanov** [pyload/pyload#3608]
### Your question

Keenetic OS. openwrt 0.4.20.
made the installation by default.
noticed that he creates identical files in two directories var / pyload and root / .pyload
the service crashes and does not enter the web interface.
```
This is your first start, running configuration assistent now.
Choose your Language / Wähle deine Sprache ([en], de, fr, it, es, nl, sv, ru, pl, cs, sr, pt_BR):

Welcome to the pyLoad Configuration Assistent.
It will check your system and make a basic setup in order to run pyLoad.

The value in brackets [] always is the default value,
in case you don't want to change it or you are unsure what to choose, just hit enter.
Don't forget: You can always rerun this assistent with --setup or -s parameter, when you start pyLoadCore.
If you have any problems with this assistent hit STRG-C,
to abort and don't let him start with pyLoadCore automatically anymore.

When you are ready for system check, hit enter.

## System Check ##
Python Version: OK
pycurl: OK
sqlite3: OK

pycrypto: OK
py-OpenSSL: OK

py-imaging: OK
tesseract: OK

PyQt4: missing

jinja2: OK
beaker: OK
JS engine: OK

System check finished, hit enter to see your status report.

## Status ##

Features available: container decrypting, ssl connection, automatic captcha decryption, Webinterface, exten                                                                                  ded Click'N'Load

Continue with setup? ([y]/n):

Do you want to change the config path? Current is /opt/var/pyload
If you use pyLoad on a server or the home partition lives on an internal flash it may be a good idea to cha                                                                                  nge it.
Change config path? (y/[n]):

Do you want to configure login data and basic settings?
This is recommend for first run.
Make basic setup? ([y]/n):

## Basic Setup ##

The following logindata is valid for CLI, GUI and webinterface.
Username [User]: admin
Password:
Password (again):

External clients (GUI, CLI or other) need remote access to work over the network.
However, if you only want to use the webinterface you may disable it to save ram.
Enable remote access ([y]/n):

Language ([en], de, fr, it, es, nl, sv, ru, pl, cs, sr, pt_BR):
Downloadfolder [Downloads]:
Max parallel downloads [3]:
Use Reconnect? (y/[n]):

Do you want to configure ssl?
Configure ssl? (y/[n]):

Do you want to configure webinterface?
Configure webinterface? ([y]/n):

## Webinterface Setup ##

Activate webinterface? ([y]/n):

Listen address, if you use 127.0.0.1 or localhost, the webinterface will only accessible locally.
Address [0.0.0.0]:
Port [8000]:

pyLoad offers several server backends, now following a short explanation.
builtin: Default server, best choice if you dont know which one to choose.
threaded: This server offers SSL and is a good alternative to builtin.
fastcgi: Can be used by apache, lighttpd, requires you to configure them, which is not too easy job.
lightweight: Very fast alternative written in C, requires libev and linux knowlegde.
        Get it from here: https://github.com/jonashaag/bjoern, compile it
        and copy bjoern.so to module/lib

Attention: In some rare cases the builtin server is not working, if you notice problems with the webinterface
come back here and change the builtin server to the threaded one here.

Server ([builtin], threaded, fastcgi, lightweight):

pyLoad offers several web user interface templates, please choose a webinterface template you like.
Template (classic, [modern], pyplex):

Setup finished successfully.
Hit enter to exit and restart pyLoad
```

when i write pyload:
```
~ # pyload
28.04.2020 09:36:02 INFO      Starting pyLoad 0.4.20
28.04.2020 09:36:02 INFO      Using home directory: /opt/root/.pyload
28.04.2020 09:36:11 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
28.04.2020 09:36:11 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
28.04.2020 09:36:11 INFO      Downloadtime: True
28.04.2020 09:36:11 ERROR     <<< UNCAUGHT EXCEPTION >>>
Traceback (most recent call last):
  File "/opt/bin/pyload", line 687, in <module>
    main()
  File "/opt/bin/pyload", line 678, in main
    pyload_core.start()
  File "/opt/bin/pyload", line 419, in start
    self.remoteManager.startBackends()
  File "/opt/share/pyload/module/remote/RemoteManager.py", line 76, in startBackends
    klass = getattr(__import__("module.remote.%s" % b, globals(), locals(), [b], -1), b)
AttributeError: 'module' object has no attribute 'ThriftBackend'
```

**Comment by GammaC0de** [comment]
From where have you downloaded pyload?

**Comment by ikhaltanov** [comment]
Downloading http://bin.entware.net/mipselsf-k3.4/pyload_0.4.20-1_mipsel-3.4.ipk

**Comment by GammaC0de** [comment]
Try running
 `python /opt/share/pyload/pyLoadCore.py -d ---configdir=/opt/root/.pyload` 
and see if it helps.

**Comment by ikhaltanov** [comment]
> 
> 
> Try running
> `python /opt/share/pyload/pyLoadCore.py -d ---configdir=/opt/root/.pyload`
> and see if it helps.

dont help:
```
~ # python /opt/share/pyload/pyLoadCore.py -d ---configdir=/opt/root/.pyload
Unknown Argument(s) "-d ---configdir=/opt/root/.pyload"

pyLoad v0.4.20     2008-2011 the pyLoad Team

Usage: python pyLoadCore.py [options]

<Options>
  -v, --version            Print version to terminal
  -c, --clear              Delete all saved packages/links
  -u, --user               Manages users
  -d, --debug              Enable debug mode
  -s, --setup              Run Setup Assistent
  --configdir=<dir>        Run with <dir> as config directory
  -p, --pidfile=<file>     Set pidfile to <file>
  --changedir              Change config dir permanently
  --daemon                 Daemonmize after start
  --no-remote              Disable remote access (saves RAM)
  --status                 Display pid if running or False
  --clean                  Remove .pyc/.pyo files
  -q, --quit               Quit running pyLoad instance
  -h, --help               Display this help screen
```

**Comment by GammaC0de** [comment]
oops, there was a mistake:
`python /opt/share/pyload/pyLoadCore.py -d --configdir=/opt/root/.pyload`

**Comment by ikhaltanov** [comment]
don't help, after configuration:
```
~ # /opt/etc/init.d/S51pyload start
starting pyLoad
Daemon PID 11451
```
and don't start
ps show service 5 sec and crash.
where i can see logs?

**Comment by GammaC0de** [comment]
> where i can see logs?

If you would have done what I asked you in https://github.com/pyload/pyload/issues/3608#issuecomment-622067430, you could see the log in the console..

**Comment by ikhaltanov** [comment]
no, where i can see logs why service crash after 5 sec starting?

**Comment by GammaC0de** [comment]
Is `/opt/share/pyload/` folder read only? it should be writeable..

**Comment by ikhaltanov** [comment]
![изображение](https://user-images.githubusercontent.com/64446870/80769146-3e486880-8b87-11ea-9059-b78e872c9824.png)
