### ISSUE TITLE
Ddl.to problems without XFileSharing

### ISSUE THREAD

**Issue by kabelclown** [pyload/pyload#3637]
### Describe the problem

I have the same problem as #3618 but the solution to deactivate the plugin XFileSharing caused below problems. A screenshot of the plugin settings is attached further below.

### Debug log

```
766 | 14.05.2020 16:06:21 | CRITICAL | 'NoneType' object has no attribute 'group'
-- | -- | -- | --
767 | ? | ? | Traceback (most recent call last):
768 | ? | ? | File "/app/pyload/module/ThreadManager.py", line 269, in assignJob
769 | ? | ? | job.initPlugin()
770 | ? | ? | File "/app/pyload/module/utils.py", line 169, in new
771 | ? | ? | return func(*args)
772 | ? | ? | File "/app/pyload/module/PyFile.py", line 103, in initPlugin
773 | ? | ? | self.plugin = self.pluginclass(self)
774 | ? | ? | File "/app/pyload/module/plugins/internal/Base.py", line 99, in __init__
775 | ? | ? | self.init()
776 | ? | ? | File "/app/pyload/module/plugins/hoster/XFileSharing.py", line 38, in init
777 | ? | ? | self.pyfile.url).group("DOMAIN").lower()
778 | ? | ? | AttributeError: 'NoneType' object has no attribute 'group'
779 | 14.05.2020 16:06:23 | CRITICAL | 'NoneType' object has no attribute 'group'
780 | ? | ? | Traceback (most recent call last):
781 | ? | ? | File "/app/pyload/module/ThreadManager.py", line 269, in assignJob
782 | ? | ? | job.initPlugin()
783 | ? | ? | File "/app/pyload/module/utils.py", line 169, in new
784 | ? | ? | return func(*args)
785 | ? | ? | File "/app/pyload/module/PyFile.py", line 103, in initPlugin
786 | ? | ? | self.plugin = self.pluginclass(self)
787 | ? | ? | File "/app/pyload/module/plugins/internal/Base.py", line 99, in __init__
788 | ? | ? | self.init()
789 | ? | ? | File "/app/pyload/module/plugins/hoster/XFileSharing.py", line 38, in init
790 | ? | ? | self.pyfile.url).group("DOMAIN").lower()
791 | ? | ? | AttributeError: 'NoneType' object has no attribute 'group'


```

### Screenshots

![image](https://user-images.githubusercontent.com/981062/81958261-0244e700-960e-11ea-9a20-85d1892443a6.png)

**Comment by GammaC0de** [comment]
You have to delete the package and then re-add it

**Comment by kabelclown** [comment]
> You have to delete the package and then re-add it

That indeed helped. Thank you
