### ISSUE TITLE
Keep2Share Plugin Fails to Expose CAPTCHA

### ISSUE THREAD

**Issue by mischif** [pyload/pyload#3642]
## Describe the problem
When I attempt to add a Keep2Share account to my pyLoad instance, a request to solve a CAPTCHA is made. The CAPTCHA is never given to me to solve, so I am never able to successfully add the account; additionally while waiting for the CAPTCHA request to timeout my instance is completely unresponsive.

### Debug log
```
ACCOUNT Keep2ShareCc: Updating account info for user `cxn*******`...
INFO	ACCOUNT Keep2ShareCc: Relogin user `cxn*******`...
DEBUG	CAPTCHA Keep2ShareCc: ReCaptcha | Challenge reCAPTCHA v2 interactive
WARNING	CAPTCHA Keep2ShareCc: ReCaptcha | Invalid captcha
ERROR	ACCOUNT Keep2ShareCc: Could not login user `cxn*******` | Invalid captcha
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
self.__bootstrap_inner()
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "~/private/pyload/module/web/ServerThread.py", line 78, in run
self.start_builtin()
File "~/private/pyload/module/web/ServerThread.py", line 85, in start_builtin
webinterface.run_simple(host=self.host, port=self.port)
File "~/private/pyload/module/web/webinterface.py", line 139, in run_simple
run(app=web, host=host, port=port, quiet=True)
File "~/private/pyload/module/lib/bottle.py", line 3137, in run
server.run(app)
File "~/private/pyload/module/lib/bottle.py", line 2790, in run
srv.serve_forever()
File "/usr/lib/python2.7/SocketServer.py", line 233, in serve_forever
self._handle_request_noblock()
File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
self.process_request(request, client_address)
File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
self.finish_request(request, client_address)
File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
self.handle()
File "/usr/lib/python2.7/wsgiref/simple_server.py", line 131, in handle
handler.run(self.server.get_app())
File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
self.result = application(self.environ, self.start_response)
File "~/private/pyload/module/web/middlewares.py", line 53, in __call__
response.gzip_start_response)
File "~/private/pyload/module/web/middlewares.py", line 17, in __call__
return self.app(e, h)
File "~/private/pyload/module/lib/beaker/middleware.py", line 152, in __call__
return self.wrap_app(environ, session_start_response)
File "~/private/pyload/module/lib/bottle.py", line 985, in __call__
return self.wsgi(environ, start_response)
File "~/private/pyload/module/lib/bottle.py", line 960, in wsgi
out = self._cast(self._handle(environ))
File "~/private/pyload/module/lib/bottle.py", line 868, in _handle
return route.call(**args)
File "~/private/pyload/module/lib/bottle.py", line 1748, in wrapper
rv = callback(*a, **ka)
File "~/private/pyload/module/web/utils.py", line 112, in _view
return func(*args, **kwargs)
File "~/private/pyload/module/web/json_app.py", line 315, in update_accounts
PYLOAD.updateAccount(plugin, user, password, options=options)
File "~/private/pyload/module/api.py", line 895, in updateAccount
self.core.accountManager.updateAccount(plugin, account, password, options)
File "~/private/pyload/module/utils.py", line 169, in new
return func(*args)
File "~/private/pyload/module/plugins/AccountManager.py", line 153, in updateAccount
updated = p.updateAccounts(user, password, options)
File "~/private/pyload/module/plugins/internal/misc.py", line 228, in new
return fn(*args, **kwargs)
File "~/private/pyload/module/plugins/internal/Account.py", line 329, in updateAccounts
u['plugin'].relogin()
File "~/private/pyload/module/plugins/internal/Account.py", line 173, in relogin
return self.login()
File "~/private/pyload/module/plugins/internal/Account.py", line 114, in login
self.info['data'])
File "~/private/pyload/module/plugins/accounts/Keep2ShareCc.py", line 78, in signin
re_captcha_response, _ = self.captcha.challenge(self.RECAPTCHA_KEY, version="2js", secure_token=False)
File "~/private/pyload/module/plugins/captcha/ReCaptcha.py", line 149, in challenge
return getattr(self, "_challenge_v%s" % version)(key, secure_token=secure_token)
File "~/private/pyload/module/plugins/captcha/ReCaptcha.py", line 345, in _challenge_v2js
result = self.decrypt_interactive(params, timeout=300)
File "~/private/pyload/module/plugins/internal/Captcha.py", line 159, in decrypt_interactive
self.pyfile.plugin.retry_captcha(msg=_("No captcha result obtained in appropriate timing (%ss)") % timeout)
File "~/private/pyload/module/plugins/accounts/Keep2ShareCc.py", line 172, in retry_captcha
self.fail_login(msg=_("Invalid captcha"))
File "~/private/pyload/module/plugins/internal/Account.py", line 441, in fail_login
return self.fail(msg)
File "~/private/pyload/module/plugins/internal/Plugin.py", line 191, in fail
raise Fail(decode(msg)) # @TODO: Remove `decode` in 0.4.10
```

### Additional references
pyLoad version 0.4.20, plugin version 0.17

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
> so I am never able to successfully add the account;

You have two options:

1. Use captcha9kw plugin to automatically solve captchas
2. Click with the mouse outside of the "add account" dialog so it disappears and then you can click on the captcha button.

**Comment by Mike-EE** [comment]
I have a similar, or the same issue:

```
06.09.2020 19:13:56	INFO	Starting pyLoad 0.4.20
2	06.09.2020 19:13:56	INFO	Using home directory: /home/seedit4me/.pyload
3	06.09.2020 19:13:57	INFO	Activated plugins: ClickNLoad, EventMapper, ExternalScripts, TORRENT, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
4	06.09.2020 19:13:57	INFO	Deactivate plugins: AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
5	06.09.2020 19:13:57	INFO	Downloadtime: True
6	06.09.2020 19:13:57	INFO	Starting ThriftBackend: 0.0.0.0:7227
7	06.09.2020 19:13:57	INFO	Free space: 2.04 TiB
8	06.09.2020 19:13:57	INFO	Activating Accounts...
9	06.09.2020 19:13:57	INFO	Activating Plugins...
10	06.09.2020 19:13:57	WARNING	ADDON TORRENT: torrents / magnets are not associated with any plugin
11	06.09.2020 19:13:57	INFO	Starting builtin webserver: 127.0.0.1:8712
12	06.09.2020 19:13:58	INFO	ADDON UpdateManager: pyLoad is up to date!
13	06.09.2020 19:13:58	INFO	ADDON UpdateManager: Removed blacklisted plugin: ACCOUNTS GetTwentyFourOrg
14	06.09.2020 19:13:58	INFO	ADDON UpdateManager: Removed blacklisted plugin: HOSTER GetTwentyFourOrg
15	06.09.2020 19:13:58	INFO	ADDON UpdateManager: All plugins are up to date!
16	06.09.2020 19:13:58	ERROR	Error importing GetTwentyFourOrg: No module named GetTwentyFourOrg
17	06.09.2020 19:13:58	INFO	ADDON XFileSharing: Auto-discover new hosters
18	06.09.2020 19:13:58	INFO	ADDON XFileSharing: Auto-discover new crypters
19	06.09.2020 19:13:58	INFO	pyLoad is up and running
20	06.09.2020 19:14:04	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
21	06.09.2020 19:17:39	INFO	ACCOUNT Keep2ShareCc: Adding user `ams*******`...
22	06.09.2020 19:17:39	INFO	ACCOUNT Keep2ShareCc: Login user `ams*******`...
23	06.09.2020 19:22:39	WARNING	CAPTCHA Keep2ShareCc: ReCaptcha | Invalid captcha
24	06.09.2020 19:22:39	ERROR	ACCOUNT Keep2ShareCc: Could not login user `ams*******` | Invalid captcha
25	06.09.2020 19:23:26	INFO	ACCOUNT Keep2ShareCc: Removing user `ams*******`...
26	06.09.2020 19:23:58	INFO	ACCOUNT Keep2ShareCc: Adding user `ams*******`...
27	06.09.2020 19:23:58	INFO	ACCOUNT Keep2ShareCc: Relogin user `ams*******`...
28	06.09.2020 19:28:59	WARNING	CAPTCHA Keep2ShareCc: ReCaptcha | Invalid captcha
29	06.09.2020 19:28:59	ERROR	ACCOUNT Keep2ShareCc: Could not login user `ams*******` | Invalid captcha
30	06.09.2020 19:30:39	INFO	ACCOUNT Keep2ShareCc: Updating account info for user `ams*******`...
31	06.09.2020 19:35:01	INFO	ACCOUNT Keep2ShareCc: Updating account info for user `ams*******`...
32	06.09.2020 19:39:00	INFO	Added package Lena Reif - Xxxx - Anal Role Play at the Lake 09.04.20 containing 1 links
33	06.09.2020 19:39:01	INFO	Download starts: https://keep2share.cc/file/e7f3927a917f2
34	06.09.2020 19:39:01	WARNING	HOSTER Keep2ShareCc[1]: Plugin may be unstable
35	06.09.2020 19:39:01	WARNING	Download failed: https://keep2share.cc/file/e7f3927a917f2 | 'NoneType' object has no attribute 'get_info'
36	06.09.2020 19:39:01	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: https://keep2share.cc/file/e7f3927a917f2 (pid:1)
37	06.09.2020 19:39:01	INFO	ADDON UnSkipOnFail: No duplicates found
38	06.09.2020 19:54:41	INFO	Starting pyLoad 0.4.20
39	06.09.2020 19:54:41	INFO	Using home directory: /home/seedit4me/.pyload
40	06.09.2020 19:54:43	INFO	Activated plugins: ClickNLoad, EventMapper, ExternalScripts, TORRENT, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
41	06.09.2020 19:54:43	INFO	Deactivate plugins: AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
42	06.09.2020 19:54:43	INFO	Downloadtime: True
43	06.09.2020 19:54:43	INFO	Starting ThriftBackend: 0.0.0.0:7227
44	06.09.2020 19:54:43	INFO	Free space: 2.04 TiB
45	06.09.2020 19:54:43	INFO	Activating Accounts...
46	06.09.2020 19:54:44	INFO	Starting builtin webserver: 127.0.0.1:8712
47	06.09.2020 19:54:44	INFO	ACCOUNT Keep2ShareCc: Adding user `ams*******`...
48	06.09.2020 19:54:44	INFO	ACCOUNT Keep2ShareCc: Login user `ams*******`...
49	06.09.2020 19:54:44	WARNING	CAPTCHA Keep2ShareCc: ReCaptcha | No Client connected for captcha decrypting
50	06.09.2020 19:54:44	ERROR	ACCOUNT Keep2ShareCc: Could not login user `ams*******` | No Client connected for captcha decrypting
51	06.09.2020 19:54:44	INFO	Activating Plugins...
52	06.09.2020 19:54:44	WARNING	ADDON TORRENT: torrents / magnets are not associated with any plugin
53	06.09.2020 19:54:44	INFO	ADDON UpdateManager: pyLoad is up to date!
54	06.09.2020 19:54:44	INFO	ADDON UpdateManager: All plugins are up to date!
55	06.09.2020 19:54:45	INFO	ADDON XFileSharing: Auto-discover new hosters
56	06.09.2020 19:54:45	INFO	ADDON XFileSharing: Auto-discover new crypters
57	06.09.2020 19:54:45	INFO	pyLoad is up and running
58	06.09.2020 19:54:51	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
59	06.09.2020 19:55:23	INFO	ACCOUNT Keep2ShareCc: Updating account info for user `ams*******`...
60	06.09.2020 19:55:23	INFO	ACCOUNT Keep2ShareCc: Relogin user `ams*******`...
61	06.09.2020 20:00:24	WARNING	CAPTCHA Keep2ShareCc: ReCaptcha | Invalid captcha
62	06.09.2020 20:00:24	ERROR	ACCOUNT Keep2ShareCc: Could not login user `ams*******` | Invalid captcha
```

I unlike the OP never see the captcha entry form. Is there anything I can do, aside from using a 3rd-party captcha resolving service?

Thanks!

**Comment by GammaC0de** [comment]
Click with the mouse outside of the "add account" dialog so it disappears and then you can click on the captcha button.

**Comment by Mike-EE** [comment]
> Click with the mouse outside of the "add account" dialog so it disappears and then you can click on the captcha button.

Thanks for the response, but I I've tried to that in several different browsers (FF and Chrome on Win10-64) and I never see the captcha dialog. Are there any additional diagnostic steps that I can take?

**Comment by c62624** [comment]
I'm having the same issue
