### ISSUE TITLE
Failed to start pyload git master version on Ubuntu 20.04 with pyton 3.8.3.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyload/pyload#3658]
Hi,

This is Ubuntu 20.04 with Python 3.8.3. I try to use pyload git master version but fail to start it. See the following for more info:

```
$ pyload 
[2020-05-30 21:01:56]  WARNING             pyload  *** Welcome to pyLoad 0.5.0 ***
[2020-05-30 21:01:56]  DEBUG               pyload  Indexing plugins...
[2020-05-30 21:01:56]  WARNING             pyload  Failed activating UnSkipOnFail
Traceback (most recent call last):
  File "/home/werner/pyload.git/src/pyload/core/managers/addon_manager.py", line 110, in create_index
    plugin_class = self.pyload.plugin_manager.load_class(
  File "/home/werner/pyload.git/src/pyload/core/managers/plugin_manager.py", line 360, in load_class
    module = self.load_module(type, name)
  File "/home/werner/pyload.git/src/pyload/core/managers/plugin_manager.py", line 403, in load_module
    base, plugin = newname.rsplit(".", 1)
ValueError: not enough values to unpack (expected 2, got 1)
[2020-05-30 21:01:56]  WARNING             pyload  Failed activating ExternalScripts
Traceback (most recent call last):
  File "/home/werner/pyload.git/src/pyload/core/managers/addon_manager.py", line 110, in create_index
    plugin_class = self.pyload.plugin_manager.load_class(
  File "/home/werner/pyload.git/src/pyload/core/managers/plugin_manager.py", line 360, in load_class
    module = self.load_module(type, name)
  File "/home/werner/pyload.git/src/pyload/core/managers/plugin_manager.py", line 403, in load_module
    base, plugin = newname.rsplit(".", 1)
ValueError: not enough values to unpack (expected 2, got 1)
[2020-05-30 21:01:56]  WARNING             pyload  Failed activating ClickNLoad
Traceback (most recent call last):
  File "/home/werner/pyload.git/src/pyload/core/managers/addon_manager.py", line 110, in create_index
    plugin_class = self.pyload.plugin_manager.load_class(
  File "/home/werner/pyload.git/src/pyload/core/managers/plugin_manager.py", line 360, in load_class
    module = self.load_module(type, name)
  File "/home/werner/pyload.git/src/pyload/core/managers/plugin_manager.py", line 403, in load_module
    base, plugin = newname.rsplit(".", 1)
ValueError: not enough values to unpack (expected 2, got 1)
[2020-05-30 21:01:56]  WARNING             pyload  Failed activating UserAgentSwitcher
Traceback (most recent call last):
  File "/home/werner/pyload.git/src/pyload/core/managers/addon_manager.py", line 110, in create_index
    plugin_class = self.pyload.plugin_manager.load_class(
  File "/home/werner/pyload.git/src/pyload/core/managers/plugin_manager.py", line 360, in load_class
    module = self.load_module(type, name)
  File "/home/werner/pyload.git/src/pyload/core/managers/plugin_manager.py", line 403, in load_module
    base, plugin = newname.rsplit(".", 1)
ValueError: not enough values to unpack (expected 2, got 1)
[2020-05-30 21:01:56]  WARNING             pyload  Failed activating XFileSharing
Traceback (most recent call last):
  File "/home/werner/pyload.git/src/pyload/core/managers/addon_manager.py", line 110, in create_index
    plugin_class = self.pyload.plugin_manager.load_class(
  File "/home/werner/pyload.git/src/pyload/core/managers/plugin_manager.py", line 360, in load_class
    module = self.load_module(type, name)
  File "/home/werner/pyload.git/src/pyload/core/managers/plugin_manager.py", line 403, in load_module
    base, plugin = newname.rsplit(".", 1)
ValueError: not enough values to unpack (expected 2, got 1)
[2020-05-30 21:01:56]  WARNING             pyload  Failed activating EventMapper
Traceback (most recent call last):
  File "/home/werner/pyload.git/src/pyload/core/managers/addon_manager.py", line 110, in create_index
    plugin_class = self.pyload.plugin_manager.load_class(
  File "/home/werner/pyload.git/src/pyload/core/managers/plugin_manager.py", line 360, in load_class
    module = self.load_module(type, name)
  File "/home/werner/pyload.git/src/pyload/core/managers/plugin_manager.py", line 403, in load_module
    base, plugin = newname.rsplit(".", 1)
ValueError: not enough values to unpack (expected 2, got 1)
[2020-05-30 21:01:56]  INFO                pyload  Activated plugins: 
[2020-05-30 21:01:56]  INFO                pyload  Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, UpdateManager, WindowsPhoneNotify, XMPP
ImportError: cannot import name 'cached_property' from 'werkzeug' (/home/werner/.pyenv/versions/3.8.3/envs/pyload/lib/python3.8/site-packages/werkzeug/__init__.py)
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/pyload/bin/pyload", line 11, in <module>
    load_entry_point('pyload-ng', 'console_scripts', 'pyload')()
  File "/home/werner/pyload.git/src/pyload/script.py", line 124, in main
    run(core_args, args.daemon)
  File "/home/werner/pyload.git/src/pyload/script.py", line 108, in run
    pyload_core = Core(*core_args)
  File "/home/werner/pyload.git/src/pyload/core/__init__.py", line 98, in __init__
    self._init_webserver()
  File "/home/werner/pyload.git/src/pyload/core/__init__.py", line 154, in _init_webserver
    from pyload.webui.webserver_thread import WebServerThread
  File "/home/werner/pyload.git/src/pyload/webui/webserver_thread.py", line 10, in <module>
    from .app import App
  File "/home/werner/pyload.git/src/pyload/webui/app/__init__.py", line 16, in <module>
    from .blueprints import BLUEPRINTS
  File "/home/werner/pyload.git/src/pyload/webui/app/blueprints/__init__.py", line 11, in <module>
    from .app_blueprint import bp as app_bp
  File "/home/werner/pyload.git/src/pyload/webui/app/blueprints/app_blueprint.py", line 18, in <module>
    from ..helpers import (
  File "/home/werner/pyload.git/src/pyload/webui/app/helpers.py", line 8, in <module>
    import flask_themes2
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyload/lib/python3.8/site-packages/flask_themes2/__init__.py", line 36, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (/home/werner/.pyenv/versions/3.8.3/envs/pyload/lib/python3.8/site-packages/werkzeug/__init__.py)

```

Any hints for this problem?

Regards

**Comment by treysis** [comment]
It's not really ready for use. Stick to 0.4.20 for now.

**Comment by Tockra** [comment]
I can recommend to use docker. With docker the crappy pyload installation and maintain is very easy. And you don't has the whole python trash on your system after that...

**Comment by vuolter** [comment]
It should work now.
