### ISSUE TITLE
multishare.cz plugin seems to be broken

### ISSUE THREAD

**Issue by ei-ke** [pyload/pyload#3671]
### Describe the problem

My MultiShare.cz account works fine with JD2 but as it seems the pyLoad plugin is broken.
If needed I'll let you use my account to fix it.

### Debug log

```
14.06.2020 17:17:42	INFO	ACCOUNT MultishareCz: Adding user `XX*******`...
828	14.06.2020 17:17:42	DEBUG	ACCOUNT MultishareCz: Reached login timeout for user `XX*******`
829	14.06.2020 17:17:42	INFO	ACCOUNT MultishareCz: Login user `XX*******`...
830	14.06.2020 17:17:42	DEBUG	ACCOUNT MultishareCz: LOAD URL https://www.multishare.cz/html/prihlaseni_process.php | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'akce': 'P\xc5\x99ihl\xc3\xa1sit', 'heslo': '**********', 'jmeno': 'XX*******'} | ref=True | just_header=False
831	14.06.2020 17:17:43	INFO	ACCOUNT MultishareCz: Grabbing account info for user `XX*******`...
832	14.06.2020 17:17:43	DEBUG	ACCOUNT MultishareCz: LOAD URL http://www.multishare.cz/profil/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
833	14.06.2020 17:17:44	DEBUG	ACCOUNT MultishareCz: LOAD URL http://www.multishare.cz/monitoring/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
834	14.06.2020 17:17:44	WARNING	ACCOUNT MultishareCz: Error loading hoster list for user `XX*******` | cannot invoke setopt() - perform() is currently running
835	?	?	Traceback (most recent call last):
836	?	?	File "/opt/pyLoad/module/Scheduler.py", line 101, in run
837	?	?	ret = self.call(*self.args, **self.kwargs)
838	?	?	File "/opt/pyLoad/config/userplugins/internal/misc.py", line 179, in _task
839	?	?	self.task()
840	?	?	File "/opt/pyLoad/module/plugins/internal/MultiAccount.py", line 86, in periodical_task
841	?	?	self.reactivate(refresh=True)
842	?	?	File "/opt/pyLoad/module/plugins/internal/MultiAccount.py", line 317, in reactivate
843	?	?	if not self.get_plugins(cached=False):
844	?	?	File "/opt/pyLoad/module/plugins/internal/MultiAccount.py", line 211, in get_plugins
845	?	?	plugin_set = set(self._grab_hosters())
846	?	?	File "/opt/pyLoad/module/plugins/internal/MultiAccount.py", line 111, in _grab_hosters
847	?	?	self.info['data'])
848	?	?	File "/opt/pyLoad/module/plugins/accounts/MultishareCz.py", line 28, in grab_hosters
849	?	?	html = self.load("http://www.multishare.cz/monitoring/")
850	?	?	File "/opt/pyLoad/config/userplugins/internal/Plugin.py", line 248, in load
851	?	?	decode is True) # @TODO: Fix network multipart in 0.4.10
852	?	?	File "/opt/pyLoad/module/network/Browser.py", line 98, in load
853	?	?	return self.http.load(*args, **kwargs)
854	?	?	File "/opt/pyLoad/module/network/HTTPRequest.py", line 207, in load
855	?	?	self.setRequestContext(url, get, post, referer, cookies, multipart)
856	?	?	File "/opt/pyLoad/module/network/HTTPRequest.py", line 175, in setRequestContext
857	?	?	self.c.setopt(pycurl.URL, url)
858	?	?	error: cannot invoke setopt() - perform() is currently running
859	?	?	
860	14.06.2020 17:17:44	DEBUG	ACCOUNT MultishareCz: Hoster list for user `XX*******`: []
861	14.06.2020 17:17:44	ERROR	ACCOUNT MultishareCz: Failed to load hoster list for user `XX*******`, retry in 5 minutes
862	?	?	Traceback (most recent call last):
863	?	?	File "/opt/pyLoad/module/Scheduler.py", line 101, in run
864	?	?	ret = self.call(*self.args, **self.kwargs)
865	?	?	File "/opt/pyLoad/config/userplugins/internal/misc.py", line 179, in _task
866	?	?	self.task()
867	?	?	File "/opt/pyLoad/module/plugins/internal/MultiAccount.py", line 86, in periodical_task
868	?	?	self.reactivate(refresh=True)
869	?	?	File "/opt/pyLoad/module/plugins/internal/MultiAccount.py", line 320, in reactivate
870	?	?	self.log_error(_("Failed to load hoster list for user `%s`, retry in 5 minutes") % self.user)
871	?	?	
872	14.06.2020 17:17:46	WARNING	ACCOUNT MultishareCz: Error loading info for user `XX*******` | can't set attribute
873	14.06.2020 17:17:46	DEBUG	ACCOUNT MultishareCz: Account info for user `XX*******`: {'login': {'timestamp': 1592147862.415962, 'password': '**********', 'valid': True}, 'data': {'hosters': [], 'premium': None, 'plugin': , 'trafficleft': None, 'maxtraffic': None, 'validuntil': None, 'login': 'XX*******', 'type': 'MultishareCz', 'options': {'limitDL': ['0']}}}
```

### System Info
```
Python: 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]

System: posix linux2 Linux XXX 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64

pyLoad Version: 0.4.20
```

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by ei-ke** [comment]
Mail is in it's way. Thanks in advance.
