### ISSUE TITLE
MagaCoNzFolder issue

### ISSUE THREAD

**Issue by unbrokenzero** [pyload/pyload#3716]
### Describe the plugin

MegaCoNzFolder plugin doesn't work with all folder links.  I have attached the debug log, which includes the link that's failing.

### Sample resources

```
pyLoad 0.4.20 Debug Report of MegaCoNzFolder 0.22

TRACEBACK:
 Traceback (most recent call last):
  File "/app/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/app/pyload/module/plugins/internal/Base.py", line 291, in preprocessing
    return self._process(*args, **kwargs)
  File "/app/pyload/module/plugins/internal/Base.py", line 281, in _process
    self.process(self.pyfile)
  File "/app/pyload/module/plugins/internal/Crypter.py", line 32, in process
    self.decrypt(pyfile)
  File "/app/pyload/module/plugins/crypter/MegaCoNzFolder.py", line 37, in decrypt
    res = mega.api_response(a="f", c=1, r=1, ca=1, ssl=1)
  File "/app/pyload/module/plugins/hoster/MegaCoNz.py", line 231, in api_response
    post=json.dumps([kwargs]))
  File "/app/pyload/module/plugins/internal/Base.py", line 487, in load
    return Plugin.load(self, *args, **kwargs)
  File "/app/pyload/module/plugins/internal/Plugin.py", line 248, in load
    decode is True)
  File "/app/pyload/module/network/Browser.py", line 98, in load
    return self.http.load(*args, **kwargs)
  File "/app/pyload/module/network/HTTPRequest.py", line 256, in load
    self.c.perform()
error: (23, 'Failed writing body (0 != 1372)')

FRAMESTACK:

Frame preprocessing in /app/pyload/module/plugins/internal/Base.py at line 291
	                self = <Crypter MegaCoNzFolder>
	                args = (<DecrypterThread(Thread-10, started daemon 23391189191456)>,)
	              kwargs = {}

Frame _process in /app/pyload/module/plugins/internal/Base.py at line 281
	                self = <Crypter MegaCoNzFolder>
	              thread = <DecrypterThread(Thread-10, started daemon 23391189191456)>

Frame process in /app/pyload/module/plugins/internal/Crypter.py at line 32
	              pyfile = PyFile 9120: 7bg3VYyC@MegaCoNzFolder
	                self = <Crypter MegaCoNzFolder>

Frame decrypt in /app/pyload/module/plugins/crypter/MegaCoNzFolder.py at line 37
	              pyfile = PyFile 9120: 7bg3VYyC@MegaCoNzFolder
	                self = <Crypter MegaCoNzFolder>
	          master_key = (66119413, 1127738421, 2439585385, 1531660648)
	                  id = u'7bg3VYyC'
	                mega = <module.plugins.hoster.MegaCoNz.MegaClient object at 0x15462fabcbd0>

Frame api_response in /app/pyload/module/plugins/hoster/MegaCoNz.py at line 237
	                self = <module.plugins.hoster.MegaCoNz.MegaClient object at 0x15462fabcbd0>
	              kwargs = {'a': 'f', 'c': 1, 'ca': 1, 'r': 1, 'ssl': 1}
	                 uid = 41353007
	     mega_session_id = None
	          get_params = {'id': 41353007, 'n': u'7bg3VYyC'}

Frame load in /app/pyload/module/plugins/internal/Base.py at line 487
	                self = <Crypter MegaCoNzFolder>
	                args = ('https://eu.api.mega.co.nz/cs',)
	              kwargs = {'get': {'id': 41353007, 'n': u'7bg3VYyC'},
 'post': '[{"a": "f", "ssl": 1, "c": 1, "r": 1, "ca": 1}]'}

Frame load in /app/pyload/module/plugins/internal/Plugin.py at line 248
	            redirect = True
	            http_req = <module.network.HTTPRequest.HTTPRequest instance at 0x15462fa8e230>
	             cookies = True
	                 get = {'id': 41353007, 'n': u'7bg3VYyC'}
	                 url = u'https://eu.api.mega.co.nz/cs'
	                self = <Crypter MegaCoNzFolder>
	                 req = <module.network.Browser.Browser object at 0x15462fa8ca60>
	               value = False
	              decode = True
	           multipart = False
	                 key = 'just_header'
	                post = '[{"a": "f", "ssl": 1, "c": 1, "r": 1, "ca": 1}]'
	                 ref = True
	         just_header = False

Frame load in /app/pyload/module/network/Browser.py at line 98
	                self = <module.network.Browser.Browser object at 0x15462fa8ca60>
	                args = (u'https://eu.api.mega.co.nz/cs',
 {'id': 41353007, 'n': u'7bg3VYyC'},
 '[{"a": "f", "ssl": 1, "c": 1, "r": 1, "ca": 1}]',
 True,
 True,
 False,
 False,
 True)
	              kwargs = {}

Frame load in /app/pyload/module/network/HTTPRequest.py at line 261
	             cookies = True
	                   e = error(23, 'Failed writing body (0 != 1372)')
	                 get = {'id': 41353007, 'n': u'7bg3VYyC'}
	                 url = u'https://eu.api.mega.co.nz/cs'
	                self = <module.network.HTTPRequest.HTTPRequest instance at 0x15462fa8e230>
	              decode = True
	             referer = True
	           multipart = False
	                post = '[{"a": "f", "ssl": 1, "c": 1, "r": 1, "ca": 1}]'
	         just_header = False

PLUGIN OBJECT DUMP: 

	    URL_REPLACEMENTS = []
	             account = False
	             captcha = <Captcha Captcha>
	           classname = 'MegaCoNzFolder'
	              config = <module.plugins.internal.misc.Config object at 0x15462fabcf90>
	                data = ''
	                  db = <module.plugins.internal.misc.DB object at 0x15462fabcad0>
	                info = {'hash': {},
 'name': u'7bg3VYyC',
 'pattern': {'ID': u'7bg3VYyC', 'KEY': u'A_Dm9UM37DWRaR5pW0tJaA'},
 'size': 0,
 'status': 7,
 'url': u'https://mega.nz/folder/7bg3VYyC#A_Dm9UM37DWRaR5pW0tJaA'}
	                  js = <module.common.JsEngine.JsEngine instance at 0x154630459aa0>
	         last_header = {}
	           last_html = ''
	               links = []
	             multiDL = True
	            packages = []
	             premium = False
	              pyfile = PyFile 9120: 7bg3VYyC@MegaCoNzFolder
	              pyload = <__main__.Core object at 0x1546309e6c90>
	                 req = <module.network.Browser.Browser object at 0x15462fa8ca60>
	             retries = {}
	              thread = <DecrypterThread(Thread-10, started daemon 23391189191456)>
	                user = None
	             waiting = False
	       wantReconnect = False

PYFILE OBJECT DUMP: 

	               _size = 0
	               abort = False
	              active = False
	               error = "(23, 'Failed writing body (0 != 1372)')"
	                  id = 9120
	                lock = <_RLock owner=None count=0>
	                   m = <module.database.FileDatabase.FileHandler instance at 0x1546309ea230>
	         maxprogress = 100
	                name = u'7bg3VYyC'
	               order = 0
	           packageid = 712
	              plugin = <Crypter MegaCoNzFolder>
	         pluginclass = <class 'module.plugins.crypter.MegaCoNzFolder.MegaCoNzFolder'>
	        pluginmodule = <module 'module.plugins.crypter.MegaCoNzFolder' from '/app/pyload/module/plugins/crypter/MegaCoNzFolder.py'>
	          pluginname = u'MegaCoNzFolder'
	            progress = 0
	         reconnected = False
	                size = 0
	              status = 8
	          statusname = None
	                 url = u'https://mega.nz/folder/7bg3VYyC#A_Dm9UM37DWRaR5pW0tJaA'
	           waitUntil = 0

CONFIG: 

{'activated': {'desc': 'Activated', 'type': 'bool', 'value': True},
 'desc': 'MegaCoNzFolder',
 'folder_per_package': {'desc': 'Create folder for each package',
                        'type': 'Default;Yes;No',
                        'value': 'Default'},
 'outline': 'Mega.co.nz folder decrypter plugin',
 'use_premium': {'desc': 'Use premium account if available',
                 'type': 'bool',
                 'value': True}}
```

**Comment by GammaC0de** [comment]
This mega folder has insane  value of 37929 files...

This explains the cause of this issue...
