### ISSUE TITLE
[Main] NameError: name 'parse_name' is not defined on adding a package

### ISSUE THREAD

**Issue by OzzieIsaacs** [pyload/pyload#3723]
I tried to catch up from @vuolter s suggestion to cntribute to the new main version. Currently I find it difficult, as I don't know what is valid code, and which code is planned to be refactored, so I will try to test pyload NG and write some issues

### Description
Start the application
Go to website
Click to add new package
Enter new package (e.g.https://filer.net/get/wlpwjckcyp1glsnp)
Traceback is shown in log

### Debug log
```
[2020-09-13 06:06:04]  INFO                pyload  Download starts: /home/ozzie/Downloads/pyLoad/tmp_
[2020-09-13 06:06:04]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `download_preparing`
[2020-09-13 06:06:04]  DEBUG               pyload  ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
[2020-09-13 06:06:04]  DEBUG               pyload  ADDON UserAgentSwitcher: Setting maximum redirections to 10
[2020-09-13 06:06:04]  DEBUG               pyload  ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
[2020-09-13 06:06:04]  DEBUG               pyload  DOWNLOADER DefaultPlugin[3]: Plugin version: 0.52
[2020-09-13 06:06:04]  DEBUG               pyload  DOWNLOADER DefaultPlugin[3]: Plugin status: testing
[2020-09-13 06:06:04]  WARNING             pyload  DOWNLOADER DefaultPlugin[3]: Plugin may be unstable
[2020-09-13 06:06:04]  DEBUG               pyload  DOWNLOADER DefaultPlugin[3]: Config option `use_premium` not found, use default `True`
[2020-09-13 06:06:04]  INFO                pyload  DOWNLOADER DefaultPlugin[3]: Grabbing link info...
[2020-09-13 06:06:04]  DEBUG               pyload  DOWNLOADER DefaultPlugin[3]: Link info: {'name': 'tmp_', 'hash': {}, 'pattern': {}, 'size': 0, 'status': 7, 'url': '/home/ozzie/Downloads/pyLoad/tmp_'}
[2020-09-13 06:06:04]  DEBUG               pyload  DOWNLOADER DefaultPlugin[3]: Previous link info: {}
[2020-09-13 06:06:04]  INFO                pyload  DOWNLOADER DefaultPlugin[3]: Link name: tmp_
[2020-09-13 06:06:04]  INFO                pyload  DOWNLOADER DefaultPlugin[3]: Link size: N/D
[2020-09-13 06:06:04]  INFO                pyload  DOWNLOADER DefaultPlugin[3]: Link status: starting
[2020-09-13 06:06:04]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `download_processed`
[2020-09-13 06:06:04]  WARNING             pyload  Download failed: tmp_ | No plugin matched
[2020-09-13 06:06:04]  INFO                pyload  ADDON UnSkipOnFail: Looking for skipped duplicates of: tmp_ (pid:2)
[2020-09-13 06:06:04]  INFO                pyload  ADDON UnSkipOnFail: No duplicates found
[2020-09-13 06:06:04]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `download_failed`
[2020-09-13 06:06:05]  INFO                pyload  Download starts: https://filer.net/get/wlpwjckcyp1glsnp
[2020-09-13 06:06:05]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `download_preparing`
[2020-09-13 06:06:05]  DEBUG               pyload  ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
[2020-09-13 06:06:05]  DEBUG               pyload  ADDON UserAgentSwitcher: Setting maximum redirections to 10
[2020-09-13 06:06:05]  DEBUG               pyload  ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
[2020-09-13 06:06:05]  DEBUG               pyload  DOWNLOADER FilerNet[4]: Plugin version: 0.28
[2020-09-13 06:06:05]  DEBUG               pyload  DOWNLOADER FilerNet[4]: Plugin status: testing
[2020-09-13 06:06:05]  WARNING             pyload  DOWNLOADER FilerNet[4]: Plugin may be unstable
[2020-09-13 06:06:05]  INFO                pyload  DOWNLOADER FilerNet[4]: Grabbing link info...
[2020-09-13 06:06:05]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `download_processed`
[2020-09-13 06:06:05]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `package_processed`
[2020-09-13 06:06:05]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `package_failed`
Traceback (most recent call last):
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/core/threads/download_thread.py", line 56, in run
    pyfile.plugin.preprocessing(self)
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/plugins/base/hoster.py", line 304, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/plugins/base/downloader.py", line 90, in _process
    self._setup()
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/plugins/base/hoster.py", line 175, in _setup
    self.grab_info()
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/plugins/base/hoster.py", line 236, in grab_info
    new_info = self.get_info(self.pyfile.url, self.data)
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/plugins/base/simple_downloader.py", line 197, in get_info
    info["name"] = parse_name(name)
NameError: name 'parse_name' is not defined
[2020-09-13 06:06:05]  WARNING             pyload  Download failed: https://filer.net/get/wlpwjckcyp1glsnp | name 'parse_name' is not defined
Traceback (most recent call last):
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/core/threads/download_thread.py", line 56, in run
    pyfile.plugin.preprocessing(self)
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/plugins/base/hoster.py", line 304, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/plugins/base/downloader.py", line 90, in _process
    self._setup()
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/plugins/base/hoster.py", line 175, in _setup
    self.grab_info()
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/plugins/base/hoster.py", line 236, in grab_info
    new_info = self.get_info(self.pyfile.url, self.data)
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/plugins/base/simple_downloader.py", line 197, in get_info
    info["name"] = parse_name(name)
NameError: name 'parse_name' is not defined
[2020-09-13 06:06:05]  DEBUG               pyload  Error creating zip file: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/tmp/pyLoad/FilerNet'
[2020-09-13 06:06:05]  INFO                pyload  Debug Report written to /tmp/pyLoad/debug_FilerNet_2020-09-13_06-06-05.txt
[2020-09-13 06:06:05]  INFO                pyload  ADDON UnSkipOnFail: Looking for skipped duplicates of: https://filer.net/get/wlpwjckcyp1glsnp (pid:2)
[2020-09-13 06:06:05]  INFO                pyload  ADDON UnSkipOnFail: No duplicates found
[2020-09-13 06:06:05]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `download_failed`
[2020-09-13 06:06:05]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `all_downloads_processed`
[2020-09-13 06:06:05]  DEBUG               pyload  All downloads processed
```

### Additional references
I tried both, the current main and also the current development branch

### Screenshots
![grafik](https://user-images.githubusercontent.com/6438895/93010152-8fcb2000-f589-11ea-92cf-24ddea5a2129.png)

**Comment by OzzieIsaacs** [comment]
Solved by lated commit
