### ISSUE TITLE
[Main] ClicknLoad isn't working

### ISSUE THREAD

**Issue by OzzieIsaacs** [pyload/pyload#3724]
### Description
Adding links via clicknLoad isn't working in pyload NG. After starting the transfer (by clicking on the Cick and load Button on the sending website, the sending website returns with an "error connection is lost". In pyload nothing happens on the website except the traceback in the log. I tried main and development branch.
Click and Load plugin is activated

### Debug log
```
[2020-09-13 06:26:44]  DEBUG               pyload  ADDON ClickNLoad: Connection from 127.0.0.1:41794
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/core/threads/addon_thread.py", line 50, in run
    self.f(*self.args, **self.kwargs)
TypeError: _server() got an unexpected keyword argument 'thread'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/core/threads/addon_thread.py", line 57, in run
    self.f(*self.args, **self.kwargs)
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/plugins/addons/ClickNLoad.py", line 136, in _server
    if self.pyload.config.get("webui", "https"):
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/core/config/parser.py", line 312, in get
    return self.config[section][option]["value"]
KeyError: 'https'
127.0.0.1 - - [13/Sep/2020 06:26:44] "POST /json/status HTTP/1.1" 200 -
127.0.0.1 - - [13/Sep/2020 06:26:48] "POST /json/status HTTP/1.1" 200 -
[2020-09-13 06:26:49]  INFO          pyload.webui  Locating template "_themes/pyplex/logs.html":
    1: trying loader of application "pyload.webui.app"
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - /home/ozzie/.local/lib/python3.8/site-packages/pyload/webui/app/templates
       -> no match
    2: trying loader of blueprint "_themes" (flask_themes2)
       class: flask_themes2.ThemeTemplateLoader
       as_blueprint: True
       -> found ('/home/ozzie/.local/lib/python3.8/site-packages/pyload/webui/app/themes/pyplex/templates/logs.html')
```
### Screenshots

![grafik](https://user-images.githubusercontent.com/6438895/93010277-0d436000-f58b-11ea-8b26-6f23db0de03a.png)

**Comment by Bava1980** [comment]
I recognised some strange behavior with CNL too. But it was all dedicated to my Firefow + uBlock + probably other plugins. Using a private window on firefox the CNL worked like a charm.

**Comment by OzzieIsaacs** [comment]
Just to make sure: 
We are talking here about the current development branch (pyload-ng version 0.5) and not the current stable version (pyload 0.4.20).
