### ISSUE TITLE
[Main] Aborting download gives traceback

### ISSUE THREAD

**Issue by OzzieIsaacs** [pyload/pyload#3751]
### Description

After you start a link to download, so it's displayed on the dashboard page (even if only in a waiting state) and you click on abort (the cross on the end of the info line) you get an internal error 500 on the javascript console.

### Debug log
```
[2020-09-20 06:49:22]  INFO                pyload  Download aborted: PC_Games_Extended_Magazin_No_06_Juni_2020.pdf
[2020-09-20 06:49:22]  DEBUG         pyload.webui  500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/webui/app/blueprints/json_blueprint.py", line 116, in abort_link
    api.stop_downloads([id])
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/core/api/__init__.py", line 80, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/core/api/__init__.py", line 886, in stop_downloads
    for pyfile in pyfiles:
RuntimeError: dictionary changed size during iteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/webui/app/helpers.py", line 181, in wrapper
    response = func(*args, **kwargs)
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/webui/app/blueprints/json_blueprint.py", line 119, in abort_link
    flask.abort(500)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

### Additional references
 Tested with Linux Mint 20, python 3.8

### Screenshots

![grafik](https://user-images.githubusercontent.com/6438895/93694599-13e35180-fb0e-11ea-8f0b-c842ad540fb3.png)

![grafik](https://user-images.githubusercontent.com/6438895/93694577-a3d4cb80-fb0d-11ea-8845-3387666a047c.png)

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/1fcea1f07ba746cce19a052e59ac9be872d74556
