### ISSUE TITLE
Entered wrong time-format now I can't access the webinterface

### ISSUE THREAD

**Issue by jfml** [pyload/pyload#3757]
Excuse me if this is not the right place for trouble-shooting but I didn't find anywhere else to ask for help.

Running Pyload 0.4.20 via Docker, I entered a time that isn't formatted correctly (23.59 instead of 23:59) in the start up-time field and now I can't access the webinterface. The log says:

```
ERROR     <<< UNCAUGHT EXCEPTION >>>
Traceback (most recent call last):
  File "/app/pyload/pyLoadCore.py", line 731, in <module>
    main()
  File "/app/pyload/pyLoadCore.py", line 722, in main
    pyload_core.start()
  File "/app/pyload/pyLoadCore.py", line 462, in start
    self.log.info(_("Downloadtime: %s") % self.api.isTimeDownload())
  File "/app/pyload/module/Api.py", line 279, in isTimeDownload
    return compare_time(start, end)
  File "/app/pyload/module/utils.py", line 80, in compare_time
    end = map(int, end)
ValueError: invalid literal for int() with base 10: '23.59'
```

Any ideas how I can fix this? I'd hoped that I could change this in the /config somewhere but I can't find it. Thanks a lot in advance (and sorry for the trouble)!

**Comment by jfml** [comment]
Managed to solve this by editing the pyload.conf while the container was running. Still this might be something that could be looked at/solved, like not being able to enter „.“ (if that's possible) in that field if it has such consequences?
