### ISSUE TITLE
[Plugin Filecrypt] Cutcaptcha link and working and Cutcaptcha missing

### ISSUE THREAD

**Issue by OzzieIsaacs** [pyload/pyload#3804]
### Description

Using a Filecrypt link (like the one I send you for PR #3803 20min ago) causes the plugin to fail with unknown Captcha type. 

Checking the filecrypt.cc plugin code shows that the Cutcaptcha meanwhile is meanwhile https://cutcaptcha.**net** available. Changing the link leads to a traceback. There is indeed no Cutcaptcha in the captcha folder. 
Did you maybe miss it to commit on updating to pyload 4.20?

### Debug log

```
25.10.2020 13:57:38 DEBUG     CRYPTER FilecryptCc[14]: CutCaptcha Captcha URL: https://cutcaptcha.net/captcha/SAs61IAI.js
25.10.2020 13:57:38 ERROR     Decrypting failed: ADF0EB9067.html | global name 'CutCaptcha' is not defined
Traceback (most recent call last):
  File "/home/ozzie/Entwicklung/pyload-web/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/home/ozzie/Entwicklung/pyload-web/module/plugins/internal/Base.py", line 291, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/ozzie/Entwicklung/pyload-web/module/plugins/internal/Base.py", line 281, in _process
    self.process(self.pyfile)
  File "/home/ozzie/Entwicklung/pyload-web/module/plugins/internal/Crypter.py", line 32, in process
    self.decrypt(pyfile)
  File "/home/ozzie/Entwicklung/pyload-web/module/plugins/crypter/FilecryptCc.py", line 100, in decrypt
    self.site_with_links = self.handle_captcha(pyfile.url)
  File "/home/ozzie/Entwicklung/pyload-web/module/plugins/crypter/FilecryptCc.py", line 152, in handle_captcha
    res = handle(submit_url)
  File "/home/ozzie/Entwicklung/pyload-web/module/plugins/crypter/FilecryptCc.py", line 257, in _handle_cutcaptcha_captcha
    cutcaptcha = CutCaptcha(self.pyfile)
NameError: global name 'CutCaptcha' is not defined
25.10.2020 13:57:38 INFO      Debug Report written to debug_FilecryptCc_25-10-2020_13-57-38.zip

```

**Comment by GammaC0de** [comment]
This commit was never intended since the cutcaptca plugin was never finished.

I will make an update to the plugin to remove cutcaptca, making it retry when dealing with cutcaptca

**Comment by snickers2k** [comment]
anything new to this topic? i would even pay a lot for a working solution :) seriously... 
cutcaptcha broke any automated downloads for years now :( it's a pain in the ass :(

**Comment by GammaC0de** [comment]
@snickers2k 
Does it work with JDownloader?
Can you provide a sample URL?

**Comment by thenewcoderintheworld** [comment]
> Does it work with JDownloader?

For a short time but filecrypt has changed the website code and then it was broken.
And retry is no good solution without very good limits in this case if the account owner has only selected cutcaptcha.
