### ISSUE TITLE
pyload-ng fails to start

### ISSUE THREAD

**Issue by Serranya** [pyload/pyload#3848]
### Description

I tried installing pyload-ng on Arch Linux. When trying to launch it errors and fails.

### Debug log

```
[root@serra-zeus ~]# pyload --help
Traceback (most recent call last):
  File "/usr/bin/pyload", line 33, in <module>
    sys.exit(load_entry_point('pyload-ng==0.5.0a5', 'console_scripts', 'pyload')())
  File "/usr/bin/pyload", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/pyload/__init__.py", line 27, in <module>
    PKGDIR = pkg_resources.resource_filename(__name__, None)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1128, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1380, in get_resource_filename
    return self._fn(self.module_path, resource_name)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1471, in _fn
    self._validate_resource_path(resource_name)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1530, in _validate_resource_path
    os.path.pardir in path.split(posixpath.sep) or
AttributeError: 'NoneType' object has no attribute 'split'
```

### Additional references
Here is the install script I used to install pyload-ng. Specifically I used replaced some
dependencies in the setup.cfg which are only available in newer version on Arch Linux.
```
pkgname='pyload-ng'
pkgver='0.5.0a5.dev528'
pkgrel=1
pkgdesc='The free and open-source Download Manager written in pure Python'
arch=('any')
url='https://pyload.net/'
license=('AGPL')
depends=(
        'python'
        'python-cheroot'
        'python-flask'
        'python-flask-babel'
        'python-flask-caching'
        'python-flask-themes2'
        'python-bitmath'
        'python-cryptography'
        'python-filetype'
        'python-js2py'
        'python-pycurl'
        'python-semver'
        'python-requests-html'
        'python-cryptography'
)
makedepends=('python-setuptools')
source=("https://files.pythonhosted.org/packages/source/${pkgname::1}/$pkgname/$pkgname-$pkgver.zip")
sha256sums=('5e08f578296be49014437b3f9a581a3ac564ef69b3c9a020913abcceaa4b54a2')

build() {
        cd "$pkgname-$pkgver"
        sed -i 's/Flask-Babel~=1.0/Flask-Babel~=2.0/g' setup.cfg
        sed -i 's/cryptography~=2.4/cryptography~=3.0/g' setup.cfg
        sed -i 's/Cheroot~=6.5/Cheroot~=8.0/g' setup.cfg
        python setup.py build
}

package() {
        cd "$pkgname-$pkgver"
        python setup.py install --root="$pkgdir" --optimize=1 --skip-build
}
```

**Comment by Serranya** [comment]
This seems to be closely related to https://github.com/pyload/pyload/issues/3412. Hoever the issue says the problem is fixed which is not true for me.

**Comment by GammaC0de** [comment]
Try using python v3.8, 
v3.9 is untested.

**Comment by micwoj92** [comment]
@Serranya I've uploaded https://aur.archlinux.org/packages/pyload-ng/ and it works for me, probably was fixed in some release.

**Comment by GammaC0de** [comment]
👍 Closing then.
