### ISSUE TITLE
"Error when decoding string from b'utf-8'", "pycurl.error: (23, 'Failed writing header')" and other errors when running pyLoad in Debian and firejailed Firefox (sandbox permissions?)

### ISSUE THREAD

**Issue by ihasaquesion** [pyload/pyload#3860]
### Description
I'm trying to run the latest pyLoad in Debian 10 and Firefox sandboxed with [Firejail](https://github.com/netblue30/firejail) and the nftables firewall.

I installed pyLoad like so: `pip install --pre pyload-ng[all]` and run it with `pyload`.

Because I have my firefox sandboxed with firejail I thought that could be the problem for why it has an error accessing /tmp/pyLoad so I opened a new instance of firefox that has access to that directory like so:

`mkdir ~/Downloads/firefoxprofile && firejail --noblacklist=/tmp/pyLoad/ firefox -no-remote -profile ~/Downloads/firefoxprofile`

I tried adding a simple youtube video link for testing to the queue with the Web UI and tried starting it but it doesn't start with no message in the Web UI. The error messages of the console output are below. Does firefox need some additional permissions, like access to specific folders (which?)? Or do I maybe need some other configurations? The firewall should allow connections from/to localhost.

### Debug log

These are the four errors that show in the console output. If the full logs are really needed I could provide them later. But maybe this description and error messages are already enough to find the problems.

```
WARNING             pyload  [Errno 2] No translation file found for domain: 'pyload'
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.6/site-packages/pyload/core/__init__.py", line 242, in _setup_language
    self.set_language(lang)
  File "/home/username/.local/lib/python3.6/site-packages/pyload/core/__init__.py", line 224, in set_language
    self._set_language(self.LOCALE_DOMAIN, localedir, languages)
  File "/home/username/.local/lib/python3.6/site-packages/pyload/core/__init__.py", line 227, in _set_language
    trans = gettext.translation(*args, **kwargs)
  File "/usr/local/lib/python3.6/gettext.py", line 514, in translation
    raise OSError(ENOENT, 'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'pyload'

DEBUG               pyload  Error when decoding string from b'utf-8'
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.6/site-packages/pyload/core/network/http/http_request.py", line 328, in decode_response
    if codecs.lookup(encoding).name == "utf-8" and rep.startswith(
TypeError: lookup() argument must be str, not bytes
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

DEBUG               pyload  Error creating zip file: [Errno 2] No such file or directory: '/tmp/pyLoad/DefaultPlugin'

WARNING             pyload  Download failed: watch?v=id | (23, 'Failed writing header')
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.6/site-packages/pyload/core/threads/download_thread.py", line 56, in run
    pyfile.plugin.preprocessing(self)
  File "/home/username/.local/lib/python3.6/site-packages/pyload/plugins/base/hoster.py", line 304, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/username/.local/lib/python3.6/site-packages/pyload/plugins/base/downloader.py", line 101, in _process
    self.process(self.pyfile)
  File "/home/username/.local/lib/python3.6/site-packages/pyload/plugins/downloaders/Http.py", line 34, in process
    self.download(url, ref=False, disposition=True)
  File "/home/username/.local/lib/python3.6/site-packages/pyload/plugins/base/downloader.py", line 323, in download
    dl_url, dl_filename, get, post, ref, cookies, disposition, resume, chunks
  File "/home/username/.local/lib/python3.6/site-packages/pyload/plugins/base/downloader.py", line 240, in _download
    disposition,
  File "/home/username/.local/lib/python3.6/site-packages/pyload/core/network/browser.py", line 114, in http_download
    name = self.dl.download(chunks, resume)
  File "/home/username/.local/lib/python3.6/site-packages/pyload/core/network/http/http_download.py", line 128, in download
    self._download(chunks, resume)
  File "/home/username/.local/lib/python3.6/site-packages/pyload/core/network/http/http_download.py", line 271, in _download
    raise ex or Exception
pycurl.error: (23, 'Failed writing header')
```

**Comment by GammaC0de** [comment]
Please check the `develop` branch

**Comment by ihasaquesion** [comment]
How? Shouldn't `pip install --pre pyload-ng[all]` install the development version because of the --pre. I ran that command again and it didn't install a newer version but only displayed "Defaulting to user installation because normal site-packages is not writeable" and "Requirement already satisfied" messages.

I changed the command to `firejail --whitelist=/tmp/pyLoad/ --whitelist=~/.pyload firefox -no-remote -profile ~/Downloads/firefoxprofile` so that firefox has access to these two folders in case that's needed (seems like it didn't with the previous command).

**Comment by GammaC0de** [comment]
> Shouldn't pip install --pre pyload-ng[all] install the development version

pyload-ng (v0.5) is still in development and is in alpha state.
pyload 0.4.20 is the stable version.

> How?

Download https://github.com/pyload/pyload/archive/develop.zip and overwrite all the files inside the src directory

**Comment by ihasaquesion** [comment]
So no idea what might be the problem? I don't think it would work with an older version and if it does there's a problem with the newer version that should be solved. Anyways: I had v0.5 installed - I tried uninstalling with `pip uninstall pyload-ng` and installing the stable version with `pip install pyload-ng` but that's also v0.5. If this problem only occurs in the newer version or if that could be the case and i should check then could you please give me the command to install the proper stable version (and I haven't searched for the src directory)?

**Comment by GammaC0de** [comment]
For Debian, you should install this: https://github.com/pyload/pyload/releases/download/0.4.20/pyload-cli_0.4.20_all.deb
