### ISSUE TITLE
FilejokerNet: 400 Bad Request

### ISSUE THREAD

**Issue by ryester27** [pyload/pyload#3866]
### Description

The Filejoker plugin is now showing a 400 Bad Request error upon starting of any download

### Debug log

```
234	26.12.2020 14:30:01	INFO	Download starts: file.m4v
235	26.12.2020 14:30:01	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
236	26.12.2020 14:30:01	DEBUG	ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
237	26.12.2020 14:30:01	DEBUG	ADDON UserAgentSwitcher: Setting maximum redirections to 10
238	26.12.2020 14:30:01	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
239	26.12.2020 14:30:01	DEBUG	HOSTER FilejokerNet[21]: Plugin version: 0.10
240	26.12.2020 14:30:01	DEBUG	HOSTER FilejokerNet[21]: Plugin status: testing
241	26.12.2020 14:30:01	WARNING	HOSTER FilejokerNet[21]: Plugin may be unstable
242	26.12.2020 14:30:01	INFO	HOSTER FilejokerNet[21]: Grabbing link info...
243	26.12.2020 14:30:01	DEBUG	HOSTER FilejokerNet[21]: Link info: {'status': 2, 'hash': {}, 'name': u'file.m4v', 'url': u'https://filejoker.net/...', 'pattern': {'ID': u'...', 'N': u'file.m4v'}, 'size': 0}
244	26.12.2020 14:30:01	DEBUG	HOSTER FilejokerNet[21]: Previous link info: {}
245	26.12.2020 14:30:01	INFO	HOSTER FilejokerNet[21]: Link name: file.m4v
246	26.12.2020 14:30:01	INFO	HOSTER FilejokerNet[21]: Link size: N/D
247	26.12.2020 14:30:01	INFO	HOSTER FilejokerNet[21]: Link status: online
248	26.12.2020 14:30:01	INFO	HOSTER FilejokerNet[21]: Processing url: https://filejoker.net/...
249	26.12.2020 14:30:01	DEBUG	HOSTER FilejokerNet[21]: LOAD URL https://filejoker.net/... | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
250	26.12.2020 14:30:02	INFO	HOSTER FilejokerNet[21]: Checking for link errors...
251	26.12.2020 14:30:02	INFO	HOSTER FilejokerNet[21]: No errors found
252	26.12.2020 14:30:02	INFO	HOSTER FilejokerNet[21]: Processing as free download...
253	26.12.2020 14:30:02	DEBUG	HOSTER FilejokerNet[21]: Getting download link #1...
254	26.12.2020 14:30:02	INFO	HOSTER FilejokerNet[21]: Checking for link errors...
255	26.12.2020 14:30:02	INFO	HOSTER FilejokerNet[21]: No errors found
256	26.12.2020 14:30:02	DEBUG	HOSTER FilejokerNet[21]: {u'method_free': u'1', u'referer': '', u'id': u'...', u'fname': u'file.m4v', u'op': u'download1'}
257	26.12.2020 14:30:02	DEBUG	HOSTER FilejokerNet[21]: LOAD URL https://filejoker.net/... | redirect=False | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'method_free': 'Free Download', u'referer': u'https://filejoker.net/...', u'id': u'...', u'fname': u'file.m4v', u'op': u'download1'} | ref=https://filejoker.net/... | just_header=False
258	26.12.2020 14:30:03	DEBUG	HOSTER FilejokerNet[21]: Getting download link #2...
259	26.12.2020 14:30:03	INFO	HOSTER FilejokerNet[21]: Checking for link errors...
260	26.12.2020 14:30:03	INFO	HOSTER FilejokerNet[21]: No errors found
261	26.12.2020 14:30:03	DEBUG	HOSTER FilejokerNet[21]: {u'rand': u'rlu1lspr', u'method_premium': '', u'down_direct': u'1', u'referer': '', u'method_free': u'Free Download', u'id': u'...', u'op': u'download2'}
262	26.12.2020 14:30:03	DEBUG	HOSTER FilejokerNet[21]: WAIT set to timestamp 1609011124.008804 | Previous waitUntil: 0.000000
263	26.12.2020 14:30:03	DEBUG	CAPTCHA FilejokerNet[21]: ReCaptcha | Key: eefef47f-3ff5-4cb7-a394-4ef180ba0fc0
264	26.12.2020 14:30:03	WARNING	CAPTCHA FilejokerNet[21]: ReCaptcha | Secure Token pattern not found
265	26.12.2020 14:30:03	DEBUG	CAPTCHA FilejokerNet[21]: ReCaptcha | Detected reCAPTCHA v2
266	26.12.2020 14:30:03	WARNING	CAPTCHA FilejokerNet[21]: ReCaptcha | Secure Token pattern not found
267	26.12.2020 14:30:03	DEBUG	HOSTER FilejokerNet[21]: LOAD URL https://www.google.com/recaptcha/api/fallback?k=eefef47f-3ff5-4cb7-a394-4ef180ba0fc0 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=https://filejoker.net/... | just_header=False
268	26.12.2020 14:30:03	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
269	26.12.2020 14:30:03	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
270	26.12.2020 14:30:03	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
271	26.12.2020 14:30:03	WARNING	Download failed: file.m4v | Bad server response: 400 Bad Request
272	?	?	Traceback (most recent call last):
273	?	?	File "/app/pyload/module/PluginThread.py", line 189, in run
274	?	?	pyfile.plugin.preprocessing(self)
275	?	?	File "/app/pyload/module/plugins/internal/Base.py", line 291, in preprocessing
276	?	?	return self._process(*args, **kwargs)
277	?	?	File "/config/userplugins/internal/Hoster.py", line 118, in _process
278	?	?	self.process(self.pyfile)
279	?	?	File "/config/userplugins/internal/SimpleHoster.py", line 283, in process
280	?	?	self.handle_free(pyfile)
281	?	?	File "/app/pyload/module/plugins/internal/XFSHoster.py", line 100, in handle_free
282	?	?	post=self._post_parameters(),
283	?	?	File "/app/pyload/module/plugins/internal/XFSHoster.py", line 206, in _post_parameters
284	?	?	self.handle_captcha(inputs)
285	?	?	File "/app/pyload/module/plugins/hoster/FilejokerNet.py", line 64, in handle_captcha
286	?	?	response, _ = recaptcha.challenge(captcha_key)
287	?	?	File "/app/pyload/module/plugins/captcha/ReCaptcha.py", line 154, in challenge
288	?	?	secure_token=secure_token)
289	?	?	File "/app/pyload/module/plugins/captcha/ReCaptcha.py", line 149, in challenge
290	?	?	return getattr(self, "_challenge_v%s" % version)(key, secure_token=secure_token)
291	?	?	File "/app/pyload/module/plugins/captcha/ReCaptcha.py", line 281, in _challenge_v2
292	?	?	html = self.pyfile.plugin.load(fallback_url, ref=self.pyfile.url)
293	?	?	File "/app/pyload/module/plugins/internal/Base.py", line 487, in load
294	?	?	return Plugin.load(self, *args, **kwargs)
295	?	?	File "/app/pyload/module/plugins/internal/Plugin.py", line 248, in load
296	?	?	decode is True)
297	?	?	File "/app/pyload/module/network/Browser.py", line 98, in load
298	?	?	return self.http.load(*args, **kwargs)
299	?	?	File "/app/pyload/module/network/HTTPRequest.py", line 270, in load
300	?	?	self.code = self.verifyHeader()
301	?	?	File "/app/pyload/module/network/HTTPRequest.py", line 286, in verifyHeader
302	?	?	raise BadHeader(code, self.header, self.getResponse())
303	?	?	BadHeader: Bad server response: 400 Bad Request
304	26.12.2020 14:30:03	INFO	Debug Report written to debug_FilejokerNet_26-12-2020_14-30-03.zip
305	26.12.2020 14:30:03	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
306	26.12.2020 14:30:03	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: file.m4v (pid:9)
307	26.12.2020 14:30:03	INFO	ADDON UnSkipOnFail: No duplicates found
308	26.12.2020 14:30:03	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
309	26.12.2020 14:30:03	DEBUG	All downloads processed
```

**Comment by OzzieIsaacs** [comment]
Filejoker switched it's captcha system to "hcaptcha" instead of google "recaptcha":
![grafik](https://user-images.githubusercontent.com/6438895/103280766-75e70900-49d1-11eb-9955-b00b72c5c6b6.png)
I think this is currently not supported
