### ISSUE TITLE
install - problem with curl

### ISSUE THREAD

**Issue by UserX404** [pyload/pyload#3884]
### Description

I have problem installing pyload-ng due to my packagemanager (Entware) has excluded curl-config from curl.
Is there a way to solve or circumvent this issue?
Im not that professional to compile curl for my system by my own.

```
pip3 install pyload-ng[all]
Collecting pyload-ng[all]
  Using cached pyload_ng-0.5.0a9.dev806-py3-none-any.whl (1.3 MB)
Requirement already satisfied: setuptools>=38.3 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.9/site-packages (from pyload-ng[all]) (51.1.2)
Collecting bitmath~=1.3
  Using cached bitmath-1.3.3.1.tar.gz (88 kB)
Collecting Cheroot~=8.4
  Using cached cheroot-8.5.1-py2.py3-none-any.whl (96 kB)
Collecting cryptography~=3.0
  Using cached cryptography-3.3.1-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
Collecting cffi>=1.12
  Using cached cffi-1.14.4-cp39-cp39-manylinux1_x86_64.whl (405 kB)
Collecting filetype~=1.0
  Using cached filetype-1.0.7-py2.py3-none-any.whl (15 kB)
Collecting Flask~=1.1
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting click>=5.1
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |ââââââââââââââââââââââââââââââââ| 82 kB 1.3 MB/s
Collecting Flask-Babel~=1.0
  Using cached Flask_Babel-1.0.0-py3-none-any.whl (9.5 kB)
Collecting Babel
  Using cached Babel-2.9.0-py2.py3-none-any.whl (8.8 MB)
Collecting Flask-Caching~=1.9
  Using cached Flask_Caching-1.9.0-py2.py3-none-any.whl (33 kB)
Collecting Flask-Themes2~=0.1
  Using cached Flask-Themes2-0.1.5.tar.gz (10 kB)
Collecting itsdangerous>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Jinja2
     |ââââââââââââââââââââââââââââââââ| 125 kB 8.0 MB/s
Collecting Js2Py~=0.7
  Using cached Js2Py-0.70-py3-none-any.whl (605 kB)
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1.tar.gz (19 kB)
Collecting more-itertools>=2.6
  Using cached more_itertools-8.6.0-py3-none-any.whl (45 kB)
Collecting pycurl~=7.43
  Using cached pycurl-7.43.0.6.tar.gz (222 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-install-l61fyacy/pycurl_40675bbe82ca465f90e738e1ff6baf38/setup.py'"'"'; __file__='"'"'/share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-install-l61fyacy/pycurl_40675bbe82ca465f90e738e1ff6baf38/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-pip-egg-info-oqsznziq
         cwd: /share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-install-l61fyacy/pycurl_40675bbe82ca465f90e738e1ff6baf38/
    Complete output (20 lines):
    Traceback (most recent call last):
      File "/share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-install-l61fyacy/pycurl_40675bbe82ca465f90e738e1ff6baf38/setup.py", line 236, in configure_unix
        p = subprocess.Popen((self.curl_config(), '--version'),
      File "/opt/lib/python3.9/subprocess.py", line 947, in __init__
      File "/opt/lib/python3.9/subprocess.py", line 1819, in _execute_child
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-install-l61fyacy/pycurl_40675bbe82ca465f90e738e1ff6baf38/setup.py", line 988, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-install-l61fyacy/pycurl_40675bbe82ca465f90e738e1ff6baf38/setup.py", line 649, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-install-l61fyacy/pycurl_40675bbe82ca465f90e738e1ff6baf38/setup.py", line 101, in __init__
        self.configure()
      File "/share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pip-install-l61fyacy/pycurl_40675bbe82ca465f90e738e1ff6baf38/setup.py", line 241, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by rootsradics** [comment]
I have no real answer to your problem  but maybe this link could help : https://github.com/pyload/pyload/issues/3396
GammaC0de may have an answer to this question, as he already helped a previous user with particular issue.

**Comment by GammaC0de** [comment]
install `python3-curl` via `opkg`

**Comment by UserX404** [comment]
Closed because it's working now.

**Comment by StarScream159** [comment]
For anyone else coming across this issue for Almalinux/other RHEL distro's you can install the required curl package with DNF: `dnf install libcurl-devel`
