### ISSUE TITLE
TypeError when adding FilerNet package

### ISSUE THREAD

**Issue by Earl0fPudding** [pyload/pyload#3886]
### Description

When I try to add a FilerNet package I get the following:
```
[2021-01-10 15:52:28]  INFO                pyload  Download starts: /root/Downloads/pyLoad/tmp_
[2021-01-10 15:52:28]  DEBUG               pyload  DOWNLOADER DefaultPlugin[26]: Plugin version: 0.52
[2021-01-10 15:52:28]  DEBUG               pyload  DOWNLOADER DefaultPlugin[26]: Plugin status: testing
[2021-01-10 15:52:28]  WARNING             pyload  DOWNLOADER DefaultPlugin[26]: Plugin may be unstable
[2021-01-10 15:52:28]  DEBUG               pyload  DOWNLOADER DefaultPlugin[26]: Config option `use_premium` not found, use default `True`
[2021-01-10 15:52:28]  INFO                pyload  DOWNLOADER DefaultPlugin[26]: Grabbing link info...
[2021-01-10 15:52:28]  DEBUG               pyload  DOWNLOADER DefaultPlugin[26]: Link info: {'name': 'tmp_', 'hash': {}, 'pattern': {}, 'size': 0, 'status': 7, 'url': '/root/Downloads/pyLoad/tmp_'}
[2021-01-10 15:52:28]  DEBUG               pyload  DOWNLOADER DefaultPlugin[26]: Previous link info: {}
[2021-01-10 15:52:28]  INFO                pyload  DOWNLOADER DefaultPlugin[26]: Link name: tmp_
[2021-01-10 15:52:28]  INFO                pyload  DOWNLOADER DefaultPlugin[26]: Link size: N/D
[2021-01-10 15:52:28]  INFO                pyload  DOWNLOADER DefaultPlugin[26]: Link status: starting
[2021-01-10 15:52:28]  WARNING             pyload  Download failed: tmp_ | No plugin matched
[2021-01-10 15:52:28]  INFO                pyload  ADDON UnSkipOnFail: Looking for skipped duplicates of: tmp_ (pid:14)
[2021-01-10 15:52:28]  INFO                pyload  ADDON UnSkipOnFail: No duplicates found
[2021-01-10 15:52:29]  INFO                pyload  Decrypting starts: https://filer.net/folder/dmzuzdepgsfmq8gv
[2021-01-10 15:52:29]  DEBUG               pyload  DECRYPTER FilerNetFolder[27]: Plugin version: 0.48
[2021-01-10 15:52:29]  DEBUG               pyload  DECRYPTER FilerNetFolder[27]: Plugin status: testing
[2021-01-10 15:52:29]  WARNING             pyload  DECRYPTER FilerNetFolder[27]: Plugin may be unstable
[2021-01-10 15:52:29]  INFO                pyload  DECRYPTER FilerNetFolder[27]: Grabbing link info...
[2021-01-10 15:52:30]  DEBUG               pyload  Error when decoding string from b'utf-8'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyload/core/network/http/http_request.py", line 328, in decode_response
    if codecs.lookup(encoding).name == "utf-8" and rep.startswith(
TypeError: lookup() argument must be str, not bytes
[2021-01-10 15:52:30]  WARNING             pyload  Decrypting failed: https://filer.net/folder/dmzuzdepgsfmq8gv | cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyload/core/threads/decrypter_thread.py", line 40, in run
    self.active.plugin.preprocessing(self)
  File "/usr/local/lib/python3.7/dist-packages/pyload/plugins/base/hoster.py", line 304, in preprocessing
    return self._process(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pyload/plugins/base/hoster.py", line 280, in _process
    self._setup()
  File "/usr/local/lib/python3.7/dist-packages/pyload/plugins/base/hoster.py", line 175, in _setup
    self.grab_info()
  File "/usr/local/lib/python3.7/dist-packages/pyload/plugins/base/hoster.py", line 236, in grab_info
    new_info = self.get_info(self.pyfile.url, self.data)
  File "/usr/local/lib/python3.7/dist-packages/pyload/plugins/base/simple_decrypter.py", line 119, in get_info
    if cls.OFFLINE_PATTERN and re.search(cls.OFFLINE_PATTERN, html) is not None:
  File "/usr/lib/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
[2021-01-10 15:52:30]  DEBUG               pyload  Error creating zip file: [Errno 2] No such file or directory: '/tmp/pyLoad/FilerNetFolder'
[2021-01-10 15:52:30]  INFO                pyload  Debug Report written to /tmp/pyLoad/debug_FilerNetFolder_2021-01-10_15-52-30.txt
```

[debug_FilerNetFolder_2021-01-10_15-52-30.txt](https://github.com/pyload/pyload/files/5792876/debug_FilerNetFolder_2021-01-10_15-52-30.txt)

**Comment by GammaC0de** [comment]
Works fine for me,
You are using an unupdated version of pyload-next, please sync your installation with the stable branch

**Comment by Earl0fPudding** [comment]
Installed the latest .deb file and it worked.
