### ISSUE TITLE
Unable to add filer.net (filernet) account login information ("Error occurred")

### ISSUE THREAD

**Issue by michaelweinold** [pyload/pyload#3891]
### Description
Unable to add premium account login information for filer.net service. "Error occured" banner thrown by the web interface.

### Debug log

```
[2021-01-26 11:55:34]  DEBUG         pyload.webui  'login'
Traceback (most recent call last):
  File "c:\users\testuser\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\testuser\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\testuser\appdata\local\programs\python\python38\lib\site-packages\pyload\webui\app\helpers.py", line 181, in wrapper
    response = func(*args, **kwargs)
  File "c:\users\testuser\appdata\local\programs\python\python38\lib\site-packages\pyload\webui\app\blueprints\json_blueprint.py", line 285, in add_account
    api.update_account(type, login, password)
  File "c:\users\testuser\appdata\local\programs\python\python38\lib\site-packages\pyload\core\api\__init__.py", line 81, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\testuser\appdata\local\programs\python\python38\lib\site-packages\pyload\core\api\__init__.py", line 1187, in update_account
    self.pyload.account_manager.update_account(plugin, account, password, options)
  File "c:\users\testuser\appdata\local\programs\python\python38\lib\site-packages\pyload\core\utils\old\__init__.py", line 144, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\testuser\appdata\local\programs\python\python38\lib\site-packages\pyload\core\managers\account_manager.py", line 165, in update_account
    updated = p.update_accounts(user, password, options)
  File "c:\users\testuser\appdata\local\programs\python\python38\lib\site-packages\pyload\core\utils\old\__init__.py", line 144, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\testuser\appdata\local\programs\python\python38\lib\site-packages\pyload\plugins\base\account.py", line 342, in update_accounts
    self.add(user, password, options)
  File "c:\users\testuser\appdata\local\programs\python\python38\lib\site-packages\pyload\core\utils\old\__init__.py", line 144, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\testuser\appdata\local\programs\python\python38\lib\site-packages\pyload\plugins\base\account.py", line 295, in add
    self.log_info(self._("Adding user `{}`...").format(user[:3] + "*" * 7))
  File "c:\users\testuser\appdata\local\programs\python\python38\lib\site-packages\pyload\plugins\base\plugin.py", line 86, in log_info
    self._log("info", self.__type__, self.__name__, args, kwargs)
  File "c:\users\testuser\appdata\local\programs\python\python38\lib\site-packages\pyload\plugins\base\account.py", line 76, in _log
    pw = self.info["login"]["password"]
KeyError: 'login'
[2021-01-26 11:55:34]  INFO          pyload.webui  Locating template "_themes/pyplex/error.html":
    1: trying loader of application "pyload.webui.app"
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - c:\users\testuser\appdata\local\programs\python\python38\lib\site-packages\pyload\webui\app\templates
       -> no match
    2: trying loader of blueprint "_themes" (flask_themes2)
       class: flask_themes2.ThemeTemplateLoader
       as_blueprint: True
       -> found ('c:\\users\\testuser\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pyload\\webui\\app\\themes\\pyplex\\templates\\error.html')
127.0.0.1 - - [26/Jan/2021 11:55:34] "POST /json/add_account HTTP/1.1" 500 -
127.0.0.1 - - [26/Jan/2021 11:55:35] "POST /json/status HTTP/1.1" 200 -
127.0.0.1 - - [26/Jan/2021 11:55:35] "POST /json/status HTTP/1.1" 200 -
```

### Additional references
pyload installed with pip in Python 3.8.2 (pyenv-win) under Windows 10 64 bit.

### Screenshots

![image](https://user-images.githubusercontent.com/23102087/105836760-f6e3f100-5fcd-11eb-9bcb-b787f9d756ab.png)

**Comment by GammaC0de** [comment]
Please use pyload v0.4.20, not v0.5.
v0.5 is beta.
