### ISSUE TITLE
Nitroflare Login Handshake failed

### ISSUE THREAD

**Issue by ethernity** [pyload/pyload#3898]
Premium download with NitroFlare doesn't seem to work anymore. I always get Handshake failed

Log:

```
> 297 | 13.02.2021 11:17:04 | INFO | ACCOUNT NitroflareCom: Adding user `*******`...
> -- | -- | -- | --
> 298 | 13.02.2021 11:17:04 | DEBUG | ACCOUNT NitroflareCom: Reached login timeout for user `*******`
> 299 | 13.02.2021 11:17:04 | INFO | ACCOUNT NitroflareCom: Login user `*******`...
> 300 | 13.02.2021 11:17:04 | DEBUG | ACCOUNT NitroflareCom: LOAD URL  https://nitroflare.com/api/v2/getKeyInfo \| redirect=True \| cookies=True \|  get={'premiumKey': '**********', 'user': '*******'} \| req=None \|  decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
> 301 | 13.02.2021 11:17:05 | ERROR | ACCOUNT NitroflareCom: Could not login user `*******` \| Login handshake has failed
> 302 | ? | ? | Traceback (most recent call last):
> 303 | ? | ? | File "/usr/share/pyload/pyLoadCore.py", line 687, in
> 304 | ? | ? | main()
> 305 | ? | ? | File "/usr/share/pyload/pyLoadCore.py", line 674, in main
> 306 | ? | ? | deamon()
> 307 | ? | ? | File "/usr/share/pyload/pyLoadCore.py", line 666, in deamon
> 308 | ? | ? | pyload_core.start()
> 309 | ? | ? | File "/usr/share/pyload/pyLoadCore.py", line 447, in start
> 310 | ? | ? | self.accountManager.getAccountInfos()
> 311 | ? | ? | File "/usr/share/pyload/module/utils.py", line 169, in new
> 312 | ? | ? | return func(*args)
> 313 | ? | ? | File "/usr/share/pyload/module/plugins/AccountManager.py", line 181, in getAccountInfos
> 314 | ? | ? | data[p.__name__] = p.getAllAccounts(force)
> 315 | ? | ? | File "/home/xbian/.pyload/userplugins/internal/misc.py", line 228, in new
> 316 | ? | ? | return fn(*args, **kwargs)
> 317 | ? | ? | File "/home/xbian/.pyload/userplugins/internal/Account.py", line 275, in getAllAccounts
> 318 | ? | ? | self.init_accounts()  # @TODO: Recheck in 0.4.10
> 319 | ? | ? | File "/home/xbian/.pyload/userplugins/internal/misc.py", line 228, in new
> 320 | ? | ? | return fn(*args, **kwargs)
> 321 | ? | ? | File "/home/xbian/.pyload/userplugins/internal/Account.py", line 263, in init_accounts
> 322 | ? | ? | self.add(user, info['password'], info['options'])
> 323 | ? | ? | File "/home/xbian/.pyload/userplugins/internal/misc.py", line 228, in new
> 324 | ? | ? | return fn(*args, **kwargs)
> 325 | ? | ? | File "/home/xbian/.pyload/userplugins/internal/Account.py", line 309, in add
> 326 | ? | ? | result = u['plugin'].choose(user)
> 327 | ? | ? | File "/home/xbian/.pyload/userplugins/internal/misc.py", line 228, in new
> 328 | ? | ? | return fn(*args, **kwargs)
> 329 | ? | ? | File "/home/xbian/.pyload/userplugins/internal/Account.py", line 426, in choose
> 330 | ? | ? | self.relogin()
> 331 | ? | ? | File "/home/xbian/.pyload/userplugins/internal/Account.py", line 173, in relogin
> 332 | ? | ? | return self.login()
> 333 | ? | ? | File "/home/xbian/.pyload/userplugins/internal/Account.py", line 114, in login
> 334 | ? | ? | self.info['data'])
> 335 | ? | ? | File "/home/xbian/.pyload/userplugins/accounts/NitroflareCom.py", line 50, in signin
> 336 | ? | ? | self.fail_login()
> 337 | ? | ? | File "/home/xbian/.pyload/userplugins/internal/Account.py", line 441, in fail_login
> 338 | ? | ? | return self.fail(msg)
> 339 | ? | ? | File "/home/xbian/.pyload/userplugins/internal/Plugin.py", line 191, in fail
> 340 | ? | ? | raise Fail(decode(msg))  # @TODO: Remove `decode` in 0.4.10
> 341 | ? | ? | Fail: Login handshake has failed
> 342 | ? | ? |  
> 343 | 13.02.2021 11:17:05 | INFO | Activating Plugins...
```

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
Well!?

**Comment by GammaC0de** [comment]
No response, closing.
