### ISSUE TITLE
AttributeError: 'HTMLParser' object has no attribute 'unescape'

### ISSUE THREAD

**Issue by martadinata666** [pyload/pyload#3909]
### Description
Error occured when add download links.
Environment:
 1. Python 3.9
 2. Docker Debian Sid
 3. Installation using ```pip install --pre pyload-ng[all]```

### Debug log

```
pyLoad 0.5.0 Debug Report of DefaultPlugin 0.52 

TRACEBACK:
 Traceback (most recent call last):
  File "/home/debian/.local/lib/python3.9/site-packages/pyload/core/threads/download_thread.py", line 56, in run
    pyfile.plugin.preprocessing(self)
  File "/home/debian/.local/lib/python3.9/site-packages/pyload/plugins/base/hoster.py", line 304, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/debian/.local/lib/python3.9/site-packages/pyload/plugins/base/downloader.py", line 90, in _process
    self._setup()
  File "/home/debian/.local/lib/python3.9/site-packages/pyload/plugins/base/hoster.py", line 175, in _setup
    self.grab_info()
  File "/home/debian/.local/lib/python3.9/site-packages/pyload/plugins/base/hoster.py", line 236, in grab_info
    new_info = self.get_info(self.pyfile.url, self.data)
  File "/home/debian/.local/lib/python3.9/site-packages/pyload/plugins/base/hoster.py", line 48, in get_info
    url = fixurl(url, unquote=True)
  File "/home/debian/.local/lib/python3.9/site-packages/pyload/core/utils/old/__init__.py", line 113, in fixurl
    url = html_unescape(url)
  File "/home/debian/.local/lib/python3.9/site-packages/pyload/core/utils/old/__init__.py", line 156, in html_unescape
    return h.unescape(text)
AttributeError: 'HTMLParser' object has no attribute 'unescape'

```

### Additional references

HTMLParser.unescape is removed. It was undocumented and deprecated since Python 3.4.
https://docs.python.org/release/3.9.0/whatsnew/changelog.html
https://bugs.python.org/issue37328
https://github.com/python/cpython/commit/8dd430265ccd4d34b74c841d6bcc8f58aa93ad94

**Comment by GammaC0de** [comment]
Please use the `develop` branch.
