### ISSUE TITLE
Realdebridlogin not working

### ISSUE THREAD

**Issue by asdproton** [pyload/pyload#3912]
I am trying to enter RealDebridCom credentials and receive an error. Both with username/password and with credentials created via /devices

[2021-03-15 21:22:17]  DEBUG         pyload.webui  'login'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/pyload/webui/app/helpers.py", line 181, in wrapper
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyload/webui/app/blueprints/json_blueprint.py", line 285, in add_account
    api.update_account(type, login, password)
  File "/usr/local/lib/python3.6/site-packages/pyload/core/api/__init__.py", line 81, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyload/core/api/__init__.py", line 1187, in update_account
    self.pyload.account_manager.update_account(plugin, account, password, options)
  File "/usr/local/lib/python3.6/site-packages/pyload/core/utils/old/__init__.py", line 144, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyload/core/managers/account_manager.py", line 165, in update_account
    updated = p.update_accounts(user, password, options)
  File "/usr/local/lib/python3.6/site-packages/pyload/plugins/base/multi_account.py", line 465, in update_accounts
    super().update_accounts(user, password, options)
  File "/usr/local/lib/python3.6/site-packages/pyload/core/utils/old/__init__.py", line 144, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyload/plugins/base/account.py", line 342, in update_accounts
    self.add(user, password, options)
  File "/usr/local/lib/python3.6/site-packages/pyload/core/utils/old/__init__.py", line 144, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyload/plugins/base/account.py", line 295, in add
    self.log_info(self._("Adding user `{}`...").format(user[:3] + "*" * 7))
  File "/usr/local/lib/python3.6/site-packages/pyload/plugins/base/plugin.py", line 86, in log_info
    self._log("info", self.__type__, self.__name__, args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyload/plugins/base/account.py", line 76, in _log
    pw = self.info["login"]["password"]
KeyError: 'login'

Any idea?

**Comment by GammaC0de** [comment]
You have to use GetRealdebridToken.py to authorize pyLoad: https://github.com/pyload/pyload/files/4406037/GetRealdebridToken.zip

Also, you should use the `develop` branch.

**Comment by asdproton** [comment]
Hi,

I got those credentials (which work in 0.4.20 but not in 0.5.0). I installed using pip as advertised on the web. Do I need to install it differently?

**Comment by asdproton** [comment]
I used

pip3 install --pre pyload-ng[all]

**Comment by GammaC0de** [comment]
0.5.0 is still in development.

> I used
>
>pip3 install --pre pyload-ng[all]

This is the `main` branch.

You have to update pyload from git `develop` branch zip archive https://github.com/pyload/pyload/archive/develop.zip

**Comment by asdproton** [comment]
Sure thing will do. I was unable to find instructions (that I am capable of understanding at least). After installing with pip, how would I change to the development branch?

Terribly sorry to burden you with this. Yes I have the ZIP... But then?

**Comment by GammaC0de** [comment]
- Browse to `http://<PYLOAD_IP>/info` and write down the value of `Installation Folder`.
- Stop pyload.
- Unzip the zip file into the Installation Folder overwriting the old files (the zip file contains a pyload-stable root directory - you must extract the files without this directory, e.g: `pyload-next\pyLoadCore.py` becomes `pyLoadCore.py` and so on..).
- Start pyload.

**Comment by asdproton** [comment]
The ZIP file contains this

AUTHORS.md  babel.cfg  CODE_OF_CONDUCT.md  Dockerfile  Dockerfile.alpine  Dockerfile.armhf  LICENSE.md  MANIFEST.in  media  pyproject.toml  README.md  setup.cfg  setup.py  src  tests  tox.ini  VERSION

but no pyLoadCore.py.... I must be blind.

**Comment by GammaC0de** [comment]
This was just an example, you have to extract the zip to the same place the original files were.

**Comment by asdproton** [comment]
Ok thanks. That worked. What is the general "keep this baby updated to the latest development branch" process? Load the latest ZIP or is there some git magic command to run from the installation directory?

Thanks very much for your help. RD seems to be working now.

**Comment by GammaC0de** [comment]
When development will be finished, the plan is to be updated via pip but for now you can repeat the above process firm time to time. 
 
 
  
***@***.***> wrote:   


Ok thanks. That worked. What is the general "keep this baby updated to the latest development branch" process? Load the latest ZIP or is there some git magic command to run from the installation directory?

Thanks very much for your help. RD seems to be working now.
