### ISSUE TITLE
ddownload Plugin missing

### ISSUE THREAD

**Issue by asdproton** [pyload/pyload#3913]
In the latest 0.5.0 development branch (or to be exact a 4 day old version) I am not able to enter ddownload credentials anymore. Is the plugin gone?

**Comment by GammaC0de** [comment]
> Is the plugin gone?

It's not gone, v0.5.0 is still in development, some plugins has not been converted to v0.5.0 yet.

**Comment by asdproton** [comment]
@GammaC0de Thanks.

Tried the latest developer version:

`[2021-03-21 13:32:10]  INFO                pyload  ACCOUNT DdownloadCom: Adding user `**********`...
[2021-03-21 13:32:10]  DEBUG               pyload  ACCOUNT DdownloadCom: Reached login timeout for user `*******`
[2021-03-21 13:32:10]  INFO                pyload  ACCOUNT DdownloadCom: Login user `*******`...
[2021-03-21 13:32:10]  DEBUG               pyload  ACCOUNT DdownloadCom: LOAD URL http://www.ddownload.com/login.html | get={} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2021-03-21 13:32:10]  DEBUG               pyload  ACCOUNT DdownloadCom: LOAD URL https://ddownload.com/ | get={} | post={'op': 'login', 'token': '***', 'rand': '', 'redirect': 'http://www.ddownload.com/login.html', 'login': '*******', 'password': '**********'} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2021-03-21 13:32:10]  INFO                pyload  ACCOUNT DdownloadCom: Checking for link errors...
[2021-03-21 13:32:10]  INFO                pyload  ACCOUNT DdownloadCom: No errors found
[2021-03-21 13:32:10]  INFO                pyload  ACCOUNT DdownloadCom: Grabbing account info for user `*******`...
[2021-03-21 13:32:10]  DEBUG               pyload  ACCOUNT DdownloadCom: LOAD URL http://www.ddownload.com/ | get={'op': 'my_account'} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2021-03-21 13:32:11]  DEBUG               pyload  ACCOUNT DdownloadCom: Expire date: 29 April 2021
[2021-03-21 13:32:11]  DEBUG               pyload  ACCOUNT DdownloadCom: Valid until: 1619654400.0
[2021-03-21 13:32:11]  DEBUG               pyload  ACCOUNT DdownloadCom: Size: 114448MB | Unit: {unit or 'N/D'}
[2021-03-21 13:32:11]  DEBUG               pyload  ACCOUNT DdownloadCom: LEECH TRAFFIC PATTERN not found
[2021-03-21 13:32:11]  DEBUG               pyload  ACCOUNT DdownloadCom: Account info for user `*******`: {'login': {'password': '**********', 'timestamp': 1616333530.0629568, 'valid': True}, 'data': {'login': '*******', 'maxtraffic': None, 'options': {'limit_dl': ['0']}, 'plugin': <Account DdownloadCom>, 'premium': True, 'trafficleft': 114448.0, 'type': 'DdownloadCom', 'validuntil': 1619654400.0, 'leechtraffic': None}}
192.168.202.35 - - [21/Mar/2021 13:32:11] "POST /json/add_account HTTP/1.1" 200 -
[2021-03-21 13:32:11]  DEBUG         pyload.webui  unsupported operand type(s) for <<: 'float' and 'int'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/pyload/webui/app/helpers.py", line 182, in wrapper
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyload/webui/app/blueprints/app_blueprint.py", line 198, in settings
    trafficleft = format.size(data.trafficleft << 10)
TypeError: unsupported operand type(s) for <<: 'float' and 'int'
[2021-03-21 13:32:11]  INFO          pyload.webui  Locating template "_themes/pyplex/error.html":
    1: trying loader of application "pyload.webui.app"
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - /usr/local/lib/python3.9/site-packages/pyload/webui/app/templates
       -> no match
    2: trying loader of blueprint "_themes" (flask_themes2)
       class: flask_themes2.ThemeTemplateLoader
       as_blueprint: True
       -> found ('/usr/local/lib/python3.9/site-packages/pyload/webui/app/themes/pyplex/templates/error.html')`


After that the settings page does not work anymore... Once I delete the account in accounts.cfg it at least works again. :-)

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by asdproton** [comment]
On its way
