### ISSUE TITLE
RealDebrid - No plugin is associated with torrents / magnets - but works when re-added

### ISSUE THREAD

**Issue by kepi** [pyload/pyload#3914]
### Description

I'm using RealDebrid premium account to download torrents using magnet links. It usually works but sometimes I get error "No plugin is associated with torrents / magnets".

When error occurs, package *restart* is not helping. It simply generate returns same error again and again.

But when I copy the magnet URL of failed *Package* and add it again with same information, everything is working for new package.

From what I understand (or better "think") it happens when some error occurs with RealDebird servers or plugin. And it would be OK if *restart failed* would fix it later, but it doesn't.

I tried to play with code as I intended to send fix for this, but I failed. Probably don't understand the link states / workflow correctly.

Anyway from logs bellow my guess is, that when URL is decrypted, it progress to some new state which don't call decrypter correctly on next try? At least first line is different - in failed download it says that decrypting starts and there is only *link name*. But when I add new package, there is whole URL in *decrypting starts* phase.

If there is anything else I can provide to help fix this, let me know.

### Debug log

Failing package download:

```
19.03.2021 23:32:50 INFO      Decrypting starts: urnbtih6869d617482ab123a2dc5186b693aa598d200dc8
19.03.2021 23:32:50 DEBUG     CONTAINER TORRENT[450]: Plugin version: 0.04
19.03.2021 23:32:50 DEBUG     CONTAINER TORRENT[450]: Plugin status: testing
19.03.2021 23:32:50 WARNING   CONTAINER TORRENT[450]: Plugin may be unstable
19.03.2021 23:32:50 INFO      CONTAINER TORRENT[450]: Grabbing link info...
19.03.2021 23:32:50 DEBUG     CONTAINER TORRENT[450]: Link info: {'status': 7, 'hash': {}, 'name': u'urnbtih6869d617482ab123a2dc5186b693aa598d200dc8', 'url': u'magnet:?xt=urn:btih:6869d617482ab123a2dc5186b693aa598d200dc8&dn=Some.File.720p.WEB.H264-GGWP[rartv]&tr=http://tracker.trackerfix.com:80/announce&tr=udp://9.rarbg.me:2710&tr=udp://9.rarbg.to:2710&tr=udp://open.demonii.com:1337/announce', 'pattern': {}, 'size': 0}
19.03.2021 23:32:50 DEBUG     CONTAINER TORRENT[450]: Previous link info: {}
19.03.2021 23:32:50 INFO      CONTAINER TORRENT[450]: Link name: urnbtih6869d617482ab123a2dc5186b693aa598d200dc8
19.03.2021 23:32:50 INFO      CONTAINER TORRENT[450]: Link size: N/D
19.03.2021 23:32:50 INFO      CONTAINER TORRENT[450]: Link status: starting
19.03.2021 23:32:50 INFO      CONTAINER TORRENT[450]: Processing url: magnet:?xt=urn:btih:6869d617482ab123a2dc5186b693aa598d200dc8&dn=Some.File.720p.WEB.H264-GGWP[rartv]&tr=http://tracker.trackerfix.com:80/announce&tr=udp://9.rarbg.me:2710&tr=udp://9.rarbg.to:2710&tr=udp://open.demonii.com:1337/announce
19.03.2021 23:32:50 ERROR     CONTAINER TORRENT[450]: No plugin is associated with torrents / magnets | Please go to plugin settings -> TORRENT and select your preferred plugin
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/filmiky/apps/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/home/filmiky/apps/pyload/module/plugins/internal/Base.py", line 291, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/filmiky/apps/pyload/module/plugins/internal/Base.py", line 281, in _process
    self.process(self.pyfile)
  File "/home/filmiky/apps/pyload/module/plugins/container/TORRENT.py", line 32, in process
    _("Please go to plugin settings -> TORRENT and select your preferred plugin"))

19.03.2021 23:32:50 ERROR     Decrypting failed: urnbtih6869d617482ab123a2dc5186b693aa598d200dc8 | No plugin is associated with torrents / magnets
```

I'm leaving it in place and adding same download again:

```
19.03.2021 23:44:27 INFO      Added package Some.File.720p.WEB.H264-GGWP[rartv] containing 1 links
19.03.2021 23:44:29 INFO      Decrypting starts: magnet:?xt=urn:btih:6869d617482ab123a2dc5186b693aa598d200dc8&dn=Some.File.720p.WEB.H264-GGWP[rartv]&tr=http://tracker.trackerfix.com:80/announce&tr=udp://9.rarbg.me:2710&tr=udp://9.rarbg.to:2710&tr=udp://open.demonii.com:1337/announce                                                          
19.03.2021 23:44:29 DEBUG     CRYPTER RealdebridComTorrent[674]: Plugin version: 0.14
19.03.2021 23:44:29 DEBUG     CRYPTER RealdebridComTorrent[674]: Plugin status: testing
19.03.2021 23:44:29 WARNING   CRYPTER RealdebridComTorrent[674]: Plugin may be unstable
19.03.2021 23:44:29 DEBUG     CRYPTER RealdebridComTorrent[674]: Config option `use_premium` not found, use default `True`
19.03.2021 23:44:29 INFO      CRYPTER RealdebridComTorrent[674]: Grabbing link info...
19.03.2021 23:44:29 DEBUG     CRYPTER RealdebridComTorrent[674]: Link info: {'status': 7, 'hash': {}, 'name': u'urnbtih6869d617482ab123a2dc5186b693aa598d200dc8', 'url': u'magnet:?xt=urn:btih:6869d617482ab123a2dc5186b693aa598d200dc8&dn=Some.File.720p.WEB.H264-GGWP[rartv]&tr=http://tracker.trackerfix.com:80/announce&tr=udp://9.rarbg.me:2710&tr=udp://9.rarbg.to:2710&tr=udp://open.demonii.com:1337/announce', 'pattern': {}, 'size': 0}
19.03.2021 23:44:29 DEBUG     CRYPTER RealdebridComTorrent[674]: Previous link info: {}
19.03.2021 23:44:29 INFO      CRYPTER RealdebridComTorrent[674]: Link name: urnbtih6869d617482ab123a2dc5186b693aa598d200dc8
19.03.2021 23:44:29 INFO      CRYPTER RealdebridComTorrent[674]: Link size: N/D
19.03.2021 23:44:29 INFO      CRYPTER RealdebridComTorrent[674]: Link status: starting
19.03.2021 23:44:29 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
19.03.2021 23:44:29 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
19.03.2021 23:44:29 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
19.03.2021 23:44:29 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36`
19.03.2021 23:44:29 INFO      CRYPTER RealdebridComTorrent[674]: Processing url: magnet:?xt=urn:btih:6869d617482ab123a2dc5186b693aa598d200dc8&dn=Some.File.720p.WEB.H264-GGWP[rartv]&tr=http://tracker.trackerfix.com:80/announce&tr=udp://9.rarbg.me:2710&tr=udp://9.rarbg.to:2710&tr=udp://open.demonii.com:1337/announce                          
19.03.2021 23:44:29 DEBUG     CRYPTER RealdebridComTorrent[674]: LOAD URL https://api.real-debrid.com/rest/1.0/torrents/addMagnet | redirect=True | cookies=True | get={'auth_token': u'Mr.Token'} | req=None | decode=True | multipart=False | post={'magnet': u'magnet:?xt=urn:btih:6869d617482ab123a2dc5186b693aa598d200dc8&dn=Some.File.720p.WEB.H264-GGWP[rartv]&tr=http://tracker.trackerfix.com:80/announce&tr=udp://9.rarbg.me:2710&tr=udp://9.rarbg.to:2710&tr=udp://open.demonii.com:1337/announce'} | ref=True | just_header=False                                                                                                                                      
19.03.2021 23:44:30 DEBUG     CRYPTER RealdebridComTorrent[674]: LOAD URL https://api.real-debrid.com/rest/1.0/torrents/info/DYSXKQLVIOYEG | redirect=True | cookies=True | get={'auth_token': u'Mr.Token'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False                  
```

And it works...

### Screenshots

![pyload_magnet_failed](https://user-images.githubusercontent.com/105303/111849785-bf7b2c00-890e-11eb-912f-d658471f36d9.png)
![pyload_magnet_config](https://user-images.githubusercontent.com/105303/111849788-c30eb300-890e-11eb-8d04-1bd36cb4330b.png)

Thanks

**Comment by GammaC0de** [comment]
How often do you use RealdebridComTorrent?
how often this issue happens?

**Comment by kepi** [comment]
I have Pyload started 24/7 and files are incoming from FlexGet at random. I tried to check logs now but there is only 2 days of data there.

To be clear, I can't say for sure as I'm not watching what got downloaded. I have automated setup and many files are for later. I'm seeing only those failed packages and not those which completed OK. My guess would be something between 5 and 30 %.

From memory (which I would belive too much): Couple times I was checking queue directly and saw all packages without problem, couple times I saw how flexget added i.e. 30 packages and 3 of them was OK, 27 failed. I believe that OK downloads was between those failed and some was from same source. It seems to me that it got better lately but I got some failed this week too.

I have this issue for couple months at least. Wanted to fix it myself so I postponed it every time and manually redownloaded some files I needed most. I'm simply moving failed pakcages to *collector* now  and hoping that I can restart them when/if there will be fix.

**Comment by GammaC0de** [comment]
Plugin updated, please confirm issue is solved.

**Comment by kepi** [comment]
Should it work with previously failed Packages? I have some of them "stored" in *Collector*. I tried with one of them but unfortunatelly same problem:

```
21.03.2021 03:05:45 INFO      Decrypting starts: urnbtih1a2b67d899d5e3695900d551f10c7468572594cd
21.03.2021 03:05:45 DEBUG     CONTAINER TORRENT[451]: Plugin version: 0.05
21.03.2021 03:05:45 DEBUG     CONTAINER TORRENT[451]: Plugin status: testing
21.03.2021 03:05:45 WARNING   CONTAINER TORRENT[451]: Plugin may be unstable
21.03.2021 03:05:45 INFO      CONTAINER TORRENT[451]: Grabbing link info...
21.03.2021 03:05:45 DEBUG     CONTAINER TORRENT[451]: Link info: {'status': 7, 'hash': {}, 'name': u'urnbtih1a2b67d899d5e3695900d551f10c7468572594cd', 'url': u'magnet:?xt=urn:btih:1a2b67d899d5e3695900d551f10c7468572594cd&dn=Other.File.720p.WEB.h264-KOMPOST[rartv]&tr=http://tracker.trackerfix.com:80/announce&tr=udp://9.rarbg.me:2710&tr=udp://9.rarbg.to:2710&tr=udp://open.demonii.com:1337/announce', 'pattern': {}, 'size': 0}
21.03.2021 03:05:45 DEBUG     CONTAINER TORRENT[451]: Previous link info: {}
21.03.2021 03:05:45 INFO      CONTAINER TORRENT[451]: Link name: urnbtih1a2b67d899d5e3695900d551f10c7468572594cd
21.03.2021 03:05:45 INFO      CONTAINER TORRENT[451]: Link size: N/D
21.03.2021 03:05:45 INFO      CONTAINER TORRENT[451]: Link status: starting
21.03.2021 03:05:45 INFO      CONTAINER TORRENT[451]: Processing url: magnet:?xt=urn:btih:1a2b67d899d5e3695900d551f10c7468572594cd&dn=Other.File.720p.WEB.h264-KOMPOST[rartv]&tr=http://tracker.trackerfix.com:80/announce&tr=udp://9.rarbg.me:2710&tr=udp://9.rarbg.to:2710&tr=udp://open.demonii.com:1337/announce
21.03.2021 03:05:45 ERROR     CONTAINER TORRENT[451]: No plugin is associated with torrents / magnets | Please go to plugin settings -> TORRENT and select your preferred plugin
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/filmiky/apps/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/home/filmiky/apps/pyload/module/plugins/internal/Base.py", line 291, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/filmiky/apps/pyload/module/plugins/internal/Base.py", line 281, in _process
    self.process(self.pyfile)
  File "/home/filmiky/apps/pyload/module/plugins/container/TORRENT.py", line 32, in process
    _("Please go to plugin settings -> TORRENT and select your preferred plugin"))

21.03.2021 03:05:45 ERROR     Decrypting failed: urnbtih1a2b67d899d5e3695900d551f10c7468572594cd | No plugin is associated with torrents / magnets
```

**Comment by GammaC0de** [comment]
Most certainly you have to remove the package and then re-add it.

**Comment by kepi** [comment]
Pitty... :) Ok, I'll re-add them, but to be clear, that worked before too so I won't be able to confirm soon if this is working or not. I'l try to queue some new files so there is better chance to fail (or hopefully not fail).

Thanks.

**Comment by kepi** [comment]
So far nothing failed, but lets wait couple days. Everything failed before just re-added and so far it looks good.

If there is somebody as lazy as me (who rather spent 20 minutes writing code then 5 minutes clicking mouse), here is super dirty snippet to readd everything from collector to queue as new packages (leaving it in collector). Only one link per package supposed.

```python
payload_login = {'username': 'your user', 'password': 'superpassword....'}
requests.post('http://localhost:8000/api/login', data=payload_login, json=None, timeout=30 )
payload = {'session': rs.json()}

collector_data = requests.post('http://localhost:8000/api/getCollectorData', data=payload)
for package in collector_data.json():
   name = urllib.parse.quote_plus(json.dumps(package['name']))
   links = urllib.parse.quote_plus(json.dumps([package['links'][0]['url']]))
   url = 'http://localhost:8000/api/addPackage?name={}&links={}'.format(name, links)
   requests.post(url.format(name, links), data=payload)
```

**Comment by kepi** [comment]
Ok, this one is new - never saw it before. I guess it might be related to the change, but let me know if new issue is preferred.

Magnet URL seems OK to me, not sure what should missing parameter be.

```
24.03.2021 16:30:26 INFO      Decrypting starts: urnbtih1a2b3cc0c34e8d9cfbc12b1a19d435ba2ab1170bd
24.03.2021 16:30:26 DEBUG     CRYPTER RealdebridComTorrent[866]: Plugin version: 0.14
24.03.2021 16:30:26 DEBUG     CRYPTER RealdebridComTorrent[866]: Plugin status: testing
24.03.2021 16:30:26 WARNING   CRYPTER RealdebridComTorrent[866]: Plugin may be unstable
24.03.2021 16:30:26 DEBUG     CRYPTER RealdebridComTorrent[866]: Config option `use_premium` not found, use default `True`
24.03.2021 16:30:26 INFO      CRYPTER RealdebridComTorrent[866]: Grabbing link info...
24.03.2021 16:30:26 DEBUG     CRYPTER RealdebridComTorrent[866]: Link info: {'status': 7, 'hash': {}, 'name': u'urnbtih1a2b3cc0c34e8d9cfbc12b1a19d435ba2ab1170bd', 'url': u'magnet:?xt=urn:btih:1a2b3cc0c34e8d9cfbc12b1a19d435ba2ab1170bd&dn=Yet.Another.File&tr=http://tracker.trackerfix.com:80/announce&tr=udp://9.rarbg.me:2710&tr=udp://9.rarbg.to:2710&tr=udp://open.demonii.com:1337/announce', 'pattern': {}, 'size': 0}
24.03.2021 16:30:26 DEBUG     CRYPTER RealdebridComTorrent[866]: Previous link info: {}
24.03.2021 16:30:26 INFO      CRYPTER RealdebridComTorrent[866]: Link name: urnbtih1a2b3cc0c34e8d9cfbc12b1a19d435ba2ab1170bd
24.03.2021 16:30:26 INFO      CRYPTER RealdebridComTorrent[866]: Link size: N/D
24.03.2021 16:30:26 INFO      CRYPTER RealdebridComTorrent[866]: Link status: starting
24.03.2021 16:30:26 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
24.03.2021 16:30:26 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
24.03.2021 16:30:26 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
24.03.2021 16:30:26 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36`
24.03.2021 16:30:26 INFO      CRYPTER RealdebridComTorrent[866]: Processing url: magnet:?xt=urn:btih:1a2b3cc0c34e8d9cfbc12b1a19d435ba2ab1170bd&dn=Yet.Another.File&tr=http://tracker.trackerfix.com:80/announce&tr=udp://9.rarbg.me:2710&tr=udp://9.rarbg.to:2710&tr=udp://open.demonii.com:1337/announce
24.03.2021 16:30:26 DEBUG     CRYPTER RealdebridComTorrent[866]: LOAD URL https://api.real-debrid.com/rest/1.0/torrents/addMagnet | redirect=True | cookies=True | get={'auth_token': u'mytoken'} | req=None | decode=True | multipart=False | post={'magnet': u'magnet:?xt=urn:btih:1a2b3cc0c34e8d9cfbc12b1a19d435ba2ab1170bd&dn=Yet.Another.File&tr=http://tracker.trackerfix.com:80/announce&tr=udp://9.rarbg.me:2710&tr=udp://9.rarbg.to:2710&tr=udp://open.demonii.com:1337/announce'} | ref=True | just_header=False
24.03.2021 16:30:27 DEBUG     CRYPTER RealdebridComTorrent[866]: LOAD URL https://api.real-debrid.com/rest/1.0/torrents/info/TTXCZ77ENNIQA | redirect=True | cookies=True | get={'auth_token': u'mytoken'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
24.03.2021 16:30:27 DEBUG     CRYPTER RealdebridComTorrent[866]: LOAD URL https://api.real-debrid.com/rest/1.0/torrents/selectFiles/TTXCZ77ENNIQA | redirect=True | cookies=True | get={'auth_token': u'mytoken'} | req=None | decode=True | multipart=False | post={'files': ''} | ref=True | just_header=False
24.03.2021 16:30:27 ERROR     Decrypting failed: urnbtih1a2b3cc0c34e8d9cfbc12b1a19d435ba2ab1170bd | parameter_missing

```

This is first error in about 30 downloaded packages.

**Comment by GammaC0de** [comment]
As you can see in the log, the URL is handled by RealdebridComTorrent so this issue is unrelated, probably you have reach the server limit or other server side error.

Please keep updating on your progress.

**Comment by kepi** [comment]
No error in last 5 days. I hope it is solved so I'm closing this. If there will something new, I'll re-open or create new related issue.

Thanks!
