### ISSUE TITLE
Error while processing content unencoding: incorrect header check

### ISSUE THREAD

**Issue by coffeepl** [pyload/pyload#3924]
Hi everyone!
First of all I would like to say that I find pyload as a great tool! Thanks a lot for multiarch support!
Unfortunately, downloading files from private sites (read as protected by http basic authentication) is a real pain...

Getting to the heart of the matter.
Address scheme of the url is as follows:
`https://serverid.domain.com/userId/download/filename.extension`

Of course, We need to provide login credentials to have access to this site.

So I followed these steps:
**1) HTTP basic authentication URL with “@” in password**
I tried to download file from path:
`https://user:password@serverid.domain.com/userId/download/filename.extension`

The only result I got was the following error:
```
43	03.04.2021 00:21:18	INFO	Download starts: https://serverid.domain.com/userId/download/file.srt
44	03.04.2021 00:21:18	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
45	03.04.2021 00:21:18	DEBUG	ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
46	03.04.2021 00:21:18	DEBUG	ADDON UserAgentSwitcher: Setting maximum redirections to 10
47	03.04.2021 00:21:18	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
48	03.04.2021 00:21:18	DEBUG	HOSTER BasePlugin[1]: Plugin version: 0.52
49	03.04.2021 00:21:18	DEBUG	HOSTER BasePlugin[1]: Plugin status: testing
50	03.04.2021 00:21:18	WARNING	HOSTER BasePlugin[1]: Plugin may be unstable
51	03.04.2021 00:21:18	DEBUG	HOSTER BasePlugin[1]: Config option `use_premium` not found, use default `True`
52	03.04.2021 00:21:18	INFO	HOSTER BasePlugin[1]: Grabbing link info...
53	03.04.2021 00:21:18	DEBUG	HOSTER BasePlugin[1]: Link info: {'status': 7, 'hash': {}, 'name': u'file.srt', 'url': u'https://serverid.domain.com/userId/download/file.srt', 'pattern': {}, 'size': 0}
54	03.04.2021 00:21:18	DEBUG	HOSTER BasePlugin[1]: Previous link info: {}
55	03.04.2021 00:21:18	INFO	HOSTER BasePlugin[1]: Link name: file.srt
56	03.04.2021 00:21:18	INFO	HOSTER BasePlugin[1]: Link size: N/D
57	03.04.2021 00:21:18	INFO	HOSTER BasePlugin[1]: Link status: starting
58	03.04.2021 00:21:18	INFO	HOSTER BasePlugin[1]: Processing url: https://serverid.domain.com/userId/download/file.srt
59	03.04.2021 00:21:18	DEBUG	HOSTER BasePlugin[1]: DOWNLOAD URL https://serverid.domain.com/userId/download/file.srt | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=False
60	03.04.2021 00:21:19	DEBUG	Chunked with range 0-12291
61	03.04.2021 00:21:19	DEBUG	Chunked with range 12291-24582
62	03.04.2021 00:21:19	DEBUG	Chunked with range 24582-
63	03.04.2021 00:21:19	DEBUG	Chunk 3 failed: (61, 'Error while processing content unencoding: incorrect header check')
64	03.04.2021 00:21:19	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
65	03.04.2021 00:21:19	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
66	03.04.2021 00:21:19	DEBUG	pycurl exception 61: Error while processing content unencoding: incorrect header check
67	03.04.2021 00:21:19	ERROR	pycurl error 61: Error while processing content unencoding: incorrect header check
68	?	?	Traceback (most recent call last):
69	?	?	File "/app/pyload/module/PluginThread.py", line 189, in run
70	?	?	pyfile.plugin.preprocessing(self)
71	?	?	File "/app/pyload/module/plugins/internal/Base.py", line 291, in preprocessing
72	?	?	return self._process(*args, **kwargs)
73	?	?	File "/app/pyload/module/plugins/internal/Hoster.py", line 118, in _process
74	?	?	self.process(self.pyfile)
75	?	?	File "/app/pyload/module/plugins/hoster/Http.py", line 38, in process
76	?	?	self.download(url, ref=False, disposition=True)
77	?	?	File "/app/pyload/module/plugins/internal/Hoster.py", line 308, in download
78	?	?	disposition, resume, chunks)
79	?	?	File "/app/pyload/module/plugins/internal/Hoster.py", line 237, in _download
80	?	?	status_notify=self._on_notification, disposition=disposition)
81	?	?	File "/app/pyload/module/network/Browser.py", line 89, in httpDownload
82	?	?	name = self.dl.download(chunks, resume)
83	?	?	File "/app/pyload/module/network/HTTPDownload.py", line 130, in download
84	?	?	self._download(chunks, resume)
85	?	?	File "/app/pyload/module/network/HTTPDownload.py", line 263, in _download
86	?	?	raise ex
87	?	?	error: (61, 'Error while processing content unencoding: incorrect header check')
```
As up mentioned: the file's extension is ".srt"

Ok, let's go to the another option.

**2) Providing login credentials in "Password" tab**
![tlB1PF3](https://user-images.githubusercontent.com/22817448/113459267-3fc48580-9415-11eb-944c-f9133f880203.png)

Same result as above:
```
89	03.04.2021 00:21:19	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: filename.srt (pid:1)
90	03.04.2021 00:21:19	INFO	ADDON UnSkipOnFail: No duplicates found
91	03.04.2021 00:21:19	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
92	03.04.2021 00:21:19	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
93	03.04.2021 00:21:19	DEBUG	All downloads processed
94	03.04.2021 00:36:34	DEBUG	ADDON ExternalScripts: No script found under folder `package_deleted`
95	03.04.2021 00:38:13	INFO	Added package checkv2 containing 1 links
96	03.04.2021 00:38:14	INFO	Download starts: https://serverid.domain.com/userId/download/file.srt
97	03.04.2021 00:38:14	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
98	03.04.2021 00:38:14	DEBUG	ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
99	03.04.2021 00:38:14	DEBUG	ADDON UserAgentSwitcher: Setting maximum redirections to 10
100	03.04.2021 00:38:14	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
101	03.04.2021 00:38:14	DEBUG	HOSTER BasePlugin[2]: Plugin version: 0.52
102	03.04.2021 00:38:14	DEBUG	HOSTER BasePlugin[2]: Plugin status: testing
103	03.04.2021 00:38:14	WARNING	HOSTER BasePlugin[2]: Plugin may be unstable
104	03.04.2021 00:38:14	DEBUG	HOSTER BasePlugin[2]: Config option `use_premium` not found, use default `True`
105	03.04.2021 00:38:14	INFO	HOSTER BasePlugin[2]: Grabbing link info...
106	03.04.2021 00:38:14	DEBUG	HOSTER BasePlugin[2]: Link info: {'status': 7, 'hash': {}, 'name': u'filename.srt', 'url': u'https://serverid.domain.com/userId/download/file.srt', 'pattern': {}, 'size': 0}
107	03.04.2021 00:38:14	DEBUG	HOSTER BasePlugin[2]: Previous link info: {}
108	03.04.2021 00:38:14	INFO	HOSTER BasePlugin[2]: Link name: filename.srt
109	03.04.2021 00:38:14	INFO	HOSTER BasePlugin[2]: Link size: N/D
110	03.04.2021 00:38:14	INFO	HOSTER BasePlugin[2]: Link status: starting
111	03.04.2021 00:38:14	INFO	HOSTER BasePlugin[2]: Processing url: https://serverid.domain.com/userId/download/file.srt
112	03.04.2021 00:38:14	DEBUG	HOSTER BasePlugin[2]: DOWNLOAD URL https://serverid.domain.com/userId/download/file.srt | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=False
113	03.04.2021 00:38:15	DEBUG	Chunk 1 failed: Bad server response: 401 Unauthorized
114	03.04.2021 00:38:15	DEBUG	HOSTER BasePlugin[2]: Auth required | Received HTTP status code: 401
115	03.04.2021 00:38:15	DEBUG	HOSTER BasePlugin[2]: DOWNLOAD URL https://serverid.domain.com/userId/download/file.srt | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=False
116	03.04.2021 00:38:15	DEBUG	Chunked with range 0-12291
117	03.04.2021 00:38:15	DEBUG	Chunked with range 12291-24582
118	03.04.2021 00:38:15	DEBUG	Chunked with range 24582-
119	03.04.2021 00:38:16	DEBUG	Chunk 2 failed: (61, 'Error while processing content unencoding: incorrect header check')
120	03.04.2021 00:38:16	DEBUG	Chunk 3 failed: (61, 'Error while processing content unencoding: incorrect header check')
121	03.04.2021 00:38:16	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
122	03.04.2021 00:38:16	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
123	03.04.2021 00:38:16	DEBUG	pycurl exception 61: Error while processing content unencoding: incorrect header check
124	03.04.2021 00:38:16	ERROR	pycurl error 61: Error while processing content unencoding: incorrect header check
125	?	?	Traceback (most recent call last):
126	?	?	File "/app/pyload/module/PluginThread.py", line 189, in run
127	?	?	pyfile.plugin.preprocessing(self)
128	?	?	File "/app/pyload/module/plugins/internal/Base.py", line 291, in preprocessing
129	?	?	return self._process(*args, **kwargs)
130	?	?	File "/app/pyload/module/plugins/internal/Hoster.py", line 118, in _process
131	?	?	self.process(self.pyfile)
132	?	?	File "/app/pyload/module/plugins/hoster/Http.py", line 38, in process
133	?	?	self.download(url, ref=False, disposition=True)
134	?	?	File "/app/pyload/module/plugins/internal/Hoster.py", line 308, in download
135	?	?	disposition, resume, chunks)
136	?	?	File "/app/pyload/module/plugins/internal/Hoster.py", line 237, in _download
137	?	?	status_notify=self._on_notification, disposition=disposition)
138	?	?	File "/app/pyload/module/network/Browser.py", line 89, in httpDownload
139	?	?	name = self.dl.download(chunks, resume)
140	?	?	File "/app/pyload/module/network/HTTPDownload.py", line 130, in download
141	?	?	self._download(chunks, resume)
142	?	?	File "/app/pyload/module/network/HTTPDownload.py", line 263, in _download
143	?	?	raise ex
144	?	?	error: (61, 'Error while processing content unencoding: incorrect header check')
145	03.04.2021 00:38:16	INFO	Debug Report written to debug_BasePlugin_03-04-2021_00-38-16.zip
146	03.04.2021 00:38:16	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: filename.srt (pid:2)
147	03.04.2021 00:38:16	INFO	ADDON UnSkipOnFail: No duplicates found
148	03.04.2021 00:38:16	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
149	03.04.2021 00:38:17	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
150	03.04.2021 00:38:17	DEBUG	All downloads processed
```

3) Adding "Http" account
![sw](https://user-images.githubusercontent.com/22817448/113459600-4ef80300-9416-11eb-9a78-6ef5d3d0a621.png)

And the result I've got is:
```
151	03.04.2021 00:48:17	INFO	ACCOUNT Http: Adding user `use******`...
152	03.04.2021 00:48:17	DEBUG	ACCOUNT Http: Reached login timeout for user `use*******`
153	03.04.2021 00:48:17	INFO	ACCOUNT Http: Login user `use******`...
154	03.04.2021 00:48:17	INFO	ACCOUNT Http: Grabbing account info for user `use*******`...
155	03.04.2021 00:48:17	DEBUG	ACCOUNT Http: Account info for user `use******`: {'login': {'timestamp': 1617403697.244156, 'password': '**********', 'valid': True}, 'data': {'premium': None, 'plugin': , 'trafficleft': None, 'maxtraffic': None, 'validuntil': None, 'login': 'use******', 'type': 'Http', 'options': {'limitDL': ['0']}}}
156	03.04.2021 00:49:10	INFO	Added package checkv3 containing 1 links
157	03.04.2021 00:49:14	INFO	Download starts: https://serverId.domain.com/userId/download/file.srt
158	03.04.2021 00:49:14	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
159	03.04.2021 00:49:14	DEBUG	ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
160	03.04.2021 00:49:14	DEBUG	ADDON UserAgentSwitcher: Setting maximum redirections to 10
161	03.04.2021 00:49:14	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
162	03.04.2021 00:49:14	DEBUG	HOSTER BasePlugin[3]: Plugin version: 0.52
163	03.04.2021 00:49:14	DEBUG	HOSTER BasePlugin[3]: Plugin status: testing
164	03.04.2021 00:49:14	WARNING	HOSTER BasePlugin[3]: Plugin may be unstable
165	03.04.2021 00:49:14	DEBUG	HOSTER BasePlugin[3]: Config option `use_premium` not found, use default `True`
166	03.04.2021 00:49:14	INFO	ACCOUNT Http: Grabbing account info for user `use******`...
167	03.04.2021 00:49:14	DEBUG	ACCOUNT Http: Account info for user `use******`: {'login': {'timestamp': 1617403697.244156, 'password': '**********', 'valid': True}, 'data': {'premium': None, 'plugin': , 'trafficleft': None, 'maxtraffic': None, 'validuntil': None, 'login': 'use******', 'type': 'Http', 'options': {'limitDL': ['0']}}}
168	03.04.2021 00:49:14	INFO	HOSTER BasePlugin[3]: Grabbing link info...
169	03.04.2021 00:49:14	DEBUG	HOSTER BasePlugin[3]: Link info: {'status': 7, 'hash': {}, 'name': u'filename.srt', 'url': u'https://ser*****.domain.com/userId/download/file.srt', 'pattern': {}, 'size': 0}
170	03.04.2021 00:49:14	DEBUG	HOSTER BasePlugin[3]: Previous link info: {}
171	03.04.2021 00:49:14	INFO	HOSTER BasePlugin[3]: Link name: filename.srt
172	03.04.2021 00:49:14	INFO	HOSTER BasePlugin[3]: Link size: N/D
173	03.04.2021 00:49:14	INFO	HOSTER BasePlugin[3]: Link status: starting
174	03.04.2021 00:49:14	INFO	HOSTER BasePlugin[3]: Processing url: https://ser*****.domain.com/userId/download/file.srt
175	03.04.2021 00:49:14	DEBUG	HOSTER BasePlugin[3]: DOWNLOAD URL https://ser*****.domain.com/userId/download/file.srt | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=False
176	03.04.2021 00:49:14	DEBUG	Chunk 1 failed: Bad server response: 401 Unauthorized
177	03.04.2021 00:49:14	DEBUG	HOSTER BasePlugin[3]: Auth required | Received HTTP status code: 401
178	03.04.2021 00:49:14	DEBUG	HOSTER BasePlugin[3]: Logging on to use******
179	03.04.2021 00:49:14	DEBUG	HOSTER BasePlugin[3]: DOWNLOAD URL https://ser*****.domain.com/userId/download/file.srt | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=False
180	03.04.2021 00:49:15	DEBUG	Chunked with range 0-12291
181	03.04.2021 00:49:15	DEBUG	Chunked with range 12291-24582
182	03.04.2021 00:49:15	DEBUG	Chunked with range 24582-
183	03.04.2021 00:49:15	DEBUG	Chunk 2 failed: (61, 'Error while processing content unencoding: incorrect header check')
184	03.04.2021 00:49:15	DEBUG	Chunk 3 failed: (61, 'Error while processing content unencoding: incorrect header check')
185	03.04.2021 00:49:15	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
186	03.04.2021 00:49:15	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
187	03.04.2021 00:49:15	DEBUG	pycurl exception 61: Error while processing content unencoding: incorrect header check
188	03.04.2021 00:49:15	ERROR	pycurl error 61: Error while processing content unencoding: incorrect header check
189	?	?	Traceback (most recent call last):
190	?	?	File "/app/pyload/module/PluginThread.py", line 189, in run
191	?	?	pyfile.plugin.preprocessing(self)
192	?	?	File "/app/pyload/module/plugins/internal/Base.py", line 291, in preprocessing
193	?	?	return self._process(*args, **kwargs)
194	?	?	File "/app/pyload/module/plugins/internal/Hoster.py", line 118, in _process
195	?	?	self.process(self.pyfile)
196	?	?	File "/app/pyload/module/plugins/hoster/Http.py", line 38, in process
197	?	?	self.download(url, ref=False, disposition=True)
198	?	?	File "/app/pyload/module/plugins/internal/Hoster.py", line 308, in download
199	?	?	disposition, resume, chunks)
200	?	?	File "/app/pyload/module/plugins/internal/Hoster.py", line 237, in _download
201	?	?	status_notify=self._on_notification, disposition=disposition)
202	?	?	File "/app/pyload/module/network/Browser.py", line 89, in httpDownload
203	?	?	name = self.dl.download(chunks, resume)
204	?	?	File "/app/pyload/module/network/HTTPDownload.py", line 130, in download
205	?	?	self._download(chunks, resume)
206	?	?	File "/app/pyload/module/network/HTTPDownload.py", line 263, in _download
207	?	?	raise ex
208	?	?	error: (61, 'Error while processing content unencoding: incorrect header check')
209	03.04.2021 00:49:15	INFO	Debug Report written to debug_BasePlugin_03-04-2021_00-49-15.zip
210	03.04.2021 00:49:15	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: filename.srt (pid:3)
211	03.04.2021 00:49:15	INFO	ADDON UnSkipOnFail: No duplicates found
212	03.04.2021 00:49:15	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
213	03.04.2021 00:49:16	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
214	03.04.2021 00:49:16	DEBUG	All downloads processed
```

**Additional references**
**Python:** `2.7.18 (default, May 3 2020, 20:31:45) [GCC 9.2.0]`
**OS:** `posix linux2 Linux 5b381bc86527 4.9.113 #1 SMP PREEMPT Wed Mar 24 07:02:37 CET 2021 aarch64`
**pyLoad version:** `0.4.20`
Docker compose snippet
```
---
version: "2"
services:
  pyload:
    image: ghcr.io/linuxserver/pyload:arm64v8-latest
    container_name: pyload
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /storage/docker/pyload/config:/config
      - /storage/docker/pyload/downloads:/downloads
    ports:
      - 8000:8000
      - 7227:7227
    restart: unless-stopped
```

**systemCheck.py's output:**
```
#####   System Information   #####

('Platform:', 'linux2')
('Operating System:', 'posix')
('Python:', '2.7.18 (default, May  3 2020, 20:31:45) [GCC 9.2.0]\n')
('pycurl:', 'PycURL/7.43.0.5 libcurl/7.67.0 OpenSSL/1.1.1k zlib/1.2.11 nghttp2/1.40.0')
('py-crypto:', '2.6.1')
/usr/lib/python2.7/site-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
('OpenSSL:', '20.0.1')
('image library:', 'missing')
('pyqt:', 'missing')
('JS engine:', 'node')


#####   System Status   #####

##  pyLoadCore  ##
No Problems detected, pyLoadCore should work fine.

##  pyLoadGui  ##
The system check has detected some errors:

GUI won't work without pyqt4 !!

##  Webinterface  ##
No Problems detected, Webinterface should work fine.

Possible improvements for webinterface:

Install Flup to use FastCGI or optional webservers.
```

If additional data is required, please write.

Thanks in advance for helping me solve the problem.

Cheers!

**Comment by GammaC0de** [comment]
> Unfortunately, downloading files from private sites (read as protected by http basic authentication) is a real pain...

Actually, this issue is unrelated to http authentication.
It is related to http gzip compression and chunked downloads:
It is probably because of bad server configuration.
> pycurl error 61: Error while processing content unencoding: incorrect header check

You have three options:
1. Disabling gzip (and probably deflate also) support (https://github.com/pyload/pyload/blob/stable/module/network/HTTPRequest.py#L121) should solve this issue
2. Disable chunked support for HTTP (BasePlugin): https://github.com/pyload/pyload/blob/stable/module/plugins/hoster/BasePlugin.py#L20
3. Disable chunked download globally via pyLoad's configuration: Config -> General -> Download -> Max connections for one download

options 1 and 2 involves editing source code

**Comment by coffeepl** [comment]
Disabling gzip & deflate solved my problem.

Thanks a lot for the support.
