### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by RDKRACZ** [pyload/pyload#3934]
```
pip install --pre pyload-ng[all]
Collecting pyload-ng[all]
  Using cached pyload_ng-0.5.0a9.dev806-py3-none-any.whl (1.3 MB)
Requirement already satisfied: cryptography~=3.0 in /usr/lib/python3/dist-packages (from pyload-ng[all]) (3.0)
Collecting semver~=2.10
  Downloading semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting Js2Py~=0.7
  Using cached Js2Py-0.71-py3-none-any.whl (1.0 MB)
Collecting filetype~=1.0
  Downloading filetype-1.0.7-py2.py3-none-any.whl (15 kB)
Collecting Flask~=1.1
  Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 1.1 MB/s 
Requirement already satisfied: setuptools>=38.3 in /usr/lib/python3/dist-packages (from pyload-ng[all]) (49.3.1)
Collecting Flask-Caching~=1.9
  Downloading Flask_Caching-1.10.1-py3-none-any.whl (34 kB)
Collecting pycurl~=7.43
  Using cached pycurl-7.43.0.6.tar.gz (222 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dyr205bp/pycurl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dyr205bp/pycurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vvxj4vsz
         cwd: /tmp/pip-install-dyr205bp/pycurl/
    Complete output (22 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-dyr205bp/pycurl/setup.py", line 236, in configure_unix
        p = subprocess.Popen((self.curl_config(), '--version'),
      File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dyr205bp/pycurl/setup.py", line 988, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-install-dyr205bp/pycurl/setup.py", line 649, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-install-dyr205bp/pycurl/setup.py", line 101, in __init__
        self.configure()
      File "/tmp/pip-install-dyr205bp/pycurl/setup.py", line 241, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by vuolter** [comment]
You need to install some dev libs to make pycurl working fine on your machine: https://stackoverflow.com/questions/23937933/could-not-run-curl-config-errno-2-no-such-file-or-directory-when-installing.

**Comment by UserX404** [comment]
I want to jump in with an other install issue.
Can please anyone give me a hint what's the problem here?

[/opt/bin] # pyload --userdir /opt/var/pyload --storagedir /share/Download/Pyload
[2021-05-02 23:36:45]  INFO                pyload  *** Welcome to pyLoad 0.5.0 ***
[2021-05-02 23:36:45]  DEBUG               pyload  Indexing plugins...
[2021-05-02 23:36:46]  INFO                pyload  Activated plugins: ClickNLoad, ExternalScripts, TORRENT, UnSkipOnFail, UserAgentSwitcher, XFileSharing
[2021-05-02 23:36:46]  INFO                pyload  Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, UpdateManager, WindowsPhoneNotify, XMPP
ModuleNotFoundError: No module named '_brotli'
Traceback (most recent call last):
  File "/opt/bin/pyload", line 8, in <module>
    sys.exit(main())
  File "/opt/lib/python3.9/site-packages/pyload/__main__.py", line 135, in main
    run(core_args, args.daemon)
  File "/opt/lib/python3.9/site-packages/pyload/__main__.py", line 119, in run
    pyload_core = Core(*core_args)
  File "/opt/lib/python3.9/site-packages/pyload/core/__init__.py", line 101, in __init__
    self._init_webserver()
  File "/opt/lib/python3.9/site-packages/pyload/core/__init__.py", line 160, in _init_webserver
    from pyload.webui.webserver_thread import WebServerThread
  File "/opt/lib/python3.9/site-packages/pyload/webui/webserver_thread.py", line 9, in <module>
    from .app import App
  File "/opt/lib/python3.9/site-packages/pyload/webui/app/__init__.py", line 18, in <module>
    from .extensions import EXTENSIONS, THEMES
  File "/opt/lib/python3.9/site-packages/pyload/webui/app/extensions.py", line 5, in <module>
    from flask_compress import Compress
  File "/opt/lib/python3.9/site-packages/flask_compress.py", line 14, in <module>
    import brotli
  File "/opt/lib/python3.9/site-packages/brotli.py", line 8, in <module>
    import _brotli
ModuleNotFoundError: No module named '_brotli'
[/opt/bin] # python -m pip install brotli
Requirement already satisfied: brotli in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.9/site-packages (1.0.9)
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
[/opt/bin] # pyload --userdir /opt/var/pyload --storagedir /share/Download/Pyload
[2021-05-02 23:39:53]  INFO                pyload  *** Welcome to pyLoad 0.5.0 ***
[2021-05-02 23:39:53]  DEBUG               pyload  Indexing plugins...
[2021-05-02 23:39:54]  INFO                pyload  Activated plugins: ClickNLoad, ExternalScripts, TORRENT, UnSkipOnFail, UserAgentSwitcher, XFileSharing
[2021-05-02 23:39:54]  INFO                pyload  Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, UpdateManager, WindowsPhoneNotify, XMPP
ModuleNotFoundError: No module named '_brotli'
Traceback (most recent call last):
  File "/opt/bin/pyload", line 8, in <module>
    sys.exit(main())
  File "/opt/lib/python3.9/site-packages/pyload/__main__.py", line 135, in main
    run(core_args, args.daemon)
  File "/opt/lib/python3.9/site-packages/pyload/__main__.py", line 119, in run
    pyload_core = Core(*core_args)
  File "/opt/lib/python3.9/site-packages/pyload/core/__init__.py", line 101, in __init__
    self._init_webserver()
  File "/opt/lib/python3.9/site-packages/pyload/core/__init__.py", line 160, in _init_webserver
    from pyload.webui.webserver_thread import WebServerThread
  File "/opt/lib/python3.9/site-packages/pyload/webui/webserver_thread.py", line 9, in <module>
    from .app import App
  File "/opt/lib/python3.9/site-packages/pyload/webui/app/__init__.py", line 18, in <module>
    from .extensions import EXTENSIONS, THEMES
  File "/opt/lib/python3.9/site-packages/pyload/webui/app/extensions.py", line 5, in <module>
    from flask_compress import Compress
  File "/opt/lib/python3.9/site-packages/flask_compress.py", line 14, in <module>
    import brotli
  File "/opt/lib/python3.9/site-packages/brotli.py", line 8, in <module>
    import _brotli
ModuleNotFoundError: No module named '_brotli'

**Comment by vuolter** [comment]
I think the problem here is the 3rd party package `brotli`, have a try with `pip install Brotli` but i suspect will fail on your platform @UserX404

**Comment by UserX404** [comment]
@vuolter
Please look in between the 2 start attempts.
Protli is already installed

**Comment by vuolter** [comment]
@UserX404 nevertheless looks to be something internal to the brotli package used by flask-compress in our webui, something related to the c binding of brotli, maybe not compiled for your platform.
Anyway i recommend to open a new issue for this.

**Comment by vuolter** [comment]
coming back to @RDKRACZ's question...

If you're under ubuntu/debian, first of all, try installing the binary package `libcurl4`:
```
sudo apt-get -y --no-install-recommends install libcurl4-openssl-dev
```

then install the PyPI package `PycURL` declaring openssl as wanted SSL backend:
```
pip install --install-option="--with-openssl" pycurl
```

then install pyLoad:
```
pip install --pre pylaod-ng
```

---

On macOS, use homebrew to do, actually, the same:
```
brew install openssl@1.1
```

then `PycURL`:

```
pip install --install-option="--with-openssl --openssl-dir=/usr/local/opt/openssl@1.1" pycurl
```

finally pyLoad.

**Comment by GammaC0de** [comment]
You are missing a shared library:
```
>> import _brotli
>>> _brotli.__file__
'C:\\Python38\\lib\\site-packages\\_brotli.cp38-win_amd64.pyd'
```

On windows this is `_brotli.cp38-win_amd64.pyd`.
This library seems to be a part of the pypi package.

From the logs, I guess you are using arm CPU. I could not find arm brotli package on pypi.

So I guess you'll have to build it yourself https://github.com/google/brotli
or open an issue and ask there.

**Comment by UserX404** [comment]
For reference:
seems my python installation couldn't load the *.so file but files are paced correctly
```
[/opt/lib/python3.9/site-packages] # ls | grep brotli
_brotli.cpython-39-x86_64-linux-gnu.so*
brotli.py
```
Solved my issue by try and error creating a symlink and reload config:
```
[/opt/lib/python3.9/site-packages] # ln -s _brotli.cpython-39-x86_64-linux-gnu.so _brotli.so
[/opt/lib/python3.9/site-packages] # ldconfig
```
