### ISSUE TITLE
Pyload fails to download multiple HTTP links

### ISSUE THREAD

**Issue by dcordb** [pyload/pyload#3969]
### Description

Pyload webui fails to download multiple HTTP links.

While testing pyload to download html links, I noticed that some http links fail, for example, try to download the following two links from pyload webui:

```
https://raw.githubusercontent.com/pyload/pyload/main/AUTHORS.md
https://raw.githubusercontent.com/pyload/pyload/main/LICENSE.md
```

I create a package and pasted these two links there, but pyload will fail to download both, for the second file I get the following error:

`pycurl.error: (61, 'Error while processing content unencoding: incorrect header check')`

### Debug log

```
[2021-05-29 08:54:30]  DEBUG               pyload  DOWNLOADER DefaultPlugin[2]: DOWNLOAD URL https://raw.githubusercontent.com/pyload/pyload/main/LICENSE.md | get={} | post={} | ref=False | cookies=True | disposition=True | resume=None | chunks=None
[2021-05-29 08:54:30]  DEBUG               pyload  Chunk 1 chunked with range 0-3950
[2021-05-29 08:54:30]  DEBUG               pyload  Chunk 2 chunked with range 3950-7900
[2021-05-29 08:54:30]  DEBUG               pyload  Chunk 3 chunked with range 7900-
[2021-05-29 08:54:30]  DEBUG               pyload  Chunk 1 download finished
[2021-05-29 08:54:30]  DEBUG               pyload  Chunk 2 failed: (61, 'Error while processing content unencoding: unknown compression method')
[2021-05-29 08:54:30]  DEBUG               pyload  Chunk 3 failed: (61, 'Error while processing content unencoding: incorrect header check')
[2021-05-29 08:54:30]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `download_processed`
[2021-05-29 08:54:30]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `package_processed`
Traceback (most recent call last):
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/core/threads/download_thread.py", line 56, in run
    pyfile.plugin.preprocessing(self)
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/plugins/base/hoster.py", line 300, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/plugins/base/downloader.py", line 104, in _process
    self.process(self.pyfile)
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/plugins/downloaders/Http.py", line 39, in process
    self.download(url, ref=False, disposition=True)
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/plugins/base/downloader.py", line 334, in download
    newname = self._download(
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/plugins/base/downloader.py", line 240, in _download
    newname = self.req.http_download(
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/core/network/browser.py", line 116, in http_download
    name = self.dl.download(chunks, resume)
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/core/network/http/http_download.py", line 133, in download
    self._download(chunks, resume)
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/core/network/http/http_download.py", line 277, in _download
    raise ex or Exception
pycurl.error: (61, 'Error while processing content unencoding: incorrect header check')
[2021-05-29 08:54:30]  WARNING             pyload  Download failed: LICENSE.md | (61, 'Error while processing content unencoding: incorrect header check')
Traceback (most recent call last):
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/core/threads/download_thread.py", line 56, in run
    pyfile.plugin.preprocessing(self)
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/plugins/base/hoster.py", line 300, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/plugins/base/downloader.py", line 104, in _process
    self.process(self.pyfile)
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/plugins/downloaders/Http.py", line 39, in process
    self.download(url, ref=False, disposition=True)
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/plugins/base/downloader.py", line 334, in download
    newname = self._download(
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/plugins/base/downloader.py", line 240, in _download
    newname = self.req.http_download(
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/core/network/browser.py", line 116, in http_download
    name = self.dl.download(chunks, resume)
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/core/network/http/http_download.py", line 133, in download
    self._download(chunks, resume)
  File "/home/dcordb/.pyenv/versions/pyload/lib/python3.9/site-packages/pyload/core/network/http/http_download.py", line 277, in _download
    raise ex or Exception
pycurl.error: (61, 'Error while processing content unencoding: incorrect header check')
[2021-05-29 08:54:30]  INFO                pyload  Debug Report written to /tmp/pyLoad/debug_DefaultPlugin_2021-05-29_08-54-30.zip
[2021-05-29 08:54:30]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `download_failed`
[2021-05-29 08:54:30]  INFO                pyload  ADDON UnSkipOnFail: Looking for skipped duplicates of: LICENSE.md (pid:1)
[2021-05-29 08:54:30]  INFO                pyload  ADDON UnSkipOnFail: No duplicates found
[2021-05-29 08:54:30]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `all_downloads_processed`
[2021-05-29 08:54:30]  DEBUG               pyload  All downloads processed
```

### Additional references

pyload is using the default plugin, I checked that the code that is doing the heavy lifting is at `pyload/core/network/http/http_download.py` on function `_download` at line 156. I checked this but it seems `pycurl` fails to download it.

This is pyload from `main` branch.

**Comment by GammaC0de** [comment]
For me it works fine,

What happens if you comment [http_request.py#L115](https://github.com/pyload/pyload/blob/main/src/pyload/core/network/http/http_request.py#L115) and 116?

**Comment by dcordb** [comment]
@GammaC0de ok, commenting this I can't reproduce it, but I tried something else: I put to download the following two links:

```
https://ftp.osuosl.org/pub/ubuntu-releases/18.04/ubuntu-18.04.5-desktop-amd64.iso.zsync
https://ftp.osuosl.org/pub/ubuntu-releases/18.04/ubuntu-18.04.5-live-server-amd64.iso.zsync
```
I can download both, but after checking the file content, I see that for the first one pyload downloaded an html 404 not found page:

```

**Comment by GammaC0de** [comment]
Thanks for notifying 🤗 , now fixed, please confirm.

**Comment by dcordb** [comment]
Yes, I can confirm it's fixed :ok_hand:. Btw thanks for creating pyload!
