### ISSUE TITLE
download from DDownload/DebridLink.fr fails: 'NoneType' object has no attribute 'get_info'

### ISSUE THREAD

**Issue by henrydatei** [pyload/pyload#3972]
### Description

I tried to download https://ddownload.com/s0ewcy6l3t8e via debrid-link.fr but I get an error: `'NoneType' object has no attribute 'get_info'`

### Debug log

```

01.06.2021 07:34:21 | INFO | Download starts: https://ddownload.com/s0ewcy6l3t8e
-- | -- | --
808 | 01.06.2021 07:34:21 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
809 | 01.06.2021 07:34:21 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
810 | 01.06.2021 07:34:21 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
811 | 01.06.2021 07:34:21 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
812 | 01.06.2021 07:34:21 | DEBUG | HOSTER DebridlinkFr[239]: DebridlinkFr \| Plugin version: 0.07
813 | 01.06.2021 07:34:21 | DEBUG | HOSTER DebridlinkFr[239]: DebridlinkFr \| Plugin status: testing
814 | 01.06.2021 07:34:21 | WARNING | HOSTER DebridlinkFr[239]: DebridlinkFr \| Plugin may be unstable
815 | 01.06.2021 07:34:21 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
816 | 01.06.2021 07:34:21 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
817 | 01.06.2021 07:34:21 | DEBUG | ADDON ExternalScripts: No script found under folder `package_failed`
818 | 01.06.2021 07:34:21 | WARNING | Download failed: https://ddownload.com/s0ewcy6l3t8e \| 'NoneType' object has no attribute 'get_info'
819 | ? | ? | Traceback (most recent call last):
820 | ? | ? | File "/usr/share/pyload/module/PluginThread.py", line 189, in run
821 | ? | ? | pyfile.plugin.preprocessing(self)
822 | ? | ? | File "/usr/share/pyload/module/plugins/internal/Base.py", line 291, in preprocessing
823 | ? | ? | return self._process(*args, **kwargs)
824 | ? | ? | File "/usr/share/pyload/module/plugins/internal/MultiHoster.py", line 78, in _process
825 | ? | ? | SimpleHoster._process(self, thread)
826 | ? | ? | File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 107, in _process
827 | ? | ? | self._setup()
828 | ? | ? | File "/usr/share/pyload/module/plugins/internal/Base.py", line 145, in _setup
829 | ? | ? | self.load_account() # @TODO: Move to PluginThread in 0.4.10
830 | ? | ? | File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 99, in load_account
831 | ? | ? | Base.load_account(self)
832 | ? | ? | File "/usr/share/pyload/module/plugins/internal/Base.py", line 179, in load_account
833 | ? | ? | self.account.choose()
834 | ? | ? | File "/usr/share/pyload/module/plugins/internal/misc.py", line 228, in new
835 | ? | ? | return fn(*args, **kwargs)
836 | ? | ? | File "/usr/share/pyload/module/plugins/internal/Account.py", line 406, in choose
837 | ? | ? | user = self.select()[0]
838 | ? | ? | File "/usr/share/pyload/module/plugins/internal/misc.py", line 228, in new
839 | ? | ? | return fn(*args, **kwargs)
840 | ? | ? | File "/usr/share/pyload/module/plugins/internal/Account.py", line 347, in select
841 | ? | ? | info = self.accounts[user]['plugin'].get_info()
842 | ? | ? | AttributeError: 'NoneType' object has no attribute 'get_info'
843 | 01.06.2021 07:34:21 | INFO | Debug Report written to debug_DdownloadCom_01-06-2021_07-34-21.zip
844 | 01.06.2021 07:34:21 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
845 | 01.06.2021 07:34:21 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: https://ddownload.com/s0ewcy6l3t8e (pid:11)
846 | 01.06.2021 07:34:21 | INFO | ADDON UnSkipOnFail: No duplicates found
847 | 01.06.2021 07:34:21 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
848 | 01.06.2021 07:34:21 | DEBUG | All downloads processed
```

**Comment by henrydatei** [comment]
It seems to be that this error only occurs when pyload has no connection to the internet...

**Comment by GammaC0de** [comment]
Why it has no connection?

**Comment by henrydatei** [comment]
It's weird and I think that's more a problem of the server pyload is running on than a problem of pyload. Every time this error occurs I'm not able to run a simple `ping 8.8.8.8`, I get the message that this operation is not allowed. Also a `curl google.com` returns that the address cannot be resolved. I think that's some sort of routing problem but I'm not an expert in network engineering. A simple restart of the whole server fixes all problems so I'm fine with it.

**Comment by GammaC0de** [comment]
OK, closing then.
