### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_pycurl)

### ISSUE THREAD

**Issue by Alyetama** [pyload/pyload#3991]
### Description

Running pyload after clean installation throws error `ImportError: dynamic module does not define module export function (PyInit_pycurl)`. I tried all the methods of installation described in `README.md` and had the same error.
### Debug log

```
$ pyload
[2021-07-04 10:44:34]  INFO                pyload  *** Welcome to pyLoad 0.5.0 ***
ImportError: dynamic module does not define module export function (PyInit_pycurl)
Traceback (most recent call last):
  File "/Users/me/miniforge3/bin/pyload", line 8, in <module>
    sys.exit(main())
  File "/Users/me/miniforge3/lib/python3.9/site-packages/pyload/__main__.py", line 135, in main
    run(core_args, args.daemon)
  File "/Users/me/miniforge3/lib/python3.9/site-packages/pyload/__main__.py", line 119, in run
    pyload_core = Core(*core_args)
  File "/Users/me/miniforge3/lib/python3.9/site-packages/pyload/core/__init__.py", line 98, in __init__
    self._init_network()
  File "/Users/me/miniforge3/lib/python3.9/site-packages/pyload/core/__init__.py", line 149, in _init_network
    from .network import request_factory
  File "/Users/me/miniforge3/lib/python3.9/site-packages/pyload/core/network/request_factory.py", line 6, in <module>
    from .browser import Browser
  File "/Users/me/miniforge3/lib/python3.9/site-packages/pyload/core/network/browser.py", line 7, in <module>
    from .http.http_download import HTTPDownload
  File "/Users/me/miniforge3/lib/python3.9/site-packages/pyload/core/network/http/http_download.py", line 7, in <module>
    import pycurl
ImportError: dynamic module does not define module export function (PyInit_pycurl)
```

Package version:
```
Name: pyload-ng
Version: 0.5.0b1.dev5
```

System information:
```
OS: macOS 11.4 20F71 arm64
Kernel: 20.5.0
CPU: Apple M1
GPU: Apple M1
```

**Comment by GammaC0de** [comment]
You have an issue with pycurl, this snippet should fail also
```
python3
>>> import pycurl
```

What OS are you running?

**Comment by Alyetama** [comment]
> You have an issue with pycurl installation, this snippet should fail also:
> 
> ```
> python3
> >>> import pycurl
> ```
> 
> What OS are you running?

Apple M1 macOS (Big Sur).

**Comment by GammaC0de** [comment]
maybe this can help https://gist.github.com/vidakDK/de86d751751b355ed3b26d69ecdbdb99

**Comment by Alyetama** [comment]
> maybe this can help [gist.github.com/vidakDK/de86d751751b355ed3b26d69ecdbdb99](https://gist.github.com/vidakDK/de86d751751b355ed3b26d69ecdbdb99)

I tried that but I still see the same error...
