### ISSUE TITLE
pycurl import error

### ISSUE THREAD

**Issue by bl4z3it** [pyload/pyload#4015]
### Description

I installed pyload on Ubuntu 20.04 LTS with pip install --pre pyload-ng[all].
When executing "pyload" I get this import error:

### Debug log

[2021-09-11 14:48:36]  INFO                pyload  *** Welcome to pyLoad 0.5.0 ***
ImportError: pycurl: libcurl link-time ssl backends (gnutls) do not include compile-time ssl backend (nss)
Traceback (most recent call last):
  File "/home/user/.local/bin/pyload", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/pyload/__main__.py", line 135, in main
    run(core_args, args.daemon)
  File "/home/user/.local/lib/python3.8/site-packages/pyload/__main__.py", line 119, in run
    pyload_core = Core(*core_args)
  File "/home/user/.local/lib/python3.8/site-packages/pyload/core/__init__.py", line 98, in __init__
    self._init_network()
  File "/home/user/.local/lib/python3.8/site-packages/pyload/core/__init__.py", line 149, in _init_network
    from .network import request_factory
  File "/home/user/.local/lib/python3.8/site-packages/pyload/core/network/request_factory.py", line 6, in <module>
    from .browser import Browser
  File "/home/user/.local/lib/python3.8/site-packages/pyload/core/network/browser.py", line 7, in <module>
    from .http.http_download import HTTPDownload
  File "/home/user/.local/lib/python3.8/site-packages/pyload/core/network/http/http_download.py", line 7, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backends (gnutls) do not include compile-time ssl backend (nss)

### Additional references

I tried reinstalling pycurl like this, but it did not make any difference. How do I fix this?

pip uninstall pycurl
export PYCURL_SSL_LIBRARY=nss
pip install --compile --install-option="--with-nss" --no-cache-dir pycurl

**Comment by bl4z3it** [comment]
Allright, I fixed it myself: 
I installed the libcurl dev package
`sudo apt-get install -y libcurl4-nss-dev`
and then told pycurl which ssl library to use, correct me if im wrong
`export PYCURL_SSL_LIBRARY=nss`
