### ISSUE TITLE
API AddPackage not working

### ISSUE THREAD

**Issue by ethernity** [pyload/pyload#4037]
### Description

I'm using pyLoad for a while. Now I switched to pyLoad ng.  I have a LinkGrabber written in Python which uses the API to add Packages. Nowadays it doesnt work anymore.  I'm sending it via the requests package using the post method:
```
def sendFile(self,link):
        payload={'username':self.username,'password':self.password}
        with requests.session() as s: 
            r=s.post("http://"+self.char.pyLoadAdress+":"+str(self.char.pyLoadPort)+'/api/login', data=payload)
            print(r.text)
            payload={'name':self.char.getname(link),'links':[link]}
            payloadJSON = {k: json.dumps(v) for k, v in payload.items()}
            r = s.post("http://"+self.char.pyLoadAdress+":"+str(self.char.pyLoadPort)+'/api/addPackage', data=payloadJSON)
            r.close()
```

### Debug log

This is the error I get in pyLoad
```
<html><body>
<!--StartFragment-->

1714 | 2021-11-11 21:44:30 | DEBUG | pyload.webui | Object of type AttributeError is not JSON serializable
-- | -- | -- | -- | --
1715 | ? | ? | ? | Traceback (most recent call last):
1716 | ? | ? | ? | File "/home/xbian/.local/lib/python3.9/site-packages/pyload/webui/app/blueprints/api_blueprint.py", line 44, in rpc
1717 | ? | ? | ? | response = call_api(func, *args, **kwargs)
1718 | ? | ? | ? | File "/home/xbian/.local/lib/python3.9/site-packages/pyload/webui/app/blueprints/api_blueprint.py", line 58, in call_api
1719 | ? | ? | ? | result = getattr(api, func)(
1720 | ? | ? | ? | AttributeError: 'Api' object has no attribute 'addPackage'
1721 | ? | ? | ? |  
1722 | ? | ? | ? | During handling of the above exception, another exception occurred:
1723 | ? | ? | ? |  
1724 | ? | ? | ? | Traceback (most recent call last):
1725 | ? | ? | ? | File "/home/xbian/.local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
1726 | ? | ? | ? | rv = self.dispatch_request()
1727 | ? | ? | ? | File "/home/xbian/.local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
1728 | ? | ? | ? | return self.view_functions[rule.endpoint](**req.view_args)
1729 | ? | ? | ? | File "/home/xbian/.local/lib/python3.9/site-packages/pyload/webui/app/blueprints/api_blueprint.py", line 46, in rpc
1730 | ? | ? | ? | response = jsonify(error=exc, traceback=traceback.format_exc()), 500
1731 | ? | ? | ? | File "/home/xbian/.local/lib/python3.9/site-packages/flask/json/__init__.py", line 370, in jsonify
1732 | ? | ? | ? | dumps(data, indent=indent, separators=separators) + "\n",
1733 | ? | ? | ? | File "/home/xbian/.local/lib/python3.9/site-packages/flask/json/__init__.py", line 211, in dumps
1734 | ? | ? | ? | rv = _json.dumps(obj, **kwargs)
1735 | ? | ? | ? | File "/home/xbian/.local/lib/python3.9/site-packages/simplejson/__init__.py", line 398, in dumps
1736 | ? | ? | ? | return cls(
1737 | ? | ? | ? | File "/home/xbian/.local/lib/python3.9/site-packages/simplejson/encoder.py", line 296, in encode
1738 | ? | ? | ? | chunks = self.iterencode(o, _one_shot=True)
1739 | ? | ? | ? | File "/home/xbian/.local/lib/python3.9/site-packages/simplejson/encoder.py", line 378, in iterencode
1740 | ? | ? | ? | return _iterencode(o, 0)
1741 | ? | ? | ? | File "/home/xbian/.local/lib/python3.9/site-packages/pyload/webui/app/helpers.py", line 18, in default
1742 | ? | ? | ? | return super().default(obj)
1743 | ? | ? | ? | File "/home/xbian/.local/lib/python3.9/site-packages/flask/json/__init__.py", line 100, in default
1744 | ? | ? | ? | return _json.JSONEncoder.default(self, o)
1745 | ? | ? | ? | File "/home/xbian/.local/lib/python3.9/site-packages/simplejson/encoder.py", line 272, in default
1746 | ? | ? | ? | raise TypeError('Object of type %s is not JSON serializable' %
1747 | ? | ? | ? | TypeError: Object of type AttributeError is not JSON serializable

<!--EndFragment-->
</body>
</html>
```

**Comment by GammaC0de** [comment]
Try using `add_package` instead of `addPackage`

**Comment by francesco-plt** [comment]
I have the same issue without legacy decorators:
```
[2022-02-21 21:42:01]  DEBUG         pyload.webui  Object of type SyntaxError is not JSON serializable
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/pyload/webui/app/blueprints/api_blueprint.py", line 44, in rpc
    response = call_api(func, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/pyload/webui/app/blueprints/api_blueprint.py", line 60, in call_api
    **{x: literal_eval(y) for x, y in kwargs.items()},
  File "/opt/homebrew/lib/python3.9/site-packages/pyload/webui/app/blueprints/api_blueprint.py", line 60, in <dictcomp>
    **{x: literal_eval(y) for x, y in kwargs.items()},
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    http://www.easybytez.com/restoftheurl
        ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/homebrew/lib/python3.9/site-packages/pyload/webui/app/blueprints/api_blueprint.py", line 46, in rpc
    response = jsonify(error=exc, traceback=traceback.format_exc()), 500
  File "/opt/homebrew/lib/python3.9/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/opt/homebrew/lib/python3.9/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/simplejson/__init__.py", line 398, in dumps
    return cls(
  File "/opt/homebrew/lib/python3.9/site-packages/simplejson/encoder.py", line 298, in encode
    chunks = list(chunks)
  File "/opt/homebrew/lib/python3.9/site-packages/simplejson/encoder.py", line 704, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/opt/homebrew/lib/python3.9/site-packages/simplejson/encoder.py", line 658, in _iterencode_dict
    for chunk in chunks:
  File "/opt/homebrew/lib/python3.9/site-packages/simplejson/encoder.py", line 724, in _iterencode
    o = _default(o)
  File "/opt/homebrew/lib/python3.9/site-packages/pyload/webui/app/helpers.py", line 18, in default
    return super().default(obj)
  File "/opt/homebrew/lib/python3.9/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/opt/homebrew/lib/python3.9/site-packages/simplejson/encoder.py", line 272, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type SyntaxError is not JSON serializable
127.0.0.1 - - [21/Feb/2022 21:42:01] "POST /api/generate_packages HTTP/1.1" 500 -
```

**Comment by GammaC0de** [comment]
@francesco-plt Can you provide the code you are using?

**Comment by francesco-plt** [comment]
> @francesco-plt Can you provide the code you are using?

````
    print('DEBUG: requesting %s, payload: %s' % (BASE_URL + 'generatePackages', {'links' : papers}))
    r = s.post(BASE_URL + 'generate_packages', data={'links' : papers})
    if r.status_code != 200:
        print('download request went wrong (%d)' % r.status_code)
        exit()    
```
where `papers` is a list of urls which belong to easybytez

**Comment by GammaC0de** [comment]
Wat is s?

**Comment by francesco-plt** [comment]
> What is s?

Sorry, I should have written it. It's a requests session object, I log in to pyload with it before making the request to generate the packages.

**Comment by GammaC0de** [comment]
@francesco-plt 
This code works fine:
```python
import requests
import json

def sendFiles():
    payload={'username':"admin" ,'password':"admin"}
    with requests.session() as s: 
        r=s.post("http://localhost:8000/api/login", data=payload)
        print(r.text)
        payload={'name':"4037" ,'links':["https://uptobox.com/link1", "https://pixeldrain.com/u/link2"]}
        payloadJSON = {k: json.dumps(v) for k, v in payload.items()}
        r = s.post("http://localhost:8000/api/addPackage", data=payload)
        print(r.text)
        r.close()

if __name__ == "__main__":
    sendFiles()
```

**Comment by francesco-plt** [comment]
> @francesco-plt This code works fine:
> 
> ```python
> import requests
> import json
> 
> def sendFiles():
>     payload={'username':"admin" ,'password':"admin"}
>     with requests.session() as s: 
>         r=s.post("http://localhost:8000/api/login", data=payload)
>         print(r.text)
>         payload={'name':"4037" ,'links':["https://uptobox.com/link1", "https://pixeldrain.com/u/link2"]}
>         payloadJSON = {k: json.dumps(v) for k, v in payload.items()}
>         r = s.post("http://localhost:8000/api/addPackage", data=payloadJSON)
>         print(r.text)
>         r.close()
> 
> if __name__ == "__main__":
>     sendFiles()
> ```

Thanks, I think the problem was that this line `payloadJSON = {k: json.dumps(v) for k, v in payload.items()}` was missing. Still, now I get another error, this time a 401. Shouldn't login be enough to be authorized to make api calls?

**Comment by francesco-plt** [comment]
> 

If I run your snippet I get 500 with the following traceback:
```

2022-02-22 13:52:30]  DEBUG         pyload.webui  Object of type AttributeError is not JSON serializable
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/pyload/webui/app/blueprints/api_blueprint.py", line 44, in rpc
    response = call_api(func, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/pyload/webui/app/blueprints/api_blueprint.py", line 58, in call_api
    result = getattr(api, func)(
AttributeError: 'Api' object has no attribute 'addPackage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/homebrew/lib/python3.9/site-packages/pyload/webui/app/blueprints/api_blueprint.py", line 46, in rpc
    response = jsonify(error=exc, traceback=traceback.format_exc()), 500
  File "/opt/homebrew/lib/python3.9/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/opt/homebrew/lib/python3.9/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/simplejson/__init__.py", line 398, in dumps
    return cls(
  File "/opt/homebrew/lib/python3.9/site-packages/simplejson/encoder.py", line 298, in encode
    chunks = list(chunks)
  File "/opt/homebrew/lib/python3.9/site-packages/simplejson/encoder.py", line 704, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/opt/homebrew/lib/python3.9/site-packages/simplejson/encoder.py", line 658, in _iterencode_dict
    for chunk in chunks:
  File "/opt/homebrew/lib/python3.9/site-packages/simplejson/encoder.py", line 724, in _iterencode
    o = _default(o)
  File "/opt/homebrew/lib/python3.9/site-packages/pyload/webui/app/helpers.py", line 18, in default
    return super().default(obj)
  File "/opt/homebrew/lib/python3.9/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/opt/homebrew/lib/python3.9/site-packages/simplejson/encoder.py", line 272, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type AttributeError is not JSON serializable
127.0.0.1 - - [22/Feb/2022 13:52:30] "POST /api/addPackage HTTP/1.1" 500 -
```
And I think that what was missing in my code is `payloadJSON = {k: json.dumps(v) for k, v in payload.items()}`. My pyload version is 0.5.0.

**Comment by GammaC0de** [comment]
> `AttributeError: 'Api' object has no attribute 'addPackage'`

It seems that you have an older version of pyload that does not include the above ["legacy" decorator fix ](https://github.com/pyload/pyload/commit/77024710476db792572d6ac05d15df9dfd2dae7d),

so either use `add_package` instead of `addPackage` ,
or update your pyload version to the latest develop branch using the command `pip install --upgrade https://github.com/pyload/pyload/archive/refs/heads/develop.zip`
