### ISSUE TITLE
RealdebridComTorrent stopped working with Decrypting failed

### ISSUE THREAD

**Issue by kepi** [pyload/pyload#4040]
### Description

I'm not able to download any torrent with Realdebrid.com torrent plugin with magnet links (didn't tried normal torrent files as I'm not using them). This applies to any torrent I tried from multiple trackers.

Download starts as usual but after couple seconds, it fails with `Decrypting failed` error and delete inprog torrent at debrid's side.

Entering magnet directly into Real Debrid works without any problem.

Unfortunately I'm not sure when this broke as I hadn't been watching download status lately, could be couple weeks but probably not more than 2 months.

### Debug log

Full debug log attached: [debug_RealdebridComTorrent_30-11-2021_22-09-55.zip](https://github.com/pyload/pyload/files/7628923/debug_RealdebridComTorrent_30-11-2021_22-09-55.zip)

You can easily test on magnet link `magnet:?xt=urn:btih:6CJLL6U7AHPOC7OUBN27SG4F6RVDQIT4`

```
30.11.2021 22:09:42 INFO      Added package debian-9.4.0-amd64-DVD-1.iso containing 1 links
30.11.2021 22:09:43 INFO      Decrypting starts: magnet:?xt=urn:btih:6CJLL6U7AHPOC7OUBN27SG4F6RVDQIT4
30.11.2021 22:09:43 DEBUG     CRYPTER RealdebridComTorrent[2479]: Plugin version: 0.14
30.11.2021 22:09:43 DEBUG     CRYPTER RealdebridComTorrent[2479]: Plugin status: testing
30.11.2021 22:09:43 WARNING   CRYPTER RealdebridComTorrent[2479]: Plugin may be unstable
30.11.2021 22:09:43 DEBUG     CRYPTER RealdebridComTorrent[2479]: Config option `use_premium` not found, use default `True`
30.11.2021 22:09:43 INFO      CRYPTER RealdebridComTorrent[2479]: Grabbing link info...
30.11.2021 22:09:43 DEBUG     CRYPTER RealdebridComTorrent[2479]: Link info: {'status': 7, 'hash': {}, 'name': u'urnbtih6CJLL6U7AHPOC7OUBN27SG4F6RVDQIT4', 'url': u'magnet:?xt=urn:btih:6CJLL6U7AHPOC7OUBN27SG4F6RVDQIT4', 'pattern': {}, 'size': 0}
30.11.2021 22:09:43 DEBUG     CRYPTER RealdebridComTorrent[2479]: Previous link info: {}
30.11.2021 22:09:43 INFO      CRYPTER RealdebridComTorrent[2479]: Link name: urnbtih6CJLL6U7AHPOC7OUBN27SG4F6RVDQIT4
30.11.2021 22:09:43 INFO      CRYPTER RealdebridComTorrent[2479]: Link size: N/D
30.11.2021 22:09:43 INFO      CRYPTER RealdebridComTorrent[2479]: Link status: starting
30.11.2021 22:09:43 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
30.11.2021 22:09:43 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
30.11.2021 22:09:43 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
30.11.2021 22:09:43 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36`
30.11.2021 22:09:43 INFO      CRYPTER RealdebridComTorrent[2479]: Processing url: magnet:?xt=urn:btih:6CJLL6U7AHPOC7OUBN27SG4F6RVDQIT4
30.11.2021 22:09:43 DEBUG     CRYPTER RealdebridComTorrent[2479]: LOAD URL https://api.real-debrid.com/rest/1.0/torrents/addMagnet | redirect=True | cookies=True | get={'auth_token': u'VOXNH2JU5NU6Q6LQACPLKAQHTDAVEAOS377DUKTKPZZY5KEI3YQA'} | req=None | decode=True | multipart=False | post={'magnet': u'magnet:?xt=urn:btih:6CJLL6U7AHPOC7OUBN27SG4F6RVDQIT4'} | re$
=True | just_header=False
30.11.2021 22:09:44 DEBUG     CRYPTER RealdebridComTorrent[2479]: LOAD URL https://api.real-debrid.com/rest/1.0/torrents/info/FJ6SUZZCPZ4T4 | redirect=True | cookies=True | get={'auth_token': u'VOXNH2JU5NU6Q6LQACPLKAQHTDAVEAOS377DUKTKPZZY5KEI3YQA'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
30.11.2021 22:09:45 DEBUG     CRYPTER RealdebridComTorrent[2479]: LOAD URL https://api.real-debrid.com/rest/1.0/torrents/selectFiles/FJ6SUZZCPZ4T4 | redirect=True | cookies=True | get={'auth_token': u'VOXNH2JU5NU6Q6LQACPLKAQHTDAVEAOS377DUKTKPZZY5KEI3YQA'} | req=None | decode=True | multipart=False | post={'files': '1'} | ref=True | just_header=False
30.11.2021 22:09:45 DEBUG     CRYPTER RealdebridComTorrent[2479]: LOAD URL https://api.real-debrid.com/rest/1.0/torrents/info/FJ6SUZZCPZ4T4 | redirect=True | cookies=True | get={'auth_token': u'VOXNH2JU5NU6Q6LQACPLKAQHTDAVEAOS377DUKTKPZZY5KEI3YQA'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
30.11.2021 22:09:50 DEBUG     CRYPTER RealdebridComTorrent[2479]: LOAD URL https://api.real-debrid.com/rest/1.0/torrents/info/FJ6SUZZCPZ4T4 | redirect=True | cookies=True | get={'auth_token': u'VOXNH2JU5NU6Q6LQACPLKAQHTDAVEAOS377DUKTKPZZY5KEI3YQA'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
30.11.2021 22:09:55 DEBUG     CRYPTER RealdebridComTorrent[2479]: LOAD URL https://api.real-debrid.com/rest/1.0/torrents/info/FJ6SUZZCPZ4T4 | redirect=True | cookies=True | get={'auth_token': u'VOXNH2JU5NU6Q6LQACPLKAQHTDAVEAOS377DUKTKPZZY5KEI3YQA'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
30.11.2021 22:09:55 DEBUG     CRYPTER RealdebridComTorrent[2479]: DELETE URL https://api.real-debrid.com/rest/1.0/torrents/delete/FJ6SUZZCPZ4T4?auth_token=VOXNH2JU5NU6Q6LQACPLKAQHTDAVEAOS377DUKTKPZZY5KEI3YQA
30.11.2021 22:09:55 ERROR     Decrypting failed: debian-9.4.0-amd64-DVD-1.iso | (16, '')
Traceback (most recent call last):
  File "/home/filmiky/apps/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/home/filmiky/apps/pyload/module/plugins/internal/Base.py", line 291, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/filmiky/apps/pyload/module/plugins/internal/Base.py", line 281, in _process
    self.process(self.pyfile)
  File "/home/filmiky/apps/pyload/module/plugins/internal/Crypter.py", line 32, in process
    self.decrypt(pyfile)
  File "/home/filmiky/apps/pyload/module/plugins/crypter/RealdebridComTorrent.py", line 230, in decrypt
    torrent_urls = self.wait_for_server_dl(torrent_id)
  File "/home/filmiky/apps/pyload/module/plugins/crypter/RealdebridComTorrent.py", line 188, in wait_for_server_dl
    get={'auth_token': self.api_token})
  File "/home/filmiky/apps/pyload/module/plugins/crypter/RealdebridComTorrent.py", line 41, in api_response
    json_data = self.load(self.API_URL + method, get=get, post=post)
  File "/home/filmiky/apps/pyload/module/plugins/internal/Base.py", line 487, in load
    return Plugin.load(self, *args, **kwargs)
  File "/home/filmiky/apps/pyload/module/plugins/internal/Plugin.py", line 248, in load
    decode is True)
  File "/home/filmiky/apps/pyload/module/network/Browser.py", line 98, in load
    return self.http.load(*args, **kwargs)
  File "/home/filmiky/apps/pyload/module/network/HTTPRequest.py", line 256, in load
    self.c.perform()
error: (16, '')
30.11.2021 22:09:55 INFO      Debug Report written to debug_RealdebridComTorrent_30-11-2021_22-09-55.zip
```

### Additional info

I'm using latest git version with installed dependencies and deleted userplugins before every test.

**Comment by GammaC0de** [comment]
This worked fine for me, 
Please try to refresh your pyLoad installation using the instruction in #3283 and then retry.

**Comment by kepi** [comment]
As mentioned, I'm using latest git with deleted user plugins. I adjusted my startup routine from your #3283 instructions couple months ago. I'm, always starting pyload like this:

```
cd ~/apps/pyload/ && find ~/.config/pyload/userplugins/ -delete ; git pull && poetry run ./pyLoadCore.py --configdir=$HOME/.config/pyload
```

Poetry is there only for cleaner dependency management. I even tried to update all dependencies and git hard reset to origin/stable, but nothing, problem persists.

Do you have any idea how to proceed? Btw. if I get it correctly, should the process really fail after one wrong reply? IMHO in case of error in HTTP request, we can try later without any rush or am ai mistaken?

For some time I'm suspecting that maybe there is sometime error in reply from RealDebrid, which might not be such problem if not for current behavior. Pyload, when encountering the error, immediately sends request to delete torrent and fails. I'm just wild guessing from logs, I didn't dig into code yet as I'm still not too familiar with it.

Thanks

**Comment by kepi** [comment]
Looks like I have been right about cause of problem. Looks like totally random errors from API which in current implementation cause download aborting no matter how much progress have been done.

I tried to fix it in PR mentioned above, which I'm currently testing. No download finished completely yet, but already couple errors appeared. So far, it is always only one error and than it is working OK again.

**Comment by GammaC0de** [comment]
Maybe you could open a ticket with their support.

**Comment by kepi** [comment]
It might help, but ayway, I believe that pyload should be able to handle such cases. A need to do more debugging but we should probably not cancel dowloading when API is unresponsive (it doesn't return error).

Anyway, if you have any comments about PR code, it would be much appreciated. I hope I'll be able to finish it in a couple days, there is at least one use case remaining to solve.

**Comment by GammaC0de** [comment]
At least change it to:
```python
           if api_errors_count < api_errors_max:
                    self.log_debug("Error from API '{}' (code: {}) for Torrent ID {}. Retrying {}/{}".format(torrent_info["error"], torrent_info.get("error_code", -1)), torrent_id, api_errors_count, api_errors_max))
                else:
                    self.fail("%s (code: %s)" % (torrent_info["error"], torrent_info.get("error_code", -1)))
 ```

So at least we can see what error the server reports..
