### ISSUE TITLE
9kw not working

### ISSUE THREAD

**Issue by deepdude321** [pyload/pyload#4049]
### Description

Captcha solving with the 9kw plugin seems to be broken. Tried multiple hoster. On the 9kw.eu website no input is recognized.
Same downloads on a windows machine with jdownloader and 9kw worked as expected.

System: Ubuntu Server 20.04.3
PyLoad: Stable release pyload-cli_0.4.20_all.deb
All dependencies met.

### Debug log

```
12.12.2021 19:55:26 INFO      ADDON UpdateManager: All plugins are up to date!
12.12.2021 19:55:28 DEBUG     Redirected import module.plugins.hoster.KatfileCom -> userplugins.hoster.KatfileCom
12.12.2021 19:55:28 DEBUG     Redirected import userplugins.internal.CaptchaService -> module.plugins.internal.CaptchaService
12.12.2021 19:55:28 DEBUG     Redirected import module.plugins.internal.Captcha -> userplugins.internal.Captcha
12.12.2021 19:55:28 DEBUG     Redirected import userplugins.captcha.SolveMedia -> module.plugins.captcha.SolveMedia
12.12.2021 19:55:28 DEBUG     Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
12.12.2021 19:55:28 INFO      Download starts: https://katfile.com/ufi9t6hh7he6
12.12.2021 19:55:28 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
12.12.2021 19:55:28 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
12.12.2021 19:55:28 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
12.12.2021 19:55:28 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
12.12.2021 19:55:28 DEBUG     HOSTER KatfileCom[3]: Plugin version: 0.03
12.12.2021 19:55:28 DEBUG     HOSTER KatfileCom[3]: Plugin status: testing
12.12.2021 19:55:28 WARNING   HOSTER KatfileCom[3]: Plugin may be unstable
12.12.2021 19:55:28 INFO      HOSTER KatfileCom[3]: Grabbing link info...
12.12.2021 19:55:28 DEBUG     HOSTER KatfileCom[3]: LOAD URL https://katfile.com/ufi9t6hh7he6 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
12.12.2021 19:55:28 DEBUG     HOSTER KatfileCom[3]: Link info: {'status': 2, 'hash': {}, 'name': u'72BD-DasGeheimnisdesDrZ-SAVASTANOS.part3.rar', 'url': u'https://katfile.com/ufi9t6hh7he6', 'pattern': {'S': u'1001.0', 'U': u'MB', 'N': u'72BD-DasGeheimnisdesDrZ-SAVASTANOS.part3.rar'}, 'size': 1049624576}
12.12.2021 19:55:28 DEBUG     HOSTER KatfileCom[3]: Previous link info: {}
12.12.2021 19:55:28 INFO      HOSTER KatfileCom[3]: Link name: 72BD-DasGeheimnisdesDrZ-SAVASTANOS.part3.rar
12.12.2021 19:55:28 INFO      HOSTER KatfileCom[3]: Link size: 1001.00 MiB (1049624576 bytes)
12.12.2021 19:55:28 INFO      HOSTER KatfileCom[3]: Link status: online
12.12.2021 19:55:28 INFO      HOSTER KatfileCom[3]: Processing url: https://katfile.com/ufi9t6hh7he6
12.12.2021 19:55:28 DEBUG     HOSTER KatfileCom[3]: LOAD URL https://katfile.com/ufi9t6hh7he6 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
12.12.2021 19:55:28 INFO      HOSTER KatfileCom[3]: Checking for link errors...
12.12.2021 19:55:28 INFO      HOSTER KatfileCom[3]: No errors found
12.12.2021 19:55:28 INFO      HOSTER KatfileCom[3]: Processing as free download...
12.12.2021 19:55:28 DEBUG     HOSTER KatfileCom[3]: Getting download link #1...
12.12.2021 19:55:28 INFO      HOSTER KatfileCom[3]: Checking for link errors...
12.12.2021 19:55:28 INFO      HOSTER KatfileCom[3]: No errors found
12.12.2021 19:55:28 DEBUG     HOSTER KatfileCom[3]: {u'method_premium': u'HIGH SPEED DOWNLOAD', u'usr_login': '', u'referer': '', u'fname': u'72BD-DasGeheimnisdesDrZ-SAVASTANOS.part3.rar', u'method_free': u'SLOW SPEED DOWNLOAD', u'id': u'ufi9t6hh7he6', u'op': u'download1'}
12.12.2021 19:55:28 DEBUG     HOSTER KatfileCom[3]: WAIT set to timestamp 1639335360.587542 | Previous waitUntil: 0.000000
12.12.2021 19:55:28 WARNING   CAPTCHA KatfileCom[3]: ReCaptcha | Key pattern not found
12.12.2021 19:55:28 DEBUG     CAPTCHA KatfileCom[3]: SolveMedia | Key pattern not found
12.12.2021 19:55:28 INFO      HOSTER KatfileCom[3]: Waiting 31 seconds...
12.12.2021 19:55:32 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
12.12.2021 19:56:00 DEBUG     HOSTER KatfileCom[3]: LOAD URL https://katfile.com/ufi9t6hh7he6 | redirect=False | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'usr_login': '', u'referer': u'https://katfile.com/ufi9t6hh7he6', u'fname': u'72BD-DasGeheimnisdesDrZ-SAVASTANOS.part3.rar', u'method_free': 'Free Download', u'id': u'ufi9t6hh7he6', u'op': u'download1'} | ref=https://katfile.com/ufi9t6hh7he6 | just_header=False
12.12.2021 19:56:00 DEBUG     HOSTER KatfileCom[3]: Getting download link #2...
12.12.2021 19:56:00 INFO      HOSTER KatfileCom[3]: Checking for link errors...
12.12.2021 19:56:00 INFO      HOSTER KatfileCom[3]: No errors found
12.12.2021 19:56:00 DEBUG     HOSTER KatfileCom[3]: {u'rand': u'5b2tsc3ma2wf274yti6nq2t3gscpphgjnawxgny', u'method_premium': '', u'referer': u'https://katfile.com/ufi9t6hh7he6', u'method_free': u'Free Download', u'id': u'ufi9t6hh7he6', u'op': u'download2'}
12.12.2021 19:56:00 DEBUG     CAPTCHA KatfileCom[3]: ReCaptcha | Key: 6LfFIQ4UAAAAAPVN0aXDQkOce2y1KmGnuY6uwgMd
12.12.2021 19:56:00 WARNING   CAPTCHA KatfileCom[3]: ReCaptcha | Secure Token pattern not found
12.12.2021 19:56:00 DEBUG     CAPTCHA KatfileCom[3]: ReCaptcha | Detected reCAPTCHA v2
12.12.2021 19:56:00 WARNING   CAPTCHA KatfileCom[3]: ReCaptcha | Secure Token pattern not found
12.12.2021 19:56:00 DEBUG     HOSTER KatfileCom[3]: LOAD URL https://www.google.com/recaptcha/api/fallback?k=6LfFIQ4UAAAAAPVN0aXDQkOce2y1KmGnuY6uwgMd | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=https://katfile.com/ufi9t6hh7he6 | just_header=False
12.12.2021 19:56:00 WARNING   CAPTCHA KatfileCom[3]: ReCaptcha | reCAPTCHA noscript is blocked, trying reCAPTCHA interactive
12.12.2021 19:56:00 DEBUG     CAPTCHA KatfileCom[3]: ReCaptcha | Challenge reCAPTCHA v2 interactive
12.12.2021 19:56:00 DEBUG     ADDON Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | redirect=True | cookies=True | get={'action': 'usercaptchaguthaben', 'source': 'pyload', 'apikey': u'20W1DHUF4EWUM3WQOX', 'pyload': '1'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
12.12.2021 19:56:01 INFO      ADDON Captcha9Kw: 409 credits left
12.12.2021 19:56:01 DEBUG     ADDON Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/root/.pyload/userplugins/hooks/Captcha9Kw.py", line 73, in _process_captcha
    "isInvisible": "INVISIBLE" if task.isInvisible() else "NORMAL",
AttributeError: CaptchaTask instance has no attribute 'isInvisible'
```

Hope this log will suffice.

**Comment by GammaC0de** [comment]
Plugin updated, BUT:
You'd better update your pyLoad installation using the instruction in #3283 to add support for invisible recaptcha.

**Comment by deepdude321** [comment]
I've followed your instructions and everything's fine now.

Thank you very much!
