### ISSUE TITLE
Easybytez - 'int' object has no attribute 'strip'

### ISSUE THREAD

**Issue by matrog** [pyload/pyload#4053]
### Description
easybytez plugin does not work anymore after recent commits, I also tried to start from fresh install following #3283  but no luck

this is a test file http://www.easybytez.com/2wyrgyvpp2pj/easy_test.txt

### Debug log

```


23.12.2021 10:00:29 | DEBUG | All downloads processed
-- | -- | --
808 | 23.12.2021 10:00:29 | INFO | ADDON UnSkipOnFail: No duplicates found
807 | 23.12.2021 10:00:29 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: easy_test.txt (pid:3)
806 | 23.12.2021 10:00:29 | INFO | Debug Report written to debug_EasybytezCom_23-12-2021_10-00-29.zip
805 | ? | ? | AttributeError: 'int' object has no attribute 'strip'
804 | ? | ? | msg = msg.strip()
803 | ? | ? | File "/volume1/@appstore/pyload/share/pyload/module/plugins/internal/Base.py", line 390, in fail
802 | ? | ? | self.fail(e.args[0])
801 | ? | ? | File "/volume1/@appstore/pyload/share/pyload/module/plugins/internal/Hoster.py", line 300, in download
800 | ? | ? | self.download(self.link, disposition=self.DISPOSITION)
799 | ? | ? | File "/volume1/@appstore/pyload/share/pyload/module/plugins/internal/SimpleHoster.py", line 284, in process
798 | ? | ? | self.process(self.pyfile)
797 | ? | ? | File "/volume1/@appstore/pyload/share/pyload/module/plugins/internal/Hoster.py", line 118, in _process
796 | ? | ? | return self._process(*args, **kwargs)
795 | ? | ? | File "/volume1/@appstore/pyload/share/pyload/module/plugins/internal/Base.py", line 290, in preprocessing
794 | ? | ? | pyfile.plugin.preprocessing(self)
793 | ? | ? | File "/volume1/@appstore/pyload/share/pyload/module/PluginThread.py", line 189, in run
792 | ? | ? | Traceback (most recent call last):
791 | 23.12.2021 10:00:29 | WARNING | Download failed: easy_test.txt \| 'int' object has no attribute 'strip'
790 | 23.12.2021 10:00:29 | DEBUG | HOSTER EasybytezCom[97]: DOWNLOAD URL http://str61.ezbytez.com/files/6/7y5dpowxwkx5zi/easy_test.txt \| cookies=True \| resume=None \| get={} \| disposition=True \| chunks=None \| post={} \| ref=True
789 | 23.12.2021 10:00:29 | INFO | HOSTER EasybytezCom[97]: Downloading file...
788 | 23.12.2021 10:00:29 | DEBUG | HOSTER EasybytezCom[97]: LOAD URL http://www.easybytez.com/2wyrgyvpp2pj/easy_test.txt \| redirect=False \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={u'rand': u'rg2exvl3eqggkifksz3b7sm2nwfh67ih7dawnda', u'method_premium': 'Premium Download', u'down_direct': u'1', u'referer': '', u'id': u'2wyrgyvpp2pj', u'op': u'download2'} \| ref=http://www.easybytez.com/2wyrgyvpp2pj/easy_test.txt \| just_header=False
787 | 23.12.2021 10:00:29 | DEBUG | HOSTER EasybytezCom[97]: {u'rand': u'rg2exvl3eqggkifksz3b7sm2nwfh67ih7dawnda', u'method_premium': u'1', u'down_direct': u'1', u'referer': '', u'method_free': '', u'id': u'2wyrgyvpp2pj', u'op': u'download2'}
786 | 23.12.2021 10:00:29 | INFO | HOSTER EasybytezCom[97]: No errors found
785 | 23.12.2021 10:00:29 | INFO | HOSTER EasybytezCom[97]: Checking for link errors...
784 | 23.12.2021 10:00:29 | DEBUG | HOSTER EasybytezCom[97]: Getting download link #1...
783 | 23.12.2021 10:00:29 | INFO | HOSTER EasybytezCom[97]: Processing as premium download...
782 | 23.12.2021 10:00:29 | INFO | HOSTER EasybytezCom[97]: Link status: online
781 | 23.12.2021 10:00:29 | INFO | HOSTER EasybytezCom[97]: Link size: 15.00 B (15 bytes)
780 | 23.12.2021 10:00:29 | INFO | HOSTER EasybytezCom[97]: Link name: easy_test.txt
779 | 23.12.2021 10:00:29 | DEBUG | HOSTER EasybytezCom[97]: Previous link info: {}
778 | 23.12.2021 10:00:29 | DEBUG | HOSTER EasybytezCom[97]: Link info: {'status': 2, 'hash': {}, 'name': u'easy_test.txt', 'url': u'http://www.easybytez.com/2wyrgyvpp2pj/easy_test.txt', 'pattern': {'S': u'15', 'U': u'B', 'N': u'easy_test.txt'}, 'size': 15}
777 | 23.12.2021 10:00:29 | INFO | HOSTER EasybytezCom[97]: Grabbing link info...
776 | 23.12.2021 10:00:29 | INFO | HOSTER EasybytezCom[97]: No errors found
```
pyload is running on a x86 Synology NAS

thanks!

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by matrog** [comment]
sent, please let me know when done with the account

**Comment by GammaC0de** [comment]
👍🏻

**Comment by GammaC0de** [comment]
@matrog What platform are you running pyload?
It seems that your pyload is still not up-to-date inspite that you said that you have done #3283 😕

**Comment by matrog** [comment]
ok, let's do the reinstallation again, the platform is a synology DS1518+ with x86

I download latest pyload-stable from here https://github.com/pyload/pyload/archive/stable.zip

```
md5sum stable.zip
130dafa26b11913670e7e1eef054957a  stable.zip
```

did all the steps but still the same on Synology, I will try on a VM with ubuntu

**Comment by matrog** [comment]
looks like on a VM and ubuntu is working..I will figure out what happened on the NAS

**Comment by matrog** [comment]
it turned out to be a permission issuebut unfortunately everything I tried is making the situazion even worse...now it' s not working anymore as root...I need to figure out something but I can say it's not a pyload issues. Thanks for all the help here. :)

**Comment by GammaC0de** [comment]
> I need to figure out something but I can say it's not a pyload issues

I guess you are using some kind of pyload synology package.
If you cannot solve your issue, why not install python and then manually install pyload?

**Comment by matrog** [comment]
need to work on that, it's difficult to install prerequisites but i will definitely give it a try
