### ISSUE TITLE
[ExternalScripts] Runtime error: No such file or directory

### ISSUE THREAD

**Issue by Kenifornication** [pyload/pyload#4082]
### Description

A "No such file or directory" error is thrown when the ExternalScripts plugin tries to run any script.

Further info:
- pyLoad is running on a RasPi, installed following the instructions in the [Wiki](https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(RaspberryPi))
- pyLoad version: 0.4.20
- Installation Folder: /opt/pyload
- Config Folder: /home/pyload/.pyload
- Script path: /home/pyload/.pyload/scripts/pyload_start/test.sh
- Permissions set to chmod 775 

### Debug log

```
26.01.2022 10:28:45 INFO      Starting pyLoad 0.4.20
26.01.2022 10:28:45 INFO      Using home directory: /home/pyload/.pyload
26.01.2022 10:28:45 DEBUG     Remote activated: False
26.01.2022 10:28:50 DEBUG     created index of plugins
26.01.2022 10:28:50 DEBUG     Redirected import module.plugins.internal.misc -> userplugins.internal.misc
26.01.2022 10:28:50 INFO      ADDON ExternalScripts: Activated scripts in folder `pyload_start`: test.sh, pyload_start.sh
26.01.2022 10:28:50 INFO      ADDON ExternalScripts: Activated scripts in folder `download_preparing`: dl_start.sh
26.01.2022 10:28:50 INFO      ADDON ExternalScripts: Activated scripts in folder `download_finished`: dl_finished.sh
26.01.2022 10:28:50 DEBUG     Redirected import module.plugins.hooks.TelegramPush -> userplugins.hooks.TelegramPush
26.01.2022 10:28:50 DEBUG     Redirected import userplugins.internal.Addon -> module.plugins.internal.Addon
26.01.2022 10:28:50 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, TORRENT, TelegramPush, UnSkipOnFail, UpdateManager, UserAgentSwitcher
26.01.2022 10:28:50 INFO      Downloadtime: True
26.01.2022 10:28:51 INFO      Free space: 14.48 GiB
26.01.2022 10:28:51 INFO      Activating Accounts...
26.01.2022 10:28:51 INFO      Activating Plugins...
26.01.2022 10:28:56 WARNING   ADDON TORRENT: torrents / magnets are not associated with any plugin
26.01.2022 10:28:56 INFO      Starting builtin webserver: :::8000
26.01.2022 10:28:56 INFO      ADDON ExternalScripts: Executing scripts in folder `pyload_start`...
26.01.2022 10:28:56 DEBUG     ADDON ExternalScripts: EXECUTE scripts/pyload_start/test.sh
26.01.2022 10:28:56 ERROR     ADDON ExternalScripts: Runtime error: scripts/pyload_start/test.sh | [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/pyload/pyLoadCore.py", line 731, in <module>
    main()
  File "/opt/pyload/pyLoadCore.py", line 722, in main
    pyload_core.start()
  File "/opt/pyload/pyLoadCore.py", line 499, in start
    self.hookManager.coreReady()
  File "/opt/pyload/module/HookManager.py", line 87, in new
    return func(*args)
  File "/opt/pyload/module/HookManager.py", line 193, in coreReady
    plugin.coreReady()
  File "/opt/pyload/module/plugins/internal/Addon.py", line 106, in coreReady
    return self.activate()
  File "/opt/pyload/module/plugins/hooks/ExternalScripts.py", line 51, in activate
    self.pyload_start()
  File "/opt/pyload/module/plugins/hooks/ExternalScripts.py", line 153, in pyload_start
    self.call_script('pyload_start')
  File "/opt/pyload/module/plugins/hooks/ExternalScripts.py", line 137, in call_script
    p = self.call_cmd(file, *args)
  File "/opt/pyload/module/plugins/hooks/ExternalScripts.py", line 117, in call_cmd
    p = Popen(call, bufsize=-1)  # @NOTE: output goes to pyload
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

26.01.2022 10:28:56 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/updates/master/plugins.txt | redirect=True | cookies=True | get={'v': '0.4.20'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
26.01.2022 10:28:56 INFO      pyLoad is up and running
26.01.2022 10:28:57 INFO      ADDON UpdateManager: pyLoad is up to date!
26.01.2022 10:28:57 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/updates/master/plugins.txt | redirect=True | cookies=True | get={'v': '0.4.20'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
26.01.2022 10:28:59 INFO      ADDON UpdateManager: All plugins are up to date!
26.01.2022 10:29:02 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
```

**Comment by GammaC0de** [comment]
What is the content of test.sh?

**Comment by Kenifornication** [comment]
> What is the content of test.sh?

```
#!/bin/sh
echo Test: 1:$1 2:$2 3:$3 4:$4 5:$5 > /home/pyload/.pyload/Logs/test.txt
```

**Comment by Kenifornication** [comment]
Sorry, it appears that I'm a colossal idiot. The problem was the newlines being Windows instead of Unix, something happened while transferring the scripts from my local machine to the RasPi. Apologies for wasting your time with this ticket.
