### ISSUE TITLE
Zippyshare plugin fails because of missing beautifulsoup4

### ISSUE THREAD

**Issue by CaptainTyphoo** [pyload/pyload#4084]
### Description

The Zippyshare plugin always fails with the message:
`failed 'NoneType' object has no attribute 'ZippyshareCom'`

The issue can be fixed by e.g.
``` bash
$ pip3 install --user beautifulsoup4
```

I think this dependency should be added to the python package so it gets automatically installed when you install pyload-ng with pip.

### Debug log
``` log


2002 | 2022-01-30 14:09:38 | ERROR | pyload | Error importing ZippyshareCom: No module named 'bs4'
-- | -- | -- | -- | --
2003 | 2022-01-30 14:09:38 | CRITICAL | pyload | 'NoneType' object has no attribute 'ZippyshareCom'
2004 | ? | ? | ? | Traceback (most recent call last):
2005 | ? | ? | ? | File "/home/pyload/.local/lib/python3.7/site-packages/pyload/core/managers/thread_manager.py", line 315, in assign_job
2006 | ? | ? | ? | job.init_plugin()
2007 | ? | ? | ? | File "/home/pyload/.local/lib/python3.7/site-packages/pyload/core/utils/struct/lock.py", line 22, in wrapped
2008 | ? | ? | ? | return func(self, *args, **kwargs)
2009 | ? | ? | ? | File "/home/pyload/.local/lib/python3.7/site-packages/pyload/core/datatypes/pyfile.py", line 90, in init_plugin
2010 | ? | ? | ? | self.m.pyload.plugin_manager.get_plugin_name(self.pluginname),
2011 | ? | ? | ? | AttributeError: 'NoneType' object has no attribute 'ZippyshareCom'

```

**Comment by GammaC0de** [comment]
Already included, see [https://github.com/pyload/pyload#extra-dependencies](https://github.com/pyload/pyload#extra-dependencies)

```
pip install pyload-ng[plugins]
```
