### ISSUE TITLE
[DepositfilesCom] Error: Captcha pattern not found

### ISSUE THREAD

**Issue by Kenifornication** [pyload/pyload#4088]
### Description

Downloading from Depositfiles is broken, a "Captcha pattern not found" error is thrown.

### Debug log

```

03.02.2022 17:29:47 INFO      Download starts: https://dfiles.eu/files/57e1ytkum
03.02.2022 17:29:49 DEBUG     HOSTER DepositfilesCom[493]: Plugin version: 0.64
03.02.2022 17:29:49 DEBUG     HOSTER DepositfilesCom[493]: Plugin status: testing
03.02.2022 17:29:49 WARNING   HOSTER DepositfilesCom[493]: Plugin may be unstable
03.02.2022 17:29:49 INFO      HOSTER DepositfilesCom[493]: Processing url: https://dfiles.eu/files/57e1ytkum
03.02.2022 17:29:49 INFO      HOSTER DepositfilesCom[493]: Looking for direct download link...
03.02.2022 17:29:49 DEBUG     HOSTER DepositfilesCom[493]: LOAD URL https://depositfiles.com/files/57e1ytkum | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
03.02.2022 17:29:50 INFO      HOSTER DepositfilesCom[493]: Direct download link not found
03.02.2022 17:29:50 DEBUG     HOSTER DepositfilesCom[493]: LOAD URL https://depositfiles.com/files/57e1ytkum | redirect=True | cookies=[('depositfiles.com', 'lang_current', 'en')] | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
03.02.2022 17:29:53 INFO      HOSTER DepositfilesCom[493]: Checking for link errors...
03.02.2022 17:29:53 INFO      HOSTER DepositfilesCom[493]: No errors found
03.02.2022 17:29:53 INFO      HOSTER DepositfilesCom[493]: Grabbing link info...
03.02.2022 17:29:53 DEBUG     HOSTER DepositfilesCom[493]: Link info: {'status': 2, 'hash': {}, 'name': u'book-snowflakes.zip', 'url': u'https://depositfiles.com/files/57e1ytkum', 'pattern': {'S': u'2.91', 'U': u'MB', 'ID': u'57e1ytkum', 'N': u'%u0064%u006F%u0063%u0075%u006D%u0065%u006E%u0074%u002E%u0077%u0072%u0069%u0074%u0065%u0028%u0027%u003C%u0064%u0069%u0076%u0020%u0063%u006C%u0061%u0073%u0073%u003D%u0022%u0066%u0069%u006C%u0065%u005F%u006E%u0061%u006D%u0065%u0022%u003E%u0046%u0069%u006C%u0065%u0020%u006E%u0061%u006D%u0065%u003A%u0020%u003C%u0062%u0020%u0074%u0069%u0074%u006C%u0065%u003D%u0022%u0062%u006F%u006F%u006B%u002D%u0073%u006E%u006F%u0077%u0066%u006C%u0061%u006B%u0065%u0073%u002E%u007A%u0069%u0070%u0022%u003E%u0062%u006F%u006F%u006B%u002D%u0073%u006E%u006F%u0077%u0066%u006C%u0061%u006B%u0065%u0073%u002E%u007A%u0069%u0070%u003C%u002F%u0062%u003E%u003C%u002F%u0064%u0069%u0076%u003E%u0027%u0029%u003B'}, 'size': 3051356}
03.02.2022 17:29:53 DEBUG     HOSTER DepositfilesCom[493]: Previous link info: {}
03.02.2022 17:29:53 INFO      HOSTER DepositfilesCom[493]: Link name: book-snowflakes.zip
03.02.2022 17:29:53 INFO      HOSTER DepositfilesCom[493]: Link size: 2.91 MiB (3051356 bytes)
03.02.2022 17:29:53 INFO      HOSTER DepositfilesCom[493]: Link status: online
03.02.2022 17:29:53 INFO      HOSTER DepositfilesCom[493]: Processing as free download...
03.02.2022 17:29:53 DEBUG     HOSTER DepositfilesCom[493]: LOAD URL https://depositfiles.com/files/57e1ytkum | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'gateway_result': '1', 'asm': '0'} | ref=True | just_header=False
03.02.2022 17:29:55 INFO      HOSTER DepositfilesCom[493]: Checking for link errors...
03.02.2022 17:29:55 DEBUG     HOSTER DepositfilesCom[493]: WAIT set to timestamp 1643905801.209047 | Previous waitUntil: 0.000000
03.02.2022 17:29:55 INFO      HOSTER DepositfilesCom[493]: Waiting 5 seconds...
03.02.2022 17:30:01 INFO      HOSTER DepositfilesCom[493]: No errors found
03.02.2022 17:30:01 DEBUG     HOSTER DepositfilesCom[493]: FID: 586ac62d83737bf06947fc5674b6032e
03.02.2022 17:30:01 DEBUG     HOSTER DepositfilesCom[493]: LOAD URL https://depositfiles.com/get_file.php | redirect=True | cookies=True | get={'fid': u'586ac62d83737bf06947fc5674b6032e'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
03.02.2022 17:30:02 ERROR     HOSTER DepositfilesCom[493]: Captcha pattern not found
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/pyload/module/PluginThread.py", line 189, in run
    pyfile.plugin.preprocessing(self)
  File "/home/pyload/.pyload/userplugins/internal/Base.py", line 290, in preprocessing
    return self._process(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Hoster.py", line 118, in _process
    self.process(self.pyfile)
  File "/home/pyload/.pyload/userplugins/internal/SimpleHoster.py", line 281, in process
    self.handle_free(pyfile)
  File "/opt/pyload/module/plugins/hoster/DepositfilesCom.py", line 74, in handle_free
    self.log_error(_("Captcha pattern not found"))

03.02.2022 17:30:02 WARNING   HOSTER DepositfilesCom[493]: Free download failed | Captcha pattern not found
03.02.2022 17:30:02 WARNING   Download failed: book-snowflakes.zip | Captcha pattern not found
```

**Comment by Kenifornication** [comment]
Thanks for the fix @GammaC0de. Works as expected.
