### ISSUE TITLE
Keep2ShareCc Hoster - failed 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by flexyboooy** [pyload/pyload#4116]
This is not a huge problem but a bit of a nuisance:

When downloading files with Keep2ShareCc even when the download finishes normally it is always reported as failed and the plugin throws this error in the log:

```
INFO      HOSTER Keep2ShareCc[364] No errors found
INFO      Download finished: somefile.mp4
WARNING   Download failed: somefile.mp4 | 'NoneType' object has no attribute 'lower'
```

I am running the, as of today, latest docker.io/linuxserver/pyload:latest image in docker.

**Comment by GammaC0de** [comment]
Please enable debug mode, retry the download and then post the logs.

Also, sample URL would help.

**Comment by flexyboooy** [comment]
Thank you, yes, of course.


Test link: https://k2s.cc/file/b2db05dbf95b0

```
23.03.2022 18:00:42 DEBUG     Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
23.03.2022 18:00:42 INFO      Added package TEST containing 1 links
23.03.2022 18:00:42 DEBUG     Redirected import userplugins.internal.Hoster -> module.plugins.internal.Hoster
23.03.2022 18:00:43 INFO      Download starts: https://k2s.cc/file/b2db05dbf95b0
23.03.2022 18:00:43 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
23.03.2022 18:00:43 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
23.03.2022 18:00:43 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
23.03.2022 18:00:43 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
23.03.2022 18:00:43 DEBUG     HOSTER Keep2ShareCc[362] Plugin version: 0.46
23.03.2022 18:00:43 DEBUG     HOSTER Keep2ShareCc[362] Plugin status: testing
23.03.2022 18:00:43 WARNING   HOSTER Keep2ShareCc[362] Plugin may be unstable
23.03.2022 18:00:43 INFO      HOSTER Keep2ShareCc[362] Processing url: https://k2s.cc/file/b2db05dbf95b0
23.03.2022 18:00:43 INFO      HOSTER Keep2ShareCc[362] Looking for direct download link...
23.03.2022 18:00:43 DEBUG     HOSTER Keep2ShareCc[362] LOAD URL https://k2s.cc/file/b2db05dbf95b0 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
23.03.2022 18:00:44 INFO      HOSTER Keep2ShareCc[362] Direct download link not found
23.03.2022 18:00:44 DEBUG     HOSTER Keep2ShareCc[362] LOAD URL https://k2s.cc/file/b2db05dbf95b0 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
23.03.2022 18:00:44 INFO      HOSTER Keep2ShareCc[362] Checking for link errors...
23.03.2022 18:00:44 INFO      HOSTER Keep2ShareCc[362] No errors found
23.03.2022 18:00:44 INFO      HOSTER Keep2ShareCc[362] Grabbing link info...
23.03.2022 18:00:44 DEBUG     HOSTER Keep2ShareCc[362] LOAD URL https://keep2share.cc/api/v2/GetFilesInfo | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={"extended_info": false, "ids": ["b2db05dbf95b0"]} | ref=True | just_header=False
23.03.2022 18:00:44 DEBUG     HOSTER Keep2ShareCc[362] Link info: {'status': 2, 'hash': {}, 'name': u'piktas vilkas_nele neuhaus.epub', 'url': u'https://k2s.cc/file/b2db05dbf95b0', 'pattern': {'ID': u'b2db05dbf95b0'}, 'access': u'public', 'size': 936290, 'md5': None}
23.03.2022 18:00:44 DEBUG     HOSTER Keep2ShareCc[362] Previous link info: {}
23.03.2022 18:00:44 INFO      HOSTER Keep2ShareCc[362] Link name: piktas vilkas_nele neuhaus.epub
23.03.2022 18:00:44 INFO      HOSTER Keep2ShareCc[362] Link size: 914.35 KiB (936290 bytes)
23.03.2022 18:00:44 INFO      HOSTER Keep2ShareCc[362] Link status: online
23.03.2022 18:00:44 INFO      HOSTER Keep2ShareCc[362] Processing as free download...
23.03.2022 18:00:44 DEBUG     HOSTER Keep2ShareCc[362] LOAD URL https://keep2share.cc/api/v2/GetUrl | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={"captcha_challenge": null, "captcha_response": null, "free_download_key": null, "file_id": "b2db05dbf95b0"} | ref=True | just_header=False
23.03.2022 18:00:44 DEBUG     HOSTER Keep2ShareCc[362] LOAD URL https://keep2share.cc/api/v2/RequestCaptcha | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
23.03.2022 18:00:44 DEBUG     CAPTCHA Keep2ShareCc[362] Captcha | LOAD URL http://keep2share.cc/api/v2/captcha.html?id=4f49afbb5f51d | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x756d3538> | decode=False | multipart=False | post={} | ref=False | just_header=False
23.03.2022 18:00:44 INFO      CAPTCHA Keep2ShareCc[362] Captcha | Using OCR to decrypt captcha...
23.03.2022 18:00:44 WARNING   CAPTCHA Keep2ShareCc[362] Captcha | No OCR result
23.03.2022 18:00:52 INFO      CAPTCHA Keep2ShareCc[362] Captcha | Captcha result: `CNpeOJ`
23.03.2022 18:00:52 DEBUG     HOSTER Keep2ShareCc[362] LOAD URL https://keep2share.cc/api/v2/GetUrl | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={"captcha_challenge": "4f49afbb5f51d", "captcha_response": "CNpeOJ", "free_download_key": null, "file_id": "b2db05dbf95b0"} | ref=True | just_header=False
23.03.2022 18:00:52 INFO      CAPTCHA Keep2ShareCc[362] Captcha | Correct captcha | CNpeOJ
23.03.2022 18:00:52 DEBUG     HOSTER Keep2ShareCc[362] WAIT set to timestamp 1648054883.989212 | Previous waitUntil: 0.000000
23.03.2022 18:00:52 DEBUG     HOSTER Keep2ShareCc[362] RECONNECT not required | Previous wantReconnect: False
23.03.2022 18:00:52 INFO      HOSTER Keep2ShareCc[362] Waiting 30 seconds...
23.03.2022 18:01:25 DEBUG     HOSTER Keep2ShareCc[362] LOAD URL https://keep2share.cc/api/v2/GetUrl | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={"captcha_challenge": null, "captcha_response": null, "free_download_key": "61ae5f5f50ad8", "file_id": "b2db05dbf95b0"} | ref=True | just_header=False
23.03.2022 18:01:25 DEBUG     HOSTER Keep2ShareCc[362] DOWNLOAD URL https://slow-118.keep2share.cc/34e4d5e9291b0/63f725276d370/2708e51269dfd?temp_url_sig=ceb43398c66b721dcede588137f2372cb156c376101c4465520c205f9bddb3236ddcf58eecff020d5862e198171ddb8c3f0d0b29ff3cbd6c59de3cf2a4f1fe5a&temp_url_expires=1648141285&id=d027096d1cf23&ip=any&node_id=118&countable=1&project=moneyplatform&rate_limit=51200&uf=b2db05dbf95b0&tags=k2s%2Cwebapi%2Cdownload&name=piktas%20vilkas_nele%20neuhaus.epub | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
23.03.2022 18:01:25 DEBUG     Content-Disposition: piktas vilkas_nele neuhaus.epub
23.03.2022 18:01:25 DEBUG     Chunked with range 0-
23.03.2022 18:01:43 INFO      HOSTER Keep2ShareCc[362] File saved
23.03.2022 18:01:43 INFO      HOSTER Keep2ShareCc[362] Checking download...
23.03.2022 18:01:44 INFO      HOSTER Keep2ShareCc[362] File is OK
23.03.2022 18:01:44 INFO      HOSTER Keep2ShareCc[362] Checking file (with built-in rules)...
23.03.2022 18:01:44 INFO      HOSTER Keep2ShareCc[362] Checking file (with custom rules)...
23.03.2022 18:01:44 INFO      HOSTER Keep2ShareCc[362] Checking for link errors...
23.03.2022 18:01:44 INFO      HOSTER Keep2ShareCc[362] No errors found
23.03.2022 18:01:44 INFO      HOSTER Keep2ShareCc[362] No errors found
23.03.2022 18:01:44 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
23.03.2022 18:01:44 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
23.03.2022 18:01:44 INFO      Download finished: piktas vilkas_nele neuhaus.epub
23.03.2022 18:01:44 DEBUG     ADDON ExternalScripts: No script found under folder `download_finished`
23.03.2022 18:01:44 DEBUG     ADDON Checksum: {'status': 2, 'hash': {}, 'name': u'piktas vilkas_nele neuhaus.epub', 'url': u'https://k2s.cc/file/b2db05dbf95b0', 'pattern': {'ID': u'b2db05dbf95b0'}, 'access': u'public', 'md5': None}
23.03.2022 18:01:44 WARNING   Download failed: piktas vilkas_nele neuhaus.epub | 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/app/pyload/module/PluginThread.py", line 192, in run
    self.m.core.hookManager.downloadFinished(pyfile)
  File "/app/pyload/module/utils.py", line 218, in new
    return func(*args)
  File "/app/pyload/module/HookManager.py", line 220, in downloadFinished
    plugin.downloadFinished(pyfile)
  File "/app/pyload/module/plugins/internal/Addon.py", line 150, in downloadFinished
    return self.download_finished(pyfile)
  File "/app/pyload/module/plugins/hooks/Checksum.py", line 178, in download_finished
    if checksum.lower() == data['hash'][key].lower(]
AttributeError: 'NoneType' object has no attribute 'lower'
23.03.2022 18:01:53 INFO      Debug Report written to debug_Keep2ShareCc_23-03-2022_18-01-44.zip
23.03.2022 18:01:53 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: piktas vilkas_nele neuhaus.epub (pid:936)
23.03.2022 18:01:53 INFO      ADDON UnSkipOnFail: No duplicates found
23.03.2022 18:01:54 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
23.03.2022 18:01:54 DEBUG     All downloads processed
```
