### ISSUE TITLE
Installed but cannot run under Termux Android arch64

### ISSUE THREAD

**Issue by defencedog** [pyload/pyload#4138]
### Description
Installed successfully but cannot run

### Debug log

`pyload
[2022-05-03 05:07:37]  INFO                pyload  *** Welcome to pyLoad 0.5.0 *** ImportError: dlopen failed: cannot find "libssl.so" from verneed[0] in DT_NEEDED list for "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pycurl.cpython-310.so" Traceback (most recent call last): File "/data/data/com.termux/files/usr/bin/pyload", line 8, in <module> sys.exit(main()) File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pyload/main.py", line 292, in main run(core_args, args.daemon, args.pidfile) File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pyload/main.py", line 235, in run pyload_core = Core(*core_args) File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pyload/core/init.py", line 102, in init self._init_network() File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pyload/core/init.py", line 157, in _init_network from .network import request_factory File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pyload/core/network/request_factory.py", line 6, in <module> from .browser import Browser File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pyload/core/network/browser.py", line 7, in <module> from .http.http_download import HTTPDownload File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pyload/core/network/http/http_download.py", line 7, in <module> import pycurl ImportError: dlopen failed: cannot find "libssl.so" from verneed[0] in DT_NEEDED list for "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pycurl.cpython-310.so"`

### Additional references

https://www.reddit.com/r/termux/comments/uh81jm/installed_but_cannot_run_pyload/

**Comment by z8512** [comment]
`pkg update && pkg upgrade`

**Comment by GammaC0de** [comment]
libssl.so is missing so I guess you have to install openssl

**Comment by defencedog** [comment]
@GammaC0de 

```
openssl is already the newest version (3.0.2).
libcurl is already the newest version (7.83.0).                                                  
openssl-1.1 is already the newest version (1.1.1n).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```                                   

  ~ $ pip install --upgrade pyload-ng pycurl
```
Requirement already satisfied: pyload-ng in /data/data/com.termux/files/usr/lib/python3.10/site-packages (0.5.0b3.dev17)
Requirement already satisfied: pycurl in /data/data/com.termux/files/usr/lib/python3.10/site-packages (7.45.1)
```

**Comment by z8512** [comment]
@defencedog uninstall Termux and again install it from f-droid. Your problem will fix trust me
