### ISSUE TITLE
Uninstall error : FileNotFoundError [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by A-Nicoladie** [pyload/pyload#4142]
### Description

Cannot uninstall V0.5.0 on Ubuntu 22.04

```
$ pyload --version
pyLoad 0.5.0

$ python3 --version
Python 3.10.4
```

### Command log

<details>
<summary>Install log <i>(click to expand/collapse)</i></summary>

```python
$ pip install --pre pyload-ng

Defaulting to user installation because normal site-packages is not writeable
Collecting pyload-ng
  Using cached pyload_ng-0.5.0b3.dev18-py3-none-any.whl (1.6 MB)
Collecting Cheroot~=8.4
  Using cached cheroot-8.6.0-py2.py3-none-any.whl (104 kB)
Requirement already satisfied: setuptools>=38.3 in /usr/lib/python3/dist-packages (from pyload-ng) (59.6.0)
Collecting bitmath~=1.3
  Using cached bitmath-1.3.3.1.tar.gz (88 kB)
  Preparing metadata (setup.py) ... done
Collecting Flask-Babel~=1.0
  Using cached Flask_Babel-1.0.0-py3-none-any.whl (9.5 kB)
Collecting Flask~=2.0
  Using cached Flask-2.1.2-py3-none-any.whl (95 kB)
Collecting Flask-Caching~=1.9
  Using cached Flask_Caching-1.10.1-py3-none-any.whl (34 kB)
Collecting filetype~=1.0
  Using cached filetype-1.0.13-py2.py3-none-any.whl (17 kB)
Collecting Js2Py~=0.7
  Using cached Js2Py-0.71-py3-none-any.whl (1.0 MB)
Collecting Flask-Session~=0.3
  Using cached Flask_Session-0.4.0-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: cryptography~=3.0 in /usr/lib/python3/dist-packages (from pyload-ng) (3.4.8)
Collecting Flask-Themes2~=1.0
  Using cached Flask-Themes2-1.0.0.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pycurl~=7.43 in /home/xxxxxxxx/.local/lib/python3.10/site-packages (from pyload-ng) (7.45.1)
Collecting semver~=2.10
  Using cached semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting Flask-Compress~=1.8
  Using cached Flask_Compress-1.12-py3-none-any.whl (7.9 kB)
Requirement already satisfied: more-itertools>=2.6 in /usr/lib/python3/dist-packages (from Cheroot~=8.4->pyload-ng) (8.10.0)
Collecting jaraco.functools
  Downloading jaraco.functools-3.5.0-py3-none-any.whl (7.0 kB)
Requirement already satisfied: six>=1.11.0 in /usr/lib/python3/dist-packages (from Cheroot~=8.4->pyload-ng) (1.16.0)
Collecting Werkzeug>=2.0
  Downloading Werkzeug-2.1.2-py3-none-any.whl (224 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.9/224.9 KB 3.4 MB/s eta 0:00:00
Collecting itsdangerous>=2.0
  Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Requirement already satisfied: click>=8.0 in /usr/lib/python3/dist-packages (from Flask~=2.0->pyload-ng) (8.0.3)
Collecting Jinja2>=3.0
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 KB 14.9 MB/s eta 0:00:00
Requirement already satisfied: Babel>=2.3 in /home/xxxxxxxx/.local/lib/python3.10/site-packages (from Flask-Babel~=1.0->pyload-ng) (2.10.1)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from Flask-Babel~=1.0->pyload-ng) (2022.1)
Requirement already satisfied: brotli in /usr/lib/python3/dist-packages (from Flask-Compress~=1.8->pyload-ng) (1.0.9)
Collecting cachelib
  Downloading cachelib-0.6.0-py3-none-any.whl (15 kB)
Collecting pyjsparser>=2.5.1
  Downloading pyjsparser-2.7.1.tar.gz (24 kB)
  Preparing metadata (setup.py) ... done
Collecting tzlocal>=1.2
  Downloading tzlocal-4.2-py3-none-any.whl (19 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/lib/python3/dist-packages (from Jinja2>=3.0->Flask~=2.0->pyload-ng) (2.0.1)
Collecting pytz-deprecation-shim
  Downloading pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting tzdata
  Downloading tzdata-2022.1-py2.py3-none-any.whl (339 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 339.5/339.5 KB 10.1 MB/s eta 0:00:00
Building wheels for collected packages: bitmath, Flask-Themes2, pyjsparser
  Building wheel for bitmath (setup.py) ... done
  Created wheel for bitmath: filename=bitmath-1.3.3.1-py3-none-any.whl size=23990 sha256=07b6a707e351292ca497a60e29bd2b9d9739a9083747c7c4995289a4818ee727
  Stored in directory: /home/xxxxxxxx/.cache/pip/wheels/2d/32/d2/936069b5a9583c55bc7c7dce6c746a543ce61d7dfbb4013e13
  Building wheel for Flask-Themes2 (setup.py) ... done
  Created wheel for Flask-Themes2: filename=Flask_Themes2-1.0.0-py3-none-any.whl size=8111 sha256=7c4c0861ad444a1f63908da54bdf34526b430d6fe6ee154e58aabe1f5034b7ea
  Stored in directory: /home/xxxxxxxx/.cache/pip/wheels/71/55/fa/ec1f24dce16dca57837e55f570cff75d998b4c2bd9c63db505
  Building wheel for pyjsparser (setup.py) ... done
  Created wheel for pyjsparser: filename=pyjsparser-2.7.1-py3-none-any.whl size=26000 sha256=600f41f5bdff5a484dc734b149ca6fd2b7a2b059d6ad454714898f863bed7230
  Stored in directory: /home/xxxxxxxx/.cache/pip/wheels/5e/81/26/5956478df303e2bf5a85a5df595bb307bd25948a4bab69f7c7
Successfully built bitmath Flask-Themes2 pyjsparser
Installing collected packages: pyjsparser, filetype, bitmath, Werkzeug, tzdata, semver, Jinja2, jaraco.functools, itsdangerous, cachelib, pytz-deprecation-shim, Flask, Cheroot, tzlocal, Flask-Themes2, Flask-Session, Flask-Compress, Flask-Caching, Flask-Babel, Js2Py, pyload-ng
Successfully installed Cheroot-8.6.0 Flask-2.1.2 Flask-Babel-1.0.0 Flask-Caching-1.10.1 Flask-Compress-1.12 Flask-Session-0.4.0 Flask-Themes2-1.0.0 Jinja2-3.1.2 Js2Py-0.71 Werkzeug-2.1.2 bitmath-1.3.3.1 cachelib-0.6.0 filetype-1.0.13 itsdangerous-2.1.2 jaraco.functools-3.5.0 pyjsparser-2.7.1 pyload-ng-0.5.0b3.dev18 pytz-deprecation-shim-0.1.0.post0 semver-2.13.0 tzdata-2022.1 tzlocal-4.2
```
</details>

<details>
<summary>Uninstall log</summary>

```python
$ pip uninstall --pre pyload-ng

Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/lib/python3/dist-packages/pip/_internal/configuration.py", line 20, in <module>
    from pip._internal.exceptions import (
  File "/usr/lib/python3/dist-packages/pip/_internal/exceptions.py", line 14, in <module>
    from pip._vendor.rich.console import Console, ConsoleOptions, RenderResult
  File "/usr/lib/python3/dist-packages/pip/_vendor/rich/__init__.py", line 16, in <module>
    _IMPORT_CWD = os.path.abspath(os.getcwd())
FileNotFoundError: [Errno 2] No such file or directory
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 76, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/lib/python3/dist-packages/pip/_internal/configuration.py", line 20, in <module>
    from pip._internal.exceptions import (
  File "/usr/lib/python3/dist-packages/pip/_internal/exceptions.py", line 14, in <module>
    from pip._vendor.rich.console import Console, ConsoleOptions, RenderResult
  File "/usr/lib/python3/dist-packages/pip/_vendor/rich/__init__.py", line 16, in <module>
    _IMPORT_CWD = os.path.abspath(os.getcwd())
FileNotFoundError: [Errno 2] No such file or directory
```
</details>

**Comment by GammaC0de** [comment]
For me it works fine:

```
root@server:/# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
root@server:/#
root@server:/# pip uninstall pyload-ng
Found existing installation: pyload-ng 0.5.0b3.dev19
Uninstalling pyload-ng-0.5.0b3.dev19:
  Would remove:
    /usr/local/bin/pyload
    /usr/local/lib/python3.10/dist-packages/pyload/*
    /usr/local/lib/python3.10/dist-packages/pyload_ng-0.5.0b3.dev19.dist-info/*
Proceed (Y/n)?
  Successfully uninstalled pyload-ng-0.5.0b3.dev19
```

**Comment by A-Nicoladie** [comment]
Oh... I see my mistake 😳

What I did 
> pip uninstall **--pre** pyload-ng

What I needed to do
>pip uninstall pyload-ng

You wright, it works fine _(with the correct command)_

Sorry, my fault.
