### ISSUE TITLE
[SevenZip] Unable to extract encrypted (header & content) RAR Archive

### ISSUE THREAD

**Issue by BobSilent** [pyload/pyload#4161]
### Description
I thought that I already had ExtractArchive working in 0.5, but same configuration/package can be extracted in 0.4.2

Initially I had a package downloaded which had a wrong password set, 
but also removing the wrong password does not work to finally extract a package

`passwords.txt` exists with values

two observations
1. Password `None` is verified as successful, which is definitely wrong
2. `passwords.txt` gets extended (first line) with an empty line

### Debug log
```
[2022-06-02 15:08:03]  DEBUG               pyload  All downloads processed
[2022-06-02 15:08:03]  INFO                pyload  ADDON ExtractArchive: Check package: The.Wire.S05.German.DL.720p.BluRay.x264-iNTENTiON - filecrypt.cc
[2022-06-02 15:08:03]  DEBUG               pyload  ADDON ExtractArchive: Targets for SevenZip: [(8847, '/downloads/The.Wire.S05.German.DL.720p.BluRay.x264-iNTENTiON - filecrypt.cc/TW1-5X01.part1.rar', '/downloads/'), (8850, '/downloads/The.Wire.S05.German.DL.720p.BluRay.x264-iNTENTiON - filecrypt.cc/TW1-5X02.part1.rar', '/downloads/'), (8853, '/downloads/The.Wire.S05.German.DL.720p.BluRay.x264-iNTENTiON - filecrypt.cc/TW1-5X03.part1.rar', '/downloads/'), (8856, '/downloads/The.Wire.S05.German.DL.720p.BluRay.x264-iNTENTiON - filecrypt.cc/TW1-5X04.part1.rar', '/downloads/'), (8859, '/downloads/The.Wire.S05.German.DL.720p.BluRay.x264-iNTENTiON - filecrypt.cc/TW1-5X05.part1.rar', '/downloads/'), (8862, '/downloads/The.Wire.S05.German.DL.720p.BluRay.x264-iNTENTiON - filecrypt.cc/TW1-5X06.part1.rar', '/downloads/'), (8865, '/downloads/The.Wire.S05.German.DL.720p.BluRay.x264-iNTENTiON - filecrypt.cc/TW1-5X07.part1.rar', '/downloads/'), (8868, '/downloads/The.Wire.S05.German.DL.720p.BluRay.x264-iNTENTiON - filecrypt.cc/TW1-5X08.part1.rar', '/downloads/'), (8871, '/downloads/The.Wire.S05.German.DL.720p.BluRay.x264-iNTENTiON - filecrypt.cc/TW1-5X09.part1.rar', '/downloads/'), (8874, '/downloads/The.Wire.S05.German.DL.720p.BluRay.x264-iNTENTiON - filecrypt.cc/TW1-5X10.part1.rar', '/downloads/')]
[2022-06-02 15:08:03]  INFO                pyload  ADDON ExtractArchive: TW1-5X01.part1.rar | Extract to: /downloads/
[2022-06-02 15:08:03]  DEBUG               pyload  ADDON ExtractArchive: Password: None
[2022-06-02 15:08:03]  DEBUG               pyload  ADDON ExtractArchive: Verifying using password: None
[2022-06-02 15:08:03]  DEBUG               pyload  EXTRACTOR SevenZip: EXECUTE 7z l -scsUTF-8 -sccUTF-8 -bso0 -bsp1 -aos -xr!*.DS_Store -xr!index.dat -xr!thumb.db -xr!Readme(Liesmich).html -xr!*.url -xr!*.URL -xr!*/Proof* -xr!*/Sample* -p- -slt /downloads/The.Wire.S05.German.DL.720p.BluRay.x264-iNTENTiON - filecrypt.cc/TW1-5X01.part1.rar
[2022-06-02 15:08:03]  DEBUG               pyload  ADDON ExtractArchive: Password Correct
[2022-06-02 15:08:03]  DEBUG               pyload  ADDON ExtractArchive: Extracting using password: None
[2022-06-02 15:08:03]  DEBUG               pyload  EXTRACTOR SevenZip: EXECUTE 7z x -scsUTF-8 -sccUTF-8 -bso0 -bsp1 -aos -xr!*.DS_Store -xr!index.dat -xr!thumb.db -xr!Readme(Liesmich).html -xr!*.url -xr!*.URL -xr!*/Proof* -xr!*/Sample* -p- -o/downloads/ /downloads/The.Wire.S05.German.DL.720p.BluRay.x264-iNTENTiON - filecrypt.cc/TW1-5X01.part1.rar
[2022-06-02 15:08:03]  ERROR               pyload  ADDON ExtractArchive: TW1-5X01.part1.rar | No password found
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pyload/plugins/addons/ExtractArchive.py", line 501, in _extract
    archive.extract(password)
  File "/usr/lib/python3.9/site-packages/pyload/plugins/extractors/SevenZip.py", line 186, in extract
    raise PasswordError
pyload.plugins.base.extractor.PasswordError
[2022-06-02 15:08:03]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `archive_extract_failed`
[2022-06-02 15:08:03]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `all_downloads_finished`
[2022-06-02 15:08:03]  DEBUG               pyload  All downloads finished
[2022-06-02 15:08:03]  ERROR               pyload  ADDON ExtractArchive: TW1-5X01.part1.rar | Extract failed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pyload/plugins/addons/ExtractArchive.py", line 330, in extract
    new_files = self._extract(
  File "/usr/lib/python3.9/site-packages/pyload/plugins/addons/ExtractArchive.py", line 568, in _extract
    raise Exception(self._("Extract failed"))
Exception: Extract failed

```

Also with a definetly wrong password the result is `ADDON ExtractArchive: Password Correct` and it fails
```
[2022-06-02 15:28:39]  DEBUG               pyload  ADDON ExtractArchive: Password: wrongPasswordSet
[2022-06-02 15:28:39]  DEBUG               pyload  ADDON ExtractArchive: Verifying using password: wrongPasswordSet
[2022-06-02 15:28:39]  DEBUG               pyload  EXTRACTOR SevenZip: EXECUTE 7z l -scsUTF-8 -sccUTF-8 -bso0 -bsp1 -aos -xr!*.DS_Store -xr!index.dat -xr!thumb.db -xr!Readme(Liesmich).html -xr!*.url -xr!*.URL -xr!*/Proof* -xr!*/Sample* -p- -slt /downloads/The.Wire.S05.German.DL.720p.BluRay.x264-iNTENTiON - filecrypt.cc/TW1-5X01.part1.rar
[2022-06-02 15:28:39]  DEBUG               pyload  ADDON ExtractArchive: Password Correct
[2022-06-02 15:28:39]  DEBUG               pyload  ADDON ExtractArchive: Extracting using password: wrongPasswordSet
[2022-06-02 15:28:39]  DEBUG               pyload  EXTRACTOR SevenZip: EXECUTE 7z x -scsUTF-8 -sccUTF-8 -bso0 -bsp1 -aos -xr!*.DS_Store -xr!index.dat -xr!thumb.db -xr!Readme(Liesmich).html -xr!*.url -xr!*.URL -xr!*/Proof* -xr!*/Sample* -pwrongPasswordSet -o/downloads/ /downloads/The.Wire.S05.German.DL.720p.BluRay.x264-iNTENTiON - filecrypt.cc/TW1-5X01.part1.rar
[2022-06-02 15:28:39]  ERROR               pyload  ADDON ExtractArchive: TW1-5X01.part1.rar | Wrong password
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pyload/plugins/addons/ExtractArchive.py", line 501, in _extract
    archive.extract(password)
  File "/usr/lib/python3.9/site-packages/pyload/plugins/extractors/SevenZip.py", line 186, in extract
    raise PasswordError
pyload.plugins.base.extractor.PasswordError
```
### Additional references
deployment: docker `linuxserver/docker-pyload-ng`

**Comment by GammaC0de** [comment]
Sample URLs please.

**Comment by BobSilent** [comment]
Please see PR #4162 as well.

it seems that rar and 7z files behave different when headers/filenames are encrypted.

you can test it with the command `7z l -scsUTF-8 -sccUTF-8 -bso0 -bsp1 -aos -p- -slt  <filename>`

for Testing you can use these example files here (simply remove trailing `.TXT` extension):
[7zz_withfilenames.rar.TXT](https://github.com/pyload/pyload/files/8856424/7zz_withfilenames.rar.TXT)
[7zz_withfilenames.7z.TXT](https://github.com/pyload/pyload/files/8856429/7zz_withfilenames.7z.TXT)

and call 
```bash
#  7z l -scsUTF-8 -sccUTF-8 -bso0 -bsp1 -aos -p- -slt "7zz_withfilenames.7z"
         
Listing archive: 7zz_withfilenames.7z


ERROR: 7zz_withfilenames.7z : Cannot open encrypted archive. Wrong password?

ERRORS:
Headers Error


Errors: 1
```

and
```bash
# 7z l -scsUTF-8 -sccUTF-8 -bso0 -bsp1 -aos -p- -slt "7zz_withfilenames.rar"
         
Listing archive: 7zz_withfilenames.rar


ERROR: 7zz_withfilenames.rar : Cannot open encrypted archive. Wrong password?



Errors: 1
```

just for completeness, the same without encrypted filenames:
[7zz_nofilenames.rar.TXT](https://github.com/pyload/pyload/files/8856425/7zz_nofilenames.rar.TXT)
[7zz_nofilenames.7z.TXT](https://github.com/pyload/pyload/files/8856430/7zz_nofilenames.7z.TXT)
