### ISSUE TITLE
Occasionally `Operation not permitted` on OS operation after download

### ISSUE THREAD

**Issue by efelon** [pyload/pyload#4183]
### Question
Occasionally I get  `Operation not permitted` after the download of a file is complete (final rar and also its chunks are present in the download folder). Due to this error further processing like unrar and delete downloaded files is then stopped for the complete package. I have a feeling it only happens when multiple packages are active at same time.

The cause seams to be:
```
Frame copystat in /usr/lib/python2.7/shutil.py at line 118
                         src = u'/mnt/cifs/somefile.rar.chunk0'
                         dst = u'/mnt/cifs/somefile.rar'
                        mode = 509
                          st = posix.stat_result(st_mode=33277, st_ino=70123985, st_dev=52, st_nlink=1, st_uid=106, st_gid=113, st_size=581474718, st_atime=1660302424, st_mtime=1660302424, st_ctime=1660302424)
```

I'm downloading/unrar directly on a CIFS mount, which might be the trouble maker.

Has anyone also seen this and can point me to a possible solution?

### Logs
```
pyLoad 0.4.20 Debug Report of UploadedTo 0.34

TRACEBACK:
 Traceback (most recent call last):
  File "/opt/downloaders/pyload/module/PluginThread.py", line 189, in run
    pyfile.plugin.preprocessing(self)
  File "/opt/downloaders/pyload/module/plugins/internal/Base.py", line 290, in preprocessing
    return self._process(*args, **kwargs)
  File "/opt/downloaders/pyload/module/plugins/internal/MultiHoster.py", line 70, in _process
    SimpleHoster._process(self, thread)
  File "/opt/downloaders/pyload/module/plugins/internal/Hoster.py", line 118, in _process
    self.process(self.pyfile)
  File "/opt/downloaders/pyload/module/plugins/internal/SimpleHoster.py", line 277, in process
    self.handle_premium(pyfile)
  File "/opt/downloaders/pyload/module/plugins/hoster/PremiumizeMe.py", line 48, in handle_premium
    self.download(res['content'][0]['link'])
  File "/opt/downloaders/pyload/module/plugins/internal/Hoster.py", line 308, in download
    disposition, resume, chunks)
  File "/opt/downloaders/pyload/module/plugins/internal/Hoster.py", line 237, in _download
    status_notify=self._on_notification, disposition=disposition)
  File "/opt/downloaders/pyload/module/network/Browser.py", line 89, in httpDownload
    name = self.dl.download(chunks, resume)
  File "/opt/downloaders/pyload/module/network/HTTPDownload.py", line 130, in download
    self._download(chunks, resume)
  File "/opt/downloaders/pyload/module/network/HTTPDownload.py", line 298, in _download
    self._copyChunks()
  File "/opt/downloaders/pyload/module/network/HTTPDownload.py", line 120, in _copyChunks
    move(init, fs_encode(self.filename))
  File "/usr/lib/python2.7/shutil.py", line 325, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 154, in copy2
    copystat(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 118, in copystat
    os.utime(dst, (st.st_atime, st.st_mtime))
OSError: [Errno 1] Operation not permitted: '/mnt/cifs/somefile.rar'
```

<details><summary>more detailed log</summary>

```
Frame _download in /opt/downloaders/pyload/module/network/HTTPDownload.py at line 298
                       chunk = <HTTPChunk id=0, size=581474717, arrived=581474718>
                        done = True
                          ex = None
                      chunks = 1
                        diff = [458752]
                        curl = <pycurl.Curl object at 0xffff9448b6f0>
               chunksCreated = True
                       errno = 23
                        self = <module.network.HTTPDownload.HTTPDownload instance at 0xffff9076fc68>
                         ret = 0
                      failed = []
                        init = <HTTPChunk id=0, size=581474717, arrived=581474718>
                 num_handles = 0
                         msg = 'Failed writing body (0 != 6558)'
                  chunksDone = set([<pycurl.Curl object at 0xffff9448b6f0>])
             lastFinishCheck = 1660302373.880951
                      resume = False
                    err_list = [(<pycurl.Curl object at 0xffff9448b6f0>,
  23,
  'Failed writing body (0 != 6558)')]
                     ok_list = []
                       num_q = 0
                           a = 458752
                           c = (<pycurl.Curl object at 0xffff9448b6f0>, 23, 'Failed writing body (0 != 6558)')
                           i = 0
                           t = 1660302373.880951
               lastTimeCheck = 1660302373.226006

Frame _copyChunks in /opt/downloaders/pyload/module/network/HTTPDownload.py at line 120
                        init = u'/mnt/cifs/somefile.rar.chunk0'
                        self = <module.network.HTTPDownload.HTTPDownload instance at 0xffff9076fc68>

Frame move in /usr/lib/python2.7/shutil.py at line 325
                    real_dst = u'/mnt/cifs/somefile.rar'
                         src = u'/mnt/cifs/somefile.rar.chunk0'
                         dst = u'/mnt/cifs/somefile.rar'

Frame copy2 in /usr/lib/python2.7/shutil.py at line 154
                         src = u'/mnt/cifs/somefile.rar.chunk0'
                         dst = u'/mnt/cifs/somefile.rar'

Frame copystat in /usr/lib/python2.7/shutil.py at line 118
                         src = u'/mnt/cifs/somefile.rar.chunk0'
                         dst = u'/mnt/cifs/somefile.rar'
                        mode = 509
                          st = posix.stat_result(st_mode=33277, st_ino=70123985, st_dev=52, st_nlink=1, st_uid=106, st_gid=113, st_size=581474718, st_atime=1660302424, st_mtime=1660302424, st_ctime=1660302424)
```

</details>

**Comment by GammaC0de** [comment]
It looks like a issue with your CIFS mount since I have not seen this issue before.
Try downloading to a local folder and see what happens.
