### ISSUE TITLE
Unable to install pyload-ng on Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by mellonguie** [pyload/pyload#4189]
### Description

When I tried to execute the following command line : `pip install --pre pyload-ng`
I got below error :
```
Defaulting to user installation because normal site-packages is not writeable
Collecting pyload-ng
  Downloading pyload_ng-0.5.0b3.dev24-py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 16.2 MB/s eta 0:00:00
Collecting Flask-Session~=0.3
  Downloading Flask_Session-0.4.0-py2.py3-none-any.whl (7.5 kB)
Collecting Js2Py~=0.7
  Downloading Js2Py-0.71-py3-none-any.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 32.8 MB/s eta 0:00:00
Collecting filetype~=1.0
  Downloading filetype-1.1.0-py2.py3-none-any.whl (17 kB)
Collecting pycurl~=7.43
  Downloading pycurl-7.45.1.tar.gz (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.9/233.9 KB 23.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-install-vu3jxzc5/pycurl_1e88e652756f42579d1af48a646dbf00/setup.py", line 235, in configure_unix
          p = subprocess.Popen((self.curl_config(), '--version'),
        File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'curl-config'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vu3jxzc5/pycurl_1e88e652756f42579d1af48a646dbf00/setup.py", line 1017, in <module>
          ext = get_extension(sys.argv, split_extension_source=split_extension_source)
        File "/tmp/pip-install-vu3jxzc5/pycurl_1e88e652756f42579d1af48a646dbf00/setup.py", line 673, in get_extension
          ext_config = ExtensionConfiguration(argv)
        File "/tmp/pip-install-vu3jxzc5/pycurl_1e88e652756f42579d1af48a646dbf00/setup.py", line 99, in __init__
          self.configure()
        File "/tmp/pip-install-vu3jxzc5/pycurl_1e88e652756f42579d1af48a646dbf00/setup.py", line 240, in configure_unix
          raise ConfigurationError(msg)
      __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Debug log

```

```

### Additional references

```
$ uname -a
Linux JP_MELLO 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

### Screenshots

![failed_to_install_pyload-ng](https://user-images.githubusercontent.com/48562379/185044056-4ec6dd95-58dd-47b0-9ae2-73104ba881c9.PNG)

**Comment by GammaC0de** [comment]
👍

**Comment by jaum20** [comment]
I have this problem too. I tried:

```
sudo apt install libcurl4-openssl-dev libssl-dev

libcurl4-openssl-dev is already the newest version (7.68.0-1ubuntu2.18).
libssl-dev is already the newest version (1.1.1f-1ubuntu2.18).
```
any ideas?

**Comment by mellonguie** [comment]
Hi @jaum20 ,

As this thread discussion has been already closed, I'm not sure that someone else in the community can see your comment except all persons who have replied in this ticket.
I suggest you to create a new issue and provide as much details as possible.
You can take as example what I done in the current description.
You can also put as reference this ticket.
Good luck ! ;)
