### ISSUE TITLE
Startup error: brotli

### ISSUE THREAD

**Issue by UserX404** [pyload/pyload#4201]
### Install support wanted!
I needed to update my Entware installation and therefor i had to reinstall pyload.
Now I'm not able to start pyload due to a module import error. So i need help to figure out what's going wrong.
As far as i know i did exact the same install steps for my last installation.
May I ask someone could spend a little time for support to help me to bring my pyload up again?! :-)

- First i uninstalled the old installation 
- Then reinstall with:
`python -m pip install --pre pyload-ng[all]`

**Output:**
```
Collecting pyload-ng[all]
  Downloading pyload_ng-0.5.0b3.dev26-py3-none-any.whl (1.6 MB)
     ââââââââââââââââââââââââââââââââââââââââ 1.6/1.6 MB 11.0 MB/s eta 0:00:00
Requirement already satisfied: Flask-Caching~=1.9 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (1.11.1)
Requirement already satisfied: Js2Py~=0.7 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (0.71)
Requirement already satisfied: Flask-Themes2~=1.0 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (1.0.0)
Requirement already satisfied: bitmath~=1.3 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (1.3.3.1)
Requirement already satisfied: Flask~=2.0 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (2.2.2)
Requirement already satisfied: Flask-Session~=0.3 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (0.4.0)
Requirement already satisfied: Flask-Babel~=1.0 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (1.0.0)
Requirement already satisfied: Cheroot~=8.4 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (8.6.0)
Requirement already satisfied: pycurl~=7.43 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (7.44.0)
Requirement already satisfied: setuptools>=38.3 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (58.1.0)
Requirement already satisfied: cryptography>=35.0.0 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (38.0.1)
Requirement already satisfied: semver~=2.10 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (2.13.0)
Requirement already satisfied: filetype~=1.0 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (1.1.0)
Requirement already satisfied: Flask-Compress~=1.8 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (1.13)
Requirement already satisfied: Pillow in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (9.2.0)
Collecting colorlog
  Downloading colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Collecting pyOpenSSL
  Downloading pyOpenSSL-22.1.0-py3-none-any.whl (57 kB)
     ââââââââââââââââââââââââââââââââââââââââ 57.0/57.0 kB 10.1 MB/s eta 0:00:00
Collecting slixmpp
  Downloading slixmpp-1.8.2.tar.gz (535 kB)
     ââââââââââââââââââââââââââââââââââââââââ 535.7/535.7 kB 15.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
     ââââââââââââââââââââââââââââââââââââââââ 128.2/128.2 kB 15.9 MB/s eta 0:00:00
Requirement already satisfied: Babel in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pyload-ng[all]) (2.10.3)
Collecting Send2Trash
  Downloading Send2Trash-1.8.1b0-py3-none-any.whl (17 kB)
Collecting Jinja2==3.0.3
  Downloading Jinja2-3.0.3-py3-none-any.whl (133 kB)
     ââââââââââââââââââââââââââââââââââââââââ 133.6/133.6 kB 24.0 MB/s eta 0:00:00
Requirement already satisfied: MarkupSafe>=2.0 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from Jinja2==3.0.3->pyload-ng[all]) (2.1.1)
Requirement already satisfied: six>=1.11.0 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from Cheroot~=8.4->pyload-ng[all]) (1.16.0)
Requirement already satisfied: more-itertools>=2.6 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from Cheroot~=8.4->pyload-ng[all]) (8.14.0)
Requirement already satisfied: jaraco.functools in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from Cheroot~=8.4->pyload-ng[all]) (3.5.2)
Requirement already satisfied: cffi>=1.12 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from cryptography>=35.0.0->pyload-ng[all]) (1.15.0)
Requirement already satisfied: click>=8.0 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from Flask~=2.0->pyload-ng[all]) (8.1.3)
Requirement already satisfied: Werkzeug>=2.2.2 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from Flask~=2.0->pyload-ng[all]) (2.2.2)
Requirement already satisfied: itsdangerous>=2.0 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from Flask~=2.0->pyload-ng[all]) (2.1.2)
Requirement already satisfied: pytz in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from Flask-Babel~=1.0->pyload-ng[all]) (2022.4)
Requirement already satisfied: cachelib in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from Flask-Caching~=1.9->pyload-ng[all]) (0.9.0)
Requirement already satisfied: brotli in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from Flask-Compress~=1.8->pyload-ng[all]) (1.0.9)
Requirement already satisfied: pyjsparser>=2.5.1 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from Js2Py~=0.7->pyload-ng[all]) (2.7.1)
Requirement already satisfied: tzlocal>=1.2 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from Js2Py~=0.7->pyload-ng[all]) (4.2)
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Collecting aiodns>=1.0
  Downloading aiodns-3.0.0-py3-none-any.whl (5.0 kB)
Collecting pyasn1
  Downloading pyasn1-0.5.0rc2-py2.py3-none-any.whl (83 kB)
     ââââââââââââââââââââââââââââââââââââââââ 83.7/83.7 kB 11.3 MB/s eta 0:00:00
Collecting pyasn1_modules
  Downloading pyasn1_modules-0.3.0rc1-py2.py3-none-any.whl (181 kB)
     ââââââââââââââââââââââââââââââââââââââââ 181.3/181.3 kB 19.9 MB/s eta 0:00:00
Collecting pycares>=4.0.0
  Downloading pycares-4.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (289 kB)
     ââââââââââââââââââââââââââââââââââââââââ 289.4/289.4 kB 18.1 MB/s eta 0:00:00
Requirement already satisfied: pycparser in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from cffi>=1.12->cryptography>=35.0.0->pyload-ng[all]) (2.21)
Requirement already satisfied: pytz-deprecation-shim in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from tzlocal>=1.2->Js2Py~=0.7->pyload-ng[all]) (0.1.0.post0)
Requirement already satisfied: tzdata in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages (from pytz-deprecation-shim->tzlocal>=1.2->Js2Py~=0.7->pyload-ng[all]) (2022.4)
Using legacy 'setup.py install' for slixmpp, since package 'wheel' is not installed.
Installing collected packages: soupsieve, Send2Trash, pyasn1, Jinja2, colorlog, pycares, pyasn1_modules, beautifulsoup4, pyOpenSSL, aiodns, slixmpp, pyload-ng
  Attempting uninstall: Jinja2
    Found existing installation: Jinja2 3.1.2
    Uninstalling Jinja2-3.1.2:
      Successfully uninstalled Jinja2-3.1.2
  Running setup.py install for slixmpp ... done
Successfully installed Jinja2-3.0.3 Send2Trash-1.8.1b0 aiodns-3.0.0 beautifulsoup4-4.11.1 colorlog-6.7.0 pyOpenSSL-22.1.0 pyasn1-0.5.0rc2 pyasn1_modules-0.3.0rc1 pycares-4.2.2 pyload-ng-0.5.0b3.dev26 slixmpp-1.8.2 soupsieve-2.3.2.post1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```
- start pyload:
`pyload --userdir /opt/var/pyload --storagedir /share/Download/Pyload --tempdir /opt/tmp/pyload`

**Output:**
```
[2022-10-03 19:38:21]  INFO                pyload  *** Welcome to pyLoad 0.5.0 ***
[2022-10-03 19:38:21]  DEBUG               pyload  Indexing plugins...
[2022-10-03 19:38:22]  INFO                pyload  Activated plugins: Captcha9Kw, ClickNLoad, ExternalScripts, ExtractArchive, TORRENT, UnSkipOnFail, UserAgentSwitcher, XFileSharing
[2022-10-03 19:38:22]  INFO                pyload  Deactivate plugins: AndroidPhoneNotify, AntiCaptcha, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, UpdateManager, WindowsPhoneNotify, XMPP
ModuleNotFoundError: No module named '_brotli'
Traceback (most recent call last):
  File "/opt/bin/pyload", line 8, in <module>
    sys.exit(main())
  File "/opt/lib/python3.10/site-packages/pyload/__main__.py", line 292, in main
    run(core_args, args.daemon, args.pidfile)
  File "/opt/lib/python3.10/site-packages/pyload/__main__.py", line 235, in run
    pyload_core = Core(*core_args)
  File "/opt/lib/python3.10/site-packages/pyload/core/__init__.py", line 105, in __init__
    self._init_webserver()
  File "/opt/lib/python3.10/site-packages/pyload/core/__init__.py", line 168, in _init_webserver
    from pyload.webui.webserver_thread import WebServerThread
  File "/opt/lib/python3.10/site-packages/pyload/webui/webserver_thread.py", line 9, in <module>
    from .app import App
  File "/opt/lib/python3.10/site-packages/pyload/webui/app/__init__.py", line 19, in <module>
    from .extensions import EXTENSIONS, THEMES
  File "/opt/lib/python3.10/site-packages/pyload/webui/app/extensions.py", line 5, in <module>
    from flask_compress import Compress
  File "/opt/lib/python3.10/site-packages/flask_compress/__init__.py", line 1, in <module>
    from .flask_compress import Compress
  File "/opt/lib/python3.10/site-packages/flask_compress/flask_compress.py", line 14, in <module>
    import brotli
  File "/opt/lib/python3.10/site-packages/brotli.py", line 8, in <module>
    import _brotli
ModuleNotFoundError: No module named '_brotli'
```

### Additional references

**python version:** Python 3.10.5
**python packaged:**
`python -m pip list`
```
Package               Version
--------------------- -------------
aiodns                3.0.0
Babel                 2.10.3
beautifulsoup4        4.11.1
bitmath               1.3.3.1
Brotli                1.0.9
cachelib              0.9.0
cffi                  1.15.0
cheroot               8.6.0
click                 8.1.3
colorlog              6.7.0
cryptography          38.0.1
filetype              1.1.0
Flask                 2.2.2
Flask-Babel           1.0.0
Flask-Caching         1.11.1
Flask-Compress        1.13
Flask-Session         0.4.0
Flask-Themes2         1.0.0
itsdangerous          2.1.2
jaraco.functools      3.5.2
Jinja2                3.0.3
Js2Py                 0.71
MarkupSafe            2.1.1
more-itertools        8.14.0
Pillow                9.2.0
pip                   22.2.2
pyasn1                0.5.0rc2
pyasn1-modules        0.3.0rc1
pycares               4.2.2
pycparser             2.21
pycurl                7.44.0
pyjsparser            2.7.1
pyload-ng             0.5.0b3.dev26
pyOpenSSL             22.1.0
pytz                  2022.4
pytz-deprecation-shim 0.1.0.post0
semver                2.13.0
Send2Trash            1.8.1b0
setuptools            58.1.0
six                   1.16.0
slixmpp               1.8.2
soupsieve             2.3.2.post1
tzdata                2022.4
tzlocal               4.2
Werkzeug              2.2.2
```
Files are in place but it seems brotli doesn't get loaded
`ls -l /opt/lib/python3.10/site-packages/ | grep brotli`
```
-rwxr-xr-x  1 admin administrators 6726712 2022-10-03 18:39 _brotli.cpython-310-x86_64-linux-gnu.so*
-rw-r--r--  1 admin administrators    1857 2022-10-03 18:39 brotli.py

```

**Comment by GammaC0de** [comment]
@UserX404 I see you have asked the same question in the past, so here is a reminder: https://github.com/pyload/pyload/issues/3934#issuecomment-830970839,
Hope it helps.

**Comment by UserX404** [comment]
Hahahah
Oh damn :joy:
Thankfully your retrospection is better than mine.
Thank you for guid me to my **own**  solution.
Hahah :+1:

**Comment by GammaC0de** [comment]
hahahaha :tongue:
