### ISSUE TITLE
Anticaptcha not working - ‘url’ key error

### ISSUE THREAD

**Issue by paulmorabito** [pyload/pyload#4212]
Hi,

I’m running the latest stable image in docker on a Debian Linux based host. I’m trying to get a captcha service up and working and am having issues with AntiCaptcha and it’s plugin. The error is below:

```
apidgatorNet[6]: Processing url: https://rapidgator.net/file/XXXX
26.10.2022 21:44:48 INFO      HOSTER RapidgatorNet[6]: Looking for direct download link...
26.10.2022 21:44:49 INFO      HOSTER RapidgatorNet[6]: Direct download link not found
26.10.2022 21:44:49 INFO      HOSTER RapidgatorNet[6]: Checking for link errors...
26.10.2022 21:44:49 INFO      HOSTER RapidgatorNet[6]: No errors found
26.10.2022 21:44:49 INFO      HOSTER RapidgatorNet[6]: Processing as free download...
26.10.2022 21:44:49 INFO      HOSTER RapidgatorNet[6]: Waiting 3 minutes...
26.10.2022 21:47:51 WARNING   CAPTCHA RapidgatorNet[6]: ReCaptcha | Key pattern not found
26.10.2022 21:47:52 INFO      CAPTCHA RapidgatorNet[6]: SolveMedia | Using OCR to decrypt captcha...
26.10.2022 21:47:52 WARNING   CAPTCHA RapidgatorNet[6]: SolveMedia | No OCR result
26.10.2022 21:47:54 INFO      ADDON AntiCaptcha: Credits left: 0.05$
Exception in thread Thread-46:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/app/pyload/module/PluginThread.py", line 465, in run
    self.f(*self.args, **self.kwargs)
  File "/app/pyload/module/plugins/hooks/AntiCaptcha.py", line 64, in _process_captcha
    url_p = urlparse.urlparse(task.captchaParams["url"])
KeyError: 'url'
26.10.2022 21:52:54 WARNING   CAPTCHA RapidgatorNet[6]: SolveMedia | Invalid captcha | No captcha result obtained in appropriate timing (120s)
```

I’m new to pyload so not sure where to check from here. Any help would be very appreciated.

Thanks,

**Comment by GammaC0de** [comment]
Thanks.
