### ISSUE TITLE
Pyload is not Working on Mac Air M1

### ISSUE THREAD

**Issue by ShubhamJ010** [pyload/pyload#4220]
### Description

- So I installed PYload using ``` pip install --pre pyload-ng[all] ``` but without the [all] tags
- And then i ran ``` pyload ``` but it didn't  work and gave me this pycurl error
- i ran --debug and there was this same error mentioned below

So I tried to resolve the pycurl error installing pycurl
```
pip install pycurl
Requirement already satisfied: pycurl in /opt/homebrew/lib/python3.11/site-packages (7.45.1)
```
so as u can see its already present
### Debug log

```
[2022-11-13 17:08:19]  INFO                pyload  *** Welcome to pyLoad 0.5.0 ***
ImportError: pycurl: libcurl link-time ssl backends (secure-transport, openssl) do not include compile-time ssl backend (none/other)
Traceback (most recent call last):
  File "/opt/homebrew/bin/pyload", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pyload/__main__.py", line 292, in main
    run(core_args, args.daemon, args.pidfile)
  File "/opt/homebrew/lib/python3.11/site-packages/pyload/__main__.py", line 235, in run
    pyload_core = Core(*core_args)
                  ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pyload/core/__init__.py", line 102, in __init__
    self._init_network()
  File "/opt/homebrew/lib/python3.11/site-packages/pyload/core/__init__.py", line 157, in _init_network
    from .network import request_factory
  File "/opt/homebrew/lib/python3.11/site-packages/pyload/core/network/request_factory.py", line 6, in <module>
    from .browser import Browser
  File "/opt/homebrew/lib/python3.11/site-packages/pyload/core/network/browser.py", line 7, in <module>
    from .http.http_download import HTTPDownload
  File "/opt/homebrew/lib/python3.11/site-packages/pyload/core/network/http/http_download.py", line 7, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backends (secure-transport, openssl) do not include compile-time ssl backend (none/other)
```

### Screenshots

![image](https://user-images.githubusercontent.com/40000538/201520008-19c71016-a0d4-4ab8-8d79-5e796c843868.png)
<img width="642" alt="image" src="https://user-images.githubusercontent.com/40000538/201524095-2b1fa4d1-db2f-4da7-b4df-41f0c9342a9a.png">

**Comment by GammaC0de** [comment]
See https://stackoverflow.com/questions/47888757/importerror-pycurl-libcurl-link-time-ssl-backend-openssl-is-different-from-c

**Comment by ShubhamJ010** [comment]
```
src/pycurl.h:178:13: fatal error: 'openssl/ssl.h' file not found
      #   include <openssl/ssl.h>
                  ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
```

**Comment by GammaC0de** [comment]
No response, closing.
