### ISSUE TITLE
uloz.to download errors

### ISSUE THREAD

**Issue by ririko5834** [pyload/pyload#4234]
![image](https://user-images.githubusercontent.com/64729293/209821914-40889483-74fc-4669-a2fa-276eb3f9b542.png)
I cant get the download finish

**Comment by ririko5834** [comment]
![image](https://user-images.githubusercontent.com/64729293/209826613-7a6b21b4-f1ac-4709-b436-02b463256417.png)

When I reload it, it downloads, but later fails again with the same error.

What can be the issue?

**Comment by GammaC0de** [comment]
Are you using some kind of VPN/proxy?
It seems like a network issue.

**Comment by ririko5834** [comment]
No Im directly connected to my home network using ethernet cable

**Comment by ririko5834** [comment]
Error log>

Reversed:   Lines per page:  
34
1874	2023-01-11 19:40:40	DEBUG	pyload	Chunk 1 failed: (56, 'OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0')
1875	2023-01-11 19:40:40	INFO	pyload	ANTICAPTCHA UlozTo[10]: BaseCaptcha | Correct captcha | Dske
1876	2023-01-11 19:40:40	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_processed`
1877	2023-01-11 19:40:40	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `package_processed`
1878	2023-01-11 19:40:40	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `package_failed`
1879	2023-01-11 19:40:40	WARNING	pyload	Download failed: Psi ostrov (2018) CZ dabing NOVINKA.mkv | (56, 'OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0')
1880	?	?	?	Traceback (most recent call last):
1881	?	?	?	  File "/usr/local/lib/python3.10/dist-packages/pyload/core/threads/download_thread.py", line 56, in run
1882	?	?	?	    pyfile.plugin.preprocessing(self)
1883	?	?	?	  File "/usr/local/lib/python3.10/dist-packages/pyload/plugins/base/hoster.py", line 291, in preprocessing
1884	?	?	?	    return self._process(*args, **kwargs)
1885	?	?	?	  File "/usr/local/lib/python3.10/dist-packages/pyload/plugins/base/downloader.py", line 103, in _process
1886	?	?	?	    self.process(self.pyfile)
1887	?	?	?	  File "/usr/local/lib/python3.10/dist-packages/pyload/plugins/base/simple_downloader.py", line 282, in process
1888	?	?	?	    self.handle_free(pyfile)
1889	?	?	?	  File "/usr/local/lib/python3.10/dist-packages/pyload/plugins/downloaders/UlozTo.py", line 209, in handle_free
1890	?	?	?	    self.download(jsvars["slowDownloadLink"])
1891	?	?	?	  File "/usr/local/lib/python3.10/dist-packages/pyload/plugins/base/downloader.py", line 332, in download
1892	?	?	?	    newname = self._download(
1893	?	?	?	  File "/usr/local/lib/python3.10/dist-packages/pyload/plugins/base/downloader.py", line 238, in _download
1894	?	?	?	    newname = self.req.http_download(
1895	?	?	?	  File "/usr/local/lib/python3.10/dist-packages/pyload/core/network/browser.py", line 116, in http_download
1896	?	?	?	    name = self.dl.download(chunks, resume)
1897	?	?	?	  File "/usr/local/lib/python3.10/dist-packages/pyload/core/network/http/http_download.py", line 132, in download
1898	?	?	?	    self._download(chunks, resume)
1899	?	?	?	  File "/usr/local/lib/python3.10/dist-packages/pyload/core/network/http/http_download.py", line 276, in _download
1900	?	?	?	    raise ex or Exception
1901	?	?	?	pycurl.error: (56, 'OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0')
1902	2023-01-11 19:40:40	INFO	pyload	Debug Report written to /tmp/pyLoad/debug_UlozTo_2023-01-11_19-40-40.zip
1903	2023-01-11 19:40:40	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_failed`
1904	2023-01-11 19:40:40	INFO	pyload	ADDON UnSkipOnFail: Looking for skipped duplicates of: Psi ostrov (2018) CZ dabing NOVINKA.mkv (pid:2)
1905	2023-01-11 19:40:40	INFO	pyload	ADDON UnSkipOnFail: No duplicates found
1906	2023-01-11 19:40:40	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
1907	2023-01-11 19:40:40	DEBUG	pyload	All downloads processed

**Comment by ririko5834** [comment]
![image](https://user-images.githubusercontent.com/64729293/212470353-e6e5113c-be44-4e0a-8904-5f0b11b2ff0e.png)

**Comment by ririko5834** [comment]
@danoslas

**Comment by GammaC0de** [comment]
I have tested it again and it works fine.
So the issue is probably on your side.

Please send a sample problematic URL so I can test.

**Comment by ririko5834** [comment]
![image](https://user-images.githubusercontent.com/64729293/213743500-594d13d8-8bfe-4f81-803a-4433064c0769.png)
for example https://ulozto.net/file/0jWiwQyAXTmb/snezny-kluk-cz-dabing-mkv#!ZJZ2AwR2AmpjMwD5MzAvZ2L3MJRjLzWgISthFKMlH191o2L5BN==

![image](https://user-images.githubusercontent.com/64729293/213743942-235787f2-6c83-4f4b-9600-7dc99f083f81.png)

**Comment by ririko5834** [comment]
after less than 10 minutes form starting download it failed.

Idk why is there not way to auto restart download when it fails instead putting it to queue with that error message and not  trying again and again to download it

**Comment by ririko5834** [comment]
Now only 2 are downloading 
![image](https://user-images.githubusercontent.com/64729293/213744214-3519d6a8-994a-4b78-86ec-4556b356be23.png)

It end up like this

![image](https://user-images.githubusercontent.com/64729293/213745796-40a1e60c-b025-4396-809e-2652b5b7246a.png)
Full logs: https://haste.cluster.ws/acojenapomaditaloqukaqefa.apache

**Comment by GammaC0de** [comment]
Worked without an issue for me.

**Comment by ririko5834** [comment]
After a few retries it fails, ratelimited by uloz to probably when trying more times
![image](https://user-images.githubusercontent.com/64729293/215132130-ceedf562-ba98-4dc2-93a9-ca07e8bb380f.png)

**Comment by ririko5834** [comment]
maybe its because of that dialog 
![image](https://user-images.githubusercontent.com/64729293/215133307-b75f22a0-e0a1-4d4c-b204-3bd9eace4714.png)

**Comment by ririko5834** [comment]
when i open it, it shows this 
![image](https://user-images.githubusercontent.com/64729293/215133486-31dc4048-f574-49a3-9ae7-1daa117e60d3.png)

but pyload doesn't show mw prompt to enter that captcha
