### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'DlProtectNet'

### ISSUE THREAD

**Issue by Cobraeti** [pyload/pyload#4248]
Hello, I'm facing the same error as referenced in [this comment](https://github.com/pyload/pyload/issues/1926#issuecomment-145086622) when trying to use a plugin located in the `USERDIR` folder tree.
I would like to share an updated version of DlProtectCom decrypter as the domain is now dl-protect.net, so I copied `DlProtectCom.py` as `DlProtectNet.py` and started tweaking it for the new domain but I get a similar stack as @kb0n when a link is assigned to it... :cry:
I'm using the following Docker image: `linuxserver/pyload-ng:0.5.0`
And I'm putting the following content in `/config/plugins/decrypters/DlProtectNet.py` (`USERDIR` being `/config`):
```
# -*- coding: utf-8 -*-

import re
import urllib.parse

from ..base.simple_decrypter import SimpleDecrypter


class DlProtectNet(SimpleDecrypter):
    __name__ = "DlProtectNet"
    __type__ = "decrypter"
    __version__ = "0.14"
    __status__ = "testing"

    __pattern__ = r"https?://(?:www\.)?dl-protect\.net/(?P<id>\d+)\?fn=(?P<nameBase64>[a-zA-Z0-9+/]+(?:=|\%3D){,2})\&.*"
    __config__ = [
        ("enabled", "bool", "Activated", True),
        ("use_premium", "bool", "Use premium account if available", True),
        (
            "folder_per_package",
            "Default;Yes;No",
            "Create folder for each package",
            "Default",
        ),
        ("max_wait", "int", "Reconnect if waiting time is greater than minutes", 30),
    ]

    __description__ = """Dl-protect.net decrypter plugin"""
    __license__ = "GPLv3"
    __authors__ = [
        ("Walter Purcaro", "vuolter@gmail.com"),
        ("GammaC0de", "nitzo2001[AT]yahoo[DOT]com")
    ]

    def get_links(self):
        if "Cliquez sur continuer pour voir le(s) lien" in self.data:
            self.data = self.load(self.pyfile.url, post={"submit": "Continuer"})

        if 'img src="captcha.php' in self.data:
            captcha_code = self.captcha.decrypt(
                urllib.parse.urljoin(self.pyfile.url, "/captcha.php"), input_type="jpeg"
            )
            self.data = self.load(
                self.pyfile.url, post={"captchaCode": captcha_code, "submit": ""}
            )

            if "Le code de sécurité est incorrect" in self.data:
                self.retry_captcha()

        return re.findall(r'<a href="(?P<id>[^/].+?)">(?P=id)</a>', self.data)
```
When a link gets matched I see the following logs:
```
[2023-01-27 07:39:24]  INFO                pyload  Added package Test DlProtectNet containing 1 links
[2023-01-27 07:39:24]  ERROR               pyload  Error importing DlProtectNet: No module named 'pyload.plugins.decrypters.DlProtectNet'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyload/core/managers/plugin_manager.py", line 354, in load_module
    module = __import__(
ModuleNotFoundError: No module named 'pyload.plugins.decrypters.DlProtectNet'
[2023-01-27 07:39:24]  ERROR               pyload  Error importing DlProtectNet: No module named 'pyload.plugins.decrypters.DlProtectNet'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyload/core/managers/plugin_manager.py", line 354, in load_module
    module = __import__(
ModuleNotFoundError: No module named 'pyload.plugins.decrypters.DlProtectNet'
[2023-01-27 07:39:24]  CRITICAL            pyload  'NoneType' object has no attribute 'DlProtectNet'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyload/core/managers/thread_manager.py", line 317, in assign_job
    job.init_plugin()
  File "/usr/lib/python3.10/site-packages/pyload/core/utils/struct/lock.py", line 22, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pyload/core/datatypes/pyfile.py", line 96, in init_plugin
    self.pluginclass = getattr(
AttributeError: 'NoneType' object has no attribute 'DlProtectNet'
```
Any idea how I could get it to work so I can test the effectiveness of my changes ?
Thanks in advance

**Comment by Cobraeti** [comment]
Hello @GammaC0de, thanks a lot for the quick fix, the plugins are now loaded correctly from the `USERDIR` folders tree, so I'm good to start fixing this decrypter :wink:

For information, now I see a `plugins.` folder created with a copy of the content from the `plugins` folder.
Replacing `self.USERROOT` by `"plugins"` at least in [this line](https://github.com/pyload/pyload/commit/0e53f8688c491500431e15d610fa3fca49433477#diff-3d7062d88993b47e9ef7daf4a72fe67148382c68091bcb656aa168a8ac12713dR24) would restore the previous behavior with only a `plugins` folder.
Should I make a Pull Request for this little fix or you prefer to fixup your commit directly ?

**Comment by GammaC0de** [comment]
I will fix this in the evening
