### ISSUE TITLE
Docker build failing with AttributeError: module 'jinja2.ext' has no attribute 'autoescape'

### ISSUE THREAD

**Issue by anarion80** [pyload/pyload#4287]
### Description

When trying to build docker image, extract_images is failing with 
`AttributeError: module 'jinja2.ext' has no attribute 'autoescape'`

### Debug log

```
#0 1.044 **** build pyLoad locales ****                                                                                                                      
#0 1.954 Collecting Babel                                                                                                                                    
#0 2.146   Downloading Babel-2.12.1-py3-none-any.whl (10.1 MB)                                                                                               
#0 2.817      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 15.2 MB/s eta 0:00:00
#0 3.019 Collecting Jinja2
#0 3.056   Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
#0 3.141      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 1.5 MB/s eta 0:00:00
#0 3.336 Collecting MarkupSafe>=2.0
#0 3.374   Downloading MarkupSafe-2.1.2-cp310-cp310-musllinux_1_1_x86_64.whl (29 kB)
#0 3.567 Installing collected packages: MarkupSafe, Babel, Jinja2
#0 5.223 Successfully installed Babel-2.12.1 Jinja2-3.1.2 MarkupSafe-2.1.2
#0 5.224 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#0 5.230 
#0 5.230 [notice] A new release of pip is available: 23.0.1 -> 23.1.2
#0 5.230 [notice] To update, run: pip3 install --upgrade pip
#0 5.679 /usr/lib/python3.10/site-packages/setuptools/dist.py:530: UserWarning: Normalizing '0.5.0-beta.3' to '0.5.0b3'
#0 5.679   warnings.warn(tmpl.format(**locals()))
#0 5.742 running build_locale
#0 5.744 creating /source/src/pyload/locale
#0 5.745 running extract_messages
#0 5.775 extracting messages from src/pyload/__init__.py (encoding="utf-8")
[cut]
#0 8.631 extracting messages from src/pyload/webui/app/static/js/captcha-interactive.user.js (encoding="utf-8", extract_messages="_, $._, jQuery._")
#0 8.643 extracting messages from src/pyload/webui/app/templates/base.html (encoding="utf-8", extensions="jinja2.ext.autoescape,jinja2.ext.with_")
#0 8.698 Traceback (most recent call last):
#0 8.699   File "/source/setup.py", line 74, in <module>
#0 8.700     setup(version=retrieve_version(), cmdclass={"build_locale": BuildLocale})
#0 8.700   File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
#0 8.701     return distutils.core.setup(**attrs)
#0 8.701   File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
#0 8.702     return run_commands(dist)
#0 8.702   File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#0 8.703     dist.run_commands()
#0 8.703   File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
#0 8.704     self.run_command(cmd)
#0 8.705   File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
#0 8.706     super().run_command(command)
#0 8.706   File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
#0 8.707     cmd_obj.run()
#0 8.708   File "/source/setup.py", line 56, in run
#0 8.708     self._execute("run_command", commands)
#0 8.709   File "/source/setup.py", line 43, in _execute
#0 8.710     execute(cmd_name)
#0 8.710   File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
#0 8.710     self.distribution.run_command(command)
#0 8.710   File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
#0 8.711     super().run_command(command)
#0 8.711   File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
#0 8.712     cmd_obj.run()
#0 8.713   File "/usr/lib/python3.10/site-packages/babel/messages/frontend.py", line 528, in run
#0 8.714     for filename, lineno, message, comments, context in extracted:
#0 8.714   File "/usr/lib/python3.10/site-packages/babel/messages/extract.py", line 208, in extract_from_dir
#0 8.714     yield from check_and_call_extract_file(
#0 8.718   File "/usr/lib/python3.10/site-packages/babel/messages/extract.py", line 272, in check_and_call_extract_file
#0 8.718     for message_tuple in extract_from_file(
#0 8.718   File "/usr/lib/python3.10/site-packages/babel/messages/extract.py", line 314, in extract_from_file
#0 8.718     return list(extract(method, fileobj, keywords, comment_tags,
#0 8.718   File "/usr/lib/python3.10/site-packages/babel/messages/extract.py", line 402, in extract
#0 8.718     for lineno, funcname, messages, comments in results:
#0 8.718   File "/usr/lib/python3.10/site-packages/jinja2/ext.py", line 808, in babel_extract
#0 8.718     extensions[import_string(extension_name)] = None
#0 8.718   File "/usr/lib/python3.10/site-packages/jinja2/utils.py", line 149, in import_string
#0 8.718     return getattr(__import__(module, None, None, [obj]), obj)
#0 8.718 AttributeError: module 'jinja2.ext' has no attribute 'autoescape'
```

### Additional references

Apparently with Jinja3, `with` and `autoescape` are deprecated:
https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-0-0

Should they be perhaps removed from babel.cfg?

**Comment by GammaC0de** [comment]
The problem is that in order to support python versions lower than 3.7, jinja2 v2.x should be used, and the `with` and `autoescape` extensions has to be specified then.
So how this can be done conditionally based on the jinja2 version?

**Comment by anarion80** [comment]
I have no idea unfortunately, but ChatGPT seems to be suggesting a condition in Python code directly 😄 :

To conditionally use the with and autoescape extensions in Jinja2, you can check the version number of Jinja2 and then load the extensions if the version is older than 3.0. You can use the pkg_resources module to get the version number of the installed Jinja2 package. Here is an example of how you could modify your code to conditionally load the extensions:

```
from jinja2 import Environment, FileSystemLoader
import pkg_resources

# Get the version number of Jinja2
jinja2_version = pkg_resources.get_distribution('jinja2').version

# Conditionally load the extensions based on the version number
if jinja2_version >= '3.0':
    jinja_env = Environment(loader=FileSystemLoader('./'), autoescape=True)
else:
    from jinja2.ext import autoescape, with_
    jinja_env = Environment(loader=FileSystemLoader('./'), extensions=[with_, autoescape])

# Use the jinja_env object to render your templates
```

This code first imports the Environment class and FileSystemLoader class from Jinja2. It then uses pkg_resources.get_distribution to get the version number of the installed Jinja2 package. Based on the version number, it either loads the autoescape and with_ extensions or sets autoescape=True. Finally, you can use the jinja_env object to render your templates as desired.

I hope this helps! Let me know if you have any further questions.

**Comment by GammaC0de** [comment]
Thanks for the hint for the version check.
After a lot of debugging, this is I came with: https://github.com/pyload/pyload/commit/f70049128e94b0c5a22ba473b8424c80791abd3e
