### ISSUE TITLE
Fshare host cant download

### ISSUE THREAD

**Issue by mtungtn** [pyload/pyload#4306]
Fshare host cant download
### Description

This error appeared in the last few weeks. Fshare vip account is still valid and shown in pyload. tried a clean install of pyload a few times
Test link: https://www.fshare.vn/file/5D3ZKJPMROTVKZ1

### Debug log

<html>
<body>
</body>
</html>

```
1	2023-06-03 10:06:33	INFO	pyload	*** Welcome to pyLoad 0.5.0 ***
2	2023-06-03 10:06:36	DEBUG	pyload	Indexing plugins...
3	2023-06-03 10:06:36	INFO	pyload	Activated addons: ClickNLoad, ExternalScripts, TORRENT, UnSkipOnFail, UserAgentSwitcher
4	2023-06-03 10:06:36	INFO	pyload	Deactivate addons: AndroidPhoneNotify, AntiCaptcha, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, UpdateManager, WindowsPhoneNotify, XFileSharing, XMPP
5	2023-06-03 10:06:37	DEBUG	pyload	Starting core...
6	2023-06-03 10:06:37	DEBUG	pyload	Debug level: TRACE
7	2023-06-03 10:06:37	DEBUG	pyload	Setup language...
8	2023-06-03 10:06:37	DEBUG	pyload	Setup permissions...
9	2023-06-03 10:06:37	INFO	pyload	User directory: /config
10	2023-06-03 10:06:37	INFO	pyload	Cache directory: /tmp/pyLoad
11	2023-06-03 10:06:37	INFO	pyload	Storage directory: /downloads
12	2023-06-03 10:06:37	INFO	pyload	Storage free space: 772.95 GiB
13	2023-06-03 10:06:37	DEBUG	pyload	Setup network...
14	2023-06-03 10:06:37	INFO	pyload	Activating accounts...
15	2023-06-03 10:06:37	INFO	pyload	Activating plugins...
16	2023-06-03 10:06:37	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `pyload_start`
17	2023-06-03 10:06:37	WARNING	pyload	ADDON TORRENT: torrents / magnets are not associated with any plugin
18	2023-06-03 10:06:37	INFO	pyload.webui	Starting webserver: http://0.0.0.0:8000
19	2023-06-03 10:06:37	DEBUG	pyload	*** pyLoad is up and running ***
20	2023-06-03 10:06:42	DEBUG	pyload	ADDON ClickNLoad: Backend found on http://127.0.0.1:8000
21	2023-06-03 10:06:42	INFO	pyload	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
22	2023-06-03 10:06:59	ERROR	pyload	Login failed for user 'pyload'
23	2023-06-03 10:07:05	INFO	pyload	User 'pyload' successfully logged in
24	2023-06-03 10:07:08	DEBUG	pyload.webui	[Errno 13] Permission denied: '/downloads/#recycle'
25	?	?	?	Traceback (most recent call last):
26	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
27	?	?	?	    rv = self.dispatch_request()
28	?	?	?	         ^^^^^^^^^^^^^^^^^^^^^^^
29	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
30	?	?	?	    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
31	?	?	?	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
32	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/webui/app/helpers.py", line 199, in wrapper
33	?	?	?	    response = func(*args, **kwargs)
34	?	?	?	               ^^^^^^^^^^^^^^^^^^^^^
35	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/webui/app/blueprints/app_blueprint.py", line 143, in files
36	?	?	?	    files = os.listdir(os.path.join(root, entry))
37	?	?	?	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
38	?	?	?	PermissionError: [Errno 13] Permission denied: '/downloads/#recycle'
39	2023-06-03 10:08:24	INFO	pyload	Added package phim containing 1 links
40	2023-06-03 10:08:24	INFO	pyload	Download starts: 5D3ZKJPMROTVKZ1
41	2023-06-03 10:08:24	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_preparing`
42	2023-06-03 10:08:24	DEBUG	pyload	ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
43	2023-06-03 10:08:24	DEBUG	pyload	ADDON UserAgentSwitcher: Setting maximum redirections to 10
44	2023-06-03 10:08:24	DEBUG	pyload	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0`
45	2023-06-03 10:08:24	DEBUG	pyload	DOWNLOADER FshareVn[1]: Plugin version: 0.37
46	2023-06-03 10:08:24	DEBUG	pyload	DOWNLOADER FshareVn[1]: Plugin status: testing
47	2023-06-03 10:08:24	WARNING	pyload	DOWNLOADER FshareVn[1]: Plugin may be unstable
48	2023-06-03 10:08:24	INFO	pyload	DOWNLOADER FshareVn[1]: Processing url: https://www.fshare.vn/file/5D3ZKJPMROTVKZ1
49	2023-06-03 10:08:24	INFO	pyload	DOWNLOADER FshareVn[1]: Looking for direct download link...
50	2023-06-03 10:08:24	DEBUG	pyload	DOWNLOADER FshareVn[1]: LOAD URL https://www.fshare.vn/file/5D3ZKJPMROTVKZ1 | get={} | post={} | ref=True | cookies=True | just_header=True | decode=True | multipart=False | redirect=True | req=None
51	2023-06-03 10:08:27	INFO	pyload	DOWNLOADER FshareVn[1]: Direct download link not found
52	2023-06-03 10:08:27	DEBUG	pyload	DOWNLOADER FshareVn[1]: LOAD URL https://www.fshare.vn/file/5D3ZKJPMROTVKZ1 | get={} | post={} | ref=False | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
53	2023-06-03 10:08:31	INFO	pyload	DOWNLOADER FshareVn[1]: Checking for link errors...
54	2023-06-03 10:08:31	INFO	pyload	DOWNLOADER FshareVn[1]: No errors found
55	2023-06-03 10:08:31	INFO	pyload	DOWNLOADER FshareVn[1]: Grabbing link info...
56	2023-06-03 10:08:31	DEBUG	pyload	DOWNLOADER FshareVn[1]: LOAD URL https://www.fshare.vn/api/v3/files/folder | get={'linkcode': '5D3ZKJPMROTVKZ1'} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
57	2023-06-03 10:08:32	DEBUG	pyload	DOWNLOADER FshareVn[1]: Link info: {'name': 'A.Nightmare.on.Elm.Street.5.The.Dream.Child.1989.HDrip.720p.Vietsub.mp4', 'hash': {}, 'pattern': {'ID': '5D3ZKJPMROTVKZ1'}, 'size': 718259792, 'status': 6, 'url': 'https://www.fshare.vn/file/5D3ZKJPMROTVKZ1'}
58	2023-06-03 10:08:32	DEBUG	pyload	DOWNLOADER FshareVn[1]: Previous link info: {}
59	2023-06-03 10:08:32	INFO	pyload	DOWNLOADER FshareVn[1]: Link name: A.Nightmare.on.Elm.Street.5.The.Dream.Child.1989.HDrip.720p.Vietsub.mp4
60	2023-06-03 10:08:32	INFO	pyload	DOWNLOADER FshareVn[1]: Link size: 684.99 MiB (718259792 bytes)
61	2023-06-03 10:08:32	INFO	pyload	DOWNLOADER FshareVn[1]: Link status: temp. offline
62	2023-06-03 10:08:32	WARNING	pyload	DOWNLOADER FshareVn[1]: Free download failed | temp. offline
63	2023-06-03 10:08:32	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_processed`
64	2023-06-03 10:08:32	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `package_processed`
65	2023-06-03 10:08:32	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `package_failed`
66	2023-06-03 10:08:32	WARNING	pyload	Download is temporary offline: A.Nightmare.on.Elm.Street.5.The.Dream.Child.1989.HDrip.720p.Vietsub.mp4
67	2023-06-03 10:08:32	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_failed`
68	2023-06-03 10:08:32	INFO	pyload	ADDON UnSkipOnFail: Looking for skipped duplicates of: A.Nightmare.on.Elm.Street.5.The.Dream.Child.1989.HDrip.720p.Vietsub.mp4 (pid:1)
69	2023-06-03 10:08:32	INFO	pyload	ADDON UnSkipOnFail: No duplicates found
70	2023-06-03 10:08:33	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
71	2023-06-03 10:08:33	DEBUG	pyload	All downloads processed
72	2023-06-03 10:13:08	INFO	pyload	ACCOUNT FshareVn: Adding user `mtu*******`...
73	2023-06-03 10:13:08	DEBUG	pyload	ACCOUNT FshareVn: Reached login timeout for user `mtu****`
74	2023-06-03 10:13:08	INFO	pyload	ACCOUNT FshareVn: Login user `mtu****`...
75	2023-06-03 10:13:08	DEBUG	pyload	ACCOUNT FshareVn: LOAD URL https://api.fshare.vn/api/user/login | get={} | post={"app_key": "dMnqMMZMUnN5YpvKENaEhdQQ5jxDqddt", "user_email": "mtu****", "password": "**********"} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
76	2023-06-03 10:13:09	INFO	pyload	ACCOUNT FshareVn: Grabbing account info for user `mtu****`...
77	2023-06-03 10:13:09	DEBUG	pyload	ACCOUNT FshareVn: LOAD URL https://api.fshare.vn/api/user/get | get={} | post={} | ref=True | cookies=[('fshare.vn', 'session_id', 'bceosguphptnt7sibtt6i7h424')] | just_header=False | decode=True | multipart=False | redirect=True | req=None
78	2023-06-03 10:13:10	DEBUG	pyload	ACCOUNT FshareVn: Account info for user `mtu****`: {'login': {'password': '**********', 'stats': [1, 0], 'timestamp': 1685761988.4501066, 'valid': True}, 'data': {'login': 'mtu****', 'options': {'limit_dl': ['0']}, 'plugin': <Account FshareVn>, 'premium': True, 'trafficleft': None, 'type': 'FshareVn', 'validuntil': 1789696790.0, 'token': 'd57463a9d9461fe6b4094be6b0d7f55fb974b0b1', 'session_id': 'bceosguphptnt7sibtt6i7h424'}}
79	2023-06-03 10:13:15	INFO	pyload	Download starts: A.Nightmare.on.Elm.Street.5.The.Dream.Child.1989.HDrip.720p.Vietsub.mp4
80	2023-06-03 10:13:15	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_preparing`
81	2023-06-03 10:13:15	DEBUG	pyload	ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
82	2023-06-03 10:13:15	DEBUG	pyload	ADDON UserAgentSwitcher: Setting maximum redirections to 10
83	2023-06-03 10:13:15	DEBUG	pyload	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0`
84	2023-06-03 10:13:15	DEBUG	pyload	DOWNLOADER FshareVn[1]: Plugin version: 0.37
85	2023-06-03 10:13:15	DEBUG	pyload	DOWNLOADER FshareVn[1]: Plugin status: testing
86	2023-06-03 10:13:15	WARNING	pyload	DOWNLOADER FshareVn[1]: Plugin may be unstable
87	2023-06-03 10:13:15	INFO	pyload	ACCOUNT FshareVn: Grabbing account info for user `mtu****`...
88	2023-06-03 10:13:15	DEBUG	pyload	ACCOUNT FshareVn: LOAD URL https://api.fshare.vn/api/user/get | get={} | post={} | ref=True | cookies=[('fshare.vn', 'session_id', 'bceosguphptnt7sibtt6i7h424')] | just_header=False | decode=True | multipart=False | redirect=True | req=None
89	2023-06-03 10:13:16	DEBUG	pyload	ACCOUNT FshareVn: Account info for user `mtu****`: {'login': {'password': '**********', 'stats': [1, 0], 'timestamp': 1685761988.4501066, 'valid': True}, 'data': {'login': 'mtu****', 'options': {'limit_dl': ['0']}, 'plugin': <Account FshareVn>, 'premium': True, 'trafficleft': None, 'type': 'FshareVn', 'validuntil': 1789696790.0, 'token': 'd57463a9d9461fe6b4094be6b0d7f55fb974b0b1', 'session_id': 'bceosguphptnt7sibtt6i7h424'}}
90	2023-06-03 10:13:16	DEBUG	pyload	ACCOUNT FshareVn: Using account mtu*******
91	2023-06-03 10:13:16	INFO	pyload	DOWNLOADER FshareVn[1]: Processing url: https://www.fshare.vn/file/5D3ZKJPMROTVKZ1
92	2023-06-03 10:13:16	INFO	pyload	DOWNLOADER FshareVn[1]: Looking for direct download link...
93	2023-06-03 10:13:16	DEBUG	pyload	DOWNLOADER FshareVn[1]: LOAD URL https://www.fshare.vn/file/5D3ZKJPMROTVKZ1 | get={} | post={} | ref=True | cookies=True | just_header=True | decode=True | multipart=False | redirect=True | req=None
94	2023-06-03 10:13:20	DEBUG	pyload	DOWNLOADER FshareVn[1]: Redirect #1 to: https://www.fshare.vn/file/5D3ZKJPMROTVKZ1?token=1685761997
95	2023-06-03 10:13:20	DEBUG	pyload	DOWNLOADER FshareVn[1]: LOAD URL https://www.fshare.vn/file/5D3ZKJPMROTVKZ1?token=1685761997 | get={} | post={} | ref=True | cookies=True | just_header=True | decode=True | multipart=False | redirect=True | req=None
96	2023-06-03 10:13:23	INFO	pyload	DOWNLOADER FshareVn[1]: Direct download link not found
97	2023-06-03 10:13:23	DEBUG	pyload	DOWNLOADER FshareVn[1]: LOAD URL https://www.fshare.vn/file/5D3ZKJPMROTVKZ1 | get={} | post={} | ref=False | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
98	2023-06-03 10:13:26	INFO	pyload	DOWNLOADER FshareVn[1]: Checking for link errors...
99	2023-06-03 10:13:26	INFO	pyload	DOWNLOADER FshareVn[1]: No errors found
100	2023-06-03 10:13:26	INFO	pyload	DOWNLOADER FshareVn[1]: Grabbing link info...
101	2023-06-03 10:13:26	DEBUG	pyload	DOWNLOADER FshareVn[1]: LOAD URL https://www.fshare.vn/api/v3/files/folder | get={'linkcode': '5D3ZKJPMROTVKZ1'} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
102	2023-06-03 10:13:27	DEBUG	pyload	DOWNLOADER FshareVn[1]: Link info: {'name': 'A.Nightmare.on.Elm.Street.5.The.Dream.Child.1989.HDrip.720p.Vietsub.mp4', 'hash': {}, 'pattern': {'ID': '5D3ZKJPMROTVKZ1'}, 'size': 718259792, 'status': 6, 'url': 'https://www.fshare.vn/file/5D3ZKJPMROTVKZ1'}
103	2023-06-03 10:13:27	DEBUG	pyload	DOWNLOADER FshareVn[1]: Previous link info: {}
104	2023-06-03 10:13:27	INFO	pyload	DOWNLOADER FshareVn[1]: Link name: A.Nightmare.on.Elm.Street.5.The.Dream.Child.1989.HDrip.720p.Vietsub.mp4
105	2023-06-03 10:13:27	INFO	pyload	DOWNLOADER FshareVn[1]: Link size: 684.99 MiB (718259792 bytes)
106	2023-06-03 10:13:27	INFO	pyload	DOWNLOADER FshareVn[1]: Link status: temp. offline
107	2023-06-03 10:13:27	WARNING	pyload	DOWNLOADER FshareVn[1]: Premium download failed | temp. offline
108	2023-06-03 10:13:27	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_processed`
109	2023-06-03 10:13:27	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `package_processed`
110	2023-06-03 10:13:27	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `package_failed`
111	2023-06-03 10:13:27	WARNING	pyload	Download is temporary offline: A.Nightmare.on.Elm.Street.5.The.Dream.Child.1989.HDrip.720p.Vietsub.mp4
112	2023-06-03 10:13:27	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_failed`
113	2023-06-03 10:13:27	INFO	pyload	ADDON UnSkipOnFail: Looking for skipped duplicates of: A.Nightmare.on.Elm.Street.5.The.Dream.Child.1989.HDrip.720p.Vietsub.mp4 (pid:1)
114	2023-06-03 10:13:27	INFO	pyload	ADDON UnSkipOnFail: No duplicates found
115	2023-06-03 10:13:27	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
116	2023-06-03 10:13:27	DEBUG	pyload	All downloads processed
117	2023-06-03 10:18:21	INFO	pyload	Received Terminate signal
118	2023-06-03 10:18:21	DEBUG	pyload	Stopping core...
119	2023-06-03 10:18:21	INFO	pyload	ADDON ClickNLoad: Shutting down proxy...
120	2023-06-03 10:18:21	DEBUG	pyload	ADDON ClickNLoad: Server exited successfully
121	2023-06-03 10:18:21	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `pyload_stop`
122	2023-06-03 10:18:22	INFO	pyload	Exiting core...
123	2023-06-03 10:18:31	INFO	pyload	*** Welcome to pyLoad 0.5.0 ***
124	2023-06-03 10:18:32	DEBUG	pyload	Indexing plugins...
125	2023-06-03 10:18:32	INFO	pyload	Activated addons: ClickNLoad, ExternalScripts, TORRENT, UnSkipOnFail, UserAgentSwitcher
126	2023-06-03 10:18:32	INFO	pyload	Deactivate addons: AndroidPhoneNotify, AntiCaptcha, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, UpdateManager, WindowsPhoneNotify, XFileSharing, XMPP
127	2023-06-03 10:18:32	DEBUG	pyload	Starting core...
128	2023-06-03 10:18:32	DEBUG	pyload	Debug level: DEBUG
129	2023-06-03 10:18:32	DEBUG	pyload	Setup language...
130	2023-06-03 10:18:32	DEBUG	pyload	Setup permissions...
131	2023-06-03 10:18:32	INFO	pyload	User directory: /config
132	2023-06-03 10:18:32	INFO	pyload	Cache directory: /tmp/pyLoad
133	2023-06-03 10:18:32	INFO	pyload	Storage directory: /downloads
134	2023-06-03 10:18:32	INFO	pyload	Storage free space: 772.95 GiB
135	2023-06-03 10:18:32	DEBUG	pyload	Setup network...
136	2023-06-03 10:18:32	INFO	pyload	Activating accounts...
137	2023-06-03 10:18:32	INFO	pyload	ACCOUNT FshareVn: Adding user `mtu*******`...
138	2023-06-03 10:18:32	DEBUG	pyload	ACCOUNT FshareVn: Reached login timeout for user `mtu****`
139	2023-06-03 10:18:32	INFO	pyload	ACCOUNT FshareVn: Login user `mtu****`...
140	2023-06-03 10:18:32	DEBUG	pyload	ACCOUNT FshareVn: LOAD URL https://api.fshare.vn/api/user/get | get={} | post={} | ref=True | cookies=[('fshare.vn', 'session_id', 'bceosguphptnt7sibtt6i7h424')] | just_header=False | decode=True | multipart=False | redirect=True | req=None
141	2023-06-03 10:18:33	WARNING	pyload	ACCOUNT FshareVn: Skipped login user `mtu****` | Already signed in
142	2023-06-03 10:18:33	INFO	pyload	ACCOUNT FshareVn: Grabbing account info for user `mtu****`...
143	2023-06-03 10:18:33	DEBUG	pyload	ACCOUNT FshareVn: LOAD URL https://api.fshare.vn/api/user/get | get={} | post={} | ref=True | cookies=[('fshare.vn', 'session_id', 'bceosguphptnt7sibtt6i7h424')] | just_header=False | decode=True | multipart=False | redirect=True | req=None
144	2023-06-03 10:18:33	DEBUG	pyload	ACCOUNT FshareVn: Account info for user `mtu****`: {'login': {'password': '**********', 'stats': [1, 0], 'timestamp': 1685762312.6975043, 'valid': True}, 'data': {'login': 'mtu****', 'options': {'limit_dl': ['0']}, 'plugin': <Account FshareVn>, 'premium': True, 'trafficleft': None, 'type': 'FshareVn', 'validuntil': 1789696790.0, 'token': 'd57463a9d9461fe6b4094be6b0d7f55fb974b0b1', 'session_id': 'bceosguphptnt7sibtt6i7h424'}}
145	2023-06-03 10:18:33	INFO	pyload	Activating plugins...
146	2023-06-03 10:18:33	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `pyload_start`
147	2023-06-03 10:18:33	WARNING	pyload	ADDON TORRENT: torrents / magnets are not associated with any plugin
148	2023-06-03 10:18:33	INFO	pyload.webui	Starting webserver: http://0.0.0.0:8000
149	2023-06-03 10:18:33	DEBUG	pyload	*** pyLoad is up and running ***
150	2023-06-03 10:18:38	DEBUG	pyload	ADDON ClickNLoad: Backend found on http://127.0.0.1:8000
151	2023-06-03 10:18:38	INFO	pyload	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
152	2023-06-03 10:19:41	INFO	pyload	Download starts: A.Nightmare.on.Elm.Street.5.The.Dream.Child.1989.HDrip.720p.Vietsub.mp4
153	2023-06-03 10:19:41	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_preparing`
154	2023-06-03 10:19:41	DEBUG	pyload	ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
155	2023-06-03 10:19:41	DEBUG	pyload	ADDON UserAgentSwitcher: Setting maximum redirections to 10
156	2023-06-03 10:19:41	DEBUG	pyload	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0`
157	2023-06-03 10:19:41	DEBUG	pyload	DOWNLOADER FshareVn[1]: Plugin version: 0.37
158	2023-06-03 10:19:41	DEBUG	pyload	DOWNLOADER FshareVn[1]: Plugin status: testing
159	2023-06-03 10:19:41	WARNING	pyload	DOWNLOADER FshareVn[1]: Plugin may be unstable
160	2023-06-03 10:19:41	INFO	pyload	ACCOUNT FshareVn: Grabbing account info for user `mtu****`...
161	2023-06-03 10:19:41	DEBUG	pyload	ACCOUNT FshareVn: LOAD URL https://api.fshare.vn/api/user/get | get={} | post={} | ref=True | cookies=[('fshare.vn', 'session_id', 'bceosguphptnt7sibtt6i7h424')] | just_header=False | decode=True | multipart=False | redirect=True | req=None
162	2023-06-03 10:19:41	DEBUG	pyload	ACCOUNT FshareVn: Account info for user `mtu****`: {'login': {'password': '**********', 'stats': [1, 0], 'timestamp': 1685762312.6975043, 'valid': True}, 'data': {'login': 'mtu****', 'options': {'limit_dl': ['0']}, 'plugin': <Account FshareVn>, 'premium': True, 'trafficleft': None, 'type': 'FshareVn', 'validuntil': 1789696790.0, 'token': 'd57463a9d9461fe6b4094be6b0d7f55fb974b0b1', 'session_id': 'bceosguphptnt7sibtt6i7h424'}}
163	2023-06-03 10:19:41	DEBUG	pyload	ACCOUNT FshareVn: Using account mtu*******
164	2023-06-03 10:19:41	INFO	pyload	DOWNLOADER FshareVn[1]: Processing url: https://www.fshare.vn/file/5D3ZKJPMROTVKZ1
165	2023-06-03 10:19:41	INFO	pyload	DOWNLOADER FshareVn[1]: Looking for direct download link...
166	2023-06-03 10:19:41	DEBUG	pyload	DOWNLOADER FshareVn[1]: LOAD URL https://www.fshare.vn/file/5D3ZKJPMROTVKZ1 | get={} | post={} | ref=True | cookies=True | just_header=True | decode=True | multipart=False | redirect=True | req=None
167	2023-06-03 10:19:45	DEBUG	pyload	DOWNLOADER FshareVn[1]: Redirect #1 to: https://www.fshare.vn/file/5D3ZKJPMROTVKZ1?token=1685762382
168	2023-06-03 10:19:45	DEBUG	pyload	DOWNLOADER FshareVn[1]: LOAD URL https://www.fshare.vn/file/5D3ZKJPMROTVKZ1?token=1685762382 | get={} | post={} | ref=True | cookies=True | just_header=True | decode=True | multipart=False | redirect=True | req=None
169	2023-06-03 10:19:48	INFO	pyload	DOWNLOADER FshareVn[1]: Direct download link not found
170	2023-06-03 10:19:48	DEBUG	pyload	DOWNLOADER FshareVn[1]: LOAD URL https://www.fshare.vn/file/5D3ZKJPMROTVKZ1 | get={} | post={} | ref=False | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
171	2023-06-03 10:19:52	INFO	pyload	DOWNLOADER FshareVn[1]: Checking for link errors...
172	2023-06-03 10:19:52	INFO	pyload	DOWNLOADER FshareVn[1]: No errors found
173	2023-06-03 10:19:52	INFO	pyload	DOWNLOADER FshareVn[1]: Grabbing link info...
174	2023-06-03 10:19:52	DEBUG	pyload	DOWNLOADER FshareVn[1]: LOAD URL https://www.fshare.vn/api/v3/files/folder | get={'linkcode': '5D3ZKJPMROTVKZ1'} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
175	2023-06-03 10:19:52	DEBUG	pyload	DOWNLOADER FshareVn[1]: Link info: {'name': 'A.Nightmare.on.Elm.Street.5.The.Dream.Child.1989.HDrip.720p.Vietsub.mp4', 'hash': {}, 'pattern': {'ID': '5D3ZKJPMROTVKZ1'}, 'size': 718259792, 'status': 6, 'url': 'https://www.fshare.vn/file/5D3ZKJPMROTVKZ1'}
176	2023-06-03 10:19:52	DEBUG	pyload	DOWNLOADER FshareVn[1]: Previous link info: {}
177	2023-06-03 10:19:52	INFO	pyload	DOWNLOADER FshareVn[1]: Link name: A.Nightmare.on.Elm.Street.5.The.Dream.Child.1989.HDrip.720p.Vietsub.mp4
178	2023-06-03 10:19:52	INFO	pyload	DOWNLOADER FshareVn[1]: Link size: 684.99 MiB (718259792 bytes)
179	2023-06-03 10:19:52	INFO	pyload	DOWNLOADER FshareVn[1]: Link status: temp. offline
180	2023-06-03 10:19:52	WARNING	pyload	DOWNLOADER FshareVn[1]: Premium download failed | temp. offline
181	2023-06-03 10:19:52	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_processed`
182	2023-06-03 10:19:53	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `package_processed`
183	2023-06-03 10:19:53	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `package_failed`
184	2023-06-03 10:19:53	WARNING	pyload	Download is temporary offline: A.Nightmare.on.Elm.Street.5.The.Dream.Child.1989.HDrip.720p.Vietsub.mp4
185	2023-06-03 10:19:53	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_failed`
186	2023-06-03 10:19:53	INFO	pyload	ADDON UnSkipOnFail: Looking for skipped duplicates of: A.Nightmare.on.Elm.Street.5.The.Dream.Child.1989.HDrip.720p.Vietsub.mp4 (pid:1)
187	2023-06-03 10:19:53	INFO	pyload	ADDON UnSkipOnFail: No duplicates found
188	2023-06-03 10:19:53	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
189	2023-06-03 10:19:53	DEBUG	pyload	All downloads processed
Jump to time:
2023-06-03 10:06:33

```

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by mtungtn** [comment]
> Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

I sent to you
