### ISSUE TITLE
1fichier issue: download doesn't start

### ISSUE THREAD

**Issue by DrekoDev** [pyload/pyload#4314]
### Description

Hi, I use payload to download files from 1fichier.com (OneFichier.com on pyLoad). But every day, I need to reinstall pyLoad because the same issue occurs. When pyLoad is installed, I enter my email and my password for 1fichier.com and everything work well. But the next day, I got disconnected from 1fichier, and if I want to download some files, only the first file can be downloaded with the free version of 1fichier.

For the others files, the download simply doesn't start, even if I enter my password/username again, even if I click on the circle arrow to force the download: it doesn't start. So the only solution I found is to completely reinstall pyLoad

### Debug log

283 | 10.06.2023 22:33:59 | INFO | HOSTER OneFichierCom[11]: Downloading file...
-- | -- | -- | --
284 | 10.06.2023 22:36:40 | INFO | HOSTER OneFichierCom[9]: File saved
285 | 10.06.2023 22:36:40 | INFO | HOSTER OneFichierCom[9]: Checking download...
286 | 10.06.2023 22:36:40 | INFO | HOSTER OneFichierCom[9]: File is OK
287 | 10.06.2023 22:36:40 | INFO | HOSTER OneFichierCom[9]: Checking file (with built-in rules)...
288 | 10.06.2023 22:36:40 | INFO | HOSTER OneFichierCom[9]: Checking file (with custom rules)...
289 | 10.06.2023 22:36:40 | INFO | HOSTER OneFichierCom[9]: Checking for link errors...
290 | 10.06.2023 22:36:40 | INFO | HOSTER OneFichierCom[9]: No errors found
291 | 10.06.2023 22:36:40 | INFO | HOSTER OneFichierCom[9]: No errors found
292 | 10.06.2023 22:36:40 | INFO | Download finished: Severance.S01E06.VOSTFR.1080p.WEB.H264-Wawacity.blue.mkv
293 | 10.06.2023 22:36:42 | INFO | Download starts: https://1fichier.com/?jfnofl25jgnpec1ybgcx&af=3797078
294 | 10.06.2023 22:36:42 | WARNING | HOSTER OneFichierCom[12]: Plugin may be unstable
295 | 10.06.2023 22:36:42 | INFO | ACCOUNT OneFichierCom: Grabbing account info for user `dre*******`...
296 | 10.06.2023 22:36:42 | INFO | HOSTER OneFichierCom[12]: Processing url: https://1fichier.com/?jfnofl25jgnpec1ybgcx&af=3797078
297 | 10.06.2023 22:36:42 | INFO | HOSTER OneFichierCom[12]: Looking for direct download link...
298 | 10.06.2023 22:36:44 | INFO | HOSTER OneFichierCom[12]: Direct download link detected
299 | 10.06.2023 22:36:44 | INFO | HOSTER OneFichierCom[12]: Downloading file...
300 | 10.06.2023 22:36:51 | INFO | HOSTER OneFichierCom[11]: File saved
301 | 10.06.2023 22:36:51 | INFO | HOSTER OneFichierCom[11]: Checking download...
302 | 10.06.2023 22:36:51 | INFO | HOSTER OneFichierCom[11]: File is OK
303 | 10.06.2023 22:36:51 | INFO | HOSTER OneFichierCom[11]: Checking file (with built-in rules)...
304 | 10.06.2023 22:36:51 | INFO | HOSTER OneFichierCom[11]: Checking file (with custom rules)...
305 | 10.06.2023 22:36:51 | INFO | HOSTER OneFichierCom[11]: Checking for link errors...
306 | 10.06.2023 22:36:51 | INFO | HOSTER OneFichierCom[11]: No errors found
307 | 10.06.2023 22:36:51 | INFO | HOSTER OneFichierCom[11]: No errors found
308 | 10.06.2023 22:36:51 | INFO | Download finished: Severance.S01E08.VOSTFR.1080p.WEB.H264-Wawacity.blue.mkv
309 | 10.06.2023 22:36:55 | INFO | HOSTER OneFichierCom[10]: File saved
310 | 10.06.2023 22:36:55 | INFO | HOSTER OneFichierCom[10]: Checking download...
311 | 10.06.2023 22:36:55 | INFO | HOSTER OneFichierCom[10]: File is OK
312 | 10.06.2023 22:36:55 | INFO | HOSTER OneFichierCom[10]: Checking file (with built-in rules)...
313 | 10.06.2023 22:36:55 | INFO | HOSTER OneFichierCom[10]: Checking file (with custom rules)...
314 | 10.06.2023 22:36:55 | INFO | HOSTER OneFichierCom[10]: Checking for link errors...
315 | 10.06.2023 22:36:55 | INFO | HOSTER OneFichierCom[10]: No errors found
316 | 10.06.2023 22:36:55 | INFO | HOSTER OneFichierCom[10]: No errors found
317 | 10.06.2023 22:36:55 | INFO | Download finished: Severance.S01E07.VOSTFR.1080p.WEB.H264-Wawacity.blue.mkv
318 | 10.06.2023 22:37:50 | INFO | HOSTER OneFichierCom[12]: File saved
319 | 10.06.2023 22:37:50 | INFO | HOSTER OneFichierCom[12]: Checking download...
320 | 10.06.2023 22:37:50 | INFO | HOSTER OneFichierCom[12]: File is OK
321 | 10.06.2023 22:37:50 | INFO | HOSTER OneFichierCom[12]: Checking file (with built-in rules)...
322 | 10.06.2023 22:37:50 | INFO | HOSTER OneFichierCom[12]: Checking file (with custom rules)...
323 | 10.06.2023 22:37:50 | INFO | HOSTER OneFichierCom[12]: Checking for link errors...
324 | 10.06.2023 22:37:50 | INFO | HOSTER OneFichierCom[12]: No errors found
325 | 10.06.2023 22:37:50 | INFO | HOSTER OneFichierCom[12]: No errors found
326 | 10.06.2023 22:37:50 | INFO | Download finished: Severance.S01E09.FiNAL.VOSTFR.1080p.WEB.H264-Wawacity.blue.mkv
327 | 11.06.2023 03:35:39 | INFO | ADDON UpdateManager: pyLoad is up to date!
328 | 11.06.2023 03:35:39 | INFO | ADDON UpdateManager: All plugins are up to date!
329 | 11.06.2023 09:35:40 | INFO | ADDON UpdateManager: pyLoad is up to date!
330 | 11.06.2023 09:35:40 | INFO | ADDON UpdateManager: All plugins are up to date!
331 | 11.06.2023 13:36:23 | INFO | Added package Andor Star Wars containing 12 links
332 | 11.06.2023 13:36:24 | INFO | Download starts: https://1fichier.com/?n7x4j8i6fqg1j4hdw36p&af=3797078
333 | 11.06.2023 13:36:24 | WARNING | HOSTER OneFichierCom[13]: Plugin may be unstable
334 | 11.06.2023 13:36:24 | INFO | ACCOUNT OneFichierCom: Relogin user `dre*******`...
335 | 11.06.2023 13:36:24 | INFO | ACCOUNT OneFichierCom: Grabbing account info for user `dre*******`...
336 | 11.06.2023 13:36:25 | INFO | HOSTER OneFichierCom[13]: Processing url: https://1fichier.com/?n7x4j8i6fqg1j4hdw36p&af=3797078
337 | 11.06.2023 13:36:25 | INFO | HOSTER OneFichierCom[13]: Looking for direct download link...
338 | 11.06.2023 13:36:25 | INFO | HOSTER OneFichierCom[13]: Direct download link not found
339 | 11.06.2023 13:36:25 | INFO | HOSTER OneFichierCom[13]: Checking for link errors...
340 | 11.06.2023 13:36:25 | INFO | HOSTER OneFichierCom[13]: No errors found
341 | 11.06.2023 13:36:25 | INFO | HOSTER OneFichierCom[13]: Grabbing link info...
342 | 11.06.2023 13:36:25 | INFO | HOSTER OneFichierCom[13]: Link name: Star.Wars.Andor.S01E01.FRENCH.1080p.WEB.H264-Wawacity.red.mkv
343 | 11.06.2023 13:36:25 | INFO | HOSTER OneFichierCom[13]: Link size: 1.71 GiB (1836098519 bytes)
344 | 11.06.2023 13:36:25 | INFO | HOSTER OneFichierCom[13]: Link status: en ligne
345 | 11.06.2023 13:36:25 | INFO | HOSTER OneFichierCom[13]: Processing as free download...
346 | 11.06.2023 13:36:25 | INFO | HOSTER OneFichierCom[13]: Checking for link errors...
347 | 11.06.2023 13:36:25 | INFO | HOSTER OneFichierCom[13]: No errors found
348 | 11.06.2023 13:36:25 | INFO | HOSTER OneFichierCom[13]: Downloading file...
349 | 11.06.2023 13:37:13 | INFO | ACCOUNT OneFichierCom: Updating account info for user `dre*******`...
350 | 11.06.2023 13:37:13 | INFO | ACCOUNT OneFichierCom: Relogin user `dre*******`...
351 | 11.06.2023 13:37:39 | INFO | ACCOUNT OneFichierCom: Removing user `dre*******`...
352 | 11.06.2023 13:37:40 | WARNING | Assign job error: 'dreko.dev@gmail.com'
353 | 11.06.2023 13:37:40 | ERROR | <<< UNCAUGHT EXCEPTION >>>
354 | ? | ? | Traceback (most recent call last):
355 | ? | ? | File "/app/pyload/pyLoadCore.py", line 731, in
356 | ? | ? | main()
357 | ? | ? | File "/app/pyload/pyLoadCore.py", line 722, in main
358 | ? | ? | pyload_core.start()
359 | ? | ? | File "/app/pyload/pyLoadCore.py", line 534, in start
360 | ? | ? | self.threadManager.work()
361 | ? | ? | File "/app/pyload/module/ThreadManager.py", line 146, in work
362 | ? | ? | self.assignJob()
363 | ? | ? | File "/app/pyload/module/ThreadManager.py", line 258, in assignJob
364 | ? | ? | inuse = set([(x.active.pluginname,self.getLimit(x)) for x in self.threads if x.active and x.active.hasPlugin() and x.active.plugin.account])
365 | ? | ? | File "/app/pyload/module/ThreadManager.py", line 306, in getLimit
366 | ? | ? | limit = thread.active.plugin.account.getAccountData(thread.active.plugin.user)["options"].get("limitDL",["0"])[0]
367 | ? | ? | File "/config/userplugins/internal/misc.py", line 231, in new
368 | ? | ? | return fn(*args, **kwargs)
369 | ? | ? | File "/config/userplugins/internal/Account.py", line 279, in getAccountData
370 | ? | ? | return self.accounts[user]
371 | ? | ? | KeyError: 'dreko.dev@gmail.com'
372 | 11.06.2023 13:38:03 | INFO | ACCOUNT OneFichierCom: Adding user `dre*******`...
373 | 11.06.2023 13:38:03 | INFO | ACCOUNT OneFichierCom: Login user `dre*******`...
374 | 11.06.2023 13:38:03 | INFO | ACCOUNT OneFichierCom: Grabbing account info for user `dre*******`...
375 | 11.06.2023 13:40:56 | INFO | Download aborted: Star.Wars.Andor.S01E01.FRENCH.1080p.WEB.H264-Wawacity.red.mkv
376 | 11.06.2023 13:42:29 | INFO | ACCOUNT OneFichierCom: Updating account info for user `dre*******`...
377 | 11.06.2023 13:42:29 | INFO | ACCOUNT OneFichierCom: Relogin user `dre*******`...
378 | 11.06.2023 13:42:39 | INFO | ACCOUNT OneFichierCom: Updating account info for user `dre*******`...
379 | 11.06.2023 13:42:39 | INFO | ACCOUNT OneFichierCom: Relogin user `dre*******`...
380 | 11.06.2023 14:06:19 | INFO | Added package Andor containing 12 links
381 | 11.06.2023 14:07:01 | INFO | ACCOUNT OneFichierCom: Updating account info for user `dre*******`...
382 | 11.06.2023 14:07:01 | INFO | ACCOUNT OneFichierCom: Relogin user `dre*******`...

It seems that the downloading is blocked even after reconnecting to 1fichier premium account

### Screenshots

<img width="1267" alt="image" src="https://github.com/pyload/pyload/assets/30262332/6121d2c0-8587-4c8c-89dd-cc2149a14a33">
<img width="1270" alt="image" src="https://github.com/pyload/pyload/assets/30262332/97e62219-7146-4ad9-a0df-329f76b96e63">

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.
