### ISSUE TITLE
Exception: Loaded URL exceeded limit (2000000)

### ISSUE THREAD

**Issue by V-a-v-a-n** [pyload/pyload#4368]
### Description
I encountered an issue while trying to download a 20 GB file from the uptobox.com host using pyLoad in its latest version, "pyload-ng 0.5.0b3.dev73." When I initiate the download, I receive the following error message: "Loaded URL exceeded limit (2000000)."

### Debug log
[2023-09-05 19:19:36]  INFO                pyload  *** Welcome to pyLoad 0.5.0 ***
[2023-09-05 19:19:36]  DEBUG               pyload  Indexing plugins...
[2023-09-05 19:19:36]  INFO                pyload  Activated addons: ClickNLoad, ExternalScripts, TORRENT, UnSkipOnFail, UserAgentSwitcher
[2023-09-05 19:19:36]  INFO                pyload  Deactivate addons: AndroidPhoneNotify, AntiCaptcha, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, UpdateManager, WindowsPhoneNotify, XFileSharing, XMPP
[2023-09-05 19:19:36]  DEBUG               pyload  Starting core...
[2023-09-05 19:19:36]  DEBUG               pyload  Debug level: DEBUG
[2023-09-05 19:19:36]  DEBUG               pyload  Setup language...
[2023-09-05 19:19:36]  DEBUG               pyload  Setup permissions...
[2023-09-05 19:19:36]  INFO                pyload  User directory: /root/.pyload
[2023-09-05 19:19:36]  INFO                pyload  Cache directory: /tmp/pyLoad
[2023-09-05 19:19:36]  INFO                pyload  Storage directory: /root/Downloads/pyLoad
[2023-09-05 19:19:36]  INFO                pyload  Storage free space: 31.36 GiB
[2023-09-05 19:19:36]  DEBUG               pyload  Setup network...
[2023-09-05 19:19:36]  INFO                pyload  Activating accounts...
[2023-09-05 19:19:36]  INFO                pyload  ACCOUNT UptoboxCom: Adding user `_Va*******`...
[2023-09-05 19:19:36]  DEBUG               pyload  ACCOUNT UptoboxCom: Reached login timeout for user `_Va****`
[2023-09-05 19:19:36]  INFO                pyload  ACCOUNT UptoboxCom: Login user `_Va****`...
[2023-09-05 19:19:36]  DEBUG               pyload  ACCOUNT UptoboxCom: LOAD URL https://uptobox.link/login | get={} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2023-09-05 19:19:36]  DEBUG               pyload  ACCOUNT UptoboxCom: LOAD URL https://uptobox.link/login | get={} | post={'login': '_Va****', 'password': '**********'} | ref=https://uptobox.link/login | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2023-09-05 19:19:36]  INFO                pyload  ACCOUNT UptoboxCom: Grabbing account info for user `_Va****`...
[2023-09-05 19:19:36]  DEBUG               pyload  ACCOUNT UptoboxCom: LOAD URL https://uptobox.link/my_account | get={} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2023-09-05 19:19:36]  DEBUG               pyload  ACCOUNT UptoboxCom: Account info for user `_Va****`: {'login': {'password': '**********', 'stats': [1, 0], 'timestamp': 1693941576.615467, 'valid': True}, 'data': {'login': '_Va****', 'options': {'limit_dl': ['0']}, 'plugin': <Account UptoboxCom>, 'premium': True, 'trafficleft': -1, 'type': 'UptoboxCom', 'validuntil': 1735089712.0}}
[2023-09-05 19:19:36]  INFO                pyload  Activating plugins...
[2023-09-05 19:19:36]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `pyload_start`
[2023-09-05 19:19:36]  WARNING             pyload  ADDON TORRENT: torrents / magnets are not associated with any plugin
[2023-09-05 19:19:36]  INFO          pyload.webui  Starting webserver: http://localhost:8000
[2023-09-05 19:19:36]  DEBUG               pyload  *** pyLoad is up and running ***
[2023-09-05 19:19:41]  DEBUG               pyload  ADDON ClickNLoad: Backend found on http://127.0.0.1:8000
[2023-09-05 19:19:41]  INFO                pyload  ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
[2023-09-05 19:20:19]  INFO                pyload  User 'pyload' successfully logged in
[2023-09-05 19:20:29]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `package_deleted`
[2023-09-05 19:24:06]  INFO                pyload  Added package test containing 1 links
[2023-09-05 19:24:07]  INFO                pyload  Download starts: 1xr9lmih6a9n
[2023-09-05 19:24:07]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `download_preparing`
[2023-09-05 19:24:07]  DEBUG               pyload  ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
[2023-09-05 19:24:07]  DEBUG               pyload  ADDON UserAgentSwitcher: Setting maximum redirections to 10
[2023-09-05 19:24:07]  DEBUG               pyload  ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0`
[2023-09-05 19:24:07]  DEBUG               pyload  DOWNLOADER UptoboxCom[2]: Plugin version: 0.40
[2023-09-05 19:24:07]  DEBUG               pyload  DOWNLOADER UptoboxCom[2]: Plugin status: testing
[2023-09-05 19:24:07]  WARNING             pyload  DOWNLOADER UptoboxCom[2]: Plugin may be unstable
[2023-09-05 19:24:07]  INFO                pyload  ACCOUNT UptoboxCom: Grabbing account info for user `_Va****`...
[2023-09-05 19:24:07]  DEBUG               pyload  ACCOUNT UptoboxCom: LOAD URL https://uptobox.link/my_account | get={} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2023-09-05 19:24:07]  DEBUG               pyload  ACCOUNT UptoboxCom: Account info for user `_Va****`: {'login': {'password': '**********', 'stats': [1, 0], 'timestamp': 1693941576.615467, 'valid': True}, 'data': {'login': '_Va****', 'options': {'limit_dl': ['0']}, 'plugin': <Account UptoboxCom>, 'premium': True, 'trafficleft': -1, 'type': 'UptoboxCom', 'validuntil': 1735089712.0}}
[2023-09-05 19:24:07]  DEBUG               pyload  ACCOUNT UptoboxCom: Using account _Va*******
[2023-09-05 19:24:07]  INFO                pyload  DOWNLOADER UptoboxCom[2]: Processing url: https://uptobox.com/1xr9lmih6a9n
[2023-09-05 19:24:07]  DEBUG               pyload  DOWNLOADER UptoboxCom[2]: LOAD URL https://uptobox.link/1xr9lmih6a9n | get={} | post={} | ref=False | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2023-09-05 19:24:08]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `download_processed`
[2023-09-05 19:24:08]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `package_processed`
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyload/core/threads/download_thread.py", line 56, in run
    pyfile.plugin.preprocessing(self)
  File "/usr/local/lib/python3.10/dist-packages/pyload/plugins/base/hoster.py", line 291, in preprocessing
    return self._process(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyload/plugins/base/downloader.py", line 103, in _process
    self.process(self.pyfile)
  File "/usr/local/lib/python3.10/dist-packages/pyload/plugins/base/simple_downloader.py", line 266, in process
    self._preload()
  File "/usr/local/lib/python3.10/dist-packages/pyload/plugins/base/simple_downloader.py", line 249, in _preload
    self.data = self.load(
  File "/usr/local/lib/python3.10/dist-packages/pyload/plugins/base/hoster.py", line 506, in load
    return super().load(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyload/plugins/base/plugin.py", line 217, in load
    html = req.load(
  File "/usr/local/lib/python3.10/dist-packages/pyload/core/network/browser.py", line 127, in load
    return self.http.load(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyload/core/network/http/http_request.py", line 314, in load
    raise self.exception from None
Exception: Loaded URL exceeded limit (2000000)
[2023-09-05 19:24:08]  WARNING             pyload  Download failed: 1xr9lmih6a9n | Loaded URL exceeded limit (2000000)
[2023-09-05 19:24:08]  INFO                pyload  Debug Report written to /tmp/pyLoad/debug_UptoboxCom_2023-09-05_19-24-08.zip
[2023-09-05 19:24:08]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `download_failed`
[2023-09-05 19:24:08]  INFO                pyload  ADDON UnSkipOnFail: Looking for skipped duplicates of: 1xr9lmih6a9n (pid:2)
[2023-09-05 19:24:08]  INFO                pyload  ADDON UnSkipOnFail: No duplicates found
[2023-09-05 19:24:08]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `all_downloads_processed`
[2023-09-05 19:24:08]  DEBUG               pyload  All downloads processed

### Additional references
This issue has occurred consistently for me when trying to download large files (20 GB) from the uptobox.com host using pyLoad.
- I have checked the pyLoad documentation and community forums but couldn't find a solution to this problem.
- I have attempted to adjust the configuration settings in pyLoad to resolve this issue, but the error persists.

### Screenshots
<img width="496" alt="image" src="https://github.com/pyload/pyload/assets/83417702/0c624491-e626-4bb2-89b2-ec77e313b287">

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by V-a-v-a-n** [comment]
What account ?

**Comment by GammaC0de** [comment]
Your account foe Uptobox

**Comment by V-a-v-a-n** [comment]
I appreciate your willingness to help with troubleshooting the issue. However, I'm unable to provide temporary account information for testing.

**Comment by V-a-v-a-n** [comment]
Thank 😊
