### ISSUE TITLE
FilerNet account fails after some downloads

### ISSUE THREAD

**Issue by Riffer** [pyload/pyload#4373]
### Description
After some downloads the plugins some 'loses' the account and subsequentially all downloads fail.

In settings the account is marked as failed without further information.
After restarting the pyload service the account is back and all links work again.

### Debug log
pyLoad 0.5.0 Debug Report of FilerNet 0.31 

TRACEBACK:
 Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyload/core/threads/download_thread.py", line 56, in run
    pyfile.plugin.preprocessing(self)
  File "/usr/local/lib/python3.7/dist-packages/pyload/plugins/base/hoster.py", line 291, in preprocessing
    return self._process(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pyload/plugins/base/downloader.py", line 92, in _process
    self._setup()
  File "/usr/local/lib/python3.7/dist-packages/pyload/plugins/base/hoster.py", line 152, in _setup
    self.load_account()  # TODO: Move to PluginThread in 0.6.x
  File "/usr/local/lib/python3.7/dist-packages/pyload/plugins/base/downloader.py", line 84, in load_account
    super().load_account()
  File "/usr/local/lib/python3.7/dist-packages/pyload/plugins/base/hoster.py", line 183, in load_account
    self.account.choose()
  File "/usr/local/lib/python3.7/dist-packages/pyload/core/utils/struct/lock.py", line 22, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pyload/plugins/base/account.py", line 462, in choose
    user = self.select()[0]
  File "/usr/local/lib/python3.7/dist-packages/pyload/core/utils/struct/lock.py", line 22, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pyload/plugins/base/account.py", line 396, in select
    if not self.accounts[user]["plugin"].choose(user):
AttributeError: 'NoneType' object has no attribute 'choose'
 

FRAMESTACK:

_frame preprocessing in /usr/local/lib/python3.7/dist-packages/pyload/plugins/base/hoster.py at line 291
	self                 = <Downloader FilerNet>
	args                 = (<DownloadThread(Thread-2, started daemon 1956570208)>,)
	kwargs               = {}

_frame _process in /usr/local/lib/python3.7/dist-packages/pyload/plugins/base/downloader.py at line 126
	self                 = <Downloader FilerNet>
	thread               = <DownloadThread(Thread-2, started daemon 1956570208)>

_frame _setup in /usr/local/lib/python3.7/dist-packages/pyload/plugins/base/hoster.py at line 152
	self                 = <Downloader FilerNet>

_frame load_account in /usr/local/lib/python3.7/dist-packages/pyload/plugins/base/downloader.py at line 84
	self                 = <Downloader FilerNet>
	__class__            = <class 'pyload.plugins.base.downloader.BaseDownloader'>

_frame load_account in /usr/local/lib/python3.7/dist-packages/pyload/plugins/base/hoster.py at line 183
	self                 = <Downloader FilerNet>

_frame wrapped in /usr/local/lib/python3.7/dist-packages/pyload/core/utils/struct/lock.py at line 24
	self                 = <Account FilerNet>
	args                 = ()
	kwargs               = {}
	func                 = <function BaseAccount.choose at 0x71bbd150>
	kwgs                 = {}

_frame choose in /usr/local/lib/python3.7/dist-packages/pyload/plugins/base/account.py at line 462
	self                 = <Account FilerNet>
	user                 = None

_frame wrapped in /usr/local/lib/python3.7/dist-packages/pyload/core/utils/struct/lock.py at line 24
	self                 = <Account FilerNet>
	args                 = ()
	kwargs               = {}
	func                 = <function BaseAccount.select at 0x71bbd0c0>
	kwgs                 = {}

_frame select in /usr/local/lib/python3.7/dist-packages/pyload/plugins/base/account.py at line 396
	self                 = <Account FilerNet>
	hide                 = <function BaseAccount.select.<locals>.hide at 0x699febb8>
	free_accounts        = {}
	premium_accounts     = {}
	user                 = 'XxXxXxXx@somewhere.to'

_PLUGIN OBJECT DUMP: 

	CHECK_FILE           = True
	CHECK_TRAFFIC        = False
	COOKIES              = True
	DIRECT_LINK          = True
	DISPOSITION          = True
	DL_LIMIT_PATTERN     = None
	ERROR_PATTERN        = None
	FILE_ERRORS          = [('Html error',
  b'\\A(?:\\s*<.+>)?((?:[\\w\\s]*(?:[Ee]rror|ERROR)\\s*\\:?)?\\s*\\d{3})(?:\\'
  b'Z|\\s+)'),
 ('Request error', b'([Aa]n error occurred while processing your request)'),
 ('Html file', b'\\A\\s*<!DOCTYPE html')]
	HAPPY_HOUR_PATTERN   = None
	HASHSUM_PATTERN      = ('[^\\w](?P<H>(CRC|crc)(-?32)?|(MD|md)-?5|(SHA|sha)-?(1|224|256|384|512)).*(:|=|>)[ '
 ']*(?P<D>(?:[a-z0-9]|[A-Z0-9]){8,})')
	INFO_PATTERN         = ('<h1 class="page-header">Free Download (?P<N>\\S+) <small>(?P<S>[\\w.]+) '
 '(?P<U>[\\w^_]+)</small></h1>')
	IP_BLOCKED_PATTERN   = None
	LINK_FREE_PATTERN    = None
	LINK_PATTERN         = 'href="([^"]+)">Get download</a>'
	LINK_PREMIUM_PATTERN = None
	LOGIN_ACCOUNT        = False
	LOGIN_PREMIUM        = False
	NAME_PATTERN         = None
	NAME_REPLACEMENTS    = []
	OFFLINE_PATTERN      = 'Datei +nicht mehr vorhanden'
	PREMIUM_ONLY_PATTERN = None
	SIZE_LIMIT_PATTERN   = None
	SIZE_PATTERN         = None
	SIZE_REPLACEMENTS    = []
	TEMP_OFFLINE_PATTERN = 'Leider sind alle kostenlosen Download-Slots belegt'
	TEXT_ENCODING        = True
	URL_REPLACEMENTS     = []
	WAIT_PATTERN         = 'var count = (\\d+);'
	_last_download       = ''
	account              = <Account FilerNet>
	captcha              = <Anticaptcha BaseCaptcha>
	chunk_limit          = None
	classname            = 'FilerNet'
	config               = <pyload.plugins.helpers.Config object at 0x69d33cb0>
	data                 = ''
	db                   = <pyload.plugins.helpers.DB object at 0x69d33790>
	info                 = {}
	last_check           = None
	last_download        = ''
	last_header          = {}
	last_html            = ''
	limit_dl             = 0
	multi_dl             = True
	no_fallback          = False
	premium              = None
	pyfile               = PyFile 621: r8clkq3odhadvnmn@FilerNet
	pyload               = <pyload.core.Core object at 0x757d7710>
	req                  = <pyload.core.network.browser.Browser object at 0x69d33f70>
	restart_free         = False
	resume_download      = False
	retries              = {}
	thread               = <DownloadThread(Thread-2, started daemon 1956570208)>
	waiting              = False
	want_reconnect       = False

_PYFILE OBJECT DUMP: 

	_name                = 'YYYYYYYY'
	_size                = 0
	abort                = False
	active               = False
	error                = "'NoneType' object has no attribute 'choose'"
	id                   = 621
	lock                 = <unlocked _thread.RLock object owner=0 count=0 at 0x69d25d58>
	m                    = <pyload.core.managers.file_manager.FileManager object at 0x7558df50>
	manager              = <pyload.core.managers.file_manager.FileManager object at 0x7558df50>
	maxprogress          = 100
	name                 = 'r8clkq3odhadvnmn'
	order                = 9
	packageid            = 70
	plugin               = <Downloader FilerNet>
	pluginclass          = <class 'pyload.plugins.downloaders.FilerNet.FilerNet'>
	pluginmodule         = <module 'pyload.plugins.downloaders.FilerNet' from '/usr/local/lib/python3.7/dist-packages/pyload/plugins/downloaders/FilerNet.py'>
	pluginname           = 'FilerNet'
	progress             = 0
	reconnected          = False
	size                 = 0
	status               = 8
	statusname           = None
	url                  = 'http://filer.net/get/YYYYYYY'
	wait_until           = 0

CONFIG: 

{'chk_filesize': {'desc': 'Check file size', 'type': 'bool', 'value': True},
 'desc': 'FilerNet',
 'enabled': {'desc': 'Activated', 'type': 'bool', 'value': True},
 'fallback': {'desc': 'Fallback to free download if premium fails',
              'type': 'bool',
              'value': False},
 'max_wait': {'desc': 'Reconnect if waiting time is greater than minutes',
              'type': 'int',
              'value': 3600},
 'outline': 'Filer.net downloader plugin',
 'use_premium': {'desc': 'Use premium account if available',
                 'type': 'bool',
                 'value': True}}

### Screenshots
![grafik](https://github.com/pyload/pyload/assets/851325/d44136fa-887d-48d0-9ed1-c742a898d769)

**Comment by GammaC0de** [comment]
Please provide debug logs, not debug report.

**Comment by Riffer** [comment]
Does this help? If not, please point me to a howto, please.
----
[2023-09-27 20:06:12]  DEBUG               pyload  ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
[2023-09-27 20:06:12]  DEBUG               pyload  ADDON UserAgentSwitcher: Setting maximum redirections to 10
[2023-09-27 20:06:12]  DEBUG               pyload  ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0`
[2023-09-27 20:06:12]  DEBUG               pyload  DOWNLOADER FilerNet[1067]: Plugin version: 0.31
[2023-09-27 20:06:12]  DEBUG               pyload  DOWNLOADER FilerNet[1067]: Plugin status: testing
[2023-09-27 20:06:12]  WARNING             pyload  DOWNLOADER FilerNet[1067]: Plugin may be unstable
[2023-09-27 20:06:12]  DEBUG               pyload  ACCOUNT FilerNet: Reached login timeout for user `rif****`
[2023-09-27 20:06:12]  INFO                pyload  ACCOUNT FilerNet: Relogin user `rif****`...
[2023-09-27 20:06:12]  DEBUG               pyload  ACCOUNT FilerNet: LOAD URL https://filer.net/login | get={} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2023-09-27 20:06:12]  ERROR               pyload  ACCOUNT FilerNet: Could not login user `rif****` | 'NoneType' object has no attribute 'group'
[2023-09-27 20:06:12]  INFO                pyload  DOWNLOADER FilerNet[1067]: Processing url: https://filer.net/get/04gzk2mrnyiqvkru
[2023-09-27 20:06:12]  INFO                pyload  DOWNLOADER FilerNet[1067]: Looking for direct download link...
[2023-09-27 20:06:12]  DEBUG               pyload  DOWNLOADER FilerNet[1067]: LOAD URL https://filer.net/get/04gzk2mrnyiqvkru | get={} | post={} | ref=True | cookies=True | just_header=True | decode=True | multipart=False | redirect=True | req=None
[2023-09-27 20:06:14]  INFO                pyload  DOWNLOADER FilerNet[1067]: Direct download link detected
[2023-09-27 20:06:14]  INFO                pyload  DOWNLOADER FilerNet[1067]: Downloading file...
[2023-09-27 20:06:14]  DEBUG               pyload  DOWNLOADER FilerNet[1067]: DOWNLOAD URL https://filer.net/get/XXXXX | get={} | post={} | ref=True | cookies=True | disposition=True | resume=None | chunks=None
[2023-09-27 20:06:16]  DEBUG               pyload  Content-Disposition: XXXXX.epub
[2023-09-27 20:06:16]  DEBUG               pyload  Chunk 1 chunked with range 0-
[2023-09-27 20:06:17]  DEBUG               pyload  Chunk 1 download finished
[2023-09-27 20:06:17]  INFO                pyload  DOWNLOADER FilerNet[1067]: File saved
[2023-09-27 20:06:17]  INFO                pyload  DOWNLOADER FilerNet[1067]: Checking download...
[2023-09-27 20:06:18]  INFO                pyload  DOWNLOADER FilerNet[1067]: File is OK
[2023-09-27 20:06:18]  INFO                pyload  DOWNLOADER FilerNet[1067]: Checking file (with built-in rules)...
[2023-09-27 20:06:18]  INFO                pyload  DOWNLOADER FilerNet[1067]: Checking file (with custom rules)...
[2023-09-27 20:06:18]  INFO                pyload  DOWNLOADER FilerNet[1067]: Checking for link errors...
[2023-09-27 20:06:18]  INFO                pyload  DOWNLOADER FilerNet[1067]: No errors found
[2023-09-27 20:06:18]  INFO                pyload  Download finished: XXXX.epub
[2023-09-27 20:06:18]  INFO                pyload  Package finished: asdf
[2023-09-27 20:06:18]  DEBUG               pyload  ADDON ExtractArchive: Use for extensions: .001|.7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
[2023-09-27 20:06:18]  DEBUG               pyload  All downloads processed
[2023-09-27 20:06:18]  INFO                pyload  ADDON ExtractArchive: Check package: asdf
[2023-09-27 20:06:18]  DEBUG               pyload  All downloads finished
[2023-09-27 20:06:18]  INFO                pyload  ADDON ExtractArchive: No files found to extract

**Comment by GammaC0de** [comment]
Do you know how to edit python files?

**Comment by Riffer** [comment]
Yes - let me know what to change.

**Comment by GammaC0de** [comment]
Apply this patch into /usr/local/lib/python3.7/dist-packages/pyload/plugins/accounts/FilerNet.py.
When login would fail, there would be a HTML file in /tmp/pyLoad directory, please post the file here.

```
Subject: [PATCH] FilerNet
---
Index: src/pyload/plugins/accounts/FilerNet.py
<+>UTF-8
===================================================================
diff --git a/src/pyload/plugins/accounts/FilerNet.py b/src/pyload/plugins/accounts/FilerNet.py
--- a/src/pyload/plugins/accounts/FilerNet.py	(revision 88c0c69b6f78afd3e0234693132047323c561c44)
+++ b/src/pyload/plugins/accounts/FilerNet.py	(date 1696093178220)
@@ -51,7 +51,12 @@
     def signin(self, user, password, data):
         html = self.load("https://filer.net/login")
 
-        token = re.search(self.TOKEN_PATTERN, html).group(1)
+        m = re.search(self.TOKEN_PATTERN, html)
+        if m is None:
+            self.dump_html()
+            self.fail_login()
+        else:
+            token = m.group(1)
 
         html = self.load(
             "https://filer.net/login_check",
```

**Comment by Riffer** [comment]
I attached the dumped file - only modified the account name in it. 

[load_line250.dump.html.zip](https://github.com/pyload/pyload/files/12776974/load_line250.dump.html.zip)

With your modification, the account fails now every time, while before a service restart repaired it somehow. 

Maybe this is just about a timing problem or a previous check that the account is fine fails and following up the (re-)login happens too soon?

**Comment by GammaC0de** [comment]
Plugin updated, please confirm fixed

**Comment by Riffer** [comment]
Confirmed!

The account data stays rock solid even after several hours and multiple downloads.

Thank you very much 👍

**Comment by GammaC0de** [comment]
👍
