### ISSUE TITLE
Captcha9Kw crashing with TypeError 

### ISSUE THREAD

**Issue by myxor** [pyload/pyload#4377]
### Description
Captcha9Kw plugin stopped working a couple of days ago.

### Debug log

```

7837	2023-10-08 18:29:59	DEBUG	pyload	ADDON Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | get={'apikey': '[xxxxxxx]', 'pyload': '1', 'source': 'pyload', 'action': 'usercaptchaguthaben'} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
7838	2023-10-08 18:29:59	INFO	pyload	ADDON Captcha9Kw: [xxxxx] credits left
7839	2023-10-08 18:29:59	DEBUG	pyload	ADDON Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt | get={} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
7840	2023-10-08 18:29:59	WARNING	pyload	Unable to create captcha task
7841	? 	?	?	Traceback (most recent call last):
7842	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/core/managers/captcha_manager.py", line 52, in handle_captcha
7843	? 	?	?	    plugin.captcha_task(task)
7844	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/addons/Captcha9Kw.py", line 272, in captcha_task
7845	? 	?	?	    if not details or details[0].lower() != pluginname.lower():
7846	? 	?	?	                      ~~~~~~~^^^
7847	? 	?	?	TypeError: 'generator' object is not subscriptable
```

Note: Number of credits left was changed by me. It is a positive number.

### Screenshots

```
System

Python Version:
    3.11.4 (main, Jun 9 2023, 02:29:05) [GCC 12.2.1 20220924]
OS Platform:
    posix linux Linux aarch64

pyLoad

Version:
    0.5.0

Docker installation using linuxserver/pyload-ng:arm64v8-latest image.
```

**Comment by GammaC0de** [comment]
Does this happen on a specific site/hoster?

Please post more of the logs

**Comment by myxor** [comment]
Happened on DDownload.com.



```
7810 | 2023-10-08 18:29:59 | INFO | pyload | Download starts: xxxxx.rar
-- | -- | -- | -- | --
7811 | 2023-10-08 18:29:59 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_preparing`
7812 | 2023-10-08 18:29:59 | DEBUG | pyload | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
7813 | 2023-10-08 18:29:59 | DEBUG | pyload | ADDON UserAgentSwitcher: Setting maximum redirections to 10
7814 | 2023-10-08 18:29:59 | DEBUG | pyload | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0`
7815 | 2023-10-08 18:29:59 | DEBUG | pyload | DOWNLOADER DdownloadCom[30]: Plugin version: 0.11
7816 | 2023-10-08 18:29:59 | DEBUG | pyload | DOWNLOADER DdownloadCom[30]: Plugin status: testing
7817 | 2023-10-08 18:29:59 | WARNING | pyload | DOWNLOADER DdownloadCom[30]: Plugin may be unstable
7818 | 2023-10-08 18:29:59 | INFO | pyload | DOWNLOADER DdownloadCom[30]: Processing url: https://ddownload.com/xxxxx
7819 | 2023-10-08 18:29:59 | DEBUG | pyload | DOWNLOADER DdownloadCom[30]: LOAD URL https://ddownload.com/xxxxx \| get={} \| post={} \| ref=False \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
7820 | 2023-10-08 18:29:59 | INFO | pyload | DOWNLOADER DdownloadCom[30]: Checking for link errors...
7821 | 2023-10-08 18:29:59 | INFO | pyload | DOWNLOADER DdownloadCom[30]: No errors found
7822 | 2023-10-08 18:29:59 | INFO | pyload | DOWNLOADER DdownloadCom[30]: Grabbing link info...
7823 | 2023-10-08 18:29:59 | DEBUG | pyload | DOWNLOADER DdownloadCom[30]: Link info: {'name': 'xxxxx', 'hash': {}, 'pattern': {'ID': 'xxxxx', 'N': 'xxxxx', 'S': '1000.00', 'U': 'MB'}, 'size': 1048576000, 'status': 2, 'url': 'https://ddownload.com/xxxxx'}
7824 | 2023-10-08 18:29:59 | DEBUG | pyload | DOWNLOADER DdownloadCom[30]: Previous link info: {}
7825 | 2023-10-08 18:29:59 | INFO | pyload | DOWNLOADER DdownloadCom[30]: Link name: xxxxx.rar
7826 | 2023-10-08 18:29:59 | INFO | pyload | DOWNLOADER DdownloadCom[30]: Link size: 1000.00 MiB (1048576000 bytes)
7827 | 2023-10-08 18:29:59 | INFO | pyload | DOWNLOADER DdownloadCom[30]: Link status: online
7828 | 2023-10-08 18:29:59 | INFO | pyload | DOWNLOADER DdownloadCom[30]: Processing as free download...
7829 | 2023-10-08 18:29:59 | DEBUG | pyload | DOWNLOADER DdownloadCom[30]: Getting download link #1...
7830 | 2023-10-08 18:29:59 | INFO | pyload | DOWNLOADER DdownloadCom[30]: Checking for link errors...
7831 | 2023-10-08 18:29:59 | INFO | pyload | DOWNLOADER DdownloadCom[30]: No errors found
7832 | 2023-10-08 18:29:59 | DEBUG | pyload | DOWNLOADER DdownloadCom[30]: {'op': 'download2', 'id': 'xxxxx', 'rand': 'xxxxx', 'referer': '', 'method_free': '', 'method_premium': '', 'adblock_detected': ''}
7833 | 2023-10-08 18:29:59 | DEBUG | pyload | ANTICAPTCHA DdownloadCom[30]: ReCaptcha \| xxxxx \| Wrong key format, this probably because it is not a reCAPTCHA key
7834 | 2023-10-08 18:29:59 | WARNING | pyload | ANTICAPTCHA DdownloadCom[30]: ReCaptcha \| Key pattern not found
7835 | 2023-10-08 18:29:59 | DEBUG | pyload | ANTICAPTCHA DdownloadCom[30]: HCaptcha \| Key: xxxxx
7836 | 2023-10-08 18:29:59 | DEBUG | pyload | ANTICAPTCHA DdownloadCom[30]: HCaptcha \| Challenge hCaptcha interactive
7837 | 2023-10-08 18:29:59 | DEBUG | pyload | ADDON Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi \| get={'apikey': 'xxxxx', 'pyload': '1', 'source': 'pyload', 'action': 'usercaptchaguthaben'} \| post={} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
7838 | 2023-10-08 18:29:59 | INFO | pyload | ADDON Captcha9Kw: xxxxx credits left
7839 | 2023-10-08 18:29:59 | DEBUG | pyload | ADDON Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt \| get={} \| post={} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
7840 | 2023-10-08 18:29:59 | WARNING | pyload | Unable to create captcha task
7841 | ? | ? | ? | Traceback (most recent call last):
7842 | ? | ? | ? | File "/lsiopy/lib/python3.11/site-packages/pyload/core/managers/captcha_manager.py", line 52, in handle_captcha
7843 | ? | ? | ? | plugin.captcha_task(task)
7844 | ? | ? | ? | File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/addons/Captcha9Kw.py", line 272, in captcha_task
7845 | ? | ? | ? | if not details or details[0].lower() != pluginname.lower():
7846 | ? | ? | ? | ~~~~~~~^^^
7847 | ? | ? | ? | TypeError: 'generator' object is not subscriptable
```
