### ISSUE TITLE
pyload Does not start anymore after update from 0.4.9 to 0.4.20

### ISSUE THREAD

**Issue by geronimoronin** [pyload/pyload#4387]
Halo after update (acording https://github.com/pyload/pyload/issues/3520)   from 0.4.9 to 0.4.20 pyload Does not start anymore.
System: Netgear R7800, Entware-NG

befor Update
 pyload --configdir=/opt/var/pyload
07.11.2023 05:01:39 INFO      starte pyLoad 0.4.9
07.11.2023 05:01:39 INFO      Benutze Home-Verzeichnis: /opt/var/pyload
07.11.2023 05:01:42 INFO      Aktivierte Plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
07.11.2023 05:01:42 INFO      Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
07.11.2023 05:01:42 INFO      Downloadzeit: True
07.11.2023 05:01:42 INFO      Starte ThriftBackend: 0.0.0.0:7227
07.11.2023 05:01:44 INFO      Starting builtin webserver: 0.0.0.0:8000
07.11.2023 05:01:44 INFO      Free space: 3.49 GiB
07.11.2023 05:01:44 INFO      Activating Accounts...
07.11.2023 05:01:44 INFO      Activating Plugins...
07.11.2023 05:01:44 WARNING   ADDON UpdateManager: Unable to connect to the server to retrieve updates
07.11.2023 05:01:47 INFO      ADDON XFileSharing: Auto-discover new hosters
07.11.2023 05:01:47 INFO      ADDON XFileSharing: Auto-discover new crypters
07.11.2023 05:01:47 INFO      pyLoad is up and running
07.11.2023 05:01:53 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
^C07.11.2023 05:05:37 INFO      shutting down...
07.11.2023 05:05:37 INFO      ADDON ClickNLoad: Shutting down proxy...
07.11.2023 05:05:37 INFO      killed pyLoad from Terminal

after Update

root@R7800:~# pyload --configdir=/opt/var/pyload
07.11.2023 05:08:30 INFO      starte pyLoad 0.4.20
07.11.2023 05:08:30 INFO      Benutze Home-Verzeichnis: /opt/var/pyload
07.11.2023 05:08:33 INFO      Aktivierte Plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, TORRENT, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
07.11.2023 05:08:33 INFO      Deaktivierte Plugins: AntiCaptcha, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
07.11.2023 05:08:33 INFO      Downloadzeit: True
07.11.2023 05:08:33 INFO      Starte ThriftBackend: 0.0.0.0:7227
07.11.2023 05:08:35 INFO      Starting builtin webserver: :::8000
07.11.2023 05:08:35 INFO      Free space: 3.49 GiB
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/share/pyload/module/web/ServerThread.py", line 78, in run
    self.start_builtin()
  File "/opt/share/pyload/module/web/ServerThread.py", line 85, in start_builtin
    webinterface.run_simple(host=self.host, port=self.port)
  File "/opt/share/pyload/module/web/webinterface.py", line 139, in run_simple
    run(app=web, host=host, port=port, quiet=True)
  File "/opt/share/pyload/module/lib/bottle.py", line 3137, in run
    server.run(app)
  File "/opt/share/pyload/module/lib/bottle.py", line 2789, in run
    srv = make_server(self.host, self.port, app, server_cls, handler_cls)
  File "/opt/lib/python2.7/wsgiref/simple_server.py", line 151, in make_server
  File "/opt/lib/python2.7/SocketServer.py", line 414, in __init__
  File "/opt/lib/python2.7/socket.py", line 191, in __init__
error: [Errno 97] Address family not supported by protocol

07.11.2023 05:08:35 INFO      Activating Accounts...
07.11.2023 05:08:35 INFO      Activating Plugins...
07.11.2023 05:08:35 WARNING   ADDON TORRENT: torrents / magnets are not associated with any plugin
07.11.2023 05:08:35 INFO      ADDON UpdateManager: pyLoad is up to date!
07.11.2023 05:08:38 INFO      ADDON XFileSharing: Auto-discover new hosters
07.11.2023 05:08:38 INFO      ADDON XFileSharing: Auto-discover new crypters
07.11.2023 05:08:38 INFO      pyLoad is up and running
07.11.2023 05:08:39 INFO      ADDON UpdateManager: All plugins are up to date!
07.11.2023 05:08:44 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666

thanks for your help

**Comment by geronimoronin** [comment]
after reinstall Entware and Pyload pyload_0.4.20-1_armv7-3.2.ipk, I get a new message 

"root@R7800:~# pyload --configdir=/opt/var/pyload
  File "/opt/bin/pyload", line 100
    print "pyLoad", CURRENT_VERSION
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?"

**Comment by GammaC0de** [comment]
I would try to delete the pyload.conf file and restart pyload so it would use the default values, maybe that would solve your issue.

**Comment by geronimoronin** [comment]
Hi GammaC0de ,  the file  pyload.conf   is not available because the first configuration does not start at all due to errors

root@R7800:~# pyload --configdir=/opt/var/pyload
  File "/opt/bin/pyload", line 100
    print "pyLoad", CURRENT_VERSION
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by geronimoronin** [comment]
There seem to be compatibility issues between Python 2.7 and 3.11, this ist the current Entware http://bin.entware.net/armv7sf-k3.2/. 
and this was the Old pkg.entware.net/binaries/armv7 , 
So with the old Entware the Pyload works, but as soon as I update it to 0.4.20 then I get the error messages
Exception in thread Thread-6:
Traceback (most recent call last):
File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
File "/opt/share/pyload/module/web/ServerThread.py", line 78, in run
self.start_builtin()
File "/opt/share/pyload/module/web/ServerThread.py", line 85, in start_builtin
webinterface.run_simple(host=self.host, port=self.port)
File "/opt/share/pyload/module/web/webinterface.py", line 139, in run_simple
run(app=web, host=host, port=port, quiet=True)
File "/opt/share/pyload/module/lib/bottle.py", line 3137, in run
server.run(app)
File "/opt/share/pyload/module/lib/bottle.py", line 2789, in run
srv = make_server(self.host, self.port, app, server_cls, handler_cls)
File "/opt/lib/python2.7/wsgiref/simple_server.py", line 151, in make_server
File "/opt/lib/python2.7/SocketServer.py", line 414, in init
File "/opt/lib/python2.7/socket.py", line 191, in init
error: [Errno 97] Address family not supported by protocol

and with then new Entware i get this error
root@R7800:/opt/share/pyload# python pyLoadCore.py -s
File "/opt/share/pyload/pyLoadCore.py", line 100
print "pyLoad", CURRENT_VERSION
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by geronimoronin** [comment]
Problem Solved , The IP address must be assigned permanently, 0.0.0.0 as default does not work. then the message like 

Traceback (most recent call last):
File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
File "/opt/share/pyload/module/web/ServerThread.py", line 78, in run
self.start_builtin()
File "/opt/share/pyload/module/web/ServerThread.py", line 85, in start_builtin
webinterface.run_simple(host=self.host, port=self.port)
File "/opt/share/pyload/module/web/webinterface.py", line 139, in run_simple
run(app=web, host=host, port=port, quiet=True)
File "/opt/share/pyload/module/lib/bottle.py", line 3137, in run
server.run(app)
File "/opt/share/pyload/module/lib/bottle.py", line 2789, in run
srv = make_server(self.host, self.port, app, server_cls, handler_cls)
File "/opt/lib/python2.7/wsgiref/simple_server.py", line 151, in make_server
File "/opt/lib/python2.7/SocketServer.py", line 414, in init
File "/opt/lib/python2.7/socket.py", line 191, in init
error: [Errno 97] Address family not supported by protocol

**Comment by GammaC0de** [comment]
If you are using python 3 then you should use pyload v0.5 https://pypi.org/project/pyload-ng/

**Comment by geronimoronin** [comment]
> If you are using python 3 then you should use pyload v0.5 https://github.com/pyload/pyload#quick-start
I tried that too but I keep getting error messages when building pip

**Comment by geronimoronin** [comment]
> If you are using python 3 then you should use pyload v0.5 https://github.com/pyload/pyload#quick-start

i get this error if i try to install v0.5

 error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [113 lines of output]
      Collecting setuptools>=61.0.0
        Obtaining dependency information for setuptools>=61.0.0 from https://files.pythonhosted.org/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl.metadata
        Using cached setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/fa/7f/4c07234086edbce4a0a446209dc0cb08a19bb206a3ea53b2f56a403f983b/wheel-0.41.3-py3-none-any.whl.metadata
        Using cached wheel-0.41.3-py3-none-any.whl.metadata (2.2 kB)
      Collecting cffi>=1.12
        Using cached cffi-1.16.0.tar.gz (512 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting setuptools-rust>=0.11.4
        Obtaining dependency information for setuptools-rust>=0.11.4 from https://files.pythonhosted.org/packages/e0/34/d88a7ceb193fbcee6c8992d1b1e33ed20361027e07fea1676efc45ec7a43/setuptools_rust-1.8.1-py3-none-any.whl.metadata
        Using cached setuptools_rust-1.8.1-py3-none-any.whl.metadata (9.4 kB)
      Collecting pycparser (from cffi>=1.12)
        Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
      Collecting semantic-version<3,>=2.8.2 (from setuptools-rust>=0.11.4)
        Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
      Using cached setuptools-68.2.2-py3-none-any.whl (807 kB)
      Using cached wheel-0.41.3-py3-none-any.whl (65 kB)
      Using cached setuptools_rust-1.8.1-py3-none-any.whl (26 kB)
      Building wheels for collected packages: cffi
        Building wheel for cffi (pyproject.toml): started
        Building wheel for cffi (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for cffi (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [73 lines of output]
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'libffi' found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'libffi' found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'libffi' found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'libffi' found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'libffi' found
            /opt/tmp/pip-build-env-2364md0x/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
            !!

                    ********************************************************************************
                    The license_file parameter is deprecated, use license_files instead.

                    This deprecation is overdue, please update your project and remove deprecated
                    calls to avoid build errors in the future.

                    See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                    ********************************************************************************

            !!
              parsed = self.parsers.get(option_name, lambda x: x)(value)
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-armv7l-cpython-311
            creating build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/__init__.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/_imp_emulation.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/_shimmed_dist_utils.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/api.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/backend_ctypes.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/cffi_opcode.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/commontypes.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/cparser.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/error.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/ffiplatform.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/lock.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/model.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/pkgconfig.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/recompiler.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/setuptools_ext.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/vengine_cpy.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/vengine_gen.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/verifier.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/_cffi_include.h -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/parse_c_type.h -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/_embedding.h -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/_cffi_errors.h -> build/lib.linux-armv7l-cpython-311/cffi
            running build_ext
            building '_cffi_backend' extension
            creating build/temp.linux-armv7l-cpython-311
            creating build/temp.linux-armv7l-cpython-311/src
            creating build/temp.linux-armv7l-cpython-311/src/c
            gcc -DNDEBUG -g -fwrapv -O3 -Wall -O2 -pipe -mtune=cortex-a9 -fno-caller-saves -fhonour-copts -mfloat-abi=soft -pthread -O2 -pipe -mtune=cortex-a9 -fno-caller-saves -fhonour-copts -mfloat-abi=soft -pthread -I/opt/usr/include -I/opt/include -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/opt/include/python3.11 -c src/c/_cffi_backend.c -o build/temp.linux-armv7l-cpython-311/src/c/_cffi_backend.o
            src/c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory
             #include <Python.h>
                      ^~~~~~~~~~
            compilation terminated.
            error: command '/opt/bin/gcc' failed with exit code 1
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cffi
      Failed to build cffi
      ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by GammaC0de** [comment]
You should install python3-dev Entware package

**Comment by geronimoronin** [comment]
> You should install python3-dev Entware package

yes after install i get this error


root@R7800:~# pip install --pre pyload-ng[all]
Collecting pyload-ng[all]
  Using cached pyload_ng-0.5.0b3.dev74-py3-none-any.whl.metadata (14 kB)
Collecting Cheroot~=8.4 (from pyload-ng[all])
  Using cached cheroot-8.6.0-py2.py3-none-any.whl (104 kB)
Collecting Flask-Babel~=1.0 (from pyload-ng[all])
  Using cached Flask_Babel-1.0.0-py3-none-any.whl (9.5 kB)
Collecting Flask-Caching~=1.9 (from pyload-ng[all])
  Using cached Flask_Caching-1.11.1-py3-none-any.whl (29 kB)
Collecting Flask-Compress~=1.8 (from pyload-ng[all])
  Using cached Flask_Compress-1.14-py3-none-any.whl.metadata (7.8 kB)
Collecting Flask-Themes2~=1.0 (from pyload-ng[all])
  Using cached Flask-Themes2-1.0.0.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
Collecting bitmath~=1.3 (from pyload-ng[all])
  Using cached bitmath-1.3.3.1.tar.gz (88 kB)
  Preparing metadata (setup.py) ... done
Collecting filetype~=1.0 (from pyload-ng[all])
  Using cached filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Collecting Js2Py~=0.7 (from pyload-ng[all])
  Using cached Js2Py-0.74-py3-none-any.whl (1.0 MB)
Requirement already satisfied: pycurl~=7.43 in /opt/lib/python3.11/site-packages (from pyload-ng[all]) (7.45.2)
Requirement already satisfied: certifi in /opt/lib/python3.11/site-packages (from pyload-ng[all]) (2023.7.22)
Collecting semver~=2.10 (from pyload-ng[all])
  Using cached semver-2.13.0-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: setuptools>=38.3 in /opt/lib/python3.11/site-packages (from pyload-ng[all]) (68.0.0)
Collecting cryptography>=35.0.0 (from pyload-ng[all])
  Using cached cryptography-41.0.5.tar.gz (630 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [109 lines of output]
      Collecting setuptools>=61.0.0
        Using cached setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Using cached wheel-0.41.3-py3-none-any.whl.metadata (2.2 kB)
      Collecting cffi>=1.12
        Using cached cffi-1.16.0.tar.gz (512 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting setuptools-rust>=0.11.4
        Using cached setuptools_rust-1.8.1-py3-none-any.whl.metadata (9.4 kB)
      Collecting pycparser (from cffi>=1.12)
        Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
      Collecting semantic-version<3,>=2.8.2 (from setuptools-rust>=0.11.4)
        Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
      Using cached setuptools-68.2.2-py3-none-any.whl (807 kB)
      Using cached wheel-0.41.3-py3-none-any.whl (65 kB)
      Using cached setuptools_rust-1.8.1-py3-none-any.whl (26 kB)
      Building wheels for collected packages: cffi
        Building wheel for cffi (pyproject.toml): started
        Building wheel for cffi (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for cffi (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [72 lines of output]
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'libffi' found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'libffi' found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'libffi' found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'libffi' found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'libffi' found
            /opt/tmp/pip-build-env-p1_vh6tz/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated conf                                                                                                                                                                                                                     ig in `setup.cfg`
            !!

                    ********************************************************************************
                    The license_file parameter is deprecated, use license_files instead.

                    This deprecation is overdue, please update your project and remove deprecated
                    calls to avoid build errors in the future.

                    See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                    ********************************************************************************

            !!
              parsed = self.parsers.get(option_name, lambda x: x)(value)
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-armv7l-cpython-311
            creating build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/__init__.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/_imp_emulation.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/_shimmed_dist_utils.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/api.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/backend_ctypes.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/cffi_opcode.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/commontypes.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/cparser.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/error.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/ffiplatform.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/lock.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/model.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/pkgconfig.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/recompiler.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/setuptools_ext.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/vengine_cpy.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/vengine_gen.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/verifier.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/_cffi_include.h -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/parse_c_type.h -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/_embedding.h -> build/lib.linux-armv7l-cpython-311/cffi
            copying src/cffi/_cffi_errors.h -> build/lib.linux-armv7l-cpython-311/cffi
            running build_ext
            building '_cffi_backend' extension
            creating build/temp.linux-armv7l-cpython-311
            creating build/temp.linux-armv7l-cpython-311/src
            creating build/temp.linux-armv7l-cpython-311/src/c
            gcc -DNDEBUG -g -fwrapv -O3 -Wall -O2 -pipe -mtune=cortex-a9 -fno-caller-saves -fhonour-copts -mfloat-abi=soft -pthread -O2 -pipe -mtune=c                                                                                                                                                                                                                     ortex-a9 -fno-caller-saves -fhonour-copts -mfloat-abi=soft -pthread -I/opt/usr/include -I/opt/include -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC                                                                                                                                                                                                                     _SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/opt/include/python3.11 -c src/c/_cffi_backend.c -o build/temp.linux-armv7l-cpython-311/src/c/                                                                                                                                                                                                                     _cffi_backend.o
            gcc -shared -Wl,--dynamic-linker=/opt/lib/ld-linux.so.3 -Wl,-rpath=/opt/lib -L/opt/usr/lib -L/opt/lib -fuse-ld=bfd -L/opt/lib -Wl,--dynami                                                                                                                                                                                                                     c-linker=/opt/lib/ld-linux.so.3 -Wl,-rpath=/opt/lib -L/opt/usr/lib -L/opt/lib -fuse-ld=bfd -L/opt/lib build/temp.linux-armv7l-cpython-311/src/c/_cffi_                                                                                                                                                                                                                     backend.o -L/opt/lib -lffi -o build/lib.linux-armv7l-cpython-311/_cffi_backend.cpython-311.so
            /opt/bin/ld.bfd: cannot find -lffi: No such file or directory
            collect2: error: ld returned 1 exit status
            error: command '/opt/bin/gcc' failed with exit code 1
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cffi
      Failed to build cffi
      ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by GammaC0de** [comment]
python3-cffi

**Comment by geronimoronin** [comment]
is also

> python3-cffi

root@R7800:~# opkg install python3-cffi
Package python3-cffi (1.15.1-1) installed in root is up to date.
root@R7800:~#

**Comment by GammaC0de** [comment]
Try python3-cryptography

**Comment by geronimoronin** [comment]
is also installed 

 opkg install  python3-cryptography
Package python3-cryptography (3.4.8-3a) installed in root is up to date.

**Comment by GammaC0de** [comment]
libffi?

**Comment by geronimoronin** [comment]
> libffi?

which packages have to be installed to run pyload 0.5 ?
python3
python3-cryptography
python3-cffi
python3-pip
libffi
curl
python3-cffi
python3-curl
python3-dev
python3-pillow

**Comment by GammaC0de** [comment]
>which packages have to be installed to run pyload 0.5

Don't know, I do not use Entware.

**Comment by geronimoronin** [comment]
And for Linux?

**Comment by GammaC0de** [comment]
> And for Linux?

pip should have take care for all the dependencies.
https://github.com/pyload/pyload#quick-start
