### ISSUE TITLE
Failed Archive extraction is recognised, but nothing is done about it

### ISSUE THREAD

**Issue by mihawk90** [pyload/pyload#4393]
### Description
When pyload-ng encounters a Bad Archive, due to a broken download or whatever, it logs this, but does nothing about it. Ideally this should restart the download of said archives, or at least mark them as a failed extraction in the package list.*
However, as it stands the files remain as finished (or skipped for mirrored links) in the Package list and in the files, so you'd never know unless you manually check either the log or the files section.

*Note this should probably also have a maximum number of retries so it doesn't keep downloading the same files over and over in case the file is actually corrupted on the hoster side.

### Debug log
Just an excerpt of the relevant section:

```
...
[2023-11-15 19:27:42]  INFO                pyload  ADDON ExtractArchive: DLvK-1080-01x02.part1.rar | Extracting finished
[2023-11-15 19:27:42]  DEBUG               pyload  ADDON ExtractArchive: Extracted files: ['/mnt/media/_unsorted_stuff/_pyload-extracted/Die.Legende.von.Korra.S01/Die.Legende.von.Korra.S01E02.Wie.ein.Blatt.im.Wind.German.DL.1080p.AmazonHD.h264-GDR.mkv']
[2023-11-15 19:27:42]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `archive_extracted`
[2023-11-15 19:27:42]  INFO                pyload  ADDON ExtractArchive: DLvK-1080-01x03.part1.rar | Extract to: /mnt/media/_unsorted_stuff/_pyload-extracted/Die.Legende.von.Korra.S01
[2023-11-15 19:27:42]  DEBUG               pyload  ADDON ExtractArchive: Password: None
[2023-11-15 19:27:42]  DEBUG               pyload  ADDON ExtractArchive: Verifying using password: None
[2023-11-15 19:27:42]  DEBUG               pyload  EXTRACTOR UnRar: EXECUTE unrar l -scf -o- -or -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -c- -p- -v /downloads/Die.Legende.von.Korra.S01/DLvK-1080-01x03.part1.rar
[2023-11-15 19:27:42]  DEBUG               pyload  EXTRACTOR UnRar: EXECUTE unrar l -scf -o- -or -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -c- -p- -v /downloads/Die.Legende.von.Korra.S01/DLvK-1080-01x03.part1.rar
[2023-11-15 19:27:42]  INFO                pyload  ADDON ExtractArchive: DLvK-1080-01x03.part1.rar | Password protected
[2023-11-15 19:27:42]  DEBUG               pyload  ADDON ExtractArchive: Password was wrong
[2023-11-15 19:27:42]  DEBUG               pyload  ADDON ExtractArchive: Verifying using password: <password>
[2023-11-15 19:27:42]  DEBUG               pyload  EXTRACTOR UnRar: EXECUTE unrar l -scf -o- -or -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -c- -p<password> -v /downloads/Die.Legende.von.Korra.S01/DLvK-1080-01x03.part1.rar
[2023-11-15 19:27:42]  DEBUG               pyload  ADDON ExtractArchive: Password Correct
[2023-11-15 19:27:42]  DEBUG               pyload  ADDON ExtractArchive: Extracting using password:<password>
[2023-11-15 19:27:42]  DEBUG               pyload  EXTRACTOR UnRar: EXECUTE unrar x -scf -o- -or -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -c- -p<password> /downloads/Die.Legende.von.Korra.S01/DLvK-1080-01x03.part1.rar /mnt/media/_unsorted_stuff/_pyload-extracted/Die.Legende.von.Korra.S01
[2023-11-15 19:27:53]  ERROR               pyload  ADDON ExtractArchive: DLvK-1080-01x03.part1.rar | Archive error | ERROR: Bad archive /downloads/Die.Legende.von.Korra.S01/DLvK-1080-01x03.part3.rar
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/addons/ExtractArchive.py", line 501, in _extract
    archive.extract(password)
  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/extractors/UnRar.py", line 213, in extract
    raise ArchiveError(err)
pyload.plugins.base.extractor.ArchiveError: ERROR: Bad archive /downloads/Die.Legende.von.Korra.S01/DLvK-1080-01x03.part3.rar
[2023-11-15 19:27:53]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `archive_extract_failed`
[2023-11-15 19:27:53]  ERROR               pyload  ADDON ExtractArchive: DLvK-1080-01x03.part1.rar | Extract failed
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/addons/ExtractArchive.py", line 330, in extract
    new_files = self._extract(
                ^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/addons/ExtractArchive.py", line 568, in _extract
    raise Exception(self._("Extract failed"))
Exception: Extract failed
[2023-11-15 19:27:53]  INFO                pyload  ADDON ExtractArchive: DLvK-1080-01x04.part1.rar | Extract to: /mnt/media/_unsorted_stuff/_pyload-extracted/Die.Legende.von.Korra.S01
...
```

### Screenshots
![image](https://github.com/pyload/pyload/assets/556162/556f9a01-eae8-40e8-b869-c5447c1a4f13)
Note both are skipped in this case, it's because my password file wasn't accessible so the first extraction attempt failed. I restarted the package and it skipped over every link, then extracted. I don't think this should have any bearing on the behaviour though.

### Additional references
From what I can tell from the relevant code:
https://github.com/pyload/pyload/blob/a65a968696f85c52c1f835d6d5dc22fd52fca12a/src/pyload/plugins/addons/ExtractArchive.py#L560-L568

It seems this is really just rudimentary error handling (and that's fine), hence why I categorised it as a feature request rather then a bug report.

Also note, I know why this file is bad, so that's not the point here. It downloaded some HTML file rather then an actual archive, but I haven't figured out yet what happened here so I had no reason to report it:
```
$ file DLvK-1080-01x03.part3.rar 
DLvK-1080-01x03.part3.rar: HTML document, ASCII text, with CRLF, LF line terminators
```

**Comment by milahu** [comment]
> Ideally this should restart the download of said archives, or at least mark them as a failed extraction in the package list.

i would prefer "mark them as a failed extraction"

the user can set a wrong password (see also #4525)
which causes the debug message
`addon ExtractArchive: Password was wrong`

optionally, pyload should stop extracting a package after the first extraction error
assuming that all archive files have the same password
and assuming that all archive files are ok (not corrupt)

corrupt files could be detected
when the extraction works at the start
but breaks later somewhere in the middle of the archive file
