### ISSUE TITLE
OneFichier plugin: downloads fail for premium account (403 error)

### ISSUE THREAD

**Issue by yourlord5** [pyload/pyload#4399]
### Description

Hi and thanks for the great work on this project!

When trying to download files from 1fichier.com in pyload, nothing starts, directly raising a "Bad server response: 403 Forbidden".

For the record:
- Pyload is installed on 0.4.20 version (python 2.7).
- I have a premium 1fichier account
- I can download files through my web browser (using premium account)
- I can download files through pyload without premium account

### Debug log

```
1003 | 23.11.2023 08:05:11 | DEBUG | ACCOUNT OneFichierCom: Reached login timeout for user `you*******`
-- | -- | -- | --
1004 | 23.11.2023 08:05:11 | INFO | ACCOUNT OneFichierCom: Login user `you*******`...
1005 | 23.11.2023 08:05:11 | DEBUG | ACCOUNT OneFichierCom: LOAD URL https://1fichier.com/login.pl?lg=en \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
1006 | 23.11.2023 08:05:12 | DEBUG | ACCOUNT OneFichierCom: LOAD URL https://1fichier.com/login.pl?lg=en \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={'purge': 'off', 'mail': 'you*******', 'lt': 'on', 'valider': 'OK', 'pass': '**********'} \| ref=https://1fichier.com/login.pl?lg=en \| just_header=False
1007 | 23.11.2023 08:05:12 | INFO | ACCOUNT OneFichierCom: Grabbing account info for user `you*******`...
1008 | 23.11.2023 08:05:12 | DEBUG | ACCOUNT OneFichierCom: LOAD URL https://1fichier.com/console/abo.pl \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
1009 | 23.11.2023 08:05:12 | DEBUG | ACCOUNT OneFichierCom: Expire date: 2023-12-13
1010 | 23.11.2023 08:05:12 | DEBUG | ACCOUNT OneFichierCom: Account info for user `you*******`: {'login': {'timestamp': 1700726711.917709, 'password': '**********', 'stats': [1, 0], 'valid': True}, 'data': {'validuntil': 1702425600.0, 'plugin': , 'trafficleft': -1, 'maxtraffic': None, 'premium': True, 'login': 'you*******', 'type': 'OneFichierCom', 'options': {'limitDL': ['0']}}}
1011 | 23.11.2023 08:05:40 | DEBUG | Redirected import module.plugins.hoster.OneFichierCom -> userplugins.hoster.OneFichierCom
1012 | 23.11.2023 08:05:40 | INFO | Download starts: 4814702
1013 | 23.11.2023 08:05:40 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
1014 | 23.11.2023 08:05:40 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
1015 | 23.11.2023 08:05:40 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
1016 | 23.11.2023 08:05:40 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
1017 | 23.11.2023 08:05:40 | DEBUG | HOSTER OneFichierCom[4]: Plugin version: 1.19
1018 | 23.11.2023 08:05:40 | DEBUG | HOSTER OneFichierCom[4]: Plugin status: testing
1019 | 23.11.2023 08:05:40 | WARNING | HOSTER OneFichierCom[4]: Plugin may be unstable
1020 | 23.11.2023 08:05:40 | INFO | ACCOUNT OneFichierCom: Grabbing account info for user `you*******`...
1021 | 23.11.2023 08:05:40 | DEBUG | ACCOUNT OneFichierCom: LOAD URL https://1fichier.com/console/abo.pl \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
1022 | 23.11.2023 08:05:40 | DEBUG | ACCOUNT OneFichierCom: Expire date: 2023-12-13
1023 | 23.11.2023 08:05:40 | DEBUG | ACCOUNT OneFichierCom: Account info for user `you*******`: {'login': {'timestamp': 1700726711.917709, 'password': '**********', 'stats': [1, 0], 'valid': True}, 'data': {'validuntil': 1702425600.0, 'plugin': , 'trafficleft': -1, 'maxtraffic': None, 'premium': True, 'login': 'you*******', 'type': 'OneFichierCom', 'options': {'limitDL': ['0']}}}
1024 | 23.11.2023 08:05:40 | DEBUG | ACCOUNT OneFichierCom: Using account you*******
1025 | 23.11.2023 08:05:40 | INFO | HOSTER OneFichierCom[4]: Processing url: https://1fichier.com/?rpzp3aedd6laxyfe0pv6
1026 | 23.11.2023 08:05:40 | INFO | HOSTER OneFichierCom[4]: Looking for direct download link...
1027 | 23.11.2023 08:05:40 | DEBUG | HOSTER OneFichierCom[4]: LOAD URL https://1fichier.com/?rpzp3aedd6laxyfe0pv6 \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
1028 | 23.11.2023 08:05:41 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
1029 | 23.11.2023 08:05:41 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
1030 | 23.11.2023 08:05:41 | WARNING | Download failed: rpzp3aedd6laxyfe0pv6 \| Bad server response: 403 Forbidden
1031 | 23.11.2023 08:05:41 | INFO | Debug Report written to debug_OneFichierCom_23-11-2023_08-05-41.zip
1032 | 23.11.2023 08:05:41 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: rpzp3aedd6laxyfe0pv6 (pid:4)
1033 | 23.11.2023 08:05:41 | INFO | ADDON UnSkipOnFail: No duplicates found
1034 | 23.11.2023 08:05:41 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
1035 | 23.11.2023 08:05:41 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
1036 | 23.11.2023 08:05:41 | DEBUG | All downloads processed
```

### Additional references

Might be related to https://github.com/pyload/pyload/issues/4314 
but i have the 0.25 version of  OneFichierCom.py plugin account

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by yourlord5** [comment]
Thanks a lot, I sent it

**Comment by GammaC0de** [comment]
I tried to download the above file with the account and it worked with no issues 🤔

Does it happen to you every time?

**Comment by yourlord5** [comment]
Hello, 

thanks for your time. 
I tried again just right now and the problem is still there. every time. Sometimes it switch whith free account to download. 
here is the log for example : 

```
26.11.2023 07:18:44 | INFO | Added package zerzerzezeze containing 1 links
-- | -- | --
4 | 26.11.2023 07:18:45 | INFO | Download starts: https://1fichier.com/?z7evjfbjfrbw0msv6bpy&af=4814702
5 | 26.11.2023 07:18:45 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
6 | 26.11.2023 07:18:45 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
7 | 26.11.2023 07:18:45 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
8 | 26.11.2023 07:18:45 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
9 | 26.11.2023 07:18:45 | DEBUG | HOSTER OneFichierCom[5]: Plugin version: 1.19
10 | 26.11.2023 07:18:45 | DEBUG | HOSTER OneFichierCom[5]: Plugin status: testing
11 | 26.11.2023 07:18:45 | WARNING | HOSTER OneFichierCom[5]: Plugin may be unstable
12 | 26.11.2023 07:18:45 | DEBUG | ACCOUNT OneFichierCom: Reached login timeout for user `you*******`
13 | 26.11.2023 07:18:45 | INFO | ACCOUNT OneFichierCom: Relogin user `you*******`...
14 | 26.11.2023 07:18:45 | DEBUG | ACCOUNT OneFichierCom: LOAD URL https://1fichier.com/login.pl?lg=en \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
15 | 26.11.2023 07:18:45 | DEBUG | ACCOUNT OneFichierCom: LOAD URL https://1fichier.com/login.pl?lg=en \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={'purge': 'off', 'mail': 'you*******', 'lt': 'on', 'valider': 'OK', 'pass': '**********'} \| ref=https://1fichier.com/login.pl?lg=en \| just_header=False
16 | 26.11.2023 07:18:46 | ERROR | ACCOUNT OneFichierCom: Could not login user `you*******` \| Login handshake has failed
17 | ? | ? | Traceback (most recent call last):
18 | ? | ? | File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
19 | ? | ? | self.__bootstrap_inner()
20 | ? | ? | File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
21 | ? | ? | self.run()
22 | ? | ? | File "/usr/share/pyload/module/PluginThread.py", line 187, in run
23 | ? | ? | pyfile.plugin.preprocessing(self)
24 | ? | ? | File "/root/.pyload/userplugins/internal/Base.py", line 290, in preprocessing
25 | ? | ? | return self._process(*args, **kwargs)
26 | ? | ? | File "/root/.pyload/userplugins/internal/Hoster.py", line 107, in _process
27 | ? | ? | self._setup()
28 | ? | ? | File "/root/.pyload/userplugins/internal/Base.py", line 144, in _setup
29 | ? | ? | self.load_account() # @TODO: Move to PluginThread in 0.4.10
30 | ? | ? | File "/root/.pyload/userplugins/internal/Hoster.py", line 99, in load_account
31 | ? | ? | Base.load_account(self)
32 | ? | ? | File "/root/.pyload/userplugins/internal/Base.py", line 178, in load_account
33 | ? | ? | self.account.choose()
34 | ? | ? | File "/root/.pyload/userplugins/internal/misc.py", line 234, in new
35 | ? | ? | return fn(*args, **kwargs)
36 | ? | ? | File "/root/.pyload/userplugins/internal/Account.py", line 421, in choose
37 | ? | ? | user = self.select()[0]
38 | ? | ? | File "/root/.pyload/userplugins/internal/misc.py", line 234, in new
39 | ? | ? | return fn(*args, **kwargs)
40 | ? | ? | File "/root/.pyload/userplugins/internal/Account.py", line 366, in select
41 | ? | ? | info = self.accounts[user]["plugin"].get_info()
42 | ? | ? | File "/root/.pyload/userplugins/internal/Account.py", line 204, in get_info
43 | ? | ? | if self.relogin():
44 | ? | ? | File "/root/.pyload/userplugins/internal/Account.py", line 183, in relogin
45 | ? | ? | return self.login()
46 | ? | ? | File "/root/.pyload/userplugins/internal/Account.py", line 115, in login
47 | ? | ? | self.info['data'])
48 | ? | ? | File "/root/.pyload/userplugins/accounts/OneFichierCom.py", line 69, in signin
49 | ? | ? | self.fail_login()
50 | ? | ? | File "/root/.pyload/userplugins/internal/Account.py", line 455, in fail_login
51 | ? | ? | return self.fail(msg)
52 | ? | ? | File "/root/.pyload/userplugins/internal/Plugin.py", line 191, in fail
53 | ? | ? | raise Fail(decode(msg)) # @TODO: Remove `decode` in 0.4.10
54 | ? | ? | Fail: Login handshake has failed
55 | ? | ? |  
56 | 26.11.2023 07:18:46 | INFO | HOSTER OneFichierCom[5]: Processing url: https://1fichier.com/?z7evjfbjfrbw0msv6bpy&af=4814702
57 | 26.11.2023 07:18:46 | INFO | HOSTER OneFichierCom[5]: Looking for direct download link...
58 | 26.11.2023 07:18:46 | DEBUG | HOSTER OneFichierCom[5]: LOAD URL https://1fichier.com/?z7evjfbjfrbw0msv6bpy \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
59 | 26.11.2023 07:18:46 | INFO | HOSTER OneFichierCom[5]: Direct download link not found
60 | 26.11.2023 07:18:46 | DEBUG | HOSTER OneFichierCom[5]: LOAD URL https://1fichier.com/?z7evjfbjfrbw0msv6bpy \| redirect=True \| cookies=[('1fichier.com', 'LG', 'en')] \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
61 | 26.11.2023 07:18:47 | INFO | HOSTER OneFichierCom[5]: Checking for link errors...
62 | 26.11.2023 07:18:47 | INFO | HOSTER OneFichierCom[5]: No errors found
63 | 26.11.2023 07:18:47 | INFO | HOSTER OneFichierCom[5]: Grabbing link info...
64 | 26.11.2023 07:18:47 | DEBUG | HOSTER OneFichierCom[5]: Link info: {'status': 2, 'hash': {}, 'name': u'Doctor.Who.60th.Anniversary.Specials.S01E01.VOSTFR.WEBRip.x264-Wawacity.fit.mp4', 'url': u'https://1fichier.com/?z7evjfbjfrbw0msv6bpy', 'pattern': {'HOST': u'1fichier.com', 'U': u'MB', 'ID1': None, 'ID2': u'z7evjfbjfrbw0msv6bpy', 'S': u'418.61', 'N': u'Doctor.Who.60th.Anniversary.Specials.S01E01.VOSTFR.WEBRip.x264-Wawacity.fit.mp4'}, 'size': 438944399}
65 | 26.11.2023 07:18:47 | DEBUG | HOSTER OneFichierCom[5]: Previous link info: {}
66 | 26.11.2023 07:18:47 | INFO | HOSTER OneFichierCom[5]: Link name: Doctor.Who.60th.Anniversary.Specials.S01E01.VOSTFR.WEBRip.x264-Wawacity.fit.mp4
67 | 26.11.2023 07:18:47 | INFO | HOSTER OneFichierCom[5]: Link size: 418.61 MiB (438944399 bytes)
68 | 26.11.2023 07:18:47 | INFO | HOSTER OneFichierCom[5]: Link status: en ligne
69 | 26.11.2023 07:18:47 | INFO | HOSTER OneFichierCom[5]: Processing as free download...
70 | 26.11.2023 07:18:47 | DEBUG | HOSTER OneFichierCom[5]: LOAD URL https://1fichier.com/?z7evjfbjfrbw0msv6bpy \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={u'dl_no_ssl': 'on', u'adz': u'507.495963390083', u'dlinline': ''} \| ref=True \| just_header=False
71 | 26.11.2023 07:18:47 | INFO | HOSTER OneFichierCom[5]: Checking for link errors...
72 | 26.11.2023 07:18:47 | INFO | HOSTER OneFichierCom[5]: No errors found
73 | 26.11.2023 07:18:47 | INFO | HOSTER OneFichierCom[5]: Downloading file...
74 | 26.11.2023 07:18:47 | DEBUG | HOSTER OneFichierCom[5]: DOWNLOAD URL http://a-3.1fichier.com/c708703756 \| cookies=True \| resume=None \| get={} \| disposition=True \| chunks=None \| post={} \| ref=True
75 | 26.11.2023 07:18:47 | DEBUG | Content-Disposition: Doctor.Who.60th.Anniversary.Specials.S01E01.VOSTFR.WEBRip.x264-Wawacity.fit.mp4
```

Is there another file i don't have in the right version ?

**Comment by yourlord5** [comment]
Maybe the site block me after many try...
Can i test in command line to check ? what's the right command line in bash with curl ?

**Comment by yourlord5** [comment]
another test and switch to free account. 
My account is detected and valid. don't understand


```
245 | 26.11.2023 08:04:56 | INFO | Added package tuioeoireokjfd containing 1 links
-- | -- | -- | --
246 | 26.11.2023 08:04:56 | INFO | Download starts: https://1fichier.com/?ktks5xvn56pv3qu1k6v9&af=3601079
247 | 26.11.2023 08:04:56 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
248 | 26.11.2023 08:04:56 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
249 | 26.11.2023 08:04:56 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
250 | 26.11.2023 08:04:56 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
251 | 26.11.2023 08:04:56 | DEBUG | HOSTER OneFichierCom[6]: Plugin version: 1.19
252 | 26.11.2023 08:04:56 | DEBUG | HOSTER OneFichierCom[6]: Plugin status: testing
253 | 26.11.2023 08:04:56 | WARNING | HOSTER OneFichierCom[6]: Plugin may be unstable
254 | 26.11.2023 08:04:56 | INFO | ACCOUNT OneFichierCom: Grabbing account info for user `you*******`...
255 | 26.11.2023 08:04:56 | DEBUG | ACCOUNT OneFichierCom: LOAD URL https://1fichier.com/console/abo.pl \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
256 | 26.11.2023 08:04:57 | DEBUG | ACCOUNT OneFichierCom: Account info for user `you*******`: {'login': {'timestamp': 1700984658.478009, 'password': '**********', 'stats': [1, 1700984708.142387], 'valid': True}, 'data': {'validuntil': None, 'plugin': , 'trafficleft': -1, 'maxtraffic': None, 'premium': False, 'login': 'you*******', 'type': 'OneFichierCom', 'options': {'limitDL': ['0']}}}
257 | 26.11.2023 08:04:57 | DEBUG | ACCOUNT OneFichierCom: Using account you*******
258 | 26.11.2023 08:04:57 | INFO | HOSTER OneFichierCom[6]: Processing url: https://1fichier.com/?ktks5xvn56pv3qu1k6v9&af=3601079
259 | 26.11.2023 08:04:57 | INFO | HOSTER OneFichierCom[6]: Looking for direct download link...
260 | 26.11.2023 08:04:57 | DEBUG | HOSTER OneFichierCom[6]: LOAD URL https://1fichier.com/?ktks5xvn56pv3qu1k6v9 \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
261 | 26.11.2023 08:04:58 | INFO | HOSTER OneFichierCom[6]: Direct download link not found
262 | 26.11.2023 08:04:58 | DEBUG | HOSTER OneFichierCom[6]: LOAD URL https://1fichier.com/?ktks5xvn56pv3qu1k6v9 \| redirect=True \| cookies=[('1fichier.com', 'LG', 'en')] \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
263 | 26.11.2023 08:04:58 | INFO | HOSTER OneFichierCom[6]: Checking for link errors...
264 | 26.11.2023 08:04:58 | DEBUG | HOSTER OneFichierCom[6]: WAIT set to timestamp 1701055979.512362 \| Previous waitUntil: 0.000000
265 | 26.11.2023 08:04:58 | INFO | HOSTER OneFichierCom[6]: Waiting 19 hours, 28 minutes...
```
