### ISSUE TITLE
Can't login to alldebrid account

### ISSUE THREAD

**Issue by howards111** [pyload/pyload#4406]
### Description

```	2023-12-06 01:07:39	ERROR	pyload	ACCOUNT AlldebridCom: Could not load hoster list - invalid account, retry in 5 minutes
64	2023-12-06 01:12:39	ERROR	pyload	ACCOUNT AlldebridCom: Could not load hoster list - invalid account, retry in 5 minutes
65	2023-12-06 01:13:05	INFO	pyload	ACCOUNT AlldebridCom: Updating account info for user `how****`...
66	2023-12-06 01:13:05	INFO	pyload	ACCOUNT AlldebridCom: Relogin user `how****`...
67	2023-12-06 01:13:05	DEBUG	pyload	ACCOUNT AlldebridCom: LOAD URL https://api.alldebrid.com/v4/user | get={'apikey': '**********', 'agent': 'pyLoad', 'version': '0.5.0'} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
68	2023-12-06 01:13:05	ERROR	pyload	ACCOUNT AlldebridCom: username for alldebrid.com should be your alldebrid.com username
69	2023-12-06 01:13:05	ERROR	pyload	ACCOUNT AlldebridCom: Could not login user `how****` | Login handshake has failed
70	?	?	?	Traceback (most recent call last):
71	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/account.py", line 138, in login
72	?	?	?	    self.signin(self.user, self.info["login"]["password"], self.info["data"])
73	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/accounts/AlldebridCom.py", line 105, in signin
74	?	?	?	    self.fail_login()
75	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/account.py", line 498, in fail_login
76	?	?	?	    return self.fail(msg)
77	?	?	?	           ^^^^^^^^^^^^^^
78	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/plugin.py", line 154, in fail
79	?	?	?	    raise Fail(msg)
80	?	?	?	pyload.core.network.exceptions.Fail: Login handshake has failed
81	2023-12-06 01:13:08	ERROR	pyload	ACCOUNT AlldebridCom: Could not load hoster list - invalid account, deactivating
82	2023-12-06 01:13:08	INFO	pyload	ACCOUNT AlldebridCom: Reverting back to default hosters

```

### Screenshots

![image](https://github.com/pyload/pyload/assets/33992423/50ebe2cd-5dcd-4b34-8797-188432e14363)
![image](https://github.com/pyload/pyload/assets/33992423/73427403-816e-4a10-9d77-1fa89859972b)

**Comment by GammaC0de** [comment]
username for alldebrid.com should be your alldebrid.com username and the password should be the API token - use GetAlldebridTokenV4.py to get it: https://github.com/pyload/pyload/files/4489732/GetAlldebridTokenV4.zip

**Comment by GammaC0de** [comment]
> but my alldebrid account asked to link the device with the pyload app which it is on a seedbox

It does not matter where pyload is, you can run the python file from your PC, and fill the generated user/password on the seedbox.

**Comment by howards111** [comment]
Hi gammacode, 

i did followed the the procedure but still have i have some errors. i have attached couple of screenshots.
![blur 1](https://github.com/pyload/pyload/assets/33992423/67dfe11b-2068-4afd-8362-8a86b70fbb11)
![blur 2](https://github.com/pyload/pyload/assets/33992423/dc71c608-208c-44d1-9ad5-f17aa348d47f)
![pyload](https://github.com/pyload/pyload/assets/33992423/128a7cc3-c173-480e-8898-03d8d4f445af)

i have no ideas what the errors coming from

**Comment by GammaC0de** [comment]
The API token is correct,
You put the wrong username, it should be the same username as you use for alldebrid web site.

**Comment by howards111** [comment]
it works thank gamma code! Forgot to put capital letter at the start of the username

**Comment by GammaC0de** [comment]
👍
