### ISSUE TITLE
SkipRev error with Realdebrid

### ISSUE THREAD

**Issue by evilsh3ll** [pyload/pyload#4409]
### Description

I use the latest version of pyload from archlinux. SkipRev generates errors and makes download impossible.

### Debug log

The error in the gui (under the download link) is:
```failed super(type, obj): obj must be an instance or subtype of type 0.00 Bit RealdebridCom```
The errors in the logs are
```
11391	2023-12-11 10:05:38	DEBUG	pyload	Chunk 1 chunked with range 0-65190014
11392	2023-12-11 10:05:38	DEBUG	pyload	Chunk 2 chunked with range 65190014-130380028
11393	2023-12-11 10:05:38	DEBUG	pyload	Chunk 3 chunked with range 130380028-
11394	2023-12-11 10:05:40	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_processed`
11395	2023-12-11 10:05:40	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `package_processed`
11396	2023-12-11 10:05:40	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `package_failed`
11397	2023-12-11 10:05:40	INFO	pyload	Download aborted: 2023.1080p.part16.rar
11398	2023-12-11 10:05:40	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
11399	2023-12-11 10:05:40	DEBUG	pyload	All downloads processed
11400	2023-12-11 10:05:56	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `package_deleted`
```

### Screenshots

![image](https://github.com/pyload/pyload/assets/63223659/8745878d-cfb4-49ba-86ee-fb1d3619940d)
![image](https://github.com/pyload/pyload/assets/63223659/79f9793b-9b2d-48bc-951d-cad23ae1d1d6)

### Additional references

none

**Comment by GammaC0de** [comment]
What is the version of the SkipRev plugin?
It seems that you are using an old version of the plugin.
Can you send more detailed log please?

**Comment by evilsh3ll** [comment]
This is the error log when I try to use **SkipRev**:
```
15919	2023-12-17 10:24:27	INFO	pyload	Download starts: oxv15y6nd0u7
15920	2023-12-17 10:24:27	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_preparing`
15921	2023-12-17 10:24:27	DEBUG	pyload	ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
15922	2023-12-17 10:24:27	DEBUG	pyload	ADDON UserAgentSwitcher: Setting maximum redirections to 10
15923	2023-12-17 10:24:27	DEBUG	pyload	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0`
15924	2023-12-17 10:24:27	WARNING	pyload	Download failed: oxv15y6nd0u7 | super(type, obj): obj must be an instance or subtype of type
15925	?	?	?	Traceback (most recent call last):
15926	?	?	?	  File "/usr/lib/python3.11/site-packages/pyload/core/threads/download_thread.py", line 55, in run
15927	?	?	?	    self.pyload.addon_manager.download_preparing(pyfile)
15928	?	?	?	  File "/usr/lib/python3.11/site-packages/pyload/core/utils/struct/lock.py", line 22, in wrapped
15929	?	?	?	    return func(self, *args, **kwargs)
15930	?	?	?	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
15931	?	?	?	  File "/usr/lib/python3.11/site-packages/pyload/core/managers/addon_manager.py", line 206, in download_preparing
15932	?	?	?	    plugin.download_preparing(pyfile)
15933	?	?	?	  File "/usr/lib/python3.11/site-packages/pyload/plugins/addons/SkipRev.py", line 44, in download_preparing
15934	?	?	?	    name = self._name(pyfile)
15935	?	?	?	           ^^^^^^^^^^^^^^^^^^
15936	?	?	?	  File "/usr/lib/python3.11/site-packages/pyload/plugins/addons/SkipRev.py", line 26, in _name
15937	?	?	?	    return pyfile.pluginclass.get_info(pyfile.url)["name"]
15938	?	?	?	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15939	?	?	?	  File "/usr/lib/python3.11/site-packages/pyload/plugins/base/multi_downloader.py", line 39, in get_info
15940	?	?	?	    return super(SimpleDownloader, self).get_info(url, html)
15941	?	?	?	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15942	?	?	?	TypeError: super(type, obj): obj must be an instance or subtype of type
15943	2023-12-17 10:24:27	INFO	pyload	Debug Report written to /tmp/pyLoad/debug_RealdebridCom_2023-12-17_10-24-27.zip
15944	2023-12-17 10:24:27	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_failed`
15945	2023-12-17 10:24:27	INFO	pyload	ADDON UnSkipOnFail: Looking for skipped duplicates of: oxv15y6nd0u7 (pid:67)
15946	2023-12-17 10:24:27	INFO	pyload	ADDON UnSkipOnFail: No duplicates found
15947	2023-12-17 10:24:32	DEBUG	pyload	Plugin unloaded: SkipRev
15948	2023-12-17 10:24:32	DEBUG	pyload	Removed callback False
```
I'm not sure where I can get the plugin version but I'm using **pyLoad 0.5.0** from archlinux AUR. 
Where I can read the plugin version?
Maybe the problem is that RealDebrid doesn't load the real name of the package before the download is started, for example in this log the name is "oxv15y6nd0u7" witout extension.
