### ISSUE TITLE
Filejoker.com issue: cannot identify image file

### ISSUE THREAD

**Issue by akfedux** [pyload/pyload#4410]
### Debug log

18	11.12.2023 12:27:52	DEBUG	Redirected import module.plugins.hoster.FilejokerNet -> userplugins.hoster.FilejokerNet
19	11.12.2023 12:27:52	DEBUG	Redirected import userplugins.internal.CaptchaService -> module.plugins.internal.CaptchaService
20	11.12.2023 12:27:52	DEBUG	Redirected import userplugins.captcha.ReCaptcha -> module.plugins.captcha.ReCaptcha
21	11.12.2023 12:27:53	DEBUG	Redirected import userplugins.internal.XFSHoster -> module.plugins.internal.XFSHoster
22	11.12.2023 12:27:53	DEBUG	Redirected import module.plugins.captcha.HCaptcha -> userplugins.captcha.HCaptcha
23	11.12.2023 12:27:53	INFO	Download starts: FileJoker.net Premium Account
24	11.12.2023 12:27:53	DEBUG	HOSTER FilejokerNet[3619]: Plugin version: 0.16
25	11.12.2023 12:27:53	DEBUG	HOSTER FilejokerNet[3619]: Plugin status: testing
26	11.12.2023 12:27:53	WARNING	HOSTER FilejokerNet[3619]: Plugin may be unstable
27	11.12.2023 12:27:53	DEBUG	Redirected import module.plugins.accounts.FilejokerNet -> userplugins.accounts.FilejokerNet
28	11.12.2023 12:27:53	DEBUG	Redirected import userplugins.internal.Account -> module.plugins.internal.Account
29	11.12.2023 12:27:53	INFO	HOSTER FilejokerNet[3619]: Processing url: https://filejoker.net/06odb4hckkja
30	11.12.2023 12:27:53	DEBUG	HOSTER FilejokerNet[3619]: LOAD URL https://filejoker.net/06odb4hckkja | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
31	11.12.2023 12:27:55	INFO	HOSTER FilejokerNet[3619]: Checking for link errors...
32	11.12.2023 12:27:55	INFO	HOSTER FilejokerNet[3619]: No errors found
33	11.12.2023 12:27:55	INFO	HOSTER FilejokerNet[3619]: Grabbing link info...
34	11.12.2023 12:27:56	DEBUG	HOSTER FilejokerNet[3619]: Link info: {'status': 2, 'hash': {}, 'name': u'FileJoker.net Premium Account', 'url': u'https://filejoker.net/06odb4hckkja', 'pattern': {'ID': u'06odb4hckkja', 'N': u'FileJoker.net Premium Account'}, 'size': 0}
35	11.12.2023 12:27:56	DEBUG	HOSTER FilejokerNet[3619]: Previous link info: {}
36	11.12.2023 12:27:56	INFO	HOSTER FilejokerNet[3619]: Link name: FileJoker.net Premium Account
37	11.12.2023 12:27:56	INFO	HOSTER FilejokerNet[3619]: Link size: N/D
38	11.12.2023 12:27:56	INFO	HOSTER FilejokerNet[3619]: Link status: online
39	11.12.2023 12:27:56	INFO	HOSTER FilejokerNet[3619]: Processing as free download...
40	11.12.2023 12:27:56	DEBUG	HOSTER FilejokerNet[3619]: Getting download link #1...
41	11.12.2023 12:27:56	INFO	HOSTER FilejokerNet[3619]: Checking for link errors...
42	11.12.2023 12:27:56	INFO	HOSTER FilejokerNet[3619]: No errors found
43	11.12.2023 12:27:57	DEBUG	HOSTER FilejokerNet[3619]: {u'method_free': u'1', u'referer': '', u'id': u'06odb4hckkja', u'fname': u'FileJoker.net Premium Account', u'op': u'download1'}
44	11.12.2023 12:27:57	DEBUG	HOSTER FilejokerNet[3619]: LOAD URL https://filejoker.net/06odb4hckkja | redirect=False | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'method_free': 'Free Download', u'referer': u'https://filejoker.net/06odb4hckkja', u'id': u'06odb4hckkja', u'fname': u'FileJoker.net Premium Account', u'op': u'download1'} | ref=https://filejoker.net/06odb4hckkja | just_header=False
45	11.12.2023 12:27:57	DEBUG	HOSTER FilejokerNet[3619]: Getting download link #2...
46	11.12.2023 12:27:57	INFO	HOSTER FilejokerNet[3619]: Checking for link errors...
47	11.12.2023 12:27:57	INFO	HOSTER FilejokerNet[3619]: No errors found
48	11.12.2023 12:27:58	DEBUG	HOSTER FilejokerNet[3619]: {u'rand': u'bfqutzzp', u'method_premium': '', u'down_direct': u'1', u'referer': '', u'method_free': u'Free Download', u'id': u'06odb4hckkja', u'op': u'download2'}
49	11.12.2023 12:27:58	DEBUG	HOSTER FilejokerNet[3619]: WAIT set to timestamp 1702294199.191293 | Previous waitUntil: 0.000000
50	11.12.2023 12:27:58	DEBUG	CAPTCHA FilejokerNet[3619]: ReCaptcha | d1d53ad768bbEskdfm32Mal | Wrong key format, this probably because is is not a reCAPTCHA key
51	11.12.2023 12:27:58	WARNING	CAPTCHA FilejokerNet[3619]: ReCaptcha | Key pattern not found
52	11.12.2023 12:27:58	DEBUG	CAPTCHA FilejokerNet[3619]: HCaptcha | d1d53ad768bbEskdfm32Mal | Wrong key format, this probably because is is not a hCaptcha key
53	11.12.2023 12:27:58	WARNING	CAPTCHA FilejokerNet[3619]: HCaptcha | Key pattern not found
54	11.12.2023 12:27:58	DEBUG	HOSTER FilejokerNet[3619]: xCaptcha | Challenge xCaptcha
55	11.12.2023 12:27:58	DEBUG	HOSTER FilejokerNet[3619]: LOAD URL https://filejoker.net/xcaptcha/api.js | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
56	11.12.2023 12:27:58	DEBUG	HOSTER FilejokerNet[3619]: LOAD URL https://filejoker.net/xcaptcha/i/f6bb95196186/d860E.png | redirect=True | cookies=True | get={} | req=None | decode=False | multipart=False | post={} | ref=https://filejoker.net/06odb4hckkja | just_header=False
57	11.12.2023 12:27:59	WARNING	Download failed: FileJoker.net Premium Account | cannot identify image file
58	? 	?	Traceback (most recent call last):
59	? 	?	File "/usr/share/pyload/module/PluginThread.py", line 189, in run
60	? 	?	pyfile.plugin.preprocessing(self)
61	? 	?	File "/usr/share/pyload/module/plugins/internal/Base.py", line 290, in preprocessing
62	? 	?	return self._process(*args, **kwargs)
63	? 	?	File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 118, in _process
64	? 	?	self.process(self.pyfile)
65	? 	?	File "/usr/share/pyload/module/plugins/internal/SimpleHoster.py", line 281, in process
66	? 	?	self.handle_free(pyfile)
67	? 	?	File "/usr/share/pyload/module/plugins/internal/XFSHoster.py", line 102, in handle_free
68	? 	?	post=self._post_parameters(),
69	? 	?	File "/usr/share/pyload/module/plugins/internal/XFSHoster.py", line 208, in _post_parameters
70	? 	?	self.handle_captcha(inputs)
71	? 	?	File "/home/akfedux/.pyload/userplugins/hoster/FilejokerNet.py", line 277, in handle_captcha
72	? 	?	response = xcaptcha.challenge()
73	? 	?	File "/home/akfedux/.pyload/userplugins/hoster/FilejokerNet.py", line 201, in challenge
74	? 	?	img = self._prepare_image(tiles, tiles_layout, example_text, example_pic)
75	? 	?	File "/home/akfedux/.pyload/userplugins/hoster/FilejokerNet.py", line 54, in _prepare_image
76	? 	?	challenge_image = self._load_image(challenge_image_url)
77	? 	?	File "/home/akfedux/.pyload/userplugins/hoster/FilejokerNet.py", line 42, in _load_image
78	? 	?	img = Image.open(s)
79	? 	?	File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1980, in open
80	? 	?	raise IOError("cannot identify image file")
81	? 	?	IOError: cannot identify image file
82	11.12.2023 12:28:01	INFO	Debug Report written to debug_FilejokerNet_11-12-2023_12-27-59.zip
83	11.12.2023 12:28:01	DEBUG	All downloads processed

**Comment by GammaC0de** [comment]
Is this a premium download?
If yea then account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by akfedux** [comment]
No.

**Comment by GammaC0de** [comment]
Use the develop tag: https://docs.linuxserver.io/images/docker-pyload-ng/
