### ISSUE TITLE
`imp` module is deprecated as of Python 3.12 - unable to launch pyload

### ISSUE THREAD

**Issue by mihawk90** [pyload/pyload#4416]
### Description
Ran into an issue of being unable to launch pyload on Fedora 39. Turns out the `imp` module is deprecated and is therefore not installed anymore.

### Debug log

```
 ~/Development/pyload   develop ±  python3.12 -m pyload
ModuleNotFoundError: No module named 'imp'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/tarulia/.local/lib/python3.12/site-packages/pyload/__main__.py", line 12, in <module>
    from .core import Core
  File "/home/tarulia/.local/lib/python3.12/site-packages/pyload/core/__init__.py", line 26, in <module>
    from .utils import format, fs
  File "/home/tarulia/.local/lib/python3.12/site-packages/pyload/core/utils/format.py", line 8, in <module>
    from .check import is_iterable
  File "/home/tarulia/.local/lib/python3.12/site-packages/pyload/core/utils/check.py", line 3, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

### Additional references
See [python Docs](https://docs.python.org/3.11/library/imp.html?highlight=imp#:~:text=Deprecated%20since%20version%203.4%2C%20will%20be%20removed%20in%20version%203.12)

On python3.11 I'm getting `No module named 'six'` instead, but that seems to be a me-issue that I still need to figure out.

**Comment by GammaC0de** [comment]
This is not the only issue with 3.12 - Js2py is not compatible with 3.12 yet.
