### ISSUE TITLE
Gofile stopped working

### ISSUE THREAD

**Issue by clst** [pyload/pyload#4453]
### Description

gofile.io plugin stopped working

Test Link: https://gofile.io/d/WO8biU

### Debug log

```
23.04.2024 22:06:13 | INFO | Decrypting starts: WO8biU
-- | -- | --
163 | 23.04.2024 22:06:13 | DEBUG | CRYPTER GofileIoFolder[26]: Plugin version: 0.03
164 | 23.04.2024 22:06:13 | DEBUG | CRYPTER GofileIoFolder[26]: Plugin status: testing
165 | 23.04.2024 22:06:13 | WARNING | CRYPTER GofileIoFolder[26]: Plugin may be unstable
166 | 23.04.2024 22:06:13 | INFO | CRYPTER GofileIoFolder[26]: Grabbing link info...
167 | 23.04.2024 22:06:13 | DEBUG | CRYPTER GofileIoFolder[26]: Link info: {'status': 7, 'hash': {},  'name': u'WO8biU', 'url': u'https://gofile.io/d/WO8biU', 'pattern':  {'ID': u'WO8biU'}, 'size': 0}
168 | 23.04.2024 22:06:13 | DEBUG | CRYPTER GofileIoFolder[26]: Previous link info: {}
169 | 23.04.2024 22:06:13 | INFO | CRYPTER GofileIoFolder[26]: Link name: WO8biU
170 | 23.04.2024 22:06:13 | INFO | CRYPTER GofileIoFolder[26]: Link size: N/D
171 | 23.04.2024 22:06:13 | INFO | CRYPTER GofileIoFolder[26]: Link status: starting
172 | 23.04.2024 22:06:13 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
173 | 23.04.2024 22:06:13 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
174 | 23.04.2024 22:06:13 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
175 | 23.04.2024 22:06:13 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/115.0`
176 | 23.04.2024 22:06:13 | INFO | CRYPTER GofileIoFolder[26]: Processing url: https://gofile.io/d/WO8biU
177 | 23.04.2024 22:06:13 | DEBUG | CRYPTER GofileIoFolder[26]: LOAD URL https://api.gofile.io/accounts \|  redirect=True \| cookies=True \| get={} \| req=None \| decode=True \|  multipart=False \| post=True \| ref=True \| just_header=False
178 | 23.04.2024 22:06:13 | ERROR | Decrypting failed: WO8biU \| 'bool' object is not iterable
179 | 23.04.2024 22:06:13 | DEBUG | Error creating zip file: [Error 3] The system cannot find the path specified: u'tmp\\GofileIoFolder\\*.*'
180 | 23.04.2024 22:06:13 | INFO | Debug Report written to debug_GofileIoFolder_23-04-2024_22-06-13.txt

```
Debug Report:

```
pyLoad 0.4.20 Debug Report of GofileIoFolder 0.03 

TRACEBACK:
 Traceback (most recent call last):
  File "E:\Apps\pyload\dist\.\module\PluginThread.py", line 363, in run
  File "E:\Apps\pyload\data\userplugins\internal\Base.py", line 290, in preprocessing
  File "E:\Apps\pyload\data\userplugins\internal\Base.py", line 280, in _process
  File "E:\Apps\pyload\dist\.\module\plugins\internal\Crypter.py", line 32, in process
  File "E:\Apps\pyload\data\userplugins\crypter\GofileIoFolder.py", line 46, in decrypt
  File "E:\Apps\pyload\data\userplugins\crypter\GofileIoFolder.py", line 39, in api_request
  File "E:\Apps\pyload\data\userplugins\internal\Base.py", line 484, in load
  File "E:\Apps\pyload\data\userplugins\internal\Plugin.py", line 248, in load
  File "E:\Apps\pyload\dist\.\module\network\Browser.py", line 98, in load
  File "E:\Apps\pyload\dist\.\module\network\HTTPRequest.py", line 207, in load
  File "E:\Apps\pyload\dist\.\module\network\HTTPRequest.py", line 186, in setRequestContext
  File "E:\Apps\pyload\dist\.\module\network\HTTPRequest.py", line 34, in myurlencode
TypeError: 'bool' object is not iterable
 

FRAMESTACK:

Frame preprocessing in E:\Apps\pyload\data\userplugins\internal\Base.py at line 290
	                self = <Crypter GofileIoFolder>
	                args = (<DecrypterThread(Thread-24, started daemon 11564)>,)
	              kwargs = {}

Frame _process in E:\Apps\pyload\data\userplugins\internal\Base.py at line 280
	                self = <Crypter GofileIoFolder>
	              thread = <DecrypterThread(Thread-24, started daemon 11564)>

Frame process in E:\Apps\pyload\dist\.\module\plugins\internal\Crypter.py at line 32
	              pyfile = PyFile 26: WO8biU@GofileIoFolder
	                self = <Crypter GofileIoFolder>

Frame decrypt in E:\Apps\pyload\data\userplugins\crypter\GofileIoFolder.py at line 46
	              pyfile = PyFile 26: WO8biU@GofileIoFolder
	                self = <Crypter GofileIoFolder>

Frame api_request in E:\Apps\pyload\data\userplugins\crypter\GofileIoFolder.py at line 41
	                self = <Crypter GofileIoFolder>
	              method = 'accounts'
	                post = True
	               token = None
	                 get = {}

Frame load in E:\Apps\pyload\data\userplugins\internal\Base.py at line 484
	                self = <Crypter GofileIoFolder>
	                args = ('https://api.gofile.io/accounts',)
	              kwargs = {'get': {}, 'post': True}

Frame load in E:\Apps\pyload\data\userplugins\internal\Plugin.py at line 248
	            redirect = True
	            http_req = <module.network.HTTPRequest.HTTPRequest instance at 0x04BC8F58>
	             cookies = True
	                 get = {}
	                 url = u'https://api.gofile.io/accounts'
	                self = <Crypter GofileIoFolder>
	                 req = <module.network.Browser.Browser object at 0x04B78FB8>
	               value = False
	              decode = True
	           multipart = False
	                 key = 'just_header'
	                post = True
	                 ref = True
	         just_header = False

Frame load in E:\Apps\pyload\dist\.\module\network\Browser.py at line 98
	                self = <module.network.Browser.Browser object at 0x04B78FB8>
	                args = (u'https://api.gofile.io/accounts', {}, True, True, True, False, False, True)
	              kwargs = {}

Frame load in E:\Apps\pyload\dist\.\module\network\HTTPRequest.py at line 207
	             cookies = True
	                 get = {}
	                 url = u'https://api.gofile.io/accounts'
	                self = <module.network.HTTPRequest.HTTPRequest instance at 0x04BC8F58>
	              decode = True
	             referer = True
	           multipart = False
	                post = True
	         just_header = False

Frame setRequestContext in E:\Apps\pyload\dist\.\module\network\HTTPRequest.py at line 186
	             cookies = True
	                 get = {}
	                 url = 'https://api.gofile.io/accounts'
	                self = <module.network.HTTPRequest.HTTPRequest instance at 0x04BC8F58>
	             referer = True
	           multipart = False
	                post = True

Frame myurlencode in E:\Apps\pyload\dist\.\module\network\HTTPRequest.py at line 34
	                data = True


PLUGIN OBJECT DUMP: 

	             API_URL = 'https://api.gofile.io/'
	    URL_REPLACEMENTS = [('http://', 'https://')]
	             account = False
	             captcha = <Captcha Captcha>
	           classname = 'GofileIoFolder'
	              config = <userplugins.internal.misc.Config object at 0x04BBAE30>
	                data = ''
	                  db = <userplugins.internal.misc.DB object at 0x04BBAD50>
	                info = {'hash': {},
 'name': u'WO8biU',
 'pattern': {'ID': u'WO8biU'},
 'size': 0,
 'status': 7,
 'url': u'https://gofile.io/d/WO8biU'}
	                  js = <module.common.JsEngine.JsEngine instance at 0x02E827D8>
	         last_header = {}
	           last_html = ''
	               links = []
	             multiDL = True
	            packages = []
	             premium = False
	              pyfile = PyFile 26: WO8biU@GofileIoFolder
	              pyload = <__main__.Core object at 0x028FE0F0>
	                 req = <module.network.Browser.Browser object at 0x04B78FB8>
	             retries = {}
	              thread = <DecrypterThread(Thread-24, started daemon 11564)>
	                user = None
	             waiting = False
	       wantReconnect = False

PYFILE OBJECT DUMP: 

	               _size = 0
	               abort = False
	              active = False
	               error = "'bool' object is not iterable"
	                  id = 26
	                lock = <_RLock owner=None count=0>
	                   m = <module.database.FileDatabase.FileHandler instance at 0x029FA170>
	         maxprogress = 100
	                name = u'WO8biU'
	               order = 0
	           packageid = 28
	              plugin = <Crypter GofileIoFolder>
	         pluginclass = <class 'userplugins.crypter.GofileIoFolder.GofileIoFolder'>
	        pluginmodule = <module 'userplugins.crypter.GofileIoFolder' from 'E:\Apps\pyload\data\userplugins\crypter\GofileIoFolder.pyc'>
	          pluginname = u'GofileIoFolder'
	            progress = 0
	         reconnected = False
	                size = 0
	              status = 8
	          statusname = None
	                 url = u'https://gofile.io/d/WO8biU'
	           waitUntil = 0


CONFIG: 

{'activated': {'desc': 'Activated', 'type': 'bool', 'value': True},
 'desc': 'GofileIoFolder',
 'folder_per_package': {'desc': 'Create folder for each package',
                        'type': 'Default;Yes;No',
                        'value': 'Default'},
 'max_wait': {'desc': 'Reconnect if waiting time is greater than minutes',
              'type': 'int',
              'value': 10},
 'outline': 'Gofile.io decrypter plugin',
 'use_premium': {'desc': 'Use premium account if available',
                 'type': 'bool',
                 'value': False}}

```

**Comment by GammaC0de** [comment]
Works fine here, mabe you have reached the download limit?

**Comment by clst** [comment]
Strange. I just tried again:
![image](https://github.com/pyload/pyload/assets/293237/4fb431df-f746-422d-a32a-a3e5af0bdcdf)

If I download the direct link (from the menu to the right):
![image](https://github.com/pyload/pyload/assets/293237/6f3a3cf2-3272-4946-ac57-ea15255032f7)
Then I get the correct filename with just 10KB of html gofile homepage instead of a zip.

I can download the file fine in my browser.

**Comment by clst** [comment]
If I do the POST with curl manually I get an account back.

I think I found it: https://github.com/pyload/pyload/blob/9376854e794f4c3eaab8fd3cb9025994d359c2c4/src/pyload/plugins/decrypters/GofileIoFolder.py#L52

The plugin sets `post=True`. In HTTPRequest it then does `post = myurlencode(post)` since there is no code for `True`. Weird that it works on your end.

If I set `post='1'` or anything else truthy it works. I don't know where exactly the error is, but since the gofile API doesn't seem to care what you post, it works now.

**Comment by GammaC0de** [comment]
I really don't know why it makes a difference:
https://github.com/pyload/pyload/blob/0947cbd0970d1437da737fd64c8ee70dddf56605/src/pyload/core/network/http/http_request.py#L237-L241

**Comment by clst** [comment]
Oh, that code looked very different in the stable version I am using.

This commit seems to be missing in stable: https://github.com/pyload/pyload/commit/3e2c9985a8e120c59478275f5b7dffac0386b28b

That totally fixes it.

I'll see about upgrading to -ng.

**Comment by GammaC0de** [comment]
> So the problem is 0.4.20 doesn't have it. Is it safe to just pull the stable branch and use that?

You can safely use the updated `stable` branch.

**Comment by clst** [comment]
That almost worked fine. Copying stable over pyload/dist has broken py2exe (and the tray icons).

I can live with that and just use my system python now.
