### ISSUE TITLE
403 Forbidden error on 1fichier (premium account)

### ISSUE THREAD

**Issue by DrekoDev** [pyload/pyload#4455]
### Description

Hello everyone, that issue came back again https://github.com/pyload/pyload/issues/4371

I still got a 403 Forbidden Error response when I try to download a file using a premium account on 1fichier.com

### Debug log

<head></head>
47 | 30.04.2024 10:37:24 | DEBUG | HOSTER OneFichierCom[438]: LOAD URL https://1fichier.com/?nlfy9f7mngwsr4jrl9ch \| redirect=False \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
-- | -- | -- | --
48 | 30.04.2024 10:37:24 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
49 | 30.04.2024 10:37:24 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
50 | 30.04.2024 10:37:24 | WARNING | Download failed: nlfy9f7mngwsr4jrl9ch \| Bad server response: 403 Forbidden
51 | ? | ? | Traceback (most recent call last):
52 | ? | ? | File "/app/pyload/module/PluginThread.py", line 189, in run
53 | ? | ? | pyfile.plugin.preprocessing(self)
54 | ? | ? | File "/config/userplugins/internal/Base.py", line 290, in preprocessing
55 | ? | ? | return self._process(*args, **kwargs)
56 | ? | ? | File "/config/userplugins/internal/Hoster.py", line 118, in _process
57 | ? | ? | self.process(self.pyfile)
58 | ? | ? | File "/config/userplugins/internal/SimpleHoster.py", line 257, in process
59 | ? | ? | self.handle_direct(pyfile)
60 | ? | ? | File "/config/userplugins/internal/SimpleHoster.py", line 439, in handle_direct
61 | ? | ? | link = self.isresource(pyfile.url)
62 | ? | ? | File "/config/userplugins/internal/Hoster.py", line 177, in isresource
63 | ? | ? | header = self.load(url, just_header=True, redirect=False)
64 | ? | ? | File "/config/userplugins/internal/Base.py", line 484, in load
65 | ? | ? | return Plugin.load(self, *args, **kwargs)
66 | ? | ? | File "/config/userplugins/internal/Plugin.py", line 248, in load
67 | ? | ? | decode is True)
68 | ? | ? | File "/app/pyload/module/network/Browser.py", line 98, in load
69 | ? | ? | return self.http.load(*args, **kwargs)
70 | ? | ? | File "/app/pyload/module/network/HTTPRequest.py", line 270, in load
71 | ? | ? | self.code = self.verifyHeader()
72 | ? | ? | File "/app/pyload/module/network/HTTPRequest.py", line 286, in verifyHeader
73 | ? | ? | raise BadHeader(code, self.header, self.getResponse())
74 | ? | ? | BadHeader: Bad server response: 403 Forbidden
75 | 30.04.2024 10:37:24 | INFO | Debug Report written to debug_OneFichierCom_30-04-2024_10-37-24.zip
76 | 30.04.2024 10:37:24 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
77 | 30.04.2024 10:37:24 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: nlfy9f7mngwsr4jrl9ch (pid:131)
78 | 30.04.2024 10:37:24 | INFO | ADDON UnSkipOnFail: No duplicates found
79 | 30.04.2024 10:37:24 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
80 | 30.04.2024 10:37:24 | DEBUG | All downloads processed

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by DrekoDev** [comment]
I’ve just sent it to your email ! Thanks for you work

**Comment by GammaC0de** [comment]
It seems to work fine for me..
