### ISSUE TITLE
Seems DebridlinkFr  related, stuck at "DEBUG pyload.webui  'id'"

### ISSUE THREAD

**Issue by MikealSouth** [pyload/pyload#4474]
### Description
My pyload 0.5.0 (installed via pip3 on ubuntu jammy) is starting but whenever I want to start/resume/delete a download that has anything to do with DebridlinkFr I get the error message  "Failed" in the WebGui.
I am not really sure what I am doing wrong, I've already deleted my ~/.pyload/ directory.

### Debug log$ pyload
[2024-05-30 02:07:53]  INFO                pyload  *** Welcome to pyLoad 0.5.0 ***
[2024-05-30 02:07:53]  DEBUG               pyload  Indexing plugins...
[2024-05-30 02:07:54]  INFO                pyload  Activated addons: ClickNLoad, ExternalScripts, TORRENT, UnSkipOnFail, UserAgentSwitcher
[2024-05-30 02:07:54]  INFO                pyload  Deactivate addons: AndroidPhoneNotify, AntiCaptcha, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, UpdateManager, WindowsPhoneNotify, XFileSharing, XMPP
[2024-05-30 02:07:54]  DEBUG               pyload  Starting core...
[2024-05-30 02:07:54]  DEBUG               pyload  Debug level: TRACE
[2024-05-30 02:07:54]  DEBUG               pyload  Setup language...
[2024-05-30 02:07:54]  DEBUG               pyload  Setup permissions...
[2024-05-30 02:07:54]  INFO                pyload  User directory: /home/USERNAME/.pyload
[2024-05-30 02:07:54]  INFO                pyload  Cache directory: /tmp/pyLoad
[2024-05-30 02:07:54]  INFO                pyload  Storage directory: /home/USERNAME/Downloads/pyLoad
[2024-05-30 02:07:54]  INFO                pyload  Storage free space: 928.76 GiB
[2024-05-30 02:07:54]  DEBUG               pyload  Setup network...
[2024-05-30 02:07:54]  INFO                pyload  Activating accounts...
[2024-05-30 02:07:54]  INFO                pyload  ACCOUNT DebridlinkFr: Adding user `sK1*******`...
[2024-05-30 02:07:54]  DEBUG               pyload  ACCOUNT DebridlinkFr: Reached login timeout for user `sK1****`
[2024-05-30 02:07:54]  INFO                pyload  ACCOUNT DebridlinkFr: Login user `sK1****`...
[2024-05-30 02:07:54]  DEBUG               pyload  ACCOUNT DebridlinkFr: LOAD URL https://debrid-link.fr/api/oauth/token | get={} | post={'client_id': 'sK1****', 'refresh_token': '**********', 'grant_type': 'refresh_token'} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2024-05-30 02:07:54]  DEBUG               pyload  ACCOUNT DebridlinkFr: LOAD URL https://debrid-link.fr/api/v2/account/infos | get={} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2024-05-30 02:07:54]  INFO                pyload  ACCOUNT DebridlinkFr: Grabbing account info for user `sK1****`...
[2024-05-30 02:07:54]  DEBUG               pyload  ACCOUNT DebridlinkFr: LOAD URL https://debrid-link.fr/api/v2/account/infos | get={} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2024-05-30 02:07:54]  DEBUG               pyload  ACCOUNT DebridlinkFr: Account info for user `sK1****`: {'login': {'password': '**********', 'stats': [1, 0], 'timestamp': 1717027674.2484107, 'valid': True}, 'data': {'login': 'sK1****', 'options': {'limit_dl': ['0']}, 'plugin': <Account DebridlinkFr>, 'premium': True, 'trafficleft': -1, 'type': 'DebridlinkFr', 'validuntil': 1728928855.538659, 'api_token': 'J3K61LIvjOY4W6Q5F0hZh45mmiZIR5lU4UzKyi2jiqi0S4540khE8LseKxx_KWhHVT9iKlqfle2H4n8o-zvNpQ'}}
[2024-05-30 02:07:54]  INFO                pyload  Activating plugins...
[2024-05-30 02:07:54]  WARNING             pyload  ADDON TORRENT: torrents / magnets are not associated with any plugin
[2024-05-30 02:07:54]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `pyload_start`
[2024-05-30 02:07:54]  INFO          pyload.webui  Starting webserver: http://localhost:8000
[2024-05-30 02:07:54]  DEBUG               pyload  *** pyLoad is up and running ***
[2024-05-30 02:07:55]  DEBUG               pyload  ACCOUNT DebridlinkFr: LOAD URL https://debrid-link.fr/api/v2/downloader/hostnames | get={} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2024-05-30 02:07:55]  DEBUG               pyload  ACCOUNT DebridlinkFr: Downloader list for user `sK1****`: ['academicearth.org', 'acast.com', 'add-anime.net', 'ahctv.com', 'allocine.fr', 'alphaporno.com', 'alterupload.com', 'animalist.com', 'animalplanet.com', 'animestigma.com', 'anysex.com', 'aparat.com', 'apkadmin.com', 'arte.tv', 'audi-mediacenter.com', 'audioboom.com', 'audiomack.com', 'beeg.com', 'camdemy.com', 'chilloutzone.net', 'cjoint.net', 'clickndownload.click', 'clickndownload.link', 'clickndownload.org', 'clickndownload.space', 'clicknupload.cc', 'clicknupload.club', 'clicknupload.co', 'clicknupload.download', 'clicknupload.link', 'clicknupload.org', 'clicknupload.space', 'clicknupload.vip', 'clubic.com', 'clyp.it', 'com.au', 'daclips.in', 'dailymail.co.uk', 'dailymotion.com', 'darkibox.com', 'ddownload.com', 'ddownload.com', 'debrid.link', 'democracynow.org', 'depositfiles.com', 'depositfiles.org', 'desfichiers.com', 'destinationamerica.com', 'dfichiers.com', 'dfile.eu', 'discovery.com', 'discoverylife.com', 'dl4free.com', 'dotsub.com', 'drop.download', 'dropapk.to', 'dropbox.com', 'ebaumsworld.com', 'eitb.tv', 'elfile.net', 'elitefile.net', 'ellentube.com', 'ellentv.com', 'emload.com', 'ex-load.com', 'fikper.com', 'file-upload.com', 'file-upload.org', 'file.al', 'fileaxa.com', 'filecat.net', 'filedot.to', 'filedot.xyz', 'filefactory.com', 'filejoker.net', 'fileland.io', 'filenext.com', 'filer.net', 'filesfly.cc', 'filespace.com', 'filestore.me', 'flipagram.com', 'footyroom.com', 'formula1.com', 'fourtube.com', 'foxbusiness.com', 'foxnews.com', 'franceculture.fr', 'free.fr', 'gameinformer.com', 'gamersyde.com', 'gigapeta.com', 'gofile.io', 'goloady.com', 'gorillavid.in', 'hbo.com', 'hellporno.com', 'hitf.cc', 'hitfile.net', 'hornbunny.com', 'hot4share.com', 'hotlink.cc', 'html5-player.libsyn.com', 'hulkshare.com', 'icerbox.com', 'imdb.com', 'instagram.com', 'investigationdiscovery.com', 'isra.cloud', 'itar-tass.com', 'jamendo.com', 'jove.com', 'jumploads.com', 'k2s.cc', 'katfile.com', 'keek.com', 'keep2share.cc', 'keep2share.com', 'keezmovies.com', 'khanacademy.org', 'kickstarter.com', 'krasview.ru', 'kshared.com', 'la7.it', 'lci.fr', 'lcp.fr', 'libsyn.com', 'liveleak.com', 'livestream.com', 'md3b0j6hj.com', 'mdy48tn97.com', 'mediafile.cc', 'mediafire.com', 'mega.co.nz', 'mega.nz', 'megadl.fr', 'megadl.org', 'mesfichiers.fr', 'mesfichiers.org', 'metacritic.com', 'mexa.sh', 'mexashare.com', 'mgoon.com', 'mixcloud.com', 'mixdrop.ag', 'mixdrop.cfd', 'mixdrop.club', 'mixdrop.co', 'mixdrop.nu', 'mixdrop.si', 'mixdrop.sx', 'mixdrop.to', 'mixdrop.vc', 'modsbase.com', 'mojvideo.com', 'movieclips.com', 'movpod.in', 'mozilla.org', 'musicplayon.com', 'mx-sh.net', 'myspass.de', 'myvidster.com', 'nelion.me', 'nitro.download', 'nitroflare.com', 'odatv.com', 'onefichier.com', 'onionstudios.com', 'opvid.online', 'opvid.org', 'ora.tv', 'pcloud.link', 'piecejointe.net', 'pixeldrain.com', 'pjointe.com', 'play.fm', 'plays.tv', 'playvid.com', 'pornhd.com', 'pornhub.com', 'prefiles.com', 'pyvideo.org', 'rapidgator.asia', 'rapidgator.net', 'redtube.com', 'reverbnation.com', 'revision3.com', 'rts.ch', 'rtve.es', 'salefiles.com', 'sapo.ao', 'sapo.cv', 'sapo.mz', 'sapo.pt', 'sapo.tl', 'sciencechannel.com', 'screencast.com', 'scribd.com', 'seeker.com', 'sendspace.com', 'sharemods.com', 'skysports.com', 'slutload.com', 'soundcloud.com', 'soundgasm.net', 'steamcommunity.com', 'steampowered.com', 'stream.cz', 'streamable.com', 'streamcloud.eu', 'streamtape.com', 'streamtape.net', 'subyshare.com', 'sunporno.com', 'supervideo.tv', 'tass.ru', 'teachertube.com', 'teamcoco.com', 'ted.com', 'tenvoi.com', 'terabox.app', 'terabox.com', 'terabytez.org', 'tezfiles.com', 'tfo.org', 'thescene.com', 'thesixtyone.com', 'tlc.com', 'tnaflix.com', 'trbbt.net', 'trubobit.com', 'trutv.com', 'turb.cc', 'turb.pw', 'turb.to', 'turbabit.com', 'turbo.cc', 'turbo.fr', 'turbo.to', 'turbobit.cc', 'turbobit.live', 'turbobit.net', 'turbobit.online', 'turbobit.pw', 'turbobit.ru', 'turboblt.co', 'turboget.net', 'tweakers.net', 'ubiqfile.com', 'unsafespeech.com', 'uploadrar.com', 'upvid.biz', 'upvid.cloud', 'upvid.co', 'upvid.host', 'upvid.live', 'upvid.pro', 'uqload.co', 'uqload.com', 'uqload.io', 'uqload.to', 'usersdrive.com', 'ustream.tv', 'vbox7.com', 'veehd.com', 'velocity.com', 'veoh.com', 'vid.me', 'videodetective.com', 'videzz.net', 'vidoza.net', 'vimeo.com', 'vimeopro.com', 'wat.tv', 'wayshare.cc', 'wdupload.com', 'wimp.com', 'workupload.com', 'world-files.com', 'worldbytez.com', 'wupfile.com', 'xtube.com', 'yahoo.com', 'yodbox.com', 'youdbox.com', 'youporn.com', 'youtu.be', 'youtube.com']
[2024-05-30 02:07:55]  DEBUG               pyload  ACCOUNT DebridlinkFr: Overwritten downloaders: DailymotionCom, DdownloadCom, DepositfilesCom, DropDownload, DropboxCom, FikperCom, FileAl, FilefactoryCom, FilejokerNet, FilerNet, FileuploadCom, GigapetaCom, GofileIo, HitfileNet, HotlinkCc, KatfileCom, Keep2ShareCc, MediafireCom, MegaCoNz, MexaSh, NitroflareCom, OneFichierCom, PixeldrainCom, PornhubCom, RapidgatorNet, RedtubeCom, SendspaceCom, SoundcloudCom, StreamCz, StreamcloudEu, TurbobitNet, VeehdCom, VeohCom, VimeoCom, WorkuploadCom, WorldbytezCom, YoupornCom, YoutubeCom
[2024-05-30 02:07:55]  DEBUG               pyload  ACCOUNT DebridlinkFr: New downloaders: academicearth.org, acast.com, add-anime.net, ahctv.com, allocine.fr, alphaporno.com, alterupload.com, animalist.com, animalplanet.com, animestigma.com, anysex.com, aparat.com, apkadmin.com, arte.tv, audi-mediacenter.com, audioboom.com, audiomack.com, beeg.com, camdemy.com, chilloutzone.net, cjoint.net, clickndownload.click, clickndownload.link, clickndownload.org, clickndownload.space, clicknupload.cc, clicknupload.club, clicknupload.co, clicknupload.download, clicknupload.link, clicknupload.org, clicknupload.space, clicknupload.vip, clubic.com, clyp.it, com.au, daclips.in, dailymail.co.uk, darkibox.com, debrid.link, democracynow.org, depositfiles.org, desfichiers.com, destinationamerica.com, dfichiers.com, dfile.eu, discovery.com, discoverylife.com, dl4free.com, dotsub.com, dropapk.to, ebaumsworld.com, eitb.tv, elfile.net, elitefile.net, ellentube.com, ellentv.com, emload.com, ex-load.com, file-upload.org, fileaxa.com, filecat.net, filedot.to, filedot.xyz, fileland.io, filenext.com, filesfly.cc, filespace.com, filestore.me, flipagram.com, footyroom.com, formula1.com, fourtube.com, foxbusiness.com, foxnews.com, franceculture.fr, free.fr, gameinformer.com, gamersyde.com, goloady.com, gorillavid.in, hbo.com, hellporno.com, hitf.cc, hornbunny.com, hot4share.com, html5-player.libsyn.com, hulkshare.com, icerbox.com, imdb.com, instagram.com, investigationdiscovery.com, isra.cloud, itar-tass.com, jamendo.com, jove.com, jumploads.com, k2s.cc, keek.com, keep2share.com, keezmovies.com, khanacademy.org, kickstarter.com, krasview.ru, kshared.com, la7.it, lci.fr, lcp.fr, libsyn.com, liveleak.com, livestream.com, md3b0j6hj.com, mdy48tn97.com, mediafile.cc, mega.nz, megadl.fr, megadl.org, mesfichiers.fr, mesfichiers.org, metacritic.com, mexashare.com, mgoon.com, mixcloud.com, mixdrop.ag, mixdrop.cfd, mixdrop.club, mixdrop.co, mixdrop.nu, mixdrop.si, mixdrop.sx, mixdrop.to, mixdrop.vc, modsbase.com, mojvideo.com, movieclips.com, movpod.in, mozilla.org, musicplayon.com, mx-sh.net, myspass.de, myvidster.com, nelion.me, nitro.download, odatv.com, onionstudios.com, opvid.online, opvid.org, ora.tv, pcloud.link, piecejointe.net, pjointe.com, play.fm, plays.tv, playvid.com, pornhd.com, prefiles.com, pyvideo.org, rapidgator.asia, reverbnation.com, revision3.com, rts.ch, rtve.es, salefiles.com, sapo.ao, sapo.cv, sapo.mz, sapo.pt, sapo.tl, sciencechannel.com, screencast.com, scribd.com, seeker.com, sharemods.com, skysports.com, slutload.com, soundgasm.net, steamcommunity.com, steampowered.com, streamable.com, streamtape.com, streamtape.net, subyshare.com, sunporno.com, supervideo.tv, tass.ru, teachertube.com, teamcoco.com, ted.com, tenvoi.com, terabox.app, terabox.com, terabytez.org, tezfiles.com, tfo.org, thescene.com, thesixtyone.com, tlc.com, tnaflix.com, trbbt.net, trubobit.com, trutv.com, turb.cc, turb.pw, turb.to, turbabit.com, turbo.cc, turbo.fr, turbo.to, turbobit.cc, turbobit.live, turbobit.online, turbobit.pw, turbobit.ru, turboblt.co, turboget.net, tweakers.net, ubiqfile.com, unsafespeech.com, uploadrar.com, upvid.biz, upvid.cloud, upvid.co, upvid.host, upvid.live, upvid.pro, uqload.co, uqload.com, uqload.io, uqload.to, usersdrive.com, ustream.tv, vbox7.com, velocity.com, vid.me, videodetective.com, videzz.net, vidoza.net, vimeopro.com, wat.tv, wayshare.cc, wdupload.com, wimp.com, world-files.com, wupfile.com, xtube.com, yahoo.com, yodbox.com, youdbox.com, youtu.be
[2024-05-30 02:07:55]  DEBUG               pyload  ACCOUNT DebridlinkFr: Pattern: https?://.*\.debrid\.link/.*|.*(?P<DOMAIN>academicearth\.org|acast\.com|add-anime\.net|ahctv\.com|allocine\.fr|alphaporno\.com|alterupload\.com|animalist\.com|animalplanet\.com|animestigma\.com|anysex\.com|aparat\.com|apkadmin\.com|arte\.tv|audi-mediacenter\.com|audioboom\.com|audiomack\.com|beeg\.com|camdemy\.com|chilloutzone\.net|cjoint\.net|clickndownload\.click|clickndownload\.link|clickndownload\.org|clickndownload\.space|clicknupload\.cc|clicknupload\.club|clicknupload\.co|clicknupload\.download|clicknupload\.link|clicknupload\.org|clicknupload\.space|clicknupload\.vip|clubic\.com|clyp\.it|com\.au|daclips\.in|dailymail\.co\.uk|darkibox\.com|debrid\.link|democracynow\.org|depositfiles\.org|desfichiers\.com|destinationamerica\.com|dfichiers\.com|dfile\.eu|discovery\.com|discoverylife\.com|dl4free\.com|dotsub\.com|dropapk\.to|ebaumsworld\.com|eitb\.tv|elfile\.net|elitefile\.net|ellentube\.com|ellentv\.com|emload\.com|ex-load\.com|file-upload\.org|fileaxa\.com|filecat\.net|filedot\.to|filedot\.xyz|fileland\.io|filenext\.com|filesfly\.cc|filespace\.com|filestore\.me|flipagram\.com|footyroom\.com|formula1\.com|fourtube\.com|foxbusiness\.com|foxnews\.com|franceculture\.fr|free\.fr|gameinformer\.com|gamersyde\.com|goloady\.com|gorillavid\.in|hbo\.com|hellporno\.com|hitf\.cc|hornbunny\.com|hot4share\.com|html5-player\.libsyn\.com|hulkshare\.com|icerbox\.com|imdb\.com|instagram\.com|investigationdiscovery\.com|isra\.cloud|itar-tass\.com|jamendo\.com|jove\.com|jumploads\.com|k2s\.cc|keek\.com|keep2share\.com|keezmovies\.com|khanacademy\.org|kickstarter\.com|krasview\.ru|kshared\.com|la7\.it|lci\.fr|lcp\.fr|libsyn\.com|liveleak\.com|livestream\.com|md3b0j6hj\.com|mdy48tn97\.com|mediafile\.cc|mega\.nz|megadl\.fr|megadl\.org|mesfichiers\.fr|mesfichiers\.org|metacritic\.com|mexashare\.com|mgoon\.com|mixcloud\.com|mixdrop\.ag|mixdrop\.cfd|mixdrop\.club|mixdrop\.co|mixdrop\.nu|mixdrop\.si|mixdrop\.sx|mixdrop\.to|mixdrop\.vc|modsbase\.com|mojvideo\.com|movieclips\.com|movpod\.in|mozilla\.org|musicplayon\.com|mx-sh\.net|myspass\.de|myvidster\.com|nelion\.me|nitro\.download|odatv\.com|onionstudios\.com|opvid\.online|opvid\.org|ora\.tv|pcloud\.link|piecejointe\.net|pjointe\.com|play\.fm|plays\.tv|playvid\.com|pornhd\.com|prefiles\.com|pyvideo\.org|rapidgator\.asia|reverbnation\.com|revision3\.com|rts\.ch|rtve\.es|salefiles\.com|sapo\.ao|sapo\.cv|sapo\.mz|sapo\.pt|sapo\.tl|sciencechannel\.com|screencast\.com|scribd\.com|seeker\.com|sharemods\.com|skysports\.com|slutload\.com|soundgasm\.net|steamcommunity\.com|steampowered\.com|streamable\.com|streamtape\.com|streamtape\.net|subyshare\.com|sunporno\.com|supervideo\.tv|tass\.ru|teachertube\.com|teamcoco\.com|ted\.com|tenvoi\.com|terabox\.app|terabox\.com|terabytez\.org|tezfiles\.com|tfo\.org|thescene\.com|thesixtyone\.com|tlc\.com|tnaflix\.com|trbbt\.net|trubobit\.com|trutv\.com|turb\.cc|turb\.pw|turb\.to|turbabit\.com|turbo\.cc|turbo\.fr|turbo\.to|turbobit\.cc|turbobit\.live|turbobit\.online|turbobit\.pw|turbobit\.ru|turboblt\.co|turboget\.net|tweakers\.net|ubiqfile\.com|unsafespeech\.com|uploadrar\.com|upvid\.biz|upvid\.cloud|upvid\.co|upvid\.host|upvid\.live|upvid\.pro|uqload\.co|uqload\.com|uqload\.io|uqload\.to|usersdrive\.com|ustream\.tv|vbox7\.com|velocity\.com|vid\.me|videodetective\.com|videzz\.net|vidoza\.net|vimeopro\.com|wat\.tv|wayshare\.cc|wdupload\.com|wimp\.com|world-files\.com|wupfile\.com|xtube\.com|yahoo\.com|yodbox\.com|youdbox\.com|youtu\.be).*
[2024-05-30 02:07:59]  DEBUG               pyload  ADDON ClickNLoad: Backend found on http://127.0.0.1:8000
[2024-05-30 02:07:59]  INFO                pyload  ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
[2024-05-30 02:09:36]  DEBUG         pyload.webui  'id'
Traceback (most recent call last):
  File "/home/USERNAME/.local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/USERNAME/.local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/USERNAME/.local/lib/python3.10/site-packages/pyload/webui/app/blueprints/api_blueprint.py", line 36, in rpc
    s = set_session(user_info)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/pyload/webui/app/helpers.py", line 151, in set_session
    "id": user_info["id"],
KeyError: 'id'

### Additional references
I can't really thing of anything that could be helpful.
I only have a DebridlinkFr account loaded.

**Comment by GammaC0de** [comment]
Does your pyLoad instance publicly available from the internet?
it seems that someone is unsuccessfully trying to login to the `/api/` endpoint, maybe trying to brute force..

**Comment by MikealSouth** [comment]
> Does your pyLoad instance publicly available from the internet? it seems that someone is unsuccessfully trying to login to the `/api/` endpoint, maybe trying to brute force..

It is publicly available but it's protected by HTTP Basic Authentication
`$ curl -iLv https://load.EXAMPLE.NET/api/
* Host load.EXAMPLE.NET:443 was resolved.
* IPv6: (none)
* IPv4: 000.000.000.000
*   Trying 000.000.000.000:443...
* Connected to load.EXAMPLE.NET (000.000.000.000) port 443
* ALPN: curl offers h2,http/1.1
....
> GET /api/ HTTP/2
> Host: load.EXAMPLE.NET
> User-Agent: curl/8.6.0
> Accept: */*
>
< HTTP/2 401
HTTP/2 401
< server: nginx/1.18.0 (Ubuntu)`

**Comment by GammaC0de** [comment]
> It is publicly available but it's protected by HTTP Basic Authentication

What do you mean by that? please explain..

The log `KeyError: 'id'` is a result of a bug (now fixed with https://github.com/pyload/pyload/commit/3b26b51b6a3ad71e87d581508bc807be3caaf470) that is caused when someone fetches the `/api/` with non-existing user (e.g. brute-force).
So for sure pyLoad DOES receive  the faulty `/api/` call.
