### ISSUE TITLE
download fails when filename encoding is not utf8

### ISSUE THREAD

**Issue by milahu** [pyload/pyload#4483]
pyload version 0.5.0b3.dev82 9376854e794f4c3eaab8fd3cb9025994d359c2c4

example url

```
https://ddownload.com/gi6q8r5bo9el
```

example filename

```
Nassim Nicholas Taleb - Der Schwarze Schwan (Ungek�rzt).rar
```

```
>>> "ü".encode("latin1").decode("utf8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 0: invalid start byte
```

but this works

```
>>> open("ü".encode("latin1"), "w").write("ok")
>>> import os
>>> os.listdir()
['\udcfc']
>>> "ü".encode("latin1")
b'\xfc'
```

`'\udcfc'` is an unicode surrogate escape for `b'\xfc'`

see also
https://docs.python.org/3/howto/unicode.html#files-in-an-unknown-encoding
https://peps.python.org/pep-0383/
https://vstinner.github.io/pep-383.html

### cheap solution: keep the original encoding

```diff
-  obj.decode(encoding, errors)
+  obj.decode(encoding, errors="surrogateescape")
```

```
>>> "ü".encode("latin1").decode("utf8", errors="surrogateescape")
'\udcfc'
```

### better solution: convert to utf8

this is what the chrome browser is doing, so this should be the expected behavior

in python, there are [magic](https://pypi.org/project/magic/), [chardet](https://pypi.org/project/chardet/), [charset_normalizer](https://github.com/jawah/charset_normalizer) to detect encoding

to my surprise, [`charset_normalizer` fails on short inputs](https://github.com/jawah/charset_normalizer/issues/486)...
so i would use `chardet`

```
>>> import charset_normalizer, magic, chardet

>>> chardet.detect("ü".encode("latin1"))["encoding"]
'ISO-8859-1'
>>> list(map(lambda m: m["encoding"], chardet.detect_all("ü".encode("latin1"))))
['ISO-8859-1']

>>> chardet.detect("ungekürzt".encode("latin1"))["encoding"]
'ISO-8859-1'
>>> list(map(lambda m: m["encoding"], chardet.detect_all("ungekürzt".encode("latin1"))))
['ISO-8859-1', 'ISO-8859-9']

>>> magic.detect_from_content("ü".encode("latin1")).encoding
'binary'

>>> magic.detect_from_content("ungekürzt".encode("latin1")).encoding
'iso-8859-1'

>>> list(map(lambda m: m.encoding, charset_normalizer.from_bytes("ü".encode("latin1"))._results))
['cp037', 'cp1006', 'cp1026', 'cp1250', 'cp1251', 'cp1253', 'cp273', 'cp437', 'cp775', 'cp852', 'cp855', 'cp864', 'cp869', 'cp875', 'iso8859_5', 'koi8_r', 'mac_greek', 'mac_latin2']
>>> list(map(lambda m: m.encoding, charset_normalizer.from_bytes("ungekürzt".encode("latin1"))._results))
['big5hkscs', 'gb18030', 'shift_jis_2004', 'cp1006', 'cp1125', 'cp1250', 'cp1251', 'cp1253', 'cp437', 'cp775', 'cp864', 'cp869', 'cp875', 'hp_roman8', 'iso8859_5', 'mac_greek', 'mac_iceland']
```

### debug log

```
[2024-06-10 19:42:58]  DEBUG               pyload  DOWNLOADER DdownloadCom[1754]: LOAD URL https://ddownload.com/asdf | get={} | post=asdf | ref=https://ddownload.com/asdf | cookies=True | just_header=False | decode=True | multipart=False | redirect=False | req=None

Traceback (most recent call last):
  File "/lib/python3.11/site-packages/pyload/core/threads/download_thread.py", line 55, in run
    pyfile.plugin.preprocessing(self)
  File "/lib/python3.11/site-packages/pyload/plugins/base/hoster.py", line 291, in preprocessing
    return self._process(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pyload/plugins/base/downloader.py", line 103, in _process
    self.process(self.pyfile)
  File "/lib/python3.11/site-packages/pyload/plugins/base/simple_downloader.py", line 282, in process
    self.handle_free(pyfile)
  File "/lib/python3.11/site-packages/pyload/plugins/base/xfs_downloader.py", line 111, in handle_free
    self.data = self.load(
                ^^^^^^^^^^
  File "/lib/python3.11/site-packages/pyload/plugins/base/hoster.py", line 506, in load
    return super().load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pyload/plugins/base/plugin.py", line 254, in load
    header.update(parse_html_header(http_req.response_header))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pyload/plugins/helpers.py", line 440, in parse_html_header
    header = to_str(header)
             ^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pyload/core/utils/convert.py", line 82, in to_str
    return obj.decode(encoding, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 251: invalid start byte

[2024-06-10 19:42:58]  WARNING             pyload  Download failed: asdf (Ungek�rzt).rar | 'utf-8' codec can't decode byte 0xfc in position 251: invalid start byte
```

similar issue #4290

**Comment by milahu** [comment]
cd3a5cce92c047cf3dbc9a406564843edd5cd40c

```diff
 def parse_html_header(header):
-    header = to_str(header)
+    header = to_str(header, encoding="iso-8859-1")
```

first i was shocked, but this is correct

https://stackoverflow.com/questions/4400678/what-character-encoding-should-i-use-for-a-http-header

> Historically, HTTP has allowed field content with text in the ISO-8859-1 charset [ISO-8859-1], supporting other charsets only through use of [RFC2047] encoding. In practice, most HTTP header field values use only a subset of the US-ASCII charset [USASCII]. Newly defined header fields SHOULD limit their field values to US-ASCII octets. A recipient SHOULD treat other octets in field content (obs-text) as opaque data.

also [http.client](https://github.com/python/cpython/raw/3.12/Lib/http/client.py) uses iso-8859-1 to decode http headers

```py
def _parse_header_lines(header_lines, _class=HTTPMessage):
    hstring = b''.join(header_lines).decode('iso-8859-1')
    return email.parser.Parser(_class=_class).parsestr(hstring)
```

---

src/pyload/plugins/helpers.py

```py
def parse_html_header(header):
    header = to_str(header)

    hdict = {}
    _re = r"[ ]*(?P<key>.+?)[ ]*:[ ]*(?P<value>.+?)[ ]*\r?\n"
```

parsing http headers with regex is ugly... `email.parser.Parser` would be better

decoding actual utf8 in http headers like `test-rfc2047: =?UTF-8?Q?=E2=9C=B0?=`
would require [email.header.decode_header](https://stackoverflow.com/questions/7331351/python-email-header-decoding-utf-8)

<details>

```py
#!/usr/bin/env python3

import email
import http.client

# html != http ...
#def parse_html_header(header):
def parse_http_headers(header_bytes):

    # https://stackoverflow.com/a/52418392/10440128

    '''
    # see also "def _read_status" in
    # https://github.com/python/cpython/raw/3.12/Lib/http/client.py
    redirects = []
    while True:
        header, body = header_bytes.split(b"\r\n\r\n", 1)
        if body[:4] == b"HTTP": # TODO verify false positives
            redirects.append(header)
            header_bytes = body
        else:
            break
    '''

    # read one line for HTTP/2 STATUSCODE MESSAGE
    requestline, header_bytes = header_bytes.split(b"\r\n", 1)

    parser = email.parser.Parser(_class=http.client.HTTPMessage)
    headers = parser.parsestr(header_bytes.decode('iso-8859-1'))

    hdict = {}

    for key, value in headers.items():
        key = key.lower()
        if key in hdict:
            current_value = hdict.get(key)
            if isinstance(current_value, list):
                current_value.append(value)
            else:
                hdict[key] = [current_value, value]
        else:
            hdict[key] = value

    return hdict



header_bytes = (
    b'HTTP/2 302 \r\n'
    b'server: ddos-guard\r\n'
    b'server: ddos-guard 2\r\n'
    b'server: ddos-guard 3\r\n'
    b'date: Mon, 10 Jun 2024 17:42:58 GMT\r\n'
    # https://stackoverflow.com/questions/4400678/what-character-encoding-should-i-use-for-a-http-header
    b'test-rfc2047: =?UTF-8?Q?=E2=9C=B0?=\r\n'
    b'content-length: 0\r\n'
    b'location: https://www857.ucdn.to:183/d/xxx/yyy (Ungek\xfcrzt).rar\r\n'
    b'access-control-allow-origin: *\r\n'
    b'access-control-allow-headers: X-Requested-With\r\n'
    b'access-control-allow-methods: GET,POST,OPTIONS\r\n'
    b'\r\n'
)

headers = parse_http_headers(header_bytes)

"""
print("headers", repr(headers))
print("headers", dir(headers))
print("headers", headers.items())
"""

for key in headers:
    print("header", key, headers[key])

assert headers["location"] == "https://www857.ucdn.to:183/d/xxx/yyy (Ungekürzt).rar"
```
