### ISSUE TITLE
Exception in Mega.nz Download

### ISSUE THREAD

**Issue by labs-blueliv** [pyload/pyload#4522]
### Description

There's some times when downloading files from mega.nz the download fails with the following message:  (18, 'transfer closed with XXX bytes remaining to read')

### Debug log

```
[2024-10-21 14:30:17]  INFO                pyload  DOWNLOADER MegaCoNz[190]: Processing url: https://mega.co.nz/folder/xxxxxx
Traceback (most recent call last):
[2024-10-21 14:34:20]  WARNING             pyload  Download failed: xxxxx xxxxxxx.crypted | (18, 'transfer closed with xxx bytes remaining to read')
  File "/usr/local/lib/python3.11/site-packages/pyload/core/threads/download_thread.py", line 55, in run
    pyfile.plugin.preprocessing(self)
  File "/usr/local/lib/python3.11/site-packages/pyload/plugins/base/hoster.py", line 291, in preprocessing
    return self._process(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyload/plugins/base/downloader.py", line 103, in _process
    self.process(self.pyfile)
  File "/usr/local/lib/python3.11/site-packages/pyload/plugins/downloaders/MegaCoNz.py", line 524, in process
    self.download(res["g"], disposition=False)
  File "/usr/local/lib/python3.11/site-packages/pyload/plugins/base/downloader.py", line 335, in download
    newname = self._download(
              ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyload/plugins/base/downloader.py", line 240, in _download
    newname = self.req.http_download(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyload/core/network/browser.py", line 116, in http_download
    name = self.dl.download(chunks, resume)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyload/core/network/http/http_download.py", line 134, in download
    self._download(chunks, resume)
  File "/usr/local/lib/python3.11/site-packages/pyload/core/network/http/http_download.py", line 280, in _download
    raise ex or Exception
pycurl.error: (18, 'transfer closed with xxx bytes remaining to read')
```

**Comment by GammaC0de** [comment]
Works fine for me,
Can you share the url?
Are you behind a proxy/vpn?
