### ISSUE TITLE
files page: UnicodeEncodeError: 'utf-8' codec can't encode character ... surrogates not allowed

### ISSUE THREAD

**Issue by milahu** [pyload/pyload#4523]
the `files` page throws on non-utf8 filenames

<details>
<summary>
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcdf' in position 10887: surrogates not allowed
</summary>

```
127.0.0.1 - - [23/Oct/2024 18:04:58] "GET /files HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/nix/store/qpjwyk7lafwwckpkqwwpi797j7n3afbi-python3-3.11.9-env/lib/python3.11/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qpjwyk7lafwwckpkqwwpi797j7n3afbi-python3-3.11.9-env/lib/python3.11/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qpjwyk7lafwwckpkqwwpi797j7n3afbi-python3-3.11.9-env/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qpjwyk7lafwwckpkqwwpi797j7n3afbi-python3-3.11.9-env/lib/python3.11/site-packages/flask/app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qpjwyk7lafwwckpkqwwpi797j7n3afbi-python3-3.11.9-env/lib/python3.11/site-packages/flask/app.py", line 902, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qpjwyk7lafwwckpkqwwpi797j7n3afbi-python3-3.11.9-env/lib/python3.11/site-packages/flask/app.py", line 1186, in make_response
    rv = self.response_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qpjwyk7lafwwckpkqwwpi797j7n3afbi-python3-3.11.9-env/lib/python3.11/site-packages/werkzeug/wrappers/response.py", line 175, in __init__
    self.set_data(response)
  File "/nix/store/qpjwyk7lafwwckpkqwwpi797j7n3afbi-python3-3.11.9-env/lib/python3.11/site-packages/werkzeug/wrappers/response.py", line 297, in set_data
    value = value.encode()
            ^^^^^^^^^^^^^^
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcdf' in position 10887: surrogates not allowed
```

</details>

expected: print non-utf8 bytes as backslash hex escapes
example: `ä` &rarr; `\xe4`

create file with latin1 filename: `'testfile-latin1-'$'\344\366\374'`

```
touch "$(echo testfile-latin1-äöü | iconv -f utf8 -t latin1)"
```

list files with latin1 filenames

```
convmv -r -f latin1 -t utf8 . 2>&1 | grep -a "^mv "
```

autofix files with latin1 filenames
warning: this can produce wrong results

```
convmv --notest -r -f latin1 -t utf8 .
```

**Comment by milahu** [comment]
not fixed by 385cbe4c7a66f960b672d8c128c0e447409d7184

filenames can have any encoding, not just utf8 or latin1 (iso-8859-1)

the latin1 fallback worked in #4483
because latin1 is a (quasi-) standard encoding for http headers

filenames can be random binary strings = no encoding makes sense
todo: [backslash-escape all non-ascii chars in bytestring](https://stackoverflow.com/a/79210969/10440128)

handling filenames requires some encoding detection

- [cchardet](https://pypi.org/project/faust-cchardet/)
  - `import cchardet as chardet; filename_encoding = chardet.detect(filename_bytes).get("encoding")`
  - `chardet.detect(random.randbytes(999)).get("encoding") == None`
- [magic](https://pypi.org/project/python-magic/)
  - `import magic; filename_encoding = magic.detect_from_content(filename_bytes).encoding`
  - fails on short strings: `filename_bytes = "ü".encode("latin1")`
- [pyicu](https://pypi.org/project/PyICU/) ([icu](https://github.com/unicode-org/icu))
  - `import icu; filename_encoding = icu.CharsetDetector(filename_bytes).detect().getName()`
  - fails on short strings: `filename_bytes = "ü".encode("latin1")`
- [rs_chardet](https://pypi.org/project/rs-chardet/) ([chardetng](https://github.com/hsivonen/chardetng)) - 40x slower than cchardet. failed project?
- [charset_normalizer](https://pypi.org/project/charset-normalizer/)
  - `import charset_normalizer; filename_encoding = charset_normalizer.from_bytes(filename_bytes).best().encoding`
  - fails on short strings: `filename_bytes = "ü".encode("latin1")`
