### ISSUE TITLE
Alldebrid plugin issue ? - 'NoneType' object has no attribute 'choose'

### ISSUE THREAD

**Issue by qwrty-ftw** [pyload/pyload#4527]
Hello,

latest pyload-ng installed, I recently add an Alldebrid account, adding the account is working great, but when I tried to add a link, I got an error:

```
11016	2024-11-25 15:53:40	INFO	pyload	Download starts: PDI_cTRlN0sYz1t6tOvAeFKUg_TomeQ9cVmns0BSYbo
11017	2024-11-25 15:53:40	WARNING	pyload	DOWNLOADER AlldebridCom[794]: AlldebridCom | Plugin may be unstable
11018	2024-11-25 15:53:40	WARNING	pyload	Download failed: PDI_cTRlN0sYz1t6tOvAeFKUg_TomeQ9cVmns0BSYbo | 'NoneType' object has no attribute 'choose'
11019	2024-11-25 15:53:40	INFO	pyload	ADDON UnSkipOnFail: Looking for skipped duplicates of: PDI_cTRlN0sYz1t6tOvAeFKUg_TomeQ9cVmns0BSYbo (pid:205)
11020	2024-11-25 15:53:40	INFO	pyload	ADDON UnSkipOnFail: No duplicates found
```

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyload/core/threads/download_thread.py", line 55, in run
    pyfile.plugin.preprocessing(self)
  File "/usr/local/lib/python3.9/dist-packages/pyload/plugins/base/hoster.py", line 291, in preprocessing
    return self._process(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pyload/plugins/base/multi_downloader.py", line 77, in _process
    super()._process(thread)
  File "/usr/local/lib/python3.9/dist-packages/pyload/plugins/base/downloader.py", line 92, in _process
    self._setup()
  File "/usr/local/lib/python3.9/dist-packages/pyload/plugins/base/hoster.py", line 152, in _setup
    self.load_account()  # TODO: Move to PluginThread in 0.6.x
  File "/usr/local/lib/python3.9/dist-packages/pyload/plugins/base/downloader.py", line 84, in load_account
    super().load_account()
  File "/usr/local/lib/python3.9/dist-packages/pyload/plugins/base/hoster.py", line 183, in load_account
    self.account.choose()
  File "/usr/local/lib/python3.9/dist-packages/pyload/core/utils/struct/lock.py", line 22, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pyload/plugins/base/account.py", line 463, in choose
    user = self.select()[0]
  File "/usr/local/lib/python3.9/dist-packages/pyload/core/utils/struct/lock.py", line 22, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pyload/plugins/base/account.py", line 397, in select
    if not self.accounts[user]["plugin"].choose(user):
AttributeError: 'NoneType' object has no attribute 'choose'`

My Python version: 3.9.2

Thank you :)

**Comment by GammaC0de** [comment]
Have you used [GetAlldebridTokenV4](https://github.com/pyload/pyload/files/4489732/GetAlldebridTokenV4.zip) to generate API token?

**Comment by qwrty-ftw** [comment]
I will check this, thank you. 

But I’ve created my API key from their website. Then I add my account in Pyload: user = username and password = apikey. 
login works great from Pyload side (I can see the status and expiration time)
When I put a magnet or torrent file in my black hole in my watch folder Pyload, it works great and get debrid from Alldebrid but the download part is not working (I also tried manually to add a link direct inside Pyload = same)

**Comment by qwrty-ftw** [comment]
Looks like it works... I dont really understand as the APIKEY was the same.
But thank you anyway :D
