### ISSUE TITLE
ModuleNotFoundError: No module named 'cgi' (PyLoad Support for python 3.13)

### ISSUE THREAD

**Issue by Bluey26** [pyload/pyload#4535]
### Description

Python version of archlinux was updated to 3.13( around 4 weeks ago), and now PyLoad does not work anymore, because of the missing package `cgi`.

A quick search showed that this module was removed from python 3.13 (https://stackoverflow.com/questions/79022412/chaquopy-modulenotfounderror-no-module-named-cgi) and thus programs depening on it will likely not work (like PyLoad).

I installed pyload both from pypi (`pip install pyload-ng`) and from the git master branch (`pip install git+https://github.com/pyload/pyload.git`) with the same error result.

~~In case this is not planned or would be done in the close future, i appreciate any workarounds for this (maybe using 3.12 for this package in a `venv`)~~ **UPDATE:** I was able to use the program again by installing a 3.12.7 python version (using `pyenv`) and then, i created a python `virtualenv` (not `venv`) following an [internet guide](https://www.roelpeters.be/virtualenv-venv-choose-python-version/). This seemed to work for me, i add it for other users having the same issue.

### Debug log

```
(pyLoad) [user: pyLoad] $ pyload 
[2024-12-30 10:52:33]  INFO                pyload  *** Welcome to pyLoad 0.5.0 ***
ModuleNotFoundError: No module named 'cgi'
Traceback (most recent call last):
  File "/path_to_pyload_venv/pyLoad/bin/pyload", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/path_to_pyload_venv/pyLoad/lib/python3.13/site-packages/pyload/__main__.py", line 292, in main
    run(core_args, args.daemon, args.pidfile)
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path_to_pyload_venv/pyLoad/lib/python3.13/site-packages/pyload/__main__.py", line 235, in run
    pyload_core = Core(*core_args)
  File "/path_to_pyload_venv/pyLoad/lib/python3.13/site-packages/pyload/core/__init__.py", line 104, in __init__
    self._init_network()
    ~~~~~~~~~~~~~~~~~~^^
  File "/path_to_pyload_venv/pyLoad/lib/python3.13/site-packages/pyload/core/__init__.py", line 170, in _init_network
    from .network import request_factory
  File "/path_to_pyload_venv/pyLoad/lib/python3.13/site-packages/pyload/core/network/request_factory.py", line 6, in <module>
    from .browser import Browser
  File "/path_to_pyload_venv/pyLoad/lib/python3.13/site-packages/pyload/core/network/browser.py", line 7, in <module>
    from .http.http_download import HTTPDownload
  File "/path_to_pyload_venv/pyLoad/lib/python3.13/site-packages/pyload/core/network/http/http_download.py", line 11, in <module>
    from .http_chunk import ChunkInfo, HTTPChunk
  File "/path_to_pyload_venv/pyLoad/lib/python3.13/site-packages/pyload/core/network/http/http_chunk.py", line 8, in <module>
    from cgi import parse_header as parse_header_line
ModuleNotFoundError: No module named 'cgi'


```

### Additional references

https://discuss.python.org/t/cgi-module-replacement/68856

Check the link in the description.

**Comment by GammaC0de** [comment]
I have decided to do a copy-paste of the function from the cgi module into pyLoad since I was not happy the way the email module handle the parsing of Content-Disposition

**Comment by Bluey26** [comment]
Thanks for the fix, i just tried it and it works now.
