### ISSUE TITLE
 Error executing hooks: (7, "couldn't connect to host")

### ISSUE THREAD

**Issue by lordfiSh** [pyload/pyload#89]
There is some bug with the hooksmanager, LinkdecrypterCom.py or something else.

Today Linkdecrypter.Com is down
```python
16.04.2013 18:03:58 INFO      Activating Plugins...
16.04.2013 18:04:19 ERROR     Error executing hooks: (7, "couldn't connect to host")
Traceback (most recent call last):
  File "/volume1/@optware/share/pyload/module/HookManager.py", line 88, in new
    return func(*args)
  File "/volume1/@optware/share/pyload/module/HookManager.py", line 198, in coreReady
    plugin.coreReady()
  File "/volume1/config/pyload/userplugins/hooks/LinkdecrypterCom.py", line 33, in coreReady
    page = getURL("http://linkdecrypter.com/")
  File "/volume1/@optware/share/pyload/module/network/RequestFactory.py", line 122, in getURL
    return pyreq.getURL(*args, **kwargs)
  File "/volume1/@optware/share/pyload/module/network/RequestFactory.py", line 67, in getURL
    rep = h.load(*args, **kwargs)
  File "/volume1/@optware/share/pyload/module/network/HTTPRequest.py", line 202, in load
    self.c.perform()
error: (7, "couldn't connect to host")
16.04.2013 18:04:19 INFO      pyLoad is up and running
16.04.2013 18:04:21 INFO      No Updates for pyLoad
16.04.2013 18:04:21 INFO      No plugin updates available
```
the problem now is that no others hooks are executed. the EpisodeMover hook from rusk_ (http://forum.pyload.org/viewtopic.php?f=9&t=1486)  dont start up. 

Now when i remove the LinkdecrypterCom plugin, it works
```python
16.04.2013 18:05:45 INFO      Activating Plugins...
16.04.2013 18:05:45 DEBUG     XFileSharingPro: Pattern loaded - handling 79 hosters
16.04.2013 18:05:45 DEBUG     EpisodeMover: Initial search on startup activated. Proceeding...
16.04.2013 18:05:45 DEBUG     EpisodeMover: acq_rls_ProcessingLock(): __em_lock acquired
16.04.2013 18:05:45 DEBUG     EpisodeMover: (Re)-Populating local tv database if necessary. Locked meanwhile...
16.04.2013 18:05:46 DEBUG     EpisodeMover: Local show: Grimm | Path to show: /volume3/tv/
16.04.2013 18:05:46 DEBUG     EpisodeMover: Local show: Vikings | Path to show: /volume3/tv/
16.04.2013 18:05:46 DEBUG     EpisodeMover: Local show: American Dad | Path to show: /volume3/tv/
........
16.04.2013 18:14:16 DEBUG     EpisodeMover: doProcessing(): __mv_queue joined
16.04.2013 18:14:16 DEBUG     EpisodeMover: acq_rls_ProcessingLock(): __em_lock released
16.04.2013 18:14:16 INFO      ZeveraCom: Reloading supported hoster list
16.04.2013 18:14:17 DEBUG     Redirected import module.plugins.hoster.ZeveraCom -> userplugins.hoster.ZeveraCom
16.04.2013 18:14:17 DEBUG     ZeveraCom: Overwritten Hosters: BayfilesCom, BitshareCom, CatShareNet, CloudzerNet, CramitIn, CrockoCom, CyberlockerCh, DailymotionCom, DdlstorageCom, EasybytezCom, EgoFilesCom, ExtabitCom, FileApeCom, FilebeerInfo, FilecloudIo, FilefactoryCom, FilejungleCom, FilepostCom, FileserveCom, FilesonicCom, FourSharedCom, FreakshareCom, GigapetaCom, HellshareCz, HotfileCom, JumbofilesCom, KickloadCom, LetitbitNet, LuckyShareNet, MediafireCom, MegasharesCom, MegauploadCom, OneFichierCom, PornhubCom, PutlockerCom, RapidgatorNet, RarefileNet, RedtubeCom, RyushareCom, SendspaceCom, ShragleCom, TusfilesNet, TwoSharedCom, UnibytesCom, UploadStationCom, UploadingCom, UptoboxCom, WuploadCom, X7To, XHamsterCom, XVideosCom, YoupornCom, YoutubeCom, ZippyshareCom
16.04.2013 18:14:17 INFO      ZeveraCom: The following hosters were not overwritten - account exists: netload.in, rapidshare.com, share-online.biz, turbobit.net, uploaded.to
16.04.2013 18:14:17 DEBUG     ZeveraCom: New Hosters: 180upload.com, 1st-files.com, albafile.com, allmyvideos.net, asfile.com, badongo.com, bulletupload.com, cuckshare.com, cum.com, dachix.com, depfile.com, deviantclip.com, dfiles.eu, empflix.com, en.vidivodo.com, epositfiles.com, fiberupload.com, filebox.com, filedefend.com, filedino.com, fileduct.net, fileflyer.com, filehost.ws, filemates.com, filemonster.net, fileparadox.in, filereactor.com, filerio.in, filerose.com, fileserving.com, filesflash.com, filesmonster.com, fileswap.com, filevelocity.com, frozenhippo.com, funny-videos.co.uk, funnyanimalvideos.com, furk.net, gigasize.com, girlfriendvideos.com, girlsandvids.com, greektube.org, henchfile.com, hipfile.com, homemoviestube.com, hotpornshow.com, i-filez.com, isavelink.com, ishare.rediff.com, keezmovies.com, livefile.org, liveleak.com, lumfile.com, madthumbs.com, mediabum.com, mega.co.nz, megaporn.com, megashare.com, metacafe.com, mixturecloud.com, mojvideo.com, movies.askjolene.com, muchshare.com, multiupload.com, oneminuteu.com, oteupload.com, pornrabbit.com, queenshare.com, scribd.com, sextube.com, shareflare.net, sharpfile.com, shufuni.com, slingfile.com, slutload.com, sockshare.com, spankwire.com, uload.to, ultramegabit.com, uploadhero.co, uploadjet.net, userporn.com, videobam.com, vidmax.com, vimeo.com, vip-file.com, xfileshare.eu, xnxx.com, youjizz.com, yousendit.com, yunfile.com, yuvutu.com, ziporn.com, ztod.com
16.04.2013 18:14:17 DEBUG     ZeveraCom: Regexp: http://zevera.com/.*|.*(empflix\.com|uploadhero\.co|hipfile\.com|keezmovies\.com|liveleak\.com|yuvutu\.com|fiberupload\.com|uploadjet\.net|1st-files\.com|epositfiles\.com|allmyvideos\.net|megaporn\.com|sockshare\.com|homemoviestube\.com|userporn\.com|livefile\.org|filebox\.com|yunfile\.com|muchshare\.com|filemonster\.net|movies\.askjolene\.com|hotpornshow\.com|fileflyer\.com|yousendit\.com|shareflare\.net|cum\.com|sharpfile\.com|ishare\.rediff\.com|queenshare\.com|cuckshare\.com|xfileshare\.eu|filedefend\.com|filedino\.com|isavelink\.com|funny-videos\.co\.uk|fileparadox\.in|xnxx\.com|dachix\.com|girlfriendvideos\.com|vidmax\.com|multiupload\.com|filemates\.com|megashare\.com|en\.vidivodo\.com|uload\.to|filerose\.com|henchfile\.com|girlsandvids\.com|mixturecloud\.com|funnyanimalvideos\.com|shufuni\.com|filehost\.ws|sextube\.com|vimeo\.com|fileswap\.com|frozenhippo\.com|ziporn\.com|badongo\.com|fileduct\.net|furk\.net|mojvideo\.com|greektube\.org|oteupload\.com|bulletupload\.com|slutload\.com|madthumbs\.com|oneminuteu\.com|180upload\.com|filesmonster\.com|slingfile\.com|i-filez\.com|metacafe\.com|spankwire\.com|filesflash\.com|mega\.co\.nz|ztod\.com|youjizz\.com|lumfile\.com|scribd\.com|depfile\.com|filerio\.in|vip-file\.com|dfiles\.eu|albafile\.com|filevelocity\.com|ultramegabit\.com|pornrabbit\.com|filereactor\.com|asfile\.com|deviantclip\.com|fileserving\.com|videobam\.com|gigasize\.com|mediabum\.com).*
16.04.2013 18:14:17 INFO      pyLoad is up and running
16.04.2013 18:14:19 INFO      No Updates for pyLoad
16.04.2013 18:14:19 INFO      New version of hook|LinkdecrypterCom : 0.17
16.04.2013 18:14:20 DEBUG     Request reload of plugins: [('hooks', 'LinkdecrypterCom')]
16.04.2013 18:14:20 INFO      *** Plugins have been updated, please restart pyLoad ***

```

So there is maybe somewhere a problem...?

**Comment by vuolter** [comment]
Fixed.
