### ISSUE TITLE
Webinterface HTTP Response 500 after adding OboomCom Premium Account

### ISSUE THREAD

**Issue by mxgross** [pyload/pyload#906]
After adding a account for OboomCom via the webinterface there is following error istead of the list of accounts:

pyLoad - Webinterface

An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(*_args)
File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(_a, *_ka)
File "/usr/share/pyload/module/web/utils.py", line 113, in _view
return func(_args, **kwargs)
File "/usr/share/pyload/module/web/pyload_app.py", line 264, in config
data.trafficleft = formatSize(data.trafficleft \* 1024)
File "/usr/share/pyload/module/utils.py", line 95, in formatSize
return "%.2f %s" % (size, sizes[steps])
IndexError: list index out of range

![pyload](https://cloud.githubusercontent.com/assets/3718449/5116814/9cdcee6c-704d-11e4-9f20-90afc24ac618.jpg)

System: Raspberry Pi with Debian
The premium account connection itself seems to work, but I can't access any account settings anymore e.g. to add a second account...

**Comment by diman82** [comment]
I get the same error (due to special character enforcement in password field.
How to resolve this?
